### ISSUE TITLE
[Bug] SchemaChangeJobV2Test is flaky

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#10071]
### Real behavior (Required)
```
Error Message
expected:<3> but was:<0>
Stacktrace
java.lang.AssertionError: expected:<3> but was:<0>
	at com.starrocks.alter.SchemaChangeJobV2Test.testSchemaChange1(SchemaChangeJobV2Test.java:155)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by decster** [comment]
still flaky, @Astralidea mind take another look?
```
Error Message
expected:<3> but was:<0>
Stacktrace
java.lang.AssertionError: expected:<3> but was:<0>
	at com.starrocks.alter.RollupJobV2Test.testSchemaChange1(RollupJobV2Test.java:162)
Standard Output
2022-08-19 21:06:59 [materialized view_pool-0] WARN  AlterReplicaTask:228 - failed to handle finish alter task: 10068, database 10056 does not exist
2022-08-19 21:06:59 [materialized view_pool-0] WARN  AlterReplicaTask:228 - failed to handle finish alter task: 10070, database 10056 does not exist
2022-08-19 21:06:59 [materialized view_pool-0] WARN  AlterReplicaTask:228 - failed to handle finish alter task: 10072, database 10056 does not exist
```
