### ISSUE TITLE
BE crash : starrocks::RowsetMetaPB::MergeFrom

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#10325]
### Steps to reproduce the behavior (Required)
duplicate/unqiue/aggregate/primary table ddl, dml and dql query execute concurently in stability test env,
BE crash:
```
Core was generated by `/home/disk2/sr/stability_master_01/be-50b527ce-645d-4e6a-bfc6-1e5e231d7cff/lib/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000027ae991 in google::protobuf::internal::InternalMetadata::PtrTag (this=0x8) at /var/local/thirdparty/installed/include/google/protobuf/metadata_lite.h:147
147	/var/local/thirdparty/installed/include/google/protobuf/metadata_lite.h: No such file or directory.
[Current thread is 1 (Thread 0x7fa8ad430700 (LWP 21573))]
(gdb) bt
Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
Python Exception <type 'exceptions.ImportError'> No module named gdb.frames:
#0  0x00000000027ae991 in google::protobuf::internal::InternalMetadata::PtrTag (this=0x8) at /var/local/thirdparty/installed/include/google/protobuf/metadata_lite.h:147
#1  google::protobuf::internal::InternalMetadata::have_unknown_fields (this=0x8) at /var/local/thirdparty/installed/include/google/protobuf/metadata_lite.h:81
#2  google::protobuf::internal::InternalMetadata::MergeFrom<google::protobuf::UnknownFieldSet> (other=..., this=0x1d06e5868)
    at /var/local/thirdparty/installed/include/google/protobuf/metadata_lite.h:120
#3  starrocks::RowsetMetaPB::MergeFrom (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0x1d06e5860, from=...) at /root/starrocks/gensrc/build/gen_cpp/olap_file.pb.cc:2698
#4  0x00000000027af218 in starrocks::RowsetMetaPB::CopyFrom (this=<optimized out>, from=...) at /root/starrocks/gensrc/build/gen_cpp/olap_file.pb.cc:2810
#5  0x0000000001d68457 in starrocks::RowsetMetaPB::operator= (from=..., this=<optimized out>) at /root/starrocks/be/../gensrc/build/gen_cpp/olap_file.pb.h:919
#6  starrocks::RowsetMeta::to_rowset_pb (rs_meta_pb=<optimized out>, this=0x0) at /root/starrocks/be/src/storage/rowset/rowset_meta.h:207
#7  starrocks::TabletMeta::to_meta_pb (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0x480a4a20, tablet_meta_pb=0x7fa8ad42a170) at /root/starrocks/be/src/storage/tablet_meta.cpp:283
#8  0x0000000001d68798 in starrocks::TabletMeta::_save_meta (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0x480a4a20, data_dir=0xa0b1520) at /root/starrocks/be/src/storage/tablet_meta.cpp:144
#9  0x0000000001d68d56 in starrocks::TabletMeta::save_meta (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0x480a4a20, data_dir=0xa0b1520) at /root/starrocks/be/src/storage/tablet_meta.cpp:136
#10 0x0000000001d412ab in starrocks::Tablet::save_meta (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=<optimized out>) at /root/starrocks/be/src/storage/tablet.cpp:122
#11 0x0000000001d59c15 in starrocks::TabletManager::_drop_tablet_unlocked (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0xa1ba000, tablet_id=<optimized out>, flag=starrocks::kMoveFilesToTrash)
    at /root/starrocks/be/src/storage/tablet_manager.cpp:1191
#12 0x0000000001d59efa in starrocks::TabletManager::drop_tablet (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0xa1ba000, tablet_id=58237041, flag=flag@entry=starrocks::kMoveFilesToTrash)
    at /root/starrocks/be/src/storage/tablet_manager.cpp:337
#13 0x0000000002896a3d in starrocks::TaskWorkerPool::_drop_tablet_worker_thread_callback (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
arg_this=0x1e469d10) at /root/starrocks/be/src/storage/storage_engine.h:153
#14 0x00000000060774e0 in std::execute_native_thread_routine (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
__p=0x2cf8a940) at ../../../.././libstdc++-v3/src/c++11/thread.cc:80
#15 0x00007fa996efdea5 in start_thread () from /lib64/libpthread.so.0
Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#16 0x00007fa996518b0d in clone () from /lib64/libc.so.6
(gdb)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+--------------------+
| current_version()  |
+--------------------+
| master release 5cd95e7 |
+--------------------+
1 row in set (0.04 sec)
```

**Comment by yongbingwang** [comment]
branch-2.2
https://github.com/StarRocks/starrocks/pull/10415
