### ISSUE TITLE
[BUG] FE Start failed when replaying insert overwrite jobs

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#10346]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
```java
2022-08-23 15:48:47,693 ERROR (stateChangeExecutor|73) [EditLog.loadJournal():884] Operation Type 10002
java.lang.NullPointerException: null
        at com.starrocks.server.LocalMetastore.replayAddPartition(LocalMetastore.java:1351) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayAddPartition(GlobalStateMgr.java:1794) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:206) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1670) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1628) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.transferToLeader(GlobalStateMgr.java:936) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.access$100(GlobalStateMgr.java:266) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$1.transferToLeader(GlobalStateMgr.java:591) [starrocks-fe.jar:?]
        at com.starrocks.ha.StateChangeExecutor.runOneCycle(StateChangeExecutor.java:86) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - main

**Comment by gengjun-git** [comment]
The reason is the log of drop db is ahead of the log of add partition.
