### ISSUE TITLE
BE core dump after ALTER TABLE statement

### ISSUE THREAD

**Issue by mchades** [StarRocks/starrocks#1034]
### Steps to reproduce the behavior (Required)
1. alter table xxx modify column xxx  (change not null to null)

### Expected behavior (Required)
alter successfully
### Real behavior (Required)
BE start up then core dump soon until FE execute CANCEL ALTER TABLE COLUMN statement
### StarRocks version (Required)
 -  UNKNOWN da4eac8 

I can't repeat it.here is the core dump backtrace.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  starrocks::faststring::append (count=2, src_v=0x27658f6800000000, this=0x1f934188)
    at /root/starrocks/be/src/util/faststring.h:123

warning: Source file is more recent than executable.
123                     *p++ = *src++;
[Current thread is 1 (Thread 0x7fc79312d700 (LWP 549378))]
(gdb) bt
#0  starrocks::faststring::append (count=2, src_v=0x27658f6800000000, this=0x1f934188)
    at /root/starrocks/be/src/util/faststring.h:123
#1  starrocks::segment_v2::NullMapBitshuffleBuilder::add_null_flags (count=2,
    flags=0x27658f6800000000 <error: Cannot access memory at address 0x27658f6800000000>, this=0x1f934180)
    at /root/starrocks/be/src/storage/rowset/segment_v2/column_writer.cpp:130
#2  starrocks::segment_v2::ScalarColumnWriter::append (this=0xe0b7880, data=0x348adf00 "@\334\352\023",
    null_flags=0x27658f6800000000 <error: Cannot access memory at address 0x27658f6800000000>,
    count=<optimized out>, has_null=false)
    at /root/starrocks/be/src/storage/rowset/segment_v2/column_writer.cpp:643
#3  0x0000000002b06c5e in starrocks::segment_v2::ScalarColumnWriter::append (this=0xe0b7880, column=...)
    at /root/starrocks/be/src/storage/rowset/segment_v2/column_writer.cpp:565
#4  0x0000000002b06f2f in starrocks::segment_v2::StringColumnWriter::finish (this=0x13eacc80)
    at /root/starrocks/be/src/storage/rowset/segment_v2/column_writer.cpp:907
#5  0x0000000002a7119e in starrocks::segment_v2::SegmentWriter::finalize (this=0xd09ba00,
    segment_file_size=segment_file_size@entry=0x7fc793125b80, index_size=index_size@entry=0x7fc793125b88)
    at /root/starrocks/be/src/storage/rowset/segment_v2/segment_writer.cpp:152
#6  0x0000000001a3c9e9 in starrocks::BetaRowsetWriter::_flush_segment_writer (this=0x299d28c0,
    segment_writer=0x299d2a10) at /root/starrocks/be/src/storage/rowset/beta_rowset_writer.cpp:457
#7  0x0000000002abd75a in starrocks::vectorized::SchemaChangeDirectly::process (this=0x2af19ea0,
    reader=<optimized out>, new_rowset_writer=0x299d28c0, new_tablet=..., base_tablet=..., rowset=...)
    at /root/starrocks/be/src/storage/vectorized/schema_change.cpp:723
#8  0x0000000002abf9f2 in starrocks::vectorized::SchemaChangeHandler::_convert_historical_rowsets (
    sc_params=...) at /usr/include/c++/10.3.0/ext/atomicity.h:100
#9  0x0000000002ac318f in starrocks::vectorized::SchemaChangeHandler::_do_process_alter_tablet_v2_normal (
    this=<optimized out>, request=..., base_tablet=..., new_tablet=...)
    at /root/starrocks/be/src/storage/vectorized/schema_change.cpp:1065
#10 0x0000000002ac4b29 in starrocks::vectorized::SchemaChangeHandler::_do_process_alter_tablet_v2 (
    this=0x7fc793126620, request=...) at /root/starrocks/be/src/storage/vectorized/schema_change.cpp:931
#11 0x0000000002ac541a in starrocks::vectorized::SchemaChangeHandler::process_alter_tablet_v2 (
    this=this@entry=0x7fc793126620, request=...)
    at /root/starrocks/be/src/storage/vectorized/schema_change.cpp:875
#12 0x0000000002a9fed0 in starrocks::EngineAlterTabletTask::execute (this=0x7fc7931268a0)
    at /root/starrocks/be/src/storage/task/engine_alter_tablet_task.cpp:46
#13 0x0000000001691bff in starrocks::StorageEngine::execute_task (this=0x8e762c0,
    task=task@entry=0x7fc7931268a0) at /usr/include/c++/10.3.0/ext/atomicity.h:97
#14 0x0000000001ece887 in starrocks::TaskWorkerPool::_alter_tablet (this=0x8eb7950,
    worker_pool_this=0x8eb7950, agent_task_req=..., signature=33905, task_type=starrocks::TTaskType::ALTER,
    finish_task_request=0x7fc793126980) at /root/starrocks/be/src/runtime/exec_env.h:143
#15 0x0000000001ed5292 in starrocks::TaskWorkerPool::_alter_tablet_worker_thread_callback (
    arg_this=0x8eb7950) at /root/starrocks/be/src/agent/task_worker_pool.cpp:434
#16 0x00007fccbb5b8ea5 in start_thread () from /lib64/libpthread.so.0
#17 0x00007fccba9bd9fd in hsearch_r () from /lib64/libc.so.6
#18 0x0000000000000000 in ?? ()
```

**Comment by imay** [comment]
@mchades 
Could you use the latest main to reproduce this problem?

**Comment by mchades** [comment]
@imay sorry,I can't even reproduce in my version,but I will upgrade my version to latest main than.

**Comment by imay** [comment]
This bug maybe introduced by some PR and have been fixed now.
