### ISSUE TITLE
FE start failed: Failed to create iceberg metadata on [catalog : iceberg2]

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#10471]
### Steps to reproduce the behavior (Required)
fe.log:
```
2022-08-26 16:32:07,727 ERROR (stateChangeExecutor|68) [IcebergConnector.getMetadata():38] Failed to create iceberg metadata on [catalog : iceberg2]
java.lang.NullPointerException: Cannot initialize custom GlobalStateMgr, impl class name is null
        at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897) ~[iceberg-bundled-guava-0.12.1.jar:?]
        at com.starrocks.external.iceberg.CatalogLoader$CustomCatalogLoader.<init>(CatalogLoader.java:87) ~[starrocks-fe.jar:?]
        at com.starrocks.external.iceberg.CatalogLoader$CustomCatalogLoader.<init>(CatalogLoader.java:72) ~[starrocks-fe.jar:?]
        at com.starrocks.external.iceberg.CatalogLoader.custom(CatalogLoader.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.external.iceberg.IcebergUtil.getIcebergCustomCatalog(IcebergUtil.java:84) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergMetadata.<init>(IcebergMetadata.java:48) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergConnector.getMetadata(IcebergConnector.java:36) [starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorMgr.registerConnectorInternal(ConnectorMgr.java:114) [starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorMgr.createConnector(ConnectorMgr.java:71) [starrocks-fe.jar:?]
        at com.starrocks.server.CatalogMgr.replayCreateCatalog(CatalogMgr.java:144) [starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:880) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1702) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1660) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.transferToLeader(GlobalStateMgr.java:937) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.access$100(GlobalStateMgr.java:270) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$1.transferToLeader(GlobalStateMgr.java:595) [starrocks-fe.jar:?]
        at com.starrocks.ha.StateChangeExecutor.runOneCycle(StateChangeExecutor.java:86) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
2022-08-26 16:32:07,731 ERROR (stateChangeExecutor|68) [EditLog.loadJournal():933] Operation Type 10051
com.starrocks.common.DdlException: Failed to create connector on [catalog : iceberg2, type : iceberg]
        at com.starrocks.connector.ConnectorMgr.createConnector(ConnectorMgr.java:80) ~[starrocks-fe.jar:?]
        at com.starrocks.server.CatalogMgr.replayCreateCatalog(CatalogMgr.java:144) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:880) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1702) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1660) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.transferToLeader(GlobalStateMgr.java:937) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.access$100(GlobalStateMgr.java:270) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$1.transferToLeader(GlobalStateMgr.java:595) [starrocks-fe.jar:?]
        at com.starrocks.ha.StateChangeExecutor.runOneCycle(StateChangeExecutor.java:86) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
Caused by: java.lang.NullPointerException: Cannot initialize custom GlobalStateMgr, impl class name is null
        at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897) ~[iceberg-bundled-guava-0.12.1.jar:?]
        at com.starrocks.external.iceberg.CatalogLoader$CustomCatalogLoader.<init>(CatalogLoader.java:87) ~[starrocks-fe.jar:?]
        at com.starrocks.external.iceberg.CatalogLoader$CustomCatalogLoader.<init>(CatalogLoader.java:72) ~[starrocks-fe.jar:?]
        at com.starrocks.external.iceberg.CatalogLoader.custom(CatalogLoader.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.external.iceberg.IcebergUtil.getIcebergCustomCatalog(IcebergUtil.java:84) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergMetadata.<init>(IcebergMetadata.java:48) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergConnector.getMetadata(IcebergConnector.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorMgr.registerConnectorInternal(ConnectorMgr.java:114) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorMgr.createConnector(ConnectorMgr.java:71) ~[starrocks-fe.jar:?]
        ... 9 more
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
branch-2.4 44dcfd1
```

**Comment by tiannan-sr** [comment]
https://github.com/StarRocks/starrocks/pull/10198
