### ISSUE TITLE
there is concurrency bug when insert overwrite with drop table/mv

### ISSUE THREAD

**Issue by ABingHuang** [StarRocks/starrocks#10681]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t1
2. create materialized view based on table t1 with refresh async
3. insert some records into t1
4. drop materialized view

### Expected behavior (Required)
there is no concurrency problem.
### Real behavior (Required)

the FE restart failed
2022-09-01 10:59:36,156 INFO (replayer|72) [Database.unprotectDropTable():471] finished dropping table[mv1] in db[test_mv_async_db_7db0fb9a_29a0_11ed_9998_00163e0e489a], tableId: 14952216
2022-09-01 10:59:36,156 INFO (replayer|72) [DatabaseTransactionMgr.replayUpsertTransactionState():1588] replay a visible transaction TransactionState. txn_id: 1269130, label: insert_7dd6f993-29a0-11ed-91ae-00163e0bb6a9, db id: 10002, table id list: 10452371, callback id: -1, coordinator: FE: [172.26.195.98](http://172.26.195.98/), transaction status: VISIBLE, error replicas num: 0, repl
ica ids: , prepare time: 1662000480117, commit time: 1662000480130, finish time: 1662000480151, write cost: 13ms, publish cost: 21ms, total cost: 34ms, reason:  attachment: com.starrocks.transaction.InsertTxnCommitAttachment@656c57d8
2022-09-01 10:59:36,158 INFO (replayer|72) [TaskManager.dropTasks():307] drop tasks:[14952259]
2022-09-01 10:59:36,158 ERROR (replayer|72) [EditLog.loadJournal():943] Operation Type 10002
java.lang.NullPointerException: null
        at com.starrocks.server.LocalMetastore.replayAddPartition(LocalMetastore.java:1356) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayAddPartition(GlobalStateMgr.java:1826) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:210) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1702) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.runOneCycle(GlobalStateMgr.java:1568) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.run(GlobalStateMgr.java:1631) [starrocks-fe.jar:?]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.4

**Comment by ABingHuang** [comment]
the reason is that InsertOverwriteRunner should check db/table/partition before use.
