### ISSUE TITLE
2.4.0-rc01修改FE FQDN节点时报错。

### ISSUE THREAD

**Issue by sj-dev** [StarRocks/starrocks#11192]
ERROR 1064 (HY000): Unexpected exception: (JE 7.3.7) Node: 10.42.0.111_9010_1663147367863 is not a member of the group: PALO_JOURNAL_GROUP

ALTER SYSTEM MODIFY FRONTEND HOST "10.42.0.111" TO "starrock-fe-2.xx.com";
修改FE节点时报错。
版本：2.4.0-rc01

**Comment by huoyue-git** [comment]
Please make sure the content of /etc/hosts file is correct，like this
![image](https://user-images.githubusercontent.com/91584973/190133606-bf466971-8bda-45fc-8641-3e91cd1515f1.png)
and modify the fe.conf file 
set enable_fqdn_func = true

When you execute “ALTER SYSTEM MODIFY FRONTEND xxx " successfully,start fe use this command
sh bin/start_fe.sh --host_type FQDN --daemon

**Comment by yongbingwang** [comment]
@sj-dev

**Comment by waittttting** [comment]
java -jar lib/je-7.3.7.jar DbGroupAdmin -helperHosts {ip:edit_log_port} -groupName PALO_JOURNAL_GROUP -dumpGroup

**Comment by sj-dev** [comment]
> `java -jar lib/je-7.3.7.jar DbGroupAdmin -helperHosts {ip:edit_log_port} -groupName PALO_JOURNAL_GROUP -dumpGroup`
> Please use above command to check fe node infos

Group: PALO_JOURNAL_GROUP
Electable Members:
    10.42.0.213_9010_1663226595011 (master, 10.42.0.213:9010, LocalCBVLSN:568 at:Fri Sep 16 08:37:45 CST 2022)
    10.42.3.202_9010_1663226627668 (10.42.3.202:9010, LocalCBVLSN:-1 at:Thu Sep 15 15:23:51 CST 2022)
    10.42.2.156_9010_1663226623158 (starrock-fe-1.starrock-fe.db-ns.svc.cluster.local:9010, LocalCBVLSN:-1 at:Thu Sep 15 15:23:45 CST 2022)

Monitor Members:
    No monitors

Secondary Members:
    No secondary members

External Members:
    No external members

**Comment by sj-dev** [comment]
> 

2022-09-16 08:56:27,542 ERROR (UNKNOWN starrock-fe-1.starrock-fe.db-ns.svc.cluster.local_9010_1663289719413(-1)|1) [StarRocksFE.start():166] StarRocksFE start failed
com.starrocks.journal.JournalException: bad environment /StarRocks/fe/meta/bdb! helper host 10.42.0.213:9010 not in local [Node:starrock-fe-0.starrock-fe.db-ns.svc.cluster.local_9010_1663289626168 starrock-fe-0.starrock-fe.db-ns.svc.cluster.local:9010 (is member) changeVersion:1 LocalCBVLSN:9 at:Fri Sep 16 08:53:54 CST 2022 jeVersion:7.3.7
, Node:starrock-fe-2.starrock-fe.db-ns.svc.cluster.local_9010_1663289720316 starrock-fe-2.starrock-fe.db-ns.svc.cluster.local:9010 (is member) changeVersion:3 LocalCBVLSN:-1 at:Fri Sep 16 08:55:22 CST 2022 jeVersion:7.3.7
, Node:starrock-fe-1.starrock-fe.db-ns.svc.cluster.local_9010_1663289719413 starrock-fe-1.starrock-fe.db-ns.svc.cluster.local:9010 (is member) changeVersion:2 LocalCBVLSN:-1 at:Fri Sep 16 08:55:20 CST 2022 jeVersion:7.3.7
]
        at com.starrocks.journal.bdbje.BDBEnvironment.ensureHelperInLocal(BDBEnvironment.java:390) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:161) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:141) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalFactory.create(JournalFactory.java:18) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:877) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:856) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:114) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:66) [starrocks-fe.jar:?]

换了ip后，就会出现这样的问题，但是启动的时候，看到都是用的域名。

**Comment by sj-dev** [comment]
@huoyue-git modify the fe.conf file
set enable_fqdn_func = true
这一个整体都好了，为什么不把这一个关键的更新到官方文档里去。thinks
