### ISSUE TITLE
insert value with quote ' fail

### ISSUE THREAD

**Issue by ltylty** [StarRocks/starrocks#11220]
### Steps to reproduce the behavior (Required)
1. using jdbc insert success
![](https://cdn-forum.starrocks.com/original/2X/2/2c5aac6fcc22c96e577f678551199f5be8e26818.png)

2. value add quote ' fail
![](https://cdn-forum.starrocks.com/original/2X/9/92b97a3339b802b91b5855d66d14caa8ef595d5e.png)

### StarRocks version (Required)
2.2.2 e27e2aa
![](https://cdn-forum.starrocks.com/original/2X/4/4150865652f242cc2fb8c215514771c47695560e.png)

**Comment by ltylty** [comment]
any  answer?

**Comment by ltylty** [comment]
这么严重的bug，官方不解答一下？

**Comment by rickif** [comment]
Sorry for the delay, I'm investigating it.

**Comment by rickif** [comment]
It would be very nice if you could provide the test code and the table schema. @ltylty

**Comment by ltylty** [comment]
ddl 
``` sql
CREATE TABLE `test` (
  `x_id` int(11) NULL COMMENT "",
  `x_uid` int(11) NULL COMMENT "",
  `nickname` varchar(65533) NULL COMMENT "",
  `x_time` datetime NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`x_id`, `x_uid`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`x_uid`) BUCKETS 10 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```

test JAVA code
``` java
public class InsertRecords {
    // JDBC driver name and database URL
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "";

    //  Database credentials
    static final String USER = "";
    static final String PASS = "";

    public static void main(String[] args) {
        Connection conn = null;
        Statement stmt = null;
        try{
            //STEP 2: Register JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            //STEP 3: Open a connection
            System.out.println("Connecting to a selected database...");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected database successfully...");

            //STEP 4: Execute a query
            System.out.println("Inserting records into the table...");


            String sql = "INSERT INTO test (x_id,x_uid,nickname,
x_time) VALUES(?, ?, ?, ?);";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setInt(1, 1);
            preparedStatement.setInt(2, 1);         
            preparedStatement.setString(3, "tes't");
            preparedStatement.setString(4, "2022-09-09");
            preparedStatement.addBatch();
            preparedStatement.executeBatch();


            System.out.println("Inserted records into the table...");

        }catch(SQLException se){
            //Handle errors for JDBC
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
        }finally{
            //finally block used to close resources
            try{
                if(stmt!=null)
                    conn.close();
            }catch(SQLException se){
            }// do nothing
            try{
                if(conn!=null)
                    conn.close();
            }catch(SQLException se){
                se.printStackTrace();
            }//end finally try
        }//end try
        System.out.println("Goodbye!");
    }//end main
}
```

**Comment by rickif** [comment]
fe.log
```
2022-09-21 17:09:29,272 WARN (starrocks-mysql-nio-pool-2|202) [ConnectProcessor.handleQuery():306] Process one query failed because.
com.starrocks.common.AnalysisException: extraneous input 't' expecting {',', ')'}
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:266) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:432) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:668) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by ltylty** [comment]
replace "tes't"  to  "test"  insert success .  I guess sqlParser‘s bug.

**Comment by rickif** [comment]
> replace "tes't" to "test" insert success . I guess sqlParser‘s bug.

I agree. The SQL printed in audit log `INSERT INTO db0.test (x_id,x_uid,nickname,x_time) VALUES(1, 1, 'tes\'t', '2022-09-09')` is wrong.

**Comment by packy92** [comment]
has been fixed in this pr [Fix embedded quotation contains backslash bug](https://github.com/StarRocks/starrocks/pull/10622)

**Comment by ltylty** [comment]
which version will fix this?

**Comment by packy92** [comment]
You can try this version [2.2.6](https://github.com/StarRocks/starrocks/releases/tag/2.2.6)
