### ISSUE TITLE
Unable to deploy StarRocks following quick start 

### ISSUE THREAD

**Issue by bing-hsu** [StarRocks/starrocks#11592]
## General Question

I acquire a build of StartRocks via  `wget https://download.starrocks.com/en-US/download/request-download/42/StarRocks-2.3.0.tar.gz`

As I am following the [guide](https://docs.starrocks.io/en-us/latest/quick_start/Deploy#step-1-download-and-install-starrocks) to deploy and try out StarRocks, the attempt fails at [Step 2: Start the FE node](https://docs.starrocks.io/en-us/latest/quick_start/Deploy#step-2-start-the-fe-node).

Invoking `fe/bin/start_fe.sh --daemon` responds nothing in terminal and there is no such a file `fe/log/fe.log` being created. 
Under the `fe/log` directory, I find a bunch of log-like files whose number increases as I repeat  `fe/bin/start_fe.sh --daemon`. 

One of them `fe.out` contains the following text:

```text
using java version 8
-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:/Local/opt/start-rocks/StarRocks-2.3.0/fe/log/fe.gc.log.20220923-163825
Fri Sep 23 16:38:26 CST 2022
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -o
	at org.apache.commons.cli.Parser.processOption(Parser.java:383)
	at org.apache.commons.cli.Parser.parse(Parser.java:210)
	at org.apache.commons.cli.Parser.parse(Parser.java:88)
	at com.starrocks.StarRocksFE.parseArgs(StarRocksFE.java:180)
	at com.starrocks.StarRocksFE.start(StarRocksFE.java:79)
	at com.starrocks.StarRocksFE.main(StarRocksFE.java:64)
Failed to parse command line. exit now
``` 

In line 120-124, `fe/bin/start_fe.sh` invokes following command 

```shell
if [ ${RUN_DAEMON} -eq 1 ]; then
    nohup $LIMIT $JAVA $final_java_opt com.starrocks.StarRocksFE ${HELPER} "$@" >> $LOG_DIR/fe.out 2>&1 </dev/null &
else
    $LIMIT $JAVA $final_java_opt com.starrocks.StarRocksFE ${HELPER} "$@" >> $LOG_DIR/fe.out 2>&1 </dev/null
fi
```

which in my case is interpreted into :
```bash
<MY_JAVA> -Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:<MY_STARROCKS_HOME>/fe/log/fe.gc.log.20220923-165216 com.starrocks.StarRocksFE fe/bin/start_fe.sh -o -l daemon -l helper: -- >> <MY_STARROCKS_HOME>/fe/log/fe.out 2>&1 </dev/null
``` 

Not sure if the `-o` part has anything to do with the error recorded in `fe.out`.

Any input is appreciated.

**Comment by bing-hsu** [comment]
For anyone that encounters similar issue: 

StartRocks and the foundation it is built upon - Apache Doris - **only runs in Linux OS**, not even MacOS. 

Use docker when you wish to make it work in a non-linux environment.
