### ISSUE TITLE
[sqlancer] Invalid regex expression

### ISSUE THREAD

**Issue by dulong41** [StarRocks/starrocks#12010]
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS g0;
CREATE DATABASE g0;
USE g0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATE NOT NULL,c_0_1 VARCHAR(11) NOT NULL,c_0_2 BOOLEAN NOT NULL,c_0_3 VARCHAR(41) NOT NULL,c_0_4 DATE NOT NULL,c_0_5 VARCHAR(11) NOT NULL,c_0_6 VARCHAR(31) NOT NULL,c_0_7 BOOLEAN NOT NULL,c_0_8 SMALLINT NOT NULL,c_0_9 BOOLEAN NOT NULL,c_0_10 ARRAY<INT> NOT NULL,c_0_11 ARRAY<INT> NOT NULL,c_0_12 BOOLEAN NOT NULL,c_0_13 VARCHAR(11) NOT NULL,c_0_14 VARCHAR(21) NOT NULL, INDEX index1_c_0_7(`c_0_7`) USING BITMAP) PRIMARY KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 98 day)) DISTRIBUTED BY HASH (c_0_1) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 LARGEINT NOT NULL ,c_1_1 DATETIME NOT NULL ,c_1_2 DATE NULL ,c_1_3 CHAR(21) NULL ,c_1_4 BOOLEAN NULL ,c_1_5 BOOLEAN NOT NULL ,c_1_6 BOOLEAN NULL ,c_1_7 DOUBLE SUM NOT NULL ,c_1_8 VARCHAR(1) MIN NOT NULL , INDEX index1_c_1_1(`c_1_1`) USING BITMAP) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 395 day)) DISTRIBUTED BY HASH (c_1_1,c_1_2,c_1_4) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DATE NOT NULL,c_2_1 TINYINT NOT NULL) PRIMARY KEY (c_2_0) PARTITION BY RANGE(c_2_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 678 day)) DISTRIBUTED BY HASH (c_2_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t3 (c_3_0 DECIMAL(1, 0)  NULL ,c_3_1 DATETIME NULL ,c_3_2 DECIMAL(15, 10)  NOT NULL ,c_3_3 ARRAY<INT> NOT NULL ,c_3_4 FLOAT NOT NULL ,c_3_5 BOOLEAN NOT NULL ,c_3_6 CHAR(1) NOT NULL ,c_3_7 DECIMAL(8, 4)  NULL ,c_3_8 CHAR(1) NULL ) UNIQUE KEY (c_3_0,c_3_1) PARTITION BY RANGE(c_3_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 153 day)) DISTRIBUTED BY HASH (c_3_0,c_3_1) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t3 VALUES (1, '2010-01-14 08:00:14', 0.0000023799, [-1961143146, 196910718, -1961143146], 0.00520718381172347, true, '', 0.2385, ''), (0, '2010-01-19 08:00:14', 0.0000042659, [-112965382, 1046544946, -918566967, 1461303959, -708022703, 1119129905, -112965382, 952498955, 143138683, -2061062390], 0.34722675292992544, true, '', NULL, '');
INSERT INTO t0 VALUES ('2010-01-29', 'Wyk', true, 'KRRXw0mW', '2010-01-05', 'oer', 'KDJ4TZ1', false, 15, true, [-1312921252, -1961143146], [1912823558, 849008076, -2092790314, 1237616487, 1119129905, -1501477793, -1608081577, -1840093496, -2040300084, 873266190, -112965382], true, '', 'AaD');
INSERT INTO t3 VALUES (NULL, '2010-01-15 08:00:14', 0.0000066147, [-985343377, -1608081577], 0.2906257376010446, false, '', 0.3422, '');
INSERT INTO t2 VALUES ('2010-01-21', 7), ('2010-01-22', 4), ('2010-01-08', 4);
INSERT INTO t3 VALUES (0, '2010-01-20 08:00:14', 0.0000015100, [1505856299, -1125478081, -1427291874, 1461303959, -1, -276162262, -1125478081, -659728869, -957643312, 1923410336, 1791629424, -112965382, 2052400533, 1818944398, -1433856987], 0.2906257376010446, false, '', NULL, NULL), (0, '2009-12-31 08:00:14', 0.0000078216, [-541499431, -550130333, -985343377, -1329304189, 963377076], 0.01924750746771242, false, '', 0.0711, '');
INSERT INTO t0 VALUES ('2010-01-30', '', true, 'PpH', '2010-01-28', 'w5E', 'Lhr8YCep', true, 13, false, [-19992196, 2052400533, 1923410336, -2070456639, -907904224, -771274799, -1312921252, -541499431, -541499431, -69856656, 351318091, 1058453604, 786130277, -708022703], [-1271552058, 1635849164, -345295573], true, 'X', '');
INSERT INTO t3 VALUES (4, '2010-01-08 08:00:14', 0.0000026224, [-345295573, -619253377, -918566967, 716230610, 2090311906, 1791629424, -2070456639, -19992196], 0.2906257376010446, false, '', 0.8660, '');
DELETE FROM t2 WHERE c_2_0='1969-12-25';
INSERT INTO t1 VALUES (-1897598683, '2010-01-01 08:00:14', NULL, 'V', true, true, false, 0.8474249924093744, ''), (1827569021, '2010-01-20 08:00:14', '2010-01-31', '', true, false, true, 0.01924750746771242, '');
INSERT INTO t1 VALUES (1119129905, '2010-01-25 08:00:14', '2010-01-09', 'tW0', NULL, true, false, 0.2906257376010446, ''), (1817695580, '2010-01-01 08:00:14', '2010-01-22', 'qI', true, false, NULL, 0.032264049008304485, '');
INSERT INTO t0 VALUES ('2010-01-20', 'N', true, 'k3F', '2010-01-22', 'MaDu', 'Q1', true, 0, true, [-1655335537, -838238832, -1653035092, 1258365753, -1799286101, 2026171121, 1635849164, -669926764, 1024193689, -328225645, 1931352167, -51632398, 488214113], [-747354842, -1522212675, 970419152, -692521852, 1825071349, -253489542, -1522212675, -1942341660, 83601298], true, 'lYrn', ''), ('2010-01-22', 'GC', false, 'c', '2010-01-21', '9uf7MW', '5', false, 13, false, [1237616487, 1024193689, 83601298, -799962291], [-1719661621, -974796487, -328225645, 1007753055], false, '', 'o'), ('2010-01-11', 'ZE', false, 'RehoZX', '2010-01-22', 'XIE1', 'swHUaq', true, 13, true, [], [509052896, -323712743], false, 'R', 'XKa');
INSERT INTO t1 VALUES (1573280500, '2010-01-03 08:00:14', '2010-01-04', '', true, true, false, 0.8474249924093744, ''), (1426546577, '2010-01-25 08:00:14', '2010-01-19', '', NULL, true, true, 0.05160702398196282, ''), (-1229851092, '2010-01-18 08:00:14', '2010-01-11', 'iO', true, false, true, 0.4159545003135626, '');
INSERT INTO t2 VALUES ('2010-01-20', 6);

SELECT t3_15.c_3_0, t3_15.c_3_3, t0_12.c_0_13, t0_12.c_0_1, t1_13.c_1_5, t2_14.c_2_0, t2_14.c_2_1, t3_15.c_3_6, t1_13.c_1_1, t3_15.c_3_8 FROM t3 AS t3_15, t2 AS t2_14, t0 AS t0_12, t1 AS t1_13 WHERE CAST(CASE  WHEN (CAST(t1_13.c_1_3 AS STRING ) )  BETWEEN (REGEXP_REPLACE('0', '', 'o') ) AND (t1_13.c_1_3)  THEN ''  WHEN false THEN t1_13.c_1_8 END AS BOOLEAN )  GROUP BY t3_15.c_3_0, t3_15.c_3_3, t0_12.c_0_13, t0_12.c_0_1, t1_13.c_1_5, t2_14.c_2_0, t2_14.c_2_1, t3_15.c_3_6, t1_13.c_1_1, t3_15.c_3_8 UNION SELECT t3_15.c_3_0, t3_15.c_3_3, t0_12.c_0_13, t0_12.c_0_1, t1_13.c_1_5, t2_14.c_2_0, t2_14.c_2_1, t3_15.c_3_6, t1_13.c_1_1, t3_15.c_3_8 FROM t3 AS t3_15, t2 AS t2_14, t0 AS t0_12, t1 AS t1_13 WHERE (NOT (CAST(CASE  WHEN (CAST(t1_13.c_1_3 AS STRING ) )  BETWEEN (REGEXP_REPLACE('0', '', 'o') ) AND (t1_13.c_1_3)  THEN ''  WHEN false THEN t1_13.c_1_8 END AS BOOLEAN ) )) GROUP BY t3_15.c_3_0, t3_15.c_3_3, t0_12.c_0_13, t0_12.c_0_1, t1_13.c_1_5, t2_14.c_2_0, t2_14.c_2_1, t3_15.c_3_6, t1_13.c_1_1, t3_15.c_3_8 UNION SELECT t3_15.c_3_0, t3_15.c_3_3, t0_12.c_0_13, t0_12.c_0_1, t1_13.c_1_5, t2_14.c_2_0, t2_14.c_2_1, t3_15.c_3_6, t1_13.c_1_1, t3_15.c_3_8 FROM t3 AS t3_15, t2 AS t2_14, t0 AS t0_12, t1 AS t1_13 WHERE ((CAST(CASE  WHEN (CAST(t1_13.c_1_3 AS STRING ) )  BETWEEN (REGEXP_REPLACE('0', '', 'o') ) AND (t1_13.c_1_3)  THEN ''  WHEN false THEN t1_13.c_1_8 END AS BOOLEAN ) ) IS NULL) GROUP BY t3_15.c_3_0, t3_15.c_3_3, t0_12.c_0_13, t0_12.c_0_1, t1_13.c_1_5, t2_14.c_2_0, t2_14.c_2_1, t3_15.c_3_6, t1_13.c_1_1, t3_15.c_3_8;

```

```
--Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid regex expression: 
--	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
--	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
--	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
--	at com.mysql.jdbc.Util.getInstance(Util.java:408)
--	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
--	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
--	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2497)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2455)
--	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 023d30d |
+----------------------+
1 row in set (0.00 sec)

**Comment by kangkaisen** [comment]
`Invalid regex expression`, This is a bug. which is a normal message.
