### ISSUE TITLE
BE: Hang before main is called

### ISSUE THREAD

**Issue by liyinsg** [StarRocks/starrocks#12753]
```
#0  futex_wait (private=0x0, expected=0x1, futex_word=0x7bfefe0 <bthread::init_sys_mutex_lock_once>) at ../sysdeps/nptl/futex-internal.h:146
#1  futex_wait_simple (private=0x0, expected=0x1, futex_word=0x7bfefe0 <bthread::init_sys_mutex_lock_once>) at ../sysdeps/nptl/futex-internal.h:177
#2  __pthread_once_slow (once_control=0x7bfefe0 <bthread::init_sys_mutex_lock_once>, init_routine=0x48f2790 <bthread::init_sys_mutex_lock() at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/mutex.cpp:411>) at ./nptl/pthread_once.c:105
#3  0x00000000048f2750 in bthread::first_sys_pthread_mutex_lock (mutex=0x864ece0 <init_lock+64>) at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/mutex.cpp:424
#4  0x00000000060a5daf in malloc_mutex_lock_final (mutex=0x864eca0 <init_lock>) at include/jemalloc/internal/mutex.h:155
#5  je_malloc_mutex_lock_slow (mutex=mutex@entry=0x864eca0 <init_lock>) at src/mutex.c:85
#6  0x000000000604aaac in malloc_mutex_lock (mutex=0x864eca0 <init_lock>, tsdn=0x0) at include/jemalloc/internal/mutex.h:221
#7  malloc_init_hard () at src/jemalloc.c:1739
#8  0x000000000604d435 in malloc_init () at src/jemalloc.c:210
#9  imalloc_init_check (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2229
#10 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2260
#11 je_malloc_default (size=0x54) at src/jemalloc.c:2289
#12 0x000000000604f7e1 in jemalloc (size=size@entry=0x54) at src/jemalloc.c:2388
#13 0x00000000025c4280 in my_malloc (size=0x54) at /root/starrocks/be/src/service/mem_hook.cpp:259
#14 0x00007ffff7fca812 in malloc (size=0x54) at ../include/rtld-malloc.h:56
#15 __GI__dl_exception_create_format (exception=exception@entry=0x7fffffffa950, objname=0x7fffffffe00b "/opt/starrocks/be/lib/starrocks_be", fmt=fmt@entry=0x7ffff7ff2d1f "undefined symbol: %s%s%s") at ./elf/dl-exception.c:157
#16 0x00007ffff7fd1a7a in _dl_lookup_symbol_x (undef_name=0xd9a991 "_dl_sym", undef_map=undef_map@entry=0x7ffff7ffe2e0, ref=ref@entry=0x7fffffffa9c0, symbol_scope=<optimized out>, version=0x7ffff7f9b410, type_class=type_class@entry=0x1, flags=0x1, skip_map=0x0) at ./elf/dl-lookup.c:793
#17 0x00007ffff7fd80d1 in _dl_fixup (l=0x7ffff7ffe2e0, reloc_arg=0x14e) at ./elf/dl-runtime.c:95
#18 0x00007ffff7fda6fe in _dl_runtime_resolve_xsavec () at ../sysdeps/x86_64/dl-trampoline.h:130
#19 0x00000000048f27ae in bthread::init_sys_mutex_lock () at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/mutex.cpp:411
#20 0x00007ffff6895577 in __pthread_once_slow (once_control=0x7bfefe0 <bthread::init_sys_mutex_lock_once>, init_routine=0x48f2790 <bthread::init_sys_mutex_lock() at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/mutex.cpp:411>) at ./nptl/pthread_once.c:116
#21 0x00000000048f2780 in bthread::first_sys_pthread_mutex_unlock (mutex=0x7ffff6200110) at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/mutex.cpp:428
#22 0x00000000060703ba in malloc_mutex_unlock (mutex=0x7ffff62000d0, tsdn=0x0) at include/jemalloc/internal/mutex.h:234
#23 base_alloc_impl (tsdn=tsdn@entry=0x0, base=0x7ffff62000c0, size=size@entry=0xa4, alignment=alignment@entry=0x40, esn=esn@entry=0x0) at src/base.c:451
#24 0x0000000006070a38 in je_base_alloc (tsdn=tsdn@entry=0x0, base=<optimized out>, size=size@entry=0xa4, alignment=alignment@entry=0x40) at src/base.c:465
#25 0x00000000060dc121 in je_tcache_boot (tsdn=tsdn@entry=0x0) at src/tcache.c:750
#26 0x000000000604a6f9 in malloc_init_hard_a0_locked () at src/jemalloc.c:1534
#27 0x000000000604a821 in malloc_init_hard () at src/jemalloc.c:1750
#28 0x000000000604d435 in malloc_init () at src/jemalloc.c:210
#29 imalloc_init_check (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2229
#30 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2260
#31 je_malloc_default (size=0x18) at src/jemalloc.c:2289
#32 0x000000000604f7e1 in jemalloc (size=size@entry=0x18) at src/jemalloc.c:2388
#33 0x00000000025c4280 in my_malloc (size=size@entry=0x18) at /root/starrocks/be/src/service/mem_hook.cpp:259
#34 0x00000000062a1045 in operator new (sz=sz@entry=0x18) at ../../.././libstdc++-v3/libsupc++/new_op.cc:50
#35 0x00000000062a10e9 in operator new (sz=sz@entry=0x18) at ../../.././libstdc++-v3/libsupc++/new_opnt.cc:42
#36 0x000000000629600e in __cxxabiv1::__cxa_thread_atexit (dtor=0x2570070 <starrocks::CurrentThread::~CurrentThread() at /root/starrocks/be/src/runtime/exec_env.h:98>, obj=0x7ffff7f718c0) at ../../.././libstdc++-v3/libsupc++/atexit_thread.cc:146
#37 0x00000000025c41d9 in my_malloc (size=0x11c00) at /root/starrocks/be/src/service/mem_hook.cpp:248
#38 0x00007ffff64aaa8a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#39 0x00007ffff7fcbfbe in call_init (l=<optimized out>, argc=argc@entry=0x1, argv=argv@entry=0x7fffffffdc18, env=env@entry=0x7fffffffdc28) at ./elf/dl-init.c:70
#40 0x00007ffff7fcc0a8 in call_init (env=0x7fffffffdc28, argv=0x7fffffffdc18, argc=0x1, l=<optimized out>) at ./elf/dl-init.c:33
#41 _dl_init (main_map=0x7ffff7ffe2e0, argc=0x1, argv=0x7fffffffdc18, env=0x7fffffffdc28) at ./elf/dl-init.c:117
#42 0x00007ffff7fe48b0 in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#43 0x0000000000000001 in ?? ()
#44 0x00007fffffffe00b in ?? ()
#45 0x0000000000000000 in ?? ()
```
### Expected behavior (Required)
main() should be called

### Real behavior (Required)
initialization of brpc caused hang issue

### StarRocks version (Required)
SR 2.4.0 / Ubuntu 22.10

**Comment by liyinsg** [comment]
Newer brpc should addressed this issue

**Comment by kien-truong** [comment]
So this is why I couldn't start SR BE 2.4.0 in my Ubuntu 22.04 machine.
