### ISSUE TITLE
Unexpected exception when create hudi/iceberg external table if database/table does not exist

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#12790]
### Steps to reproduce the behavior (Required)
1. create hudi external table:
```
mysql>  CREATE EXTERNAL TABLE IF NOT EXISTS customer_address(
    ->  ca_address_sk int
    ->  ,ca_address_id varchar(16)
    ->  ,ca_street_number varchar(10)
    ->  ,ca_street_name varchar(60)
    ->  ,ca_street_type varchar(15)
    ->  ,ca_suite_number varchar(10)
    ->  ,ca_city varchar(60)
    ->  ,ca_county varchar(30)
    ->  ,ca_state varchar(2)
    ->  ,ca_zip varchar(10)
    ->  ,ca_country varchar(20)
    ->  ,ca_gmt_offset decimal(5,2)
    ->  ,ca_location_type varchar(20)
    ->  )ENGINE=Hudi
    ->  properties (
    ->  "resource" = "hudi_res",
    ->  "table" = "customer_address",
    ->  "database" = "hudi_mor_tpcds_1g_parquet_gzip");
ERROR 1064 (HY000): Unexpected exception: null
```

2. fe.warn.log:
```
2022-11-01 19:22:33,951 ERROR (starrocks-mysql-nio-pool-78|3038) [HiveMetaClient.getDb():145] Failed to get database hudi_mor_tpcds_1g_parquet_gzip
org.apache.hadoop.hive.metastore.api.NoSuchObjectException: hudi_mor_tpcds_1g_parquet_gzip
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_database_result$get_database_resultStandardScheme.read(ThriftHiveMetastore.java:40927) ~[hive-apache-3.1.2-13.jar:?]
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_database_result$get_database_resultStandardScheme.read(ThriftHiveMetastore.java:40904) ~[hive-apache-3.1.2-13.jar:?]
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_database_result.read(ThriftHiveMetastore.java:40835) ~[hive-apache-3.1.2-13.jar:?]
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:88) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_database(ThriftHiveMetastore.java:1151) ~[hive-apache-3.1.2-13.jar:?]
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_database(ThriftHiveMetastore.java:1138) ~[hive-apache-3.1.2-13.jar:?]
        at com.starrocks.external.hive.HiveMetaStoreThriftClient.getDatabase(HiveMetaStoreThriftClient.java:915) ~[starrocks-fe.jar:?]
        at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:208) ~[hive-apache-3.1.2-13.jar:?]
        at com.sun.proxy.$Proxy39.getDatabase(Unknown Source) ~[?:?]
        at com.starrocks.external.hive.HiveMetaClient.getDb(HiveMetaClient.java:143) ~[starrocks-fe.jar:?]
        at com.starrocks.external.hive.HiveMetastore.getDb(HiveMetastore.java:45) ~[starrocks-fe.jar:?]
        at com.starrocks.external.hive.CachingHiveMetastore.loadDb(CachingHiveMetastore.java:172) ~[starrocks-fe.jar:?]
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.external.hive.CachingHiveMetastore.get(CachingHiveMetastore.java:325) ~[starrocks-fe.jar:?]
        at com.starrocks.external.hive.CachingHiveMetastore.getDb(CachingHiveMetastore.java:168) ~[starrocks-fe.jar:?]
        at com.starrocks.external.hive.CachingHiveMetastore.loadDb(CachingHiveMetastore.java:172) ~[starrocks-fe.jar:?]
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.external.hive.CachingHiveMetastore.get(CachingHiveMetastore.java:325) ~[starrocks-fe.jar:?]
        at com.starrocks.external.hive.CachingHiveMetastore.getDb(CachingHiveMetastore.java:168) ~[starrocks-fe.jar:?]
        at com.starrocks.external.hive.HiveMetastoreOperations.getDb(HiveMetastoreOperations.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.hudi.HudiMetadata.getDb(HudiMetadata.java:73) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.lambda$getDb$1(MetadataMgr.java:115) ~[starrocks-fe.jar:?]
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_252]
        at com.starrocks.server.MetadataMgr.getDb(MetadataMgr.java:115) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.resolveTable(QueryAnalyzer.java:701) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.access$100(QueryAnalyzer.java:68) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.resolveTableRef(QueryAnalyzer.java:238) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:163) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:85) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:205) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:90) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:108) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:102) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:85) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:90) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:78) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:305) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:113) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:40) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:115) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:110) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:53) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:365) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:305) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:420) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2022-11-01 19:22:33,953 ERROR (starrocks-mysql-nio-pool-78|3038) [HudiMetadata.getDb():75] Failed to get hudi database [hudi_catalog.hudi_mor_tpcds_1g_parquet_gzip]
``` 

### Expected behavior (Required)
ERROR 1064 (HY000): Can not find hudi/iceberg table **** from the resource ****

### Real behavior (Required)
Unexpected exception: null

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 8c5420b |
+----------------------+
1 row in set (0.01 sec)
```

**Comment by tiannan-sr** [comment]
```
mysql> select * from iceberg_catalog.icebergdb.icebergtbl;
ERROR 1064 (HY000): Unknown database 'icebergdb'
**mysql> select * from iceberg_catalog.iceberg_db.icebergtbl;
ERROR 1064 (HY000): Unknown error**
```

unknown error when select iceberg_catalog.db.tbl when iceberg table dose not exist

fe.warn.log:
```
2022-11-01 20:06:08,513 WARN (starrocks-mysql-nio-pool-87|3221) [StmtExecutor.execute():514] execute Exception, sql select * from iceberg_catalog.iceberg_db.icebergtbl
java.lang.NullPointerException: null
        at org.apache.iceberg.BaseTable.schema(BaseTable.java:69) ~[iceberg-core-0.12.1.jar:?]
        at com.starrocks.external.iceberg.IcebergUtil.convertToSRTable(IcebergUtil.java:248) ~[starrocks-fe.jar:?]
        at com.starrocks.external.iceberg.IcebergUtil.convertHiveCatalogToSRTable(IcebergUtil.java:243) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergMetadata.getTable(IcebergMetadata.java:95) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.lambda$getTable$2(MetadataMgr.java:120) ~[starrocks-fe.jar:?]
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_252]
        at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:120) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.resolveTable(QueryAnalyzer.java:706) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.access$100(QueryAnalyzer.java:68) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.resolveTableRef(QueryAnalyzer.java:238) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:163) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:85) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:205) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:90) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:108) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:102) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:85) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:90) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:78) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:305) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:113) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:40) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:115) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:110) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:53) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:365) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:305) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:420) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
