### ISSUE TITLE
[HUDI] unknown table when select from hudi_catalog.hudi_db.hudi_tbl when s3 file system

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#13001]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. select hudi table in sr:
```
MySQL [hive_catalog.hive_db]> use hudi_catalog.hudi_db;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MySQL [hudi_catalog.hudi_db]> show tables;
+---------------------------------------+
| Tables_in_hudi_db                     |
+---------------------------------------+
| hudi_mor_parquet_snappy               |
| hudi_mor_parquet_snappy_ro            |
| hudi_mor_parquet_snappy_rt            |
| hudi_s3_mor_par_parquet_gzip          |
| hudi_s3_mor_par_parquet_gzip_ro       |
| hudi_s3_mor_par_parquet_gzip_rt       |
| hudi_s3_mor_par_parquet_lz4           |
| hudi_s3_mor_par_parquet_lz4_ro        |
| hudi_s3_mor_par_parquet_lz4_rt        |
| hudi_s3_mor_par_parquet_nocompress    |
| hudi_s3_mor_par_parquet_nocompress_ro |
| hudi_s3_mor_par_parquet_nocompress_rt |
| hudi_s3_mor_par_parquet_snappy        |
| hudi_s3_mor_par_parquet_snappy_ro     |
| hudi_s3_mor_par_parquet_snappy_rt     |
| hudi_s3_mor_par_parquet_zstd          |
| hudi_s3_mor_par_parquet_zstd_ro       |
| hudi_s3_mor_par_parquet_zstd_rt       |
| hudi_s3_mor_parquet_gzip              |
| hudi_s3_mor_parquet_gzip_ro           |
| hudi_s3_mor_parquet_gzip_rt           |
| hudi_s3_mor_parquet_lz4               |
| hudi_s3_mor_parquet_lz4_ro            |
| hudi_s3_mor_parquet_lz4_rt            |
| hudi_s3_mor_parquet_nocompress        |
| hudi_s3_mor_parquet_nocompress_ro     |
| hudi_s3_mor_parquet_nocompress_rt     |
| hudi_s3_mor_parquet_snappy            |
| hudi_s3_mor_parquet_snappy_ro         |
| hudi_s3_mor_parquet_snappy_rt         |
| hudi_s3_mor_parquet_zstd              |
| hudi_s3_mor_parquet_zstd_ro           |
| hudi_s3_mor_parquet_zstd_rt           |
+---------------------------------------+
33 rows in set (0.01 sec)

MySQL [hudi_catalog.hudi_db]> select count(*) from hudi_s3_mor_parquet_snappy;
ERROR 1064 (HY000): Unknown table 'hudi_s3_mor_parquet_snappy'
```
query ok when hudi table with hdfs file system:
```
MySQL [hudi_catalog.hudi_db]> select col_int,col_date,col_decimal from hudi_mor_parquet_snappy;
+---------+------------+--------------------------------+
| col_int | col_date   | col_decimal                    |
+---------+------------+--------------------------------+
|       1 | 2020-01-01 | 10000000000.000000000100000000 |
|       2 | 2020-02-01 | 20000000000.000000000200000000 |
+---------+------------+--------------------------------+
2 rows in set (0.20 sec)
```

3. fe.warn.log:
```
2022-11-05 14:05:29,911 ERROR (starrocks-mysql-nio-pool-5|180) [CachingHiveMetastore.get():329] Error occurred when loading cache
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.hudi.exception.HoodieIOException: Failed to get instance of org.apache.hadoop.fs.FileSystem
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.get(CachingHiveMetastore.java:327) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.getTable(CachingHiveMetastore.java:183) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.HiveMetastoreOperations.getTable(HiveMetastoreOperations.java:45) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hudi.HudiMetadata.getTable(HudiMetadata.java:86) ~[starrocks-fe.jar:?]
	at com.starrocks.server.MetadataMgr.lambda$getTable$2(MetadataMgr.java:120) ~[starrocks-fe.jar:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_352]
	at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:120) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer.resolveTable(QueryAnalyzer.java:725) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer.access$100(QueryAnalyzer.java:67) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.resolveTableRef(QueryAnalyzer.java:237) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:162) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:84) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:205) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:89) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:107) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:101) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:84) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:89) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:77) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:305) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:113) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:40) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:115) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:110) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:53) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:365) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:305) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:420) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.hudi.exception.HoodieIOException: Failed to get instance of org.apache.hadoop.fs.FileSystem
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.get(CachingHiveMetastore.java:327) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.getTable(CachingHiveMetastore.java:183) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:187) ~[starrocks-fe.jar:?]
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
	... 40 more
Caused by: org.apache.hudi.exception.HoodieIOException: Failed to get instance of org.apache.hadoop.fs.FileSystem
	at org.apache.hudi.common.fs.FSUtils.getFs(FSUtils.java:104) ~[hudi-common-0.10.1.jar:0.10.1]
	at org.apache.hudi.common.table.HoodieTableMetaClient.getFs(HoodieTableMetaClient.java:256) ~[hudi-common-0.10.1.jar:0.10.1]
	at org.apache.hudi.common.table.HoodieTableMetaClient.<init>(HoodieTableMetaClient.java:112) ~[hudi-common-0.10.1.jar:0.10.1]
	at org.apache.hudi.common.table.HoodieTableMetaClient.<init>(HoodieTableMetaClient.java:73) ~[hudi-common-0.10.1.jar:0.10.1]
	at org.apache.hudi.common.table.HoodieTableMetaClient$Builder.build(HoodieTableMetaClient.java:614) ~[hudi-common-0.10.1.jar:0.10.1]
	at com.starrocks.connector.hive.HiveMetastoreApiConverter.toHudiTable(HiveMetastoreApiConverter.java:110) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.HiveMetastore.getTable(HiveMetastore.java:65) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:187) ~[starrocks-fe.jar:?]
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.get(CachingHiveMetastore.java:327) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.getTable(CachingHiveMetastore.java:183) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:187) ~[starrocks-fe.jar:?]
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
	... 40 more
Caused by: org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "s3"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3443) ~[hadoop-common-3.3.3.jar:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466) ~[hadoop-common-3.3.3.jar:?]
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174) ~[hadoop-common-3.3.3.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574) ~[hadoop-common-3.3.3.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521) ~[hadoop-common-3.3.3.jar:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540) ~[hadoop-common-3.3.3.jar:?]
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365) ~[hadoop-common-3.3.3.jar:?]
	at org.apache.hudi.common.fs.FSUtils.getFs(FSUtils.java:102) ~[hudi-common-0.10.1.jar:0.10.1]
	at org.apache.hudi.common.table.HoodieTableMetaClient.getFs(HoodieTableMetaClient.java:256) ~[hudi-common-0.10.1.jar:0.10.1]
	at org.apache.hudi.common.table.HoodieTableMetaClient.<init>(HoodieTableMetaClient.java:112) ~[hudi-common-0.10.1.jar:0.10.1]
	at org.apache.hudi.common.table.HoodieTableMetaClient.<init>(HoodieTableMetaClient.java:73) ~[hudi-common-0.10.1.jar:0.10.1]
	at org.apache.hudi.common.table.HoodieTableMetaClient$Builder.build(HoodieTableMetaClient.java:614) ~[hudi-common-0.10.1.jar:0.10.1]
	at com.starrocks.connector.hive.HiveMetastoreApiConverter.toHudiTable(HiveMetastoreApiConverter.java:110) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.HiveMetastore.getTable(HiveMetastore.java:65) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:187) ~[starrocks-fe.jar:?]
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[spark-dpp
        at com.starrocks.connector.hive.HiveMetastoreOperations.getTable(HiveMetastoreOperations.java:45) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.hudi.HudiMetadata.getTable(HudiMetadata.java:86) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.lambda$getTable$2(MetadataMgr.java:120) ~[starrocks-fe.jar:?]
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_352]
        at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:120) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.resolveTable(QueryAnalyzer.java:725) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.access$100(QueryAnalyzer.java:67) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.resolveTableRef(QueryAnalyzer.java:237) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:162) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:84) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:205) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:107) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:101) ~[starrocks-fe.jar:?]
@@@
"fe.warn.log" 12229L, 1289820C                                                     12121,1-8     99%
-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.get(CachingHiveMetastore.java:327) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.getTable(CachingHiveMetastore.java:183) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:187) ~[starrocks-fe.jar:?]
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
	... 40 more
2022-11-05 14:05:29,912 ERROR (starrocks-mysql-nio-pool-5|180) [HudiMetadata.getTable():88] Failed to get hudi table [hudi_catalog.hudi_db.hudi_s3_mor_parquet_snappy]
```

### Expected behavior (Required)
right result returned from hudi_catalog.hudi_db.hudi_tbl when s3 file system

### Real behavior (Required)
Unknown table error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
MySQL [(none)]> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 9dd9f81 |
+----------------------+
1 row in set (0.02 sec)
```

**Comment by miomiocat** [comment]
Put the S3 jar package in this path: $STARROCKS_HOME/be/lib/hudi-reader-lib/

**Comment by tiannan-sr** [comment]
Configuration problem, not a bug
