### ISSUE TITLE
[time_slice]join on Unknown error

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#13054]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE `duplicate_par_tbl` ( `k1`  date NOT NULL, `k2`  datetime NOT NULL, `k3`  char(20) NOT NULL, `k4`  varchar(20) NOT NULL, `k5`  boolean NOT NULL, `k6`  tinyint NOT NULL, `k7`  smallint NOT NULL, `k8`  int NOT NULL, `k9`  bigint NOT NULL, `k10` largeint NOT NULL, `k11` float NOT NULL, `k12` double NOT NULL, `k13` decimal(27,9) NOT NULL ) ENGINE=OLAP DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "3", "storage_format" = "v2" );
```
2. INSERT INTO '....'
```
curl --location-trusted -u root: -T common/data/basic_types_data -XPUT -H label:load_duplicate_table_without_null_3e8e2206_5e6d_11ed_a778_00163e0e550b -H max_filter_ratio:0.8 http://ip:port/api/starrocks_delete_test_3e86c132_5e6d_11ed_a778_00163e0e550b/duplicate_par_tbl/_stream_load
```
3. SELECT  '....'
```
select a.K2,b.time_slice(k2,interval 58 SECOND) from duplicate_par_tbl a right join duplicate_par_tbl b on a.K2 >b.k2 where a.K5 = 'true' order by 1 limit 30;
```
### Expected behavior (Required)
```
+---------------------+
| 2020-06-23 00:00:02 |
| 2020-06-23 00:00:02 |
| 2020-06-23 00:00:04 |
| 2020-06-23 00:00:04 |
| 2020-06-23 00:00:04 |
| 2020-06-23 00:00:04 |
| 2020-06-23 00:00:06 |
| 2020-06-23 00:00:06 |
| 2020-06-23 00:00:06 |
| 2020-06-23 00:00:06 |
| 2020-06-23 00:00:06 |
| 2020-06-23 00:00:06 |
| 2020-06-23 00:00:08 |
| 2020-06-23 00:00:08 |
| 2020-06-23 00:00:08 |
| 2020-06-23 00:00:08 |
| 2020-06-23 00:00:08 |
| 2020-06-23 00:00:08 |
| 2020-06-23 00:00:08 |
| 2020-06-23 00:00:08 |
| 2020-06-23 00:00:10 |
| 2020-06-23 00:00:10 |
| 2020-06-23 00:00:10 |
| 2020-06-23 00:00:10 |
| 2020-06-23 00:00:10 |
| 2020-06-23 00:00:10 |
| 2020-06-23 00:00:10 |
| 2020-06-23 00:00:10 |
| 2020-06-23 00:00:10 |
| 2020-06-23 00:00:10 |
+---------------------+
```
### Real behavior (Required)
Unknown error

fe.warn.log
```
2022-11-07 16:04:27,130 WARN (starrocks-mysql-nio-pool-78|2798) [StmtExecutor.execute():514] execute Exception, sql select a.K2,b.time_slice(k2,interval 58 SECOND) from duplicate_par_tbl a right join duplicate_par_tbl b on a.K2 >b.k2 where a.K5 = 'true' order by 1 limit 30
java.lang.NullPointerException: null
        at com.starrocks.sql.analyzer.AST2SQL$SQLBuilder.visitFunctionCall(AST2SQL.java:544) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.AST2SQL$SQLBuilder.visitFunctionCall(AST2SQL.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.analysis.FunctionCallExpr.accept(FunctionCallExpr.java:448) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:40) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.AST2SQL.toString(AST2SQL.java:73) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.SelectAnalyzer.analyzeSelect(SelectAnalyzer.java:229) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.SelectAnalyzer.analyze(SelectAnalyzer.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:171) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:84) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:205) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:107) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:101) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:84) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:77) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:305) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:113) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:40) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:115) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:110) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:53) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:365) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:305) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:420) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE d8d155e |
+----------------------+
```

**Comment by Pslydhh** [comment]
```
select a.K2,b.time_slice(k2,interval 58 SECOND) from duplicate_par_tbl a right join duplicate_par_tbl b on a.K2 >b.k2 where a.K5 = 'true' order by 1 limit 30;
```
It's illegal sql.
Pleas try
```
select a.K2,time_slice(b.k2,interval 58 SECOND) from duplicate_par_tbl a right join duplicate_par_tbl b on a.K2 >b.k2 where a.K5 = 'true' order by 1 limit 30;
```
It's executed normally.
