### ISSUE TITLE
`ERROR` returned while show tablet from starrocks_external table.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#13413]
### Steps to reproduce the behavior (Required)
create a starrocks external table external_t.
show tablet from starrocks external_t;

### Real behavior (Required)
```
mysql> show tablet from external_t;
ERROR 2027 (HY000): Malformed packet
```
```
2022-11-15 17:31:51,603 WARN (starrocks-mysql-nio-pool-13|3052) [StmtExecutor.execute():521] execute Exception, sql show tablet from external_t
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.common.proc.LocalTabletsProcDir.fetchComparableResult(LocalTabletsProcDir.java:84) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ShowExecutor.handleShowTablet(ShowExecutor.java:1246) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ShowExecutor.execute(ShowExecutor.java:231) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleShow(StmtExecutor.java:1062) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:484) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.4.1 cc3c302     |
+-------------------+
1 row in set (0.01 sec)
```

**Comment by gengjun-git** [comment]
fixed by #13520
