### ISSUE TITLE
[HIVE-STRUCT] unknown error when select 'colstruct'.c_tinyint from catalog.db.tbl

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#13449]
### Steps to reproduce the behavior (Required)
```
mysql> select col_struct.c_tinyint,'col_struct'.c_tinyint from hive_extbl_test_struct_map.hdfs_orc_lz4_struct_tinyint order by 1 desc limit 3;
ERROR 1064 (HY000): Unknown error
```

fe.warn.log:
```
2022-11-16 12:06:55,524 WARN (starrocks-mysql-nio-pool-14|315) [StmtExecutor.execute():516] execute Exception, sql select col_struct.c_tinyint,'col_struct'.c_tinyint from hive_extbl_test_struct_map.hdfs_orc_lz4_struct_tinyint order by 1 desc limit 3
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:130) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitSubfieldExpr(ExpressionAnalyzer.java:209) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitSubfieldExpr(ExpressionAnalyzer.java:188) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.SubfieldExpr.accept(SubfieldExpr.java:48) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:41) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:185) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:97) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1111) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.SelectAnalyzer.analyzeExpression(SelectAnalyzer.java:624) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.SelectAnalyzer.analyzeSelect(SelectAnalyzer.java:228) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.SelectAnalyzer.analyze(SelectAnalyzer.java:62) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:175) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:84) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:205) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:89) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:107) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:101) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:84) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:89) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:77) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:325) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:115) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:41) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:117) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:112) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:53) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:367) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:305) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:420) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

### Expected behavior (Required)
Clear error message if not supported

### Real behavior (Required)
unknown error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 512d9ca |
+----------------------------+
1 row in set (0.01 sec)
```

**Comment by tiannan-sr** [comment]
mysql> select col_struct.c_tinyint,'col_struct'.c_tinyint from hive_extbl_test_struct_map.hdfs_orc_lz4_struct_tinyint order by 1 desc limit 3;
ERROR 1064 (HY000): 'col_struct' must be a struct type, check if you are using `'`
