### ISSUE TITLE
[BUG] FE start failed when replaying add frontend

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#13542]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
```
2022-11-17 05:09:07,420 ERROR (main|1) [StarRocksFE.start():137] StarRocksFE start failed
java.lang.NullPointerException: null
        at com.starrocks.server.NodeMgr.replayAddFrontend(NodeMgr.java:736) ~[starrocks-fe.jar:?]
        at com.starrocks.server.NodeMgr.loadFrontends(NodeMgr.java:444) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1118) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:843) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:110) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:65) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - 2.2, 2.3

**Comment by gengjun-git** [comment]
fixed by #13544 #13545
