### ISSUE TITLE
[HIVE-STRUCT] unknown error when struct contains struct

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#13589]
### Steps to reproduce the behavior (Required)
1. create hive table and insert data:
```
create table hdfs_orc_lz4_struct_nest(
col_int int,
col_struct_array_map_struct struct<c_array:array<map<bigint,struct<c_int:int,c_string:string,c_date:date>>>,c_string:string,c_date:date>,
col_struct_struct_struct_struct struct<c_struct:struct<c_string:string,c_struct:struct<c_date:date,c_struct:struct<c_string:string,c_tinyint:tinyint>>>,c_string:string,c_double:double>,
col_struct_map_array_struct struct<c_string:string,c_map:map<boolean,array<struct<c_date:date,c_string:string>>>>,
col_struct_array_map_strut struct<c_array:array<map<float,date>>,c_string:string,c_int:int>,
col_struct_struct_map_array struct<c_date:date,c_struct:struct<c_int:int,c_date:date,c_map:map<int,array<boolean>>>,c_tinyint:tinyint>
)
stored as orc
tblproperties("orc.compress"="none");
insert into hdfs_orc_lz4_struct_nest select 1,
named_struct("c_array",array(map(cast(1 as bigint),named_struct("c_int",100,"c_string",'hello world',"c_date",cast('2022-10-30' as date)))),"c_string",'I like apples.',"c_date",cast('2001-01-01' as date)),
named_struct("c_struct",named_struct("c_string",'hello',"c_struct",named_struct("c_date",cast('2010-10-01' as date),"c_struct",named_struct("c_string",'你好',"c_tinyint",cast(10 as tinyint)))),"c_string","hi","c_double",cast(99.99 as double)),
named_struct("c_string",'hello world',"c_map",map(cast(1 as boolean),array(named_struct("c_date",cast('2022-10-01'as date),"c_string","abc"),named_struct("c_date",cast('2022-11-01' as date),"c_string","bcd"),named_struct("c_date",cast('2022-12-01' as date),"c_string","cde")))),
named_struct("c_array",array(map(cast(1.1 as float),cast('0001-01-01' as date)),map(cast(2.2 as float),cast('0002-02-02' as date)),map(cast(3.3 as float),cast('0003-03-03' as date)),map(cast(4.4 as float),cast('0004-04-04' as date))),"c_string",'hi',"c_int",cast(10 as int)),
named_struct("c_date",cast('1000-10-10' as date),"c_struct",named_struct("c_int",cast(10 as int),"c_date",cast('2000-01-01' as date),"c_map",map(cast(11 as int),array(cast(1 as boolean),cast(0 as boolean),cast(1 as boolean),cast(1 as boolean),cast(0 as boolean)))),"c_tinyint",cast(100 as tinyint));
```

2. select from sr:
```
select col_struct_struct_struct_struct.c_struct,
                    col_struct_struct_struct_struct.c_string,
                    col_struct_struct_struct_struct.c_double,
                    col_struct_struct_struct_struct.c_struct.c_struct,
                    col_struct_struct_struct_struct.c_struct.c_string,
                    col_struct_struct_struct_struct.c_struct.c_struct.c_struct,
                    col_struct_struct_struct_struct.c_struct.c_struct.c_date,
                    col_struct_struct_struct_struct.c_struct.c_struct.c_struct.c_string,
                    col_struct_struct_struct_struct.c_struct.c_struct.c_struct.c_tinyint
                    from hdfs_orc_lz4_struct_nest;
```

3. fe.warn.log:
```
2022-11-17 15:08:05,338 WARN (starrocks-mysql-nio-pool-180|3440) [StmtExecutor.execute():516] execute Exception, sql select col_struct_struct_struct_struct.c_struct,
                    col_struct_struct_struct_struct.c_string,
                    col_struct_struct_struct_struct.c_double,
                    col_struct_struct_struct_struct.c_struct.c_struct,
                    col_struct_struct_struct_struct.c_struct.c_string,
                    col_struct_struct_struct_struct.c_struct.c_struct.c_struct,
                    col_struct_struct_struct_struct.c_struct.c_struct.c_date,
                    col_struct_struct_struct_struct.c_struct.c_struct.c_struct.c_string,
                    col_struct_struct_struct_struct.c_struct.c_struct.c_struct.c_tinyint
                    from hdfs_orc_lz4_struct_nest
java.lang.NullPointerException: null
	at com.starrocks.sql.analyzer.Field.canResolve(Field.java:83) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.RelationFields.lambda$resolveFields$0(RelationFields.java:50) ~[starrocks-fe.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_252]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_252]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_252]
	at com.starrocks.sql.analyzer.RelationFields.resolveFields(RelationFields.java:51) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Scope.resolveField(Scope.java:89) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Scope.resolveField(Scope.java:81) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Scope.resolveField(Scope.java:77) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitSlot(ExpressionAnalyzer.java:222) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitSlot(ExpressionAnalyzer.java:188) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.SlotRef.accept(SlotRef.java:471) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:41) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:185) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:97) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1111) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.SelectAnalyzer.analyzeExpression(SelectAnalyzer.java:624) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.SelectAnalyzer.analyzeSelect(SelectAnalyzer.java:228) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.SelectAnalyzer.analyze(SelectAnalyzer.java:62) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:175) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:84) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:205) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:89) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:107) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:101) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:84) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:89) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:77) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:325) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:115) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:35) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:41) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:117) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:112) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:53) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:367) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:305) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:420) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

### Expected behavior (Required)
return the right result

### Real behavior (Required)
unknown error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 512d9ca |
+----------------------------+
1 row in set (0.01 sec)
```

**Comment by tiannan-sr** [comment]
create table default_catalog.tn_test.ctas_tbl as 
select *,
col_struct_struct_struct_struct.c_struct,
col_struct_struct_struct_struct.c_string,
col_struct_struct_struct_struct.c_double,
col_struct_struct_struct_struct.c_struct.c_struct,
col_struct_struct_struct_struct.c_struct.c_string,
col_struct_struct_struct_struct.c_struct.c_struct.c_struct,
col_struct_struct_struct_struct.c_struct.c_struct.c_date,
col_struct_struct_struct_struct.c_struct.c_struct.c_struct.c_string,
col_struct_struct_struct_struct.c_struct.c_struct.c_struct.c_tinyint,
col_struct_array_map_struct.c_array,
col_struct_array_map_struct.c_string,
col_struct_array_map_struct.c_date,
col_struct_array_map_struct.c_array[0],
col_struct_array_map_struct.c_array[0][1],
col_struct_array_map_struct.c_array[0][1].c_int,
col_struct_array_map_struct.c_array[0][1].c_string,
col_struct_array_map_struct.c_array[0][1].c_date,
col_struct_map_array_struct.c_string,
col_struct_map_array_struct.c_map,
col_struct_map_array_struct.c_map[cast(1 as boolean)],
col_struct_map_array_struct.c_map[cast(1 as boolean)][0],
col_struct_map_array_struct.c_map[cast(1 as boolean)][0].c_date,
col_struct_map_array_struct.c_map[cast(1 as boolean)][0].c_string,
col_struct_map_array_struct.c_map[cast(1 as boolean)][1],
col_struct_map_array_struct.c_map[cast(1 as boolean)][1].c_date,
col_struct_map_array_struct.c_map[cast(1 as boolean)][1].c_string,
col_struct_map_array_struct.c_map[cast(1 as boolean)][2],
col_struct_map_array_struct.c_map[cast(1 as boolean)][2].c_date,
col_struct_map_array_struct.c_map[cast(1 as boolean)][2].c_string
from hdfs_orc_lz4_struct_nest;

**Comment by tiannan-sr** [comment]
fixed
