### ISSUE TITLE
[lambda]Unknown error when array_filter/array_sum is used in a predicates

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#13586]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
 CREATE TABLE `array_sort_null` ( c1 int NOT NULL, c2 array<date>, c3 array<datetime>, c4 array<char(20)>, c5 array<varchar(20)>, c6 array<boolean>, c7 array<tinyint>, c8 array<smallint>, c9 array<int>, c10 array<bigint>, c11 array<largeint>, c12 array<float>, c13 array<double> ) DUPLICATE KEY(c1) DISTRIBUTED BY HASH(c1) buckets 1 PROPERTIES ("replication_num" = "3");
```
2. INSERT INTO '....'
```
insert into array_sort_null (c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13)values (1, ['2022-01-02', '2012-01-01', '2011-01-04'], ['2012-01-04 01:01:01', '2012-01-03 01:01:01', '2013-01-01 01:01:01'], ['22', '33', '11'], ['222feds', '中文', null], [False, True, False], [2, 1, 3], [22, 11, 33], [null, null, null], [null, 12345, null], [3333, null, 1111], [11.2, 11.1, -10.1], [11.11, null, 4.44]);
```
3. SELECT  '....'
```
select * from array_sort_null where array_filter(x -> x, c2)[1]>1;
select * from array_sort_null where array_filter(x -> x, c2)[1] between 1 and -1;
select * from array_sort_null where array_sum(array_map(x -> x, c2)) in (c1);
```
### Expected behavior (Required)
Return the right result
### Real behavior (Required)
ERROR 1064 (HY000): Unknown error
```
2022-11-17 14:58:19,830 WARN (starrocks-mysql-nio-pool-294|3971) [StmtExecutor.execute():516] execute Exception, sql select * from array_sort_null where array_filter(x -> x, c2)[1] between 1 and -1
java.lang.NullPointerException: null
        at java.util.HashMap.merge(HashMap.java:1225) ~[?:1.8.0_252]
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[?:1.8.0_252]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_252]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_252]
        at com.starrocks.sql.optimizer.rule.transformation.PruneScanColumnRule.transform(PruneScanColumnRule.java:64) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.execute(RewriteTreeTask.java:46) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:49) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.ruleRewriteOnlyOnce(Optimizer.java:521) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:287) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:139) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:100) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:104) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:65) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:367) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:305) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:420) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 689c816 |
+----------------------------+
```

**Comment by fzhedu** [comment]
closed by https://github.com/StarRocks/starrocks/pull/13752
