### ISSUE TITLE
mariadb/mysql connector error

### ISSUE THREAD

**Issue by grezap** [StarRocks/starrocks#13869]
When Itry to connect with DBeaver and use mariadb connector I get the following error. 

```
Could not connect to address=(host=192.168.203.8)(port=9030)(type=master) : (conn=50) could not load system variables
  (conn=50) could not load system variables
  (conn=50) could not load system variables
    Backend not found. Check if any backend is down or not
```

The log.Warn from the leader fe server is below: 

```
2022-11-23 00:34:21,339 WARN (starrocks-mysql-nio-pool-26|570) [BackendServiceClient.execBatchPlanFragmentsAsync():111] Execute batch plan fragments catch a exception, address=192.168.203.11:8060
java.lang.NoClassDefFoundError: Could not initialize class com.starrocks.rpc.BrpcProxy
        at com.starrocks.rpc.BackendServiceClient.execBatchPlanFragmentsAsync(BackendServiceClient.java:96) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator$BackendExecState.execRemoteBatchFragmentsAsync(Coordinator.java:2739) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecBatchFragmentsRequests(Coordinator.java:982) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragments(Coordinator.java:615) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:521) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:759) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:432) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
2022-11-23 00:34:21,339 WARN (starrocks-mysql-nio-pool-26|570) [Coordinator.deliverExecBatchFragmentsRequests():1011] exec plan fragment failed, errmsg=Could not initialize class com.starrocks.rpc.BrpcProxy, host: 192.168.203.11, code: THRIFT_RPC_ERROR, fragmentId=F00, backend=192.168.203.11:9060
2022-11-23 00:34:21,339 WARN (starrocks-mysql-nio-pool-26|570) [BackendServiceClient.cancelPlanFragmentAsync():154] Cancel plan fragment catch a exception, address=192.168.203.11:8060
java.lang.NoClassDefFoundError: Could not initialize class com.starrocks.rpc.BrpcProxy
        at com.starrocks.rpc.BackendServiceClient.cancelPlanFragmentAsync(BackendServiceClient.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator$BackendExecState.cancelFragmentInstance(Coordinator.java:2647) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.cancelRemoteFragmentsAsync(Coordinator.java:1357) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.cancelInternal(Coordinator.java:1346) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecBatchFragmentsRequests(Coordinator.java:1014) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragments(Coordinator.java:615) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:521) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:759) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:432) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
2022-11-23 00:34:21,339 WARN (starrocks-mysql-nio-pool-26|570) [Coordinator$BackendExecState.cancelFragmentInstance():2650] cancel plan fragment get a exception, address=192.168.203.11:8060
2022-11-23 00:34:21,339 WARN (starrocks-mysql-nio-pool-26|570) [SimpleScheduler.addToBlacklist():232] add black list 10003
2022-11-23 00:34:21,339 WARN (starrocks-mysql-nio-pool-26|570) [StmtExecutor.execute():449] retry 1 times. stmt: SELECT @@max_allowed_packet,@@system_time_zone,@@time_zone,@@auto_increment_increment
2022-11-23 00:34:21,340 WARN (starrocks-mysql-nio-pool-26|570) [BackendServiceClient.execBatchPlanFragmentsAsync():111] Execute batch plan fragments catch a exception, address=192.168.203.12:8060
java.lang.NoClassDefFoundError: Could not initialize class com.starrocks.rpc.BrpcProxy
        at com.starrocks.rpc.BackendServiceClient.execBatchPlanFragmentsAsync(BackendServiceClient.java:96) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator$BackendExecState.execRemoteBatchFragmentsAsync(Coordinator.java:2739) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecBatchFragmentsRequests(Coordinator.java:982) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragments(Coordinator.java:615) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:521) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:759) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:432) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
2022-11-23 00:34:21,340 WARN (starrocks-mysql-nio-pool-26|570) [Coordinator.deliverExecBatchFragmentsRequests():1011] exec plan fragment failed, errmsg=Could not initialize class com.starrocks.rpc.BrpcProxy, host: 192.168.203.12, code: THRIFT_RPC_ERROR, fragmentId=F00, backend=192.168.203.12:9060
2022-11-23 00:34:21,340 WARN (starrocks-mysql-nio-pool-26|570) [BackendServiceClient.cancelPlanFragmentAsync():154] Cancel plan fragment catch a exception, address=192.168.203.12:8060
java.lang.NoClassDefFoundError: Could not initialize class com.starrocks.rpc.BrpcProxy
        at com.starrocks.rpc.BackendServiceClient.cancelPlanFragmentAsync(BackendServiceClient.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator$BackendExecState.cancelFragmentInstance(Coordinator.java:2647) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.cancelRemoteFragmentsAsync(Coordinator.java:1357) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.cancelInternal(Coordinator.java:1346) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecBatchFragmentsRequests(Coordinator.java:1014) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragments(Coordinator.java:615) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:521) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:759) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:432) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
2022-11-23 00:34:21,340 WARN (starrocks-mysql-nio-pool-26|570) [Coordinator$BackendExecState.cancelFragmentInstance():2650] cancel plan fragment get a exception, address=192.168.203.12:8060
2022-11-23 00:34:21,340 WARN (starrocks-mysql-nio-pool-26|570) [SimpleScheduler.addToBlacklist():232] add black list 10122
2022-11-23 00:34:21,340 WARN (starrocks-mysql-nio-pool-26|570) [StmtExecutor.execute():521] execute Exception, sql SELECT @@max_allowed_packet,@@system_time_zone,@@time_zone,@@auto_increment_increment
com.starrocks.rpc.RpcException: rpc failed, host: 192.168.203.12
        at com.starrocks.qe.Coordinator.deliverExecBatchFragmentsRequests(Coordinator.java:1020) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragments(Coordinator.java:615) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:521) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:759) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:432) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
2022-11-23 00:34:21,343 WARN (starrocks-mysql-nio-pool-26|570) [BackendServiceClient.execPlanFragmentAsync():81] Execute plan fragment catch a exception, address=192.168.203.13:8060
java.lang.NoClassDefFoundError: Could not initialize class com.starrocks.rpc.BrpcProxy
        at com.starrocks.rpc.BackendServiceClient.execPlanFragmentAsync(BackendServiceClient.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator$BackendExecState.execRemoteFragmentAsync(Coordinator.java:2689) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragmentRequests(Coordinator.java:709) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragments(Coordinator.java:617) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:521) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:759) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:432) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
2022-11-23 00:34:21,344 WARN (starrocks-mysql-nio-pool-26|570) [Coordinator.deliverExecFragmentRequests():737] exec plan fragment failed, errmsg=Could not initialize class com.starrocks.rpc.BrpcProxy, host: 192.168.203.13, code: THRIFT_RPC_ERROR, fragmentId=F00, backend=192.168.203.13:9060
2022-11-23 00:34:21,344 WARN (starrocks-mysql-nio-pool-26|570) [BackendServiceClient.cancelPlanFragmentAsync():154] Cancel plan fragment catch a exception, address=192.168.203.13:8060
java.lang.NoClassDefFoundError: Could not initialize class com.starrocks.rpc.BrpcProxy
        at com.starrocks.rpc.BackendServiceClient.cancelPlanFragmentAsync(BackendServiceClient.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator$BackendExecState.cancelFragmentInstance(Coordinator.java:2647) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.cancelRemoteFragmentsAsync(Coordinator.java:1357) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.cancelInternal(Coordinator.java:1346) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragmentRequests(Coordinator.java:740) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragments(Coordinator.java:617) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:521) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:759) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:432) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
2022-11-23 00:34:21,344 WARN (starrocks-mysql-nio-pool-26|570) [Coordinator$BackendExecState.cancelFragmentInstance():2650] cancel plan fragment get a exception, address=192.168.203.13:8060
2022-11-23 00:34:21,344 WARN (starrocks-mysql-nio-pool-26|570) [SimpleScheduler.addToBlacklist():232] add black list 10142
2022-11-23 00:34:21,344 WARN (starrocks-mysql-nio-pool-26|570) [StmtExecutor.execute():449] retry 1 times. stmt: SHOW VARIABLES WHERE Variable_name in ('max_allowed_packet','system_time_zone','time_zone','auto_increment_increment')
2022-11-23 00:34:21,344 WARN (starrocks-mysql-nio-pool-26|570) [Coordinator.computeFragmentHosts():1621] DataPartition UNPARTITIONED, no scanNode Backend
2022-11-23 00:34:21,344 WARN (starrocks-mysql-nio-pool-26|570) [Coordinator.cancel():1331] cancel execution of query, this is outside invoke
2022-11-23 00:34:21,345 WARN (starrocks-mysql-nio-pool-26|570) [ReadListener.lambda$handleEvent$0():63] Exception happened in one session(com.starrocks.mysql.nio.NConnectContext@6e87e748).
java.io.IOException: Error happened when receiving packet.
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:671) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]

```

The Starrocks version used is : 
```
./bin/show_fe_version.sh
Commit hash: cc3c302
Build type: RELEASE
Build time: 2022-11-15 15:47:07
Build user: StarRocks@docker
Java compile version: openjdk full version "1.8.0_322-b06"
```

**Comment by imay** [comment]
You must use JDK, not JRE

**Comment by grezap** [comment]
Can you elaborate a litthle on this ? I do not understand what yoou mean.

**Comment by imay** [comment]
How do you install your JAVA environment? can you show your JAVA_HOME?

**Comment by grezap** [comment]
# echo $JAVA_HOME
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.352.b08-2.el7_9.x86_64/jre/
