### ISSUE TITLE
[materialized view]fe can't start up after back to 2.2

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#13961]
### Steps to reproduce the behavior (Required)
```
2022-11-23 20:30:00,578 ERROR (main|1) [StarRocksFE.start():138] StarRocksFE start failed
java.lang.IllegalArgumentException: No enum constant com.starrocks.catalog.Table.TableType.MATERIALIZED_VIEW
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_252]
        at com.starrocks.catalog.Table$TableType.valueOf(Table.java:52) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Table.read(Table.java:189) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Database.readFields(Database.java:597) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.loadDb(Catalog.java:1727) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.loadImage(Catalog.java:1549) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.initialize(Catalog.java:882) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:111) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:66) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by Astralidea** [comment]
If the user encounters this problem. Generally due to cross-version rollback from 2.4 or 2.5 to 2.2.
my suggestion is:
1. Backup the metadata first.
2. Then return to the version you upgraded before, such as 2.5, and then delete all materialized views.
3. Try to make an image. There are two ways. One is to modify edit_log_roll_num to a relatively small value, such as 10, so that an image will be made after 10 operations. Another way is to restart FE twice, which will force an image
4. If you finish the image, it means that the metadata in the image has been cleaned up. At this time, you try to roll back to the old version. After doing this, the rollback will not fail due to the problem in the issue.
