### ISSUE TITLE
[sqlsmith] unknown error of IllegalStateException

### ISSUE THREAD

**Issue by dulong41** [StarRocks/starrocks#14257]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

```sql
select  
  ref_0.N_NAME as c0, 
  case when ref_3.d_weekend > ref_3.d_following_holiday then ref_1.cd_dep_college_count else ref_1.cd_dep_college_count end
     as c1
from 
  sqlsmith.tpch_100g_nation as ref_0
            inner join sqlsmith.tpcds_100g_customer_demographics as ref_1
            on (ref_0.N_REGIONKEY = ref_1.cd_demo_sk )
          left join sqlsmith.t2 as ref_2
          on (ref_0.N_NATIONKEY = ref_2.c1 )
        inner join sqlsmith.tpcds_100g_date_dim as ref_3
        on (ref_1.cd_dep_college_count = ref_3.d_date_sk )
      inner join sqlsmith.tpcds_100g_ship_mode as ref_4
      on (ref_1.cd_credit_rating = ref_4.sm_ship_mode_id )
    left join sqlsmith.tpch_100g_supplier as ref_5
    on (ref_2.c2 = ref_5.S_SUPPKEY )
where cast(coalesce(ref_3.d_following_holiday,
    ref_0.N_NAME) as VARCHAR) = ref_5.S_ADDRESS
limit 56;
```

### Expected behavior (Required)
no unknown error

### Real behavior (Required)
ERROR 1064 (HY000): Unknown error

fe.log:
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.Statistics.getColumnStatistic(Statistics.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:126) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:39) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:35) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.getExpressionStatistic(PredicateStatisticsCalculator.java:317) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:195) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator.statisticsCalculate(PredicateStatisticsCalculator.java:28) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimateStatistics(StatisticsCalculator.java:1242) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeJoinNode(StatisticsCalculator.java:802) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalJoin(StatisticsCalculator.java:681) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalJoin(StatisticsCalculator.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalJoinOperator.accept(LogicalJoinOperator.java:145) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:152) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.JoinOrder.calculateStatistics(JoinOrder.java:229) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.JoinReorderLeftDeep.enumerate(JoinReorderLeftDeep.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.JoinOrder.reorder(JoinOrder.java:179) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.ReorderJoinRule.enumerate(ReorderJoinRule.java:70) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.ReorderJoinRule.transform(ReorderJoinRule.java:145) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:347) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:149) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:91) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:104) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:65) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:367) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:308) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:423) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:669) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 70b7179 |
+----------------------------+
1 row in set (0.01 sec)

**Comment by dulong41** [comment]
this also occurs in main branch

**Comment by dulong41** [comment]
```sql
DROP DATABASE IF EXISTS g2;
CREATE DATABASE g2;
USE g2;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATE NULL ,c_0_1 BOOLEAN NOT NULL ,c_0_2 DATETIME NOT NULL ,c_0_3 DATE NULL ,c_0_4 CHAR(11) NOT NULL ,c_0_5 DATETIME NOT NULL ,c_0_6 VARCHAR(11) NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 474 day)) DISTRIBUTED BY HASH (c_0_2,c_0_4,c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DATE NOT NULL ,c_1_1 DECIMAL(30, 1)  NULL ,c_1_2 DECIMAL(10, 5)  NOT NULL ,c_1_3 INT NOT NULL ,c_1_4 BOOLEAN NULL ,c_1_5 BOOLEAN NOT NULL ,c_1_6 LARGEINT NOT NULL ,c_1_7 BOOLEAN NOT NULL ,c_1_8 DECIMAL(5, 3)  NULL ,c_1_9 SMALLINT NULL ,c_1_10 DECIMAL(34, 8)  NULL ,c_1_11 BOOLEAN NOT NULL ,c_1_12 BOOLEAN NOT NULL ,c_1_13 CHAR(11) NULL ,c_1_14 BOOLEAN NULL ,c_1_15 VARCHAR(11) NOT NULL ,c_1_16 CHAR(31) NOT NULL ,c_1_17 ARRAY<STRING> NOT NULL ,c_1_18 FLOAT NULL , INDEX index1_c_1_12(`c_1_12`) USING BITMAP, INDEX index1_c_1_13(`c_1_13`) USING BITMAP) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9,c_1_10,c_1_11,c_1_12,c_1_13,c_1_14) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 124 day)) DISTRIBUTED BY HASH (c_1_4,c_1_2,c_1_6,c_1_13,c_1_3,c_1_7,c_1_9,c_1_8,c_1_14,c_1_5,c_1_12,c_1_11,c_1_1,c_1_10) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 SMALLINT NOT NULL ,c_2_1 DATE NOT NULL ,c_2_2 DATETIME NOT NULL ,c_2_3 DATETIME NULL ,c_2_4 LARGEINT NULL ,c_2_5 DECIMAL(31, 17)  NULL ,c_2_6 DECIMAL(36, 15)  NULL ,c_2_7 LARGEINT NULL ,c_2_8 DECIMAL(21, 0)  NOT NULL ,c_2_9 BOOLEAN NOT NULL ,c_2_10 ARRAY<STRING> NOT NULL ,c_2_11 ARRAY<INT> NULL ,c_2_12 ARRAY<STRING> NULL , INDEX index1_c_2_0(`c_2_0`) USING BITMAP) UNIQUE KEY (c_2_0,c_2_1) PARTITION BY RANGE(c_2_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 365 day)) DISTRIBUTED BY HASH (c_2_0,c_2_1) BUCKETS 3 properties("replication_num"="3") ;
DELETE FROM t2 WHERE c_2_1 IS NULL AND c_2_0=-950196261;
DELETE FROM t1 WHERE c_1_1=9601207853709025878303773282.5 AND c_1_0='1969-12-15' AND c_1_3=-950196261 AND c_1_14=true AND c_1_6=-1473662707;

WITH with_t_0 as (SELECT t0_19.c_0_0, t0_19.c_0_1, t0_19.c_0_2, t0_19.c_0_3, t0_19.c_0_4, t0_19.c_0_5, t0_19.c_0_6 FROM t0 AS t0_19) , with_t_1 as (SELECT t0_19.c_0_0, t0_19.c_0_1, t0_19.c_0_2, t0_19.c_0_3, t0_19.c_0_4, t0_19.c_0_5, t0_19.c_0_6 FROM t0 AS t0_19 WHERE true) SELECT t0_19.c_0_2, t0_19.c_0_6 FROM with_t_1 AS with_t_1,  t0 AS t0_19 FULL JOIN (SELECT with_t_0.c_0_0, with_t_0.c_0_1, with_t_0.c_0_2, with_t_0.c_0_3, with_t_0.c_0_4, with_t_0.c_0_5, with_t_0.c_0_6 FROM with_t_0 AS with_t_0) subwith_t_0 ON t0_19.c_0_1 = subwith_t_0.c_0_1 AND  ( subwith_t_0.c_0_0 ) <= ( t0_19.c_0_0 )  < subwith_t_0.c_0_1 AND t0_19.c_0_4 < subwith_t_0.c_0_0 AND t0_19.c_0_4 != subwith_t_0.c_0_0 WHERE (subwith_t_0.c_0_6) IN ((SELECT t0_19.c_0_6 FROM t0 AS t0_19 WHERE  ( t0_19.c_0_6 ) = ( CAST(CASE  WHEN (subwith_t_0.c_0_4) IN ('')  THEN t0_19.c_0_2  WHEN false THEN t0_19.c_0_2  WHEN CAST(t0_19.c_0_3 AS BOOLEAN )  THEN t0_19.c_0_2 END AS STRING )  ) ) )  GROUP BY t0_19.c_0_2, t0_19.c_0_6 UNION SELECT t0_19.c_0_2, t0_19.c_0_6 FROM with_t_1 AS with_t_1,  t0 AS t0_19 FULL JOIN (SELECT with_t_0.c_0_0, with_t_0.c_0_1, with_t_0.c_0_2, with_t_0.c_0_3, with_t_0.c_0_4, with_t_0.c_0_5, with_t_0.c_0_6 FROM with_t_0 AS with_t_0) subwith_t_0 ON t0_19.c_0_1 = subwith_t_0.c_0_1 AND  ( subwith_t_0.c_0_0 ) <= ( t0_19.c_0_0 )  < subwith_t_0.c_0_1 AND t0_19.c_0_4 < subwith_t_0.c_0_0 AND t0_19.c_0_4 != subwith_t_0.c_0_0 WHERE (NOT ((subwith_t_0.c_0_6) IN ((SELECT t0_19.c_0_6 FROM t0 AS t0_19 WHERE  ( t0_19.c_0_6 ) = ( CAST(CASE  WHEN (subwith_t_0.c_0_4) IN ('')  THEN t0_19.c_0_2  WHEN false THEN t0_19.c_0_2  WHEN CAST(t0_19.c_0_3 AS BOOLEAN )  THEN t0_19.c_0_2 END AS STRING )  ) ) ) )) GROUP BY t0_19.c_0_2, t0_19.c_0_6 UNION SELECT t0_19.c_0_2, t0_19.c_0_6 FROM with_t_1 AS with_t_1,  t0 AS t0_19 FULL JOIN (SELECT with_t_0.c_0_0, with_t_0.c_0_1, with_t_0.c_0_2, with_t_0.c_0_3, with_t_0.c_0_4, with_t_0.c_0_5, with_t_0.c_0_6 FROM with_t_0 AS with_t_0) subwith_t_0 ON t0_19.c_0_1 = subwith_t_0.c_0_1 AND  ( subwith_t_0.c_0_0 ) <= ( t0_19.c_0_0 )  < subwith_t_0.c_0_1 AND t0_19.c_0_4 < subwith_t_0.c_0_0 AND t0_19.c_0_4 != subwith_t_0.c_0_0 WHERE (((subwith_t_0.c_0_6) IN ((SELECT t0_19.c_0_6 FROM t0 AS t0_19 WHERE  ( t0_19.c_0_6 ) = ( CAST(CASE  WHEN (subwith_t_0.c_0_4) IN ('')  THEN t0_19.c_0_2  WHEN false THEN t0_19.c_0_2  WHEN CAST(t0_19.c_0_3 AS BOOLEAN )  THEN t0_19.c_0_2 END AS STRING )  ) ) ) ) IS NULL) GROUP BY t0_19.c_0_2, t0_19.c_0_6;
```

fe.log:
execute Exception, sql WITH with_t_0 as (SELECT t0_19.c_0_0, t0_19.c_0_1, t0_19.c_0_2, t0_19.c_0_3, t0_19.c_0_4, t0_19.c_0_5, t0_19.c_0_6 FROM t0 AS t0_19) , with_t_1 as (SELECT t0_19.c_0_0, t0_19.c_0_1, t0_19.c_0_2, t0_19.c_0_3, t0_19.c_0_4, t0_19.c_0_5, t0_19.c_0_6 FROM t0 AS t0_19 WHERE true) SELECT t0_19.c_0_2, t0_19.c_0_6 FROM with_t_1 AS with_t_1,  t0 AS t0_19 FULL JOIN (SELECT with_t_0.c_0_0, with_t_0.c_0_1, with_t_0.c_0_2, with_t_0.c_0_3, with_t_0.c_0_4, with_t_0.c_0_5, with_t_0.c_0_6 FROM with_t_0 AS with_t_0) subwith_t_0 ON t0_19.c_0_1 = subwith_t_0.c_0_1 AND  ( subwith_t_0.c_0_0 ) <= ( t0_19.c_0_0 )  < subwith_t_0.c_0_1 AND t0_19.c_0_4 < subwith_t_0.c_0_0 AND t0_19.c_0_4 != subwith_t_0.c_0_0 WHERE (subwith_t_0.c_0_6) IN ((SELECT t0_19.c_0_6 FROM t0 AS t0_19 WHERE  ( t0_19.c_0_6 ) = ( CAST(CASE  WHEN (subwith_t_0.c_0_4) IN ('')  THEN t0_19.c_0_2  WHEN false THEN t0_19.c_0_2  WHEN CAST(t0_19.c_0_3 AS BOOLEAN )  THEN t0_19.c_0_2 END AS STRING )  ) ) )  GROUP BY t0_19.c_0_2, t0_19.c_0_6 UNION SELECT t0_19.c_0_2, t0_19.c_0_6 FROM with_t_1 AS with_t_1,  t0 AS t0_19 FULL JOIN (SELECT with_t_0.c_0_0, with_t_0.c_0_1, with_t_0.c_0_2, with_t_0.c_0_3, with_t_0.c_0_4, with_t_0.c_0_5, with_t_0.c_0_6 FROM with_t_0 AS with_t_0) subwith_t_0 ON t0_19.c_0_1 = subwith_t_0.c_0_1 AND  ( subwith_t_0.c_0_0 ) <= ( t0_19.c_0_0 )  < subwith_t_0.c_0_1 AND t0_19.c_0_4 < subwith_t_0.c_0_0 AND t0_19.c_0_4 != subwith_t_0.c_0_0 WHERE (NOT ((subwith_t_0.c_0_6) IN ((SELECT t0_19.c_0_6 FROM t0 AS t0_19 WHERE  ( t0_19.c_0_6 ) = ( CAST(CASE  WHEN (subwith_t_0.c_0_4) IN ('')  THEN t0_19.c_0_2  WHEN false THEN t0_19.c_0_2  WHEN CAST(t0_19.c_0_3 AS BOOLEAN )  THEN t0_19.c_0_2 END AS STRING )  ) ) ) )) GROUP BY t0_19.c_0_2, t0_19.c_0_6 UNION SELECT t0_19.c_0_2, t0_19.c_0_6 FROM with_t_1 AS with_t_1,  t0 AS t0_19 FULL JOIN (SELECT with_t_0.c_0_0, with_t_0.c_0_1, with_t_0.c_0_2, with_t_0.c_0_3, with_t_0.c_0_4, with_t_0.c_0_5, with_t_0.c_0_6 FROM with_t_0 AS with_t_0) subwith_t_0 ON t0_19.c_0_1 = subwith_t_0.c_0_1 AND  ( subwith_t_0.c_0_0 ) <= ( t0_19.c_0_0 )  < subwith_t_0.c_0_1 AND t0_19.c_0_4 < subwith_t_0.c_0_0 AND t0_19.c_0_4 != subwith_t_0.c_0_0 WHERE (((subwith_t_0.c_0_6) IN ((SELECT t0_19.c_0_6 FROM t0 AS t0_19 WHERE  ( t0_19.c_0_6 ) = ( CAST(CASE  WHEN (subwith_t_0.c_0_4) IN ('')  THEN t0_19.c_0_2  WHEN false THEN t0_19.c_0_2  WHEN CAST(t0_19.c_0_3 AS BOOLEAN )  THEN t0_19.c_0_2 END AS STRING )  ) ) ) ) IS NULL) GROUP BY t0_19.c_0_2, t0_19.c_0_6
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.CaseWhenOperator.getCaseClause(CaseWhenOperator.java:88) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.BaseScalarOperatorShuttle.visitCaseWhenOperator(BaseScalarOperatorShuttle.java:207) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.CorrelatedPredicateRewriter.visitCaseWhenOperator(CorrelatedPredicateRewriter.java:105) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.CorrelatedPredicateRewriter.visitCaseWhenOperator(CorrelatedPredicateRewriter.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.CaseWhenOperator.accept(CaseWhenOperator.java:212) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.BaseScalarOperatorShuttle.visitList(BaseScalarOperatorShuttle.java:230) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.BaseScalarOperatorShuttle.visitCastOperator(BaseScalarOperatorShuttle.java:191) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.CorrelatedPredicateRewriter.visitCastOperator(CorrelatedPredicateRewriter.java:119) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.CorrelatedPredicateRewriter.visitCastOperator(CorrelatedPredicateRewriter.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.CastOperator.accept(CastOperator.java:81) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.BaseScalarOperatorShuttle.visitList(BaseScalarOperatorShuttle.java:230) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.BaseScalarOperatorShuttle.visitBinaryPredicate(BaseScalarOperatorShuttle.java:124) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.BaseScalarOperatorShuttle.visitBinaryPredicate(BaseScalarOperatorShuttle.java:45) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:75) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.SubqueryUtils.rewritePredicateAndExtractColumnRefs(SubqueryUtils.java:219) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.QuantifiedApply2OuterJoinRule$CorrelationOuterJoinTransformer.buildCTEProduce(QuantifiedApply2OuterJoinRule.java:259) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.QuantifiedApply2OuterJoinRule$CorrelationOuterJoinTransformer.transform(QuantifiedApply2OuterJoinRule.java:213) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.QuantifiedApply2OuterJoinRule.transform(QuantifiedApply2OuterJoinRule.java:122) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:74) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.execute(RewriteTreeTask.java:59) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.ruleRewriteIterative(Optimizer.java:467) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:228) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.rewriteAndValidatePlan(Optimizer.java:322) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:143) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:104) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:108) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:50) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:383) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:333) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:448) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:694) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:68) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
