### ISSUE TITLE
[materialized view]unknow error when use nested mv

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#14578]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1 (
    k1 INT,
    v1 INT,
    v2 INT)
DUPLICATE KEY(k1)
PARTITION BY RANGE(`k1`)
(
PARTITION `p1` VALUES LESS THAN ('2'),
PARTITION `p2` VALUES LESS THAN ('3'),
PARTITION `p3` VALUES LESS THAN ('4'),
PARTITION `p4` VALUES LESS THAN ('5'),
PARTITION `p5` VALUES LESS THAN ('6'),
PARTITION `p6` VALUES LESS THAN ('7')
)
DISTRIBUTED BY HASH(k1);
insert into t1 values (1,1,1),(1,1,2),(1,1,3),(1,2,1),(1,2,2),(1,2,3),(1,3,1),(1,3,2),(1,3,3)
                     ,(2,1,1),(2,1,2),(2,1,3),(2,2,1),(2,2,2),(2,2,3),(2,3,1),(2,3,2),(2,3,3)
                     ,(3,1,1),(3,1,2),(3,1,3),(3,2,1),(3,2,2),(3,2,3),(3,3,1),(3,3,2),(3,3,3);
CREATE MATERIALIZED VIEW mv1 PARTITION BY k1 DISTRIBUTED BY HASH(k1) BUCKETS 10
REFRESH ASYNC AS SELECT k1, v1 as k2, v2 as k3 from t1;
CREATE MATERIALIZED VIEW mv2 PARTITION BY k1 DISTRIBUTED BY HASH(k1) BUCKETS 10
REFRESH ASYNC AS SELECT k1, count(k2) as count_k2, sum(k3) as sum_k3 from mv1 group by k1;
insert into t1 values (4,1,1);
CREATE MATERIALIZED VIEW mv3 DISTRIBUTED BY HASH(k1)
REFRESH ASYNC AS SELECT k1, count_k2, sum_k3 from mv2 where k1 >1;
SELECT k1, count(v1), sum(v2) from t1 group by k1;
```

### Expected behavior (Required)
`query ok`
### Real behavior (Required)
```
2022-12-05 10:28:02,811 WARN (starrocks-mysql-nio-pool-97|10937) [StmtExecutor.execute():516] execute Exception, sql SELECT k1, count(v1), sum(v2) from t1 group by k1
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.sql.optimizer.statistics.Statistics.getColumnStatistic(Statistics.java:56) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:63) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:42) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:126) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:39) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:35) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.getExpressionStatistic(PredicateStatisticsCalculator.java:317) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:195) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:31) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:62) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator.statisticsCalculate(PredicateStatisticsCalculator.java:28) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimateStatistics(StatisticsCalculator.java:1242) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitOperator(StatisticsCalculator.java:172) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeOlapScanNode(StatisticsCalculator.java:238) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalOlapScan(StatisticsCalculator.java:201) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalOlapScan(StatisticsCalculator.java:136) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.logical.LogicalOlapScanOperator.accept(LogicalOlapScanOperator.java:120) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:152) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:42) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:49) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:380) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:149) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:91) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:95) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:66) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:367) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:312) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:427) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:673) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 1d329ce |
+----------------------------+
```

**Comment by ABingHuang** [comment]
fixed by https://github.com/StarRocks/starrocks/pull/14642
