### ISSUE TITLE
[sqlancer] unknown error of npe when creating materialized view

### ISSUE THREAD

**Issue by dulong41** [StarRocks/starrocks#14588]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'
```sql
DROP DATABASE IF EXISTS h1;
CREATE DATABASE h1;
USE h1;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATETIME NULL ,c_0_1 DATETIME NULL ,c_0_2 DATE NOT NULL ,c_0_3 LARGEINT NOT NULL ,c_0_4 CHAR(1) REPLACE NULL ) AGGREGATE KEY (c_0_0,c_0_1,c_0_2,c_0_3) DISTRIBUTED BY HASH (c_0_1,c_0_0,c_0_3,c_0_2) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATETIME NOT NULL ) UNIQUE KEY (c_1_0) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 1186 day)) DISTRIBUTED BY HASH (c_1_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE MATERIALIZED VIEW v0 AS SELECT t1_28.c_1_0 FROM t1 AS t1_28;
```

### Expected behavior (Required)
no error

### Real behavior (Required)
mysql> CREATE MATERIALIZED VIEW v0 AS SELECT t1_28.c_1_0 FROM t1 AS t1_28;
ERROR 1064 (HY000): Unknown error

fe.log:
java.lang.NullPointerException: null
        at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1128) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:477) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:320) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:435) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:681) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE a5d95ac |
+----------------------+
1 row in set (0.01 sec)

**Comment by dulong41** [comment]
this should be a high priority
