### ISSUE TITLE
Nothing works.

### ISSUE THREAD

**Issue by alexey-milovidov** [StarRocks/starrocks#1464]
### Steps to reproduce the behavior (Required)

I'm installing Starrocks and recording the steps:

```
wget https://starrocks.com/en-US/download/request-download/4
mv 4 StarRocks-1.19.1.tar.gz
tar xvf StarRocks-1.19.1.tar.gz

$ fe/bin/start_fe.sh
Error: JAVA_HOME is not set.

sudo apt install openjdk-8-jre

$ echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
$ fe/bin/start_fe.sh
```

It printed nothing.
And nothing happened.

```
ubuntu@ip-172-31-13-255:~/StarRocks-1.19.1$ pgrep fe
ubuntu@ip-172-31-13-255:~/StarRocks-1.19.1$ pgrep star
ubuntu@ip-172-31-13-255:~/StarRocks-1.19.1$ pgrep rocks

less fe/log/fe.log

2021-11-21 18:56:35,696 ERROR (main|1) [Catalog.initialize():807] /home/ubuntu/StarRocks-1.19.1/fe/meta does not exist, will exit

mkdir -p /home/ubuntu/StarRocks-1.19.1/fe/meta

$ fe/bin/start_fe.sh
```

It started.

```
sudo apt-get install mysql-client

mysql -h 127.0.0.1 -P9030 -uroot
```

Ok, it connected.

```
mysql> SHOW PROC '/frontends'\G
*************************** 1. row ***************************
             Name: 172.31.13.255_9010_1637521122808
               IP: 172.31.13.255
         HostName: ip-172-31-13-255.us-east-2.compute.internal
      EditLogPort: 9010
         HttpPort: 8030
        QueryPort: 9030
          RpcPort: 9020
             Role: FOLLOWER
         IsMaster: true
        ClusterId: 727427320
             Join: true
            Alive: true
ReplayedJournalId: 41
    LastHeartbeat: 2021-11-21 19:00:58
         IsHelper: true
           ErrMsg:
1 row in set (0.04 sec)
```

```
mysql> SELECT 1;
ERROR 1064 (HY000): there is no scanNode Backend
```

Looks like I need to start backends first.

```
cd StarRocks-1.19.1/be
mkdir -p storage
```

On frontend:
```
mysql> ALTER SYSTEM ADD BACKEND "127.0.0.1:9060";
Query OK, 0 rows affected (0.02 sec)
```

```
ubuntu@ip-172-31-13-255:~/StarRocks-1.19.1/be$ bin/start_be.sh
```

```
mysql> SHOW PROC '/backends'\G
*************************** 1. row ***************************
            BackendId: 10002
              Cluster: default_cluster
                   IP: 127.0.0.1
             HostName: localhost
        HeartbeatPort: 9060
               BePort: -1
             HttpPort: -1
             BrpcPort: -1
        LastStartTime: NULL
        LastHeartbeat: NULL
                Alive: false
 SystemDecommissioned: false
ClusterDecommissioned: false
            TabletNum: 0
     DataUsedCapacity: .000
        AvailCapacity: 1.000 B
        TotalCapacity: .000
              UsedPct: 0.00 %
       MaxDiskUsedPct: 0.00 %
               ErrMsg: Invalid method name: 'heartbeat'
              Version:
               Status: {"lastSuccessReportTabletsTime":"N/A"}
    DataTotalCapacity: .000
          DataUsedPct: 0.00 %
1 row in set (0.03 sec)
```

```
W1121 19:04:36.296695 73312 system_allocator.cc:56] Disable aggressive memory decommit
W1121 19:04:36.300451 73551 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:04:36.300469 73551 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
W1121 19:04:46.300714 73551 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:04:46.300736 73551 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
W1121 19:04:56.300976 73551 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:04:56.300999 73551 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
W1121 19:05:06.301239 73551 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:05:06.301268 73551 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
W1121 19:05:16.301528 73551 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:05:16.301553 73551 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
W1121 19:05:26.301838 73551 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:05:26.301868 73551 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
W1121 19:05:36.302142 73551 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:05:36.302191 73551 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
W1121 19:05:46.302467 73551 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:05:46.302501 73551 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
W1121 19:05:56.302783 73551 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:05:56.302814 73551 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
```

Looks like the port for backend is clashed with the port of frontend.
I have to change it if I want to start both frontend and backend on one machine.
Let's increase port numbers by one.

```
# ports for admin, web, heartbeat service.
be_port = 9061
webserver_port = 8041
heartbeat_service_port = 9051
brpc_port = 8061
```

```
mysql> ALTER SYSTEM DROP BACKEND "127.0.0.1:9060";
ERROR 1064 (HY000): It is highly NOT RECOMMENDED to use DROP BACKEND stmt.It is not safe to directly drop a backend. All data on this backend will be discarded permanently. If you insist, use DROPP BACKEND stmt (double P).
```

Missing whitespace. Also I thought DROPP was a typo.

When I press Ctrl+C:

```
ubuntu@ip-172-31-13-255:~/StarRocks-1.19.1/be$ bin/start_be.sh
^Cbin/start_be.sh: line 114: 73312 Segmentation fault      (core dumped) ${STARROCKS_HOME}/lib/starrocks_be "$@" >> $LOG_DIR/be.out 2>&1 < /dev/null
```

It was too quick to get my first Segmentation fault with StarRocks.

Let's run again.

```
ALTER SYSTEM ADD BACKEND "127.0.0.1:9051";
```

Does not work:

```
mysql> SELECT 1
    -> ;
ERROR 1064 (HY000): there is no scanNode Backend
```

```
W1121 19:14:19.716825 74489 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
W1121 19:14:24.367143 74602 heartbeat_server.cpp:80] backend ip saved in master does not equal to backend local ip127.0.0.1 vs. 172.31.13.255
```

```
mysql> ALTER SYSTEM DROPP BACKEND "127.0.0.1:9051";
Query OK, 0 rows affected (0.00 sec)

mysql> ALTER SYSTEM ADD BACKEND "172.31.13.255:9051";
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW PROC '/backends'\G
*************************** 1. row ***************************
            BackendId: 10107
              Cluster: default_cluster
                   IP: 172.31.13.255
             HostName: ip-172-31-13-255.us-east-2.compute.internal
        HeartbeatPort: 9051
               BePort: 9061
             HttpPort: 8041
             BrpcPort: 8061
        LastStartTime: 2021-11-21 19:15:54
        LastHeartbeat: 2021-11-21 19:15:54
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
            TabletNum: 0
     DataUsedCapacity: .000
        AvailCapacity: 37.509 GB
        TotalCapacity: 155.043 GB
              UsedPct: 75.81 %
       MaxDiskUsedPct: 75.81 %
               ErrMsg:
              Version: 1.19.1-65e87c3
               Status: {"lastSuccessReportTabletsTime":"2021-11-21 19:15:55"}
    DataTotalCapacity: 37.509 GB
          DataUsedPct: 0.00 %
1 row in set (0.02 sec)
```

Looks like it's started. Let's try some query...

```
mysql> SELECT 1;
ERROR 1064 (HY000): Unknown error
```

Cannot be better.

```
W1121 19:15:42.300310 75275 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:15:42.300331 75275 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
W1121 19:15:52.300581 75275 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1121 19:15:52.300623 75275 task_worker_pool.cpp:1116] Fail to report task to :0, err=-1
```

```
mysql> SHOW TABLES;
ERROR 1064 (HY000): No database selected
mysql> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| _statistics_       |
| information_schema |
+--------------------+
2 rows in set (0.00 sec)

mysql> CREATE DATABASE test;
Query OK, 0 rows affected (0.01 sec)

mysql> USE test;
No connection. Trying to reconnect...
Connection id:    1
Current database: *** NONE ***

Database changed
mysql> SELECT 1;
ERROR 1064 (HY000): Could not initialize class com.starrocks.rpc.BackendServiceProxy
```

It does not work:

```
mysql> SHOW TABLES FROM information_schema ;
+------------------------------+
| Tables_in_information_schema |
+------------------------------+
| character_sets               |
| collations                   |
| columns                      |
| engines                      |
| events                       |
| global_variables             |
| key_column_usage             |
| referential_constraints      |
| routines                     |
| schema_privileges            |
| schemata                     |
| session_variables            |
| statistics                   |
| table_constraints            |
| table_privileges             |
| tables                       |
| triggers                     |
| user_privileges              |
| views                        |
+------------------------------+
19 rows in set (0.00 sec)

mysql> SELECT * FROM information_schema.tables;
ERROR 1064 (HY000): Could not initialize class com.starrocks.rpc.BackendServiceProxy
```

Let's copy-paste something from the docs:

```
mysql> CREATE TABLE table1
    -> (
    ->     siteid INT DEFAULT '10',
    ->     citycode SMALLINT,
    ->     username VARCHAR(32) DEFAULT '',
    ->     pv BIGINT SUM DEFAULT '0'
    -> )
    -> AGGREGATE KEY(siteid, citycode, username)
    -> DISTRIBUTED BY HASH(siteid) BUCKETS 10
    -> PROPERTIES("replication_num" = "1");
Query OK, 0 rows affected (0.02 sec)
```

Still does not work:
```
mysql> SELECT * FROM table1;
ERROR 1064 (HY000): Could not initialize class com.starrocks.rpc.BackendServiceProxy
```

The backend node looks working:
```
I1121 19:24:10.091261 75245 task_worker_pool.cpp:214] remove task info. type=CREATE, signature=10143, queue_size=4
I1121 19:24:10.091284 75244 tablet_manager.cpp:191] Creating tablet_id=10149 schema_hash=1421156361
I1121 19:24:10.091289 75244 tablet_manager.cpp:1358] creating tablet meta. next_unique_id=4
I1121 19:24:10.091293 75245 tablet_manager.cpp:191] Creating tablet_id=10151 schema_hash=1421156361
I1121 19:24:10.091297 75245 tablet_manager.cpp:1358] creating tablet meta. next_unique_id=4
I1121 19:24:10.091373 75243 tablet_manager.cpp:251] Created tablet_id=10147 schema_hash=1421156361
I1121 19:24:10.091464 75244 tablet_manager.cpp:251] Created tablet_id=10149 schema_hash=1421156361
I1121 19:24:10.091485 75245 tablet_manager.cpp:251] Created tablet_id=10151 schema_hash=1421156361
I1121 19:24:10.091554 75243 task_worker_pool.cpp:254] finish task success.
I1121 19:24:10.091562 75243 task_worker_pool.cpp:214] remove task info. type=CREATE, signature=10147, queue_size=3
I1121 19:24:10.091576 75243 tablet_manager.cpp:191] Creating tablet_id=10153 schema_hash=1421156361
I1121 19:24:10.091579 75243 tablet_manager.cpp:1358] creating tablet meta. next_unique_id=4
I1121 19:24:10.091672 75245 task_worker_pool.cpp:254] finish task success.
I1121 19:24:10.091678 75245 task_worker_pool.cpp:214] remove task info. type=CREATE, signature=10151, queue_size=2
I1121 19:24:10.091677 75244 task_worker_pool.cpp:254] finish task success.
I1121 19:24:10.091683 75244 task_worker_pool.cpp:214] remove task info. type=CREATE, signature=10149, queue_size=1
I1121 19:24:10.091805 75243 tablet_manager.cpp:251] Created tablet_id=10153 schema_hash=1421156361
I1121 19:24:10.092017 75243 task_worker_pool.cpp:254] finish task success.
I1121 19:24:10.092023 75243 task_worker_pool.cpp:214] remove task info. type=CREATE, signature=10153, queue_size=0
I1121 19:24:22.297890 75231 load_channel_mgr.cpp:327] Cleaning timed out load channels
I1121 19:24:22.297909 75231 load_channel_mgr.cpp:360] Memory consumption(bytes) limit=7992247910 current=0 peak=0
I1121 19:24:22.344563 75232 update_manager.cpp:149] index cache expire: before:(0 0) after:(0 0) expire: (0 0)
I1121 19:24:39.846375 75386 heartbeat_server.cpp:57] get heartbeat from FE.host:172.31.13.255, port:9020, cluster id:727427320, counter:109
```

The frontend node is printing Java exceptions:

```
2021-11-21 19:26:23,892 INFO (tablet scheduler|29) [ClusterLoadStatistic.classifyBackendByLoad():155] classify backend by load. medium: HDD, avg load score: 0.5, low/mid/high: 0/1/0
2021-11-21 19:26:23,893 INFO (tablet scheduler|29) [TabletScheduler.updateClusterLoadStatistic():353] update cluster default_cluster load statistic:
    be id: 10107, is available: true, mediums: [{medium: HDD, replica: 20, used: 0, total: 40201084928, score: 0.5},{medium: SSD, replica: 0, used: 0, total: 0, score: NaN},], paths: [{path: /home/ubuntu/StarRocks-1.19.1/be/storage, path hash: 8658366482312805367, be: 10107, medium: HDD, used: 0, total: 40201084928},]

2021-11-21 19:26:23,893 INFO (tablet scheduler|29) [TabletScheduler.adjustPriorities():382] adjust priority for all tablets. changed: 0, total: 0
2021-11-21 19:26:27,449 INFO (starrocks-mysql-nio-pool-9|135) [QeProcessorImpl.registerQuery():69] register query id = ec1401dd-4b00-11ec-ba5e-0284c19cfa12, job: -1
2021-11-21 19:26:27,449 INFO (starrocks-mysql-nio-pool-9|135) [Coordinator.exec():455] dispatch query job: ec1401dd-4b00-11ec-ba5e-0284c19cfa12 to TNetworkAddress(hostname:172.31.13.255, port:9061)
2021-11-21 19:26:27,450 INFO (starrocks-mysql-nio-pool-9|135) [QeProcessorImpl.unregisterQuery():79] deregister query id ec1401dd-4b00-11ec-ba5e-0284c19cfa12
2021-11-21 19:26:27,450 WARN (starrocks-mysql-nio-pool-9|135) [StmtExecutor.execute():456] execute Exception, sql SELECT * FROM table1
java.lang.NoClassDefFoundError: Could not initialize class com.starrocks.rpc.BackendServiceProxy
        at com.starrocks.qe.Coordinator$BackendExecState.execRemoteFragmentAsync(Coordinator.java:1695) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:522) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:771) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:371) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:248) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:397) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:633) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$480(ReadListener.java:54) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
2021-11-21 19:26:27,454 INFO (ForkJoinPool.commonPool-worker-3|136) [Coordinator.exec():455] dispatch query job: ec144fff-4b00-11ec-ba5e-0284c19cfa12 to TNetworkAddress(hostname:172.31.13.255, port:9061)
```

### Expected behavior (Required)

At least I should be able to run some queries.

### Real behavior (Required)

I did not get through installation process.

### StarRocks version (Required)

1.19.1

```
mysql> select current_version()
    -> ;
ERROR 1064 (HY000): Could not initialize class com.starrocks.rpc.BackendServiceProxy
```

This query does not work either.

**Comment by gengjun-git** [comment]
Do not use the jre environment. Could you install the jdk, and try again?

**Comment by Seaven** [comment]
> Do not use the jre environment. Could you install the jdk, and try again?

@gengjun-git  BTW, In addition to report `JAVA_HOME is not set`,  can also report that you need to install jdk?

**Comment by alexey-milovidov** [comment]
Thank you, it's my mistake. I did not install `openjdk-8-jdk` package - no experience with Java.
After I did, at least version query works:

```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 1.19.1 65e87c3    |
+-------------------+
```

Let me continue...

**Comment by alexey-milovidov** [comment]
`SELECT 1` also works.

**Comment by Dshadowzh** [comment]
Thank you for your advice @alexey-milovidov, We will continue to improve the usability, error messages and documentation of StarRocks。
Such as https://github.com/StarRocks/starrocks/issues/1576 replace dropp by drop <backends> force.
