### ISSUE TITLE
query with count(*) failed after materialized view rewrite

### ISSUE THREAD

**Issue by ABingHuang** [StarRocks/starrocks#14702]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE 
CREATE TABLE `emps` (
  `empid` int(11) NOT NULL COMMENT "",
  `deptno` int(11) NOT NULL COMMENT "",
  `name` varchar(25) NOT NULL COMMENT "",
  `salary` double NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`empid`, `deptno`, `name`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`empid`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);

CREATE MATERIALIZED VIEW `count_mv_1`
COMMENT "MATERIALIZED_VIEW"
DISTRIBUTED BY HASH(`deptno`) BUCKETS 6
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD"
)
AS SELECT `emps`.`deptno`, count(*) AS `num`
FROM `mvdb`.`emps`
GROUP BY `emps`.`deptno`;

2. query 
SELECT count(*) AS `num` FROM `mvdb`.`emps`;

### Expected behavior (Required)
query rewrite ok
### Real behavior (Required)
query failed with stack:
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.SplitAggregateRule.getIntermediateType(SplitAggregateRule.java:538) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.SplitAggregateRule.createNormalAgg(SplitAggregateRule.java:510) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.SplitAggregateRule.implementTwoStageAgg(SplitAggregateRule.java:310) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.SplitAggregateRule.transform(SplitAggregateRule.java:247) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.ApplyRuleTask.execute(ApplyRuleTask.java:70) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:49) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:379) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:149) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:91) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:95) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:66) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:369) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:320) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:435) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:681) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by ABingHuang** [comment]
the reason for the bug is during mv rewrite with rollup, we generate sum(count()) to replace the original count function, but provide wrong argument type to sum for count(*) function, so get null function object, which leads to the npe bug
