### ISSUE TITLE
broker load  Error happened when receiving packet.

### ISSUE THREAD

**Issue by winter-tang** [StarRocks/starrocks#15321]
### Steps to reproduce the behavior (Required)
从oss 数据进行broker load操作；

### Expected behavior (Required)
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/117736468/208012988-c37d4b47-5fb7-4a53-84bc-c15edf51012f.png">

### StarRocks version (Required)
2.3.5

### location problem

2022-12-15 11:17:38,167 WARN (starrocks-mysql-nio-pool-12|262) [ReadListener.lambda$handleEvent$0():63] Exception happened in one session(com.starrocks.mysql.nio.NConnectContext@1fecfad2).
java.io.IOException: Error happened when receiving packet.
at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:675) ~[starrocks-fe.jar:?]
at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

[hadoop@sr-01 log]$ tailf be.WARNING
W1215 11:28:27.481781 3576 broker_mgr.cpp:76] Create broker client failed. broker=TNetworkAddress(hostname=192.168.144.48, port=8000), status=Couldn't open transport for 192.168.144.48:8000 (socket open() error: Connection refused)
W1215 11:28:32.482843 3576 broker_mgr.cpp:76] Create broker client failed. broker=TNetworkAddress(hostname=192.168.144.48, port=8000), status=Couldn't open transport for 192.168.144.48:8000 (socket open() error: Connection refused)
W1215 11:28:37.483964 3576 broker_mgr.cpp:76] Create broker client failed. broker=TNetworkAddress(hostname=192.168.144.48, port=8000), status=Couldn't open transport for 192.168.144.48:8000 (socket open() error: Connection refused)
W1215 11:28:42.485127 3576 broker_mgr.cpp:76] Create broker client failed. broker=TNetworkAddress(hostname=192.168.144.48, port=8000), status=Couldn't open transport for 192.168.144.48:8000 (socket open() error: Connection refused)
W1215 11:28:47.486223 3576 broker_mgr.cpp:76] Create broker client failed. broker=TNetworkAddress(hostname=192.168.144.48, port=8000), status=Couldn't open transport for 192.168.144.48:8000 (socket open() error: Connection refused)
W1215 11:28:52.487426 3576 broker_mgr.cpp:76] Create broker client failed. broker=TNetworkAddress(hostname=192.168.144.48, port=8000), status=Couldn't open transport for 192.168.144.48:8000 (socket open() error: Connection refused)
W1215 11:28:57.488534 3576 broker_mgr.cpp:76] Create broker client failed. broker=TNetworkAddress(hostname=192.168.144.48, port=8000), status=Couldn't open transport for 192.168.144.48:8000 (socket open() error: Connection refused)

![image](https://user-images.githubusercontent.com/117736468/208013274-519a8217-8494-4e60-9d3a-dcffbe3be19c.png)
下线的broker 仍在连接；如果直接对应服务器的broker，报 Connection refused 错误；

### 解决方法
重启be 服务，让他重新或者broker信息，解决问题；broker任务执行成功

**Comment by xiaoyong-z** [comment]
This error log indicates connection to mysql protocol is break. Broker load is a background asyn task, i think the break of mysql protocol won't affect it.
```
2022-12-15 11:17:38,167 WARN (starrocks-mysql-nio-pool-12|262) [ReadListener.lambda$handleEvent$0():63] Exception happened in one session(com.starrocks.mysql.nio.NConnectContext@1fecfad2).
java.io.IOException: Error happened when receiving packet.
at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:675) ~[starrocks-fe.jar:?]
at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by xiaoyong-z** [comment]
can you provide more broker's log at that time for problem tracing @winter-tang , i guess broker's service is interrupted due to some unknown error at that time. Thank you!
