### ISSUE TITLE
BerkeleyDB UNEXPECTED_STATE_FATAL: Unexpected internal state after restarting a FE Follower

### ISSUE THREAD

**Issue by didip** [StarRocks/starrocks#15381]
### Steps to reproduce the behavior (Required)
1. Restart 1 FE Kubernetes pod (make sure all the other FE are healthy and make sure the restarted one is FOLLOWER).

### Expected behavior (Required)
The FE starts correctly.

### Real behavior (Required)
```bash
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/starrocks/fe/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/starrocks/fe/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/starrocks/fe/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
01:18:42.144 [main] ERROR com.starrocks.journal.bdbje.BDBEnvironment - failed to check if helper in local after retried 1 times
com.sleepycat.je.EnvironmentFailureException: (JE 7.3.7) sr-fe-0.sr-fe-headless.starrocks.svc.cluster.local_9010_1671324636997(-1):/root/starrocks/fe/ebs/meta/bdb recoveryTracker should overlap or follow on disk last VLSN of 53,318 recoveryFirst= 53,320 UNEXPECTED_STATE_FATAL: Unexpected internal state, unable to continue. Environment is invalid and must be closed.
        at com.sleepycat.je.EnvironmentFailureException.unexpectedState(EnvironmentFailureException.java:443) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.vlsn.VLSNIndex.merge(VLSNIndex.java:1573) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.vlsn.VLSNIndex.init(VLSNIndex.java:1483) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.vlsn.VLSNIndex.<init>(VLSNIndex.java:422) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.RepImpl.preRecoveryCheckpointInit(RepImpl.java:567) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.recovery.RecoveryManager.recover(RecoveryManager.java:461) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.EnvironmentImpl.finishInit(EnvironmentImpl.java:841) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:222) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:267) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.<init>(Environment.java:252) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:607) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:466) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:540) ~[je-7.3.7.jar:7.3.7]
        at com.starrocks.journal.bdbje.BDBEnvironment.ensureHelperInLocal(BDBEnvironment.java:369) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:160) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:140) [starrocks-fe.jar:?]
        at com.starrocks.journal.JournalFactory.create(JournalFactory.java:18) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:943) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:893) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:116) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:68) [starrocks-fe.jar:?]
01:18:47.338 [main] ERROR com.starrocks.journal.bdbje.BDBEnvironment - failed to check if helper in local after retried 2 times
com.sleepycat.je.EnvironmentFailureException: (JE 7.3.7) sr-fe-0.sr-fe-headless.starrocks.svc.cluster.local_9010_1671324636997(-1):/root/starrocks/fe/ebs/meta/bdb recoveryTracker should overlap or follow on disk last VLSN of 53,318 recoveryFirst= 53,320 UNEXPECTED_STATE_FATAL: Unexpected internal state, unable to continue. Environment is invalid and must be closed.
        at com.sleepycat.je.EnvironmentFailureException.unexpectedState(EnvironmentFailureException.java:443) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.vlsn.VLSNIndex.merge(VLSNIndex.java:1573) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.vlsn.VLSNIndex.init(VLSNIndex.java:1483) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.vlsn.VLSNIndex.<init>(VLSNIndex.java:422) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.RepImpl.preRecoveryCheckpointInit(RepImpl.java:567) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.recovery.RecoveryManager.recover(RecoveryManager.java:461) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.EnvironmentImpl.finishInit(EnvironmentImpl.java:841) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:222) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:267) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.<init>(Environment.java:252) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:607) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:466) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:540) ~[je-7.3.7.jar:7.3.7]
        at com.starrocks.journal.bdbje.BDBEnvironment.ensureHelperInLocal(BDBEnvironment.java:369) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:160) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:140) [starrocks-fe.jar:?]
        at com.starrocks.journal.JournalFactory.create(JournalFactory.java:18) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:943) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:893) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:116) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:68) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
The latest 2.5 branch.

**Comment by didip** [comment]
Because it is just a follower, it's not a big deal, I can just restart the pod again while deleting its EBS volume. But it would be super nice to always have a clean FE restart.

**Comment by nshangyiming** [comment]
@gengjun-git PTAL

**Comment by gengjun-git** [comment]
This is a BDB bug, but we use shutdown hook to prevent it. If you did not stop the FE node with kill -9 , the chances of this problem being triggered are very small.

**Comment by didip** [comment]
I will take a look at your `stop_fe.sh` to learn about this shutdown hook. Thank you.

**Comment by didip** [comment]
Ah, i see that it simply sleep for 2 seconds. Kubernetes by default has a 30 seconds grace period after the SIGTERM is sent.
And yet, unfortunately, this still happened.
