### ISSUE TITLE
CREATE MATERIALIZED AS select to_bitmap(xxxx)  returns Unknown error

### ISSUE THREAD

**Issue by buggithubs** [StarRocks/starrocks#15809]
### Steps to reproduce the behavior (Required)

【DUPLICATE / unique 】has the same problem

```
create table uuu (
    user_id bigint(4) NOT NULL,
    name varchar(5) NOT NULL
) PRIMARY KEY (user_id)
DISTRIBUTED BY HASH(user_id) BUCKETS 1
PROPERTIES("replication_num" = "1",
"enable_persistent_index" = "true");

MySQL [pkk]> CREATE MATERIALIZED VIEW usdf AS select to_bitmap(record_id) from sales_records;
ERROR 1064 (HY000): Unknown error
```

### Expected behavior (Required)

`ERROR 1064 (HY000): xxxxx`

### Real behavior (Required)

```
2022-12-27 15:55:50,730 WARN (starrocks-mysql-nio-pool-490|2235758) [StmtExecutor.execute():521] execute Exception, sql CREATE MATERIALIZED VIEW ussss AS select user_id,to_bitmap(user_id) from uuu
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.analysis.FunctionCallExpr.isDistinct(FunctionCallExpr.java:294) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.CreateMaterializedViewStmt.genColumnAndSetIntoStmt(CreateMaterializedViewStmt.java:386) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.CreateMaterializedViewStmt.access$000(CreateMaterializedViewStmt.java:69) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.CreateMaterializedViewStmt$OldMVAnalyzerVisitor.visitCreateMaterializedViewStmt(CreateMaterializedViewStmt.java:316) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.CreateMaterializedViewStmt$OldMVAnalyzerVisitor.visitCreateMaterializedViewStmt(CreateMaterializedViewStmt.java:285) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.CreateMaterializedViewStmt.accept(CreateMaterializedViewStmt.java:278) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:129) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.CreateMaterializedViewStmt.analyze(CreateMaterializedViewStmt.java:282) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitCreateMaterializedViewStmt(Analyzer.java:285) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitCreateMaterializedViewStmt(Analyzer.java:82) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.CreateMaterializedViewStmt.accept(CreateMaterializedViewStmt.java:278) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:129) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:84) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:79) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:55) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:39) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:370) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.4.1 cc3c302

**Comment by mofeiatwork** [comment]
fixed by https://github.com/StarRocks/starrocks/issues/22401
