### ISSUE TITLE
Persistence Index may cause be rpc thread pool full

### ISSUE THREAD

**Issue by caneGuy** [StarRocks/starrocks#15808]
### Steps to reproduce the behavior (Required)
This is a corner case from our user's cluster on alibaba cloud.

### Real behavior (Required)
1. Query dispatch fragments timeout
```
2022-12-26 14:16:47,274 INFO (replayer|72) [GlobalStateMgr.replayJournalInner():1755] replayed journal from 717404 - 717405
2022-12-26 14:16:49,901 WARN (starrocks-mysql-nio-pool-22|160) [Coordinator.deliverExecFragmentRequests():722] catch a execute exception
java.util.concurrent.ExecutionException: A error occurred: errorCode=62 errorMessage:method request time out, please check 'onceTalkTimeout' property. current value is:60000(MILLISECONDS) correlationId:723 timeout with bound channel =>[id: 0x7531dd43, L:/172.16.1.60:38906
 - R:/172.16.1.62:8060]
        at com.baidu.jprotobuf.pbrpc.client.ProtobufRpcProxy$2.get(ProtobufRpcProxy.java:578) ~[jprotobuf-rpc-core-4.2.1.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragmentRequests(Coordinator.java:716) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragments(Coordinator.java:617) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:521) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:759) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:432) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: com.baidu.jprotobuf.pbrpc.ErrorDataException: A error occurred: errorCode=62 errorMessage:method request time out, please check 'onceTalkTimeout' property. current value is:60000(MILLISECONDS) correlationId:723 timeout with bound channel =>[id: 0x7531dd43, L:/1
72.16.1.60:38906 - R:/172.16.1.62:8060]
        at com.baidu.jprotobuf.pbrpc.client.ProtobufRpcProxy.doWaitCallback(ProtobufRpcProxy.java:651) ~[jprotobuf-rpc-core-4.2.1.jar:?]
        at com.baidu.jprotobuf.pbrpc.client.ProtobufRpcProxy.access$0(ProtobufRpcProxy.java:611) ~[jprotobuf-rpc-core-4.2.1.jar:?]
        at com.baidu.jprotobuf.pbrpc.client.ProtobufRpcProxy$2.get(ProtobufRpcProxy.java:576) ~[jprotobuf-rpc-core-4.2.1.jar:?]
        ... 12 more
2022-12-26 14:16:49,901 WARN (ForkJoinPool.commonPool-worker-6|163) [Coordinator.deliverExecBatchFragmentsRequests():996] catch a execute exception
java.util.concurrent.ExecutionException: A error occurred: errorCode=62 errorMessage:method request time out, please check 'onceTalkTimeout' property. current value is:60000(MILLISECONDS) correlationId:725 timeout with bound channel =>[id: 0xf800677e, L:/172.16.1.60:38916
 - R:/172.16.1.62:8060]
        at com.baidu.jprotobuf.pbrpc.client.ProtobufRpcProxy$2.get(ProtobufRpcProxy.java:578) ~[jprotobuf-rpc-core-4.2.1.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecBatchFragmentsRequests(Coordinator.java:990) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.deliverExecFragments(Coordinator.java:615) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:521) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.executeStmtWithExecPlan(StmtExecutor.java:1492) ~[starrocks-fe.jar:?]
        at com.starrocks.statistic.StatisticExecutor.executeDQL(StatisticExecutor.java:230) ~[starrocks-fe.jar:?]
        at com.starrocks.statistic.StatisticExecutor.queryStatisticSync(StatisticExecutor.java:72) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ColumnBasicStatsCacheLoader.queryStatisticsData(ColumnBasicStatsCacheLoader.java:103) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ColumnBasicStatsCacheLoader.lambda$asyncLoadAll$1(ColumnBasicStatsCacheLoader.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_352]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_352]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_352]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_352]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_352]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_352]
Caused by: com.baidu.jprotobuf.pbrpc.ErrorDataException: A error occurred: errorCode=62 errorMessage:method request time out, please check 'onceTalkTimeout' property. current value is:60000(MILLISECONDS) correlationId:725 timeout with bound channel =>[id: 0xf800677e, L:/1
72.16.1.60:38916 - R:/172.16.1.62:8060]
        at com.baidu.jprotobuf.pbrpc.client.ProtobufRpcProxy.doWaitCallback(ProtobufRpcProxy.java:651) ~[jprotobuf-rpc-core-4.2.1.jar:?]
        at com.baidu.jprotobuf.pbrpc.client.ProtobufRpcProxy.access$0(ProtobufRpcProxy.java:611) ~[jprotobuf-rpc-core-4.2.1.jar:?]
        at com.baidu.jprotobuf.pbrpc.client.ProtobufRpcProxy$2.get(ProtobufRpcProxy.java:576) ~[jprotobuf-rpc-core-4.2.1.jar:?]
        ... 14 more
```
2. fe get tablet stats timeout
```
2022-12-27 00:03:57,181 WARN (tablet stat mgr|26) [TabletStatMgr.updateLocalTabletStat():130] task exec error. backend[10004]
org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.thrift.BackendService$Client.recv_get_tablet_stat(BackendService.java:454) ~[starrocks-fe.jar:?]
        at com.starrocks.thrift.BackendService$Client.get_tablet_stat(BackendService.java:442) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.TabletStatMgr.updateLocalTabletStat(TabletStatMgr.java:123) [starrocks-fe.jar:?]
        at com.starrocks.catalog.TabletStatMgr.runAfterCatalogReady(TabletStatMgr.java:72) [starrocks-fe.jar:?]
        at com.starrocks.common.util.LeaderDaemon.runOneCycle(LeaderDaemon.java:60) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_352]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_352]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_352]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_352]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_352]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_352]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_352]
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:125) ~[libthrift-0.13.0.jar:0.13.0]
        ... 11 more
```
3. i got the pstack information
```
hread 473 (Thread 0x7f3b3407f700 (LWP 8983)):
#0  0x00007f3d0927f184 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#1  0x0000000002f08564 in starrocks::TabletManager::_build_tablet_stat() ()
#2  0x0000000002f088c2 in starrocks::TabletManager::get_tablet_stat(starrocks::TTabletStatResult*) ()
#3  0x00000000037e37be in starrocks::BackendServiceProcessor::process_get_tablet_stat(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*) ()
#4  0x00000000037e5422 in starrocks::BackendServiceProcessor::dispatchCall(apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, void*) ()
#5  0x00000000037e7132 in apache::thrift::TDispatchProcessor::process(std::shared_ptr<apache::thrift::protocol::TProtocol>, std::shared_ptr<apache::thrift::protocol::TProtocol>, void*) ()
#6  0x000000000480db28 in apache::thrift::server::TConnectedClient::run() ()
#7  0x0000000004806024 in apache::thrift::server::TThreadedServer::TConnectedClientRunner::run() ()
#8  0x000000000480882d in apache::thrift::concurrency::Thread::threadMain(std::shared_ptr<apache::thrift::concurrency::Thread>) ()
#9  0x00000000047edf96 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(std::shared_ptr<apache::thrift::concurrency::Thread>), std::shared_ptr<apache::thrift::concurrency::Thread> > > >::_M_run() ()
#10 0x0000000006321d20 in execute_native_thread_routine ()
#11 0x00007f3d0927bea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007f3d08896b0d in clone () from /lib64/libc.so.6
Thread 472 (Thread 0x7f38465fe700 (LWP 13836)):
#0  0x00007f3d0928254d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f3d0927de9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f3d0927dd68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x0000000002f08844 in starrocks::TabletManager::get_tablet_stat(starrocks::TTabletStatResult*) ()
#4  0x00000000037e37be in starrocks::BackendServiceProcessor::process_get_tablet_stat(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*) ()
#5  0x00000000037e5422 in starrocks::BackendServiceProcessor::dispatchCall(apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, void*) ()
#6  0x00000000037e7132 in apache::thrift::TDispatchProcessor::process(std::shared_ptr<apache::thrift::protocol::TProtocol>, std::shared_ptr<apache::thrift::protocol::TProtocol>, void*) ()
#7  0x000000000480db28 in apache::thrift::server::TConnectedClient::run() ()
#8  0x0000000004806024 in apache::thrift::server::TThreadedServer::TConnectedClientRunner::run() ()
#9  0x000000000480882d in apache::thrift::concurrency::Thread::threadMain(std::shared_ptr<apache::thrift::concurrency::Thread>) ()
#10 0x00000000047edf96 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(std::shared_ptr<apache::thrift::concurrency::Thread>), std::shared_ptr<apache::thrift::concurrency::Thread> > > >::_M_run() ()
#11 0x0000000006321d20 in execute_native_thread_routine ()
#12 0x00007f3d0927bea5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f3d08896b0d in clone () from /lib64/libc.so.6
Thread 471 (Thread 0x7f3896dff700 (LWP 16188)):
#0  0x00007f3d0928254d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f3d0927de9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f3d0927dd68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x0000000002f08844 in starrocks::TabletManager::get_tablet_stat(starrocks::TTabletStatResult*) ()
#4  0x00000000037e37be in starrocks::BackendServiceProcessor::process_get_tablet_stat(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*) ()
#5  0x00000000037e5422 in starrocks::BackendServiceProcessor::dispatchCall(apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, void*) ()
#6  0x00000000037e7132 in apache::thrift::TDispatchProcessor::process(std::shared_ptr<apache::thrift::protocol::TProtocol>, std::shared_ptr<apache::thrift::protocol::TProtocol>, void*) ()
#7  0x000000000480db28 in apache::thrift::server::TConnectedClient::run() ()
#8  0x0000000004806024 in apache::thrift::server::TThreadedServer::TConnectedClientRunner::run() ()
#9  0x000000000480882d in apache::thrift::concurrency::Thread::threadMain(std::shared_ptr<apache::thrift::concurrency::Thread>) ()
#10 0x00000000047edf96 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(std::shared_ptr<apache::thrift::concurrency::Thread>), std::shared_ptr<apache::thrift::concurrency::Thread> > > >::_M_run() ()
#11 0x0000000006321d20 in execute_native_thread_routine ()
#12 0x00007f3d0927bea5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f3d08896b0d in clone () from /lib64/libc.so.6

Thread 655 (Thread 0x7fdb95fc2700 (LWP 1247)):
#0  0x00007fdc93f1da35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00000000062b640c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#2  0x0000000002f401d4 in starrocks::TabletUpdates::_stop_and_wait_apply_done() ()
#3  0x00000000030c7820 in starrocks::BaseTablet::set_tablet_state(starrocks::TabletState) ()
#4  0x0000000002f0cc6e in starrocks::TabletManager::_drop_tablet_unlocked(long, starrocks::TabletDropFlag) ()
#5  0x0000000002f0cf99 in starrocks::TabletManager::drop_tablet(long, starrocks::TabletDropFlag) ()
#6  0x0000000001d50b85 in starrocks::DropTabletTaskWorkerPool::_worker_thread_callback(void*) ()
#7  0x0000000006321d20 in execute_native_thread_routine ()
#8  0x00007fdc93f19ea5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fdc93534b0d in clone () from /lib64/libc.so.6
Thread 654 (Thread 0x7fdb957c1700 (LWP 1248)):
#0  0x00007fdc93f1d184 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#1  0x0000000002f0979a in starrocks::TabletManager::get_tablet(long, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ()
#2  0x0000000001d50b4a in starrocks::DropTabletTaskWorkerPool::_worker_thread_callback(void*) ()
#3  0x0000000006321d20 in execute_native_thread_routine ()
#4  0x00007fdc93f19ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fdc93534b0d in clone () from /lib64/libc.so.6
Thread 653 (Thread 0x7fdb94fc0700 (LWP 1249)):
#0  0x00007fdc93f1d184 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#1  0x0000000002f0979a in starrocks::TabletManager::get_tablet(long, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ()
#2  0x0000000001d50b4a in starrocks::DropTabletTaskWorkerPool::_worker_thread_callback(void*) ()
#3  0x0000000006321d20 in execute_native_thread_routine ()
#4  0x00007fdc93f19ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fdc93534b0d in clone () from /lib64/libc.so.6
Thread 652 (Thread 0x7fdb947bf700 (LWP 1250)):
#0  0x00007fdc93f1da35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00000000062b640c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#2  0x0000000001d85e48 in starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithReqBody<starrocks::TPushReq> >::_pop_task(starrocks::TPriority::type) ()
#3  0x0000000001d54a3c in starrocks::PushTaskWorkerPool::_worker_thread_callback(void*) ()
#4  0x0000000006321d20 in execute_native_thread_routine ()
#5  0x00007fdc93f19ea5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fdc93534b0d in clone () from /lib64/libc.so.6
Thread 651 (Thread 0x7fdb93fbe700 (LWP 1251)):
#0  0x00007fdc93f1da35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00000000062b640c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#2  0x0000000001d85e48 in starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithReqBody<starrocks::TPushReq> >::_pop_task(starrocks::TPriority::type) ()
#3  0x0000000001d54a3c in starrocks::PushTaskWorkerPool::_worker_thread_callback(void*) ()
#4  0x0000000006321d20 in execute_native_thread_routine ()
#5  0x00007fdc93f19ea5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fdc93534b0d in clone () from /lib64/libc.so.6
Thread 650 (Thread 0x7fdb937bd700 (LWP 1252)):
#0  0x00007fdc93f1da35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
```
4. we can see drop tablet of some tablet will hold a write lock of tablet_manager, and other rpc thread will blocked by this since they can not get the read lock
5. i search the log 'Start to drop ' and 'Succeed to drop' then i found the tablet which blocked on 'drop' operation. tablet id is 95197
6. i assume that the drop operation was blocked by apply, and apply was blocked by persistent index
```
Thread 517 (Thread 0x7f92b2b7b700 (LWP 20212)):
#0  0x0000000001d38750 in __tls_init ()
#1  0x000000000368d961 in my_malloc ()
#2  0x00000000062a8105 in operator new(unsigned long) ()
#3  0x00000000030fac1b in starrocks::ImmutableIndexShard::try_create(unsigned long, unsigned long, unsigned long, std::vector<starrocks::KVRef, std::allocator<starrocks::KVRef> > const&) ()
#4  0x00000000031001a5 in starrocks::ImmutableIndexShard::create(unsigned long, unsigned long, unsigned long, std::vector<starrocks::KVRef, std::allocator<starrocks::KVRef> > const&) ()
#5  0x0000000003100375 in starrocks::ImmutableIndexWriter::write_shard(unsigned long, unsigned long, unsigned long, std::vector<starrocks::KVRef, std::allocator<starrocks::KVRef> > const&) ()
#6  0x0000000003194e00 in starrocks::SliceMutableIndex::flush_to_immutable_index(std::unique_ptr<starrocks::ImmutableIndexWriter, std::default_delete<starrocks::ImmutableIndexWriter> >&, unsigned long, unsigned long, unsigned long) const ()
#7  0x000000000310355a in starrocks::PersistentIndex::_merge_compaction() ()
#8  0x0000000003104bc0 in starrocks::PersistentIndex::_check_and_flush_l0() ()
#9  0x00000000031070c0 in starrocks::PersistentIndex::commit(starrocks::PersistentIndexMetaPB*) ()
#10 0x0000000002e8936e in starrocks::PrimaryIndex::commit(starrocks::PersistentIndexMetaPB*) ()
#11 0x0000000002f59786 in starrocks::TabletUpdates::_apply_rowset_commit(starrocks::TabletUpdates::EditVersionInfo const&) ()
#12 0x0000000002f5e413 in starrocks::TabletUpdates::do_apply() ()
#13 0x0000000003762b55 in starrocks::ThreadPool::dispatch_thread() ()
#14 0x000000000375df8a in starrocks::Thread::supervise_thread(void*) ()
#15 0x00007f92e106fea5 in start_thread () from /lib64/libpthread.so.0
#16 0x00007f92e068ab0d in clone () from /lib64/libc.so.6
```
7. after enable verbose logging we can found that 95197 tablet was blocked in apply logic
```
I1227 15:06:37.795197 20058 tablet.cpp:81] begin to load tablet. tablet=122351.1351566832.8d4cf14baa6ba5b4-92edcf95ac457a9e, version_size=1
I1227 15:06:37.893922 20058 tablet.cpp:81] begin to load tablet. tablet=151010.1351566832.b24d55495197a599-26b50b1755cc15a9, version_size=1
I1227 15:06:37.895197 20059 tablet.cpp:293] no rowset for version:[3501-3501], tablet: 149145.1351566832.6c49a92c0936ca5c-6bd36d74e1576dad
I1227 15:06:37.951970 20060 tablet.cpp:293] no rowset for version:[3407-3407], tablet: 149201.1351566832.174937e921cb8303-191f61f36032fab8
I1227 15:06:37.951970 20058 tablet_manager.cpp:701] Loaded shutdown tablet 164941
I1227 15:06:37.951972 20060 tablet.cpp:293] no rowset for version:[3408-3408], tablet: 149201.1351566832.174937e921cb8303-191f61f36032fab8
I1227 15:06:37.951970 20059 tablet.cpp:81] begin to load tablet. tablet=160120.1351566832.ae4d62e4874809eb-32a2551658889b9a, version_size=1
I1227 15:06:37.951977 20059 tablet_manager.cpp:701] Loaded shutdown tablet 160120
I1227 15:06:37.951974 20060 tablet.cpp:293] no rowset for version:[3409-3409], tablet: 149201.1351566832.174937e921cb8303-191f61f36032fab8
I1227 15:06:44.281643 20059 tablet.cpp:81] begin to load tablet. tablet=95197.70850503.904ef8f4f21421c7-edfb1b159f6b948e, version_size=0
I1227 15:06:44.283646 20059 tablet_updates.cpp:250] load tablet tablet:95197 #version:3 [25 25@0 27] pending: rowsets:26[id/seg/row/del/byte/compaction]: [0/10/1288292/12/94.76 MB/-62.76 MB],[10/10/1289147/10/96.82 MB/-64.81 MB],[20/10/1289383/9/94.74 MB/-62.73 MB],[30/10/1288362/13/90.56 MB/-58.55 MB],[40/10/1288701/11/92.49 MB/-60.49 MB],[50/10/1288709/11/92.58 MB/-60.58 MB],[60/10/1288461/11/91.72 MB/-59.71 MB],[70/10/1289029/6/90.38 MB/-58.38 MB],[80/10/1289095/8/90.61 MB/-58.61 MB],[90/10/1288929/3/91.19 MB/-59.19 MB],[100/10/1288825/3/90.55 MB/-58.55 MB]...,[169/10/1287327/2/92.67 MB/-60.67 MB],[179/10/1288758/6/90.36 MB/-58.36 MB],[189/10/1289321/3/91.28 MB/-59.28 MB],[199/10/1287723/4/92.89 MB/-60.89 MB],[209/10/1288165/1/89.99 MB/-57.99 MB],[219/10/1288324/0/91.40 MB/-59.40 MB],[229/10/1289775/0/91.56 MB/-59.56 MB],[239/10/1289072/0/89.18 MB/-57.18 MB],[249/10/1288292/0/90.65 MB/-58.65 MB]
I1227 15:06:44.283855 20212 tablet_updates.cpp:778] apply_rowset_commit start tablet:95197 version:26 rowset:239
I1227 15:06:44.285840 20212 rowset.cpp:79] rowset is loaded. rowset version:26-26, state from ROWSET_UNLOADED to ROWSET_LOADED. tabletid:95197
I1227 15:06:44.394816 20212 persistent_index.cpp:2887] delete expired index file /mnt/disk3/starrocks/storage/data/181/95197/70850503/index.l1.26.0.tmp
I1227 15:06:44.394856 20212 persistent_index.cpp:2522] load persistent index tablet:95197 version:25 size: 30921733 l0_size: 1289775 l0_capacity:2097152 #shard: 2049 l1_size:29631972 memory: 94375994 status: OK time:54ms
  03: signature (i64) = 95197,
    01: tablet_id (i64) = 95197,
I1227 15:06:49.000291 20572 tablet_manager.cpp:1238] Start to drop tablet 95197
I1227 15:06:49.000310 20572 tablet_manager.cpp:1243] Succeed to stop compaction of tablet 95197
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by caneGuy** [comment]
cc @meegoo @decster @sevev @chaoyli
