### ISSUE TITLE
Throwing exception if created starrocks external table

### ISSUE THREAD

**Issue by blackstar-baba** [StarRocks/starrocks#16014]
### Steps to reproduce the behavior (Required)
I have two starrocks clusters,  i want use external table for copy datas from cluster one (version 2.1.1)   to another (version 2.4.2).
my test scripts like this :
```
# Create a destination table in the destination StarRocks cluster.
CREATE TABLE t
(
    k1 DATE,
    k2 INT,
    k3 SMALLINT,
    k4 VARCHAR(
2048
),
    k5 DATETIME
)
ENGINE=olap
DISTRIBUTED BY HASH(k1) BUCKETS 
10
;

# Create an external table in the source StarRocks cluster.
CREATE EXTERNAL TABLE external_t
(
    k1 DATE,
    k2 INT,
    k3 SMALLINT,
    k4 VARCHAR(
2048
),
    k5 DATETIME
)
ENGINE=olap
DISTRIBUTED BY HASH(k1) BUCKETS 
10

PROPERTIES
(
    "host" = "xx.xx.xx.xx",
    "port" = "9020",
    "user" = "root",
    "password" = "123456",
    "database" = "test",
    "table" = "t"
);
```

### Expected behavior (Required)
No errors in `fe.log`

### Real behavior (Required)
some warn log in `fe.log` like this:
```
2022-12-30 13:47:49,212 WARN (star rocks repository|38) [TableMetaSyncer.syncTable():53] call fe TNetworkAddress(hostname:xx.xx.xx.xx, port:9020) refreshTable rpc method failed
org.apache.thrift.TApplicationException: Required field 'host' was not present! Struct: TAuthenticateParams(user:root, passwd:123456, host:null, db_name:null, table_names:null)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79) ~[libthrift-0.13.0.jar:0.13.0]
	at com.starrocks.thrift.FrontendService$Client.recv_getTableMeta(FrontendService.java:643) ~[starrocks-fe.jar:?]
	at com.starrocks.thrift.FrontendService$Client.getTableMeta(FrontendService.java:630) ~[starrocks-fe.jar:?]
	at com.starrocks.external.starrocks.TableMetaSyncer.syncTable(TableMetaSyncer.java:44) [starrocks-fe.jar:?]
	at com.starrocks.external.starrocks.StarRocksRepository.runAfterCatalogReady(StarRocksRepository.java:77) [starrocks-fe.jar:?]
	at com.starrocks.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:61) [starrocks-fe.jar:?]
	at com.starrocks.external.starrocks.StarRocksRepository.runOneCycle(StarRocksRepository.java:55) [starrocks-fe.jar:?]
	at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]

```

### StarRocks version (Required)
- Cluster One: 2.1.1
- Cluster Two: 2.4.2

**Comment by blackstar-baba** [comment]
I find some commits which changed the thrift protocol caused this exception: 
https://github.com/StarRocks/starrocks/commit/160d01279323aa753f8f576f75059b93344a21e1
