### ISSUE TITLE
Query hudi catalog, got: MERGE_ON_READ type of hudi table is NOT supported.

### ISSUE THREAD

**Issue by zh-jn** [StarRocks/starrocks#16329]
### Steps to reproduce the behavior (Required)
1. create hudi table in spark_sql:
```
CREATE TABLE zjn_test.hudi_tbl (
  id BIGINT,
  name STRING,
  p STRING)
USING hudi
PARTITIONED BY (p)
LOCATION 'hdfs://xxx/zjn_test/hudi_tbl'
TBLPROPERTIES (
  'primaryKey' = 'id',
  'type' = 'mor')
```

2. create hudi catalog:
```
create external catalog hudi properties ('type' = 'hudi', 'hive.metastore.uris' = 'thrift://127.0.0.1:9083')
```

3. select hudi table in doris:
```
select * from hudi.zjn_test.hudi_tbl;
```
got Error in CLI: "ERROR 1064 (HY000): Unknown table 'hudi_tbl'"
exception in fe log: 
2023-01-06 19:45:58,310 ERROR (starrocks-mysql-nio-pool-4|183) [HiveMetaCache.getTable():316] Failed to get table [databaseName: zjn_test, tableName: hudi_tbl]
java.util.concurrent.ExecutionException: com.starrocks.common.DdlException: MERGE_ON_READ type of hudi table is NOT supported.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:527) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:104) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:240) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2313) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2279) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.external.hive.HiveMetaCache.getTable(HiveMetaCache.java:314) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hudi.HudiMetadata.getTable(HudiMetadata.java:61) ~[starrocks-fe.jar:?]
	at com.starrocks.server.MetadataMgr.lambda$getTable$1(MetadataMgr.java:114) ~[starrocks-fe.jar:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_181]
	at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:114) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer.resolveTable(QueryAnalyzer.java:665) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer.access$100(QueryAnalyzer.java:65) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.resolveTableRef(QueryAnalyzer.java:234) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:160) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:82) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:206) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:87) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:105) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:99) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:82) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:36) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:87) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:75) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:224) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:82) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:36) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:129) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:84) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:79) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:55) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:39) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:370) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: com.starrocks.common.DdlException: MERGE_ON_READ type of hudi table is NOT supported.
	at com.starrocks.catalog.HudiTable.initProps(HudiTable.java:282) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.HudiTable.<init>(HudiTable.java:104) ~[starrocks-fe.jar:?]
	at com.starrocks.external.HiveMetaStoreTableUtils.convertHudiConnTableToSRTable(HiveMetaStoreTableUtils.java:369) ~[starrocks-fe.jar:?]
	at com.starrocks.external.hive.HiveMetaCache.loadTable(HiveMetaCache.java:327) ~[starrocks-fe.jar:?]
	at com.starrocks.external.hive.HiveMetaCache.access$700(HiveMetaCache.java:40) ~[starrocks-fe.jar:?]
	at com.starrocks.external.hive.HiveMetaCache$8.load(HiveMetaCache.java:145) ~[starrocks-fe.jar:?]
	at com.starrocks.external.hive.HiveMetaCache$8.load(HiveMetaCache.java:142) ~[starrocks-fe.jar:?]
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
	... 39 more

### Expected behavior (Required)
can query hudi MOR table:
![捕获](https://user-images.githubusercontent.com/15308244/211009157-a32d6466-898b-46a1-a0dd-95ebb1384658.PNG)

### Real behavior (Required)
not support MOR table

### StarRocks version (Required)
2.4.1

**Comment by wangyouzhuo** [comment]
It seems that there is some issues in version 2.4-latest's release note. We will fix this as soon as possible.
The Hudi MOR is supported in version 2.5.0, not in version 2.4.x. If you want to have a try on it, you need to upgrade it to 2.5RC version or main branch. And 2.5 will GA in this month.

**Comment by zh-jn** [comment]
ok,  i will have a try on version 2.5.
