### ISSUE TITLE
Query returns error with hive external table

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#1657]
### Steps to reproduce the behavior (Required)
1. CREATE EXTERNAL RESOURCE "hive_resource_stability"  PROPERTIES (  "type" = "hive",  "hive.metastore.uris" = "thrift://172.26.194.118:9083"  );
2. CREATE EXTERNAL TABLE `ssb_orc_1t_customer` (
  `c_custkey` int(11) NULL COMMENT "",
  `c_name` varchar(26) NULL COMMENT "",
  `c_address` varchar(41) NULL COMMENT "",
  `c_city` varchar(11) NULL COMMENT "",
  `c_nation` varchar(16) NULL COMMENT "",
  `c_region` varchar(13) NULL COMMENT "",
  `c_phone` varchar(16) NULL COMMENT "",
  `c_mktsegment` varchar(11) NULL COMMENT ""
) ENGINE=HIVE
COMMENT "PARTITION BY ()"
PROPERTIES (
"database" = "ssb_orc_1t",
"table" = "customer",
"resource" = "hive_resource_stability",
"hive.metastore.uris"  =  "thrift://172.26.194.118:9083"
);
3. select        sum(       cast(random() as DOUBLE)) over (partition by ref_0.c_nation order by ref_0.c_address,ref_0.c_mktsegment) as c6,    timediff(     cast(cast(null as DATETIME) as DATETIME),     cast(case when ((cast(null as DOUBLE) < cast(null as DOUBLE))            and (ref_0.c_custkey > ref_0.c_custkey))          or (ref_0.c_mktsegment <> ref_0.c_nation) then cast(null as DATETIME) else cast(null as DATETIME) end        as DATETIME)) as c18 from   ssb_orc_1t_customer as ref_0;

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
ERROR 1064 (HY000): java.lang.Integer cannot be cast to java.lang.Double

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main `a7c9e90` ASAN

**Comment by wangruin** [comment]
`2021-11-26 17:25:19,388 WARN (starrocks-mysql-nio-pool-17|792) [StmtExecutor.execute():465] execute Exception, sql select        sum(       cast(random() as DOUBLE)) over (partition by ref_0.c_nation order by ref_0.c_address,ref_0.c_mktsegment) as c6,    timediff(     cast(cast(null as DATETIME) as DATETIME),     cast(case when ((cast(null as DOUBLE) < cast(null as DOUBLE))            and (ref_0.c_custkey > ref_0.c_custkey))          or (ref_0.c_mktsegment <> ref_0.c_nation) then cast(null as DATETIME) else cast(null as DATETIME) end        as DATETIME)) as c18 from    sqlsmith.ssb_orc_1t_customer as ref_0
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
        at com.starrocks.sql.optimizer.operator.scalar.ConstantOperator.getTime(ConstantOperator.java:224) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.doubleValueFromConstant(ExpressionStatisticCalculator.java:253) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.access$000(ExpressionStatisticCalculator.java:26) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitConstant(ExpressionStatisticCalculator.java:59) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitConstant(ExpressionStatisticCalculator.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ConstantOperator.accept(ConstantOperator.java:275) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:34) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:30) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitOperator(StatisticsCalculator.java:176) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeAnalyticNode(StatisticsCalculator.java:1155) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalAnalytic(StatisticsCalculator.java:1134) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalAnalytic(StatisticsCalculator.java:118) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalWindowOperator.accept(LogicalWindowOperator.java:77) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:134) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:148) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:81) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:48) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:299) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:248) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:397) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:633) [starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:54) [starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener$$Lambda$248/1303224047.run(Unknown Source) [starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_41]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_41]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_41]
(END)`
