### ISSUE TITLE
failed to generate the source 

### ISSUE THREAD

**Issue by liukun4515** [StarRocks/starrocks#16699]
## General Question

I read the doc https://github.com/StarRocks/community/blob/main/Contributors/guide/IDEA.md#generate-source-code to generate the source code, but got error message:

```
/Library/Developer/CommandLineTools/usr/bin/make -C script
/Users/kliu3/Documents/github/starrocks/gensrc/script/../../build-support/gen_build_version.py --cpp /Users/kliu3/Documents/github/starrocks/gensrc/script/../build//gen_cpp --java /Users/kliu3/Documents/github/starrocks/gensrc/script/../../fe/fe-core/target/generated-sources/build
Traceback (most recent call last):
  File "/Users/kliu3/Documents/github/starrocks/gensrc/script/../../build-support/gen_build_version.py", line 190, in <module>
    main()
  File "/Users/kliu3/Documents/github/starrocks/gensrc/script/../../build-support/gen_build_version.py", line 184, in main
    java_version = get_java_version()
  File "/Users/kliu3/Documents/github/starrocks/gensrc/script/../../build-support/gen_build_version.py", line 62, in get_java_version
    java_res = subprocess.Popen([java_home + "/bin/java", "-fullversion"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
make[1]: *** [gen_version] Error 1
make: *** [script] Error 2
```

And I following the preparation:
1. create install `thrift`,`proto` with the right version, and link them to the right path
2. create thirdparty dir
3. jdk is oracle jdk8.
```
bin/java -fullversion
java full version "1.8.0_271-b09"

java -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
```

**Comment by liukun4515** [comment]
resolved

**Comment by xiabaike** [comment]
hi, I met the same problem, may I ask you how?
