### ISSUE TITLE
Constant-cmp-Column not supported here, should be deal earlier

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#1689]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS h55;
CREATE DATABASE h55;
USE h55;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 BOOLEAN NULL ,c_0_1 VARCHAR(11) NULL ) DUPLICATE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL32(8, 3)  NULL ,c_1_1 DECIMAL128(10, 7)  NOT NULL ,c_1_2 DECIMAL64(1, 0)  REPLACE_IF_NOT_NULL NULL ,c_1_3 DECIMAL64(3, 0)  MIN NULL ,c_1_4 HLL HLL_UNION NULL ) AGGREGATE KEY (c_1_0,c_1_1) DISTRIBUTED BY HASH (c_1_1) properties("replication_num"="1") ;
CREATE TABLE t2 (c_2_0 SMALLINT NULL ,c_2_1 DATE NOT NULL ,c_2_2 DECIMAL64(12, 10)  NOT NULL ,c_2_3 VARCHAR(11) NULL ,c_2_4 DECIMAL128(17, 16)  NOT NULL ,c_2_5 CHAR(11) NOT NULL ,c_2_6 VARCHAR(11) MIN NULL ,c_2_7 DECIMAL128(17, 16)  REPLACE NULL ,c_2_8 FLOAT MIN NOT NULL ,c_2_9 SMALLINT SUM NOT NULL ) AGGREGATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5) DISTRIBUTED BY HASH (c_2_2,c_2_0,c_2_5) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 DECIMAL128(24, 9)  NULL ,c_3_1 BOOLEAN REPLACE NULL ,c_3_2 PERCENTILE PERCENTILE_UNION NOT NULL ,c_3_3 HLL HLL_UNION NULL ,c_3_4 DECIMAL64(17, 11)  MIN NOT NULL ) AGGREGATE KEY (c_3_0) DISTRIBUTED BY HASH (c_3_0) properties("replication_num"="1") ;
INSERT INTO t1 VALUES (59.055, 0.0000348, 4, 675, hll_hash("7")), (84.690, 0.0000201, 2, 818, hll_hash("6kmL9"));
INSERT INTO t0 VALUES (true, "wIFrKGw"), (false, NULL);
2.  SELECT subt0.c_0_0 FROM  (SELECT t0.c_0_0, t0.c_0_1 FROM t0 WHERE false) subt0 LEFT SEMI JOIN (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7, t2.c_2_8, t2.c_2_9 FROM t2) subt2 ON subt0.c_0_0 = subt2.c_2_0 AND  ( subt2.c_2_9 ) > ( subt2.c_2_9 )  <= subt2.c_2_0 AND subt0.c_0_0 > subt2.c_2_5 AND subt0.c_0_0 > subt2.c_2_5 GROUP BY subt0.c_0_0, subt0.c_0_1, subt0.c_0_0 HAVING ((MAX(CASE  WHEN false THEN true  WHEN (subt0.c_0_1)  BETWEEN (subt0.c_0_1) AND (subt0.c_0_1)  THEN (subt0.c_0_1) IN ("")  ELSE false END) ) IS NULL) ORDER BY subt0.c_0_0 DESC, subt0.c_0_1 ASC, subt0.c_0_0 ASC;

### Expected behavior (Required)
execute correct
### Real behavior (Required)
--java.lang.AssertionError: SELECT subt0.c_0_0 FROM  (SELECT t0.c_0_0, t0.c_0_1 FROM t0 WHERE false) subt0 LEFT SEMI JOIN (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7, t2.c_2_8, t2.c_2_9 FROM t2) subt2 ON subt0.c_0_0 = subt2.c_2_0 AND  ( subt2.c_2_9 ) > ( subt2.c_2_9 )  <= subt2.c_2_0 AND subt0.c_0_0 > subt2.c_2_5 AND subt0.c_0_0 > subt2.c_2_5 GROUP BY subt0.c_0_0, subt0.c_0_1, subt0.c_0_0 HAVING ((MAX(CASE  WHEN false THEN true  WHEN (subt0.c_0_1)  BETWEEN (subt0.c_0_1) AND (subt0.c_0_1)  THEN (subt0.c_0_1) IN ("")  ELSE false END) ) IS NULL) ORDER BY subt0.c_0_0 DESC, subt0.c_0_1 ASC, subt0.c_0_0 ASC;
--	at sqlancer.common.query.QueryAdapter.checkException(QueryAdapter.java:98)
--	at sqlancer.common.query.QueryAdapter.executeAndGet(QueryAdapter.java:128)
--	at sqlancer.ComparatorHelper.getResultSetFirstColumnAsString(ComparatorHelper.java:54)
--	at sqlancer.ComparatorHelper.getCombinedResultSet(ComparatorHelper.java:130)
--	at sqlancer.doris.oracle.tlp.DorisTLPHavingOracle.check(DorisTLPHavingOracle.java:45)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:59)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:337)
--	at sqlancer.Main$2.run(Main.java:520)
--	at sqlancer.Main$2.runThread(Main.java:498)
--	at sqlancer.Main$2.run(Main.java:488)
--	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
--	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
--	at java.lang.Thread.run(Thread.java:748)
--Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Constant-cmp-Column not supported here, should be deal earlier
--	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
--	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
--	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
--	at com.mysql.jdbc.Util.getInstance(Util.java:408)
--	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
--	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
--	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2497)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2455)
--	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
--	at sqlancer.common.query.QueryAdapter.executeAndGet(QueryAdapter.java:118)

fe.log:
java.lang.IllegalStateException: ConstantRef-cmp-ConstantRef not supported here, should be eliminated earlier: false >= true
        at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:157)
 ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:30) 
~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator.statisticsCalculate(PredicateStatisticsCalculator.java:27) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimateStatistics(StatisticsCalculator.java:1176) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitOperator(StatisticsCalculator.java:159) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeOlapScanNode(StatisticsCalculator.java:230) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalOlapScan(StatisticsCalculator.java:193) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalOlapScan(StatisticsCalculator.java:123) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalOlapScanOperator.accept(LogicalOlapScanOperator.java:119) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:139) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:158) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:81) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:48) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:299) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:265) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:414) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:650) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:54) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.0 release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_BRANCH_RELEASE 49b22bf |
+---------------------------------+

**Comment by Seaven** [comment]
I didn't reproduce the problem, so I add check frist
