### ISSUE TITLE
enable_auth_check not work on new priv framework

### ISSUE THREAD

**Issue by nshangyiming** [StarRocks/starrocks#17125]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
2023-01-31 17:41:24,990 INFO (tablet scheduler|46) [ClusterLoadStatistic.classifyBackendByLoad():165] classify backend by load. medium: HDD, avg load score: 0.5, low/mid/high: 0/1/0
2023-01-31 17:41:25,250 INFO (starrocks-mysql-nio I/O-4|137) [AcceptListener.handleEvent():70] Connection established. remote=/172.26.92.139:46028
2023-01-31 17:41:25,252 WARN (starrocks-mysql-nio-pool-1|156) [AcceptListener.lambda$handleEvent$1():108] connect processor exception because
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_202]
        at com.starrocks.qe.ConnectScheduler.registerConnection(ConnectScheduler.java:133) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.AcceptListener.lambda$handleEvent$1(AcceptListener.java:87) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by nshangyiming** [comment]
it works on branch-2.5 after test

**Comment by nshangyiming** [comment]
this pr https://github.com/StarRocks/starrocks/pull/11317 fixed this problem before

**Comment by nshangyiming** [comment]
https://github.com/StarRocks/starrocks/issues/18267 redirect to this issue , close this one first
