### ISSUE TITLE
[RBAC] load image failed after upgrade

### ISSUE THREAD

**Issue by nshangyiming** [StarRocks/starrocks#17208]
### Steps to reproduce the behavior (Required)
1. start fe with 2.5.0
2. execute the following statements
```
create user testuser1 identified by '12345678';
set password for root = password('123456');
create user testuser2 identified by '';
```
3. restart and upgrade to main 
4. stop fe
5. restart again

### Expected behavior (Required)
restart normally

### Real behavior (Required)
```
2023-02-01 18:39:25,038 WARN (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: UNKNOWN
2023-02-01 18:39:25,064 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [BDBEnvironment.setupEnvironment():297] replicated environment is all set, wait for state change...
2023-02-01 18:39:27,044 WARN (RepNode 172.18.0.1_9711_1675246705902(-1)|70) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: LEADER
2023-02-01 18:39:27,065 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [BDBEnvironment.setupEnvironment():305] state change done, current role LEADER
2023-02-01 18:39:27,073 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [BDBEnvironment.setupEnvironment():309] end setup bdb environment after 1 times
2023-02-01 18:39:27,077 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [GlobalStateMgr.loadImage():1297] start load image from /home/disk5/shangyiming/starrocks.np/output/fe/meta/image/image.21. is ckpt: false
2023-02-01 18:39:27,077 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [GlobalStateMgr.loadHeader():1472] finished replay header from image
2023-02-01 18:39:27,077 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [NodeMgr.loadLeaderInfo():1115] finished replay masterInfo from image
2023-02-01 18:39:27,078 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [LocalMetastore.loadDb():349] finished replay databases from image
2023-02-01 18:39:27,079 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [Load.loadLoadJob():999] finished replay loadJob from image
2023-02-01 18:39:27,079 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [GlobalStateMgr.loadAlterJob():1487] finished replay alterJob from image
2023-02-01 18:39:27,080 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [CatalogRecycleBin.loadRecycleBin():1159] finished replay recycleBin from image
2023-02-01 18:39:27,088 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [VariableMgr.loadGlobalVariable():574] finished replay globalVariable from image
2023-02-01 18:39:27,100 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [LocalMetastore.loadCluster():4359] finished replay cluster from image
2023-02-01 18:39:27,100 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [NodeMgr.loadBrokers():1083] finished replay brokerMgr from image
2023-02-01 18:39:27,153 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [GlobalStateMgr.loadResources():1573] finished replay resources from image
2023-02-01 18:39:27,153 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [GlobalStateMgr.loadResources():1575] start to replay resource mapping catalog
2023-02-01 18:39:27,154 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [GlobalStateMgr.loadResources():1577] finished replaying resource mapping catalogs from resources
2023-02-01 18:39:27,154 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [ExportMgr.loadExportJob():414] finished replay exportJob from image
2023-02-01 18:39:27,154 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [BackupHandler.readFields():688] finished replay 0 backup/store jobs from image
2023-02-01 18:39:27,154 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [BackupHandler.loadBackupHandler():701] finished replay backupHandler from image
2023-02-01 18:39:27,157 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [Auth.loadAuth():1969] finished replay auth from image
2023-02-01 18:39:27,160 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [GlobalTransactionMgr.loadTransactionState():750] finished replay transactionState from image
2023-02-01 18:39:27,160 WARN (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [ColocateTableIndex.cleanupInvalidDbOrTable():988] remove 0 invalid tableid: []
2023-02-01 18:39:27,160 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [ColocateTableIndex.loadColocateTableIndex():841] finished replay colocateTableIndex from image
2023-02-01 18:39:27,160 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [RoutineLoadManager.loadRoutineLoadJobs():689] finished replay routineLoadJobs from image
2023-02-01 18:39:27,160 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [LoadManager.loadLoadJobsV2():722] finished replay loadJobsV2 from image
2023-02-01 18:39:27,161 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [SmallFileMgr.loadSmallFiles():549] finished replay smallFiles from image
2023-02-01 18:39:27,161 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [PluginMgr.loadPlugins():352] finished replay plugins from image
2023-02-01 18:39:27,163 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [GlobalStateMgr.loadDeleteHandler():1551] finished replay deleteHandler from image
2023-02-01 18:39:27,171 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [AnalyzeManager.loadAnalyze():419] finished replay analyze job from image
2023-02-01 18:39:27,176 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [ResourceGroupMgr.loadResourceGroups():243] finished replaying ResourceGroups from image
2023-02-01 18:39:27,182 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [TaskManager.loadTasks():456] finished replaying TaskManager from image
2023-02-01 18:39:27,184 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [CatalogMgr.loadCatalogs():224] finished replaying CatalogMgr from image
2023-02-01 18:39:27,187 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [SystemInfoService.loadComputeNodes():871] finished replaying compute node from image
2023-02-01 18:39:27,187 INFO (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [GlobalStateMgr.loadShardManager():1583] finished replay shardManager from image
2023-02-01 18:39:27,201 ERROR (UNKNOWN 172.18.0.1_9711_1675246705902(-1)|1) [StarRocksFE.start():183] StarRocksFE start failed
java.lang.NegativeArraySizeException: null
        at com.starrocks.common.io.Text.readStringWithChecksum(Text.java:445) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.metablock.SRMetaBlockReader.close(SRMetaBlockReader.java:109) ~[starrocks-fe.jar:?]
        at com.starrocks.authentication.AuthenticationManager.load(AuthenticationManager.java:494) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadRBACPrivilege(GlobalStateMgr.java:1493) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1359) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:950) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:129) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:81) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by nshangyiming** [comment]
fixed by #17452
