### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#17256]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t0(c0 INT);

### Expected behavior (Required)
create table failed.

### Real behavior (Required)
```
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

### StarRocks version (Required)
 5c18df0

**Comment by sduzh** [comment]
```
2023-02-02 18:39:04,473 WARN (starrocks-mysql-nio-pool-0|152) [ReadListener.lambda$handleEvent$0():76] Exception happened in one session(com.starrocks.mysql.nio.NConnectContext@62b8f65).
java.lang.NullPointerException: null
        at com.starrocks.sql.ast.CreateTableStmt.isOlapEngine(CreateTableStmt.java:202) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.CreateTableStmt.isOlapOrLakeEngine(CreateTableStmt.java:210) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.CreateTableStmt.needAuditEncryption(CreateTableStmt.java:275) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.auditAfterExec(ConnectProcessor.java:208) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:378) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:454) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:700) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:68) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```
