### ISSUE TITLE
query lake table throw unknown error

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#17419]
### Steps to reproduce the behavior (Required)
```
create table t1(c0 INT, c1 array<varchar(65533)>) duplicate key(c0) distributed by hash(c0) buckets 1 properties('replication_num'='1');
insert into t1 values(1, ['x']),(2, ['y']),(3, ['z']);
insert into t1 values(4, ['a']),(5, ['b']),(6, ['c']);
insert into t1 values(100, ['100']),(100, ['100']),(100, ['100']);
delete from t1 where c0=1;
delete from t1 where c0=3;
delete from t1 where c0=5;
delete from t1 where c0>10;
select c1, c0 from t1 order by c0;
```

### Expected behavior (Required)
```
+-------+------+
| c1    | c0   |
+-------+------+
| ["y"] |    2 |
| ["a"] |    4 |
| ["c"] |    6 |
+-------+------+
```
### Real behavior (Required)
```
ERROR 1064 (HY000): Unknown error
```

### StarRocks version (Required)
 - 4e44295c999d03a2f0f9cbd53a41b7d0fd79deeb

**Comment by sduzh** [comment]
fe.warn.log
```
java.lang.NullPointerException: null
	at com.starrocks.lake.LakeTablet.getPrimaryBackendId(LakeTablet.java:83) ~[starrocks-fe.jar:?]
	at com.starrocks.lake.Utils.chooseBackend(Utils.java:54) ~[starrocks-fe.jar:?]
	at com.starrocks.lake.DeleteLakeTableTask.run(DeleteLakeTableTask.java:68) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.Database.dropTable(Database.java:487) ~[starrocks-fe.jar:?]
	at com.starrocks.server.LocalMetastore.dropTable(LocalMetastore.java:2868) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.dropTable(GlobalStateMgr.java:2599) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.lambda$visitDropTableStatement$6(DDLStmtExecutor.java:244) ~[starrocks-fe.jar:?]
	at com.starrocks.common.ErrorReport.wrapWithRuntimeException(ErrorReport.java:108) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitDropTableStatement(DDLStmtExecutor.java:243) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitDropTableStatement(DDLStmtExecutor.java:140) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.DropTableStmt.accept(DropTableStmt.java:71) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor.execute(DDLStmtExecutor.java:126) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1141) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:501) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:337) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:454) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:712) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:68) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```
