### ISSUE TITLE
Query returns not implement builder

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#1753]
### Steps to reproduce the behavior (Required)
1. CREATE EXTERNAL RESOURCE "hive_resource_stability" PROPERTIES ( "type" = "hive", "hive.metastore.uris" = "thrift://172.26.194.118:9083" );
2. CREATE TABLE primary_table (
k1 datetime NOT NULL COMMENT "",
k2 varchar(65533) NOT NULL COMMENT "",
k3 varchar(65533) NOT NULL COMMENT "",
k4 boolean NOT NULL COMMENT "",
v1 tinyint(4) NOT NULL COMMENT "",
v2 smallint(6) NOT NULL COMMENT "",
v3 int(11) NOT NULL COMMENT "",
v4 double NOT NULL COMMENT "",
v5 decimal128(27, 9) NOT NULL COMMENT ""
) ENGINE=OLAP
PRIMARY KEY(k1, k2, k3, k4)
COMMENT "OLAP"
DISTRIBUTED BY HASH(k1, k2, k3, k4) BUCKETS 3
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. CREATE EXTERNAL TABLE ssb_orc_1t_part (
p_partkey int(11) NULL COMMENT "",
p_name varchar(23) NULL COMMENT "",
p_mfgr varchar(7) NULL COMMENT "",
p_category varchar(8) NULL COMMENT "",
p_brand varchar(10) NULL COMMENT "",
p_color varchar(12) NULL COMMENT "",
p_type varchar(26) NULL COMMENT "",
p_size int(11) NULL COMMENT "",
p_container varchar(11) NULL COMMENT ""
) ENGINE=HIVE
COMMENT "PARTITION BY ()"
PROPERTIES (
"database" = "ssb_orc_1t",
"table" = "part",
"resource" = "hive_resource_stability",
"hive.metastore.uris" = "thrift://172.26.194.118:9083"
);
3. CREATE EXTERNAL TABLE `hive_external_test` (
  `col_date` date NULL COMMENT "column date",
  `col_tinyint` tinyint(4) NULL COMMENT "column tinyint",
  `col_string` varchar(1000) NULL COMMENT "column string",
  `col_smallint` smallint(6) NULL COMMENT "column smallint",
  `col_int` int(11) NULL COMMENT "column int",
  `col_integer` int(11) NULL COMMENT "column integer",
  `col_bigint` bigint(20) NULL COMMENT "column bigint",
  `col_float` float NULL COMMENT "column float",
  `col_double` double NULL COMMENT "column double",
  `col_double_precision` double NULL COMMENT "column double precision",
  `col_decimal` decimal64(10, 0) NULL COMMENT "column decimal",
  `col_timestamp` datetime NULL COMMENT "column timestamp",
  `col_varchar` varchar(100) NULL COMMENT "colu
mn varchar",
  `col_binary` varchar(1000) NULL COMMENT "column binary",
  `col_boolean` boolean NULL COMMENT "column boolean"
) ENGINE=HIVE
COMMENT "PARTITION BY ()"
PROPERTIES (
"database" = "hive_extbl_test_1636019895543",
"table" = "hive_hdfs_orc_nocompress",
"resource" = "hive_resource",
"hive.metastore.uris"  =  "thrift://172.26.92.141:9083"
);
4. CREATE EXTERNAL TABLE `ssb_orc_1t_supplier` (
  `s_suppkey` int(11) NULL COMMENT "",
  `s_name` varchar(26) NULL COMMENT "",
  `s_address` varchar(26) NULL COMMENT "",
  `s_city` varchar(11) NULL COMMENT "",
  `s_nation` varchar(16) NULL COMMENT "",
  `s_region` varchar(13) NULL COMMENT "",
  `s_phone` varchar(16) NULL COMMENT ""
) ENGINE=HIVE
COMMENT "PARTITION BY ()"
PROPERTIES (
"database" = "ssb_orc_1t",
"table" = "supplier",
"resource" = "hive_resource_stability",
"hive.metastore.uris"  =  "thrift://172.26.194.118:9083"
);
5. select     ref_2.col_varchar as c0,    case when true then ref_1.p_mfgr else ref_1.p_mfgr end
     as c1,    ref_2.col_bigint as c2,    case when false then ref_1.p_partkey else ref_1.p_partkey end
as c3,    case when ref_1.p_partkey <= ref_2.col_int then ref_2.col_date else ref_2.col_date end      as c4 from    (select                 ref_0.k4 as c0,                ref_0.v1 as c1,                ref_0.k4 as c2 from                sqlsmith.primary_table as ref_0             where ((false)                  or (ref_0.v3 = ref_0.v3))                or (ref_0.k2 <> ref_0.k3)             limit 164) as subq_0         inner join sqlsmith.ssb_orc_1t_part as ref_1         on (subq_0.c2 = ref_1.p_partkey )       inner join sqlsmith.hive_external_test as ref_2       on (ref_1.p_mfgr = ref_2.col_string )     inner join sqlsmith.ssb_orc_1t_supplier as ref_3     on (subq_0.c0 = ref_3.s_suppkey ) where (ref_1.p_partkey < case when true then 55 else 55 end       )    and ((ref_3.s_name > ref_1.p_container)      or (cast(null as DOUBLE) < ref_2.col_double)) limit 141;

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
ERROR 1064 (HY000): not implement builder

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main `97f2592` release

**Comment by wangruin** [comment]
```
com.starrocks.sql.common.StarRocksPlannerException: not implement builder
	at com.starrocks.sql.optimizer.operator.OperatorBuilderFactory.build(OperatorBuilderFactory.java:64) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.transformation.JoinAssociativityRule.transform(JoinAssociativityRule.java:175) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.ApplyRuleTask.execute(ApplyRuleTask.java:66) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:36) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:150) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:81) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:48) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:299) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:248) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:397) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:633) [starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:54) [starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener$$Lambda$250/150207903.run(Unknown Source) [starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_41]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_41]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_41]
```
