### ISSUE TITLE
Query returns error

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#1759]
### Steps to reproduce the behavior (Required)
1. CREATE EXTERNAL RESOURCE "hive_resource_stability" PROPERTIES ( "type" = "hive", "hive.metastore.uris" = "thrift://172.26.194.118:9083" );
2. CREATE EXTERNAL TABLE `ssb_orc_1t_customer` (
  `c_custkey` int(11) NULL COMMENT "",
  `c_name` varchar(26) NULL COMMENT "",
  `c_address` varchar(41) NULL COMMENT "",
  `c_city` varchar(11) NULL COMMENT "",
  `c_nation` varchar(16) NULL COMMENT "",
  `c_region` varchar(13) NULL COMMENT "",
  `c_phone` varchar(16) NULL COMMENT "",
  `c_mktsegment` varchar(11) NULL COMMENT ""
) ENGINE=HIVE
COMMENT "PARTITION BY ()"
PROPERTIES (
"database" = "ssb_orc_1t",
"table" = "customer",
"resource" = "hive_resource_stability",
"hive.metastore.uris"  =  "thrift://172.26.194.118:9083"
);
3. CREATE TABLE `metrics_detail` (
  `tags_id` int(11) NULL COMMENT "",
  `timestamp` datetime NULL COMMENT "",
  `value` double SUM NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`tags_id`, `timestamp`)
COMMENT "OLAP"
PARTITION BY RANGE(`timestamp`)
(PARTITION p20200704 VALUES [('0000-01-01 00:00:00'), ('2020-07-05 00:00:00')))
DISTRIBUTED BY HASH(`tags_id`) BUCKETS 32
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
4. CREATE TABLE `test_cross_join_30` (
  `id_int` int(11) NOT NULL COMMENT "",
  `id_double` double NOT NULL COMMENT "",
  `id_varchar` varchar(100) NOT NULL COMMENT "",
  `id_datetime` datetime NOT NULL COMMENT "",
  `id_decimal` decimal128(20, 3) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`id_int`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id_int`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
5. CREATE EXTERNAL TABLE `external_mysql_table_with_null` (
  `id_tinyint` tinyint(4) NULL COMMENT "",
  `id_smallint` smallint(6) NULL COMMENT "",
  `id_int` int(11) NULL COMMENT "",
  `id_float` float NULL COMMENT "",
  `id_double` double NULL COMMENT "",
  `id_decimal` decimal128(27, 9) NULL COMMENT "",
  `id_date` date NULL COMMENT "",
  `id_datetime` datetime NULL COMMENT "",
  `id_char` char(20) NULL COMMENT "",
  `id_varchar` varchar(20) NULL COMMENT ""
) ENGINE=MYSQL
COMMENT "MYSQL"
PROPERTIES (
"host" = "172.26.92.139",
"port" = "3306",
"user" = "root",
"password" = "",
"database" = "doris_external",
"table" = "mysql_external_null"
);
6. SELECT   * from   sqlsmith.ssb_orc_1t_customer as ref_0   right join sqlsmith.metrics_detail as ref_1
on (ref_0.c_custkey = ref_1.tags_id)   right join sqlsmith.metrics_detail as ref_2 on (ref_1.tags_id = ref_2.tags_id)   inner join sqlsmith.test_cross_join_30 as ref_3 on (ref_1.tags_id = ref_3.id_int)   inner join sqlsmith.external_mysql_table_with_null as ref_4 on (ref_3.id_int = ref_4.id_tinyint);

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
ERROR 1064 (HY000): Must be replicate join or colocate join

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main `97f2592` release

**Comment by wangruin** [comment]
```
java.lang.IllegalStateException: Must be replicate join or colocate join
	at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashJoin(PlanFragmentBuilder.java:1334) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashJoin(PlanFragmentBuilder.java:225) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.physical.PhysicalHashJoinOperator.accept(PhysicalHashJoinOperator.java:57) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:234) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDecode(PlanFragmentBuilder.java:377) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDecode(PlanFragmentBuilder.java:225) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.physical.PhysicalDecodeOperator.accept(PhysicalDecodeOperator.java:46) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:234) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:133) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:90) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:48) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:299) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:248) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:397) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:633) [starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:54) [starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener$$Lambda$250/150207903.run(Unknown Source) [starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_41]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_41]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_41]
```
