### ISSUE TITLE
[StarOS] fe cannot start

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#18061]
### Steps to reproduce the behavior (Required)
fe crash and cannot be started when executing cases in: test_dml/test_stream_load
fe.warn.log:
```
2023-02-18 05:48:34,766 ERROR (stateChangeExecutor|63) [GlobalStateMgr.transferToLeader():1086] failed to init journal after transfer to leader! will exit
com.starrocks.journal.JournalException: fail to read journal entity key=11478, data=<DatabaseEntry offset="0" size="803" data="39 18 0 0 0 1 0 0 0 0 0 0 71 140 0 0 0 0 0 0 71 142 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 0 0 71 154 0 0 0 8 116 49 95 49 56 51 50 57 0 0 0 6 78 79 82 77 65 76 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 0 0 0 71 143 0 0 0 6 78 79 82 77  ... 703 bytes not shown "/>
	at com.starrocks.journal.bdbje.BDBJournalCursor.deserializeData(BDBJournalCursor.java:257) ~[starrocks-fe.jar:?]
	at com.starrocks.journal.bdbje.BDBJournalCursor.next(BDBJournalCursor.java:295) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1966) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1925) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.transferToLeader(GlobalStateMgr.java:1081) [starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.access$100(GlobalStateMgr.java:311) [starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr$1.transferToLeader(GlobalStateMgr.java:677) [starrocks-fe.jar:?]
	at com.starrocks.ha.StateChangeExecutor.runOneCycle(StateChangeExecutor.java:103) [starrocks-fe.jar:?]
	at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197) ~[?:1.8.0_351]
	at com.starrocks.common.io.Text.readString(Text.java:390) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.Replica.readFields(Replica.java:571) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.Replica.read(Replica.java:582) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.LocalTablet.readFields(LocalTablet.java:388) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.LocalTablet.read(LocalTablet.java:404) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.MaterializedIndex.readFields(MaterializedIndex.java:297) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.MaterializedIndex.read(MaterializedIndex.java:308) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.Partition.readFields(Partition.java:419) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.Partition.read(Partition.java:372) ~[starrocks-fe.jar:?]
	at com.starrocks.persist.PartitionPersistInfo.readFields(PartitionPersistInfo.java:133) ~[starrocks-fe.jar:?]
	at com.starrocks.persist.PartitionPersistInfo.read(PartitionPersistInfo.java:126) ~[starrocks-fe.jar:?]
	at com.starrocks.persist.AddPartitionsInfo.read(AddPartitionsInfo.java:49) ~[starrocks-fe.jar:?]
	at com.starrocks.journal.JournalEntity.readFields(JournalEntity.java:284) ~[starrocks-fe.jar:?]
	at com.starrocks.journal.bdbje.BDBJournalCursor.deserializeData(BDBJournalCursor.java:251) ~[starrocks-fe.jar:?]
	... 8 more
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
UNKNOWN-800b5477f
```

**Comment by sduzh** [comment]
Duplicated with #17928
