### ISSUE TITLE
fe start failed.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#18129]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
```
2023-02-20 15:57:14,128 WARN (UNKNOWN 172.26.92.151_9312_1675165389351(-1)|1) [GlobalStateMgr.loadImage():1374] load image eof.
java.io.EOFException: null
        at java.io.DataInputStream.readFully(DataInputStream.java:197) ~[?:1.8.0_262]
        at com.starrocks.common.io.Text.readString(Text.java:390) ~[starrocks-fe.jar:?]
        at com.starrocks.backup.BackupJob.readFields(BackupJob.java:951) ~[starrocks-fe.jar:?]
        at com.starrocks.backup.AbstractJob.read(AbstractJob.java:207) ~[starrocks-fe.jar:?]
        at com.starrocks.backup.BackupHandler.readFields(BackupHandler.java:684) ~[starrocks-fe.jar:?]
        at com.starrocks.backup.BackupHandler.loadBackupHandler(BackupHandler.java:701) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1333) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:960) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:129) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:81) [starrocks-fe.jar:?]
2023-02-20 15:57:14,134 ERROR (UNKNOWN 172.26.92.151_9312_1675165389351(-1)|1) [StarRocksFE.start():183] StarRocksFE start failed
java.lang.IllegalStateException: -1 vs. -6141936
        at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1379) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:960) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:129) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:81) [starrocks-fe.jar:?]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - BRANCH-3.0-ASAN ASAN (build d811ec2)

**Comment by gengjun-git** [comment]
fixed
