### ISSUE TITLE
Cannot open null host

### ISSUE THREAD

**Issue by fushaofeng** [StarRocks/starrocks#19388]
### Steps to reproduce the behavior (Required)
select duration,extDuration,lesson_id lessonId,user_code userCode,first_in firstIn,last_out lastOut,total_playback_time playbackTime  from t_xxx where lesson_id in (3046457320)  and user_code in ( 'NTB43270')

### Real behavior (Required)
**1）Application side error log**
Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Cannot open null host

**2）StarRocks FE side error log**
2023-03-10 13:26:34,758 WARN (starrocks-mysql-nio-pool-6419|18467) [StmtExecutor.execute():491] execute Exception, sql select duration,extDuration,lesson_id lessonId,user_code userCode,first_in firstIn,last_out lastOut,total_playback_time playbackTime  from t_xxx where lesson_id in (3046457320)  and user_code in ( 'NTB43270')
org.apache.thrift.transport.TTransportException: Cannot open null host.
        at org.apache.thrift.transport.TSocket.open(TSocket.java:210) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:116) ~[starrocks-fe.jar:?]
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1036) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:278) ~[commons-pool2-2.3.jar:2.3]
        at com.starrocks.common.GenericPool.borrowObject(GenericPool.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.rpc.FrontendServiceProxy.call(FrontendServiceProxy.java:20) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.forward(MasterOpExecutor.java:140) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.execute(MasterOpExecutor.java:78) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.forwardToMaster(StmtExecutor.java:583) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:382) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:322) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:440) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:684) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

### StarRocks version (Required)
StarRocks version is 2.3.8
mysql> select current_version();
+-------------------+
| current_version()    |
+-------------------+
| 2.3.8 4739a1e         |
+-------------------+
1 row in set (0.01 sec)

**Comment by gengjun-git** [comment]
The reason is follower's meta is behind leader's meta. Can you show us the fe.log when the error happens.

**Comment by fushaofeng** [comment]
The following is today's error log.

2023-03-14 13:18:34,132 WARN (replayer|82) [GlobalStateMgr.setCanRead():1561] meta out of date. current time: 1678771114132, synchronized time: 1678771104131, has log: true, fe type: FOLLOWER
2023-03-14 13:18:34,595 INFO (starrocks-mysql-nio-pool-8123|23334) [MasterOpExecutor.forward():138] Forward statement 754012 to Master TNetworkAddress(hostname:, port:0)
2023-03-14 13:18:34,596 WARN (starrocks-mysql-nio-pool-8123|23334) [StmtExecutor.execute():491] execute Exception, sql select duration,extDuration,lesson_id lessonId,user_code userCode,first_in firstIn,last_out lastOut,total_playback_time playbackTime
        from dws_xxxx where

            lesson_id in
             (
                '3076633580'
             )


            and user_code in
             (
                'TH0122108904'
             )
org.apache.thrift.transport.TTransportException: Cannot open null host.
        at org.apache.thrift.transport.TSocket.open(TSocket.java:210) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:116) ~[starrocks-fe.jar:?]
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1036) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:278) ~[commons-pool2-2.3.jar:2.3]
        at com.starrocks.common.GenericPool.borrowObject(GenericPool.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.rpc.FrontendServiceProxy.call(FrontendServiceProxy.java:20) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.forward(MasterOpExecutor.java:140) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.execute(MasterOpExecutor.java:78) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.forwardToMaster(StmtExecutor.java:583) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:382) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:322) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:440) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:684) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2023-03-14 13:18:37,399 INFO (starrocks-mysql-nio I/O-4|88) [AcceptListener.handleEvent():54] Connection established. remote=/172.28.0.19:54880
2023-03-14 13:18:37,402 INFO (starrocks-mysql-nio-pool-8123|23334) [MasterOpExecutor.forward():138] Forward statement 754013 to Master TNetworkAddress(hostname:, port:0)
2023-03-14 13:18:37,402 WARN (starrocks-mysql-nio-pool-8123|23334) [StmtExecutor.execute():491] execute Exception, sql /* mysql-connector-java-8.0.12 (Revision: 24766725dc6e017025532146d94c6e6c488fb8f1) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@language AS language, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
org.apache.thrift.transport.TTransportException: Cannot open null host.
        at org.apache.thrift.transport.TSocket.open(TSocket.java:210) ~[libthrift-0.13.0.jar:0.13.0]

**Comment by fushaofeng** [comment]
The following is today's error log.

2023-03-14 13:18:34,132 WARN (replayer|82) [GlobalStateMgr.setCanRead():1561] meta out of date. current time: 1678771114132, synchronized time: 1678771104131, has log: true, fe type: FOLLOWER
2023-03-14 13:18:34,595 INFO (starrocks-mysql-nio-pool-8123|23334) [MasterOpExecutor.forward():138] Forward statement 754012 to Master TNetworkAddress(hostname:, port:0)
2023-03-14 13:18:34,596 WARN (starrocks-mysql-nio-pool-8123|23334) [StmtExecutor.execute():491] execute Exception, sql select duration,extDuration,lesson_id lessonId,user_code userCode,first_in firstIn,last_out lastOut,total_playback_time playbackTime
        from dws_xxxx where

            lesson_id in
             (
                '3076633580'
             )


            and user_code in
             (
                'TH0122108904'
             )
org.apache.thrift.transport.TTransportException: Cannot open null host.
        at org.apache.thrift.transport.TSocket.open(TSocket.java:210) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:116) ~[starrocks-fe.jar:?]
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1036) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:278) ~[commons-pool2-2.3.jar:2.3]
        at com.starrocks.common.GenericPool.borrowObject(GenericPool.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.rpc.FrontendServiceProxy.call(FrontendServiceProxy.java:20) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.forward(MasterOpExecutor.java:140) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.execute(MasterOpExecutor.java:78) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.forwardToMaster(StmtExecutor.java:583) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:382) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:322) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:440) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:684) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2023-03-14 13:18:37,399 INFO (starrocks-mysql-nio I/O-4|88) [AcceptListener.handleEvent():54] Connection established. remote=/172.28.0.19:54880
2023-03-14 13:18:37,402 INFO (starrocks-mysql-nio-pool-8123|23334) [MasterOpExecutor.forward():138] Forward statement 754013 to Master TNetworkAddress(hostname:, port:0)
2023-03-14 13:18:37,402 WARN (starrocks-mysql-nio-pool-8123|23334) [StmtExecutor.execute():491] execute Exception, sql /* mysql-connector-java-8.0.12 (Revision: 24766725dc6e017025532146d94c6e6c488fb8f1) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@language AS language, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
org.apache.thrift.transport.TTransportException: Cannot open null host.
        at org.apache.thrift.transport.TSocket.open(TSocket.java:210) ~[libthrift-0.13.0.jar:0.13.0]

**Comment by gengjun-git** [comment]
Is the disk IO load or memory used very high?

**Comment by fushaofeng** [comment]
The disk IO load or memory usage is not high.
<img width="687" alt="image" src="https://user-images.githubusercontent.com/37654785/224926932-bc92cbab-7c7c-4a52-9e21-e699388b5b95.png">

**Comment by gengjun-git** [comment]
We need the follower's metrics, not the BE.

**Comment by fushaofeng** [comment]
StarRocks Version 2.5 has fixed this bug

**Comment by fushaofeng** [comment]
StarRocks Version 2.5 has fixed this bug

**Comment by fushaofeng** [comment]
StarRocks Version 2.5 has fixed this bug
