### ISSUE TITLE
NPE in com.starrocks.sql.plan.ScalarOperatorToExpr

### ISSUE THREAD

**Issue by rcauble** [StarRocks/starrocks#19392]
### Steps to reproduce the behavior (Required)
```
CREATE DATABASE TEST;

CREATE TABLE `TEST`.`ACTIVITY` (`case` BIGINT, `timestamp` DATETIME, `sorting` BIGINT, `ID_activity` BIGINT, `activity` BIGINT, `activityname` STRING, `FK_8_activity_case` BIGINT) PRIMARY KEY(`case`,`timestamp`,`sorting`,`ID_activity`) DISTRIBUTED BY HASH (`case`) PROPERTIES("replication_num" = "1");
CREATE TABLE `TEST`.`CASE` (`ID_case` BIGINT, `case` BIGINT, `caseinfo` STRING, `caseextrainfo` BIGINT, `FK_8_activity_case` BIGINT, `FK_4_case_caseextrainfo` BIGINT, `PU_9_ARRAY_AGG_8_activity_case` ARRAY<BIGINT>, `PU_9_ARRAY_AGG_8_activity_timestamp` ARRAY<DATETIME>, `PU_9_ARRAY_AGG_8_activity_sorting` ARRAY<BIGINT>, `PU_9_ARRAY_AGG_8_activity_ID_activity` ARRAY<BIGINT>, `PU_9_ARRAY_AGG_8_activity_activity` ARRAY<BIGINT>, `PU_9_ARRAY_AGG_8_activity_activityname` ARRAY<STRING>, `PU_9_ARRAY_AGG_8_activity_FK_8_activity_case` ARRAY<BIGINT>)  DISTRIBUTED BY HASH (`ID_case`) PROPERTIES("replication_num" = "1");
CREATE TABLE `TEST`.`CASEEXTRAINFO` (`ID_caseextrainfo` BIGINT, `caseextrainfo` BIGINT, `extraexpr` BIGINT, `activitysuffix` STRING, `FK_4_case_caseextrainfo` BIGINT)  DISTRIBUTED BY HASH (`ID_caseextrainfo`) PROPERTIES("replication_num" = "1");

WITH `CASEEXTRAINFO` AS (
  SELECT
    `FK_4_CASE_CASEEXTRAINFO`,
    `EXTRAEXPR`
  FROM
    `TEST`.`CASEEXTRAINFO`
),
`ParserContext_Table_CASEEXTRAINFO_006` AS (
  SELECT
    `CASEEXTRAINFO`.`FK_4_CASE_CASEEXTRAINFO` AS `JoinColumnResolver_Column_FK_4_CASE_CASEEXTRAINFO_007`,
    `CASEEXTRAINFO`.`EXTRAEXPR` AS `JoinColumnResolver_Column_EXTRAEXPR_009`
  FROM
    `CASEEXTRAINFO`
),
`CASE` AS (
  SELECT
    `CASEINFO`,
    `FK_4_CASE_CASEEXTRAINFO`,
    `PU_9_ARRAY_AGG_8_ACTIVITY_TIMESTAMP`
  FROM
    `TEST`.`CASE`
),
`TableScanSequence_CASE_005` AS (
  SELECT
    `CASE`.`CASEINFO` AS `JoinColumnResolver_Column_CASEINFO_030`,
    `CASE`.`PU_9_ARRAY_AGG_8_ACTIVITY_TIMESTAMP` AS `JoinColumnResolver_Column_PU_9_ARRAY_AGG_8_ACTIVITY_TIMESTAMP_002`,
    `ParserContext_Table_CASEEXTRAINFO_006`.`JoinColumnResolver_Column_EXTRAEXPR_009` AS `JoinColumnResolver_Column_EXTRAEXPR_010`
  FROM
    `CASE`
    LEFT JOIN `ParserContext_Table_CASEEXTRAINFO_006` ON (
      `CASE`.`FK_4_CASE_CASEEXTRAINFO` = `ParserContext_Table_CASEEXTRAINFO_006`.`JoinColumnResolver_Column_FK_4_CASE_CASEEXTRAINFO_007`
    )
),
`ParserContext_Table_CASE_000` AS (
  SELECT
    array_map(
      (OperatorNodeHandler_arg_008) -> (
          TIMESTAMPDIFF(MINUTE,from_unixtime(0),OperatorNodeHandler_arg_008)*JoinColumnResolver_Column_EXTRAEXPR_010
      )
      ,
      `JoinColumnResolver_Column_PU_9_ARRAY_AGG_8_ACTIVITY_TIMESTAMP_002`
    ) AS `OperatorNodeHandler_011`
  FROM
    `TableScanSequence_CASE_005`
)
SELECT * FROM ParserContext_Table_CASE_000;
```
### Expected behavior (Required)
Query should succeed without an error

### Real behavior (Required)

Query fails with "Unknown error". Looking at the FE log there is an NPE:

```
java.lang.NullPointerException: null
	at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitVariableReference(ScalarOperatorToExpr.java:167) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitVariableReference(ScalarOperatorToExpr.java:127) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:127) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr.buildExecExpression(ScalarOperatorToExpr.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitCall(ScalarOperatorToExpr.java:433) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitCall(ScalarOperatorToExpr.java:127) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.scalar.CallOperator.accept(CallOperator.java:196) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr.buildExecExpression(ScalarOperatorToExpr.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitLambdaFunctionOperator(ScalarOperatorToExpr.java:590) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitLambdaFunctionOperator(ScalarOperatorToExpr.java:127) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.scalar.LambdaFunctionOperator.accept(LambdaFunctionOperator.java:120) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr.buildExecExpression(ScalarOperatorToExpr.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.lambda$visitCall$1(ScalarOperatorToExpr.java:512) ~[starrocks-fe.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitCall(ScalarOperatorToExpr.java:513) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitCall(ScalarOperatorToExpr.java:127) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.scalar.CallOperator.accept(CallOperator.java:196) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.ScalarOperatorToExpr.buildExecExpression(ScalarOperatorToExpr.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.buildProjectNode(PlanFragmentBuilder.java:529) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:366) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.translate(PlanFragmentBuilder.java:354) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:202) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:137) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:89) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:50) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:389) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:343) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:460) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:724) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```

### StarRocks version (Required)
3.0

**Comment by Seaven** [comment]
simple sql
```
CREATE TABLE `a2` (
  `v1` bigint(20) NULL COMMENT "",
  `v2` bigint(20) NULL COMMENT "",
  `v3` bigint(20) NULL COMMENT "",
  `a1` ARRAY<decimal32(9, 3)> NULL COMMENT "",
  `a2` ARRAY<decimal64(18, 7)> NULL COMMENT "",
  `a3` ARRAY<decimal128(38, 27)> NULL COMMENT "",
  `a4` ARRAY<int(11)> NULL COMMENT "",
  `a5` ARRAY<varchar(65533)> NULL COMMENT "",
  `a6` ARRAY<ARRAY<int(11)>> NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`v1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`v1`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);


with x2 as (select array_map((ss) -> TIMESTAMPDIFF(MINUTE,from_unixtime(0),ss) * v3, a4) from a2)
select * from x2;
```
