### ISSUE TITLE
[PK update] unknown error from update pk from table

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#19466]
### Steps to reproduce the behavior (Required)
create table:
````sql
create table pri_tbl(
                col_tinyint_pk tinyint
                ,col_date_pk date
                ,col_varchar_pk varchar(65533)
                ,col_string_pk string
                ,col_smallint_pk smallint
                ,col_tinyint tinyint default "100"
                ,col_date date
                ,col_varchar varchar(20)
                ,col_string string
                ,col_smallint smallint
                ,col_timestamp datetime default "2014-12-07 03:43:07"
                ,col_char char(100) default "test primary key udpate"
                ,col_boolean boolean
                ,col_int int
                ,col_bigint bigint
                ,col_float float
                ,col_double double
                ,col_decimal decimal(38,18) default "3.1415926"
                ,col_largeint largeint
                ,col_array array<string>
                ,col_json json
                ,col_bitmap bitmap)
                primary KEY(col_tinyint_pk,col_date_pk,col_varchar_pk,col_string_pk,col_smallint_pk)
                DISTRIBUTED BY HASH(col_tinyint_pk) BUCKETS 10
                PROPERTIES ("replication_num" = "3");
create table agg_tbl(
                col_tinyint_key tinyint
                ,col_date_key date
                ,col_varchar_key varchar(65533)
                ,col_string_key string
                ,col_smallint_key smallint
                ,col_tinyint tinyint max
                ,col_date date max
                ,col_varchar varchar(20) replace
                ,col_string string replace
                ,col_smallint smallint max
                ,col_timestamp datetime max
                ,col_char char(100) replace
                ,col_boolean boolean replace
                ,col_int int replace
                ,col_bigint bigint sum
                ,col_float float max
                ,col_double double max
                ,col_decimal decimal(38,18) max
                ,col_largeint largeint replace
                ,col_array array<string> replace
                ,col_json json replace
                ,col_bitmap bitmap BITMAP_UNION NULL)
                aggregate KEY(col_tinyint_key,col_date_key,col_varchar_key,col_string_key,col_smallint_key)
                DISTRIBUTED BY HASH(col_tinyint_key) BUCKETS 10
                PROPERTIES ("replication_num" = "3");
create table uniq_tbl(
                col_tinyint_key tinyint
                ,col_date_key date
                ,col_varchar_key varchar(65533)
                ,col_string_key string
                ,col_smallint_key smallint
                ,col_tinyint tinyint
                ,col_date date
                ,col_varchar varchar(20)
                ,col_string string
                ,col_smallint smallint
                ,col_timestamp datetime
                ,col_char char(100)
                ,col_boolean boolean
                ,col_int int
                ,col_bigint bigint
                ,col_float float
                ,col_double double
                ,col_decimal decimal(38,18)
                ,col_largeint largeint
                ,col_array array<string>
                ,col_json json)
                unique KEY(col_tinyint_key,col_date_key,col_varchar_key,col_string_key,col_smallint_key)
                DISTRIBUTED BY HASH(col_tinyint_key) BUCKETS 10
                PROPERTIES ("replication_num" = "3");
````

update sql:
```
with
tbl1 as(select col_tinyint_key,col_date_key,col_timestamp,col_largeint,col_bitmap from agg_tbl),
tbl2 as(select col_tinyint_key,col_date,col_char,col_boolean,col_array,col_json from uniq_tbl)
update pri_tbl
set col_double = null,
    col_char = b.col_date,
    col_string = cast(pri_tbl.col_tinyint_pk as string),
    col_boolean = not cast(a.col_timestamp as boolean),
    col_json = (CAST(1 AS JSON)),
    col_bitmap = a.col_bitmap,
    col_date = adddate(a.col_date_key, INTERVAL 2 DAY),
    col_bigint = a.col_tinyint_key + b.col_tinyint_key
from tbl1 a, tbl2 b
where a.col_tinyint_key = pri_tbl.col_tinyint_pk
  and pri_tbl.col_tinyint_pk = b.col_tinyint_key
  and pri_tbl.col_date is not null
  and pri_tbl.col_largeint = a.col_largeint
  and date_trunc("month", pri_tbl.col_date) > '2023-03-01';
```

fe.warn.log:
```
2023-03-14 10:39:17,175 WARN (starrocks-mysql-nio-pool-6|508) [StmtExecutor.execute():552] execute Exception, sql with
tbl1 as(select col_tinyint_key,col_date_key,col_timestamp,col_largeint,col_bitmap from agg_tbl),
tbl2 as(select col_tinyint_key,col_date,col_char,col_boolean,col_array,col_json from uniq_tbl)
update pri_tbl
set col_double = null,
    col_char = b.col_date,
    col_string = cast(pri_tbl.col_tinyint_pk as string),
    col_boolean = not cast(a.col_timestamp as boolean),
    col_json = (CAST(1 AS JSON)),
    col_bitmap = a.col_bitmap,
    col_date = adddate(a.col_date_key, INTERVAL 2 DAY),
    col_bigint = a.col_tinyint_key + b.col_tinyint_key
from tbl1 a, tbl2 b
where a.col_tinyint_key = pri_tbl.col_tinyint_pk
  and pri_tbl.col_tinyint_pk = b.col_tinyint_key
  and pri_tbl.col_date is not null
  and pri_tbl.col_largeint = a.col_largeint
  and date_trunc("month", pri_tbl.col_date) > '2023-03-01'
java.lang.NullPointerException: null
        at com.starrocks.sql.analyzer.PrivilegeCheckerV2$PrivilegeCheckerVisitor.checkSelectTableAction(PrivilegeCheckerV2.java:528) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.PrivilegeCheckerV2$PrivilegeCheckerVisitor.visitUpdateStatement(PrivilegeCheckerV2.java:512) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.PrivilegeCheckerV2$PrivilegeCheckerVisitor.visitUpdateStatement(PrivilegeCheckerV2.java:469) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.UpdateStmt.accept(UpdateStmt.java:91) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.PrivilegeCheckerV2$PrivilegeCheckerVisitor.check(PrivilegeCheckerV2.java:472) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.PrivilegeCheckerV2.check(PrivilegeCheckerV2.java:201) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.PrivilegeChecker.check(PrivilegeChecker.java:161) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:73) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:55) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:395) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:348) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:462) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:728) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-3.0-RELEASE 27ffa8b |
+----------------------------+
1 row in set (0.00 sec)
```

**Comment by tiannan-sr** [comment]
delete from with cte:
```
2023-03-16 11:14:55,108 WARN (starrocks-mysql-nio-pool-59|9646) [StmtExecutor.execute():552] execute Exception, sql with
tbl1 as(select col_tinyint_key,col_date_key,col_timestamp,col_largeint from agg_tbl),
tbl2 as(select col_tinyint_key,col_date,col_char,col_boolean,col_array,col_json from uniq_tbl)
delete from pri_tbl
using tbl1 a, tbl2 b
where a.col_tinyint_key = pri_tbl.col_tinyint_pk
  and pri_tbl.col_tinyint_pk = b.col_tinyint_key
  and pri_tbl.col_date is not null
  and pri_tbl.col_largeint = a.col_largeint
  and date_trunc("month", pri_tbl.col_date) > '2023-03-01'
java.lang.NullPointerException: null
        at com.starrocks.sql.analyzer.PrivilegeCheckerV2$PrivilegeCheckerVisitor.checkSelectTableAction(PrivilegeCheckerV2.java:528) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.PrivilegeCheckerV2$PrivilegeCheckerVisitor.visitDeleteStatement(PrivilegeCheckerV2.java:503) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.PrivilegeCheckerV2$PrivilegeCheckerVisitor.visitDeleteStatement(PrivilegeCheckerV2.java:469) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.DeleteStmt.accept(DeleteStmt.java:140) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.PrivilegeCheckerV2$PrivilegeCheckerVisitor.check(PrivilegeCheckerV2.java:472) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.PrivilegeCheckerV2.check(PrivilegeCheckerV2.java:201) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.PrivilegeChecker.check(PrivilegeChecker.java:161) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:73) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:55) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:395) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:348) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:462) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:728) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
