### ISSUE TITLE
Hive external table, Bucket identification error

### ISSUE THREAD

**Issue by dq1201** [StarRocks/starrocks#1987]
hive外表bucket识别错误，eg: hive location如此配置： oss://ssports-bigdata-dw.oss-cn-beijing-internal.aliyuncs.com/hive/datawarehouse/dwd_xi_ubehav_applog 会报bucket格式识别错误；只有修改成oss://ssports-bigdata-dw/hive/datawarehouse/dwd_xi_ubehav_applog 去掉地区才不报错。感觉是路径中的“.”导致解析错误

**Comment by miomiocat** [comment]
为什么要加地区呢？bucket名称就有地区？

**Comment by dq1201** [comment]
hive的location是有地区的。目前的解决方案是将地区删除，但是这种方式只是退而求其次，正常应该是带着地区也能识别到

**Comment by miomiocat** [comment]
> hive的location是有地区的。目前的解决方案是将地区删除，但是这种方式只是退而求其次，正常应该是带着地区也能识别到

我试了一下是正常的，没有复现出来。能提供一下你那边的报错详细信息和堆栈吗，还有使用的starrocks版本号？

**Comment by dq1201** [comment]
使用的版本是 1.18.2

**Comment by miomiocat** [comment]
能提供一下报错详细信息和堆栈么？

**Comment by dq1201** [comment]
*** Aborted at 1639377920 (unix time) try "date -d @1639377920" if you are using GNU date ***
PC: @     0x7f85f144a2c1 jni_invoke_nonstatic()
*** SIGSEGV (@0x1800000035) received by PID 6363 (TID 0x7f85e11e4700) from PID 53; stack trace: ***
    @          0x3093812 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f85f1681105 os::Linux::chained_handler()
    @     0x7f85f1685f31 JVM_handle_linux_signal
    @     0x7f85f1679128 signalHandler()
    @     0x7f85f1db6630 (unknown)
    @     0x7f85f144a2c1 jni_invoke_nonstatic()
    @     0x7f85f14553da jni_CallObjectMethodV
    @          0x3b5a16c invokeMethodOnJclass
    @          0x3b5a4bf invokeMethod
    @          0x3b5375d hdfsFileGetReadStatistics
    @          0x26caa23 doris::vectorized::HdfsScanner::update_counter()
    @          0x26cea01 doris::vectorized::HdfsOrcScanner::update_counter()
    @          0x26cec58 doris::vectorized::HdfsOrcScanner::do_close()
    @          0x26ca9a5 doris::vectorized::HdfsScanner::close()
    @          0x2643cf7 doris::vectorized::HdfsScanNode::_scanner_thread()
    @          0x1eaaa37 doris::PriorityThreadPool::work_thread()
    @          0x3043917 thread_proxy
    @     0x7f85f1daeea5 start_thread
    @     0x7f85f01c39fd __clone

**Comment by dq1201** [comment]
`W1213 14:45:14.981257  6581 beta_rowset.cpp:119] Fail to delete file=/opt/apps/StarRocks-1.18.2/be/storage/data/129/26983/1009125466/02000000001f9a136f46875f978a7600e3af95dd974157af_0.dat err=No such file or directory
W1213 14:45:14.981277  6581 beta_rowset.cpp:147] Fail to remove files in rowset id=/opt/apps/StarRocks-1.18.2/be/storage/data/129/26983/1009125466/02000000001f9a136f46875f978a7600e3af95dd974157af
W1213 14:45:14.981431  6581 beta_rowset.cpp:119] Fail to delete file=/opt/apps/StarRocks-1.18.2/be/storage/data/127/26974/1009125466/02000000001f9a4b6f46875f978a7600e3af95dd974157af_0.dat err=No such file or directory
W1213 14:45:14.981453  6581 beta_rowset.cpp:147] Fail to remove files in rowset id=/opt/apps/StarRocks-1.18.2/be/storage/data/127/26974/1009125466/02000000001f9a4b6f46875f978a7600e3af95dd974157af`

**Comment by miomiocat** [comment]
> *** Aborted at 1639377920 (unix time) try "date -d @1639377920" if you are using GNU date *** PC: @ 0x7f85f144a2c1 jni_invoke_nonstatic() *** SIGSEGV (@0x1800000035) received by PID 6363 (TID 0x7f85e11e4700) from PID 53; stack trace: *** @ 0x3093812 google::(anonymous namespace)::FailureSignalHandler() @ 0x7f85f1681105 os::Linux::chained_handler() @ 0x7f85f1685f31 JVM_handle_linux_signal @ 0x7f85f1679128 signalHandler() @ 0x7f85f1db6630 (unknown) @ 0x7f85f144a2c1 jni_invoke_nonstatic() @ 0x7f85f14553da jni_CallObjectMethodV @ 0x3b5a16c invokeMethodOnJclass @ 0x3b5a4bf invokeMethod @ 0x3b5375d hdfsFileGetReadStatistics @ 0x26caa23 doris::vectorized::HdfsScanner::update_counter() @ 0x26cea01 doris::vectorized::HdfsOrcScanner::update_counter() @ 0x26cec58 doris::vectorized::HdfsOrcScanner::do_close() @ 0x26ca9a5 doris::vectorized::HdfsScanner::close() @ 0x2643cf7 doris::vectorized::HdfsScanNode::_scanner_thread() @ 0x1eaaa37 doris::PriorityThreadPool::work_thread() @ 0x3043917 thread_proxy @ 0x7f85f1daeea5 start_thread @ 0x7f85f01c39fd __clone

@dq1201  这个报错现在已经解决了，但是还没有release版本包出来，你可以使用main分支编译自行最新版本，或者等starrocks的release新版本包。

**Comment by tiannan-sr** [comment]
hive中创建oss存储hive外部表，location中带地域信息：
```
CREATE EXTERNAL TABLE IF NOT EXISTS oss_lineorder (
 lo_orderkey bigint,
 lo_linenumber int,
 lo_custkey int,
 lo_partkey int,
 lo_suppkey int,
 lo_orderdate int,
 lo_orderpriority varchar(16),
 lo_shippriority int,
 lo_quantity int,
 lo_extendedprice int,
 lo_ordtotalprice int,
 lo_discount int,
 lo_revenue int,
 lo_supplycost int,
 lo_tax int,
 lo_commitdate int,
 lo_shipmode varchar(11)
) row format delimited fields terminated by '|'
 stored as textfile
location 'oss://dorisdb-data.oss-cn-zhangjiakou.aliyuncs.com/ssb_csv_1g/lineorder';
```
创建成功后，hive中查询该表，select count(*)报错：
```
hive> select count(*) from oss_lineorder;
Query ID = root_20220219160655_92f3b972-b5f3-449f-b3f2-c3984c6573a2
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Starting Job = job_1644301670407_0064, Tracking URL = http://emr-header-1.cluster-49155:20888/proxy/application_1644301670407_0064/
Kill Command = /usr/lib/hadoop-current/bin/mapred job  -kill job_1644301670407_0064
Hadoop job information for Stage-1: number of mappers: 2; number of reducers: 1
2022-02-19 16:07:08,102 Stage-1 map = 0%,  reduce = 0%
2022-02-19 16:08:09,055 Stage-1 map = 0%,  reduce = 0%
2022-02-19 16:09:02,321 Stage-1 map = 100%,  reduce = 100%
Ended Job = job_1644301670407_0064 with errors
Error during job, obtaining debugging information...
Job Tracking URL: http://emr-header-1.cluster-49155:20888/proxy/application_1644301670407_0064/
Examining task ID: task_1644301670407_0064_m_000000 (and more) from job job_1644301670407_0064

Task with the most failures(4):
-----
Task ID:
  task_1644301670407_0064_m_000000

URL:
  http://emr-header-1.cluster-49155:8088/taskdetails.jsp?jobid=job_1644301670407_0064&tipid=task_1644301670407_0064_m_000000
-----
Diagnostic Messages for this Task:
Error: java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.apache.hadoop.hive.io.HiveIOExceptionHandlerChain.handleRecordReaderCreationException(HiveIOExceptionHandlerChain.java:97)
	at org.apache.hadoop.hive.io.HiveIOExceptionHandlerUtil.handleRecordReaderCreationException(HiveIOExceptionHandlerUtil.java:57)
	at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileRecordReader.initNextRecordReader(HadoopShimsSecure.java:272)
	at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileRecordReader.<init>(HadoopShimsSecure.java:218)
	at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileInputFormatShim.getRecordReader(HadoopShimsSecure.java:346)
	at org.apache.hadoop.hive.ql.io.CombineHiveInputFormat.getRecordReader(CombineHiveInputFormat.java:721)
	at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.<init>(MapTask.java:175)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:444)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:174)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1732)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:168)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileRecordReader.initNextRecordReader(HadoopShimsSecure.java:258)
	... 11 more
Caused by: java.io.IOException: java.io.IOException: [ErrorCode] : 112 , [ErrorType]:  [HostId]: oss-cn-zhangjiakou.aliyuncs.com [ErrorMessage]: [E112]Fail to select channel, Host is down [R1][E112]Fail to select channel, Host is down [R2][E112]Fail to select channel, Host is down [R3][E112]Fail to select channel, Host is down
	at com.aliyun.emr.fs.internal.ossnative.OssFileletSystem.open(OssFileletSystem.java:330)
	at com.aliyun.emr.fs.internal.ossnative.OssNativeStore.open(OssNativeStore.java:522)
	at com.aliyun.emr.fs.oss.JindoOssFileSystem.openCore(JindoOssFileSystem.java:187)
	at com.aliyun.emr.fs.common.AbstractJindoShimsFileSystem.open(AbstractJindoShimsFileSystem.java:292)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:899)
	at org.apache.hadoop.mapred.LineRecordReader.<init>(LineRecordReader.java:109)
	at org.apache.hadoop.mapred.TextInputFormat.getRecordReader(TextInputFormat.java:67)
	at org.apache.hadoop.hive.ql.io.CombineHiveRecordReader.<init>(CombineHiveRecordReader.java:99)
	... 16 more
Caused by: java.io.IOException: [ErrorCode] : 112 , [ErrorType]:  [HostId]: oss-cn-zhangjiakou.aliyuncs.com [ErrorMessage]: [E112]Fail to select channel, Host is down [R1][E112]Fail to select channel, Host is down [R2][E112]Fail to select channel, Host is down [R3][E112]Fail to select channel, Host is down
	at com.alibaba.jboot.JbootFuture.get(JbootFuture.java:168)
	at com.alibaba.jboot.future.ByteBufferFuture.get(ByteBufferFuture.java:31)
	at com.aliyun.emr.fs.internal.ossnative.OssFileletSystem.open(OssFileletSystem.java:324)
	... 23 more


FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched:
Stage-Stage-1: Map: 2  Reduce: 1   HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec
```
select * limit *正常：
```
hive> select * from oss_lineorder limit 10;
OK
1	1	7381	155190	828	19960102	5-LOW	0	17	2116823	17366547	4	2032150	74711	2	19960212	TRUCK
1	2	7381	67310	163	19960102	5-LOW	0	36	4598316	17366547	9	4184467	76638	6	19960228	MAIL
1	3	7381	63700	71	19960102	5-LOW	0	8	1330960	17366547	10	1197864	99822	2	19960305	REG AIR
1	4	7381	2132	943	19960102	5-LOW	0	28	2895564	17366547	9	2634963	62047	6	19960330	AIR
1	5	7381	24027	1625	19960102	5-LOW	0	24	2282448	17366547	10	2054203	57061	4	19960314	FOB
1	6	7381	15635	1368	19960102	5-LOW	0	32	4962016	17366547	7	4614674	93037	2	19960207	MAIL
2	1	15601	106170	1066	19961201	1-URGENT	0	38	4469446	4692918	0	4469446	70570	5	19970114	RAIL
3	1	24664	4297	1959	19931014	5-LOW	0	45	5405805	19384625	6	5081456	72077	0	19940104	AIR
3	2	24664	19036	1667	19931014	5-LOW	0	49	4679647	19384625	10	4211682	57301	0	19931220	RAIL
3	3	24664	128449	1409	19931014	5-LOW	0	27	3989088	19384625	6	3749742	88646	7	19931122	SHIP
Time taken: 0.172 seconds, Fetched: 10 row(s)
```

使用此hive表在starrocks中创建hive外表报错，bucket name解析格式不对：
```
mysql> create external table ex_hive_oss_lineorder
    ->  (lo_orderkey bigint,
    ->  lo_linenumber int,
    ->  lo_custkey int,
    ->  lo_partkey int,
    ->  lo_suppkey int,
    ->  lo_orderdate int,
    ->  lo_orderpriority varchar(16),
    ->  lo_shippriority int,
    ->  lo_quantity int,
    ->  lo_extendedprice int,
    ->  lo_ordtotalprice int,
    ->  lo_discount int,
    ->  lo_revenue int,
    ->  lo_supplycost int,
    ->  lo_tax int,
    ->  lo_commitdate int,
    ->  lo_shipmode varchar(11))
    ->  engine=hive
    ->  properties (
    ->  "resource" = "hive_emr_tn",
    ->  "table" = "oss_lineorder",
    ->  "database" = "tn_test");
Query OK, 0 rows affected (0.05 sec)

mysql> select count(*) from ex_hive_oss_lineorder;
ERROR 1064 (HY000): com.starrocks.common.DdlException: get partition detail failed: com.starrocks.common.DdlException: get hive partition meta data failed: The bucket name "dorisdb-data.oss-cn-zhangjiakou.aliyuncs.com" is invalid. A bucket name must: 1) be comprised of lower-case characters, numbers or dash(-); 2) start with lower case or numbers; 3) be between 3-63 characters long.
```

报错对应FE日志：
```
2022-02-18 21:51:35,224 WARN (starrocks-mysql-nio-pool-44|789) [StatisticsCalculator.getTableRowCount():501] compute hive table row count failed : com.starrocks.common.DdlException: com.starrocks.common.DdlException: get partition detail failed: com.starrocks.common.DdlException: get hive partition meta data failed: The bucket name "dorisdb-data.oss-cn-zhangjiakou.aliyuncs.com" is invalid. A bucket name must: 1) be comprised of lower-case characters, numbers or dash(-); 2) start with lower case or numbers; 3) be between 3-63 characters long.
2022-02-18 21:51:35,224 WARN (starrocks-mysql-nio-pool-44|789) [StmtExecutor.execute():304] New planner error: select count(*) from ex_hive_oss_lineorder
com.starrocks.sql.common.StarRocksPlannerException: com.starrocks.common.DdlException: get partition detail failed: com.starrocks.common.DdlException: get hive partition meta data failed: The bucket name "dorisdb-data.oss-cn-zhangjiakou.aliyuncs.com" is invalid. A bucket name must: 1) be comprised of lower-case characters, numbers or dash(-); 2) start with lower case or numbers; 3) be between 3-63 characters long.
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.getTableRowCount(StatisticsCalculator.java:502) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeHiveScanNode(StatisticsCalculator.java:263) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalHiveScan(StatisticsCalculator.java:250) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalHiveScan(StatisticsCalculator.java:124) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalHiveScanOperator.accept(LogicalHiveScanOperator.java:123) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:140) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:40) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:115) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:97) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:80) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:47) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:290) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]        
2022-02-18 21:51:35,224 WARN (starrocks-mysql-nio-pool-44|789) [StmtExecutor.execute():451] execute Exception, sql select count(*) from ex_hive_oss_lineorder
com.starrocks.sql.common.StarRocksPlannerException: com.starrocks.common.DdlException: get partition detail failed: com.starrocks.common.DdlException: get hive partition meta data failed: The bucket name "dorisdb-data.oss-cn-zhangjiakou.aliyuncs.com" is invalid. A bucket name must: 1) be comprised of lower-case characters, numbers or dash(-); 2) start with lower case or numbers; 3) be between 3-63 characters long.
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.getTableRowCount(StatisticsCalculator.java:502) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeHiveScanNode(StatisticsCalculator.java:263) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalHiveScan(StatisticsCalculator.java:250) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalHiveScan(StatisticsCalculator.java:124) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalHiveScanOperator.accept(LogicalHiveScanOperator.java:123) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:140) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:40) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:115) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:97) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:80) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:47) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:290) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]    
```

**Comment by miomiocat** [comment]
经验证，该问题已修复.
