### ISSUE TITLE
JournalInconsistentException: failed to load journal type 100

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#20021]
### Real behavior (Required)
```
2023-03-22 17:27:45,815 WARN (replayer|90) [GlobalStateMgr$5.runOneCycle():1848] got interrupt exception or inconsistent exception when replay journal 6974, will exit,
com.starrocks.journal.JournalInconsistentException: failed to load journal type 100
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:1031) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1987) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.runOneCycle(GlobalStateMgr.java:1845) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.run(GlobalStateMgr.java:1910) [starrocks-fe.jar:?]
Caused by: java.lang.IllegalStateException: 
        at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.transaction.LakeTableTxnLogApplier.applyVisibleLog(LakeTableTxnLogApplier.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.transaction.DatabaseTransactionMgr.updateCatalogAfterVisible(DatabaseTransactionMgr.java:1524) ~[starrocks-fe.jar:?]
        at com.starrocks.transaction.DatabaseTransactionMgr.replayUpsertTransactionState(DatabaseTransactionMgr.java:1613) ~[starrocks-fe.jar:?]
        at com.starrocks.transaction.GlobalTransactionMgr.replayUpsertTransactionState(GlobalTransactionMgr.java:627) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:602) ~[starrocks-fe.jar:?]
        ... 4 more
```

### StarRocks version (Required)
 branch-3.0 3209c7c

**Comment by sduzh** [comment]
Introduced by #9436, which move the write to edit log after the invocation of `LakeSchemaChangeJob.visualiseShadowIndex(OlapTable)`.

`LakeSchemaChangeJob.visualiseShadowIndex(OlapTable)` will increase the visible version of partition,
if another transaction got published between `LakeSchemaChangeJob.visualiseShadowIndex(OlapTable)` and
`LakeSchemaChangeJob.writeEditLog(LakeSchemaChangeJob)`, the follower node or checkpoint thread
will see discontinuous growth of the visible version of Partition, i,e, the following assertion will fail:
https://github.com/StarRocks/starrocks/blob/ae9b37dff92e3b38338fceda06000b28973d4bb4/fe/fe-core/src/main/java/com/starrocks/transaction/LakeTableTxnLogApplier.java#L58
```
