### ISSUE TITLE
Query returns Instant exceeds minimum or maximum instant

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#2002]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `test_cross_join_30` (
  `id_int` int(11) NOT NULL COMMENT "",
  `id_double` double NOT NULL COMMENT "",
  `id_varchar` varchar(100) NOT NULL COMMENT "",
  `id_datetime` datetime NOT NULL COMMENT "",
  `id_decimal` decimal128(20, 3) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`id_int`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id_int`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. CREATE EXTERNAL RESOURCE "hive2" PROPERTIES ( "type" = "hive", "hive.metastore.uris" = "thrift://172.26.92.141:9083");
3. CREATE EXTERNAL TABLE `hive_external_table` (
  `col_date` date NULL COMMENT "column date",
  `col_tinyint` tinyint(4) NULL COMMENT "column tinyint",
  `col_string` varchar(1000) NULL COMMENT "column string",
  `col_smallint` smallint(6) NULL COMMENT "column smallint",
  `col_int` int(11) NULL COMMENT "column int",
  `col_integer` int(11) NULL COMMENT "column integer",
  `col_bigint` bigint(20) NULL COMMENT "column bigint",
  `col_float` float NULL COMMENT "column float",
  `col_double` double NULL COMMENT "column double",
  `col_double_precision` double NULL COMMENT "column double precision",
  `col_decimal` decimal64(10, 0) NULL COMMENT "column decimal",
  `col_timestamp` datetime NULL COMMENT "column timestamp",
  `col_varchar` varchar(100) NULL COMMENT "colu
mn varchar",
  `col_binary` varchar(1000) NULL COMMENT "column binary",
  `col_boolean` boolean NULL COMMENT "column boolean"
) ENGINE=HIVE
COMMENT "PARTITION BY ()"
PROPERTIES (
"database" = "hive_extbl_test_1636019895543",
"table" = "hive_hdfs_orc_nocompress",
"resource" = "hive2",
"hive.metastore.uris"  =  "thrift://172.26.92.141:9083"
); 

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
ERROR 1064 (HY000): Instant exceeds minimum or maximum instant
```
java.time.DateTimeException: Instant exceeds minimum or maximum instant
	at java.time.Instant.create(Instant.java:411) ~[?:1.8.0_41]
	at java.time.Instant.ofEpochSecond(Instant.java:304) ~[?:1.8.0_41]
	at com.starrocks.sql.optimizer.Utils.getDatetimeFromLong(Utils.java:341) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitCastOperator(ExpressionStatisticCalculator.java:110) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitCastOperator(ExpressionStatisticCalculator.java:39) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.scalar.CastOperator.accept(CastOperator.java:68) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:36) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:32) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitOperator(StatisticsCalculator.java:173) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeHiveScanNode(StatisticsCalculator.java:247) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalHiveScan(StatisticsCalculator.java:227) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalHiveScan(StatisticsCalculator.java:115) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.logical.LogicalHiveScanOperator.accept(LogicalHiveScanOperator.java:123) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:131) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:36) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:147) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:75) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:46) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:299) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:248) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:397) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:633) [starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$510(ReadListener.java:54) [starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener$$Lambda$225/1444468760.run(Unknown Source) [starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_41]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_41]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_41]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-2.0 d57d156 release

**Comment by wangruin** [comment]
the same error as https://github.com/StarRocks/starrocks/issues/2014
