### ISSUE TITLE
select array<int>[] caused "Unexpected exception: null"

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#20215]
### Steps to reproduce the behavior (Required)
1. SELECT ARRAY<INT>[];

### Expected behavior (Required)
```
ARRAY<INT>[]
---------------
[]
```

### Real behavior (Required)
```
ERROR 1064 (HY000): Unexpected exception: null
```

### StarRocks version (Required)
 f0803f04a628cb17d39bd605d32640d9acb9f6a0

**Comment by sduzh** [comment]
```
2023-03-24 14:39:36,378 WARN (starrocks-mysql-nio-pool-0|183) [ConnectProcessor.handleQuery():376] Process one query failed. SQL: select ARRAY<INT>[], because unknown reason:
java.lang.NullPointerException: null
	at com.starrocks.sql.parser.AstBuilder.visitArrayConstructor(AstBuilder.java:5341) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.AstBuilder.visitArrayConstructor(AstBuilder.java:401) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$ArrayConstructorContext.accept(StarRocksParser.java:32033) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.StarRocksBaseVisitor.visitValueExpressionDefault(StarRocksBaseVisitor.java:2323) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$ValueExpressionDefaultContext.accept(StarRocksParser.java:31417) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.AstBuilder.visitPredicate(AstBuilder.java:4725) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.AstBuilder.visitPredicate(AstBuilder.java:401) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$PredicateContext.accept(StarRocksParser.java:31021) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.StarRocksBaseVisitor.visitBooleanExpressionDefault(StarRocksBaseVisitor.java:2260) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$BooleanExpressionDefaultContext.accept(StarRocksParser.java:30837) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.StarRocksBaseVisitor.visitExpressionDefault(StarRocksBaseVisitor.java:2225) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$ExpressionDefaultContext.accept(StarRocksParser.java:30259) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.AstBuilder.visitSelectSingle(AstBuilder.java:3699) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.AstBuilder.visitSelectSingle(AstBuilder.java:401) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$SelectSingleContext.accept(StarRocksParser.java:27956) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_202]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_202]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_202]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_202]
	at com.starrocks.sql.parser.AstBuilder.visit(AstBuilder.java:5858) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.AstBuilder.visitQuerySpecification(AstBuilder.java:3580) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.AstBuilder.visitQuerySpecification(AstBuilder.java:401) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$QuerySpecificationContext.accept(StarRocksParser.java:27266) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.StarRocksBaseVisitor.visitQueryPrimaryDefault(StarRocksBaseVisitor.java:1966) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$QueryPrimaryDefaultContext.accept(StarRocksParser.java:26806) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.AstBuilder.visitQueryNoWith(AstBuilder.java:3529) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.AstBuilder.visitQueryNoWith(AstBuilder.java:401) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$QueryNoWithContext.accept(StarRocksParser.java:26530) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.AstBuilder.visitQueryRelation(AstBuilder.java:3494) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.AstBuilder.visitQueryRelation(AstBuilder.java:401) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$QueryRelationContext.accept(StarRocksParser.java:26397) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.AstBuilder.visitQueryStatement(AstBuilder.java:3475) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.AstBuilder.visitQueryStatement(AstBuilder.java:401) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$QueryStatementContext.accept(StarRocksParser.java:26315) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.StarRocksBaseVisitor.visitStatement(StarRocksBaseVisitor.java:41) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.StarRocksParser$StatementContext.accept(StarRocksParser.java:1278) ~[starrocks-fe.jar:?]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.9.2.jar:4.9.2]
	at com.starrocks.sql.parser.AstBuilder.visitSingleStatement(AstBuilder.java:423) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.SqlParser.parseWithStarRocksDialect(SqlParser.java:82) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.parser.SqlParser.parse(SqlParser.java:49) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:323) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:462) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:728) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```
