### ISSUE TITLE
The Azure doesn't work after upgrade

### ISSUE THREAD

**Issue by chaoyli** [StarRocks/starrocks#20495]
```
com.starrocks.common.UserException: Illegal azure load properties
	at com.starrocks.fs.hdfs.HdfsFsManager.getAzureFileSystem(HdfsFsManager.java:650) ~[starrocks-fe.jar:?]
	at com.starrocks.fs.hdfs.HdfsFsManager.getFileSystem(HdfsFsManager.java:394) ~[starrocks-fe.jar:?]
	at com.starrocks.fs.hdfs.HdfsFsManager.listPath(HdfsFsManager.java:1096) ~[starrocks-fe.jar:?]
	at com.starrocks.fs.hdfs.HdfsService.listPath(HdfsService.java:59) ~[starrocks-fe.jar:?]
	at com.starrocks.fs.HdfsUtil.parseFile(HdfsUtil.java:81) ~[starrocks-fe.jar:?]
	at com.starrocks.load.loadv2.BrokerLoadPendingTask.getAllFileStatus(BrokerLoadPendingTask.java:97) ~[starrocks-fe.jar:?]
	at com.starrocks.load.loadv2.BrokerLoadPendingTask.executeTask(BrokerLoadPendingTask.java:75) ~[starrocks-fe.jar:?]
	at com.starrocks.load.loadv2.LoadTask.exec(LoadTask.java:73) [starrocks-fe.jar:?]
	at com.starrocks.task.PriorityLeaderTask.run(PriorityLeaderTask.java:38) [starrocks-fe.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

```
LOAD LABEL `TEST1_label` (
  DATA INFILE("wasb://bucket1@root.azurite.local.com:10000/*") INTO TABLE `MYTABLE` FORMAT AS "parquet" (`ACTIVITY`)
  SET
(`ACTIVITY` = `ACTIVITY`)
) WITH BROKER ("foo" = "bar") PROPERTIES ("max_filter_ratio" = "0.2", "timeout" = "36000")
```

Before the upgrade, the commit hash is 9041d0f1; after the upgrade the commit hash is 468a5fb9.

**Comment by Smith-Cruise** [comment]
fixed by using new parameters
