### ISSUE TITLE
[AUTO_INCREMENT column] 'Index: 4, Size: 4' error when insert table with auto_increment column

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#20518]
### Steps to reproduce the behavior (Required)
````sql
drop table if exists test_tbl_1;
create table test_tbl_1(k1 bigint not null auto_increment,k2 string,k3 boolean,k4 int,k5 int default "999")
primary key(k1)
partition by range(k1)
(partition p1 values less than("10"),
 partition p2 values less than("20"),
 partition p3 values less than("30"),
 partition p4 values less than("40"),
 partition p5 values less than("50"),
 partition p6 values less than("60000000"))
distributed by hash(k1) buckets 3;
insert into test_tbl_1(k2,k3,k4,k5) values('insert value-51', 0, 51, default);
````

fe.warn.log:
```
2023-03-29 11:20:09,560 WARN (starrocks-mysql-nio-pool-13|320) [StmtExecutor.execute():552] execute Exception, sql insert into test_tbl_1(k2,k3,k4,k5) values('insert value-51', 0, 51, default)
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_252]
        at java.util.ArrayList.set(ArrayList.java:448) ~[?:1.8.0_252]
        at com.starrocks.sql.InsertPlanner.castLiteralToTargetColumnsType(InsertPlanner.java:267) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.InsertPlanner.plan(InsertPlanner.java:107) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:93) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:55) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:395) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:348) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:462) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:728) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

Table without auto_increment column OK:
````sql
drop table if exists test_tbl_2;
create table test_tbl_2(k1 bigint,k2 string,k3 boolean,k4 int,k5 int default "999")
primary key(k1)
partition by range(k1)
(partition p1 values less than("10"),
 partition p2 values less than("20"),
 partition p3 values less than("30"),
 partition p4 values less than("40"),
 partition p5 values less than("50"),
 partition p6 values less than("60000000"))
distributed by hash(k1) buckets 3;
insert into test_tbl_2(k1,k2,k3,k4,k5) values(1,'insert value-51', 0, 51, default);
````

### Expected behavior (Required)
insert ok

### Real behavior (Required)
error:
```
mysql> insert into test_tbl_1(k2,k3,k4,k5) values('insert value-51', 0, 51, default);
ERROR 1064 (HY000): Index: 4, Size: 4
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-3.0-RELEASE 81c5b9e |
+----------------------------+
1 row in set (0.01 sec)
```

**Comment by tiannan-sr** [comment]
Table with auto_increment column ,but without column: [ k5 int default "999" ] can also be inserted successfully:
````sql
drop table if exists test_tbl_3;
create table test_tbl_3(k1 bigint not null auto_increment,k2 string,k3 boolean,k4 int)
primary key(k1)
partition by range(k1)
(partition p1 values less than("10"),
 partition p2 values less than("20"),
 partition p3 values less than("30"),
 partition p4 values less than("40"),
 partition p5 values less than("50"),
 partition p6 values less than("60000000"))
distributed by hash(k1) buckets 3;
insert into test_tbl_3(k2,k3,k4) values ('insert value-51', 0, 51);
````
