### ISSUE TITLE
[AUTO_INCREMENT] FE cannot start after cluster rollback from 3.0 to 2.5 with auto_increment column

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#20679]
### Steps to reproduce the behavior (Required)
1. branch-3.0:  create tables with auto increment column;
2. rollback to branch-2.5, fe cannot start:
```
2023-03-30 21:18:34,780 INFO (main|1) [BDBEnvironment.setupEnvironment():254] start to setup bdb environment for 3 times
2023-03-30 21:18:34,788 ERROR (main|1) [BDBEnvironment.setupEnvironment():290] failed to setup environment after retried 3 times
com.sleepycat.je.VersionMismatchException: (JE 7.3.7) 172.26.92.200_9312_1680081914949(-1):/home/disk1/sr/qa_test_master_02/fe/meta/bdb Expected log version 14 or earlier but found 17 VERSION_MISMATCH: The existing log was written with a version of JE that is later than the running version of JE, the log cannot be read. Environment is invalid and must be closed. Couldn't open file /home/disk1/sr/qa_test_master_02/fe/meta/bdb/00000003.jdb
	at com.sleepycat.je.log.FileHeader.validate(FileHeader.java:68) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.log.FileManager.readAndValidateFileHeader(FileManager.java:1495) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.log.FileManager.openFileHandle(FileManager.java:1431) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.log.FileManager.getFileHandle(FileManager.java:1232) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.log.LastFileReader.startAtLastGoodFile(LastFileReader.java:147) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.log.LastFileReader.<init>(LastFileReader.java:80) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.recovery.RecoveryManager.findEndOfLog(RecoveryManager.java:512) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.recovery.RecoveryManager.recover(RecoveryManager.java:339) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.dbi.EnvironmentImpl.finishInit(EnvironmentImpl.java:841) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:222) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:267) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.Environment.<init>(Environment.java:252) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:607) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:466) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:540) ~[je-7.3.7.jar:7.3.7]
	at com.starrocks.journal.bdbje.BDBEnvironment.setupEnvironment(BDBEnvironment.java:255) [starrocks-fe.jar:?]
	at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:162) [starrocks-fe.jar:?]
	at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:140) [starrocks-fe.jar:?]
	at com.starrocks.journal.JournalFactory.create(JournalFactory.java:18) [starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:975) [starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:925) [starrocks-fe.jar:?]
	at com.starrocks.StarRocksFE.start(StarRocksFE.java:116) [starrocks-fe.jar:?]
	at com.starrocks.StarRocksFE.main(StarRocksFE.java:68) [starrocks-fe.jar:?]
2023-03-30 21:18:34,789 ERROR (main|1) [StarRocksFE.start():170] StarRocksFE start failed
com.starrocks.journal.JournalException: failed to setup environment after retried 3 times
	at com.starrocks.journal.bdbje.BDBEnvironment.setupEnvironment(BDBEnvironment.java:291) ~[starrocks-fe.jar:?]
	at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:162) ~[starrocks-fe.jar:?]
	at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:140) ~[starrocks-fe.jar:?]
	at com.starrocks.journal.JournalFactory.create(JournalFactory.java:18) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:975) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:925) ~[starrocks-fe.jar:?]
	at com.starrocks.StarRocksFE.start(StarRocksFE.java:116) [starrocks-fe.jar:?]
	at com.starrocks.StarRocksFE.main(StarRocksFE.java:68) [starrocks-fe.jar:?]
Caused by: com.sleepycat.je.VersionMismatchException: (JE 7.3.7) 172.26.92.200_9312_1680081914949(-1):/home/disk1/sr/qa_test_master_02/fe/meta/bdb Expected log version 14 or earlier but found 17 VERSION_MISMATCH: The existing log was written with a version of JE that is later than the running version of JE, the log cannot be read. Environment is invalid and must be closed. Couldn't open file /home/disk1/sr/qa_test_master_02/fe/meta/bdb/00000003.jdb
	at com.sleepycat.je.log.FileHeader.validate(FileHeader.java:68) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.log.FileManager.readAndValidateFileHeader(FileManager.java:1495) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.log.FileManager.openFileHandle(FileManager.java:1431) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.log.FileManager.getFileHandle(FileManager.java:1232) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.log.LastFileReader.startAtLastGoodFile(LastFileReader.java:147) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.log.LastFileReader.<init>(LastFileReader.java:80) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.recovery.RecoveryManager.findEndOfLog(RecoveryManager.java:512) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.recovery.RecoveryManager.recover(RecoveryManager.java:339) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.dbi.EnvironmentImpl.finishInit(EnvironmentImpl.java:841) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:222) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:267) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.Environment.<init>(Environment.java:252) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:607) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:466) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:540) ~[je-7.3.7.jar:7.3.7]
	at com.starrocks.journal.bdbje.BDBEnvironment.setupEnvironment(BDBEnvironment.java:255) ~[starrocks-fe.jar:?]
	... 7 more
```

### Expected behavior (Required)
cluster status normal after rollback to branch-2.5

### Real behavior (Required)
fe cannot start

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-3.0-RELEASE 7d4c5d4 |
+----------------------------+
1 row in set (0.01 sec)
```

**Comment by tiannan-sr** [comment]
not a bug, fe cannot start because of bdbje upgrade
