### ISSUE TITLE
colocate info can't deleted after drop database

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#2088]
### Steps to reproduce the behavior (Required)
Create lots of tables  with colocate group and drop database without force concurrently
### Expected behavior (Required)
group info are deleted
### Real behavior (Required)
group info can't deleted
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
d57d156

**Comment by gengjun-git** [comment]
This may be the result of concurrent operations
```java
2022-01-04 00:56:59,159 ERROR (colocate group clone checker|91) [Daemon.run():121] daemon thread got exception. name: colocate group clone checker
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_252]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_252]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_252]
        at com.google.common.collect.AbstractMapBasedMultimap$KeySet$1.next(AbstractMapBasedMultimap.java:929) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.clone.ColocateTableBalancer.matchGroup(ColocateTableBalancer.java:188) ~[starrocks-fe.jar:?]
        at com.starrocks.clone.ColocateTableBalancer.runAfterCatalogReady(ColocateTableBalancer.java:90) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
```

When deleting a groupId, the keySet of group2Tables is referenced by the colocate checker thread.
