### ISSUE TITLE
FE can't receive heartbeat from BE resulting in query error

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#2152]
### Steps to reproduce the behavior (Required)
fe.log:
```
2021-12-15 05:14:10,486 INFO (Thread-41|86) [ReportHandler.taskReport():363] finished to handle task report from backend 10004, diff task num: 0. cost: 0 ms
2021-12-15 05:14:12,730 WARN (heartbeat-mgr-pool-2|99) [HeartbeatMgr$BackendHeartbeatHandler.call():260] backend heartbeat got exception
org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.thrift.HeartbeatService$Client.recv_heartbeat(HeartbeatService.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.thrift.HeartbeatService$Client.heartbeat(HeartbeatService.java:48) ~[starrocks-fe.jar:?]
        at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:235) [starrocks-fe.jar:?]
        at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:214) [starrocks-fe.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_272]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_272]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_272]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_272]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_272]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_272]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_272]
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:125) ~[libthrift-0.13.0.jar:0.13.0]
        ... 13 more
2021-12-15 05:14:12,886 WARN (heartbeat mgr|31) [HeartbeatMgr.runAfterCatalogReady():143] get bad heartbeat response: type: BACKEND, status: BAD, msg: java.net.SocketTimeoutExcep
tion: Read timed out
2021-12-15 05:14:12,887 INFO (heartbeat mgr|31) [Backend.handleHbResponse():674] Backend [id=10002, host=172.26.92.182, heartbeatPort=9354, alive=false] is dead,
2021-12-15 05:14:13,691 INFO (tablet scheduler|37) [ClusterLoadStatistic.classifyBackendByLoad():155] classify backend by load. medium: HDD, avg load score: 1.0099961155099704, l
ow/mid/high: 0/3/0
2021-12-15 05:14:13,691 INFO (tablet scheduler|37) [TabletScheduler.updateClusterLoadStatistic():353] update cluster default_cluster load statistic:
```

be.log:
```
I1215 05:14:06.685658 189874 plan_fragment_executor.cpp:222] Open(): fragment_instance_id=c592dbca-5d22-11ec-be5a-00163e03f189
I1215 05:14:06.686251 190032 internal_service.cpp:241] exec plan fragment, fragment_instance_id=c592dbca-5d22-11ec-be5a-00163e03f187, coord=TNetworkAddress(hostname=172.26.92.182, port=9322), backend=6 is_pipeline 0
I1215 05:14:06.686388 190032 plan_fragment_executor.cpp:70] Prepare(): query_id=c592dbca-5d22-11ec-be5a-00163e03f184 fragment_instance_id=c592dbca-5d22-11ec-be5a-00163e03f187 backend_num=6
I1215 05:14:06.686374 189904 plan_fragment_executor.cpp:222] Open(): fragment_instance_id=c592b4b5-5d22-11ec-be5a-00163e03f190
I1215 05:14:06.686432 190032 plan_fragment_executor.cpp:119] Using query memory limit: 2.00 GB
I1215 05:14:06.692591 190012 internal_service.cpp:241] exec plan fragment, fragment_instance_id=c592b4b5-5d22-11ec-be5a-00163e03f18d, coord=TNetworkAddress(hostname=172.26.92.182, port=9322), backend=9 is_pipeline 0
I1215 05:14:06.693097 189868 plan_fragment_executor.cpp:222] Open(): fragment_instance_id=c592dbca-5d22-11ec-be5a-00163e03f187
I1215 05:14:06.693217 190012 plan_fragment_executor.cpp:70] Prepare(): query_id=c592b4b5-5d22-11ec-be5a-00163e03f184 fragment_instance_id=c592b4b5-5d22-11ec-be5a-00163e03f18d backend_num=9
I1215 05:14:06.693271 190012 plan_fragment_executor.cpp:119] Using query memory limit: 2.00 GB
I1215 05:14:06.694056 190038 internal_service.cpp:241] exec plan fragment, fragment_instance_id=c5923f7a-5d22-11ec-be5a-00163e03f18b, coord=TNetworkAddress(hostname=172.26.92.182, port=9322), backend=8 is_pipeline 0
I1215 05:14:06.694092 189901 plan_fragment_executor.cpp:222] Open(): fragment_instance_id=c592b4b5-5d22-11ec-be5a-00163e03f18d
I1215 05:14:06.694202 190038 plan_fragment_executor.cpp:70] Prepare(): query_id=c5923f7a-5d22-11ec-be5a-00163e03f184 fragment_instance_id=c5923f7a-5d22-11ec-be5a-00163e03f18b backend_num=8
I1215 05:14:06.694247 190038 plan_fragment_executor.cpp:119] Using query memory limit: 2.00 GB
I1215 05:14:06.694803 190031 internal_service.cpp:241] exec plan fragment, fragment_instance_id=c592b4b5-5d22-11ec-be5a-00163e03f18a, coord=TNetworkAddress(hostname=172.26.92.182, port=9322), backend=12 is_pipeline 0
I1215 05:14:06.695008 190031 plan_fragment_executor.cpp:70] Prepare(): query_id=c592b4b5-5d22-11ec-be5a-00163e03f184 fragment_instance_id=c592b4b5-5d22-11ec-be5a-00163e03f18a backend_num=12
I1215 05:14:06.695058 190031 plan_fragment_executor.cpp:119] Using query memory limit: 2.00 GB
I1215 05:14:06.697301 189894 plan_fragment_executor.cpp:488] Fragment c589b3ed-5d22-11ec-be5a-00163e03f18a:(Active: 51.855ms, non-child: 0.00%)
I1215 05:14:06.701925 189894 plan_fragment_executor.cpp:222] Open(): fragment_instance_id=c5923f7a-5d22-11ec-be5a-00163e03f18b
I1215 05:14:06.718878 189894 plan_fragment_executor.cpp:488] Fragment c5923f7a-5d22-11ec-be5a-00163e03f18b:(Active: 5.620ms, non-child: 0.00%)
I1215 05:14:13.589038 189643 daemon.cpp:84] Released 24117760 bytes from column pool
I1215 05:14:13.178642 189888 plan_fragment_executor.cpp:222] Open(): fragment_instance_id=c5923f7a-5d22-11ec-be5a-00163e03f186
I1215 05:14:13.277830 190036 internal_service.cpp:241] exec plan fragment, fragment_instance_id=c5923f7a-5d22-11ec-be5a-00163e03f18a, coord=TNetworkAddress(hostname=172.26.92.182, port=9322), backend=11 is_pipeline 0
I1215 05:14:14.088562 190036 plan_fragment_executor.cpp:70] Prepare(): query_id=c5923f7a-5d22-11ec-be5a-00163e03f184 fragment_instance_id=c5923f7a-5d22-11ec-be5a-00163e03f18a backend_num=11
I1215 05:14:14.088793 190036 plan_fragment_executor.cpp:119] Using query memory limit: 2.00 GB
I1215 05:14:14.185214 189906 plan_fragment_executor.cpp:488] Fragment c58dab8f-5d22-11ec-be5a-00163e03f187:(Active: 7s425ms, non-child: 0.00%)
I1215 05:14:14.186363 189894 plan_fragment_executor.cpp:222] Open(): fragment_instance_id=c592b4b5-5d22-11ec-be5a-00163e03f18a
I1215 05:14:14.285581 189905 plan_fragment_executor.cpp:488] Fragment c58dab8f-5d22-11ec-be5a-00163e03f189:(Active: 7s633ms, non-child: 1.35%)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.0 asan
```
mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_BRANCH_ASAN 9025308 |
+------------------------------+
```

**Comment by Astralidea** [comment]
The default timeout time of the heartbeat is 5s, which means that BE is hang in these 5 seconds. 
That is, 2021-12-15 05:14:07~2021-12-15 05:14:12.
it needs to figure out what operation is causing this. If you look at the log, there seems to be a Released 24117760 bytes from column pool may be a hint.
