### ISSUE TITLE
Crazy refreshing of materialized view causes FE to fail to start

### ISSUE THREAD

**Issue by Astralidea** [StarRocks/starrocks#21654]
### Steps to reproduce the behavior (Required)
1. Crazy refreshing materialized view

### Real behavior (Required)
2023-02-20 00:00:37,251 ERROR (leaderCheckpointer|655) [Checkpoint.replayAndGenerateGlobalStateMgrImage():214] Exception when generate new image file
java.lang.IllegalArgumentException: null
        at java.nio.CharBuffer.allocate(CharBuffer.java:334) ~[?:1.8.0_144]
        at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:810) ~[?:1.8.0_144]
        at com.starrocks.common.io.Text.decode(Text.java:336) ~[starrocks-fe.jar:?]
        at com.starrocks.common.io.Text.decode(Text.java:315) ~[starrocks-fe.jar:?]
        at com.starrocks.common.io.Text.readString(Text.java:390) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskManager.loadTasks(TaskManager.java:396) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1183) ~[starrocks-fe.jar:?]
        at com.starrocks.leader.Checkpoint.replayAndGenerateGlobalStateMgrImage(Checkpoint.java:201) [starrocks-fe.jar:?]
        at com.starrocks.leader.Checkpoint.runAfterCatalogReady(Checkpoint.java:93) [starrocks-fe.jar:?]
        at com.starrocks.common.util.LeaderDaemon.runOneCycle(LeaderDaemon.java:60) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.4~2.5

**Comment by gengjun-git** [comment]
Use the following patch to recover. After the new image is generated, you need to upgrade your StarRocks to the new version.

```
diff --git a/fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java b/fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
index 7139b16327..eefa5ade24 100644
--- a/fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
+++ b/fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java
@@ -7,6 +7,7 @@ import com.clearspring.analytics.util.Preconditions;
 import com.google.common.collect.ImmutableList;
 import com.google.common.collect.Maps;
 import com.google.gson.annotations.SerializedName;
+import com.google.gson.stream.JsonReader;
 import com.starrocks.catalog.Column;
 import com.starrocks.catalog.ScalarType;
 import com.starrocks.common.DdlException;
@@ -28,10 +29,13 @@ import com.starrocks.sql.optimizer.Utils;
 import org.apache.logging.log4j.LogManager;
 import org.apache.logging.log4j.Logger;
 
+import java.io.ByteArrayInputStream;
 import java.io.DataInputStream;
 import java.io.DataOutputStream;
 import java.io.EOFException;
 import java.io.IOException;
+import java.io.InputStreamReader;
+import java.nio.charset.StandardCharsets;
 import java.time.Duration;
 import java.time.LocalDateTime;
 import java.util.ArrayList;
@@ -421,20 +425,25 @@ public class TaskManager {
     public long loadTasks(DataInputStream dis, long checksum) throws IOException {
         int taskCount = 0;
         try {
-            String s = Text.readString(dis);
-            SerializeData data = GsonUtils.GSON.fromJson(s, SerializeData.class);
-            if (data != null) {
-                if (data.tasks != null) {
-                    for (Task task : data.tasks) {
-                        replayCreateTask(task);
-                    }
-                    taskCount = data.tasks.size();
+            int length = dis.readInt();
+            byte[] bytes = new byte[length];
+            dis.readFully(bytes, 0, length);
+            SerializeData data;
+            try (JsonReader jsonReader = new JsonReader(new InputStreamReader(new ByteArrayInputStream(bytes),
+                    StandardCharsets.UTF_8))) {
+                data = GsonUtils.GSON.fromJson(jsonReader, SerializeData.class);
+            }
+            data.runStatus = null;
+            if (data.tasks != null) {
+                for (Task task : data.tasks) {
+                    replayCreateTask(task);
                 }
+                taskCount = data.tasks.size();
+            }
 
-                if (data.runStatus != null) {
-                    for (TaskRunStatus runStatus : data.runStatus) {
-                        replayCreateTaskRun(runStatus);
-                    }
+            if (data.runStatus != null) {
+                for (TaskRunStatus runStatus : data.runStatus) {
+                    replayCreateTaskRun(runStatus);
                 }
             }
             checksum ^= taskCount;
```
