### ISSUE TITLE
Sqlancer report error: StarRocks planner use long time 3000 ms in logical phase, This probably because 1. FE Full GC, 2. Hive external table fetch metadata took a long time, 3. The SQL is very complex. You could 1. adjust FE JVM config, 2. try query again, 3. enlarge new_planner_optimize_timeout session variable

### ISSUE THREAD

**Issue by satanson** [StarRocks/starrocks#22335]
### Steps to reproduce the behavior (Required)
1. Prepare Data:

```sql
-- Time: 2023/04/23 17:04:05
-- Database: d9
-- Database version: 5.1.0
-- seed value: 1682240321929
DROP DATABASE IF EXISTS d9;
CREATE DATABASE d9;
USE d9;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATETIME NOT NULL,c_0_1 TINYINT NOT NULL,c_0_2 BIGINT NOT NULL,c_0_3 DATE NOT NULL,c_0_4 VARCHAR(41) NOT NULL,c_0_5 BOOLEAN NOT NULL,c_0_6 BIGINT NOT NULL,c_0_7 SMALLINT NOT NULL,c_0_8 VARCHAR(1) NOT NULL,c_0_9 BIGINT NOT NULL,c_0_10 DATETIME NOT NULL,c_0_11 DECIMAL(34, 19)  NOT NULL,c_0_12 DATE NOT NULL, INDEX index1_c_0_4(`c_0_4`) USING BITMAP) PRIMARY KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 1582 day)) DISTRIBUTED BY HASH (c_0_0,c_0_8,c_0_7,c_0_4,c_0_5) BUCKETS 3 properties("replication_num"="1", "bloom_filter_columns"="c_0_2, c_0_4") ;
CREATE TABLE t1 (c_1_0 DECIMAL(7, 2)  NOT NULL ,c_1_1 DATE NULL ,c_1_2 DATE NULL ,c_1_3 TINYINT NOT NULL ,c_1_4 DATE NULL ,c_1_5 DATETIME NULL ,c_1_6 CHAR(11) NOT NULL ,c_1_7 DATE NULL ,c_1_8 DECIMAL(21, 0)  NOT NULL ,c_1_9 DATE NOT NULL ,c_1_10 BOOLEAN REPLACE NULL ,c_1_11 DATETIME REPLACE_IF_NOT_NULL NOT NULL ,c_1_12 DECIMAL(31, 5)  MAX NOT NULL ,c_1_13 BOOLEAN REPLACE NULL ,c_1_14 BOOLEAN REPLACE NOT NULL ,c_1_15 PERCENTILE PERCENTILE_UNION NULL ,c_1_16 TINYINT REPLACE_IF_NOT_NULL NULL ,c_1_17 DECIMAL(8, 0)  SUM NULL ,c_1_18 HLL HLL_UNION NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 791 day)) DISTRIBUTED BY HASH (c_1_3) BUCKETS 3 properties("replication_num"="1") ;
INSERT INTO t0 VALUES ('2010-01-10 08:00:14', 1, 1383996213, '2010-01-16', 'qM', false, 1383996213, 15, '', 897805346, '2010-01-28 08:00:14', 0.0000429418621564036, '2010-01-15'), ('2010-01-07 08:00:14', 6, 897805346, '2010-01-30', '', false, -2098445232, 1, '', 244800210, '2010-01-08 08:00:14', 0.0000236070846403859, '2010-01-26');
INSERT INTO t1 VALUES (583.88, '2010-01-18', NULL, 1, '2010-01-26', '2010-01-02 08:00:14', '', '2010-01-13', 412475174986117317412, '2010-01-14', true, '2010-01-28 08:00:14', 93284422266009636715.01182, true, true, percentile_hash('-2098445232'), 3, 5834053230864810757339203877177300331, hll_hash('')), (810.77, '2010-01-14', '2010-01-15', 3, '2010-01-04', NULL, '', '2010-01-09', 735381116266007863704, '2010-01-10', false, NULL, 525018448459987352450.18460, false, false, percentile_hash('897805346'), 3, 584937393796280957758496208296486215, hll_hash('lNO')), (423.35, '2010-01-20', '2010-01-18', 1, '2010-01-23', '2010-01-30 08:00:14', 'q', '2010-01-21', 97894810662498268492, '2010-01-31', false, '2010-01-10 08:00:14', 682854553219196811042.47956, false, false, percentile_hash('-2098445232'), 1, 66862529455465846695006367310237394462, hll_hash('lnxa'));
DELETE FROM t0 WHERE c_0_7=-2098445232 AND c_0_4='' AND c_0_6=-2098445232 AND c_0_5=true;

```

2. Query

```sql
DELETE FROM t0 WHERE c_0_7=-2098445232 AND c_0_4='' AND c_0_6=-2098445232 AND c_0_5=true;
```
### Expected behavior (Required)
NO Error

### Real behavior (Required)
Error as follows
```
--java.lang.AssertionError: DELETE FROM t0 WHERE c_0_7=-2098445232 AND c_0_4='' AND c_0_6=-2098445232 AND c_0_5=true;
--	at sqlancer.common.query.QueryAdapter.checkException(QueryAdapter.java:98)
--	at sqlancer.common.query.QueryAdapter.execute(QueryAdapter.java:91)
--	at sqlancer.Main$QueryManager.execute(Main.java:252)
--	at sqlancer.GlobalState.executeStatement(GlobalState.java:131)
--	at sqlancer.StatementExecutor.executeStatements(StatementExecutor.java:69)
--	at sqlancer.starrocks.StarRocksProvider.generateDatabase(StarRocksProvider.java:73)
--	at sqlancer.starrocks.StarRocksProvider.generateDatabase(StarRocksProvider.java:1)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:47)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:334)
--	at sqlancer.Main$2.run(Main.java:542)
--	at sqlancer.Main$2.runThread(Main.java:519)
--	at sqlancer.Main$2.run(Main.java:509)
--	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
--	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
--	at java.lang.Thread.run(Thread.java:748)
--Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: StarRocks planner use long time 3000 ms in logical phase, This probably because 1. FE Full GC, 2. Hive external table fetch metadata took a long time, 3. The SQL is very complex. You could 1. adjust FE JVM config, 2. try query again, 3. enlarge new_planner_optimize_timeout session variable
--	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
--	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
--	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
--	at com.mysql.jdbc.Util.getInstance(Util.java:408)
--	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
--	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
--	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2497)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2455)
--	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
--	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
--	at sqlancer.common.query.QueryAdapter.execute(QueryAdapter.java:85)
--	... 13 more
--
```
### StarRocks version (Required)
- main(688433861d)

**Comment by kangkaisen** [comment]
the disk io issue.
