### ISSUE TITLE
Sqlancer report error: Unexpected exception: Failed to acquire globalStateMgr lock. Try again

### ISSUE THREAD

**Issue by satanson** [StarRocks/starrocks#22334]
### Steps to reproduce the behavior (Required)
1. Prepare Data:

```sql
-- Time: 2023/04/23 16:58:53
-- Database: n0
-- Database version: null
-- seed value: 1682240321855
DROP DATABASE IF EXISTS n0;
CREATE DATABASE n0;
USE n0;

```

2. Query

```sql
Unexpected exception: Failed to acquire globalStateMgr lock. Try again
```
### Expected behavior (Required)
NO Error

### Real behavior (Required)
Error as follows
```
--com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unexpected exception: Failed to acquire globalStateMgr lock. Try again
--	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
--	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
--	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
--	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
--	at com.mysql.jdbc.Util.getInstance(Util.java:408)
--	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
--	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
--	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2497)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2455)
--	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
--	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
--	at sqlancer.starrocks.StarRocksProvider.createDatabase(StarRocksProvider.java:93)
--	at sqlancer.starrocks.StarRocksProvider.createDatabase(StarRocksProvider.java:1)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:320)
--	at sqlancer.Main$2.run(Main.java:542)
--	at sqlancer.Main$2.runThread(Main.java:519)
--	at sqlancer.Main$2.run(Main.java:509)
--	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
--	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
--	at java.lang.Thread.run(Thread.java:748)
--
```
### StarRocks version (Required)
- main(688433861d)

**Comment by kangkaisen** [comment]
the disk io issue.
