### ISSUE TITLE
ASAN BE crashed when delete rows from primary key table

### ISSUE THREAD

**Issue by ZiheLiu** [StarRocks/starrocks#22362]
### Steps to reproduce the behavior (Required)
BE uses **ASAN** mode.
Daily case: TestSqlancer.test_sr_9248_2_bug

```sql
SET sql_mode = 'ONLY_FULL_GROUP_BY,PIPES_AS_CONCAT';
set enable_insert_strict = False;
admin set frontend config ("enable_decimal_v3" = "true");

CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATE NOT NULL,c_1_1 DATE NOT NULL,c_1_2 VARCHAR(1) NOT NULL,c_1_3 VARCHAR(1) NOT NULL,c_1_4 BOOLEAN NOT NULL,c_1_5 BIGINT NOT NULL,c_1_6 VARCHAR(11) NOT NULL,c_1_7 BOOLEAN NOT NULL,c_1_8 DECIMAL(21, 14)  NOT NULL,c_1_9 FLOAT NOT NULL,c_1_10 DATETIME NOT NULL,c_1_11 VARCHAR(11) NOT NULL,c_1_12 BOOLEAN NOT NULL,c_1_13 LARGEINT NOT NULL,c_1_14 DOUBLE NOT NULL, INDEX index1_c_1_3(`c_1_3`) USING BITMAP, INDEX index1_c_1_5(`c_1_5`) USING BITMAP, INDEX index1_c_1_6(`c_1_6`) USING BITMAP) PRIMARY KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 243 day)) DISTRIBUTED BY HASH (c_1_1,c_1_4,c_1_3,c_1_0,c_1_7,c_1_6,c_1_2,c_1_5) BUCKETS 3 properties("replication_num"="3") ;

INSERT INTO t1 VALUES ('2010-01-07', '2010-01-22', '', '', false, 2056189775, 'ZEb', true, 6.670807E-8, 0.9856970986288477, '2010-01-07 08:00:14', 'l', false, 2100391351, 0.8545141916891065);
INSERT INTO t1 VALUES ('2010-01-12', '2010-01-30', '', '', false, 387924244, '0V', true, 5.128304E-8, 0.8797504076995621, '2010-01-28 08:00:14', 'd', false, -383507511, 2.9412386E8);

DELETE FROM t1 WHERE c_1_3='' AND c_1_4=false AND c_1_2='';

```
### Expected behavior (Required)
BE don't crash.

### Real behavior (Required)
BE crased.

be.WARNING
```
F0424 13:30:27.173856 26981 rowset_writer.cpp:147] Check failed: _delfile_idxes.size() == _num_delfile
```

be.out
```
*** SIGABRT (@0x3e8000068fb) received by PID 26875 (TID 0x7f8c4322c700) from PID 26875; stack trace: ***
    @         0x17e1efa2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f8c66aad630 (unknown)
    @     0x7f8c65ff8387 __GI_raise
    @     0x7f8c65ff9a78 __GI_abort
    @          0xe235f69 starrocks::failure_function()
    @         0x17e0c0ad google::LogMessage::Fail()
    @         0x17e0e51f google::LogMessage::SendToLog()
    @         0x17e0bbfe google::LogMessage::Flush()
    @         0x17e0eb29 google::LogMessageFatal::~LogMessageFatal()
    @         0x15ede35a starrocks::RowsetWriter::build()
    @         0x15eeb32c starrocks::HorizontalRowsetWriter::build()
    @         0x15be9e9b starrocks::DeltaWriter::commit()
    @         0x1411d131 _ZZN9starrocks17SegmentFlushToken6submitEPN4brpc10ControllerEPKNS_30PTabletWriterAddSegmentRequestEPNS_29PTabletWriterAddSegmentResultEPN6google8protobuf7ClosureEENKUlvE_clEv
    @         0x1411ecee _ZSt13__invoke_implIvRZN9starrocks17SegmentFlushToken6submitEPN4brpc10ControllerEPKNS0_30PTabletWriterAddSegmentRequestEPNS0_29PTabletWriterAddSegmentResultEPN6google8protobuf7ClosureEEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @         0x1411eb9d _ZSt10__invoke_rIvRZN9starrocks17SegmentFlushToken6submitEPN4brpc10ControllerEPKNS0_30PTabletWriterAddSegmentRequestEPNS0_29PTabletWriterAddSegmentResultEPN6google8protobuf7ClosureEEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESH_E4typeEOSI_DpOSJ_
    @         0x1411e755 _ZNSt17_Function_handlerIFvvEZN9starrocks17SegmentFlushToken6submitEPN4brpc10ControllerEPKNS1_30PTabletWriterAddSegmentRequestEPNS1_29PTabletWriterAddSegmentResultEPN6google8protobuf7ClosureEEUlvE_E9_M_invokeERKSt9_Any_data
    @          0xe12cfe8 std::function<>::operator()()
    @         0x1669fa9c starrocks::FunctionRunnable::run()
    @         0x1669c7bb starrocks::ThreadPool::dispatch_thread()
    @         0x166b8402 std::__invoke_impl<>()
    @         0x166b7d5b std::__invoke<>()
    @         0x166b7152 _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @         0x166b5ab4 std::_Bind<>::operator()<>()
    @         0x166b2b24 std::__invoke_impl<>()
    @         0x166b04e0 _ZSt10__invoke_rIvRSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @         0x166ac571 std::_Function_handler<>::_M_invoke()
    @          0xe12cfe8 std::function<>::operator()()
    @         0x16684c15 starrocks::Thread::supervise_thread()
    @     0x7f8c66aa5ea5 start_thread
    @     0x7f8c660c0b0d __clone
    @                0x0 (unknown)
```

What's worse, after one BE crashed by the above `DHECK`, the other 2 BE also crashed:
```

==26804==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f3f9e9f3210 at pc 0x00000df249e1 bp 0x7f3f9e9f2a40 sp 0x7f3f9e9f21f0
READ of size 267484782 at 0x7f3f9e9f3210 thread T88 (delta_writer)
    #0 0xdf249e0 in __interceptor_memmove ../../../../libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:789
    #1 0xe2b5672 in char* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<char>(char const*, char const*, char*) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/stl_algobase.h:426
    #2 0xe2b5605 in char* std::__copy_move_a2<false, char const*, char*>(char const*, char const*, char*) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/stl_algobase.h:472
    #3 0xe2b53be in char* std::__copy_move_a1<false, char const*, char*>(char const*, char const*, char*) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/stl_algobase.h:506
    #4 0xe2b524d in char* std::__copy_move_a<false, char const*, char*>(char const*, char const*, char*) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/stl_algobase.h:513
    #5 0xe2b4a8e in char* std::copy<char const*, char*>(char const*, char const*, char*) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/stl_algobase.h:569
    #6 0xe68b4fc in std::back_insert_iterator<fmt::v7::detail::buffer<char> > fmt::v7::detail::write<char, std::back_insert_iterator<fmt::v7::detail::buffer<char> > >(std::back_insert_iterator<fmt::v7::detail::buffer<char> >, fmt::v7::basic_string_view<char>) /home/disk5/sr-deps/thirdparty-re2/installed/include/fmt/format.h:1751
    #7 0x19394206 in std::back_insert_iterator<fmt::v7::detail::buffer<char> > fmt::v7::detail::default_arg_formatter<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>::operator()<fmt::v7::basic_string_view<char> >(fmt::v7::basic_string_view<char>) /var/local/thirdparty/src/fmt-7.0.3/include/fmt/format.h:1818
    #8 0x19394206 in decltype ({parm#1}(0)) fmt::v7::visit_format_arg<fmt::v7::detail::default_arg_formatter<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>, fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char> >(fmt::v7::detail::default_arg_formatter<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>&&, fmt::v7::basic_format_arg<fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char> > const&) /var/local/thirdparty/src/fmt-7.0.3/include/fmt/core.h:1192
    #9 0x19394206 in fmt::v7::detail::format_handler<fmt::v7::detail::arg_formatter<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>, char, fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char> >::on_replacement_field(int, char const*) /var/local/thirdparty/src/fmt-7.0.3/include/fmt/format.h:2730
    #10 0x19394206 in char const* fmt::v7::detail::parse_replacement_field<char, fmt::v7::detail::format_handler<fmt::v7::detail::arg_formatter<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>, char, fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char> >&>(char const*, char const*, fmt::v7::detail::format_handler<fmt::v7::detail::arg_formatter<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>, char, fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char> >&) /var/local/thirdparty/src/fmt-7.0.3/include/fmt/format.h:2625
    #11 0x193949b8 in void fmt::v7::detail::parse_format_string<false, char, fmt::v7::detail::format_handler<fmt::v7::detail::arg_formatter<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>, char, fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char> >&>(fmt::v7::basic_string_view<char>, fmt::v7::detail::format_handler<fmt::v7::detail::arg_formatter<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>, char, fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char> >&) /var/local/thirdparty/src/fmt-7.0.3/include/fmt/format.h:2649
    #12 0x193949b8 in fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>::iterator fmt::v7::vformat_to<fmt::v7::detail::arg_formatter<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>, char, fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char> >(fmt::v7::detail::arg_formatter<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>::iterator, fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char> >, fmt::v7::detail::locale_ref) /var/local/thirdparty/src/fmt-7.0.3/include/fmt/format.h:3295
    #13 0x1938a559 in fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>, fmt::v7::format_args) /var/local/thirdparty/src/fmt-7.0.3/include/fmt/format-inl.h:1408
    #14 0x161249fc in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v7::format<char [7], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, starrocks::Slice, char>(char const (&) [7], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, starrocks::Slice&&) /home/disk5/sr-deps/thirdparty-re2/installed/include/fmt/core.h:1836
    #15 0x161249fc in starrocks::LocalTabletsChannel::WriteContext::update_status(starrocks::Status const&) ../src/runtime/local_tablets_channel.h:106
    #16 0x1612015f in starrocks::LocalTabletsChannel::WriteCallback::run(starrocks::Status const&, starrocks::CommittedRowsetInfo const*, starrocks::FailedRowsetInfo const*) ../src/runtime/local_tablets_channel.cpp:717
    #17 0x157ab5da in starrocks::AsyncDeltaWriter::_execute(void*, bthread::TaskIterator<starrocks::AsyncDeltaWriter::Task>&) ../src/storage/async_delta_writer.cpp:56
    #18 0x157b2497 in bthread::ExecutionQueue<starrocks::AsyncDeltaWriter::Task>::execute_task(void*, void*, bthread::TaskIteratorBase&) /home/disk5/sr-deps/thirdparty-re2/installed/include/bthread/execution_queue_inl.h:271
    #19 0x17f97c6b in bthread::ExecutionQueueBase::_execute(bthread::TaskNode*, bool, int*) src/bthread/execution_queue.cpp:272
    #20 0x17f989e7 in bthread::ExecutionQueueBase::_execute_tasks(void*) src/bthread/execution_queue.cpp:151
    #21 0x16461049 in operator() ../src/util/bthreads/executor.cpp:29
    #22 0x16461f31 in __invoke_impl<void, starrocks::bthreads::ThreadPoolExecutor::submit(void* (*)(void*), void*)::<lambda()>&> /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #23 0x16461dd2 in __invoke_r<void, starrocks::bthreads::ThreadPoolExecutor::submit(void* (*)(void*), void*)::<lambda()>&> /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:110
    #24 0x16461c3a in _M_invoke /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:291
    #25 0xe12cfe7 in std::function<void ()>::operator()() const /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
    #26 0x1669fa9b in starrocks::FunctionRunnable::run() ../src/util/threadpool.cpp:57
    #27 0x1669c7ba in starrocks::ThreadPool::dispatch_thread() ../src/util/threadpool.cpp:552
    #28 0x166b8401 in void std::__invoke_impl<void, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(std::__invoke_memfun_deref, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:73
    #29 0x166b7d5a in std::__invoke_result<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>::type std::__invoke<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:95
    #30 0x166b7151 in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:416
    #31 0x166b5ab3 in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::operator()<, void>() /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:499
    #32 0x166b2b23 in void std::__invoke_impl<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #33 0x166b04df in std::enable_if<is_invocable_r_v<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:110
    #34 0x166ac570 in std::_Function_handler<void (), std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:291
    #35 0xe12cfe7 in std::function<void ()>::operator()() const /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
    #36 0x16684c14 in starrocks::Thread::supervise_thread(void*) ../src/util/thread.cpp:364
    #37 0x7f3fb6cd7ea4 in start_thread (/lib64/libpthread.so.0+0x7ea4)
    #38 0x7f3fb62f2b0c in clone (/lib64/libc.so.6+0xfeb0c)

Address 0x7f3f9e9f3210 is located in stack of thread T88 (delta_writer) at offset 80 in frame
    #0 0x16124691 in starrocks::LocalTabletsChannel::WriteContext::update_status(starrocks::Status const&) ../src/runtime/local_tablets_channel.h:102

  This frame has 6 object(s):
    [32, 40) 'l' (line 107)
    [64, 80) '<unknown>'
    [96, 112) '<unknown>' <== Memory access at offset 80 partially underflows this variable
    [128, 160) 'msg' (line 106) <== Memory access at offset 80 partially underflows this variable
    [192, 224) '<unknown>' <== Memory access at offset 80 partially underflows this variable
    [256, 288) '<unknown>' <== Memory access at offset 80 partially underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T88 (delta_writer) created by T0 here:
    #0 0xdf40512 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:214
    #1 0x16683fe2 in starrocks::Thread::start_thread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, unsigned long, scoped_refptr<starrocks::Thread>*) ../src/util/thread.cpp:319
    #2 0x166a309c in starrocks::Status starrocks::Thread::create<void (starrocks::ThreadPool::*)(), starrocks::ThreadPool*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void (starrocks::ThreadPool::* const&)(), starrocks::ThreadPool* const&, scoped_refptr<starrocks::Thread>*) ../src/util/thread.h:71
    #3 0x1669daa5 in starrocks::ThreadPool::create_thread() ../src/util/threadpool.cpp:605
    #4 0x16696f14 in starrocks::ThreadPool::init() ../src/util/threadpool.cpp:267
    #5 0x16693bd1 in starrocks::ThreadPoolBuilder::build(std::unique_ptr<starrocks::ThreadPool, std::default_delete<starrocks::ThreadPool> >*) const ../src/util/threadpool.cpp:94
    #6 0x151226a2 in starrocks::StorageEngine::_open() ../src/storage/storage_engine.cpp:196
    #7 0x1511efcc in starrocks::StorageEngine::open(starrocks::EngineOptions const&, starrocks::StorageEngine**) ../src/storage/storage_engine.cpp:96
    #8 0xdfd7c40 in main ../src/service/starrocks_main.cpp:313
    #9 0x7f3fb6216554 in __libc_start_main (/lib64/libc.so.6+0x22554)

SUMMARY: AddressSanitizer: stack-buffer-overflow ../../../../libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:789 in __interceptor_memmove
Shadow bytes around the buggy address:
  0x0fe873d365f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe873d36600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe873d36610: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe873d36620: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe873d36630: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2
=>0x0fe873d36640: 00 00[f2]f2 00 00 f2 f2 00 00 00 00 f2 f2 f2 f2
  0x0fe873d36650: 00 00 00 00 f2 f2 f2 f2 00 00 00 00 f3 f3 f3 f3
  0x0fe873d36660: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe873d36670: 00 00 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2 00 f2
  0x0fe873d36680: f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 00 f2 f2 00 00
  0x0fe873d36690: f2 f2 00 00 00 00 00 00 00 00 00 00 00 00 f2 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==26804==ABORTING

```

### StarRocks version (Required)

The main branch b734ac0abe .

**Comment by sevev** [comment]
@ZiheLiu you can assign this issue to me, i will fix it later.
