### ISSUE TITLE
Bad packet sequence (Backend node not found. Check if any backend node is down)

### ISSUE THREAD

**Issue by useratmar** [StarRocks/starrocks#23382]
### Steps to reproduce the behavior (Required)
1. installation ubuntu 22.04.2 LTS from scratch
2. install openjdk-8-jdk
3. create  /etc/profile.d/java_home.sh with following content and restart computer
   export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
   export PATH=$PATH:$JAVA_HOME/bin
4. install mysql workbench    
   sudo snap install mysql-workbench-community   
   sudo snap connect mysql-workbench-community:password-manager-service :password-manager-service
   sudo snap install mysql-shell

5. follow https://docs.starrocks.io/en-us/2.5/quick_start/Deploy to install starrocks

### Expected behavior (Required)
mysqlsh -h <ip> -P 9030 -uroot

should succeed and connect to the server (where ip is the ip of a single NIC)

### Real behavior (Required)
the connection failed with following message:

Creating a session to 'root@1<ip>:9030'
Fetching schema names for autocompletion... Press ^C to stop.
ERROR: MySQL Error 1064 (HY000): Backend node not found. Check if any backend node is down.

don't see warning file be/log/be.WARNING but see following error in fe/log/fe.warn.log

2023-05-14 01:14:30,752 WARN (Routine load task scheduler|40) [RoutineLoadTaskScheduler.process():117] no available be slot to scheduler tasks, wait for 10 seconds to scheduler again, you can set max_routine_load_task_num_per_be bigger in fe.conf, current value is 10
2023-05-14 01:14:32,784 WARN (starrocks-mysql-nio-pool-0|123) [MysqlChannel.fetchOnePacket():194] receive packet sequence id[0] want to get[1]
2023-05-14 01:14:32,784 WARN (starrocks-mysql-nio-pool-0|123) [AcceptListener.lambda$handleEvent$1():108] connect processor exception because
java.io.IOException: Bad packet sequence.
        at com.starrocks.mysql.MysqlChannel.fetchOnePacket(MysqlChannel.java:195) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.MysqlProto.readAuthPacket(MysqlProto.java:275) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.MysqlProto.negotiate(MysqlProto.java:153) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.AcceptListener.lambda$handleEvent$1(AcceptListener.java:84) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2023-05-14 01:14:33,615 WARN (starrocks-mysql-nio-pool-1|124) [CoordinatorPreprocessor.computeFragmentHosts():523] DataPartition UNPARTITIONED. Backend node not found. Check if any backend node is down.
2023-05-14 01:14:33,628 WARN (starrocks-mysql-nio-pool-1|124) [Coordinator.cancel():1361] cancel execution of query, this is outside invoke
2023-05-14 01:14:40,753 WARN (Routine load task scheduler|40) [RoutineLoadTaskScheduler.process():117] no available be slot to scheduler tasks, wait for 10 seconds to scheduler again, you can set max_routine_load_task_num_per_be bigger in fe.conf, current value is 10

### StarRocks version (Required)
free installation from StarRocks-3.0.0.tar.gz

**Comment by useratmar** [comment]
downgraded to 2.5.5-24c1eca and works just fine now

**Comment by nshangyiming** [comment]
hi @useratmar , thanks for the report, i have a few questions,
- which mysqlsh version are you using? could you show the `show databases` result of 2.5 when connecting using mysqlsh? because mysql 8.0 client is not supported yet, we found some compatibility issues.
- how many backends have you deployed when using mysqlsh to connect to SR? could you use mysql 5.7.x client to connect 3.0 SR and show the `show backends` result, the `backend not found...` error is because SR FE doesn't found any alive backends when executing query.

**Comment by nshangyiming** [comment]
Since there is no further reply, i'm going to close this issue. Feel free to reopen it when necessary.
