### ISSUE TITLE
StarRocks SuperSet getting 1064, "Unknown catalog.db 'albert.demo'"

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#24011]
(MySQLdb._exceptions.ProgrammingError) (1064, "Unknown catalog.db 'albert.demo'")
(Background on this error at: https://sqlalche.me/e/14/f405)

![Screenshot 2023-05-23 at 11 04 49 AM](https://github.com/StarRocks/starrocks/assets/749093/00e3ab9c-e02b-4514-8013-6dbd0f8f9a41)

```
superset_app          | 2023-05-23 18:04:17,486:INFO:superset.sql_lab:Query 21: Set query to 'running'
superset_app          | SupersetErrorsException
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset_app          |     rv = self.dispatch_request()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
superset_app          |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 127, in wraps
superset_app          |     raise ex
superset_app          |   File "/app/superset/views/base_api.py", line 121, in wraps
superset_app          |     duration, response = time_function(f, self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1596, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 93, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/log.py", line 266, in wrapper
superset_app          |     value = f(*args, **kwargs)
superset_app          |   File "/app/superset/sqllab/api.py", line 310, in execute_sql_query
superset_app          |     command_result: CommandResult = command.run()
superset_app          |   File "/app/superset/sqllab/commands/execute.py", line 121, in run
superset_app          |     raise ex
superset_app          |   File "/app/superset/sqllab/commands/execute.py", line 103, in run
superset_app          |     status = self._run_sql_json_exec_from_scratch()
superset_app          |   File "/app/superset/sqllab/commands/execute.py", line 161, in _run_sql_json_exec_from_scratch
superset_app          |     raise ex
superset_app          |   File "/app/superset/sqllab/commands/execute.py", line 156, in _run_sql_json_exec_from_scratch
superset_app          |     return self._sql_json_executor.execute(
superset_app          |   File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
superset_app          |     raise SupersetErrorsException(
superset_app          | superset.exceptions.SupersetErrorsException: [SupersetError(message='(MySQLdb._exceptions.ProgrammingError) (1064, "Unknown catalog.db \'albert.demo\'")\n(Background on this error at: https://sqlalche.me/e/14/f405)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'StarRocks', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
superset_app          | 2023-05-23 18:04:17,626:WARNING:superset.views.base:SupersetErrorsException
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset_app          |     rv = self.dispatch_request()
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
superset_app          |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 127, in wraps
superset_app          |     raise ex
superset_app          |   File "/app/superset/views/base_api.py", line 121, in wraps
superset_app          |     duration, response = time_function(f, self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1596, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 93, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/log.py", line 266, in wrapper
superset_app          |     value = f(*args, **kwargs)
superset_app          |   File "/app/superset/sqllab/api.py", line 310, in execute_sql_query
superset_app          |     command_result: CommandResult = command.run()
superset_app          |   File "/app/superset/sqllab/commands/execute.py", line 121, in run
superset_app          |     raise ex
superset_app          |   File "/app/superset/sqllab/commands/execute.py", line 103, in run
superset_app          |     status = self._run_sql_json_exec_from_scratch()
superset_app          |   File "/app/superset/sqllab/commands/execute.py", line 161, in _run_sql_json_exec_from_scratch
superset_app          |     raise ex
superset_app          |   File "/app/superset/sqllab/commands/execute.py", line 156, in _run_sql_json_exec_from_scratch
superset_app          |     return self._sql_json_executor.execute(
superset_app          |   File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
superset_app          |     raise SupersetErrorsException(
superset_app          | superset.exceptions.SupersetErrorsException: [SupersetError(message='(MySQLdb._exceptions.ProgrammingError) (1064, "Unknown catalog.db \'albert.demo\'")\n(Background on this error at: https://sqlalche.me/e/14/f405)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'StarRocks', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
superset_app          | 172.18.0.1 - - [23/May/2023:18:04:17 +0000] "POST /api/v1/sqllab/execute/ HTTP/1.1" 500 375 "http://localhost:8088/superset/sqllab/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
superset_app          | 172.18.0.1 - - [23/May/2023:18:04:17 +0000] "PUT /tabstateview/4 HTTP/1.1" 200 1 "http://localhost:8088/superset/sqllab/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
superset_app          | 172.18.0.1 - - [23/May/2023:18:04:18 +0000] "POST /superset/log/?explode=events HTTP/1.1" 200 1 "http://localhost:8088/superset/sqllab/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
superset_app          | 127.0.0.1 - - [23/May/2023:18:04:22 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"

```

**Comment by alberttwong** [comment]
![Screenshot 2023-05-23 at 11 06 55 AM](https://github.com/StarRocks/starrocks/assets/749093/ab93ddae-948e-4fc1-b3ee-2bbede453753)

**Comment by alberttwong** [comment]
![Screenshot 2023-05-23 at 11 10 01 AM](https://github.com/StarRocks/starrocks/assets/749093/338af25e-afd3-43ee-b9c9-3f79ec349c96)

**Comment by alberttwong** [comment]
I also tried to change the albert to "default_catalog" and that did not work.  albert is a database.   The URI requests a database but not a catalog.
![Screenshot 2023-05-23 at 11 11 24 AM](https://github.com/StarRocks/starrocks/assets/749093/c49f7a86-872f-4142-9793-fa4a552e9949)
![Screenshot 2023-05-23 at 11 11 11 AM](https://github.com/StarRocks/starrocks/assets/749093/318c9a50-0720-46d3-b58a-07c2aae7acf3)

**Comment by miomiocat** [comment]
seems usage error. 
URI format: starrocks://<user>:<password>@ip:port/<catalog>.<db>
this cannot be starrocks://<user>:<password>@ip:port/<catalog>
