### ISSUE TITLE
StarRocks SuperSet issue with creating dataset 

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#24010]
Tried to create a dataset and chart.

![Screenshot 2023-05-23 at 10 59 39 AM](https://github.com/StarRocks/starrocks/assets/749093/8bfbe7f1-c0c6-4cbe-bee5-47f1bb5f65b6)

```
superset_app          | 2023-05-23 17:59:34,806:ERROR:flask_appbuilder.api:__enter__
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 127, in wraps
superset_app          |     raise ex
superset_app          |   File "/app/superset/views/base_api.py", line 121, in wraps
superset_app          |     duration, response = time_function(f, self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1596, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/app/superset/utils/log.py", line 266, in wrapper
superset_app          |     value = f(*args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 93, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/datasets/api.py", line 307, in post
superset_app          |     new_model = CreateDatasetCommand(item).run()
superset_app          |   File "/app/superset/datasets/commands/create.py", line 49, in run
superset_app          |     dataset.fetch_metadata(commit=False)
superset_app          |   File "/app/superset/connectors/sqla/models.py", line 1265, in fetch_metadata
superset_app          |     new_columns = self.external_metadata()
superset_app          |   File "/app/superset/connectors/sqla/models.py", line 720, in external_metadata
superset_app          |     return get_physical_table_metadata(
superset_app          |   File "/app/superset/connectors/sqla/utils.py", line 71, in get_physical_table_metadata
superset_app          |     database.has_table_by_name(table_name=table_name, schema=_schema_name)
superset_app          |   File "/app/superset/models/core.py", line 925, in has_table_by_name
superset_app          |     return engine.has_table(table_name, schema)
superset_app          |   File "<string>", line 2, in has_table
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 401, in warned
superset_app          |     return fn(*args, **kwargs)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3275, in has_table
superset_app          |     return insp.has_table(table_name, schema=schema)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 283, in has_table
superset_app          |     return self.dialect.has_table(conn, table_name, schema)
superset_app          |   File "<string>", line 2, in has_table
superset_app          |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 47, in cache
superset_app          |     return fn(self, con, *args, **kw)
superset_app          |   File "/usr/local/lib/python3.9/site-packages/starrocks/sqlalchemy/dialect.py", line 58, in has_table
superset_app          |     with connection.exec_driver_sql(
superset_app          | AttributeError: __enter__
superset_app          | 172.18.0.1 - - [23/May/2023:17:59:34 +0000] "POST /api/v1/dataset/ HTTP/1.1" 500 26 "http://localhost:8088/dataset/add/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
superset_app          | 127.0.0.1 - - [23/May/2023:17:59:51 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.74.0"
```

**Comment by alberttwong** [comment]
SQL lab seems to work.

![Screenshot 2023-05-23 at 11 02 56 AM](https://github.com/StarRocks/starrocks/assets/749093/da4af2f0-9270-4f58-afea-bd1464bb7d9a)

**Comment by miomiocat** [comment]
This problem is from starrocks not superset, I will fix it later

**Comment by alberttwong** [comment]
I hate to trouble you but do you have an ETA?   I'm trying to do a webinar of your work with the Apache Superset team

**Comment by miomiocat** [comment]
> I hate to trouble you but do you have an ETA? I'm trying to do a webinar of your work with the Apache Superset team
@alberttwong 
It doesn't matter, feel free to contact me anytime.
I've been busy with other things lately and I plan to fix this issue next week.

**Comment by miomiocat** [comment]
@alberttwong I've fixed it.
you can try it again by reinstall starrocks python client
```
pip uninstall starrocks
pip install starrocks
```

**Comment by alberttwong** [comment]
validated that this works.
