### ISSUE TITLE
The directory have a redundant "/", and can not rename in OSS

### ISSUE THREAD

**Issue by main888** [StarRocks/starrocks#2478]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
1.19.1 65e87c3
 msg:move tmp file to final destination failBroker check path exist exception. path=oss://dev//test_a2ff7f29-678f-11ec-ad4b-00163e301384_0_1_0.csv,

**Comment by imay** [comment]
@wyb PTAL

**Comment by wyb** [comment]
@main888 Please provide the export statement.

**Comment by main888** [comment]
@wyb EXPORT TABLE test.test
TO "oss://dev/test_" 
PROPERTIES
(
    "column_separator"=",",
    "load_mem_limit"="2147483648",
    "timeout" = "3600"
)
WITH BROKER "broker1"
(
"fs.oss.accessKeyId"="xx",
"fs.oss.accessKeySecret"="xx",
"fs.oss.endpoint"="xx"
);

**Comment by wyb** [comment]
Is there any errors in `broker/log/apache_hdfs_broker.log` file?

**Comment by main888** [comment]
@wyb Fail to open oss:///__starrocks_export_tmp_7b65dcc7-678f-11ec-ad4b-00163e301384//dev7b65dcc7-678f-11ec-ad4b-00163e301384_0_4_0.csv.1640662654047: Rpc error: Internal error processing openWriter

**Comment by main888** [comment]
@wyb [ pool-2-thread-5:407130509 ] - [ ERROR ]  Internal error processing checkPathExist
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem.pathToKey(AliyunOSSFileSystem.java:394)
	at org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem.getFileStatus(AliyunOSSFileSystem.java:258)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1632)
	at com.starrocks.broker.hdfs.FileSystemManager.checkPathExist(FileSystemManager.java:640)
	at com.starrocks.broker.hdfs.HDFSBrokerServiceImpl.checkPathExist(HDFSBrokerServiceImpl.java:127)
	at com.starrocks.thrift.TFileBrokerService$Processor$checkPathExist.getResult(TFileBrokerService.java:890)
	at com.starrocks.thrift.TFileBrokerService$Processor$checkPathExist.getResult(TFileBrokerService.java:870)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wyb** [comment]
@main888 
Create a subdirectory under dev, and try `EXPORT TABLE test.test TO "oss://dev/subdir/test_"`

**Comment by wyb** [comment]
I have reproduced it and will fix it later.

**Comment by main888** [comment]
@wyb 我应该怎么修改才能正常使用
