### ISSUE TITLE
Revoke privilege failure for some tables

### ISSUE THREAD

**Issue by zou-xuan** [StarRocks/starrocks#25100]
### Steps to reproduce the behavior (Required)
In the latest branch 3.0, some user has the privilege to a external table, as shown in `grants_to_users`,
```
'gda'@'%'              | default_catalog | development     | external_test1                        | TABLE       | SELECT                    | NO
```
however when I call revoke privilege, it shows failure
```
mysql> REVOKE SELECT ON TABLE development.external_test1 FROM USER 'gda';
ERROR 1064 (HY000): Unexpected exception: There is no such grant defined on TABLE development.external_test1
```
The stack trace is 
```
2023-06-09 21:07:56,618 WARN (thrift-server-pool-37|51580) [StmtExecutor.handleDdlStmt():1215] DDL statement (REVOKE SELECT ON TABLE development.external_test1 FROM USER 'gda'@'%') process failed.
com.starrocks.common.DdlException: There is no such grant defined on TABLE development.external_test1
        at com.starrocks.privilege.AuthorizationManager.revoke(AuthorizationManager.java:401) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.lambda$visitGrantRevokePrivilegeStatement$28(DDLStmtExecutor.java:478) ~[starrocks-fe.jar:?]
        at com.starrocks.common.ErrorReport.wrapWithRuntimeException(ErrorReport.java:108) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitGrantRevokePrivilegeStatement(DDLStmtExecutor.java:469) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitGrantRevokePrivilegeStatement(DDLStmtExecutor.java:143) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.BaseGrantRevokePrivilegeStmt.accept(BaseGrantRevokePrivilegeStmt.java:161) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor.execute(DDLStmtExecutor.java:129) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1189) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:512) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.proxyExecute(ConnectProcessor.java:674) ~[starrocks-fe.jar:?]
        at com.starrocks.service.FrontendServiceImpl.forward(FrontendServiceImpl.java:1055) ~[starrocks-fe.jar:?]
        at com.starrocks.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:2951) ~[starrocks-fe.jar:?]
        at com.starrocks.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:2931) ~[starrocks-fe.jar:?]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_74]
```

I also tried to revoke privilege from a internal table, it also shows failure
```
 'gda'@'%'              | default_catalog | development     | test_automatic_partition              | TABLE       | SELECT

mysql> REVOKE SELECT ON TABLE development.test_automatic_partition FROM USER 'gda';
ERROR 1064 (HY000): Unexpected exception: There is no such grant defined on TABLE development.test_automatic_partition
```

### Expected behavior (Required)
Revoke existing privilege should pass.

### Real behavior (Required)
It shows no grant defined for the table.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch 3.0, the latest commit hash is `94f8e54fe07eea66fbd4a5b7bed1aaa16f98b898` on May 24th.

**Comment by nshangyiming** [comment]
hi @zou-xuan , i haved tested the bug you mentioned above and i didn't reproduce it, both internal and external tables. The version i am testing is `tag:3.0.2` , commit hash is `c833698`. Could you provide the exact version info like the commit hash you are using and the complete steps to help reproduce this bug?

Below is the detailed reproducing steps i have done,

```
mysql> show frontends;
+----------------------------------+---------------+-------------+----------+-----------+---------+--------+-----------+------+-------+-------------------+---------------------+----------+--------+---------------------+-----------------+
| Name                             | IP            | EditLogPort | HttpPort | QueryPort | RpcPort | Role   | ClusterId | Join | Alive | ReplayedJournalId | LastHeartbeat       | IsHelper | ErrMsg | StartTime           | Version         |
+----------------------------------+---------------+-------------+----------+-----------+---------+--------+-----------+------+-------+-------------------+---------------------+----------+--------+---------------------+-----------------+
| 172.26.92.xxx_9711_1676016705714 | 172.26.92.xxx | 9711        | 8731     | 9731      | 9721    | LEADER | 660017644 | true | true  | 513               | 2023-06-19 15:21:47 | true     |        | 2023-06-19 15:00:03 | UNKNOWN-c833698 |
+----------------------------------+---------------+-------------+----------+-----------+---------+--------+-----------+------+-------+-------------------+---------------------+----------+--------+---------------------+-----------------+
1 row in set (0.00 sec)

mysql> show create table test_table_internal;
+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table               | Create Table
                                      |
+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| test_table_internal | CREATE TABLE `test_table_internal` (
  `id` int(11) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
); |
+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

mysql> select * from starrocks.grants_to_users;
+-----------+-----------------+-----------------+---------------------+-------------+----------------+--------------+
| GRANTEE   | OBJECT_CATALOG  | OBJECT_DATABASE | OBJECT_NAME         | OBJECT_TYPE | PRIVILEGE_TYPE | IS_GRANTABLE |
+-----------+-----------------+-----------------+---------------------+-------------+----------------+--------------+
| 'gda'@'%' | default_catalog | development     | test_table_internal | TABLE       | SELECT         | NO           |
+-----------+-----------------+-----------------+---------------------+-------------+----------------+--------------+
1 row in set (0.02 sec)

mysql> REVOKE SELECT ON TABLE development.test_table_internal FROM USER 'gda';
Query OK, 0 rows affected (0.01 sec)

mysql> select * from starrocks.grants_to_users;
Empty set (0.01 sec)

mysql> show create table test_external_table;
+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table               | Create Table                                                                                                                                                                                                                                                            |
+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| test_external_table | CREATE EXTERNAL TABLE `test_external_table` (
  `id` int(11) NULL COMMENT ""
) ENGINE=HIVE
COMMENT "PARTITION BY (id)"
PROPERTIES (
"database" = "stephen",
"table" = "lineitem_test",
"resource" = "hive0",
"hive.metastore.uris"  =  "thrift://172.26.195.0:9083"
); |
+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select * from starrocks.grants_to_users;
Empty set (0.01 sec)

mysql> GRANT SELECT ON TABLE development.test_external_table TO USER 'gda';
Query OK, 0 rows affected (0.00 sec)

mysql> select * from starrocks.grants_to_users;
+-----------+-----------------+-----------------+---------------------+-------------+----------------+--------------+
| GRANTEE   | OBJECT_CATALOG  | OBJECT_DATABASE | OBJECT_NAME         | OBJECT_TYPE | PRIVILEGE_TYPE | IS_GRANTABLE |
+-----------+-----------------+-----------------+---------------------+-------------+----------------+--------------+
| 'gda'@'%' | default_catalog | development     | test_external_table | TABLE       | SELECT         | NO           |
+-----------+-----------------+-----------------+---------------------+-------------+----------------+--------------+
1 row in set (0.01 sec)

mysql> REVOKE SELECT ON TABLE development.test_external_table FROM USER 'gda';
Query OK, 0 rows affected (0.01 sec)

mysql> select * from starrocks.grants_to_users;
Empty set (0.01 sec)

```
