### ISSUE TITLE
Connection timed out: connect

### ISSUE THREAD

**Issue by lx-jialin** [StarRocks/starrocks#25922]
[debezium-engine] INFO io.debezium.connector.common.BaseSourceTask - 174 records sent during previous 00:00:10.5, last recorded offset: {transaction_id=null, event_serial_no=2, commit_lsn=00005bd6:000264e0:0077, change_lsn=00005bd6:000264e0:0068}
Exception in thread "Thread-7" java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to 192.168.0.39:8040 [/192.168.0.39] failed: Connection timed out: connect
	at icc.sqlserver.cdc.test.functions.HttpSinkStarRocksFunction$HttpSinkRunnable.lambda$run$1(HttpSinkStarRocksFunction.java:76)
	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
	at icc.sqlserver.cdc.test.functions.HttpSinkStarRocksFunction$HttpSinkRunnable.run(HttpSinkStarRocksFunction.java:66)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 192.168.0.39:8040 [/192.168.0.39] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at icc.sqlserver.cdc.test.functions.StarRocksStreamLoad.sendData(StarRocksStreamLoad.java:134)
	at icc.sqlserver.cdc.test.functions.HttpSinkStarRocksFunction$HttpSinkRunnable.lambda$run$1(HttpSinkStarRocksFunction.java:71)
	... 3 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 14 more
[debezium-engine] INFO io.debezium.connector.common.BaseSourceTask - 212 records sent during previous 00:00:21.011, last recorded offset: {transaction_id=null, event_serial_no=2, commit_lsn=00005bd6:00027b48:0007, 

http 请求外网ip 被转为内网ip

192.168.0.39 是内网ip

**Comment by baiyi-os** [comment]
最后咋解决的呀
