### ISSUE TITLE
query stucks due to deadlock issue if memory allocate failed when load zone map index

### ISSUE THREAD

**Issue by silverbullet233** [StarRocks/starrocks#26501]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

stack trace when memory allocate failed:
```
W0704 19:01:07.437384 91372 stack_util.cpp:350] 2023-07-04 19:01:07.437365, query_id=137fb810-1a5a-11ee-966c-daaa37d1a479, fragment_instance_id=137fb810-1a5a-11ee-966c-daaa37d1a47a throws exception: std::bad_alloc, trace:
     @          0x24cc122  _Znwm.cold
    @          0x2a085c7  std::vector<>::reserve()
    @          0x4534174  starrocks::ColumnReader::zone_map_filter()
    @          0x457641f  starrocks::ScalarColumnIterator::get_row_ranges_by_zone_map()
    @          0x4107604  starrocks::SegmentIterator::_get_row_ranges_by_zone_map()
    @          0x4108444  starrocks::SegmentIterator::_init()
    @          0x4108810  starrocks::SegmentIterator::do_get_next()
    @          0x4192e25  starrocks::ProjectionIterator::do_get_next()
    @          0x47b28b5  starrocks::SegmentIteratorWrapper::do_get_next()
    @          0x45cbbdb  starrocks::TimedChunkIterator::do_get_next()
    @          0x41c6766  starrocks::TabletReader::do_get_next()
    @          0x2ca4a48  starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage()
    @          0x2ca512e  starrocks::pipeline::OlapChunkSource::_read_chunk()
    @          0x29ff1e1  starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking()
    @          0x2757cf0  _ZZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS_12RuntimeStateEiENKUlvE_clEv
    @          0x27617ae  starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x49db9b7  starrocks::ThreadPool::dispatch_thread()
    @          0x49d6240  starrocks::Thread::supervise_thread()
    @     0x7fef2550dea5  start_thread
    @     0x7fef25236b0d  __clone
    @              (nil)  (unknown)
```

use pstack to dump stack trace when query stucks, we can see the following stack:

```
Thread 1355 (Thread 0x7fec72b2b700 (LWP 91373) "pip_wg_scan_io"):
#0  0x00007fef25230e29 in syscall () from /lib64/libc.so.6
#1  0x00000000045b7a3e in bthread::futex_wait_private (timeout=0x0, expected=1, addr1=0x7feb9f291080) at /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/thirdparty-docker-latest/installed/include/bthread/sys_futex.h:40
#2  starrocks::success_once<starrocks::ZoneMapIndexReader::load(const starrocks::IndexReadOptions&, const starrocks::ZoneMapIndexPB&)::<lambda()> > (f=..., once=...) at ../src/util/once.h:93
#3  starrocks::ZoneMapIndexReader::load (this=0x7feb9f291080, opts=..., meta=...) at ../src/storage/rowset/zone_map_index.cpp:275
#4  0x0000000004533f12 in starrocks::ColumnReader::_load_zonemap_index (this=0x7feefe9cd380, skip_fill_local_cache=<optimized out>) at /usr/local/include/c++/12.2.0/bits/unique_ptr.h:191
#5  0x000000000453405b in starrocks::ColumnReader::zone_map_filter (this=0x7feefe9cd380, predicates=..., del_predicate=0x0, del_partial_filtered_pages=0x7feb96ea8d00, row_ranges=0x7fec72b243a0, skip_fill_local_cache=<optimized out>) at ../src/storage/rowset/column_reader.cpp:439
#6  0x000000000457641f in starrocks::ScalarColumnIterator::get_row_ranges_by_zone_map (this=<optimized out>, predicates=..., del_predicate=<optimized out>, row_ranges=<optimized out>) at ../src/storage/rowset/scalar_column_iterator.cpp:304
#7  0x0000000004107604 in starrocks::SegmentIterator::_get_row_ranges_by_zone_map (this=0x7fea06860610) at ../src/storage/rowset/segment_iterator.cpp:701
#8  0x0000000004108444 in starrocks::SegmentIterator::_init (this=0x7fea06860610) at ../src/storage/rowset/segment_iterator.cpp:396
#9  0x0000000004108810 in starrocks::SegmentIterator::do_get_next (this=0x7fea06860610, chunk=0x7feaecdfc700) at ../src/storage/rowset/segment_iterator.cpp:892
#10 0x0000000004192e25 in starrocks::ChunkIterator::get_next (chunk=<optimized out>, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#11 starrocks::ProjectionIterator::do_get_next (this=0x7fead4fac010, chunk=0x7feaecdfc600) at ../src/storage/projection_iterator.cpp:81
#12 0x00000000047b28b5 in starrocks::ChunkIterator::get_next (chunk=<optimized out>, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#13 starrocks::SegmentIteratorWrapper::do_get_next (this=<optimized out>, chunk=<optimized out>) at ../src/storage/rowset/rowset.cpp:457
#14 0x00000000045cbbdb in starrocks::ChunkIterator::get_next (chunk=0x7feaecdfc600, this=0x7fead4fac190) at ../src/storage/chunk_iterator.h:52
#15 starrocks::TimedChunkIterator::do_get_next (this=<optimized out>, chunk=0x7feaecdfc600) at ../src/storage/chunk_iterator.cpp:49
#16 0x00000000041c6766 in starrocks::ChunkIterator::get_next (chunk=0x7feaecdfc600, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#17 starrocks::TabletReader::do_get_next (this=0x7fe9f8c67010, chunk=0x7feaecdfc600) at ../src/storage/tablet_reader.cpp:227
#18 0x0000000002ca4a48 in starrocks::ChunkIterator::get_next (chunk=0x7feaecdfc600, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#19 starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage (this=0x7fead4faf510, state=<optimized out>, chunk=0x7feaecdfc600) at ../src/exec/pipeline/scan/olap_chunk_source.cpp:364
#20 0x0000000002ca512e in starrocks::pipeline::OlapChunkSource::_read_chunk (this=0x7fead4faf510, state=<optimized out>, chunk=0x7fec72b249f0) at /usr/local/include/c++/12.2.0/bits/shared_ptr_base.h:1665
#21 0x00000000029ff1e1 in starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking (this=0x7fead4faf510, state=<optimized out>, batch_size=batch_size@entry=64, running_wg=<optimized out>) at ../src/exec/pipeline/scan/chunk_source.cpp:66
#22 0x0000000002757cf0 in operator() (__closure=0x7fea03ddb900) at ../src/exec/pipeline/scan/scan_operator.cpp:399
#23 0x00000000027617ae in std::function<void ()>::operator()() const (this=0x7fec72b25040) at /usr/local/include/c++/12.2.0/bits/std_function.h:591
#24 starrocks::workgroup::ScanExecutor::worker_thread (this=0x7fef03783780) at ../src/exec/workgroup/scan_executor.cpp:70
#25 0x00000000049db9b7 in std::function<void ()>::operator()() const (this=0x7feef438c998) at /usr/local/include/c++/12.2.0/bits/std_function.h:591
#26 starrocks::FunctionRunnable::run (this=0x7feef438c990) at ../src/util/threadpool.cpp:58
#27 starrocks::ThreadPool::dispatch_thread (this=0x7fef05c528c0) at ../src/util/threadpool.cpp:553
#28 0x00000000049d6240 in std::function<void ()>::operator()() const (this=0x7feef439b018) at /usr/local/include/c++/12.2.0/bits/std_function.h:591
#29 starrocks::Thread::supervise_thread (arg=0x7feef439b000) at ../src/util/thread.cpp:364
#30 0x00007fef2550dea5 in start_thread () from /lib64/libpthread.so.0
#31 0x00007fef25236b0d in clone () from /lib64/libc.so.6
Thread 1354 (Thread 0x7fec7332c700 (LWP 91372) "pip_wg_scan_io"):
#0  0x00007fef25230e29 in syscall () from /lib64/libc.so.6
#1  0x00000000045b7a3e in bthread::futex_wait_private (timeout=0x0, expected=1, addr1=0x7feefe9254e0) at /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/thirdparty-docker-latest/installed/include/bthread/sys_futex.h:40
#2  starrocks::success_once<starrocks::ZoneMapIndexReader::load(const starrocks::IndexReadOptions&, const starrocks::ZoneMapIndexPB&)::<lambda()> > (f=..., once=...) at ../src/util/once.h:93
#3  starrocks::ZoneMapIndexReader::load (this=0x7feefe9254e0, opts=..., meta=...) at ../src/storage/rowset/zone_map_index.cpp:275
#4  0x0000000004533f12 in starrocks::ColumnReader::_load_zonemap_index (this=0x7feefe818f60, skip_fill_local_cache=<optimized out>) at /usr/local/include/c++/12.2.0/bits/unique_ptr.h:191
#5  0x000000000453405b in starrocks::ColumnReader::zone_map_filter (this=0x7feefe818f60, predicates=..., del_predicate=0x0, del_partial_filtered_pages=0x7fead4cdc000, row_ranges=0x7fec733253a0, skip_fill_local_cache=<optimized out>) at ../src/storage/rowset/column_reader.cpp:439
#6  0x000000000457641f in starrocks::ScalarColumnIterator::get_row_ranges_by_zone_map (this=<optimized out>, predicates=..., del_predicate=<optimized out>, row_ranges=<optimized out>) at ../src/storage/rowset/scalar_column_iterator.cpp:304
#7  0x0000000004107604 in starrocks::SegmentIterator::_get_row_ranges_by_zone_map (this=0x7fead4ce9e10) at ../src/storage/rowset/segment_iterator.cpp:701
#8  0x0000000004108444 in starrocks::SegmentIterator::_init (this=0x7fead4ce9e10) at ../src/storage/rowset/segment_iterator.cpp:396
#9  0x0000000004108810 in starrocks::SegmentIterator::do_get_next (this=0x7fead4ce9e10, chunk=0x7feb4dedb000) at ../src/storage/rowset/segment_iterator.cpp:892
#10 0x0000000004192e25 in starrocks::ChunkIterator::get_next (chunk=<optimized out>, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#11 starrocks::ProjectionIterator::do_get_next (this=0x7fead4cdb090, chunk=0x7feb4dd9af00) at ../src/storage/projection_iterator.cpp:81
#12 0x00000000047b28b5 in starrocks::ChunkIterator::get_next (chunk=<optimized out>, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#13 starrocks::SegmentIteratorWrapper::do_get_next (this=<optimized out>, chunk=<optimized out>) at ../src/storage/rowset/rowset.cpp:457
#14 0x00000000045cbbdb in starrocks::ChunkIterator::get_next (chunk=0x7feb4dd9af00, this=0x7fead4cdb210) at ../src/storage/chunk_iterator.h:52
#15 starrocks::TimedChunkIterator::do_get_next (this=<optimized out>, chunk=0x7feb4dd9af00) at ../src/storage/chunk_iterator.cpp:49
#16 0x00000000041c6766 in starrocks::ChunkIterator::get_next (chunk=0x7feb4dd9af00, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#17 starrocks::TabletReader::do_get_next (this=0x7fea0356cc10, chunk=0x7feb4dd9af00) at ../src/storage/tablet_reader.cpp:227
#18 0x0000000002ca4a48 in starrocks::ChunkIterator::get_next (chunk=0x7feb4dd9af00, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#19 starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage (this=0x7fead4ed3e10, state=<optimized out>, chunk=0x7feb4dd9af00) at ../src/exec/pipeline/scan/olap_chunk_source.cpp:364
#20 0x0000000002ca512e in starrocks::pipeline::OlapChunkSource::_read_chunk (this=0x7fead4ed3e10, state=<optimized out>, chunk=0x7fec733259f0) at /usr/local/include/c++/12.2.0/bits/shared_ptr_base.h:1665
#21 0x00000000029ff1e1 in starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking (this=0x7fead4ed3e10, state=<optimized out>, batch_size=batch_size@entry=64, running_wg=<optimized out>) at ../src/exec/pipeline/scan/chunk_source.cpp:66
#22 0x0000000002757cf0 in operator() (__closure=0x7fea000b6560) at ../src/exec/pipeline/scan/scan_operator.cpp:399
#23 0x00000000027617ae in std::function<void ()>::operator()() const (this=0x7fec73326040) at /usr/local/include/c++/12.2.0/bits/std_function.h:591
#24 starrocks::workgroup::ScanExecutor::worker_thread (this=0x7fef03783780) at ../src/exec/workgroup/scan_executor.cpp:70
#25 0x00000000049db9b7 in std::function<void ()>::operator()() const (this=0x7feef438c958) at /usr/local/include/c++/12.2.0/bits/std_function.h:591
#26 starrocks::FunctionRunnable::run (this=0x7feef438c950) at ../src/util/threadpool.cpp:58
#27 starrocks::ThreadPool::dispatch_thread (this=0x7fef05c528c0) at ../src/util/threadpool.cpp:553
#28 0x00000000049d6240 in std::function<void ()>::operator()() const (this=0x7feef4395f18) at /usr/local/include/c++/12.2.0/bits/std_function.h:591
#29 starrocks::Thread::supervise_thread (arg=0x7feef4395f00) at ../src/util/thread.cpp:364
#30 0x00007fef2550dea5 in start_thread () from /lib64/libpthread.so.0
#31 0x00007fef25236b0d in clone () from /lib64/libc.so.6
Thread 1353 (Thread 0x7fec73b2d700 (LWP 91371) "pip_wg_scan_io"):
#0  0x00007fef25230e29 in syscall () from /lib64/libc.so.6
#1  0x00000000045b7a3e in bthread::futex_wait_private (timeout=0x0, expected=1, addr1=0x7feb9f477fa0) at /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/thirdparty-docker-latest/installed/include/bthread/sys_futex.h:40
#2  starrocks::success_once<starrocks::ZoneMapIndexReader::load(const starrocks::IndexReadOptions&, const starrocks::ZoneMapIndexPB&)::<lambda()> > (f=..., once=...) at ../src/util/once.h:93
#3  starrocks::ZoneMapIndexReader::load (this=0x7feb9f477fa0, opts=..., meta=...) at ../src/storage/rowset/zone_map_index.cpp:275
#4  0x0000000004533f12 in starrocks::ColumnReader::_load_zonemap_index (this=0x7feb9f43d740, skip_fill_local_cache=<optimized out>) at /usr/local/include/c++/12.2.0/bits/unique_ptr.h:191
#5  0x000000000453405b in starrocks::ColumnReader::zone_map_filter (this=0x7feb9f43d740, predicates=..., del_predicate=0x0, del_partial_filtered_pages=0x7feb83131080, row_ranges=0x7fec73b263a0, skip_fill_local_cache=<optimized out>) at ../src/storage/rowset/column_reader.cpp:439
#6  0x000000000457641f in starrocks::ScalarColumnIterator::get_row_ranges_by_zone_map (this=<optimized out>, predicates=..., del_predicate=<optimized out>, row_ranges=<optimized out>) at ../src/storage/rowset/scalar_column_iterator.cpp:304
#7  0x0000000004107604 in starrocks::SegmentIterator::_get_row_ranges_by_zone_map (this=0x7feb80f2f410) at ../src/storage/rowset/segment_iterator.cpp:701
#8  0x0000000004108444 in starrocks::SegmentIterator::_init (this=0x7feb80f2f410) at ../src/storage/rowset/segment_iterator.cpp:396
#9  0x0000000004108810 in starrocks::SegmentIterator::do_get_next (this=0x7feb80f2f410, chunk=0x7fef05acf900) at ../src/storage/rowset/segment_iterator.cpp:892
#10 0x0000000004192e25 in starrocks::ChunkIterator::get_next (chunk=<optimized out>, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#11 starrocks::ProjectionIterator::do_get_next (this=0x7feb80ef3d10, chunk=0x7fef05acf800) at ../src/storage/projection_iterator.cpp:81
#12 0x00000000047b28b5 in starrocks::ChunkIterator::get_next (chunk=<optimized out>, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#13 starrocks::SegmentIteratorWrapper::do_get_next (this=<optimized out>, chunk=<optimized out>) at ../src/storage/rowset/rowset.cpp:457
#14 0x00000000045cbbdb in starrocks::ChunkIterator::get_next (chunk=0x7fef05acf800, this=0x7feb80ef3e90) at ../src/storage/chunk_iterator.h:52
#15 starrocks::TimedChunkIterator::do_get_next (this=<optimized out>, chunk=0x7fef05acf800) at ../src/storage/chunk_iterator.cpp:49
#16 0x00000000041c6766 in starrocks::ChunkIterator::get_next (chunk=0x7fef05acf800, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#17 starrocks::TabletReader::do_get_next (this=0x7feb80f40410, chunk=0x7fef05acf800) at ../src/storage/tablet_reader.cpp:227
#18 0x0000000002ca4a48 in starrocks::ChunkIterator::get_next (chunk=0x7fef05acf800, this=<optimized out>) at ../src/storage/chunk_iterator.h:52
#19 starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage (this=0x7feb80f1d910, state=<optimized out>, chunk=0x7fef05acf800) at ../src/exec/pipeline/scan/olap_chunk_source.cpp:364
#20 0x0000000002ca512e in starrocks::pipeline::OlapChunkSource::_read_chunk (this=0x7feb80f1d910, state=<optimized out>, chunk=0x7fec73b269f0) at /usr/local/include/c++/12.2.0/bits/shared_ptr_base.h:1665
#21 0x00000000029ff1e1 in starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking (this=0x7feb80f1d910, state=<optimized out>, batch_size=batch_size@entry=64, running_wg=<optimized out>) at ../src/exec/pipeline/scan/chunk_source.cpp:66
#22 0x0000000002757cf0 in operator() (__closure=0x7feb80ec42a0) at ../src/exec/pipeline/scan/scan_operator.cpp:399
#23 0x00000000027617ae in std::function<void ()>::operator()() const (this=0x7fec73b27040) at /usr/local/include/c++/12.2.0/bits/std_function.h:591
#24 starrocks::workgroup::ScanExecutor::worker_thread (this=0x7fef03783780) at ../src/exec/workgroup/scan_executor.cpp:70
#25 0x00000000049db9b7 in std::function<void ()>::operator()() const (this=0x7feef438c918) at /usr/local/include/c++/12.2.0/bits/std_function.h:591
#26 starrocks::FunctionRunnable::run (this=0x7feef438c910) at ../src/util/threadpool.cpp:58
#27 starrocks::ThreadPool::dispatch_thread (this=0x7fef05c528c0) at ../src/util/threadpool.cpp:553
#28 0x00000000049d6240 in std::function<void ()>::operator()() const (this=0x7feef4395e18) at /usr/local/include/c++/12.2.0/bits/std_function.h:591
#29 starrocks::Thread::supervise_thread (arg=0x7feef4395e00) at ../src/util/thread.cpp:364
#30 0x00007fef2550dea5 in start_thread () from /lib64/libpthread.so.0
#31 0x00007fef25236b0d in clone () from /lib64/libc.so.6
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by silverbullet233** [comment]
not a bug
