### ISSUE TITLE
issue with starrocks/destination-starrocks:latest. get spec job failed

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#26686]
In the logs there is this error.
```
airbyte-worker                    | io.airbyte.workers.exception.WorkerException: Error while getting spec from image starrocks/destination-starrocks:latest
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:83) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-worker                    | Caused by: io.airbyte.workers.exception.WorkerException: Could not find image: starrocks/destination-starrocks:latest
airbyte-worker                    | 	at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:117) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:89) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:55) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	... 3 more
airbyte-worker                    | 2023-07-07 01:53:41 INFO i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
airbyte-worker                    | 2023-07-07 01:53:41 WARN i.t.i.a.ActivityTaskExecutors$BaseActivityTaskExecutor(execute):114 - Activity failure. ActivityId=ef3ed87d-2206-32af-ab02-968302298272, activityType=Run, attempt=1
airbyte-worker                    | java.util.concurrent.ExecutionException: io.airbyte.workers.exception.WorkerException: Error while getting spec from image starrocks/destination-starrocks:latest
airbyte-worker                    | 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
airbyte-worker                    | 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:161) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.spec.SpecActivityImpl.run(SpecActivityImpl.java:118) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
airbyte-worker                    | 	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
airbyte-worker                    | 	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-worker                    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-worker                    | 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-worker                    | Caused by: io.airbyte.workers.exception.WorkerException: Error while getting spec from image starrocks/destination-starrocks:latest
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:83) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	... 1 more
airbyte-worker                    | Caused by: io.airbyte.workers.exception.WorkerException: Could not find image: starrocks/destination-starrocks:latest
airbyte-worker                    | 	at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:117) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:89) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:55) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	... 1 more
airbyte-worker                    | 2023-07-07 01:53:41 WARN i.t.i.s.WorkflowExecuteRunnable(throwAndFailWorkflowExecution):134 - Workflow execution failure WorkflowId='e41d515e-4a45-4b44-833d-2a4338de1830', RunId=56d130cd-587b-45b1-a9c7-f184879b87cc, WorkflowType='SpecWorkflow'
airbyte-worker                    | io.temporal.failure.ActivityFailure: scheduledEventId=5, startedEventId=6, activityType='Run', activityId='ef3ed87d-2206-32af-ab02-968302298272', identity='1@75113f9931ac', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
airbyte-worker                    | 	at java.lang.Thread.getStackTrace(Thread.java:2550) ~[?:?]
airbyte-worker                    | 	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:49) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:78) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:60) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at jdk.proxy2.$Proxy86.run(Unknown Source) ~[?:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.spec.SpecWorkflowImpl.run(SpecWorkflowImpl.java:34) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	at SpecWorkflowImplProxy.run$accessor$vJ6rkZoE(Unknown Source) ~[?:?]
airbyte-worker                    | 	at SpecWorkflowImplProxy$auxiliary$AHacKLoi.call(Unknown Source) ~[?:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.support.TemporalActivityStubInterceptor.execute(TemporalActivityStubInterceptor.java:79) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	at SpecWorkflowImplProxy.run(Unknown Source) ~[?:?]
airbyte-worker                    | 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
airbyte-worker                    | 	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
airbyte-worker                    | 	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:302) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:277) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:71) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:116) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:106) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
airbyte-worker                    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-worker                    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-worker                    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-worker                    | 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-worker                    | Caused by: io.temporal.failure.ApplicationFailure: message='io.airbyte.workers.exception.WorkerException: Error while getting spec from image starrocks/destination-starrocks:latest', type='java.util.concurrent.ExecutionException', nonRetryable=false
airbyte-worker                    | 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
airbyte-worker                    | 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:161) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.spec.SpecActivityImpl.run(SpecActivityImpl.java:118) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
airbyte-worker                    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
airbyte-worker                    | 	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:92) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:241) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:206) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:179) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.17.0.jar:?]
airbyte-worker                    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-worker                    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-worker                    | 	at java.base/java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-worker                    | Caused by: io.temporal.failure.ApplicationFailure: message='Error while getting spec from image starrocks/destination-starrocks:latest', type='io.airbyte.workers.exception.WorkerException', nonRetryable=false
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:83) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	at java.base/java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-worker                    | Caused by: io.temporal.failure.ApplicationFailure: message='Could not find image: starrocks/destination-starrocks:latest', type='io.airbyte.workers.exception.WorkerException', nonRetryable=false
airbyte-worker                    | 	at io.airbyte.workers.process.DockerProcessFactory.create(DockerProcessFactory.java:117) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.process.AirbyteIntegrationLauncher.spec(AirbyteIntegrationLauncher.java:89) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:55) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.general.DefaultGetSpecWorker.run(DefaultGetSpecWorker.java:36) ~[io.airbyte-airbyte-commons-worker-0.44.5.jar:?]
airbyte-worker                    | 	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.5.jar:?]
airbyte-worker                    | 	at java.base/java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-server                    | 2023-07-07 01:53:41 ERROR i.a.s.a.ApiHelper(execute):40 - Unexpected Exception
airbyte-server                    | java.lang.IllegalStateException: Get Spec job failed.
airbyte-server                    | 	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.1-jre.jar:?]
airbyte-server                    | 	at io.airbyte.commons.server.converters.SpecFetcher.getSpecFromJob(SpecFetcher.java:18) ~[io.airbyte-airbyte-commons-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.commons.server.handlers.DestinationDefinitionsHandler.getSpecForImage(DestinationDefinitionsHandler.java:305) ~[io.airbyte-airbyte-commons-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.commons.server.handlers.DestinationDefinitionsHandler.destinationDefinitionFromCreate(DestinationDefinitionsHandler.java:215) ~[io.airbyte-airbyte-commons-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.commons.server.handlers.DestinationDefinitionsHandler.createCustomDestinationDefinition(DestinationDefinitionsHandler.java:201) ~[io.airbyte-airbyte-commons-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.server.apis.DestinationDefinitionApiController.lambda$createCustomDestinationDefinition$0(DestinationDefinitionApiController.java:52) ~[io.airbyte-airbyte-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26) ~[io.airbyte-airbyte-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.server.apis.DestinationDefinitionApiController.createCustomDestinationDefinition(DestinationDefinitionApiController.java:52) ~[io.airbyte-airbyte-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.server.apis.$DestinationDefinitionApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.44.5.jar:?]
airbyte-server                    | 	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.9.1.jar:3.9.1]
airbyte-server                    | 	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.9.1.jar:3.9.1]
airbyte-server                    | 	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) ~[micronaut-router-3.9.1.jar:3.9.1]
airbyte-server                    | 	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.9.1.jar:3.9.1]
airbyte-server                    | 	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.9.1.jar:3.9.1]
airbyte-server                    | 	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.9.1.jar:3.9.1]
airbyte-server                    | 	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-server                    | 	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-server                    | 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-server                    | 	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.9.1.jar:3.9.1]
airbyte-server                    | 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-server                    | 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-server                    | 	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) ~[micronaut-context-3.9.1.jar:3.9.1]
airbyte-server                    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-server                    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-server                    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-server                    | 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-server                    | 2023-07-07 01:53:42 ERROR i.a.s.e.UncaughtExceptionHandler(handle):31 - Uncaught exception
airbyte-server                    | java.lang.IllegalStateException: Get Spec job failed.
airbyte-server                    | 	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.1-jre.jar:?]
airbyte-server                    | 	at io.airbyte.commons.server.converters.SpecFetcher.getSpecFromJob(SpecFetcher.java:18) ~[io.airbyte-airbyte-commons-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.commons.server.handlers.DestinationDefinitionsHandler.getSpecForImage(DestinationDefinitionsHandler.java:305) ~[io.airbyte-airbyte-commons-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.commons.server.handlers.DestinationDefinitionsHandler.destinationDefinitionFromCreate(DestinationDefinitionsHandler.java:215) ~[io.airbyte-airbyte-commons-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.commons.server.handlers.DestinationDefinitionsHandler.createCustomDestinationDefinition(DestinationDefinitionsHandler.java:201) ~[io.airbyte-airbyte-commons-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.server.apis.DestinationDefinitionApiController.lambda$createCustomDestinationDefinition$0(DestinationDefinitionApiController.java:52) ~[io.airbyte-airbyte-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26) ~[io.airbyte-airbyte-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.server.apis.DestinationDefinitionApiController.createCustomDestinationDefinition(DestinationDefinitionApiController.java:52) ~[io.airbyte-airbyte-server-0.44.5.jar:?]
airbyte-server                    | 	at io.airbyte.server.apis.$DestinationDefinitionApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.44.5.jar:?]
airbyte-server                    | 	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.9.1.jar:3.9.1]
airbyte-server                    | 	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.9.1.jar:3.9.1]
airbyte-server                    | 	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) ~[micronaut-router-3.9.1.jar:3.9.1]
airbyte-server                    | 	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.9.1.jar:3.9.1]
airbyte-server                    | 	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.9.1.jar:3.9.1]
airbyte-server                    | 	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.9.1.jar:3.9.1]
airbyte-server                    | 	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-server                    | 	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-server                    | 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-server                    | 	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.9.1.jar:3.9.1]
airbyte-server                    | 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-server                    | 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-server                    | 	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) ~[micronaut-context-3.9.1.jar:3.9.1]
airbyte-server                    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-server                    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-server                    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-server                    | 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

Even when you delete the airbyte PVs.... you still get this issue.

The fix was to use another docker build.   atwong/destination-starrocks:latest

**Comment by alberttwong** [comment]
asking the starrocks/destination-starrocks to be replaced.

**Comment by alberttwong** [comment]
replaced.  Thanks @kevincai

**Comment by alberttwong** [comment]
here's the weird thing. I just tried to use the new deployment at starrocks/destination-starrocks and it still gives the same error.

I had to force airbye to download the container
```
docker exec -it airbyte-worker `/bin/bash`
docker pull starrocks/destination-starrocks --platform=linux/amd64
```
what I don't understand is why atwong/destination-starrocks:latest works

**Comment by kevincai** [comment]
is there cached image in the local docker engine? it is usually a side-effect of using `latest` tag.

**Comment by alberttwong** [comment]
My airbyte instance wouldn't download `starrocks/destination-starrocks` for Apple arm.  I think it expects an OS specific image.  So I think the answer is that Airbyte compile has to support multiple OS builds.  https://github.com/airbytehq/airbyte/issues/27888.  I got around this issue by forcing the airbyte-worker to use the amd64 image by doing a docker pull on  `--platform=linux/amd64`.

**Comment by kevincai** [comment]
that means `starrocks/destination-starrocks` doesn't provide arm platform. we may need to provide a multi-arch image for it.

**Comment by alberttwong** [comment]
Yes.... I have a issue ticket with airbyte asking how to do.
