### ISSUE TITLE
Routine Load Job null pointer exception results in hung job

### ISSUE THREAD

**Issue by Jmoore1127** [StarRocks/starrocks#27085]
Creating a routine load job from kafka with "calculated" column results in FE NullPointerException and hung job.

### Steps to reproduce the behavior (Required)
1.Create destination table
```
CREATE TABLE appointments (
    id VARCHAR(36), 
    person_id VARCHAR(36),
    location_id VARCHAR(36),
    appt_date DATE,
    appt_time VARCHAR(8),
    appointment_dt DATETIME
)
DISTRIBUTED BY HASH(location_id)
PROPERTIES (
    "replication_num"="1"
);
```

2. Create Routine Load from Kafka with "computed" column
```
CREATE ROUTINE LOAD appointments_load ON appointments 
COLUMNS(id, location_id, person_id, appt_date, appt_time, appointment_dt=str_to_date(appt_date || ' ' || appt_time))
PROPERTIES
(
    "format" = "json"
    , "jsonpaths" = "[\"$.id\", \"$.location_id\", \"$.person_id\", \"$.appointment_date\", \"$.appointment_time\"]"
)
FROM KAFKA
(
    "kafka_broker_list" ="kafka-broker-url:9092",
    "kafka_topic" = "appointments",
    "property.kafka_default_offsets" = "OFFSET_BEGINNING"
);
```
3. SHOW ROUTINE LOAD TASK WHERE JobName = 'appointments_load';
```
2de1b22a-b071-4495-b2fc-047f16f3541d	41	UNKNOWN	10117	2023-07-12 22:42:31	2023-07-12 22:42:41	NULL	60	10004	Progress:{"0":0},LatestOffset:{"0":98380}	previous task aborted because of timeout by txn manager
```
4. Search `fe/log/fe.warn.log`
```
2023-07-12 22:36:51,170 WARN (pool-17-thread-10|1283) [RoutineLoadTaskScheduler.lambda$submitToSchedule$1():167] schedule routine load task failed
java.lang.NullPointerException: null
	at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitCompoundPredicate(ExpressionAnalyzer.java:573) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitCompoundPredicate(ExpressionAnalyzer.java:329) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.CompoundPredicate.accept(CompoundPredicate.java:154) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:326) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:323) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:323) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeIgnoreSlot(ExpressionAnalyzer.java:122) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeExpressionIgnoreSlot(ExpressionAnalyzer.java:1605) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.Expr.analyzeAndCastFold(Expr.java:1428) ~[starrocks-fe.jar:?]
	at com.starrocks.load.Load.analyzeMappingExprs(Load.java:780) ~[starrocks-fe.jar:?]
	at com.starrocks.load.Load.initColumns(Load.java:640) ~[starrocks-fe.jar:?]
	at com.starrocks.planner.StreamLoadScanNode.initColumns(StreamLoadScanNode.java:234) ~[starrocks-fe.jar:?]
	at com.starrocks.planner.StreamLoadScanNode.initParams(StreamLoadScanNode.java:228) ~[starrocks-fe.jar:?]
	at com.starrocks.planner.StreamLoadScanNode.init(StreamLoadScanNode.java:186) ~[starrocks-fe.jar:?]
	at com.starrocks.planner.StreamLoadPlanner.plan(StreamLoadPlanner.java:181) ~[starrocks-fe.jar:?]
	at com.starrocks.load.routineload.RoutineLoadJob.plan(RoutineLoadJob.java:827) ~[starrocks-fe.jar:?]
	at com.starrocks.load.routineload.KafkaTaskInfo.plan(KafkaTaskInfo.java:212) ~[starrocks-fe.jar:?]
	at com.starrocks.load.routineload.KafkaTaskInfo.createRoutineLoadTask(KafkaTaskInfo.java:176) ~[starrocks-fe.jar:?]
	at com.starrocks.load.routineload.RoutineLoadTaskScheduler.scheduleOneTask(RoutineLoadTaskScheduler.java:240) ~[starrocks-fe.jar:?]
	at com.starrocks.load.routineload.RoutineLoadTaskScheduler.lambda$submitToSchedule$1(RoutineLoadTaskScheduler.java:165) ~[starrocks-fe.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]

```

### Expected behavior (Required)
Job should error if invalid or succeed if valid
### Real behavior (Required)
Job hangs indefinitely

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`3.1.0-rc01-64ca37e863`

**Comment by Jmoore1127** [comment]
Kafka messages look like this (fake data):
```
{
	"id": "3bbffeec-50a6-4c3f-8062-8d5662f02fdd",
	"person_id": "fce7a9a7-47f9-4fd1-b206-6dde1894df0b",
	"location_id": "d9032c6c-a81d-4428-8411-bafea349fa7f",
	"appointment_date": "2024-07-09",
	"appointment_time": "20:30:00"
}
```

**Comment by imay** [comment]
`appt_date || ' ' || appt_time` is not treated as a concat function in starrocks default sqlMode. You can use `concat(appt_date, ' ', appt_time)` instead.
But that is still an issue for us, we will fix it ASAP

**Comment by Jmoore1127** [comment]
Yes, I tested with `concat(appt_date, ' ', appt_time)` as well but the NullPointerException still occurs.

**Comment by kangkaisen** [comment]
@Jmoore1127 Hi, I'm fixing this bug, could you send the exception stack of `concat(appt_date, ' ', appt_time)` to me, I want to double check something, thanks.

**Comment by Jmoore1127** [comment]
```
2023-07-13 22:06:55,538 WARN (pool-17-thread-1|221) [RoutineLoadTaskScheduler.lambda$submitToSchedule$1():167] schedule routine load task failed
java.lang.NullPointerException: null
	at com.starrocks.sql.analyzer.AnalyzerUtils.getDBUdfFunction(AnalyzerUtils.java:171) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.AnalyzerUtils.getUdfFunction(AnalyzerUtils.java:211) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1063) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:329) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.FunctionCallExpr.accept(FunctionCallExpr.java:487) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:326) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeIgnoreSlot(ExpressionAnalyzer.java:122) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeExpressionIgnoreSlot(ExpressionAnalyzer.java:1605) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.Expr.analyzeAndCastFold(Expr.java:1428) ~[starrocks-fe.jar:?]
	at com.starrocks.load.Load.analyzeMappingExprs(Load.java:780) ~[starrocks-fe.jar:?]
	at com.starrocks.load.Load.initColumns(Load.java:640) ~[starrocks-fe.jar:?]
	at com.starrocks.planner.StreamLoadScanNode.initColumns(StreamLoadScanNode.java:234) ~[starrocks-fe.jar:?]
	at com.starrocks.planner.StreamLoadScanNode.initParams(StreamLoadScanNode.java:228) ~[starrocks-fe.jar:?]
	at com.starrocks.planner.StreamLoadScanNode.init(StreamLoadScanNode.java:186) ~[starrocks-fe.jar:?]
	at com.starrocks.planner.StreamLoadPlanner.plan(StreamLoadPlanner.java:181) ~[starrocks-fe.jar:?]
	at com.starrocks.load.routineload.RoutineLoadJob.plan(RoutineLoadJob.java:827) ~[starrocks-fe.jar:?]
	at com.starrocks.load.routineload.KafkaTaskInfo.plan(KafkaTaskInfo.java:212) ~[starrocks-fe.jar:?]
	at com.starrocks.load.routineload.KafkaTaskInfo.createRoutineLoadTask(KafkaTaskInfo.java:176) ~[starrocks-fe.jar:?]
	at com.starrocks.load.routineload.RoutineLoadTaskScheduler.scheduleOneTask(RoutineLoadTaskScheduler.java:240) ~[starrocks-fe.jar:?]
	at com.starrocks.load.routineload.RoutineLoadTaskScheduler.lambda$submitToSchedule$1(RoutineLoadTaskScheduler.java:165) ~[starrocks-fe.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by kangkaisen** [comment]
@Jmoore1127  you could try this two ways:
1.
```
appointment_dt=str_to_date(str_to_date(concat(concat(12: cast, ' '), 12: cast), '%Y-%m-%d %H:%i:%s'))
```

2 

```
set global sql_mode="PIPES_AS_CONCAT"

appointment_dt=str_to_date(appt_date || ' ' || appt_time),  '%Y-%m-%d %H:%i:%s'))

```
