### ISSUE TITLE
buffer-overflow in parquet external table

### ISSUE THREAD

**Issue by stdpain** [StarRocks/starrocks#2732]
### Steps to reproduce the behavior (Required)
```
 SELECT   * from   hive_ssb_1t_parquet_customer as ref_0   right join metrics_detail as ref_1 on (ref_0.c_custkey = ref_1.tags_id)   right join metrics_detail as ref_2 on (ref_1.tags_id = ref_2.tags_id)   inner join test_cross_join_30 as ref_3 on (ref_1.tags_id = ref_3.id_int)   inner join mysql_with_null as ref_4 on (ref_3.id_int = ref_4.id_tinyint);
```

### Expected behavior (Required)
```
0 rows return
```
### Real behavior (Required)
```
WRITE of size 4 at 0x621004caa790 thread T217 (fragment_mgr)
    #0 0x83cfbaf in starrocks::DataStreamSender::send_chunk(starrocks::RuntimeState*, starrocks::vectorized::Chunk*) /home/disk1/jenkins/workspace/master_asan/cluster-management/resource/starrocks/be/src/runtime/data_stream_sender.cpp:621
    #1 0x4fd3787 in starrocks::PlanFragmentExecutor::_open_internal_vectorized() /home/disk1/jenkins/workspace/master_asan/cluster-management/resource/starrocks/be/src/runtime/plan_fragment_executor.cpp:240
    #2 0x4fd231c in starrocks::PlanFragmentExecutor::open() /home/disk1/jenkins/workspace/master_asan/cluster-management/resource/starrocks/be/src/runtime/plan_fragment_executor.cpp:192
    #3 0x4e4ed55 in starrocks::FragmentExecState::execute() /home/disk1/jenkins/workspace/master_asan/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:193
    #4 0x4e53e1e in starrocks::FragmentMgr::exec_actual(std::shared_ptr<starrocks::FragmentExecState>*, std::function<void (starrocks::PlanFragmentExecutor*)> const&) /home/disk1/jenkins/workspace/master_asan/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:379
    #5 0x4e5483a in operator() /home/disk1/jenkins/workspace/master_asan/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:438
    #6 0x4e5d865 in __invoke_impl<void, starrocks::FragmentMgr::exec_plan_fragment(const starrocks::TExecPlanFragmentParams&, const StartSuccCallback&, const FinishCallback&)::<lambda()>&> /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #7 0x4e5d456 in __invoke_r<void, starrocks::FragmentMgr::exec_plan_fragment(const starrocks::TExecPlanFragmentParams&, const StartSuccCallback&, const FinishCallback&)::<lambda()>&> /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:110
    #8 0x4e5cc07 in _M_invoke /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:291
    #9 0x3d5a543 in std::function<void ()>::operator()() const /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
    #10 0x524635f in starrocks::FunctionRunnable::run() /home/disk1/jenkins/workspace/master_asan/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:45
    #11 0x5242e3d in starrocks::ThreadPool::dispatch_thread() /home/disk1/jenkins/workspace/master_asan/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:514
    #12 0x5260487 in void std::__invoke_impl<void, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(std::__invoke_memfun_deref, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:73
    #13 0x525fd6a in std::__invoke_result<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>::type std::__invoke<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:95
    #14 0x525f181 in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:416
    #15 0x525dced in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::operator()<, void>() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:499
    #16 0x525abd3 in void std::__invoke_impl<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #17 0x5258b9b in std::enable_if<is_invocable_r_v<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:110
    #18 0x5254336 in std::_Function_handler<void (), std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:291
    #19 0x3d5a543 in std::function<void ()>::operator()() const /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
    #20 0x522d53c in starrocks::Thread::supervise_thread(void*) /home/disk1/jenkins/workspace/master_asan/cluster-management/resource/starrocks/be/src/util/thread.cpp:312
    #21 0x7f3058a0aea4 in start_thread (/lib64/libpthread.so.0+0x7ea4)
    #22 0x7f3057e0f8dc in __clone (/lib64/libc.so.6+0xfe8dc)
```

### StarRocks version (Required)
 - main-asan

**Comment by stdpain** [comment]
will fixed by #2731
