### ISSUE TITLE
create table error - java.lang.NoClassDefFoundError: org/apache/commons/collections/CollectionUtils

### ISSUE THREAD

**Issue by even986025158** [StarRocks/starrocks#2754]
## General Question

After the source code is compiled and run FE, BE, an error occurs when building the table

SQL:
CREATE TABLE IF NOT EXISTS example_db.aggregate_tbl (
    site_id LARGEINT NOT NULL COMMENT "id of site",
    date DATE NOT NULL COMMENT "time of event",
    city_code VARCHAR(20) COMMENT "city_code of user",
    pv BIGINT SUM DEFAULT "0" COMMENT "total page views"
) DISTRIBUTED BY HASH(site_id) BUCKETS 8

Error msg: 

2022-01-10 21:24:47,348 INFO (starrocks-mysql-nio-pool-0|87) [StmtExecutor.analyze():569] begin to analyze stmt: 8, forwarded stmt id: 0
2022-01-10 21:24:47,349 WARN (starrocks-mysql-nio-pool-0|87) [StmtExecutor.execute():451] execute Exception, sql CREATE TABLE IF NOT EXISTS example_db.aggregate_tbl (
    site_id LARGEINT NOT NULL COMMENT "id of site",
    date DATE NOT NULL COMMENT "time of event",
    city_code VARCHAR(20) COMMENT "city_code of user",
    pv BIGINT SUM DEFAULT "0" COMMENT "total page views"
) DISTRIBUTED BY HASH(site_id) BUCKETS 8
java.lang.NoClassDefFoundError: org/apache/commons/collections/CollectionUtils
	at com.starrocks.analysis.CreateTableStmt.analyze(CreateTableStmt.java:421) ~[classes/:?]
	at com.starrocks.qe.StmtExecutor.analyze(StmtExecutor.java:596) ~[classes/:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:310) ~[classes/:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) ~[classes/:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) ~[classes/:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) ~[classes/:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by stdpain** [comment]
Check that the JDK version used to run FE and the JDK version used to compile FE are the same

**Comment by even986025158** [comment]
caused by dependency conflicts，
Open the pom.xml file of the parent module starrocks-fe, locate the location that depends on hadoop-common, change <scope>provided</scope> to <scope>compile</scope> , refresh

**Comment by even986025158** [comment]
![未命名](https://user-images.githubusercontent.com/39552698/154953131-e7c4dfea-1d50-4c83-ba62-388c6e0d349f.jpg)
