### ISSUE TITLE
Hudi fails to read Merge On Read table after adding logs files

### ISSUE THREAD

**Issue by parisni** [StarRocks/starrocks#27556]
### Steps to reproduce the behavior (Required)
```python
from pyspark.sql.types import StructType, StructField, StringType, IntegerType
data = [
    (1, "f5c2ebfd-f57b-4ff3-ac5c-f30674037b21", "A", "BC", "C"),
    (2, "f5c2ebfd-f57b-4ff3-ac5c-f30674037b22", "A", "BC", "C"),
    (3, "f5c2ebfd-f57b-4ff3-ac5c-f30674037b21", "A", "BC", "C"),
    (4, "f5c2ebfd-f57b-4ff3-ac5c-f30674037b22", "A", "BC", "C"),
]

schema = StructType(
    [
        StructField("uuid", IntegerType(), True, {"comment": "foo bar"}),
        StructField("user_id", StringType(), True),
        StructField("col1", StringType(), True),
        StructField("ts", StringType(), True),
        StructField("part", StringType(), True),
    ]
)

df = spark.createDataFrame(data=data, schema=schema)


tableName="test_starrocks_mor"

basePath="s3://bucket/test_starrocks_mor"

hudi_options = {
"hoodie.table.name": tableName,
"hoodie.datasource.write.recordkey.field": "uuid",
"hoodie.datasource.write.partitionpath.field": "part",
"hoodie.datasource.write.table.name": tableName,
"hoodie.datasource.write.operation": "insert",
"hoodie.datasource.write.table.type": "MERGE_ON_READ",
"hoodie.datasource.write.precombine.field": "ts",
 "hoodie.datasource.hive_sync.enable": "true",
"hoodie.datasource.hive_sync.database": "default",
"hoodie.datasource.hive_sync.table": tableName,
"hoodie.datasource.hive_sync.mode": "hms",
"hoodie.datasource.hive_sync.partition_fields": "part",
"hoodie.datasource.hive_sync.partition_extractor_class": "org.apache.hudi.hive.MultiPartKeysValueExtractor",
}

# insert
(df.write.format("hudi").options(**hudi_options).mode("overwrite").save(basePath))
# upsert
(df.write.format("hudi").options(**hudi_options).option("hoodie.datasource.write.operation", "upsert").mode("append").save(basePath))
```

### Expected behavior (Required)

Starrocks should not fail with error

### Real behavior (Required)

1. create a MOR table (see below pyspark script)
2. do insert
3. do upsert (to create logs files)
4. sync glue w/ hive sync
5. now try to read both `_ro` / `_rt` tables
6. `_ro` works fine, but `_rt` fails

```
Caused by: java.io.IOException: No FileSystem for scheme: s3
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.parquet.hadoop.util.HadoopInputFile.fromPath(HadoopInputFile.java:38)
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:469)
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:454)
        at org.apache.hadoop.hive.ql.io.parquet.ParquetRecordReaderBase.getSplit(ParquetRecordReaderBase.java:79)
        at org.apache.hadoop.hive.ql.io.parquet.read.ParquetRecordReaderWrapper.<init>(ParquetRecordReaderWrapper.java:75)
        at org.apache.hadoop.hive.ql.io.parquet.read.ParquetRecordReaderWrapper.<init>(ParquetRecordReaderWrapper.java:60)
        at org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat.getRecordReader(MapredParquetInputFormat.java:92)
        at org.apache.hudi.hadoop.HoodieParquetInputFormat.getRecordReaderInternal(HoodieParquetInputFormat.java:89)
        at org.apache.hudi.hadoop.HoodieParquetInputFormat.getRecordReader(HoodieParquetInputFormat.java:83)
        at org.apache.hudi.hadoop.realtime.HoodieParquetRealtimeInputFormat.getRecordReader(HoodieParquetRealtimeInputFormat.java:74)
        at com.starrocks.hudi.reader.HudiSliceScanner.initReader(HudiSliceScanner.java:183)
        at com.starrocks.hudi.reader.HudiSliceScanner.open(HudiSliceScanner.java:201)
```
### StarRocks version (Required)
- 
```
+-------------------+
| current_version() |
+-------------------+
| 3.0.4 f8ff06dcbc  |
+-------------------+
```
- aws glue metastore
- any hudi version from 0.11 to 0.13

 I suspect somehow on glue / s3 for realtimeview w/ logs files, starrocks try to resolve parquet files with `s3` scheme instead of `s3a` (maybe @dirtysalt)

**Comment by Smith-Cruise** [comment]
Because MOR is using JNI to access s3, but s3 credential doesn't pass through JNI now.
You can configure `core-site.xml` in be/conf.

**Comment by dirtysalt** [comment]
Got it. 

Right now reading from hudi table have two data paths:
- from RO table, we use C++ native code
- from RT table(since there are some complicated merge-on-read code logic), we use C++->JNI->Java Code.

And in java code, we are supposed to use hadoop/hdfs to access s3, and I guess we need to integrate hadoop-aws jar, otherwise this problem will be raised.

So my guess is, maybe you can 
- download a hadoo-aws.jar https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws
- put it under be/lib/hudi-reader-lib, 
- and restart BE and try it.

**Comment by parisni** [comment]
Thanks for your help. I copied the lib, before starting the BE:
```
root@starrocks-be:/data/deploy# ls -Alrth starrocks/be/lib/hudi-reader-lib/|grep aws
-rw-rw-r-- 1 1001  1001 769K Jul 19 16:30 hadoop-aws-3.3.6.jar
```

Sadly this did not solve

**Comment by dirtysalt** [comment]
OK, I'll try to reproduce this case on my side and find solution.

**Comment by Smith-Cruise** [comment]
> OK, I'll try to reproduce this case on my side and find solution.

He also need to set `core-site.xml`, because Hadoop S3AFilesystem only support for s3a:// protocol, not s3:// protocol.

**Comment by dirtysalt** [comment]
@Smith-Cruise you are right. I'm hittig that problem when I'm reproducing this case.

**Comment by dirtysalt** [comment]
Looks like there are two problems out there:
1. lacks of hadoop-aws to access s3 (which I will fix)
2. lacks of correct configuration.

Because we use hadoop-aws to access s3, we need to configure hadoop configuration under be/conf/core-site.xml.

In following configuration, it assume be accesses S3 via ak/sk. But if our ec2 has right access to s3 using instance profile, then there is no need to configure ak/sk.

And full documentation about credential configuration can be found here. https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/index.html#Authenticating_with_S3

```
<configuration>
  <property>
      <name>fs.s3.impl</name>
      <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
   </property>
   <property>
      <name>fs.AbstractFileSystem.s3.impl</name>
      <value>org.apache.hadoop.fs.s3a.S3A</value>
   </property>
   <property>
      <name>fs.s3.access.key</name>
      <value>****</value>
   </property>
   <property>
      <name>fs.s3.secret.key</name>
      <value>*****</value>
   </property>
   <property>
      <name>fs.s3.endpoint</name>
      <value>s3.us-west-2.amazonaws.com</value>
   </property>
<、configuration>
```
