### ISSUE TITLE
fe memory leak 

### ISSUE THREAD

**Issue by caohb1985** [StarRocks/starrocks#27975]
starrocks fe 2.5.8   
![微信图片_20230726162029](https://github.com/StarRocks/starrocks/assets/38458555/4947d56e-2e04-4101-8c5a-8fce22b5df9f)

**Comment by gengjun-git** [comment]
Can you give more details? or send us the dump file?

**Comment by caohb1985** [comment]
the dump file is too large

**Comment by caohb1985** [comment]
One instance of "com.starrocks.server.GlobalStateMgr" loaded by "sun.misc.Launcher$AppClassLoader @ 0xe99b0830" occupies 15,224,148,664 (85.80%) bytes. The memory is accumulated in one instance of "com.starrocks.transaction.DatabaseTransactionMgr", loaded by "sun.misc.Launcher$AppClassLoader @ 0xe99b0830", which occupies 11,679,266,016 (65.83%) bytes.

Keywords
com.starrocks.server.GlobalStateMgr
sun.misc.Launcher$AppClassLoader @ 0xe99b0830
com.starrocks.transaction.DatabaseTransactionMgr

**Comment by caohb1985** [comment]
com.starrocks.server.GlobalStateMgr

**Comment by caohb1985** [comment]
com.starrocks.server.GlobalStateMgr 应该是没有垃圾回收

**Comment by gengjun-git** [comment]
@caohb1985 方便加微信吗？18810663282

**Comment by caohb1985** [comment]
已经加你了

**Comment by gengjun-git** [comment]
LabelCleaner thread is blocked
```
"LoadLabelCleaner" #67 daemon prio=5 os_prio=0 tid=0x00007fab90005000 nid=0x2961c waiting on condition [0x00007fabd65ec000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000397310c40> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at com.starrocks.journal.JournalTask.get(JournalTask.java:65)
        at com.starrocks.journal.JournalTask.get(JournalTask.java:14)
        at com.starrocks.persist.EditLog.waitInfinity(EditLog.java:1035)
        at com.starrocks.persist.EditLog.logEdit(EditLog.java:977)
        at com.starrocks.persist.EditLog.logEndLoadJob(EditLog.java:1434)
        at com.starrocks.load.loadv2.InsertLoadJob.setLoadFinishOrCancel(InsertLoadJob.java:119)
        at com.starrocks.load.loadv2.LoadManager.recordFinishedOrCacnelledLoadJob(LoadManager.java:203)
        at com.starrocks.load.loadv2.LoadManager.lambda$cleanResidualJob$6(LoadManager.java:390)
        at com.starrocks.load.loadv2.LoadManager$$Lambda$525/1573738362.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.starrocks.load.loadv2.LoadManager.cleanResidualJob(LoadManager.java:385)
        at com.starrocks.server.GlobalStateMgr.clearExpiredJobs(GlobalStateMgr.java:3532)
        at com.starrocks.server.GlobalStateMgr$2.runAfterCatalogReady(GlobalStateMgr.java:1738)
        at com.starrocks.common.util.LeaderDaemon.runOneCycle(LeaderDaemon.java:60)
        at com.starrocks.common.util.Daemon.run(Daemon.java:115)

```
