### ISSUE TITLE
BE crash on _delete_tablets_on_unused_root_path or publish_primary_key_tablet

### ISSUE THREAD

**Issue by zhengxingmao** [StarRocks/starrocks#28467]
### Steps to reproduce the behavior (Required)
Flink task sink to StarRocks,continuously reporting errors that the file cannot be found, and carshed.
There are several primary keys composed of three fields in the table. 
The error info like this :
```
Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /starrocks/f0ba92ba-5751-4edf-9497-45efe43e2f4c/12013/log/0000000000002EEF_000000000000BE37.log
        at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
        at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
        at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:156)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:2089)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:762)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:458)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:604)
        at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:572)
        at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:556)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1043)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:971)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2976)
```
And here is stack info :
*** Aborted at 1690903787 (unix time) try "date -d @1690903787" if you are using GNU date ***
First one:
```
PC: @     0x7ff53bd26387 __GI_raise
*** SIGABRT (@0x3924) received by PID 14628 (TID 0x7ff44adaa700) from PID 14628; stack trace: ***
    @          0x5f4e7a2 google::(anonymous namespace)::FailureSignalHandler()
    @          0x7ff53c7db630 (unknown)
    @          0x7ff53bd26387 __GI_raise
    @          0x7ff53bd27a78 __GI_abort
    @          0x27f0aee starrocks::failure_function()
    @          0x5f4217d google::LogMessage::Fail()
    @          0x5f445ef google::LogMessage::SendToLog()
    @          0x5f41cce google::LogMessage::Flush()
    @          0x5f44bf9 google::LogMessageFatal::~LogMessageFatal()
    @          0x4193e89 starrocks::StorageEngine::_delete_tablets_on_unused_root_path()
    @          0x4193fba starrocks::StorageEngine::_start_disk_stat_monitor()
    @          0x447b221 starrocks::StorageEngine::_disk_stat_monitor_thread_callback()
    @          0x8236210 execute_native_thread_routine
    @          0x7ff53c7d3ea5 start_thread
    @          0x7ff53bdeeb0d __clone
    @                0x0 (unknown)
```
Second one:
```PC: @     0x7fe645c08387 __GI_raise
*** SIGABRT (@0x7ee6) received by PID 32486 (TID 0x7fe572916700) from PID 32486; stack trace: ***
    @          0x5f4e7a2 google::(anonymous namespace)::FailureSignalHandler()
    @          0x7fe6466bd630 (unknown)
    @          0x7fe645c08387 __GI_raise
    @          0x7fe645c09a78 __GI_abort
    @          0x27f0aee starrocks::failure_function()
    @          0x5f4217d google::LogMessage::Fail()
    @          0x5f445ef google::LogMessage::SendToLog()
    @          0x5f41cce google::LogMessage::Flush()
    @          0x5f44bf9 google::LogMessageFatal::~LogMessageFatal()
    @          0x442464c starrocks::lake::UpdateManager::publish_primary_key_tablet()
    @          0x4454456 starrocks::lake::PrimaryKeyTxnLogApplier::apply()
    @          0x44099cc starrocks::lake::TabletManager::publish_version()
    @          0x4ab0dec ZNSt17_Function_handlerIFvvEZN9starrocks15LakeServiceImpl15publish_versionEPN6google8protobuf13RpcControllerEPKNS1_4lake21PublishVersionRequestEPNS7_22PublishVersionResponseEPNS4_7ClosureEEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x4b97542 starrocks::ThreadPool::dispatch_thread()
    @          0x4b9203a starrocks::Thread::supervise_thread()
    @          0x7fe6466b5ea5 start_thread
```
### StarRocks version (Required)
 3.1.0RC1 With storage and calculation separation mode

**Comment by zhengxingmao** [comment]
Simply relate to this line https://github.com/StarRocks/starrocks/blob/ea7fd029482603790e9dd14d0ea33b55d6c09000/be/src/storage/storage_engine.cpp#L568

**Comment by zhengxingmao** [comment]
What is the reason why the file cannot be found?

**Comment by zhengxingmao** [comment]
Second one maybe relate to https://github.com/StarRocks/starrocks/pull/26424 @luohaha

**Comment by jaogoy** [comment]
@zhengxingmao Is the table a PK model or others? Is the FE error right for the noexisting file?

**Comment by zhengxingmao** [comment]
Table is a PK model ,It's been too long. The log has been cleared and has not been reproduced as of now.

**Comment by lufeizxy** [comment]
Our team also catch this bug using shared-data StarRocks, which caused the be node to crash. The stack of this error is as follows:
hdfsOpenFile(/home/starrocks/aa9bb40c-19e5-43a7-bfce-c26747d22f3c/71763/log/0000000000011C41_000000000002667D.log): FileSystem#open((Lorg/apache/hadoop/fs/Path;I)Lorg/apache/hadoop/fs/FSDataInputStream;)
error:
RemoteException: File does not exist: /home/starrocks/aa9bb40c-19e5-43a7-bfce-c26747d22f3c/71763/log/0000000000011C41_000000000002667D.log
        at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
        at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
        at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:160)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:2042)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:825)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:285)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1072)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1027)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:948)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:3039)
java.io.FileNotFoundException: File does not exist: /home/starrocks/aa9bb40c-19e5-43a7-bfce-c26747d22f3c/71763/log/0000000000011C41_000000000002667D.log
        at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
        at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
        at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:160)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:2042)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:825)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:285)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1072)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1027)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:948)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:3039)

        at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
        at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:343)
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:339)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:356)
Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /home/starrocks/aa9bb40c-19e5-43a7-bfce-c26747d22f3c/71763/log/0000000000011C41_000000000002667D.log
        at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
        at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
        at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:160)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:2042)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:825)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:285)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1072)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1027)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:948)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:3039)

        at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1567)
        at org.apache.hadoop.ipc.Client.call(Client.java:1513)
        at org.apache.hadoop.ipc.Client.call(Client.java:1410)
        at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:258)
        at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:139)
        at com.sun.proxy.$Proxy24.getBlockLocations(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:334)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:433)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:166)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:158)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:96)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:362)
        at com.sun.proxy.$Proxy25.getBlockLocations(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
        ... 7 more
