### ISSUE TITLE
Getting error when running "pip install starrocks" on Mac Ventura 13.5

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#28792]
```
atwong@Alberts-MBP-3 sandbox % pip install starrocks
Collecting starrocks
  Obtaining dependency information for starrocks from https://files.pythonhosted.org/packages/20/2a/6540970e7abf131d09a2cd232e5bfee98cb1380596aae0248890a5944da2/starrocks-1.0.5-py3-none-any.whl.metadata
  Downloading starrocks-1.0.5-py3-none-any.whl.metadata (2.3 kB)
Collecting sqlalchemy<2,>=1.4 (from starrocks)
  Downloading SQLAlchemy-1.4.49.tar.gz (8.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 34.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sqlalchemy-utils<0.39,>=0.38.3 (from starrocks)
  Using cached SQLAlchemy_Utils-0.38.3-py3-none-any.whl (100 kB)
Collecting mysqlclient<3,>=2.1.0 (from starrocks)
  Downloading mysqlclient-2.2.0.tar.gz (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.5/89.5 kB 17.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "/Users/atwong/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/atwong/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/atwong/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/xn/_h8gfpfs3vv_m6gkxm8t0l380000gn/T/pip-build-env-bllocdw9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/xn/_h8gfpfs3vv_m6gkxm8t0l380000gn/T/pip-build-env-bllocdw9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/xn/_h8gfpfs3vv_m6gkxm8t0l380000gn/T/pip-build-env-bllocdw9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
        File "<string>", line 48, in get_config_posix
        File "<string>", line 27, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by alberttwong** [comment]
```
atwong@Alberts-MBP-3 sandbox % pyenv version
3.9.16 (set by /Users/atwong/.pyenv/version)
```

**Comment by alberttwong** [comment]
short answer 

brew reinstall mysql-client
export PKG_CONFIG_PATH="/opt/homebrew/opt/mysql-client/lib/pkgconfig"
pip install starrocks

```
atwong@Alberts-MBP-3 ~ % brew reinstall mysql-client
==> Fetching mysql-client
==> Downloading https://ghcr.io/v2/homebrew/core/mysql-client/manifests/8.1.0
Already downloaded: /Users/atwong/Library/Caches/Homebrew/downloads/870c579387f033b043d4abd48d5da12500675a5346c80262c2474fa75d78c483--mysql-client-8.1.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mysql-client/blobs/sha256:26cc0
Already downloaded: /Users/atwong/Library/Caches/Homebrew/downloads/bdc26b33ae68a13f5fce83d560b106de93f3dd87d5ede5a48a4c7ee11a39a27a--mysql-client--8.1.0.arm64_ventura.bottle.tar.gz
==> Reinstalling mysql-client
==> Pouring mysql-client--8.1.0.arm64_ventura.bottle.tar.gz
==> Caveats
mysql-client is keg-only, which means it was not symlinked into /opt/homebrew,
because it conflicts with mysql (which contains client libraries).

If you need to have mysql-client first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"' >> ~/.zshrc

For compilers to find mysql-client you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/mysql-client/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/mysql-client/include"

For pkg-config to find mysql-client you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/mysql-client/lib/pkgconfig"
==> Summary
🍺  /opt/homebrew/Cellar/mysql-client/8.1.0: 128 files, 150.8MB
==> Running `brew cleanup mysql-client`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
atwong@Alberts-MBP-3 ~ % pip install starrocks
Collecting starrocks
  Obtaining dependency information for starrocks from https://files.pythonhosted.org/packages/20/2a/6540970e7abf131d09a2cd232e5bfee98cb1380596aae0248890a5944da2/starrocks-1.0.5-py3-none-any.whl.metadata
  Using cached starrocks-1.0.5-py3-none-any.whl.metadata (2.3 kB)
Collecting sqlalchemy<2,>=1.4 (from starrocks)
  Using cached SQLAlchemy-1.4.49.tar.gz (8.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sqlalchemy-utils<0.39,>=0.38.3 (from starrocks)
  Using cached SQLAlchemy_Utils-0.38.3-py3-none-any.whl (100 kB)
Collecting mysqlclient<3,>=2.1.0 (from starrocks)
  Using cached mysqlclient-2.2.0.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "/Users/atwong/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/atwong/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/atwong/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/xn/_h8gfpfs3vv_m6gkxm8t0l380000gn/T/pip-build-env-d8ouxeqp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/xn/_h8gfpfs3vv_m6gkxm8t0l380000gn/T/pip-build-env-d8ouxeqp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/xn/_h8gfpfs3vv_m6gkxm8t0l380000gn/T/pip-build-env-d8ouxeqp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
        File "<string>", line 48, in get_config_posix
        File "<string>", line 27, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
atwong@Alberts-MBP-3 ~ % export PKG_CONFIG_PATH="/opt/homebrew/opt/mysql-client/lib/pkgconfig"
atwong@Alberts-MBP-3 ~ % pip install starrocks
Collecting starrocks
  Obtaining dependency information for starrocks from https://files.pythonhosted.org/packages/20/2a/6540970e7abf131d09a2cd232e5bfee98cb1380596aae0248890a5944da2/starrocks-1.0.5-py3-none-any.whl.metadata
  Using cached starrocks-1.0.5-py3-none-any.whl.metadata (2.3 kB)
Collecting sqlalchemy<2,>=1.4 (from starrocks)
  Using cached SQLAlchemy-1.4.49.tar.gz (8.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sqlalchemy-utils<0.39,>=0.38.3 (from starrocks)
  Using cached SQLAlchemy_Utils-0.38.3-py3-none-any.whl (100 kB)
Collecting mysqlclient<3,>=2.1.0 (from starrocks)
  Using cached mysqlclient-2.2.0.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Downloading starrocks-1.0.5-py3-none-any.whl (10 kB)
Building wheels for collected packages: mysqlclient, sqlalchemy
  Building wheel for mysqlclient (pyproject.toml) ... done
  Created wheel for mysqlclient: filename=mysqlclient-2.2.0-cp39-cp39-macosx_13_0_arm64.whl size=75467 sha256=58ad155b9b98b3c7af276097a115cd4ac8a18f31e0f38ce083a8935ce14c7094
  Stored in directory: /Users/atwong/Library/Caches/pip/wheels/aa/58/d4/2e7a1d266508fd74887c2f74ec1ae819509bae6711480d8666
  Building wheel for sqlalchemy (pyproject.toml) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.4.49-cp39-cp39-macosx_13_0_arm64.whl size=1565123 sha256=5a179efcaa11b38989f33f64f4bf039039258e18ae92fe0d2122b213973a60be
  Stored in directory: /Users/atwong/Library/Caches/pip/wheels/19/ba/f3/f36b5a8f372bd5fb29b114e787e43fae0db141350198340272
Successfully built mysqlclient sqlalchemy
Installing collected packages: sqlalchemy, mysqlclient, sqlalchemy-utils, starrocks
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.19
    Uninstalling SQLAlchemy-2.0.19:
      Successfully uninstalled SQLAlchemy-2.0.19
Successfully installed mysqlclient-2.2.0 sqlalchemy-1.4.49 sqlalchemy-utils-0.38.3 starrocks-1.0.5
```
