### ISSUE TITLE
stream load failed with vague error message

### ISSUE THREAD

**Issue by kevincai** [StarRocks/starrocks#29209]
```
$ curl --location-trusted -u root -p -H "label:label_000" \
    -H "format: CSV" \
    -H "skip_header: 1" \
    -H "column_separator:," \
    -H "columns: col1,sender,receiver,txhash,timestamp=str_to_date(col1)" \
    -T USDC-Polygon-transfers.csv -XPUT \
    https://<be_ip>:<be_port>/api/test_db/<table>/_stream_load
{
    "TxnId": 1010,
    "Label": "label_000",
    "Status": "Fail",
    "Message": "",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 0,
    "LoadTimeMs": 0,
    "BeginTxnTimeMs": 3,
    "StreamLoadPlanTimeMs": 5,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 0,
    "CommitAndPublishTimeMs": 0
}
curl: (18) HTTP/2 stream 1 was reset
```

BE LOG:
```
W0815 00:27:05.901499   749 stream_load.cpp:591] plan streaming load failed. errmsg=id=ed483fd735c45ff7-02b078b89403e887, job_id=-1, txn_id: 1010, label=label_000, db=test_db
```

FE LOG:
```
2023-08-15 00:27:05,901 INFO (thrift-server-pool-102|346) [FrontendServiceImpl.loadTxnRollback():1328] receive txn rollback request. db: test_db, tbl: ***, txn_id: 1010, reason: , backend: ***
at java.lang.Thread.run(Thread.java:829) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311) ~[starrocks-fe.jar:?]
at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.13.0.jar:0.13.0]
at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.13.0.jar:0.13.0]
at com.starrocks.thrift.FrontendService$Processor$streamLoadPut.getResult(FrontendService.java:3326) ~[starrocks-fe.jar:?]
at com.starrocks.thrift.FrontendService$Processor$streamLoadPut.getResult(FrontendService.java:3346) ~[starrocks-fe.jar:?]
at com.starrocks.service.FrontendServiceImpl.streamLoadPut(FrontendServiceImpl.java:1433) ~[starrocks-fe.jar:?]
at com.starrocks.service.FrontendServiceImpl.streamLoadPutImpl(FrontendServiceImpl.java:1479) ~[starrocks-fe.jar:?]
at com.starrocks.planner.StreamLoadPlanner.plan(StreamLoadPlanner.java:181) ~[starrocks-fe.jar:?]
at com.starrocks.planner.StreamLoadScanNode.init(StreamLoadScanNode.java:186) ~[starrocks-fe.jar:?]
at com.starrocks.planner.StreamLoadScanNode.initParams(StreamLoadScanNode.java:228) ~[starrocks-fe.jar:?]
at com.starrocks.planner.StreamLoadScanNode.initColumns(StreamLoadScanNode.java:234) ~[starrocks-fe.jar:?]
at com.starrocks.load.Load.initColumns(Load.java:640) ~[starrocks-fe.jar:?]
at com.starrocks.load.Load.analyzeMappingExprs(Load.java:780) ~[starrocks-fe.jar:?]
at com.starrocks.analysis.Expr.analyzeAndCastFold(Expr.java:1435) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeExpressionIgnoreSlot(ExpressionAnalyzer.java:1623) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeIgnoreSlot(ExpressionAnalyzer.java:127) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:331) ~[starrocks-fe.jar:?]
at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[starrocks-fe.jar:?]
at com.starrocks.analysis.FunctionCallExpr.accept(FunctionCallExpr.java:487) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:334) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1078) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.AnalyzerUtils.getUdfFunction(AnalyzerUtils.java:213) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.AnalyzerUtils.getGlobalUdfFunction(AnalyzerUtils.java:198) ~[starrocks-fe.jar:?]
java.lang.NullPointerException: null
2023-08-15 00:27:05,900 WARN (thrift-server-pool-103|347) [FrontendServiceImpl.streamLoadPut():1439] catch unknown result.
```

It is the `timestamp=str_to_date(col1)` incorrect use of `str_to_date` causes the error. The failure is reasonable, but the error message doesn't to the stream load response, doesn't contain any useful information, neither in the BE log.

Need improve the failure reason so the end user can easily understand and adjust the request accordingly.

**Comment by kevincai** [comment]
with above #29386 fixes,  the error will show like follows
```
{
    "TxnId": 6009,
    "Label": "label_0000",
    "Status": "Fail",
    "Message": "Getting analyzing error from line 1, column 29 to line 1, column 45. Detail message: No matching function with signature: str_to_date(varchar).",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 0,
    "LoadTimeMs": 0,
    "BeginTxnTimeMs": 16,
    "StreamLoadPlanTimeMs": 81,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 0,
    "CommitAndPublishTimeMs": 0
}
```

It has a complete error message indicating the problem.

**Comment by kevincai** [comment]
FE LOG example
```
2023-08-17 06:56:12,384 WARN (thrift-server-pool-15|295) [FrontendServiceImpl.streamLoadPut():1436] failed to get stream load plan: Getting analyzing error from line 1, column 29 to line 1, column 45. Detail message: No matching function with signature: str_to_date(varchar).
```
