### ISSUE TITLE
异步物化视图中如果有list分区表，刷新物化视图任务时，fe会报错

### ISSUE THREAD

**Issue by mkt2022** [StarRocks/starrocks#29233]
### StarRocks version
3.1、3.0.4

### Steps to reproduce the behavior 
```sql
create table GL_DETAIL_T1
(
pk_detail         CHAR(20) not null,
  yearv             CHAR(4) not null,
  assid             CHAR(20)
)unique key(pk_detail,yearv)
comment "科目表"
partition by list(yearv)
(
  partition LIST1 values in ('2008', '2009', '2010', '2011', '2012'),
  partition LIST2 values in ('2013', '2014', '2015'),
  partition LIST3 values in ('2016'),
  partition LIST4 values in ('2017'),
  partition LIST5 values in ('2018'),
  partition LIST6 values in ('2019'),
  partition LIST7 values in ('2020'),
  partition LIST8 values in ('2021'),
  partition LIST9 values in ('2022'),
  partition LIST10 values in ('2023'),
  partition LIST11 values in ('2024'),
  partition LIST12 values in ('2025'),
  partition LIST13 values in ('2026')
)
distributed by hash(pk_detail) buckets 4
properties(
"replication_num"="1"
);

INSERT INTO GL_DETAIL_T1 values('1009AA1000000004C71M','2023','1234AA1000000004C71M');

create materialized view MV_T1
distributed by hash(pk_detail)
refresh async start('2023-08-15 16:10:00') every (interval 1 minute) as 
select F.pk_detail pk_detail
 FROM  GL_DETAIL  F;
```
 

### 查询MV_T1无数据，查看物化视图task任务存在报错：
```
mysql> select * from information_schema.task_runs where task_name = 'mv-11539' limit 1\G
*************************** 1. row ***************************
     QUERY_ID: 682533ca-3b43-11ee-83f6-5254000c0200
    TASK_NAME: mv-11539
  CREATE_TIME: 2023-08-15 16:11:59
  FINISH_TIME: 2023-08-15 16:12:00
        STATE: FAILED
     DATABASE: mkttest
   DEFINITION: insert overwrite MV_T1 SELECT `mkttest`.`F`.`pk_detail`
FROM `mkttest`.`GL_DETAIL` AS `F`
  EXPIRE_TIME: 2023-08-16 16:11:59
   ERROR_CODE: -1
ERROR_MESSAGE: java.lang.IllegalStateException
     PROGRESS: 0%
EXTRA_MESSAGE: {"forceRefresh":false,"mvPartitionsToRefresh":[],"refBasePartitionsToRefreshMap":{},"basePartitionsToRefreshMap":{}}
   PROPERTIES: {"mvId":"11539","replication_num":"1","in_memory":"false"}
1 row in set (0.01 sec)
```

### fe节点日志：
```
2023-08-15 16:13:00,032 WARN (pool-21-thread-5|628) [PartitionBasedMvRefreshProcessor.doMvRefresh():247] Refresh mv MV_T1 failed: java.lang.IllegalStateException
2023-08-15 16:13:00,032 WARN (pool-21-thread-5|628) [TaskRunExecutor.lambda$executeTaskRun$0():54] failed to execute TaskRun.
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:496) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.catalog.OlapTable.getRangePartitionMap(OlapTable.java:858) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.checkBaseTablePartitionChange(PartitionBasedMvRefreshProcessor.java:958) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doMvRefresh(PartitionBasedMvRefreshProcessor.java:188) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.processTaskRun(PartitionBasedMvRefreshProcessor.java:158) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:189) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:47) ~[starrocks-fe.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

**Comment by jaogoy** [comment]
Maybe MV doesn't support List partitioned base table yet.

**Comment by mofeiatwork** [comment]
it's supported in latest version. you could update to the latest version of 3.1.*
