### ISSUE TITLE
postgresql  the table name has blank space，run starrocks-migrate-tool migrate error

### ISSUE THREAD

**Issue by chenglin321** [StarRocks/starrocks#29405]
the table name has blank space ,eg: " itlh1", when  run the migrate tools

$ ./starrocks-migrate-tool 

2023/08/17 17:05:04 source/pgsql.go:124 ERROR: relation "public.itlh1" does not exist (SQLSTATE 42P01)
[131.892ms] [rows:0] SELECT "table_name","table_schema","table_catalog",pg_table_size(table_schema || '.' || table_name) as data_length,pg_indexes_size(table_schema || '.' || table_name) as index_length FROM "information_schema"."tables" WHERE table_type='BASE TABLE' and table_schema not in ('information_schema', 'pg_catalog') ORDER BY TABLE_SCHEMA asc, TABLE_NAME asc
panic: ERROR: relation "public.itlh1" does not exist (SQLSTATE 42P01)

goroutine 1 [running]:
main.main()
	main.go:39 +0x959

**Comment by chenglin321** [comment]
select
	table_name,
	table_schema,
	table_catalog,
	pg_table_size(table_name1) AS  data_length,
	pg_indexes_size(table_name1) as index_length
from
	(
		select
			table_name,('"' || table_schema || '"."' || table_name || '"') as table_name1,table_schema,table_type,table_catalog
		from
			information_schema.tables 
	where		
			table_type = 'BASE TABLE'
	and table_schema not in ('information_schema', 'pg_catalog')
	) t
order by
	TABLE_SCHEMA asc,
	TABLE_NAME asc

**Comment by jaogoy** [comment]
@huangfeng1993 Could you have a look?
