### ISSUE TITLE
[daily] cn crash

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#29499]
### Steps to reproduce the behavior (Required)
```
*** Aborted at 1692273119 (unix time) try "date -d @1692273119" if you are using GNU date ***
PC: @     0x7fd95fd570d5 jni_CallVoidMethodV
*** SIGSEGV (@0xffffffff00000036) received by PID 2716 (TID 0x7fd8c00f5700) from PID 54; stack trace: ***
    @          0x600ec02 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fd95ff8b235 os::Linux::chained_handler()
    @     0x7fd95ff90031 JVM_handle_linux_signal
    @     0x7fd95ff830c8 signalHandler()
    @     0x7fd95f43a630 (unknown)
    @     0x7fd95fd570d5 jni_CallVoidMethodV
    @          0x40c9b79 JNIEnv_::CallVoidMethod()
    @          0x52db608 starrocks::JniScanner::do_close()
    @          0x52e3248 starrocks::HdfsScanner::close()
    @          0x5252e58 _ZZN9starrocks10ObjectPool3addINS_10JniScannerEEEPT_S4_ENUlPvE_4_FUNES5_
    @          0x5254748 starrocks::connector::HiveDataSource::~HiveDataSource()
    @          0x293e48b starrocks::pipeline::ConnectorChunkSource::~ConnectorChunkSource()
    @          0x27eed0a std::_Sp_counted_base<>::_M_release()
    @          0x293a95b _ZZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS_12RuntimeStateEiENKUlvE_clEv
    @          0x2943121 starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x4c279b2 starrocks::ThreadPool::dispatch_thread()
    @          0x4c224aa starrocks::Thread::supervise_thread()
    @     0x7fd95f432ea5 start_thread
    @     0x7fd95ea4db0d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-3.1-00dc135

**Comment by dirtysalt** [comment]
In be.INFO, I saw logs like

```
W0817 19:51:59.359172  2950 pipeline_driver.cpp:294] pull_chunk returns not ok status Internal error: Failed to init the scanner class. java exception details: java.lang.OutOfMemoryError: GC overhead limit exceeded[]
/root/celerdata/be/src/exec/jni_scanner.cpp:95 _check_jni_exception(_jni_env, "Failed to init the scanner class.")
/root/celerdata/be/src/exec/jni_scanner.cpp:45 _init_jni_table_scanner(_jni_env, runtime_state)
/root/celerdata/be/src/connector/hive_connector.cpp:542 scanner->init(state, scanner_params)
/root/celerdata/be/src/connector/hive_connector.cpp:105 _init_scanner(state)
/root/celerdata/be/src/exec/pipeline/scan/connector_scan_operator.cpp:504 _data_source->open(state)
/root/celerdata/be/src/exec/pipeline/scan/connector_scan_operator.cpp:533 _open_data_source(state)
/root/celerdata/be/src/exec/pipeline/scan/scan_operator.cpp:226 _get_scan_status()
W0817 19:51:59.359228  2950 pipeline_driver_executor.cpp:161] [Driver] Process error, query_id=77990d7b-3cf4-11ee-ac9a-00163e0a0ae1, instance_id=77990d7b-3cf4-11ee-ac9a-00163e0a0ae2, status=Internal error: Failed to init the scanner class. java exception details: java.lang.OutOfMemoryError: GC overhead limit exceeded[]
/root/celerdata/be/src/exec/jni_scanner.cpp:95 _check_jni_exception(_jni_env, "Failed to init the scanner class.")
/root/celerdata/be/src/exec/jni_scanner.cpp:45 _init_jni_table_scanner(_jni_env, runtime_state)
/root/celerdata/be/src/connector/hive_connector.cpp:542 scanner->init(state, scanner_params)
/root/celerdata/be/src/connector/hive_connector.cpp:105 _init_scanner(state)
/root/celerdata/be/src/exec/pipeline/scan/connector_scan_operator.cpp:504 _data_source->open(state)
/root/celerdata/be/src/exec/pipeline/scan/connector_scan_operator.cpp:533 _open_data_source(state)
/root/celerdata/be/src/exec/pipeline/scan/scan_operator.cpp:226 _get_scan_status()

```

Looks like `jni_scanner_cls` is not created.  And in core dump file

```
(gdb) bt
#0  0x00007fd95fd570d5 in jni_CallNonvirtualCharMethodV () from /usr/lib/jvm/java-1.8.0/jre/lib/amd64/server/libjvm.so
#1  0x00000000040c9b79 in JNIEnv_::CallVoidMethod (this=this@entry=0x7fd8578bf2d8, obj=<optimized out>, methodID=<optimized out>) at /var/local/thirdparty/installed/open_jdk/include/jni.h:1054
#2  0x00000000052db608 in do_close (runtime_state=<optimized out>, this=0x7fd82d86d000) at /root/celerdata/be/src/exec/jni_scanner.cpp:63
#3  starrocks::JniScanner::do_close (this=0x7fd82d86d000, runtime_state=<optimized out>) at /root/celerdata/be/src/exec/jni_scanner.cpp:60
#4  0x00000000052e3248 in starrocks::HdfsScanner::close (this=this@entry=0x7fd82d86d000, runtime_state=0x7fd854096800) at /root/celerdata/be/src/exec/hdfs_scanner.cpp:181
#5  0x00000000052e3301 in starrocks::HdfsScanner::finalize (this=this@entry=0x7fd82d86d000) at /root/celerdata/be/src/exec/hdfs_scanner.cpp:190
#6  0x0000000005252e58 in ~JniScanner (this=0x7fd82d86d000, __in_chrg=<optimized out>) at /root/celerdata/be/src/exec/jni_scanner.h:31
#7  ~JniScanner (this=0x7fd82d86d000, __in_chrg=<optimized out>) at /root/celerdata/be/src/exec/jni_scanner.h:31
#8  operator() (obj=0x7fd82d86d000, this=0x0) at /root/celerdata/be/src/common/object_pool.h:45
#9  starrocks::JniScanner* starrocks::ObjectPool::add<starrocks::JniScanner>(starrocks::JniScanner*)::{lambda(void*)#1}::_FUN(void*) () at /root/celerdata/be/src/common/object_pool.h:45
#10 0x0000000005252e58 in starrocks::JniScanner* starrocks::ObjectPool::add<starrocks::JniScanner>(starrocks::JniScanner*)::{lambda(void*)#1}::_FUN(void*) ()
#11 0x0000000005254748 in clear (this=0x7fd855d4eee0) at /root/celerdata/be/src/common/object_pool.h:52
#12 ~ObjectPool (this=0x7fd855d4eee0, __in_chrg=<optimized out>) at /root/celerdata/be/src/common/object_pool.h:34
#13 ~HiveDataSource (this=0x7fd855d4ed00, __in_chrg=<optimized out>) at /root/celerdata/be/src/connector/hive_connector.h:51
#14 starrocks::connector::HiveDataSource::~HiveDataSource (this=0x7fd855d4ed00, __in_chrg=<optimized out>) at /root/celerdata/be/src/connector/hive_connector.h:51
#15 0x000000000293e48b in operator() (__ptr=<optimized out>, this=0x7fd852dd9a10) at /root/celerdata/be/src/exec/pipeline/scan/connector_scan_operator.cpp:489
```

And `f 2` to frame 2, variables are 
```
(gdb) p this._jni_scanner_cls
$3 = (jclass) 0x0
(gdb) p this._jni_scanner_obj
$4 = (jobject) 0x7fd8b6c33b70
(gdb) p this._jni_scanner_open
$5 = (jmethodID) 0x7fd8b6c33b78
```

`_jni_scanner_cls = 0x0` is expected, but `_jni_scanner_obj != 0x0` is not expected.  I guess it's because we rely on class/field initialization, but we don't set `_jni_scanner_obj = nullptr` in class definition.
