### ISSUE TITLE
Query error  unstable from iceberg external table when iceberg table dropped

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#3076]
### Steps to reproduce the behavior (Required)
1. create iceberg table:
```
create table hive_prod.iceberg_db.iceberg_par_parquet_snappy_refresh(
col_boolean boolean,
col_int int,
col_long long,
col_float float,
col_double double,
col_decimal decimal(38,18),
col_date date,
col_timestamp timestamp,
col_string string,
col_binary binary,
col_struct struct<a:string,b:int>,
col_map map<string,int>
) USING iceberg 
PARTITIONED BY (col_date)
TBLPROPERTIES('write.format.default'='parquet','write.parquet.compression-codec'='snappy');
```

2. create iceberg external table:
```
create external table ex_iceberg_parquet_refresh (
col_int int,
col_date date,
col_string varchar(200),
col_boolean boolean,
col_float float,
col_double double,
col_long bigint,
col_decimal decimal(38,18))
ENGINE=iceberg
properties (
"resource" = "iceberg_emr_tn",
"table" = "iceberg_par_parquet_snappy_refresh",
"database" = "iceberg_db");
```

3. drop iceberg table:
```
drop table hive_prod.iceberg_db.iceberg_par_parquet_snappy_refresh;
```

4. select iceberg external table:
```
mysql> select * from ex_iceberg_parquet_refresh;
ERROR 1064 (HY000): No such table: iceberg_db.iceberg_par_parquet_snappy_refresh
mysql> select * from ex_iceberg_parquet_refresh;
ERROR 1064 (HY000): Unknown error
```

### Expected behavior (Required)
ERROR 1064 (HY000): No such table: iceberg_db.iceberg_par_parquet_snappy_refresh

### Real behavior (Required)
After the second query, the error becomes:
ERROR 1064 (HY000): Unknown error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER d4a0de6 |
+------------------------+
1 row in set (0.04 sec)
```

**Comment by caneGuy** [comment]
please assign to me thanks

**Comment by caneGuy** [comment]
```
2022-02-09 10:38:44,285 WARN (starrocks-mysql-nio-pool-6|1969) [StmtExecutor.execute():452] execute Exception, sql select * from ex_iceberg_tbl8
java.lang.NullPointerException: null
        at org.apache.iceberg.BaseTable.currentSnapshot(BaseTable.java:109) ~[iceberg-core-0.12.1.jar:?]
        at com.starrocks.external.iceberg.IcebergUtil.getCurrentTableSnapshot(IcebergUtil.java:81) ~[starrocks-fe.jar:?]
        at com.starrocks.planner.IcebergScanNode.getScanRangeLocations(IcebergScanNode.java:128) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalIcebergScan(PlanFragmentBuilder.java:730) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalIcebergScan(PlanFragmentBuilder.java:234) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalIcebergScanOperator.accept(PhysicalIcebergScanOperator.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:243) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:139) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:97) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:47) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:291) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

```
2022-02-09 10:38:42,312 WARN (starrocks-mysql-nio-pool-6|1969) [StmtExecutor.execute():452] execute Exception, sql select * from ex_iceberg_tbl8
org.apache.iceberg.exceptions.NoSuchTableException: No such table: iceberg.iceberg_parquet
        at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:188) ~[iceberg-hive-metastore-0.12.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:94) ~[iceberg-core-0.12.1.jar:?]
        at org.apache.iceberg.BaseTable.refresh(BaseTable.java:59) ~[iceberg-core-0.12.1.jar:?]
        at com.starrocks.external.iceberg.IcebergUtil.getCurrentTableSnapshot(IcebergUtil.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.planner.IcebergScanNode.getScanRangeLocations(IcebergScanNode.java:128) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalIcebergScan(PlanFragmentBuilder.java:730) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalIcebergScan(PlanFragmentBuilder.java:234) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalIcebergScanOperator.accept(PhysicalIcebergScanOperator.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:243) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:139) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:97) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:47) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:291) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
