### ISSUE TITLE
The FE sometimes returns `java.net.SocketException: Broken pipe` when `show frontends;`

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#3077]
```
2022-01-25 16:23:46,142 WARN (starrocks-mysql-nio-pool-938|2617) [MasterOpExecutor.forward():152] Forward statement 17891501 to Master TNetworkAddress(hostname:172.26.194.119, port:9820) failed, e
rror type 0
org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe
        at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:159) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.thrift.FrontendService$Client.send_forward(FrontendService.java:430) ~[starrocks-fe.jar:?]
        at com.starrocks.thrift.FrontendService$Client.forward(FrontendService.java:422) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.forward(MasterOpExecutor.java:149) [starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.execute(MasterOpExecutor.java:76) [starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.forwardToMaster(StmtExecutor.java:553) [starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:317) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) [starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) [starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener$$Lambda$73/1018985975.run(Unknown Source) [starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_41]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_41]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_41]
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_41]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[?:1.8.0_41]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[?:1.8.0_41]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_41]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_41]
        at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:157) ~[libthrift-0.13.0.jar:0.13.0]
        ... 16 more
```
### Steps to reproduce the behavior (Required)
```
mysql> show frontends;
ERROR 1064 (HY000): java.net.SocketException: Broken pipe
```
### Expected behavior (Required)
return correct result.
### Real behavior (Required)
```
mysql> show frontends;
ERROR 1064 (HY000): java.net.SocketException: Broken pipe
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.1

**Comment by gengjun-git** [comment]
The reason is that frontendPool returned a broker conn, like #5655
