### ISSUE TITLE
"Table UUID does not match" error needed after recreate iceberg table

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#3078]
### Steps to reproduce the behavior (Required)
1. create iceberg table;
2. create iceberg external table;
3. drop iceberg table --> create iceberg table with same table name --> select iceberg external table:
```
mysql> select * from ex_iceberg_parquet_refresh;
ERROR 1064 (HY000): Table UUID does not match: current=1435706f-1321-4c8f-ab4b-6b248ceaaae7 != refreshed=612411ac-4f8e-425f-a23a-cb76f79b242f
```
4. drop iceberg table --> select iceberg external table --> create iceberg table with same table name --> select iceberg external table, no error.

### Expected behavior (Required)
Table UUID does not match error reported after recreate iceberg table.

### Real behavior (Required)
some times no error reported after recreate iceberg table.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER d4a0de6 |
+------------------------+
1 row in set (0.01 sec)
```

**Comment by caneGuy** [comment]
please assign to me thanks

**Comment by caneGuy** [comment]
```
2022-02-09 09:52:05,868 WARN (starrocks-mysql-nio-pool-4|1935) [StmtExecutor.execute():452] execute Exception, sql select * from iceberg_tbl
java.lang.IllegalStateException: Table UUID does not match: current=ab36dbed-3664-4442-8e8e-17e9c5495030 != refreshed=0e9d2e9c-fce6-4acb-8af4-4f75959249a5
        at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:824) ~[iceberg-bundled-guava-0.12.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:183) ~[iceberg-core-0.12.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:160) ~[iceberg-core-0.12.1.jar:?]
        at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:200) ~[iceberg-hive-metastore-0.12.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:94) ~[iceberg-core-0.12.1.jar:?]
        at org.apache.iceberg.BaseTable.refresh(BaseTable.java:59) ~[iceberg-core-0.12.1.jar:?]
        at com.starrocks.external.iceberg.IcebergUtil.getCurrentTableSnapshot(IcebergUtil.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.planner.IcebergScanNode.getScanRangeLocations(IcebergScanNode.java:128) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalIcebergScan(PlanFragmentBuilder.java:730) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalIcebergScan(PlanFragmentBuilder.java:234) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalIcebergScanOperator.accept(PhysicalIcebergScanOperator.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:243) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:139) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:97) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:47) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:291) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by caneGuy** [comment]
as discussed with @tiannan-sr we should throw exception to user here. since the table underhood has been changed, actually it is an other table
