### ISSUE TITLE
[paimon catalog] select from paimon table NPE

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#31329]
### Steps to reproduce the behavior (Required)
```
mysql> create external catalog paimon_catalog_957eafec_5677_11ee_9b1c_00163e0e489a
    ->                 PROPERTIES(
    ->                 "type" = "paimon",
    ->                 "paimon.catalog.type"="hive",
    ->                 "paimon.catalog.warehouse"="hdfs://emr-header-1.cluster-49091:9000/user/hive/warehouse",
    ->                 "hive.metastore.uris" = "thrift://emr-header-1.cluster-49091:9083");
Query OK, 0 rows affected (0.02 sec)

mysql> use paimon_catalog_957eafec_5677_11ee_9b1c_00163e0e489a.paimon_db
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select col_smallint, col_varchar, col_boolean from paimon_db.paimon_hdfs_orc_snappy order by 1 limit 5;
ERROR 1064 (HY000): Unknown error
```

fe.warn.log:
```
2023-09-19 09:53:28,785 WARN (starrocks-mysql-nio-pool-0|187) [StmtExecutor.execute():707] execute Exception, sql select col_smallint, col_varchar, col_boolean from paimon_db.paimon_hdfs_orc_snappy order by 1 limit 5
java.lang.NullPointerException: null
        at com.starrocks.connector.paimon.PaimonMetadata.getTableStatistics(PaimonMetadata.java:235) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.CatalogConnectorMetadata.getTableStatistics(CatalogConnectorMetadata.java:135) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.lambda$getTableStatistics$6(MetadataMgr.java:374) ~[starrocks-fe.jar:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at com.starrocks.server.MetadataMgr.getTableStatistics(MetadataMgr.java:374) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.getTableStatistics(MetadataMgr.java:387) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computePaimonScanNode(StatisticsCalculator.java:362) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalPaimonScan(StatisticsCalculator.java:350) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalPaimonScan(StatisticsCalculator.java:153) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalPaimonScanOperator.accept(LogicalPaimonScanOperator.java:47) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:169) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:57) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:65) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:569) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:191) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:129) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:148) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.planQuery(StatementPlanner.java:123) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:98) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:482) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:377) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:569) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:848) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

### Expected behavior (Required)
select execute success

### Real behavior (Required)
NPE

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main-e56cefd

**Comment by miomiocat** [comment]
introduced by #31281  @stephen-shelby
