### ISSUE TITLE
NullPointerException threw when executing `SHOW MATERIALIZED VIEWS` in version 3.1

### ISSUE THREAD

**Issue by wxl24life** [StarRocks/starrocks#31451]
### Steps to reproduce the behavior (Required)

SHOW MATERIALIZED VIEWS;

### Real behavior (Required)
```sh
2023-09-20 12:19:22,387 WARN (starrocks-mysql-nio-pool-2130|500802) [MvRewritePreprocessor.prepareRelatedMVs():196] preprocess mv xxx_view failed for query tables:[xxx_view]
java.lang.NullPointerException: null
        at com.starrocks.sql.optimizer.MvRewritePreprocessor.preprocessMv(MvRewritePreprocessor.java:238) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.MvRewritePreprocessor.prepareRelatedMVs(MvRewritePreprocessor.java:193) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.MvRewritePreprocessor.prepareMvCandidatesForPlan(MvRewritePreprocessor.java:88) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.prepare(Optimizer.java:246) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:121) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:140) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.planQuery(StatementPlanner.java:115) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:90) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:55) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:430) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:380) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:494) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:760) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]
```

### StarRocks version (Required)
- 3.1.0, run_mode=shared_data

**Comment by mofeiatwork** [comment]
It's already fixed by #30361
