### ISSUE TITLE
Query iceberg table, NullPointerException occurred

### ISSUE THREAD

**Issue by Xiangakun** [StarRocks/starrocks#31784]
### Steps to reproduce the behavior (Required)
Iceberg catalog：iceberg v2 table，which has delete file
exec sql：select bitmap_agg(id) from iceberg_catalog.test.test_table;
id with type bigint

### Expected behavior (Required)
return the result normally

### Real behavior (Required)
java.lang.NullPointerException: null

```java
java.lang.NullPointerException: null
	at com.starrocks.planner.IcebergScanNode.appendEqualityColumns(IcebergScanNode.java:165) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalIcebergScan(PlanFragmentBuilder.java:1198) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalIcebergScan(PlanFragmentBuilder.java:417) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.physical.PhysicalIcebergScanOperator.accept(PhysicalIcebergScanOperator.java:50) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:434) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:1750) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:417) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.physical.PhysicalHashAggregateOperator.accept(PhysicalHashAggregateOperator.java:220) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:434) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:1957) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:417) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.physical.PhysicalDistributionOperator.accept(PhysicalDistributionOperator.java:63) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:434) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:1750) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:417) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.physical.PhysicalHashAggregateOperator.accept(PhysicalHashAggregateOperator.java:220) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:434) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.translate(PlanFragmentBuilder.java:428) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:219) ~[starrocks-fe.jar:?]
```

### StarRocks version (Required)
3.1.2
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by Xiangakun** [comment]
In fact, when execute single query on the table like select count(*) from tableName, the same error occurred, the NullPointerException threw when execute following code in `IcebergScanNode.appendEqualityColumns`
`TableName tableName = desc.getRef().getName();`

Investigated with arthas, it shows desc.getRef() return null, and current TupleDescriptor is:

TupleDescriptor[TupleDescriptor{id=0, tbl=tableName, is_materialized=true, slots=[SlotDescriptor{id=2, parent=0, col=entity_config_id, type=INT, materialized=true, byteSize=0, byteOffset=-1, nullIndicatorByte=0, nullIndicatorBit=0, slotIdx=0}]}]

It's strange that `is_materialized` indicator is true, I did add MV for the test table, however, when execute above sql, the MV has dropped by me, and the prior MV does not contains count(*) or any other count agg.

**Comment by Xiangakun** [comment]
It seems, it's caused by starrocks does not support cases: iceberg with equality delete files
 https://github.com/StarRocks/starrocks/pull/30595

**Comment by Xiangakun** [comment]
However, for some cases, even when iceberg has equality delete files, starrocks can execute all the sql (sql with different pattern) and get correct result. In my scenario, the case like following: 
position deletes and equality deletes have same delete records, the data is produced by flink, each commit, one position delete and one equality delete file produced with same delete records

**Comment by dirtysalt** [comment]
> However, for some cases, even when iceberg has equality delete files, starrocks can execute all the sql (sql with different pattern) and get correct result. In my scenario, the case like following: position deletes and equality deletes have same delete records, the data is produced by flink, each commit, one position delete and one equality delete file produced with same delete records

We will support eq-delete in future version, and this feature is on the road

[[[Feature] support to read iceberg equality delete file for mor. by stephen-shelby · Pull Request #37419 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/37419)](https://github.com/StarRocks/starrocks/pull/37419)

[[[Feature] support to read iceberg equality delete file with parquet format by Xiangakun · Pull Request #41267 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/41267)](https://github.com/StarRocks/starrocks/pull/41267)
