### ISSUE TITLE
Glue unified catalog should not required hive URI

### ISSUE THREAD

**Issue by williamho123** [StarRocks/starrocks#32079]
### Steps to reproduce the behavior (Required)
I am trying out the unreleased unified catalog feature, using a custom build of Starrocks.

```
CREATE EXTERNAL CATALOG unified_catalog
PROPERTIES
(
    "type" = "unified",
    "unified.metastore.type" = "glue",
    "aws.glue.use_aws_sdk_default_behavior" = "true",
    "aws.glue.region" = "us-west-2",
    "aws.s3.use_aws_sdk_default_behavior" = "true",
    "aws.s3.region" = "us-west-2",
    "enable_metastore_cache" = "true",
    "enable_remote_file_cache" = "false"
);
```

### Expected behavior (Required)
Able to create a unified catalog with AWS Glue.

### Real behavior (Required)
Creation errors out.

SQL client reports `Query 1 ERROR: Unexpected exception: connector create failed`.

FE logs show that `hive.metastore.uris` is required, but this should not be required for an AWS Glue catalog.

```
2023-10-06 22:58:46,605 ERROR (starrocks-mysql-nio-pool-2|229) [ConnectorFactory.createConnector():56] can't create connector for type: unified
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.starrocks.connector.ConnectorFactory.createConnector(ConnectorFactory.java:43) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.ConnectorMgr.createConnector(ConnectorMgr.java:36) ~[starrocks-fe.jar:?]
	at com.starrocks.server.CatalogMgr.createCatalog(CatalogMgr.java:116) ~[starrocks-fe.jar:?]
	at com.starrocks.server.CatalogMgr.createCatalog(CatalogMgr.java:97) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.lambda$visitCreateCatalogStatement$70(DDLStmtExecutor.java:844) ~[starrocks-fe.jar:?]
	at com.starrocks.common.ErrorReport.wrapWithRuntimeException(ErrorReport.java:112) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitCreateCatalogStatement(DDLStmtExecutor.java:843) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitCreateCatalogStatement(DDLStmtExecutor.java:156) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.CreateCatalogStmt.accept(CreateCatalogStmt.java:63) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor.execute(DDLStmtExecutor.java:142) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1492) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:658) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:377) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:569) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:848) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NullPointerException: hive.metastore.uris must be set in properties when creating hive catalog
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1010) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.connector.delta.DeltaLakeInternalMgr.(DeltaLakeInternalMgr.java:50) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.delta.DeltaLakeConnector.(DeltaLakeConnector.java:47) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.unified.UnifiedConnector.(UnifiedConnector.java:60) ~[starrocks-fe.jar:?]
	... 23 more
```

### StarRocks version (Required)
Built from `main` on October 6th.

`main-d26ad8b`

**Comment by letian-jiang** [comment]
Thanks! Working on this.

**Comment by letian-jiang** [comment]
A quick fix would be https://github.com/StarRocks/starrocks/pull/31839, which takes some time to merge.
