### ISSUE TITLE
REVERSE  function crash

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#3248]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS g0;
CREATE DATABASE g0;
USE g0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 BIGINT NULL ,c_0_1 VARCHAR(31) NULL ,c_0_2 DATETIME NULL ,c_0_3 BOOLEAN NOT NULL ,c_0_4 BOOLEAN NOT NULL ,c_0_5 INT NOT NULL ,c_0_6 BOOLEAN NOT NULL ,c_0_7 VARCHAR(1) NOT NULL ,c_0_8 DATE NOT NULL ,c_0_9 BOOLEAN NOT NULL ,c_0_10 VARCHAR(11) NULL ,c_0_11 DECIMAL(1, 0)  NULL ,c_0_12 PERCENTILE PERCENTILE_UNION NULL ,c_0_13 DECIMAL(15, 10)  REPLACE NULL ,c_0_14 BOOLEAN REPLACE NULL ,c_0_15 FLOAT REPLACE_IF_NOT_NULL NOT NULL ,c_0_16 BOOLEAN REPLACE NULL ,c_0_17 DATE REPLACE_IF_NOT_NULL NOT NULL ,c_0_18 HLL HLL_UNION NOT NULL ) AGGREGATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10,c_0_11) DISTRIBUTED BY HASH (c_0_8,c_0_11,c_0_10,c_0_7,c_0_6,c_0_3,c_0_4,c_0_2,c_0_1) properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 CHAR(31) NOT NULL ) DUPLICATE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
INSERT INTO t0 VALUES (809557484, "EO6", "1970-01-01 08:00:00", false, true, 20, false, "", "1970-01-01", true, "m1Tg", 3, percentile_hash("1149329785"), NULL, NULL, 0.5994891118051477, true, "1970-01-01", hll_hash("gdy3GN"));
TRUNCATE TABLE t0;
SELECT t1.c_1_0 FROM t1 WHERE (((("")||(REVERSE(AES_ENCRYPT("f", "") ) ))) IS NOT NULL) GROUP BY t1.c_1_0 UNION SELECT t1.c_1_0 FROM t1 WHERE (NOT ((((("")||(REVERSE(AES_ENCRYPT("f", "") ) ))) IS NOT NULL))) GROUP BY t1.c_1_0 UNION SELECT t1.c_1_0 FROM t1 WHERE (((((("")||(REVERSE(AES_ENCRYPT("f", "") ) ))) IS NOT NULL)) IS NULL) GROUP BY t1.c_1_0;

```
crash.log:
==30311==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300077bd4f at pc 0x000003ecf621 bp 0x7ff1c72afe30 sp 0x7ff1c72afe28
WRITE of size 2 at 0x60300077bd4f thread T216 (fragment_mgr)
    #0 0x3ecf620 in strings::memcpy_inlined(void*, void const*, unsigned long) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/gutil/strings/fastmem.h:111
    #1 0x889030d in utf8_reverse_per_slice /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1664
    #2 0x88beebf in reverse<false> /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1680
    #3 0x88b9fe3 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::ReverseFunction::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1703
    #4 0x88b0075 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction>::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:138
    #5 0x889e35d in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::DealNullableColumnUnaryFunction<starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction> >::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:205
    #6 0x88946c3 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::DealNullableColumnUnaryFunction<starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction> >::evaluate<(starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:211
    #7 0x887bcda in starrocks::vectorized::StringFunctions::reverse(starrocks_udf::FunctionContext*, std::vector<std::shared_ptr<starrocks::vectorized::Column>, std::allocator<std::shared_ptr<starrocks::vectorized::Column> > > const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1710
    #8 0x8138edc in starrocks::vectorized::VectorizedFunctionCallExpr::evaluate(starrocks::ExprContext*, starrocks::vectorized::Chunk*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/function_call_expr.cpp:142
    #9 0x76bfe13 in starrocks::ExprContext::evaluate(starrocks::Expr*, starrocks::vectorized::Chunk*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/expr_context.cpp:194
    #10 0x76ca7dd in operator() /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:599
    #11 0x76cb22c in __invoke_impl<void, starrocks::Expr::evaluate_const(starrocks::ExprContext*)::<lambda()> > /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #12 0x76cb1fb in __invoke<starrocks::Expr::evaluate_const(starrocks::ExprContext*)::<lambda()> > /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:95
    #13 0x76cb007 in operator() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:717
    #14 0x76cb02a in operator() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:722
    #15 0x76cb03b in _FUN /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:722
    #16 0x7ff222d1920a in __pthread_once_slow (/lib64/libpthread.so.0+0x620a)
    #17 0x76c2685 in __gthread_once /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/x86_64-pc-linux-gnu/bits/gthr-default.h:700
    #18 0x76cb153 in call_once<starrocks::Expr::evaluate_const(starrocks::ExprContext*)::<lambda()> > /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:729
    #19 0x76ca9de in starrocks::Expr::evaluate_const(starrocks::ExprContext*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:598
    #20 0x813777c in starrocks::vectorized::VectorizedFunctionCallExpr::open(starrocks::RuntimeState*, starrocks::ExprContext*, starrocks_udf::FunctionContext::FunctionStateScope) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/function_call_expr.cpp:65
    #21 0x76c78a6 in starrocks::Expr::open(starrocks::RuntimeState*, starrocks::ExprContext*, starrocks_udf::FunctionContext::FunctionStateScope) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:437
    #22 0x76c78a6 in starrocks::Expr::open(starrocks::RuntimeState*, starrocks::ExprContext*, starrocks_udf::FunctionContext::FunctionStateScope) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:437
    #23 0x76bcd41 in starrocks::ExprContext::open(starrocks::RuntimeState*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/expr_context.cpp:69
    #24 0x76c7357 in starrocks::Expr::open(std::vector<starrocks::ExprContext*, std::allocator<starrocks::ExprContext*> > const&, starrocks::RuntimeState*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:429
    #25 0x5b5f52d in starrocks::ExecNode::open(starrocks::RuntimeState*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exec/exec_node.cpp:220
    #26 0x6031552 in starrocks::vectorized::OlapScanNode::open(starrocks::RuntimeState*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exec/vectorized/olap_scan_node.cpp:68
    #27 0x5e05b9f in starrocks::vectorized::DistinctBlockingNode::open(starrocks::RuntimeState*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp:25
    #28 0x500fc3e in starrocks::PlanFragmentExecutor::_open_internal_vectorized() /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/runtime/plan_fragment_executor.cpp:203
    #29 0x500f32c in starrocks::PlanFragmentExecutor::open() /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/runtime/plan_fragment_executor.cpp:186
    #30 0x4e8eb37 in starrocks::FragmentExecState::execute() /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:193
    #31 0x4e93c00 in starrocks::FragmentMgr::exec_actual(std::shared_ptr<starrocks::FragmentExecState>*, std::function<void (starrocks::PlanFragmentExecutor*)> const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:379
    #32 0x4e9461c in operator() /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:438
    #33 0x4e9d701 in __invoke_impl<void, starrocks::FragmentMgr::exec_plan_fragment(const starrocks::TExecPlanFragmentParams&, const StartSuccCallback&, const FinishCallback&)::<lambda()>&> /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #34 0x4e9d2f2 in __invoke_r<void, starrocks::FragmentMgr::exec_plan_fragment(const starrocks::TExecPlanFragmentParams&, const StartSuccCallback&, const FinishCallback&)::<lambda()>&> /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:110
    #35 0x4e9caa3 in _M_invoke /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:291
    #36 0x3dd7917 in std::function<void ()>::operator()() const /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
    #37 0x52837f5 in starrocks::FunctionRunnable::run() /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:45
    #38 0x52802d3 in starrocks::ThreadPool::dispatch_thread() /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:514
    #39 0x529d91d in void std::__invoke_impl<void, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(std::__invoke_memfun_deref, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:73
    #40 0x529d200 in std::__invoke_result<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>::type std::__invoke<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:95
    #41 0x529c617 in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:416
    #42 0x529b183 in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::operator()<, void>() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:499
    #43 0x5298069 in void std::__invoke_impl<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #44 0x5296031 in std::enable_if<is_invocable_r_v<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:110
    #45 0x52917cc in std::_Function_handler<void (), std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:291
    #46 0x3dd7917 in std::function<void ()>::operator()() const /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
    #47 0x526a856 in starrocks::Thread::supervise_thread(void*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/util/thread.cpp:312
    #48 0x7ff222d1aea4 in start_thread (/lib64/libpthread.so.0+0x7ea4)
    #49 0x7ff22211f8dc in __clone (/lib64/libc.so.6+0xfe8dc)

0x60300077bd4f is located 1 bytes to the left of 32-byte region [0x60300077bd50,0x60300077bd70)
allocated by thread T216 (fragment_mgr) here:
    #0 0x3d67247 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x3dedd90 in __gnu_cxx::new_allocator<unsigned char>::allocate(unsigned long, void const*) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/ext/new_allocator.h:115
    #2 0x3ded1bf in starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> >::allocate(unsigned long) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/util/raw_container.h:44
    #3 0x3de7bbf in std::allocator_traits<starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::allocate(starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> >&, unsigned long) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/alloc_traits.h:314
    #4 0x3de1f6b in std::_Vector_base<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::_M_allocate(unsigned long) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/stl_vector.h:346
    #5 0x3fa40b0 in std::vector<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::_M_default_append(unsigned long) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/vector.tcc:635
    #6 0x3fa04c8 in std::vector<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::resize(unsigned long) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/stl_vector.h:940
    #7 0x88b9f7a in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::ReverseFunction::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1697
    #8 0x88b0075 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction>::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:138
    #9 0x889e35d in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::DealNullableColumnUnaryFunction<starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction> >::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:205
    #10 0x88946c3 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::DealNullableColumnUnaryFunction<starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction> >::evaluate<(starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:211
    #11 0x887bcda in starrocks::vectorized::StringFunctions::reverse(starrocks_udf::FunctionContext*, std::vector<std::shared_ptr<starrocks::vectorized::Column>, std::allocator<std::shared_ptr<starrocks::vectorized::Column> > > const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1710
    #12 0x8138edc in starrocks::vectorized::VectorizedFunctionCallExpr::evaluate(starrocks::ExprContext*, starrocks::vectorized::Chunk*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/vectorized/function_call_expr.cpp:142
    #13 0x76bfe13 in starrocks::ExprContext::evaluate(starrocks::Expr*, starrocks::vectorized::Chunk*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/expr_context.cpp:194
    #14 0x76ca7dd in operator() /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:599
    #15 0x76cb22c in __invoke_impl<void, starrocks::Expr::evaluate_const(starrocks::ExprContext*)::<lambda()> > /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #16 0x76cb1fb in __invoke<starrocks::Expr::evaluate_const(starrocks::ExprContext*)::<lambda()> > /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:95
    #17 0x76cb007 in operator() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:717
    #18 0x76cb02a in operator() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:722
    #19 0x76cb03b in _FUN /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:722
    #20 0x7ff222d1920a in __pthread_once_slow (/lib64/libpthread.so.0+0x620a)

Thread T216 (fragment_mgr) created by T0 here:
    #0 0x3d10f42 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:214
    #1 0x5269caa in starrocks::Thread::start_thread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, unsigned long, scoped_refptr<starrocks::Thread>*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/util/thread.cpp:267
    #2 0x5287e5a in starrocks::Status starrocks::Thread::create<void (starrocks::ThreadPool::*)(), starrocks::ThreadPool*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void (starrocks::ThreadPool::* const&)(), starrocks::ThreadPool* const&, scoped_refptr<starrocks::Thread>*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/util/thread.h:55
    #3 0x5281533 in starrocks::ThreadPool::create_thread() /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:564
    #4 0x527b7d4 in starrocks::ThreadPool::init() /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:253
    #5 0x527848f in starrocks::ThreadPoolBuilder::build(std::unique_ptr<starrocks::ThreadPool, std::default_delete<starrocks::ThreadPool> >*) const /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:82
    #6 0x4e930fa in starrocks::FragmentMgr::FragmentMgr(starrocks::ExecEnv*) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:349
    #7 0x4e1c50f in starrocks::ExecEnv::_init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/runtime/exec_env.cpp:142
    #8 0x4e1ba31 in starrocks::ExecEnv::init(starrocks::ExecEnv*, std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/runtime/exec_env.cpp:118
    #9 0x3da662d in main /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/service/starrocks_main.cpp:212
    #10 0x7ff222043554 in __libc_start_main (/lib64/libc.so.6+0x22554)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/disk1/jenkins/workspace/starrocks_build/cluster-management/resource/starrocks/be/src/gutil/strings/fastmem.h:111 in strings::memcpy_inlined(void*, void const*, unsigned long)
Shadow bytes around the buggy address:
  0x0c06800e7750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06800e7760: fa fa fa fa fa fa fa fa 00 00 00 00 fa fa fa fa
  0x0c06800e7770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06800e7780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06800e7790: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c06800e77a0: fa fa fa fa fa fa fa fa fa[fa]00 00 00 00 fa fa
  0x0c06800e77b0: fd fd fd fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06800e77c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06800e77d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06800e77e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06800e77f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==30311==ABORTING
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_01_ASAN cee9fdd |
+------------------------------+

**Comment by satanson** [comment]
AES_ENCRYPT generate an illegal utf8 string
```
mysql> select AES_ENCRYPT("f", "");
+----------------------+
| aes_encrypt('f', '') |
+----------------------+
| g׻$,]�G�eTÞB�          |
+----------------------+
1 row in set (0.04 sec)

mysql> select reverse(AES_ENCRYPT("f", ""));
ERROR 1064 (HY000): A error occurred: errorCode=2001 errorMessage:Channel inactive error!, host: unknown
```
