### ISSUE TITLE
create view on apache hudi tables

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#32526]
```
StarRocks > show databases;
+----------------------------------+
| Database                         |
+----------------------------------+
| default                          |
| demo_default                     |
| demo_tpc_pg                      |
| hive_zhangyan_ml_25m_orc_zlib    |
| hive_zhangyan_ssb_100g_orc_zlib  |
| hive_zhangyan_tpch_100g_orc_zlib |
| onehouse                         |
| sales_default                    |
| sales_onehouse                   |
| zhangyan_ml_25m_csv              |
| zhangyan_ssb_100g_csv            |
| zhangyan_tpch_100g_csv           |
+----------------------------------+
12 rows in set (0.43 sec)

StarRocks > use demo_tpc_pg;
Database changed
StarRocks > create view demo_tpc_pg.item as select * from public_item_ro;
ERROR 1064 (HY000): Unexpected exception: Unknown database 'demo_tpc_pg'
```

``` from fe.log
2023-10-11 16:53:03,555 WARN (starrocks-mysql-nio-pool-5|327) [StmtExecutor.handleDdlStmt():1416] DDL statement (create view demo_tpc_pg.item as select * from public_item_ro) process failed.
com.starrocks.common.DdlException: Unknown database 'demo_tpc_pg'
        at com.starrocks.common.ErrorReport.reportDdlException(ErrorReport.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.common.ErrorReport.reportDdlException(ErrorReport.java:94) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.createView(LocalMetastore.java:3895) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.createView(GlobalStateMgr.java:3610) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.lambda$visitCreateViewStatement$42(DDLStmtExecutor.java:584) ~[starrocks-fe.jar:?]
        at com.starrocks.common.ErrorReport.wrapWithRuntimeException(ErrorReport.java:112) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitCreateViewStatement(DDLStmtExecutor.java:583) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitCreateViewStatement(DDLStmtExecutor.java:150) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.CreateViewStmt.accept(CreateViewStmt.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor.execute(DDLStmtExecutor.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1390) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:615) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:362) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:476) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:742) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-10-11 16:53:03,557 INFO (starrocks-mysql-nio-pool-5|327) [MetadataMgr.removeQueryMetadata():112] Succeed to deregister query level connector metadata on query id: a4be60ba-6856-11ee-aa63-0242ac110002
```

**Comment by alberttwong** [comment]
select works fine.

```
StarRocks > select * from demo_tpc_pg.public_item_ro limit 10;
+---------------------+-----------------------+--------------------+------------------------+------------------------------------------------------------------------------+------------------------+---------------------------------+--------------------------------+---------------------+--------------+--------------+-------------+-----------+------------------+------------------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+------------+---------------------+------------+--------------+---------------+-------------+---------------+----------------+--------+----------------------+-----------+---------+-------------+--------------+-------------------+
| _hoodie_commit_time | _hoodie_commit_seqno  | _hoodie_record_key | _hoodie_partition_path | _hoodie_file_name                                                            | _change_operation_type | _upstream_event_processed_ts_ms | db_shard_source_partition      | _event_origin_ts_ms | _event_tx_id | _event_lsn   | _event_xmin | i_item_sk | i_item_id        | i_rec_start_date | i_rec_end_date | i_item_desc                                                                                                                                                                            | i_current_price | i_wholesale_cost | i_brand_id | i_brand             | i_class_id | i_class      | i_category_id | i_category  | i_manufact_id | i_manufact     | i_size | i_formulation        | i_color   | i_units | i_container | i_manager_id | i_product_name    |
+---------------------+-----------------------+--------------------+------------------------+------------------------------------------------------------------------------+------------------------+---------------------------------+--------------------------------+---------------------+--------------+--------------+-------------+-----------+------------------+------------------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+------------+---------------------+------------+--------------+---------------+-------------+---------------+----------------+--------+----------------------+-----------+---------+-------------+--------------+-------------------+
| 20231007012701624   | 20231007012701624_0_0 | 907                |                        | dcce3896-8ae5-4a75-966c-42fcbd674eaa-0_0-107-17488_20231007012701624.parquet | r                      |                   1696641988061 | oh_debezium_bootstrap_67b9d9fd |       1696641986428 |        30069 | 159316447424 |        NULL |       907 | AAAAAAAALIDAAAAA | 1997-10-27       | NULL           | German, ultimate personnel want even. Asian, old hospitals could not open far applicable, logical seeds. Years worry schemes. Perhaps li                                               |            1.55 |             0.48 |    9007008 | brandmaxi #8        |          7 | reference    |             9 | Books       |            54 | eseanti        | N/A    | 06579288peru57969840 | smoke     | Pallet  | Unknown     |            5 | ationbarn st      |
| 20231007012701624   | 20231007012701624_0_1 | 3993               |                        | dcce3896-8ae5-4a75-966c-42fcbd674eaa-0_0-107-17488_20231007012701624.parquet | r                      |                   1696641988159 | oh_debezium_bootstrap_67b9d9fd |       1696641986428 |        30069 | 159316447424 |        NULL |      3993 | AAAAAAAAIJPAAAAA | 2000-10-27       | NULL           | Optimistic, western customers see usually special variations. Things bring in a lips; good years should kill with a shops. Really flat months can act minor, new ways. Elegant, specia |            0.77 |             0.39 |    3001002 | amalgexporti #2     |          4 | newborn      |             3 | Children    |           996 | callyn stn st  | large  | 0145plum798630189535 | pale      | Unknown | Unknown     |           41 | prin stn stpri    |
| 20231007012701624   | 20231007012701624_0_2 | 1452               |                        | dcce3896-8ae5-4a75-966c-42fcbd674eaa-0_0-107-17488_20231007012701624.parquet | r                      |                   1696641988068 | oh_debezium_bootstrap_67b9d9fd |       1696641986428 |        30069 | 159316447424 |        NULL |      1452 | AAAAAAAAKKFAAAAA | 2001-10-27       | NULL           | Special patterns could believe very in a chil                                                                                                                                          |            3.04 |             3.74 |    6010004 | maxicorp #5         |          9 | womens watch |             6 | Jewelry     |           285 | antieingable   | N/A    | 80309146273046lawn18 | gainsboro | Pallet  | Unknown     |           57 | ableantieseought  |
| 20231007012701624   | 20231007012701624_0_3 | 3872               |                        | dcce3896-8ae5-4a75-966c-42fcbd674eaa-0_0-107-17488_20231007012701624.parquet | r                      |                   1696641988157 | oh_debezium_bootstrap_67b9d9fd |       1696641986428 |        30069 | 159316447424 |        NULL |      3872 | AAAAAAAAACPAAAAA | 1997-10-27       | 2000-10-26     | Clearly specific russians owe never at all rare days. Recent, political countries get into a patients. Economic masters understand throughout the                                      |            0.98 |             0.55 |    1002001 | importoamalg #1     |          2 | fragrances   |             1 | Women       |            70 | baration       | medium | 5623324520yellow3114 | yellow    | N/A     | Unknown     |           27 | ableationeingpri  |
| 20231007012701624   | 20231007012701624_0_4 | 4961               |                        | dcce3896-8ae5-4a75-966c-42fcbd674eaa-0_0-107-17488_20231007012701624.parquet | r                      |                   1696641988169 | oh_debezium_bootstrap_67b9d9fd |       1696641986428 |        30069 | 159316447424 |        NULL |      4961 | AAAAAAAAAGDBAAAA | 1999-10-28       | 2001-10-26     | Chiefly long hours shall not remain prisons. International, central interests cause firm, dramatic abilities. Sweet tea                                                                |            0.39 |             7.15 |    1004001 | amalgamalg #2       |          4 | dresses      |             1 | Women       |            17 | oughtcallyable | petite | 71540914red637627105 | rosy      | Case    | Unknown     |           38 | oughtcallyn stese |
| 20231007012701624   | 20231007012701624_0_5 | 2783               |                        | dcce3896-8ae5-4a75-966c-42fcbd674eaa-0_0-107-17488_20231007012701624.parquet | r                      |                   1696641988086 | oh_debezium_bootstrap_67b9d9fd |       1696641986428 |        30069 | 159316447424 |        NULL |      2783 | AAAAAAAAONKAAAAA | 1999-10-28       | 2001-10-26     | Only full efforts might not improve american famil                                                                                                                                     |            2.57 |             2.15 |    1004001 | maxiunivamalg #13   |          4 | televisions  |            10 | Electronics |           375 | antiationpri   | N/A    | 534604tan90132211720 | rosy      | Carton  | Unknown     |           19 | prieingationable  |
| 20231007012701624   | 20231007012701624_0_6 | 3630               |                        | dcce3896-8ae5-4a75-966c-42fcbd674eaa-0_0-107-17488_20231007012701624.parquet | r                      |                   1696641988154 | oh_debezium_bootstrap_67b9d9fd |       1696641986428 |        30069 | 159316447424 |        NULL |      3630 | AAAAAAAAMCOAAAAA | 2001-10-27       | NULL           | Other, social guests might not leave rooms; times will change more away different pounds; too international conditions might verify more real typical universit                        |            2.95 |             2.35 |    6015005 | corpamalgamalg #10  |         16 | wireless     |            10 | Electronics |           259 | n stantiable   | N/A    | 89goldenrod050723339 | maroon    | Oz      | Unknown     |           66 | barpricallypri    |
| 20231007012701624   | 20231007012701624_0_7 | 1331               |                        | dcce3896-8ae5-4a75-966c-42fcbd674eaa-0_0-107-17488_20231007012701624.parquet | r                      |                   1696641988066 | oh_debezium_bootstrap_67b9d9fd |       1696641986428 |        30069 | 159316447424 |        NULL |      1331 | AAAAAAAACDFAAAAA | 1999-10-28       | 2001-10-26     | Public relationships might reach also. Different, alternative effects must not trip members. Important, chief sisters bring wonderful,                                                 |            1.58 |             2.54 |    6008004 | namelesscorp #4     |          8 | mens watch   |             6 | Jewelry     |           328 | eingablepri    | N/A    | 80708608561red961966 | sky       | Carton  | Unknown     |           38 | oughtpripriought  |
| 20231007012701624   | 20231007012701624_0_8 | 3751               |                        | dcce3896-8ae5-4a75-966c-42fcbd674eaa-0_0-107-17488_20231007012701624.parquet | r                      |                   1696641988156 | oh_debezium_bootstrap_67b9d9fd |       1696641986428 |        30069 | 159316447424 |        NULL |      3751 | AAAAAAAAHKOAAAAA | 1997-10-27       | NULL           | Studies may not spare finally nearby, sorry authorities. Servants might imagine a bit gold families. Arts cannot rely safe, aware others; new, realistic co                            |            0.27 |             0.15 |    9013008 | exportiunivamalg #8 |         13 | self-help    |             9 | Books       |            95 | antin st       | N/A    | 4snow703834274866883 | ivory     | Pound   | Unknown     |           63 | oughtantiationpri |
| 20231007012701624   | 20231007012701624_0_9 | 2420               |                        | dcce3896-8ae5-4a75-966c-42fcbd674eaa-0_0-107-17488_20231007012701624.parquet | r                      |                   1696641988080 | oh_debezium_bootstrap_67b9d9fd |       1696641986428 |        30069 | 159316447424 |        NULL |      2420 | AAAAAAAAEHJAAAAA | 1997-10-27       | 2000-10-26     | Running, special problems shall lose                                                                                                                                                   |            3.88 |             2.63 |    7013001 | exportinameless #1  |         13 | wallpaper    |             7 | Home        |           856 | callyantieing  | N/A    | 12tan038991165685380 | tan       | Oz      | Unknown     |           19 | barableeseable    |
+---------------------+-----------------------+--------------------+------------------------+------------------------------------------------------------------------------+------------------------+---------------------------------+--------------------------------+---------------------+--------------+--------------+-------------+-----------+------------------+------------------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+------------------+------------+---------------------+------------+--------------+---------------+-------------+---------------+----------------+--------+----------------------+-----------+---------+-------------+--------------+-------------------+
10 rows in set (7.65 sec)
```

**Comment by 0akarma** [comment]
I think it is because both `VIEW` and  `MATERIALIZED VIEW`  are not supported to store in catalog database. 
It will be succeeded when you create view in the `default_catalog.existed_db`. 
Here are my code that works on paimon catalog table
```
StarRocks > use default_catalog.dev
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed

StarRocks > CREATE VIEW test_view (_id, raw)
    -> AS SELECT _id,`raw` FROM  paimon_s3_dev.`default`.table_name;
ERROR 1064 (HY000): Unexpected exception: Table 'test_view' already exists
```
