### ISSUE TITLE
starrocks hangs when external catalog's metastore is not accessible

### ISSUE THREAD

**Issue by neokjchen** [StarRocks/starrocks#33110]
### Steps to reproduce the behavior (Required)
1. Create external catalog, in which the metastore is not accessible
```
CREATE EXTERNAL CATALOG iceberg_rest_s3 PROPERTIES (
        "type" = "iceberg",
        "aws.s3.use_instance_profile"="false",
        "aws.s3.enable_ssl" = "false",
        "aws.s3.access_key" = "aaaa",
        "aws.s3.secret_key" = "+CEbLIwFc43G",
        "aws.s3.region" = "us-east-1",
        "uri" = "http://3.221.233.15:8181",
        "warehouse" = "",
        "security" = "",
        "session" = "",
        "credential" = "",
        "hive.metastore.type" = "rest",
        "iceberg.catalog.type" = "rest"
);
```
http://3.221.233.15:8181 is not accessible
2. set catalog as used.
`set catalog iceberg_rest_s3;
`
3. show database list.
`show databases;
`

### Expected behavior (Required)
Starrocks will return error message in a reasonable time (such as 15s) and can be set by connection-timeout like parameters.

### Real behavior (Required)
Starrocks hangs for near 3 minutes. and return `ERROR 1064 (HY000): Error occurred while processing GET request
`
### StarRocks version (Required)
3.1.1-e0229632f9

FE error message likes follow
```
2023-08-08 12:58:01,307 WARN (starrocks-mysql-nio-pool-3|197) [StmtExecutor.execute():651] execute Exception, sql show databases
org.apache.iceberg.exceptions.RESTException: Error occurred while processing GET request
        at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:305) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:220) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.rest.HTTPClient.get(HTTPClient.java:321) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.rest.RESTSessionCatalog.fetchConfig(RESTSessionCatalog.java:810) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.rest.RESTSessionCatalog.initialize(RESTSessionCatalog.java:165) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.rest.RESTCatalog.initialize(RESTCatalog.java:69) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:239) ~[iceberg-core-1.2.1.jar:?]
        at com.starrocks.connector.iceberg.rest.IcebergRESTCatalog.<init>(IcebergRESTCatalog.java:87) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergConnector.buildIcebergNativeCatalog(IcebergConnector.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergConnector.getNativeCatalog(IcebergConnector.java:103) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergConnector.getMetadata(IcebergConnector.java:96) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr$QueryMetadatas.getConnectorMetadata(MetadataMgr.java:358) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.getOptionalMetadata(MetadataMgr.java:91) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.listDbNames(MetadataMgr.java:118) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ShowExecutor.handleShowDb(ShowExecutor.java:802) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ShowExecutor.execute(ShowExecutor.java:267) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleShow(StmtExecutor.java:1291) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:605) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:360) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:474) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:740) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://3.221.233.125:8181 [/3.221.233.125] failed: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.lambda$connectSocket$0(PlainConnectionSocketFactory.java:85) ~[httpclient5-5.2.1.jar:5.2.1]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:84) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.socket.ConnectionSocketFactory.connectSocket(ConnectionSocketFactory.java:113) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:123) ~[httpclient5-5.2.1.jar:5.2.1]
        at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:268) ~[iceberg-core-1.2.1.jar:?]
        ... 24 more


```

**Comment by Smith-Cruise** [comment]
RestCatalog's HTTPClient is provided by Iceberg SDK, but it looks like it didn't expose any timeout API to us, so we are hard to control it's behavior.
