### ISSUE TITLE
select into outfile to oss failed

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#3328]
### Steps to reproduce the behavior (Required)
1.
```
CREATE TABLE `duplicate_table_with_null` (
    `k1`  date,
    `k2`  datetime,
    `k3`  char(20),
    `k4`  varchar(20),
    `k5`  boolean,
    `k6`  tinyint,
    `k7`  smallint,
    `k8`  int,
    `k9`  bigint,
    `k10` largeint,
    `k11` float,
    `k12` double,
    `k13` decimal(27,9)
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3
PROPERTIES (
    "replication_num" = "1",
    "storage_format" = "v2"
);
```
2. load data
3.
 ```
SELECT * FROM duplicate_table_without_null1 
INTO OUTFILE "oss://dorisdb-data/outfile/outfile_res_" 
FORMAT AS CSV 
PROPERTIES (     "broker.name" = "hdfs_broker",     "broker.username" = "dorisdb",    "broker.fs.oss.accessKeyId" = "xxxxxxxxxx" = "","broker.fs.oss.endpoint" = "xxxxxxxxxx","column_separator" = ",",     "line_delimiter" = "\n" );
```

### Expected behavior (Required)
query ok
### Real behavior (Required)
`Broker storage service error, the fd is not owned by client null, cause by: null`
broker's log:
```
2022-02-11 20:51:32  [ TThreadPoolServer WorkerProcess-%d:179849925 ] - [ ERROR ]  Thrift Error occurred during processing of message.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)
	at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:213)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:60)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:208)
	... 6 more
2022-02-11 20:51:32  [ TThreadPoolServer WorkerProcess-%d:179849925 ] - [ INFO ]  receive a check path request, request detail: TBrokerCheckPathExistRequest(version:VERSION_ONE, path:oss://dorisdb-data/outfile/outfile_res_1.csv, properties:{fs.oss.accessKeyId=, fs.oss.accessKeySecret=, fs.oss.endpoint=oss-cn-zhangjiakou.aliyuncs.com, username=dorisdb})
2022-02-11 20:51:32  [ TThreadPoolServer WorkerProcess-%d:179849925 ] - [ WARN ]  Error closing output stream.
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.apache.thrift.transport.TIOStreamTransport.close(TIOStreamTransport.java:156)
	at org.apache.thrift.transport.TSocket.close(TSocket.java:252)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-02-11 20:51:32  [ TThreadPoolServer WorkerProcess-%d:179849936 ] - [ INFO ]  receive a open writer request, request detail: TBrokerOpenWriterRequest(version:VERSION_ONE, path:oss://dorisdb-data/outfile/outfile_res_1.csv, openMode:APPEND, clientId:172.26.92.141:9560, properties:{fs.oss.accessKeyId=, fs.oss.accessKeySecret=, fs.oss.endpoint=, username=dorisdb})
2022-02-11 20:51:32  [ TThreadPoolServer WorkerProcess-%d:179849976 ] - [ INFO ]  receive a close writer request, request detail: TBrokerCloseWriterRequest(version:VERSION_ONE, fd:TBrokerFD(high:-1807493690108327935, low:-6803353052603831993))
2022-02-11 20:57:03  [ pool-1-thread-1:180180343 ] - [ INFO ]  file system BrokerFileSystem [identity=com.starrocks.broker.hdfs.FileSystemIdentity@a7475a88, dfsFileSystem=org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem@19aedc5e, fileSystemId=82c1bc03-8624-4aa6-b021-8c097831fee3] is expired, close and remove it
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
branch-2.1 release
a87e76c
```

**Comment by stdpain** [comment]
It seems cause by rpc timeout
