### ISSUE TITLE
Start fe failed when creating or dropping database concurrently

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#3357]
### Steps to reproduce the behavior (Required)
Execute the following SQL concurrently
```sql
drop database if exists test_select_slt_good_7_test;
create database if not exists test_select_slt_good_7_test;
use database test_select_slt_good_7_test;
CREATE TABLE tab0(col0 INTEGER, col1 INTEGER, col2 INTEGER) DUPLICATE KEY(`col0`) DISTRIBUTED BY HASH(col0) BUCKETS 10 PROPERTIES ("replication_num" = "1");
CREATE TABLE tab1(col0 INTEGER, col1 INTEGER, col2 INTEGER) DUPLICATE KEY(`col0`) DISTRIBUTED BY HASH(col0) BUCKETS 10 PROPERTIES ("replication_num" = "1");
CREATE TABLE tab2(col0 INTEGER, col1 INTEGER, col2 INTEGER) DUPLICATE KEY(`col0`) DISTRIBUTED BY HASH(col0) BUCKETS 10 PROPERTIES ("replication_num" = "1");
```

### Expected behavior (Required)
System runs normally.

### Real behavior (Required)
Start fe failed.
```java
2022-02-14 11:36:47,303 ERROR (stateListener|70) [EditLog.loadJournal():830] Operation Type 100
java.lang.NullPointerException: null
        at com.starrocks.transaction.DatabaseTransactionMgr.updateCatalogAfterCommitted(DatabaseTransactionMgr.java:1276) ~[starrocks-fe.jar:?]
        at com.starrocks.transaction.DatabaseTransactionMgr.replayUpsertTransactionState(DatabaseTransactionMgr.java:1446) ~[starrocks-fe.jar:?]
        at com.starrocks.transaction.GlobalTransactionMgr.replayUpsertTransactionState(GlobalTransactionMgr.java:498) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:596) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2494) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.transferToMaster(Catalog.java:1244) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.access$800(Catalog.java:289) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$4.runOneCycle(Catalog.java:2411) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - all version

**Comment by gengjun-git** [comment]
1. The reason that causes NullPointerException is non-existent of table 12333049 in database doris_test_select_slt_good_7_test.

![image](https://user-images.githubusercontent.com/54172532/154052611-5c53d1ff-b2d5-4c65-b62e-41ce771a289b.png)
![image](https://user-images.githubusercontent.com/54172532/154053182-b8bf4a0c-5b3a-4d8f-bd54-e6e617dc806a.png)

2. The reason that causes table 12333049 lost from database doris_test_select_slt_good_7_test is creating the same name table in the database. 
![image](https://user-images.githubusercontent.com/54172532/154059615-9f8c346c-0d6a-42a9-ae9c-13f48c1cf9d4.png)
![image](https://user-images.githubusercontent.com/54172532/154059727-28c00c94-0356-4ee3-aaf4-551c84ce9bae.png)

3. The reason for the duplicate creation of tables with the same name is that the database doris_test_select_slt_good_7_test was recreated when the table tab1-12324992 was created. 
![image](https://user-images.githubusercontent.com/54172532/154070753-e312b3b3-b957-40f6-a3a7-46d839088a7b.png)
we can see that the time interval of creating table tab1 is [00:46:23,781~00:46:28,903]. The drop and create database doris_test_select_slt_good_7_test occurred during this time period.
Table tab1-12324992 was created into the dropped database, and table tab-12333049 was created into the newly created database. But only the name of the database is recorded in the create table log. When replaying the create table log, only one table can be created into the database. So this will cause the lost of table.
