### ISSUE TITLE
[paimon connector] query error from paimon table with struct type

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#33636]
### Steps to reproduce the behavior (Required)
1. create paimon table in hive:
```
create table struct_mix_test
(col_int int,
col_string string,
col_struct struct<c_int:int,c_float:float,c_double:double,c_char:char(30),c_varchar:varchar(200),c_date:date,c_timestamp:timestamp,c_boolean:boolean>)
STORED BY 'org.apache.paimon.hive.PaimonStorageHandler'
TBLPROPERTIES (
    'file.format' = 'parquet',
    'file.compression' = 'gzip'
);


insert into struct_mix_test select -577841796, "Vertcoin", named_struct("c_int",cast(-951098998 as int),"c_float",cast(9291.128482 as float),"c_double",cast(-0.5081 as double),"c_char",cast("+1-173-021-1921x027" as char(30)),"c_varchar",cast("Mozilla/5.0 (Windows; U; Windows 95) AppleWebKit/534.20.1 (KHTML, like Gecko) Version/5.1 Safari/534.20.1" as varchar(200)),"c_date",cast("2001-02-14" as date),"c_timestamp",cast("1974-09-04 09:14:34" as timestamp),"c_boolean",cast(0 as boolean));
insert into struct_mix_test select -1787049426, "Litecoin", named_struct("c_int",cast(1438567980 as int),"c_float",cast(-4410.9022094 as float),"c_double",cast(-64384.5174 as double),"c_char",cast("001-143-886-2126" as char(30)),"c_varchar",cast("Mozilla/5.0 (compatible; MSIE 9.0; Windows 98; Trident/5.1)" as varchar(200)),"c_date",cast("1982-09-24" as date),"c_timestamp",cast("1982-09-28 18:34:45" as timestamp),"c_boolean",cast(0 as boolean));
insert into struct_mix_test select -1915459235, "Dash", named_struct("c_int",cast(-384319491 as int),"c_float",cast(-2186.76545286668 as float),"c_double",cast(0.6431 as double),"c_char",cast("8982269293" as char(30)),"c_varchar",cast("Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_1 rv:6.0; hy-AM) AppleWebKit/533.49.6 (KHTML, like Gecko) Version/5.0.5 Safari/533.49.6" as varchar(200)),"c_date",cast("2020-09-08" as date),"c_timestamp",cast("2007-05-29 17:39:43" as timestamp),"c_boolean",cast(0 as boolean));
insert into struct_mix_test select -1735632402, "Bitcoin C", named_struct("c_int",cast(277625218 as int),"c_float",cast(6902.5752 as float),"c_double",cast(-13483.311 as double),"c_char",cast("961.094.9421" as char(30)),"c_varchar",cast("Opera/9.89.(Windows NT 5.0; aa-DJ) Presto/2.9.164 Version/10.00" as varchar(200)),"c_date",cast("2000-12-08" as date),"c_timestamp",cast("1973-05-05 17:48:18" as timestamp),"c_boolean",cast(0 as boolean));
insert into struct_mix_test select 314883698, "Vertcoin", named_struct("c_int",cast(-1837490365 as int),"c_float",cast(-5745.203 as float),"c_double",cast(-6156.496 as double),"c_char",cast("+1-290-180-1867x8570" as char(30)),"c_varchar",cast("Mozilla/5.0 (Windows NT 5.0; sr-ME; rv:1.9.2.20) Gecko/5637-01-07 16:16:36 Firefox/5.0" as varchar(200)),"c_date",cast("1970-02-16" as date),"c_timestamp",cast("2000-02-16 09:49:47" as timestamp),"c_boolean",cast(0 as boolean));
```

2. create paimon catalog in sr:
```
mysql> create external catalog paimon_catalog_5c6b3768_7272_11ee_b05d_00163e0e550b
    ->                 PROPERTIES(
    ->                 "type" = "paimon",
    ->                 "paimon.catalog.type"="hive",
    ->                 "paimon.catalog.warehouse"="hdfs://****:9000/user/hive/warehouse",
    ->                 "hive.metastore.uris" = "thrift://****:9083");
```

3. select paimon table:
```
mysql> select * from struct_mix_test;
ERROR 1064 (HY000): Failed to call the nextChunkOffHeap method of off-heap table scanner. java exception details: java.io.IOException: Failed to get the next off-heap table chunk of paimon.
	at com.starrocks.paimon.reader.PaimonSplitScanner.getNext(PaimonSplitScanner.java:219)
	at com.starrocks.jni.connector.ConnectorScanner.getNextOffHeapChunk(ConnectorScanner.java:101)
Caused by: java.lang.ClassCastException: class org.apache.paimon.data.columnar.heap.HeapLongVector cannot be cast to class org.apache.paimon.data.columnar.Ti
```

fe.warn.log:
```
2023-10-25 14:44:07,635 WARN (thrift-server-pool-5|143) [DefaultCoordinator.updateFragmentExecStatus():865] exec state report failed status=errorCode INTERNAL_ERROR Failed to call the nextChunkOffHeap method of off-heap table scanner. java exception details: java.io.IOException: Failed to get the next off-heap table chunk of paimon.
        at com.starrocks.paimon.reader.PaimonSplitScanner.getNext(PaimonSplitScanner.java:219)
        at com.starrocks.jni.connector.ConnectorScanner.getNextOffHeapChunk(ConnectorScanner.java:101)
Caused by: java.lang.ClassCastException: class org.apache.paimon.data.columnar.heap.HeapLongVector cannot be cast to class org.apache.paimon.data.columnar.TimestampColumnVector (org.apache.paimon.data.columnar.heap.HeapLongVector and org.apache.paimon.data.columnar.TimestampColumnVector are in unnamed module of loader com.starrocks.utils.loader.ChildFirstClassLoader @d59970a)
        at org.apache.paimon.data.columnar.VectorizedColumnBatch.getTimestamp(VectorizedColumnBatch.java:120)
        at org.apache.paimon.data.columnar.ColumnarRow.getTimestamp(ColumnarRow.java:133)
        at org.apache.paimon.utils.InternalRowUtils.get(InternalRowUtils.java:171)
        at com.starrocks.paimon.reader.PaimonColumnValue.unpackStruct(PaimonColumnValue.java:134)
        at com.starrocks.jni.connector.OffHeapColumnVector.appendValue(OffHeapColumnVector.java:533)
        at com.starrocks.jni.connector.OffHeapTable.appendData(OffHeapTable.java:95)
        at com.starrocks.jni.connector.ConnectorScanner.appendData(ConnectorScanner.java:86)
        at com.starrocks.paimon.reader.PaimonSplitScanner.getNext(PaimonSplitScanner.java:209)
        ... 1 more
, query_id=e315763c-7301-11ee-9468-00163e1948d2, instance_id=e315763c-7301-11ee-9468-00163e1948d4
2023-10-25 14:44:07,635 WARN (thrift-server-pool-5|143) [DefaultCoordinator.updateStatus():683] one instance report fail throw updateStatus(), need cancel. job id: -1, query id: e315763c-7301-11ee-9468-00163e1948d2, instance id: e315763c-7301-11ee-9468-00163e1948d4
2023-10-25 14:44:07,636 WARN (thrift-server-pool-17|160) [DefaultCoordinator.updateFragmentExecStatus():865] exec state report failed status=errorCode CANCELLED InternalError, query_id=e315763c-7301-11ee-9468-00163e1948d2, instance_id=e315763c-7301-11ee-9468-00163e1948d3
2023-10-25 14:44:07,637 WARN (starrocks-mysql-nio-pool-7|248) [DefaultCoordinator.getNext():705] get next fail, need cancel. status errorCode CANCELLED InternalError, query id: e315763c-7301-11ee-9468-00163e1948d2
2023-10-25 14:44:07,637 WARN (starrocks-mysql-nio-pool-7|248) [DefaultCoordinator.getNext():731] query failed: Failed to call the nextChunkOffHeap method of off-heap table scanner. java exception details: java.io.IOException: Failed to get the next off-heap table chunk of paimon.
        at com.starrocks.paimon.reader.PaimonSplitScanner.getNext(PaimonSplitScanner.java:219)
        at com.starrocks.jni.connector.ConnectorScanner.getNextOffHeapChunk(ConnectorScanner.java:101)
Caused by: java.lang.ClassCastException: class org.apache.paimon.data.columnar.heap.HeapLongVector cannot be cast to class org.apache.paimon.data.columnar.TimestampColumnVector (org.apache.paimon.data.columnar.heap.HeapLongVector and org.apache.paimon.data.columnar.TimestampColumnVector are in unnamed module of loader com.starrocks.utils.loader.ChildFirstClassLoader @d59970a)
        at org.apache.paimon.data.columnar.VectorizedColumnBatch.getTimestamp(VectorizedColumnBatch.java:120)
        at org.apache.paimon.data.columnar.ColumnarRow.getTimestamp(ColumnarRow.java:133)
        at org.apache.paimon.utils.InternalRowUtils.get(InternalRowUtils.java:171)
        at com.starrocks.paimon.reader.PaimonColumnValue.unpackStruct(PaimonColumnValue.java:134)
        at com.starrocks.jni.connector.OffHeapColumnVector.appendValue(OffHeapColumnVector.java:533)
        at com.starrocks.jni.connector.OffHeapTable.appendData(OffHeapTable.java:95)
        at com.starrocks.jni.connector.ConnectorScanner.appendData(ConnectorScanner.java:86)
        at com.starrocks.paimon.reader.PaimonSplitScanner.getNext(PaimonSplitScanner.java:209)
        ... 1 more
```

### Expected behavior (Required)
return the right result

### Real behavior (Required)
error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
main-71783f0
```

**Comment by miomiocat** [comment]
Can this table be queried correctly using spark/hive?
