### ISSUE TITLE
Iceberg doesn't work with Unified Catalog in the master branch

### ISSUE THREAD

**Issue by Gatsby-Lee** [StarRocks/starrocks#33714]
I've tested the Unified Catalog feature on the master branch.
It works for Hudi Table, but it doesn't work for Iceberg.

The more interesting thing is

- Hudi type specific catalog still works.
- But, Iceberg type specific catalog doesn't work although it used to work.

### Steps to reproduce the behavior (Required)
```
# newly created - unified
CREATE EXTERNAL CATALOG `ft_datalake_unified`
PROPERTIES (
"type"  =  "unified",
"enable_metastore_cache"  =  "true",
"enable_remote_file_cache"  =  "false",
--
"aws.glue.use_aws_sdk_default_behavior"  =  "true",
"aws.s3.region"  =  "us-west-2",
"aws.glue.region"  =  "us-west-2",
"aws.s3.use_aws_sdk_default_behavior"  =  "true",
"unified.metastore.type"  =  "glue"
)
```

```
CREATE EXTERNAL CATALOG `ft_datalake_no_cache_iceberg`
PROPERTIES ("aws.glue.use_aws_sdk_default_behavior"  =  "true",
"enable_remote_file_cache"  =  "false",
"aws.s3.region"  =  "us-west-2",
"aws.glue.region"  =  "us-west-2",
"type"  =  "iceberg",
"aws.s3.use_aws_sdk_default_behavior"  =  "true",
"iceberg.catalog.type"  =  "glue",
"enable_metastore_cache"  =  "false"
)
```

### Expected behavior (Required)
The unified catalog should work for hive, hudi, and iceberg table.

### Real behavior (Required)
Failed with exception msg
```
2023-10-26 00:03:40,883 ERROR (starrocks-mysql-nio-pool-238|8724) [MetadataMgr.getPrunedPartitions():350] Failed to getPrunedPartitions on [ft_datalake_no_cache_iceberg.Table [id=100008748, name=metrics__servicemeta_model_serving, type=ICEBERG]]
com.starrocks.connector.exception.StarRocksConnectorException: date literal [19645] is invalid
	at com.starrocks.connector.iceberg.IcebergMetadata.getPrunedPartitions(IcebergMetadata.java:320) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.CatalogConnectorMetadata.getPrunedPartitions(CatalogConnectorMetadata.java:138) ~[starrocks-fe.jar:?]
	at com.starrocks.server.MetadataMgr.getPrunedPartitions(MetadataMgr.java:348) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rewrite.OptExternalPartitionPruner.computePartitionInfo(OptExternalPartitionPruner.java:320) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rewrite.OptExternalPartitionPruner.prunePartitionsImpl(OptExternalPartitionPruner.java:124) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rewrite.OptExternalPartitionPruner.prunePartitions(OptExternalPartitionPruner.java:79) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.transformation.ExternalScanPartitionPruneRule.transform(ExternalScanPartitionPruneRule.java:56) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:76) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.execute(RewriteTreeTask.java:59) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:65) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.ruleRewriteOnlyOnce(Optimizer.java:701) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:384) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.rewriteAndValidatePlan(Optimizer.java:462) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:178) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:132) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:148) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.planQuery(StatementPlanner.java:123) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:98) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:63) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:487) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:376) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:568) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:847) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-10-26 00:03:40,884 WARN (starrocks-mysql-nio-pool-238|8724) [OptExternalPartitionPruner.prunePartitionsImpl():126] HMS table partition prune failed : 
com.starrocks.connector.exception.StarRocksConnectorException: date literal [19645] is invalid
	at com.starrocks.connector.iceberg.IcebergMetadata.getPrunedPartitions(IcebergMetadata.java:320) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.CatalogConnectorMetadata.getPrunedPartitions(CatalogConnectorMetadata.java:138) ~[starrocks-fe.jar:?]
	at com.starrocks.server.MetadataMgr.getPrunedPartitions(MetadataMgr.java:348) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rewrite.OptExternalPartitionPruner.computePartitionInfo(OptExternalPartitionPruner.java:320) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rewrite.OptExternalPartitionPruner.prunePartitionsImpl(OptExternalPartitionPruner.java:124) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rewrite.OptExternalPartitionPruner.prunePartitions(OptExternalPartitionPruner.java:79) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.transformation.ExternalScanPartitionPruneRule.transform(ExternalScanPartitionPruneRule.java:56) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:76) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.execute(RewriteTreeTask.java:59) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:65) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.ruleRewriteOnlyOnce(Optimizer.java:701) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:384) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.rewriteAndValidatePlan(Optimizer.java:462) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:178) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:132) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:148) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.planQuery(StatementPlanner.java:123) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:98) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:63) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:487) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:376) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:568) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:847) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-10-26 00:03:40,884 WARN (starrocks-mysql-nio-pool-238|8724) [StmtExecutor.execute():505] New planner error: /* ApplicationName=DBeaver 23.2.2 - SQLEditor  */ SELECT count(*) as count FROM ft_datalake_no_cache_iceberg.ft_prod_analytics.metrics__servicemeta_model_serving where ml_task='chat_generation'
LIMIT 0, 200
com.starrocks.sql.common.StarRocksPlannerException: date literal [19645] is invalid
	at com.starrocks.sql.optimizer.rewrite.OptExternalPartitionPruner.prunePartitionsImpl(OptExternalPartitionPruner.java:127) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rewrite.OptExternalPartitionPruner.prunePartitions(OptExternalPartitionPruner.java:79) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.transformation.ExternalScanPartitionPruneRule.transform(ExternalScanPartitionPruneRule.java:56) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:76) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.execute(RewriteTreeTask.java:59) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:65) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.ruleRewriteOnlyOnce(Optimizer.java:701) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:384) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.rewriteAndValidatePlan(Optimizer.java:462) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:178) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:132) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:148) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.planQuery(StatementPlanner.java:123) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:98) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:63) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:487) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:376) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:568) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:847) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### StarRocks version (Required)
- 2023-10-24 master branch

**Comment by letian-jiang** [comment]
An issue of iceberg connector in `main`

**Comment by stephen-shelby** [comment]
@Gatsby-Lee Thanks for your issue. I'm fixing it. I want to know what's your table schema. which is partition column?

**Comment by Gatsby-Lee** [comment]
@stephen-shelby 
Thank you for taking a look.

here is the shorten version of the table schema

```
CREATE TABLE failed_table_schema (
  org_id string,
  ml_task string,
  event_created_datetime_utc_ts timestamp,
  model_id string)
PARTITIONED BY (`ml_task`, day(`event_created_datetime_utc_ts`))
LOCATION '<s3_path>'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='PARQUET',
  'write_compression'='ZSTD'
);
```

**Comment by Gatsby-Lee** [comment]
@stephen-shelby 
how is your testing?
