### ISSUE TITLE
hive/iceberg external table query failed with OSS file system

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#3416]
## Enhancement
```
1.hive external table with OSS file system, query error：
mysql> select count(*) from customer;
ERROR 1064 (HY000): com.starrocks.common.DdlException: get partition detail failed: com.starrocks.common.DdlException: get hive partition meta data failed: dorisdb-data: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECR

fe.log：
2022-02-16 14:54:05,863 WARN (starrocks-mysql-nio-pool-0|144) [StmtExecutor.execute():305] New planner error: select * from customer limit 5
com.starrocks.sql.common.StarRocksPlannerException: com.starrocks.common.DdlException: get partition detail failed: com.starrocks.common.DdlException: get hive partition meta data failed: dorisdb-data: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.getTableRowCount(StatisticsCalculator.java:502) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeHiveScanNode(StatisticsCalculator.java:263) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalHiveScan(StatisticsCalculator.java:250) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalHiveScan(StatisticsCalculator.java:124) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalHiveScanOperator.accept(LogicalHiveScanOperator.java:123) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:140) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:40) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:130) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:93) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:80) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:47) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:291) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

2.iceberg external table with OSS file system, BE crash when execute select:
*** Aborted at 1644986009 (unix time) try "date -d @1644986009" if you are using GNU date ***
PC: @     0x7f73024eb387 __GI_raise
*** SIGABRT (@0x3ef000067ae) received by PID 26542 (TID 0x7f72a7b54700) from PID 26542; stack trace: ***
    @          0x3b6eee2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f7303420630 (unknown)
    @     0x7f73024eb387 __GI_raise
    @     0x7f73024eca78 __GI_abort
    @          0x174d497 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x5474646 __cxxabiv1::__terminate()
    @          0x54746b1 std::terminate()
    @          0x5474804 __cxa_throw
    @          0x174ef8b std::__throw_logic_error()
    @          0x3136b4a std::__cxx11::basic_string<>::_M_construct<>()
    @          0x313a32f starrocks::S3Client::S3Client()
    @          0x30628d3 starrocks::create_hdfs_fs_handle()
    @          0x3062c11 starrocks::HdfsFsCache::get_connection()
    @          0x25d1ca6 starrocks::vectorized::HdfsScanNode::_find_and_insert_hdfs_file()
    @          0x25d4788 starrocks::vectorized::HdfsScanNode::open()
    @          0x1dfe77b starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1dff467 starrocks::PlanFragmentExecutor::open()
    @          0x1d9cef2 starrocks::FragmentExecState::execute()
    @          0x1da142c starrocks::FragmentMgr::exec_actual()
    @          0x1ed15d9 starrocks::ThreadPool::dispatch_thread()
    @          0x1ecd198 starrocks::Thread::supervise_thread()
    @     0x7f7303418ea5 start_thread
    @     0x7f73025b38dd __clone
    @                0x0 (unknown)
```

**Comment by dirtysalt** [comment]
I think FE error message is acceptable?
