### ISSUE TITLE
Query Hive default database with catalog and database name got error.

### ISSUE THREAD

**Issue by FrommyMind** [StarRocks/starrocks#34673]
### Steps to reproduce the behavior (Required)
1. create Hive catalog
2. query Hive table through， catalog_name.db.tablename
3. query default database, got exeption

### Expected behavior (Required)
query default database as others .
### Real behavior (Required)
query default database got errr
```java
com.starrocks.sql.parser.ParsingException: Getting syntax error at line 1, column 20. Detail message: No viable statement for input 'hive0.default'.
```

Just change the [test](https://github.com/StarRocks/starrocks/blob/main/fe/fe-core/src/test/java/com/starrocks/connector/hive/HiveViewTest.java#L46)
use default replace tpch.
and run the test, will got this error.
``` java

com.starrocks.sql.parser.ParsingException: Getting syntax error at line 1, column 20. Detail message: No viable statement for input 'hive0.default'.

	at com.starrocks.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:40)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at com.starrocks.sql.parser.SqlParser$1.reportNoViableAlternative(SqlParser.java:193)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at com.starrocks.sql.parser.StarRocksParser.relationPrimary(StarRocksParser.java:33664)
	at com.starrocks.sql.parser.StarRocksParser.relation(StarRocksParser.java:33069)
	at com.starrocks.sql.parser.StarRocksParser.relations(StarRocksParser.java:32985)
	at com.starrocks.sql.parser.StarRocksParser.fromClause(StarRocksParser.java:32106)
	at com.starrocks.sql.parser.StarRocksParser.querySpecification(StarRocksParser.java:31967)
	at com.starrocks.sql.parser.StarRocksParser.queryPrimary(StarRocksParser.java:31478)
	at com.starrocks.sql.parser.StarRocksParser.queryNoWith(StarRocksParser.java:31184)
	at com.starrocks.sql.parser.StarRocksParser.queryRelation(StarRocksParser.java:31061)
	at com.starrocks.sql.parser.StarRocksParser.queryStatement(StarRocksParser.java:30993)
	at com.starrocks.sql.parser.StarRocksParser.statement(StarRocksParser.java:1429)
	at com.starrocks.sql.parser.StarRocksParser.singleStatement(StarRocksParser.java:732)
	at com.starrocks.sql.parser.StarRocksParser.sqlStatements(StarRocksParser.java:625)
	at com.starrocks.sql.parser.SqlParser.parseWithStarRocksDialect(SqlParser.java:102)
	at com.starrocks.sql.parser.SqlParser.parse(SqlParser.java:64)
	at com.starrocks.utframe.UtFrameUtils.getPlanAndFragment(UtFrameUtils.java:400)
	at com.starrocks.sql.plan.PlanTestNoneDBBase.getFragmentPlan(PlanTestNoneDBBase.java:133)
	at com.starrocks.connector.hive.HiveViewPlanTest.testHiveView1(HiveViewPlanTest.java:39)

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.1.4 and 3.1.2

**Comment by alberttwong** [comment]
This does not have enough data to help debug.   What is the environment, how did you connect to Hive (what is the external catalog command).    Per github issue instruction, this is a better question to be asked on community slack.

**Comment by alberttwong** [comment]
how did you create your hive environment? what is the command you used to connect to hive?

**Comment by FrommyMind** [comment]
> how did you create your hive environment? what is the command you used to connect to hive?

Create hive catalog like in the docs with ha
```
CREATE EXTERNAL  CATALOG hz_hive PROPERTIES (
    'type'='hive',
        "hive.metastore.type" = "hive",
    'hive.metastore.uris' = 'thrift://10.x.x.x:9083',
    'hadoop.username' = 'hive',
    'dfs.nameservices'='nameservice1',
    'dfs.ha.namenodes.nameservice1'='namenode45,namenode47',
    'dfs.namenode.rpc-address.nameservice1.namenode45'='hadoop-x:8020',
    'dfs.namenode.rpc-address.nameservice1.namenode47'='hadoop-x:8020',
    'dfs.client.failover.proxy.provider.nameservice1'='org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider',
        'hive.version' = '2.1.1'
);
```
My hive version is cdh6.3.2
after that query the hive table like
```
Select *from hive.default.tablename
```

**Comment by FrommyMind** [comment]
Update,
with bellow query , it works.
```
select * from hz_hive.`default`.tablename;
```

**Comment by DanRoscigno** [comment]
I just changed the Hudi/StarRocks quick start because of this bug. Using a DB named 'default' works with MySQL cli, but not the go https://github.com/go-sql-driver/mysql driver
