### ISSUE TITLE
Failed to find key 3497822 in database 3497820 when replay bdb log

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#3533]
### Steps to reproduce the behavior (Required)
Not easy to reproduce this bug.

### Expected behavior (Required)
System runs normally.

### Real behavior (Required)
```java
2022-02-18 15:57:57,438 WARN (stateListener|94) [BDBJournalCursor.next():148] Catch an exception when get next JournalEntity. key:3497822
java.lang.Exception: Failed to find key 3497822 in database 3497820
        at com.starrocks.journal.bdbje.BDBJournalCursor.next(BDBJournalCursor.java:141) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2496) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.transferToMaster(Catalog.java:1245) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.access$800(Catalog.java:288) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$4.runOneCycle(Catalog.java:2418) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
```
All the logs after 3497822 will not be replayed when this error happend.

### StarRocks version (Required)
 - all

**Comment by gengjun-git** [comment]
The dump of database 3497820 shows that there is a hole of the log journal id.
![image](https://user-images.githubusercontent.com/54172532/154789384-0848a01b-ea85-4efe-b4a4-7818e501ab5b.png)
