### ISSUE TITLE
Error querying iceberg catalog tables

### ISSUE THREAD

**Issue by vytautas-karpavicius** [StarRocks/starrocks#35422]
### Steps to reproduce the behavior (Required)
1. Create iceberg catalog based on [documentation](https://docs.starrocks.io/en-us/latest/data_source/catalog/iceberg_catalog#s3-compatible-storage-system-1) with Hive metastore and S3 compatible endpoint.
```
mysql> CREATE EXTERNAL CATALOG iceberg
PROPERTIES (
    "type"  =  "iceberg",
    "iceberg.catalog.type"  =  "hive",
    "hive.metastore.uris"  =  "thrift://hive-metastore.hive-metastore:9083",
    "aws.s3.endpoint"  =  "bucket-gateway.blob.svc.cluster.local:8080",
    "aws.s3.enable_ssl"  =  "false",
    "aws.s3.enable_path_style_access"  =  "true",
    "aws.s3.access_key"  =  "XXX",
    "aws.s3.secret_key"  =  "YYY"
);
Query OK, 0 rows affected (0.02 sec)
```
2. Verify created:
```
mysql> show catalogs;
+-----------------+----------+------------------------------------------------------------------+
| Catalog         | Type     | Comment                                                          |
+-----------------+----------+------------------------------------------------------------------+
| default_catalog | Internal | An internal catalog contains this cluster's self-managed tables. |
| iceberg         | Iceberg  | NULL                                                             |
+-----------------+----------+------------------------------------------------------------------+
2 rows in set (0.01 sec)
```
3. Show databases in the catalog:
```
mysql> set catalog iceberg;
Query OK, 0 rows affected (0.00 sec)

mysql> show databases;
+----------------------------------------------------------------------------+
| Database                                                                   |
+----------------------------------------------------------------------------+
...
| sql_iceberg_test                                                           |
...
+----------------------------------------------------------------------------+
240 rows in set (2.27 sec)
```
4. Show tables in the database:
```
mysql> use sql_iceberg_test;
Database changed

mysql> show tables;
ERROR 1064 (HY000): Unable to marshall request to JSON: baseUri must not be null.
```

### Expected behavior (Required)
Tables should be listed.

### Real behavior (Required)
Getting error `ERROR 1064 (HY000): Unable to marshall request to JSON: baseUri must not be null.`

Relevant output in the fe.log
```
2023-11-20 13:23:52,197 INFO (starrocks-mysql-nio-pool-3|285) [MetadataMgr$QueryMetadatas.getConnectorMetadata():389] Succeed to register query level connector metadata [catalog:iceberg, queryId: 0c1433ac-87a8-11ee-8fcf-7a1e80606d8a]
2023-11-20 13:23:52,339 INFO (ReportHandler|157) [ReportHandler.tabletReport():380] backend[16030] reports 97 tablet(s). report version: 16974681830171
2023-11-20 13:23:52,339 INFO (ReportHandler|157) [TabletInvertedIndex.tabletReport():301] finished to do tablet diff with backend[16030]. sync: 0. metaDel: 0. foundValid: 97. foundInvalid: 0. migration: 0. found invalid transactions 0. found rep
ublish transactions 0  cost: 0 ms
2023-11-20 13:23:52,440 INFO (starrocks-mysql-nio-pool-3|285) [BaseMetastoreTableOperations.refreshFromMetadataLocation():199] Refreshing table metadata from new version: s3a://scratch/default/sql_iceberg_test.db/test_repartition-33d9118daa774d7
f98686ddfd9404160/metadata/00003-6ff73d33-3685-47dd-83d1-02dde295674c.metadata.json
2023-11-20 13:23:52,440 WARN (starrocks-mysql-nio-pool-3|285) [Tasks$Builder.runTaskWithRetry():456] Retrying task after failure: Unable to marshall request to JSON: baseUri must not be null.
software.amazon.awssdk.core.exception.SdkClientException: Unable to marshall request to JSON: baseUri must not be null.
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.services.s3.transform.HeadObjectRequestMarshaller.marshall(HeadObjectRequestMarshaller.java:53) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.services.s3.transform.HeadObjectRequestMarshaller.marshall(HeadObjectRequestMarshaller.java:31) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$finalizeSdkHttpFullRequest$0(BaseClientHandler.java:68) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.core.internal.util.MetricUtils.measureDuration(MetricUtils.java:50) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:67) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:151) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.services.s3.DefaultS3Client.headObject(DefaultS3Client.java:5438) ~[bundle-2.17.257.jar:?]
        at org.apache.iceberg.aws.s3.BaseS3File.getObjectMetadata(BaseS3File.java:85) ~[iceberg-aws-1.2.1.jar:?]
        at org.apache.iceberg.aws.s3.S3InputFile.getLength(S3InputFile.java:75) ~[iceberg-aws-1.2.1.jar:?]
        at com.starrocks.connector.iceberg.io.IcebergCachingFileIO$CachingInputFile.getLength(IcebergCachingFileIO.java:530) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.io.IcebergCachingFileIO$CachingInputFile.newStream(IcebergCachingFileIO.java:537) ~[starrocks-fe.jar:?]
        at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:272) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:266) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.lambda$refreshFromMetadataLocation$0(BaseMetastoreTableOperations.java:189) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.lambda$refreshFromMetadataLocation$1(BaseMetastoreTableOperations.java:208) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:208) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:185) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:180) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:176) ~[iceberg-hive-metastore-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:97) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:80) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:47) ~[iceberg-core-1.2.1.jar:?]
        at com.starrocks.connector.iceberg.hive.IcebergHiveCatalog.getTable(IcebergHiveCatalog.java:98) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergMetadata.loadTable(IcebergMetadata.java:235) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergMetadata.getTable(IcebergMetadata.java:214) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.lambda$getTable$3(MetadataMgr.java:255) ~[starrocks-fe.jar:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ShowExecutor.handleShowTable(ShowExecutor.java:953) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ShowExecutor.execute(ShowExecutor.java:275) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleShow(StmtExecutor.java:1360) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:619) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:363) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:477) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:753) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NullPointerException: baseUri must not be null.
        at software.amazon.awssdk.utils.Validate.paramNotNull(Validate.java:156) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.utils.http.SdkHttpUtils.appendUri(SdkHttpUtils.java:302) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.http.SdkHttpFullRequest$Builder.uri(SdkHttpFullRequest.java:71) ~[http-client-spi-2.17.257.jar:?]
        at software.amazon.awssdk.protocols.core.ProtocolUtils.createSdkHttpRequest(ProtocolUtils.java:44) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.protocols.xml.internal.marshall.XmlProtocolMarshaller.<init>(XmlProtocolMarshaller.java:64) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.protocols.xml.internal.marshall.XmlProtocolMarshaller.<init>(XmlProtocolMarshaller.java:50) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.protocols.xml.internal.marshall.XmlProtocolMarshaller$Builder.build(XmlProtocolMarshaller.java:255) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.protocols.xml.AwsXmlProtocolFactory.createProtocolMarshaller(AwsXmlProtocolFactory.java:106) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.services.s3.transform.HeadObjectRequestMarshaller.marshall(HeadObjectRequestMarshaller.java:50) ~[bundle-2.17.257.jar:?]
        ... 47 more
```

### StarRocks version (Required)
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 3.1.4-0c4b2a3     |
+-------------------+
1 row in set (0.01 sec)
```

**Comment by Smith-Cruise** [comment]
are you using minio?

**Comment by vytautas-karpavicius** [comment]
> are you using minio?

We are using minio compatible layer.

**Comment by Smith-Cruise** [comment]
can you try to replace your endpoint as `http://bucket-gateway.blob.svc.cluster.local:8080`

**Comment by vytautas-karpavicius** [comment]
Ok, this helped. Thank you!

Although it is not consistent with other catalogs. For example it works without this prefix on hudi catalog.

**Comment by vytautas-karpavicius** [comment]
In both cases it was Minio compatible gateway.

Anyway, it solves the issue.
