### ISSUE TITLE
Issue with starting the allin1 container on docker desktop v4.25.2 mac 14.1.1 (23B81)

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#35608]
Issue with starting the allin1 container on docker desktop v4.25.2
```
docker run -p 9030:9030 -p 8030:8030 -p 8040:8040 -itd starrocks/allin1-ubuntu:3.1.4
```

```
023-11-22 10:35:16 
2023-11-22 10:35:16 StarRocks [(Blazing Fast)]> _
2023-11-22 10:35:16 
2023-11-22 10:35:16 
2023-11-22 10:35:17 2023-11-22 18:35:17,002 INFO Set uid to user 0 succeeded
2023-11-22 10:35:17 2023-11-22 18:35:17,004 INFO RPC interface 'supervisor' initialized
2023-11-22 10:35:17 2023-11-22 18:35:17,004 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-11-22 10:35:17 2023-11-22 18:35:17,004 INFO supervisord started with pid 7
2023-11-22 10:35:18 2023-11-22 18:35:18,011 INFO spawned: 'beservice' with pid 525
2023-11-22 10:35:18 2023-11-22 18:35:18,014 INFO spawned: 'broker' with pid 526
2023-11-22 10:35:18 2023-11-22 18:35:18,017 INFO spawned: 'director' with pid 527
2023-11-22 10:35:18 2023-11-22 18:35:18,022 INFO spawned: 'feproxy' with pid 528
2023-11-22 10:35:18 2023-11-22 18:35:18,028 INFO spawned: 'feservice' with pid 529
2023-11-22 10:35:18 2023-11-22 18:35:18+00:00 INFO checking if need to perform auto registring Backend and Broker ...
2023-11-22 10:35:18 2023-11-22 18:35:18+00:00 INFO checking if FE service query port:9030 alive or not ...
2023-11-22 10:35:18 2023-11-22 18:35:18+00:00 WARN FE service query port:9030 is NOT alive yet!
2023-11-22 10:35:20 2023-11-22 18:35:20+00:00 WARN FE service query port:9030 is NOT alive yet!
2023-11-22 10:35:22 2023-11-22 18:35:22+00:00 WARN FE service query port:9030 is NOT alive yet!
2023-11-22 10:35:23 2023-11-22 18:35:23,286 INFO success: beservice entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2023-11-22 10:35:23 2023-11-22 18:35:23,286 INFO success: broker entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2023-11-22 10:35:23 2023-11-22 18:35:23,286 INFO success: director entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2023-11-22 10:35:23 2023-11-22 18:35:23,286 INFO success: feproxy entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2023-11-22 10:35:23 2023-11-22 18:35:23,286 INFO success: feservice entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2023-11-22 10:35:24 2023-11-22 18:35:24+00:00 WARN FE service query port:9030 is NOT alive yet!
2023-11-22 10:35:26 2023-11-22 18:35:26+00:00 WARN FE service query port:9030 is NOT alive yet!
2023-11-22 10:35:28 2023-11-22 18:35:28+00:00 WARN FE service query port:9030 is NOT alive yet!
```

**Comment by alberttwong** [comment]
```
root@e91037d889ab:/data/deploy/starrocks/fe/log# tail -f fe.log
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:175) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:153) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalFactory.create(JournalFactory.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:1142) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1091) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:135) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]
2023-11-22 18:37:53,581 INFO (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():269] start to setup bdb environment for 3 times
2023-11-22 18:37:53,585 WARN (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: UNKNOWN
2023-11-22 18:37:53,586 INFO (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():280] replicated environment is all set, wait for state change...




2023-11-22 18:38:03,603 INFO (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():288] state change done, current role UNKNOWN
2023-11-22 18:38:03,605 ERROR (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():305] failed to setup environment after retried 3 times
com.sleepycat.je.rep.ReplicaWriteException: (JE 18.3.16) Problem closing transaction 27. The current state is:UNKNOWN. The node transitioned to this state at:Wed Nov 22 18:37:23 UTC 2023
        at com.sleepycat.je.rep.txn.ReadonlyTxn.disallowReplicaWrite(ReadonlyTxn.java:114) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.checkReplicaWrite(DbTree.java:880) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.doCreateDb(DbTree.java:579) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.createDb(DbTree.java:486) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Database.initNew(Database.java:174) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.setupDatabase(Environment.java:864) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:668) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setupEnvironment(BDBEnvironment.java:291) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:175) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:153) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalFactory.create(JournalFactory.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:1142) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1091) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:135) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]
2023-11-22 18:38:03,606 ERROR (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [StarRocksFE.start():192] StarRocksFE start failed
com.starrocks.journal.JournalException: failed to setup environment after retried 3 times
        at com.starrocks.journal.bdbje.BDBEnvironment.setupEnvironment(BDBEnvironment.java:306) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:175) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:153) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalFactory.create(JournalFactory.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:1142) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1091) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:135) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]
Caused by: com.sleepycat.je.rep.ReplicaWriteException: (JE 18.3.16) Problem closing transaction 27. The current state is:UNKNOWN. The node transitioned to this state at:Wed Nov 22 18:37:23 UTC 2023
        at com.sleepycat.je.rep.txn.ReadonlyTxn.disallowReplicaWrite(ReadonlyTxn.java:114) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.checkReplicaWrite(DbTree.java:880) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.doCreateDb(DbTree.java:579) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.createDb(DbTree.java:486) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Database.initNew(Database.java:174) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.setupDatabase(Environment.java:864) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:668) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setupEnvironment(BDBEnvironment.java:291) ~[starrocks-fe.jar:?]
        ... 7 more
2023-11-22 18:38:05,182 INFO (main|1) [StarRocksFE.start():129] StarRocks FE starting, version: 3.1.4-0c4b2a3
2023-11-22 18:38:05,185 INFO (main|1) [FrontendOptions.analyzePriorityCidrs():299] configured prior_cidrs value: 127.0.0.1/32
2023-11-22 18:38:05,186 WARN (main|1) [FrontendOptions.initAddrUseIp():243] ip address range configured for priority_networks does not include the current IP address
2023-11-22 18:38:05,186 INFO (main|1) [FrontendOptions.initAddrUseIp():249] Use IP init local addr, IP: /127.0.0.1
2023-11-22 18:38:05,309 INFO (main|1) [Auth.grantRoleInternal():837] grant operator to 'root'@'%', isReplay = true
2023-11-22 18:38:05,320 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():281] create built-in role root[-1]
2023-11-22 18:38:05,322 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():281] create built-in role db_admin[-2]
2023-11-22 18:38:05,323 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():281] create built-in role cluster_admin[-3]
2023-11-22 18:38:05,323 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():281] create built-in role user_admin[-4]
2023-11-22 18:38:05,323 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():281] create built-in role public[-5]
2023-11-22 18:38:05,323 INFO (main|1) [GlobalStateMgr.initAuth():1118] using new privilege framework..
2023-11-22 18:38:05,403 INFO (main|1) [NodeMgr.getHelperNodes():660] get helper nodes: [127.0.0.1:9010]
2023-11-22 18:38:05,409 INFO (main|1) [NodeMgr.getClusterIdAndRoleOnStartup():461] Current run_mode is shared_nothing
2023-11-22 18:38:05,409 INFO (main|1) [NodeMgr.getClusterIdAndRoleOnStartup():468] Got cluster id: 828487348, role: FOLLOWER, node name: 127.0.0.1_9010_1700678209004 and run_mode: shared_nothing
2023-11-22 18:38:05,409 INFO (main|1) [BDBEnvironment.ensureHelperInLocal():340] skip check local environment because helper node and local node are identical.
2023-11-22 18:38:05,420 INFO (main|1) [BDBEnvironment.setupEnvironment():269] start to setup bdb environment for 1 times
2023-11-22 18:38:05,567 WARN (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: UNKNOWN
2023-11-22 18:38:05,585 INFO (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():280] replicated environment is all set, wait for state change...
2023-11-22 18:38:15,608 INFO (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():288] state change done, current role UNKNOWN
2023-11-22 18:38:15,613 ERROR (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():305] failed to setup environment after retried 1 times
com.sleepycat.je.rep.ReplicaWriteException: (JE 18.3.16) Problem closing transaction 25. The current state is:UNKNOWN. The node transitioned to this state at:Wed Nov 22 18:38:05 UTC 2023
        at com.sleepycat.je.rep.txn.ReadonlyTxn.disallowReplicaWrite(ReadonlyTxn.java:114) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.checkReplicaWrite(DbTree.java:880) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.doCreateDb(DbTree.java:579) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.createDb(DbTree.java:486) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Database.initNew(Database.java:174) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.setupDatabase(Environment.java:864) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:668) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setupEnvironment(BDBEnvironment.java:291) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:175) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:153) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalFactory.create(JournalFactory.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:1142) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1091) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:135) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]
2023-11-22 18:38:20,624 INFO (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():269] start to setup bdb environment for 2 times
2023-11-22 18:38:20,628 WARN (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: UNKNOWN
2023-11-22 18:38:20,629 INFO (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():280] replicated environment is all set, wait for state change...
2023-11-22 18:38:30,649 INFO (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():288] state change done, current role UNKNOWN
2023-11-22 18:38:30,651 ERROR (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():305] failed to setup environment after retried 2 times
com.sleepycat.je.rep.ReplicaWriteException: (JE 18.3.16) Problem closing transaction 26. The current state is:UNKNOWN. The node transitioned to this state at:Wed Nov 22 18:38:05 UTC 2023
        at com.sleepycat.je.rep.txn.ReadonlyTxn.disallowReplicaWrite(ReadonlyTxn.java:114) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.checkReplicaWrite(DbTree.java:880) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.doCreateDb(DbTree.java:579) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.DbTree.createDb(DbTree.java:486) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Database.initNew(Database.java:174) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.setupDatabase(Environment.java:864) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:668) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setupEnvironment(BDBEnvironment.java:291) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:175) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:153) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalFactory.create(JournalFactory.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:1142) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1091) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:135) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]
2023-11-22 18:38:35,654 INFO (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():269] start to setup bdb environment for 3 times
2023-11-22 18:38:35,658 WARN (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: UNKNOWN
2023-11-22 18:38:35,659 INFO (UNKNOWN 127.0.0.1_9010_1700678209004(-1)|1) [BDBEnvironment.setupEnvironment():280] replicated environment is all set, wait for state change...
```

**Comment by kevincai** [comment]
FE has a default config that requires at least 5GB free space for the disk partitions its meta directory residents (that is /data/deploy/starrocks/fe/meta).

have a check about the free space.

**Comment by alberttwong** [comment]
<img width="1047" alt="Screenshot 2023-11-22 at 4 39 02 PM" src="https://github.com/StarRocks/starrocks/assets/749093/48dbb1df-a237-4c9a-9ea7-d564a6b18d97">

that was it.   I was showing not enough space and I had to edit the "virtual disk limit" setting in docker desktop.

**Comment by alberttwong** [comment]
updated docs via PR https://github.com/StarRocks/starrocks/pull/35612
