### ISSUE TITLE
jdbc catalog 源数据库为postgresql，物化视图刷新Exception：corrupted partition meta

### ISSUE THREAD

**Issue by hcloc** [StarRocks/starrocks#35898]
2023-11-27 09:46:30,449 WARN (pool-23-thread-120|2218) [PartitionBasedMvRefreshProcessor.doMvRefresh():285] Refresh mv mv_user_partition_local failed: java.lang.IllegalStateException: corrupted partition meta
2023-11-27 09:46:30,449 WARN (pool-23-thread-120|2218) [TaskRunExecutor.lambda$executeTaskRun$0():54] failed to execute TaskRun.
java.lang.IllegalStateException: corrupted partition meta
	at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getPartitionNameWithPartitionInfo(ConnectorPartitionTraits.java:217) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getUpdatedPartitionNames(ConnectorPartitionTraits.java:239) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfExternalTable(MaterializedView.java:691) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:718) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:534) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.needToRefreshTable(PartitionBasedMvRefreshProcessor.java:792) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.isNonPartitionedMVNeedToRefresh(PartitionBasedMvRefreshProcessor.java:814) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:890) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:848) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doMvRefresh(PartitionBasedMvRefreshProcessor.java:240) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.processTaskRun(PartitionBasedMvRefreshProcessor.java:192) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:190) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:47) ~[starrocks-fe.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]

### Steps to reproduce the behavior (Required)
1. CREATE EXTERNAL CATALOG pg_localhost
PROPERTIES
(
    "type"="jdbc",
    "user"="postgres",
    "password"="123456",
    "jdbc_uri"="jdbc:postgresql://192.168.40.110:5432/database",
    "driver_url"="https://repo1.maven.org/maven2/org/postgresql/postgresql/42.3.3/postgresql-42.3.3.jar",
    "driver_class"="org.postgresql.Driver"
);
2. CREATE MATERIALIZED VIEW IF NOT EXISTS example_db.mv_user_local REFRESH IMMEDIATE ASYNC START ('2023-09-12 16:30:25') EVERY (INTERVAL 5 MINUTE)
AS
  select * from pg_localhost.public.user;

### StarRocks version (Required)
 - starRocks > select current_version();
+--------------------+
| current_version()  |
+--------------------+
| 3.2.0-rc01-9d64ad2 |

**Comment by zyclove** [comment]
请问这个有解决办法吗？
@hcloc @LiShuMing

**Comment by zyclove** [comment]
2023-12-13 15:38:03,528 INFO (thrift-server-pool-4018|4739) [QeProcessorImpl.reportExecStatus():179] ReportExecStatus() failed, query does not exist, fragment_instance_id=8c661246-998a-11ee-bfd3-eeeeeeeeeeef, query_id=8c661246-998a-11ee-bfd3-eeeeeeeeeeee,
2023-12-13 15:38:03,629 WARN (pool-23-thread-107|4641) [PartitionBasedMvRefreshProcessor.doMvRefresh():282] Refresh mv mv_product_category_rela_test failed: java.lang.IllegalStateException: corrupted partition meta
2023-12-13 15:38:03,629 WARN (pool-23-thread-107|4641) [TaskRunExecutor.lambda$executeTaskRun$0():54] failed to execute TaskRun.
java.lang.IllegalStateException: corrupted partition meta
        at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getPartitionNameWithPartitionInfo(ConnectorPartitionTraits.java:202) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getUpdatedPartitionNames(ConnectorPartitionTraits.java:224) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfExternalTable(MaterializedView.java:698) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:725) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:541) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.needToRefreshTable(PartitionBasedMvRefreshProcessor.java:769) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.isNonPartitionedMVNeedToRefresh(PartitionBasedMvRefreshProcessor.java:791) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:863) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:825) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doMvRefresh(PartitionBasedMvRefreshProcessor.java:233) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.processTaskRun(PartitionBasedMvRefreshProcessor.java:186) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:189) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:47) ~[starrocks-fe.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]
2023-12-13 15:38:03,715 INFO (thrift-server-pool-4015|4736) [FrontendServiceImpl.forward():1085] receive forwarded stmt 1514 from FE: 172.16.233.146
2023-12-13 15:38:04,641 WARN (pool-23-thread-107|4641) [PartitionBasedMvRefreshProcessor.doMvRefresh():282] Refresh mv mv_product_category_rela_test failed: java.lang.IllegalStateException: corrupted partition meta
2023-12-13 15:38:04,641 WARN (pool-23-thread-107|4641) [TaskRunExecutor.lambda$executeTaskRun$0():54] failed to execute TaskRun.
java.lang.IllegalStateException: corrupted partition meta
        at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getPartitionNameWithPartitionInfo(ConnectorPartitionTraits.java:202) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getUpdatedPartitionNames(ConnectorPartitionTraits.java:224) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfExternalTable(MaterializedView.java:698) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:725) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:541) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.needToRefreshTable(PartitionBasedMvRefreshProcessor.java:769) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.isNonPartitionedMVNeedToRefresh(PartitionBasedMvRefreshProcessor.java:791) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:863) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:825) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doMvRefresh(PartitionBasedMvRefreshProcessor.java:233) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.processTaskRun(PartitionBasedMvRefreshProcessor.java:186) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:189) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:47) ~[starrocks-fe.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]

**Comment by andyliumathematics** [comment]
The bug has not bean fixed in v3.2.4,please fix it. Now I can build a view with outer table in pg.

**Comment by Bulbashful** [comment]
The same

**Comment by nanchun** [comment]
3.3.7也没修复吗
