### ISSUE TITLE
Cannot truncate a file by broker

### ISSUE THREAD

**Issue by TheheiWorld** [StarRocks/starrocks#3683]
version:2.0.1

备份数据至阿里云OSS中，备份某个表时候一直失败，显示子任务失败，换成其他的表也有能备份成功的
[12008: Cannot truncate a file by broker]

remote file checksum is invalid. remote: 0200000000000372b84d62fa90c3a5ea99f3d08966b212a5_0.dat, local: 03082da95d78c4dcec0098e2aac011d3
W0225 15:18:09.661361 19221 task_worker_pool.cpp:1317] Fail to upload job id=12007 msg=Cannot truncate a file by broker

**Comment by TheheiWorld** [comment]
导入失败的表是 更新模型，数据量也才50w，中间出现这样的错误信息
Broker storage service error, the fd is not owned by client null, cause by: null

**Comment by TheheiWorld** [comment]
2022-02-25 17:09:42  [ TThreadPoolServer WorkerProcess-%d:19154589 ] - [ INFO ]  receive a close writer request, request detail: TBrokerCloseWriterRequest(version:VERSION_ONE, fd:TBrokerFD(high:1290572370509122109, low:-6908896782875474178))
2022-02-25 17:09:53  [ TThreadPoolServer WorkerProcess-%d:19164993 ] - [ ERROR ]  Thrift Error occurred during processing of message.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)
	at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:213)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:60)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:208)
	... 6 more
2022-02-25 17:09:53  [ TThreadPoolServer WorkerProcess-%d:19164994 ] - [ WARN ]  Error closing output stream.
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.apache.thrift.transport.TIOStreamTransport.close(TIOStreamTransport.java:156)
	at org.apache.thrift.transport.TSocket.close(TSocket.java:252)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2022-02-25 17:09:53  [ TThreadPoolServer WorkerProcess-%d:19165590 ] - [ INFO ]  receive a close writer request, request detail: TBrokerCloseWriterRequest(version:VERSION_ONE, fd:TBrokerFD(high:1290572370509122109, low:-6908896782875474178))
2022-02-25 17:09:53  [ TThreadPoolServer WorkerProcess-%d:19165590 ] - [ WARN ]  failed to close writer: TBrokerFD(high:1290572370509122109, low:-6908896782875474178)
com.starrocks.broker.hdfs.BrokerException: the fd is not owned by client null
	at com.starrocks.broker.hdfs.ClientContextManager.getFsDataOutputStream(ClientContextManager.java:95)
	at com.starrocks.broker.hdfs.FileSystemManager.closeWriter(FileSystemManager.java:921)
	at com.starrocks.broker.hdfs.HDFSBrokerServiceImpl.closeWriter(HDFSBrokerServiceImpl.java:250)
	at com.starrocks.thrift.TFileBrokerService$Processor$closeWriter.getResult(TFileBrokerService.java:1065)
	at com.starrocks.thrift.TFileBrokerService$Processor$closeWriter.getResult(TFileBrokerService.java:1045)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2022-02-25 17:09:53  [ TThreadPoolServer WorkerProcess-%d:19165590 ] - [ INFO ]  receive a close writer request, request detail: TBrokerCloseWriterRequest(version:VERSION_ONE, fd:TBrokerFD(high:1290572370509122109, low:-6908896782875474178))
2022-02-25 17:09:53  [ TThreadPoolServer WorkerProcess-%d:19165590 ] - [ WARN ]  failed to close writer: TBrokerFD(high:1290572370509122109, low:-6908896782875474178)
com.starrocks.broker.hdfs.BrokerException: the fd is not owned by client null
	at com.starrocks.broker.hdfs.ClientContextManager.getFsDataOutputStream(ClientContextManager.java:95)
	at com.starrocks.broker.hdfs.FileSystemManager.closeWriter(FileSystemManager.java:921)
	at com.starrocks.broker.hdfs.HDFSBrokerServiceImpl.closeWriter(HDFSBrokerServiceImpl.java:250)
	at com.starrocks.thrift.TFileBrokerService$Processor$closeWriter.getResult(TFileBrokerService.java:1065)
	at com.starrocks.thrift.TFileBrokerService$Processor$closeWriter.getResult(TFileBrokerService.java:1045)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by bibichuan** [comment]
我也遇到了同样的问题，我备份到了自己建的hdfs上，也是出现这个问题。

**Comment by liangkiller** [comment]
同样遇到这个问题，解决方法如下： 在be上查看be.WARNING日志，有报错

remote file checksum is invalid. remote: 0200000000118cad1240a8b33c9469046d2bacea69e4e0a8_0.dat, local: b483d204dc8034ebef062e620324b868

在broker的日志上查找 0200000000118cad1240a8b33c9469046d2bacea69e4e0a8_0.dat，有eceive a check path request, request detail: TBrokerCheckPathExistRequest(version:VERSION_ONE, path:oss://xxxx/__part_536170/__idx_536202/__545799/0200000000118cad1240a8b33c9469046d2bacea69e4e0a8_0.dat.part, properties:{})

到OSS的相应路径上查看，将相应的文件重命名或删除。让starrocks重传文件，正常文件名是： 0200000000118cad1240a8b33c9469046d2bacea69e4e0a8_0.dat.b483d204dc8034ebef062e620324b868

在broker日志里查找所有 dat.part，所现OSS上有些类__545799目录没有创建，手动创建就可以了。

**Comment by bibichuan** [comment]
感谢您的来信，敝人已收到。敝人会尽快给您回复，谢谢。

**Comment by thirdparty-core** [comment]
> 同样遇到这个问题，解决方法如下： 在be上查看be.WARNING日志，有报错
> 
> remote file checksum is invalid. remote: 0200000000118cad1240a8b33c9469046d2bacea69e4e0a8_0.dat, local: b483d204dc8034ebef062e620324b868
> 
> 在broker的日志上查找 0200000000118cad1240a8b33c9469046d2bacea69e4e0a8_0.dat，有eceive a check path request, request detail: TBrokerCheckPathExistRequest(version:VERSION_ONE, path:oss://xxxx/__part_536170/__idx_536202/__545799/0200000000118cad1240a8b33c9469046d2bacea69e4e0a8_0.dat.part, properties:{})
> 
> 到OSS的相应路径上查看，将相应的文件重命名或删除。让starrocks重传文件，正常文件名是： 0200000000118cad1240a8b33c9469046d2bacea69e4e0a8_0.dat.b483d204dc8034ebef062e620324b868
> 
> 在broker日志里查找所有 dat.part，所现OSS上有些类__545799目录没有创建，手动创建就可以了。

你好，我的表数据量有些大，按照你的说法删除dat.part后，starrocks又重新创建了，而且我的有多个dat.part文件。这如何处理？
