### ISSUE TITLE
Failed to read iceberg table stored in Azure Blob Using SAS token

### ISSUE THREAD

**Issue by neokjchen** [StarRocks/starrocks#36911]
### Steps to reproduce the behavior (Required)
CREATE EXTERNAL CATALOG iceberg_hms_azblob4 PROPERTIES (
  "type"="iceberg",
  "iceberg.catalog.type"="hive",
  "hive.metastore.uris" = "thrift://172.31.16.168:9083",
  "azure.blob.account_name" = "name",
  "azure.blob.container_name" = "name",
  "azure.blob.sas_token" = "sp=r&st=2023-12-13T02:33:52Z&se=2023-12-13T10:33:52Z&sip=xx.xx.xx.xx&sv=2022-11-02&sr=c&sig=xx"
);

set catalog iceberg_hms_azblob4;
use iceberg_onazblob;
show tables;

### Real behavior (Required)
mysql> desc person;
ERROR 1064 (HY000): Failed to get file system for path: wasbs://name@name.blob.core.windows.net/datalake/iceberg_onazblob.db/person/metadata/00001-9dc79345-995d-4ff5-8ff3-696e3ab88ab5.metadata.json

FE LOG
```
2023-12-13 03:03:15,755 ERROR (starrocks-mysql-nio-pool-7|254) [AzureNativeFileSystemStore.connectUsingAnonymousCredentials():894] Service returned StorageException when checking existence of container laketest in account puppy.blob.core.windows.net
com.microsoft.azure.storage.StorageException: Public access is not permitted on this storage account.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87) ~[azure-storage-7.0.1.jar:?]
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315) ~[azure-storage-7.0.1.jar:?]
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185) ~[azure-storage-7.0.1.jar:?]
	at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:769) ~[azure-storage-7.0.1.jar:?]
	at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:756) ~[azure-storage-7.0.1.jar:?]
	at org.apache.hadoop.fs.azure.StorageInterfaceImpl$CloudBlobContainerWrapperImpl.exists(StorageInterfaceImpl.java:233) ~[hadoop-azure-3.3.6.jar:?]
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.connectUsingAnonymousCredentials(AzureNativeFileSystemStore.java:892) ~[hadoop-azure-3.3.6.jar:?]
...
2023-12-13 03:03:15,755 WARN (starrocks-mysql-nio-pool-7|254) [FileSystem.createFileSystem():3615] Failed to initialize filesystem wasbs://name@name.blob.core.windows.net/datalake/iceberg_onazblob.db/person/metadata/00001-9dc79345-995d-4ff5-8ff3-696e3ab88ab5.metadata.json: org.apache.hadoop.fs.azure.AzureException: org.apache.hadoop.fs.azure.AzureException: No credentials found for account puppy.blob.core.windows.net in the configuration, and its container laketest is not accessible using anonymous credentials. Please check if the container exists first. If it is not publicly available, you have to provide account credentials.
2023-12-13 03:03:15,756 WARN (starrocks-mysql-nio-pool-7|254) [Tasks$Builder.runTaskWithRetry():456] Retrying task after failure: Failed to get file system for path: wasbs://name@name.blob.core.windows.net/datalake/iceberg_onazblob.db/person/metadata/00001-9dc79345-995d-4ff5-8ff3-696e3ab88ab5.metadata.json
org.apache.iceberg.exceptions.RuntimeIOException: Failed to get file system for path: wasbs://name@name.blob.core.windows.net/datalake/iceberg_onazblob.db/person/metadata/00001-9dc79345-995d-4ff5-8ff3-696e3ab88ab5.metadata.json
	at org.apache.iceberg.hadoop.Util.getFs(Util.java:58) ~[iceberg-core-1.2.1.jar:?]
	at org.apache.iceberg.hadoop.HadoopInputFile.fromLocation(HadoopInputFile.java:56) ~[iceberg-core-1.2.1.jar:?]
	at org.apache.iceberg.hadoop.HadoopFileIO.newInputFile(HadoopFileIO.java:90) ~[iceberg-core-1.2.1.jar:?]
	at org.apache.iceberg.io.ResolvingFileIO.newInputFile(ResolvingFileIO.java:61) ~[iceberg-core-1.2.1.jar:?]
...
aused by: org.apache.hadoop.fs.azure.AzureException: org.apache.hadoop.fs.azure.AzureException: No credentials found for account name.blob.core.windows.net in the configuration, and its container laketest is not accessible using anonymous credentials. Please check if the container exists first. If it is not publicly available, you have to provide account credentials.
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.createAzureStorageSession(AzureNativeFileSystemStore.java:1123) ~[hadoop-azure-3.3.6.jar:?]
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.initialize(AzureNativeFileSystemStore.java:566) ~[hadoop-azure-3.3.6.jar:?]
	at org.apache.hadoop.fs.azure.NativeAzureFileSystem.initialize(NativeAzureFileSystem.java:1423) ~[hadoop-azure-3.3.6.jar:?]
```

The SAS token can be used to download the json file.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 3.1.5-5d8438a     |
+-------------------+
1 row in set (0.04 sec)

**Comment by Smith-Cruise** [comment]
use
```sql
CREATE EXTERNAL CATALOG iceberg_hms_azblob4 PROPERTIES (
"type"="iceberg",
"iceberg.catalog.type"="hive",
"hive.metastore.uris" = "thrift://172.31.16.168:9083",
"azure.blob.storage_account" = "name",
"azure.blob.container" = "name",
"azure.blob.sas_token" = "sp=r&st=2023-12-13T02:33:52Z&se=2023-12-13T10:33:52Z&sip=xx.xx.xx.xx&sv=2022-11-02&sr=c&sig=xx"
);
```

instead, document is wrong.

**Comment by neokjchen** [comment]
It works with the correct parameters above.
