### ISSUE TITLE
Failed to read Deltalake/Hudi table stored in Azure Blob Using SAS token

### ISSUE THREAD

**Issue by neokjchen** [StarRocks/starrocks#37046]
### Steps to reproduce the behavior (Required)
1.
CREATE EXTERNAL CATALOG delta_hms_azblob PROPERTIES (
  "type"="deltalake",
  "hive.metastore.uris"="thrift://172.31.16.168:9083",
  "azure.blob.storage_account" = "account",
  "azure.blob.container" = "container",
  "azure.blob.sas_token" = "sp=r&st=2023-12-13T06:54:39Z&se=2024-10-13T14:54:39Z&sv=2022-11-02&sr=c&sig=xxxxx"
);
2. set catalog delta_hms_azblob;
3. use delta_onazblob;
4. show tables;

### Expected behavior (Required)
```
mysql> show tables;
+--------------------------+
| Tables_in_delta_onazblob |
+--------------------------+
| person                   |
| referral                 |
+--------------------------+
2 rows in set (0.61 sec)
```

### Real behavior (Required)
show empty result.
While use shared key catalog, it shows two tables.
Ssing the same parameters, iceberg is OK, while Hudi also failed.
The fe.warn.log output error message as follow.

```
2023-12-14 07:49:30,969 ERROR (starrocks-mysql-nio-pool-0|121) [CachingHiveMetastore.get():525] Error occurred when loading cache
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.hudi.exception.HoodieIOException: Could not check if wasbs://container@account.blob.core.windows.net/datalake/hudi_onazblob.db/person is a valid table
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2085) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4011) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4034) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5010) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5017) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.get(CachingHiveMetastore.java:523) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.getTable(CachingHiveMetastore.java:252) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.hive.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:256) ~[starrocks-fe.jar:?]
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169) ~[spark-dpp-1.0.0.jar:?]
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
...
Caused by: org.apache.hudi.exception.HoodieIOException: Could not check if wasbs://container@account.blob.core.windows.net/datalake/hudi_onazblob.db/person is a valid table
	at org.apache.hudi.exception.TableNotFoundException.checkTableValidity(TableNotFoundException.java:59) ~[hudi-common-0.12.2.jar:0.12.2]
	at org.apache.hudi.common.table.HoodieTableMetaClient.<init>(HoodieTableMetaClient.java:128) ~[hudi-common-0.12.2.jar:0.12.2]
	at org.apache.hudi.common.table.HoodieTableMetaClient.newMetaClient(HoodieTableMetaClient.java:642) ~[hudi-common-0.12.2.jar:0.12.2]
	at org.apache.hudi.common.table.HoodieTableMetaClient.access$000(HoodieTableMetaClient.java:80) ~[hudi-common-0.12.2.jar:0.12.2]
...
Caused by: org.apache.hadoop.fs.azure.AzureException: java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.retrieveMetadata(AzureNativeFileSystemStore.java:2265) ~[hadoop-azure-3.3.6.jar:?]
	at org.apache.hadoop.fs.azure.NativeAzureFileSystem.getFileStatusInternal(NativeAzureFileSystem.java:2741) ~[hadoop-azure-3.3.6.jar:?]
	at org.apache.hadoop.fs.azure.NativeAzureFileSystem.existsInternal(NativeAzureFileSystem.java:2706) ~[hadoop-azure-3.3.6.jar:?]
	at org.apache.hadoop.fs.azure.NativeAzureFileSystem.conditionalRedoFolderRename(NativeAzureFileSystem.java:2797) ~[hadoop-azure-3.3.6.jar:?]
...
Caused by: java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
	at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:113) ~[azure-storage-7.0.1.jar:?]
	at org.apache.hadoop.fs.azure.StorageInterfaceImpl$WrappingIterator.hasNext(StorageInterfaceImpl.java:148) ~[hadoop-azure-3.3.6.jar:?]
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.retrieveMetadata(AzureNativeFileSystemStore.java:2244) ~[hadoop-azure-3.3.6.jar:?]
	at org.apache.hadoop.fs.azure.NativeAzureFileSystem.getFileStatusInternal(NativeAzureFileSystem.java:2741) ~[hadoop-azure-3.3.6.jar:?]
	at org.apache.hadoop.fs.azure.NativeAzureFileSystem.existsInternal(NativeAzureFileSystem.java:2706) ~[hadoop-azure-3.3.6.jar:?]
...
Caused by: com.microsoft.azure.storage.StorageException: This request is not authorized to perform this operation using this permission.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87) ~[azure-storage-7.0.1.jar:?]
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315) ~[azure-storage-7.0.1.jar:?]
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185) ~[azure-storage-7.0.1.jar:?]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 3.1.5-5d8438a |
+-------------------+
1 row in set (0.04 sec)
```

**Comment by Smith-Cruise** [comment]
plz check permission in sas token.

DeltaLake and Hudi required more permission than iceberg.

**Comment by neokjchen** [comment]
Yes,  DeltaLake/Hudi need addiontal list operation, while iceberg do not need.
