### ISSUE TITLE
Query for information_schema.stream_loads table threw NullPointerException when no label is specified

### ISSUE THREAD

**Issue by wxl24life** [StarRocks/starrocks#37357]
This bug is related to https://github.com/StarRocks/starrocks/pull/23649

### Steps to reproduce the behavior (Required)

1. create a stream load task
2. execute a query from information_schema.stream_loads

### Real behavior (Required)

![image](https://github.com/StarRocks/starrocks/assets/3615043/1c65b98a-1f5a-405a-923a-38ec04e05fb9)

```
2023-12-19 16:37:40,800 WARN (thrift-server-pool-355|1202) [FrontendServiceImpl.getStreamLoads():2604] Failed to getStreamLoads
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:?]
	at com.starrocks.load.streamload.StreamLoadMgr.getTaskByName(StreamLoadMgr.java:550) ~[starrocks-fe.jar:?]
	at com.starrocks.service.FrontendServiceImpl.getStreamLoads(FrontendServiceImpl.java:2596) ~[starrocks-fe.jar:?]
	at com.starrocks.thrift.FrontendService$Processor$getStreamLoads.getResult(FrontendService.java:3641) ~[starrocks-fe.jar:?]
	at com.starrocks.thrift.FrontendService$Processor$getStreamLoads.getResult(FrontendService.java:3621) ~[starrocks-fe.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.13.0.jar:0.13.0]
	at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
```

### StarRocks version (Required)
 - main branch

**Comment by wxl24life** [comment]
I will fix it
