### ISSUE TITLE
current node is not added to the cluster, will exit

### ISSUE THREAD

**Issue by digitalgust** [StarRocks/starrocks#38184]
start fe fail, the only one fe
### Steps to reproduce the behavior (Required)

./start_fe.sh --daemon
### StarRocks version (Required)
 -  3.2.1-79ee91d

###Log
```
2023-12-30 20:55:41,352 INFO (main|1) [StarRocksFE.start():129] StarRocks FE starting, version: 3.2.1-79ee91d
2023-12-30 20:55:41,360 INFO (main|1) [FrontendOptions.initAddrUseIp():249] Use IP init local addr, IP: /172.31.3.21
2023-12-30 20:55:41,714 INFO (main|1) [Auth.grantRoleInternal():837] grant operator to 'root'@'%', isReplay = true
2023-12-30 20:55:41,746 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():282] create built-in role root[-1]
2023-12-30 20:55:41,753 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():282] create built-in role db_admin[-2]
2023-12-30 20:55:41,754 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():282] create built-in role cluster_admin[-3]
2023-12-30 20:55:41,754 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():282] create built-in role user_admin[-4]
2023-12-30 20:55:41,755 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():282] create built-in role public[-5]
2023-12-30 20:55:41,755 INFO (main|1) [GlobalStateMgr.initAuth():1157] using new privilege framework..
2023-12-30 20:55:41,971 INFO (main|1) [NodeMgr.getHelperNodes():658] get helper nodes: [172.31.3.21:9010]
2023-12-30 20:55:41,987 INFO (main|1) [NodeMgr.getClusterIdAndRoleOnStartup():459] Current run_mode is shared_nothing
2023-12-30 20:55:41,987 INFO (main|1) [NodeMgr.getClusterIdAndRoleOnStartup():466] Got cluster id: 865615367, role: FOLLOWER, node name: 172.31.3.21_9010_1703338898971 and run_mode: shared_nothing
2023-12-30 20:55:41,988 INFO (main|1) [BDBEnvironment.ensureHelperInLocal():340] skip check local environment because helper node and local node are identical.
2023-12-30 20:55:42,007 INFO (main|1) [BDBEnvironment.setupEnvironment():269] start to setup bdb environment for 1 times
2023-12-30 20:55:42,604 WARN (UNKNOWN 172.31.3.21_9010_1703338898971(-1)|1) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: UNKNOWN
2023-12-30 20:55:42,691 INFO (UNKNOWN 172.31.3.21_9010_1703338898971(-1)|1) [BDBEnvironment.setupEnvironment():280] replicated environment is all set, wait for state change...
2023-12-30 20:55:42,699 WARN (RepNode 172.31.3.21_9010_1703338898971(-1)|62) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: LEADER
2023-12-30 20:55:43,691 INFO (UNKNOWN 172.31.3.21_9010_1703338898971(-1)|1) [BDBEnvironment.setupEnvironment():288] state change done, current role LEADER
2023-12-30 20:55:43,697 INFO (UNKNOWN 172.31.3.21_9010_1703338898971(-1)|1) [BDBEnvironment.setupEnvironment():292] end setup bdb environment after 1 times
2023-12-30 20:55:43,704 INFO (UNKNOWN 172.31.3.21_9010_1703338898971(-1)|1) [GlobalStateMgr.loadImage():1513] start load image from /data/ssdata/meta/image/image.174620. is ckpt: false
2023-12-30 20:55:43,704 WARN (UNKNOWN 172.31.3.21_9010_1703338898971(-1)|1) [GlobalStateMgr.loadImage():1670] load image eof.
java.io.EOFException: null
	at java.io.DataInputStream.readInt(DataInputStream.java:392) ~[?:1.8.0_392]
	at com.starrocks.server.GlobalStateMgr.loadVersion(GlobalStateMgr.java:1751) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1521) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1131) ~[starrocks-fe.jar:?]
	at com.starrocks.StarRocksFE.start(StarRocksFE.java:135) ~[starrocks-fe.jar:?]
	at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]
2023-12-30 20:55:43,711 WARN (UNKNOWN 172.31.3.21_9010_1703338898971(-1)|1) [GlobalStateMgr.loadImage():1676] follower has to wait for leader to upgrade the privileges, set usingNewPrivilege = false for now
2023-12-30 20:55:43,712 INFO (UNKNOWN 172.31.3.21_9010_1703338898971(-1)|1) [GlobalStateMgr.processMvRelatedMeta():1710] finish processing all tables' related materialized views in 0ms
2023-12-30 20:55:43,712 INFO (UNKNOWN 172.31.3.21_9010_1703338898971(-1)|1) [GlobalStateMgr.loadImage():1690] finished to load image in 8 ms
2023-12-30 20:55:43,713 INFO (stateChangeExecutor|70) [StateChangeExecutor.runOneCycle():85] begin to transfer FE type from INIT to UNKNOWN
2023-12-30 20:55:43,714 INFO (stateChangeExecutor|70) [StateChangeExecutor.runOneCycle():179] finished to transfer FE type from INIT to UNKNOWN
2023-12-30 20:55:43,714 INFO (stateChangeExecutor|70) [StateChangeExecutor.runOneCycle():85] begin to transfer FE type from INIT to LEADER
2023-12-30 20:55:43,720 INFO (stateChangeExecutor|70) [BDBHA.fencing():94] start fencing, epoch number is 20
2023-12-30 20:55:43,740 INFO (stateChangeExecutor|70) [GlobalStateMgr.replayJournal():2279] start to replay journal from 174621 to 174623
2023-12-30 20:55:43,742 INFO (stateChangeExecutor|70) [BDBJournalCursor.refresh():198] update dbnames null -> [174621]
2023-12-30 20:55:43,742 INFO (stateChangeExecutor|70) [BDBJournalCursor.calculateNextDbIndex():156] nextKey 174621, currentDatabase null, index of next opened db is 0
2023-12-30 20:55:43,742 INFO (stateChangeExecutor|70) [BDBJournalCursor.openDatabaseIfNecessary():232] open next database CloseSafeDatabase{db=174621}
2023-12-30 20:55:43,796 INFO (stateChangeExecutor|70) [BDBJournalCursor.next():268] cursor reaches the end: next key 174624 > to key 174623
2023-12-30 20:55:43,796 INFO (stateChangeExecutor|70) [GlobalStateMgr.replayJournalInner():2380] replayed journal from 174620 - 174623
2023-12-30 20:55:43,797 INFO (stateChangeExecutor|70) [GlobalStateMgr.replayJournal():2309] finish replay from 174621 to 174623 in 57 msec
2023-12-30 20:55:43,797 ERROR (stateChangeExecutor|70) [NodeMgr.checkCurrentNodeExist():700] current node is not added to the cluster, will exit


```

**Comment by digitalgust** [comment]
this is a test cluster, so reinstall the cluster , and setup 2 fe.

**Comment by slieer** [comment]
我也碰到这个错了，完全重建集群当然可以，但不是好办法啊。starrocks 集群自愈能力差吗？
