### ISSUE TITLE
[column_with_row] select NPE when enable_short_circuit = true

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#38515]
### Steps to reproduce the behavior (Required)
```
mysql> create table pk_tbl(c1 int, c2 date, c3 varchar(10), c4 boolean) primary key(c1,c2,c3) distributed by hash(c1,c2,c3) properties("storage_type"="column_with_row");
Query OK, 0 rows affected (0.01 sec)

mysql> select c1 || c2 from pk_tbl where c1=1 and c2='2023-01-01' and c3='Hello';
Empty set (0.01 sec)

mysql> set enable_short_circuit = true;
Query OK, 0 rows affected (0.00 sec)

mysql> select c1 || c2 from pk_tbl where c1=1 and c2='2023-01-01' and c3='Hello';
ERROR 1064 (HY000): Unknown error
```

fe.warn.log:
```
2024-01-05 11:15:30,612 WARN (starrocks-mysql-nio-pool-9|219) [StmtExecutor.execute():669] execute Exception, sql select c1 || c2 from pk_tbl where c1=1 and c2='2023-01-01' and c3='Hello'
java.lang.NullPointerException: null
        at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.hackTypeNull(ScalarOperatorToExpr.java:144) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitVariableReference(ScalarOperatorToExpr.java:168) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitVariableReference(ScalarOperatorToExpr.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:128) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.ScalarOperatorToExpr.buildExecExpression(ScalarOperatorToExpr.java:102) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder.lambda$createOutputFragment$1(PlanFragmentBuilder.java:299) ~[starrocks-fe.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder.createOutputFragment(PlanFragmentBuilder.java:301) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:225) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlanWithReTry(StatementPlanner.java:263) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.planQuery(StatementPlanner.java:159) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:127) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:487) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:381) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:573) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:852) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
main-ffd02c6
```

**Comment by tiannan-sr** [comment]
```
mysql> set enable_short_circuit = false;
Query OK, 0 rows affected (0.00 sec)

mysql> select c1,c2 from pk_tbl where c1=1 and c2='2023-01-01' and c3='Hello';
Empty set (0.00 sec)

mysql> set enable_short_circuit = true;
Query OK, 0 rows affected (0.00 sec)

mysql> select c1,c2 from pk_tbl where c1=1 and c2='2023-01-01' and c3='Hello';
ERROR 1064 (HY000): USER_CANCEL
mysql>
```

fe.warn.log:
```
2024-01-05 11:19:36,097 WARN (starrocks-mysql-nio-pool-10|227) [StmtExecutor.execute():669] execute Exception, sql select c1,c2 from pk_tbl where c1=1 and c2='2023-01-01' and c3='Hello'
java.lang.NullPointerException: null
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:1057) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:556) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:381) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:573) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:852) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2024-01-05 11:19:36,097 WARN (starrocks-mysql-nio-pool-10|227) [DefaultCoordinator.cancel():827] cancel execState of query, this is outside invoke
```
