### ISSUE TITLE
Can not activate materialized view inactivated by swapping a base table

### ISSUE THREAD

**Issue by fzn0268** [StarRocks/starrocks#38535]
### Steps to reproduce the behavior (Required)
1. Install 3.1.4 with shared-data deployment
2. CREATE TABLE a (id bigint NOT NULL, b_id bigint bigint NOT NULL, tag VARCHAR(255) NULL, update_time datetime DEFAULT CURRENT_TIMESTAMP) PRIMARY KEY (id, update_time) PARTITION BY RANGE (update_time) (START ("2020-01-01") END ("2023-12-01") EVERY (INTERVAL 1 MONTH)) DISTRIBUTED BY HASH (id) BUCKETS 1 PROPERTIES ("replication_num" = "1","enable_persistent_index" = "true","enable_async_write_back" = "false","datacache.enable" = "true","dynamic_partition.enable" = "true","dynamic_partition.time_unit" = "MONTH","dynamic_partition.end" = "2");
3. CREATE TABLE b (id bigint NOT NULL, name VARCHAR(255) NULL, create_time datetime DEFAULT CURRENT_TIMESTAMP, update_time datetime DEFAULT CURRENT_TIMESTAMP) PRIMARY KEY (id, create_time) PARTITION BY RANGE (create_time) (START ("2020-01-01") END ("2023-12-01") EVERY (INTERVAL 1 MONTH)) DISTRIBUTED BY HASH (id) BUCKETS 1 PROPERTIES ("replication_num" = "1","enable_persistent_index" = "true","enable_async_write_back" = "false","datacache.enable" = "true","dynamic_partition.enable" = "true","dynamic_partition.time_unit" = "MONTH","dynamic_partition.end" = "2");
4. CREATE MATERIALIZED VIEW test_mv DISTRIBUTED BY HASH(id) BUCKETS 1 REFRESH IMMEDIATE ASYNC START ('2024-01-01 00:00:00') EVERY(INTERVAL 1 HOUR) PARTITION BY date_trunc("MONTH",create_time) PROPERTIES ("replication_num" = "1","partition_ttl_number" = "-1","partition_refresh_number" = "1","excluded_trigger_tables" = "a") AS SELECT b.id, b.name, a.tag, b.create_time, b.update_time FROM a LEFT JOIN b ON b.id = a.b_id;
5. Upgrade from 3.1.4 to 3.1.6
6. CREATE TABLE a2 (id bigint NOT NULL, b_id bigint bigint NOT NULL, tag VARCHAR(255) NULL, update_time datetime DEFAULT CURRENT_TIMESTAMP) PRIMARY KEY (id) DISTRIBUTED BY HASH (id) BUCKETS 12 PROPERTIES ("replication_num" = "1","enable_persistent_index" = "true","enable_async_write_back" = "false","datacache.enable" = "true");
7. ALTER TABLE a SWAP WITH a2;
8. REFRESH MATERIALIZED VIEW test_mv FORCE WITH ASYNC MODE; -- failed, error message inform me to activate
9. ALTER MATERIALIZED VIEW test_mv ACTIVE;

### Expected behavior (Required)
"test_mv" materialized view is activated.

### Real behavior (Required)
DDL statement (ALTER MATERIALIZED VIEW test_mv active) process failed.
java.util.UnknownFormatConversionException: Conversion = 'Y'
        at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2839) ~[?:?]
        at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2865) ~[?:?]
        at java.util.Formatter.parse(Formatter.java:2713) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2655) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2609) ~[?:?]
        at java.lang.String.format(String.java:2897) ~[?:?]
        at com.starrocks.sql.analyzer.SemanticException.<init>(SemanticException.java:53) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.AlterJobMgr.processChangeMaterializedViewStatus(AlterJobMgr.java:416) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.AlterJobMgr.processChangeMaterializedViewStatus(AlterJobMgr.java:374) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.AlterJobMgr.processAlterMaterializedView(AlterJobMgr.java:349) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.alterMaterializedView(LocalMetastore.java:3382) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.alterMaterializedView(GlobalStateMgr.java:3417) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.lambda$visitAlterMaterializedViewStatement$10(DDLStmtExecutor.java:293) ~[starrocks-fe.jar:?]
        at com.starrocks.common.ErrorReport.wrapWithRuntimeException(ErrorReport.java:112) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitAlterMaterializedViewStatement(DDLStmtExecutor.java:292) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitAlterMaterializedViewStatement(DDLStmtExecutor.java:152) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AlterMaterializedViewStmt.accept(AlterMaterializedViewStmt.java:87) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor.execute(DDLStmtExecutor.java:138) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1459) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:646) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectContext.executeSql(ConnectContext.java:817) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.MVActiveChecker.tryToActivate(MVActiveChecker.java:126) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.MVActiveChecker.process(MVActiveChecker.java:91) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.MVActiveChecker.runAfterCatalogReady(MVActiveChecker.java:65) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.FrontendDaemon.runOneCycle(FrontendDaemon.java:72) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) ~[starrocks-fe.jar:?]

### StarRocks version (Required)
 3.1.6

**Comment by mofeiatwork** [comment]
fixed by https://github.com/StarRocks/starrocks/pull/38008
