### ISSUE TITLE
AddressSanitizer: stack-use-after-return

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#39117]
```
==3522591==ERROR: AddressSanitizer: stack-use-after-return on address 0x7faf5685a3a0 at pc 0x000012bca484 bp 0x7faf57563a80 sp 0x7faf57563a78
READ of size 8 at 0x7faf5685a3a0 thread T1641 (clound_native_c)
    #0 0x12bca483 in starrocks::PageIO::read_and_decompress_page(starrocks::PageReadOptions const&, starrocks::PageHandle*, starrocks::Slice*, starrocks::PageFooterPB*) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/page_io.cpp:138
    #1 0x12e1d541 in starrocks::OrdinalIndexReader::_do_load(starrocks::IndexReadOptions const&, starrocks::OrdinalIndexPB const&, unsigned long) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/ordinal_page_index.cpp:127
    #2 0x12e1c7fa in operator() /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/ordinal_page_index.cpp:89
    #3 0x12e1efb6 in __invoke_impl<starrocks::Status, starrocks::OrdinalIndexReader::load(const starrocks::IndexReadOptions&, const starrocks::OrdinalIndexPB&, starrocks::ordinal_t)::<lambda()> > /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #4 0x12e1ef61 in __invoke<starrocks::OrdinalIndexReader::load(const starrocks::IndexReadOptions&, const starrocks::OrdinalIndexPB&, starrocks::ordinal_t)::<lambda()> > /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:96
    #5 0x12e1e871 in invoke<starrocks::OrdinalIndexReader::load(const starrocks::IndexReadOptions&, const starrocks::OrdinalIndexPB&, starrocks::ordinal_t)::<lambda()> > /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:89
    #6 0x12e1ebfe in success_once<starrocks::OrdinalIndexReader::load(const starrocks::IndexReadOptions&, const starrocks::OrdinalIndexPB&, starrocks::ordinal_t)::<lambda()> > /home/disk3/zhuming/celerdata-enterprise/be/src/util/once.h:81
    #7 0x12e1ca8a in starrocks::OrdinalIndexReader::load(starrocks::IndexReadOptions const&, starrocks::OrdinalIndexPB const&, unsigned long) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/ordinal_page_index.cpp:97
    #8 0x1326cbf3 in starrocks::ColumnReader::load_ordinal_index(starrocks::IndexReadOptions const&) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/column_reader.cpp:364
    #9 0x132517e4 in starrocks::ScalarColumnIterator::init(starrocks::ColumnIteratorOptions const&) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/scalar_column_iterator.cpp:58
    #10 0x132c24da in starrocks::SegmentIterator::_init_column_iterator_by_cid(unsigned int, int, bool) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/segment_iterator.cpp:541
    #11 0x132eb8ec in starrocks::Status starrocks::SegmentIterator::_init_column_iterators<true>(starrocks::Schema const&) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/segment_iterator.cpp:575
    #12 0x132be682 in starrocks::SegmentIterator::_init() /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/segment_iterator.cpp:411
    #13 0x132ca592 in starrocks::SegmentIterator::do_get_next(starrocks::Chunk*) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/segment_iterator.cpp:955
    #14 0x1197fd01 in starrocks::ChunkIterator::get_next(starrocks::Chunk*) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/chunk_iterator.h:52
    #15 0x13544914 in starrocks::lake::CompactionState::_load_segments(starrocks::lake::Rowset*, std::shared_ptr<starrocks::TabletSchema const> const&, unsigned int) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/lake/update_compaction_state.cpp:87
    #16 0x13543b82 in starrocks::lake::CompactionState::load_segments(starrocks::lake::Rowset*, starrocks::lake::UpdateManager*, std::shared_ptr<starrocks::TabletSchema const> const&, unsigned int) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/lake/update_compaction_state.cpp:52
    #17 0x134e2882 in starrocks::lake::UpdateManager::preload_compaction_state(starrocks::lake::TxnLogPB const&, starrocks::lake::Tablet const&, std::shared_ptr<starrocks::TabletSchema const> const&) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/lake/update_manager.cpp:748
    #18 0x15c0feeb in starrocks::lake::VerticalCompactionTask::execute(starrocks::lake::CompactionTask::Progress*, std::function<bool ()>) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/lake/vertical_compaction_task.cpp:105
    #19 0x15c3816b in starrocks::lake::CompactionScheduler::do_compaction(std::unique_ptr<starrocks::lake::CompactionTaskContext, std::default_delete<starrocks::lake::CompactionTaskContext> >) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/lake/compaction_scheduler.cpp:218
    #20 0x15c374d6 in starrocks::lake::CompactionScheduler::thread_task(int) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/lake/compaction_scheduler.cpp:181
    #21 0x15c351be in operator() /home/disk3/zhuming/celerdata-enterprise/be/src/storage/lake/compaction_scheduler.cpp:102
    #22 0x15c3b7f9 in __invoke_impl<void, starrocks::lake::CompactionScheduler::CompactionScheduler(starrocks::lake::TabletManager*)::<lambda()>&> /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #23 0x15c3b369 in __invoke_r<void, starrocks::lake::CompactionScheduler::CompactionScheduler(starrocks::lake::TabletManager*)::<lambda()>&> /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:110
    #24 0x15c3ada4 in _M_invoke /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:291
    #25 0xf5c1997 in std::function<void ()>::operator()() const /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
    #26 0x19015527 in starrocks::FunctionRunnable::run() /home/disk3/zhuming/celerdata-enterprise/be/src/util/threadpool.cpp:59
    #27 0x1901217e in starrocks::ThreadPool::dispatch_thread() /home/disk3/zhuming/celerdata-enterprise/be/src/util/threadpool.cpp:562
    #28 0x1902e7e9 in void std::__invoke_impl<void, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(std::__invoke_memfun_deref, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:73
    #29 0x1902e2d4 in std::__invoke_result<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>::type std::__invoke<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:95
    #30 0x1902d21d in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:416
    #31 0x1902c18b in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::operator()<, void>() /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:499
    #32 0x19029cff in void std::__invoke_impl<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #33 0x19026707 in std::enable_if<is_invocable_r_v<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:110
    #34 0x19022a90 in std::_Function_handler<void (), std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:291
    #35 0xf5c1997 in std::function<void ()>::operator()() const /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
    #36 0x18ff976e in starrocks::Thread::supervise_thread(void*) /home/disk3/zhuming/celerdata-enterprise/be/src/util/thread.cpp:365
    #37 0x7fb6e3586ea4 in start_thread (/lib64/libpthread.so.0+0x7ea4)
    #38 0x7fb6e32afb0c in clone (/lib64/libc.so.6+0xfeb0c)

Address 0x7faf5685a3a0 is located in stack of thread T1641 (clound_native_c) at offset 928 in frame
    #0 0x13543e15 in starrocks::lake::CompactionState::_load_segments(starrocks::lake::Rowset*, std::shared_ptr<starrocks::TabletSchema const> const&, unsigned int) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/lake/update_compaction_state.cpp:57

  This frame has 16 object(s):
    [32, 33) '<unknown>'
    [48, 52) '<unknown>'
    [64, 72) 'pk_column' (line 65)
    [96, 104) '<unknown>'
    [128, 136) '<unknown>'
    [160, 168) '<unknown>'
    [192, 200) '<unknown>'
    [224, 232) 'chunk_shared_ptr' (line 75)
    [256, 264) 'col' (line 83)
    [288, 296) 'st' (line 87)
    [320, 336) '<unknown>'
    [352, 368) '<unknown>'
    [384, 408) 'pk_columns' (line 58)
    [448, 480) '<unknown>'
    [512, 608) 'pkey_schema' (line 63)
    [640, 1112) 'stats' (line 68) <== Memory access at offset 928 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T1641 (clound_native_c) created by T0 here:
    #0 0xf4e6512 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:214
    #1 0x18ff8b06 in starrocks::Thread::start_thread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, unsigned long, scoped_refptr<starrocks::Thread>*) /home/disk3/zhuming/celerdata-enterprise/be/src/util/thread.cpp:320
    #2 0x19018cde in starrocks::Status starrocks::Thread::create<void (starrocks::ThreadPool::*)(), starrocks::ThreadPool*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void (starrocks::ThreadPool::* const&)(), starrocks::ThreadPool* const&, scoped_refptr<starrocks::Thread>*) /home/disk3/zhuming/celerdata-enterprise/be/src/util/thread.h:71
    #3 0x19013469 in starrocks::ThreadPool::create_thread() /home/disk3/zhuming/celerdata-enterprise/be/src/util/threadpool.cpp:615
    #4 0x1900c716 in starrocks::ThreadPool::init() /home/disk3/zhuming/celerdata-enterprise/be/src/util/threadpool.cpp:270
    #5 0x190093c1 in starrocks::ThreadPoolBuilder::build(std::unique_ptr<starrocks::ThreadPool, std::default_delete<starrocks::ThreadPool> >*) const /home/disk3/zhuming/celerdata-enterprise/be/src/util/threadpool.cpp:96
    #6 0x15c3575d in starrocks::lake::CompactionScheduler::CompactionScheduler(starrocks::lake::TabletManager*) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/lake/compaction_scheduler.cpp:98
    #7 0x1343a7e0 in std::_MakeUniq<starrocks::lake::CompactionScheduler>::__single_object std::make_unique<starrocks::lake::CompactionScheduler, starrocks::lake::TabletManager*>(starrocks::lake::TabletManager*&&) /home/disk1/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/unique_ptr.h:962
    #8 0x13421a81 in starrocks::lake::TabletManager::TabletManager(starrocks::lake::LocationProvider*, starrocks::lake::UpdateManager*, long) /home/disk3/zhuming/celerdata-enterprise/be/src/storage/lake/tablet_manager.cpp:67
    #9 0xfad0335 in starrocks::ExecEnv::init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&, bool) /home/disk3/zhuming/celerdata-enterprise/be/src/runtime/exec_env.cpp:481
    #10 0x18c3b2ce in starrocks::start_be(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&, bool) /home/disk3/zhuming/celerdata-enterprise/be/src/service/service_be/starrocks_be.cpp:164
    #11 0xf57c77e in main /home/disk3/zhuming/celerdata-enterprise/be/src/service/starrocks_main.cpp:250
    #12 0x7fb6e31d3554 in __libc_start_main (/lib64/libc.so.6+0x22554)

SUMMARY: AddressSanitizer: stack-use-after-return /home/disk3/zhuming/celerdata-enterprise/be/src/storage/rowset/page_io.cpp:138 in starrocks::PageIO::read_and_decompress_page(starrocks::PageReadOptions const&, starrocks::PageHandle*, starrocks::Slice*, starrocks::PageFooterPB*)
Shadow bytes around the buggy address:
  0x0ff66ad03420: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff66ad03430: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff66ad03440: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff66ad03450: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff66ad03460: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x0ff66ad03470: f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff66ad03480: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff66ad03490: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff66ad034a0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff66ad034b0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff66ad034c0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3522591==ABORTING
```

### StarRocks version (Required)
 - 3.2.1-ee

**Comment by luohaha** [comment]
https://github.com/StarRocks/starrocks/pull/39125
