### ISSUE TITLE
Can't use python sqlalchemy to create table

### ISSUE THREAD

**Issue by singrockzhou** [StarRocks/starrocks#39179]
Can't use python sqlalchemy to create table,
python verison is 3.11.5,   the follow is the python code
---------------------------------------------------------------------------------
from sqlalchemy import create_engine, UniqueConstraint, Index
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String

engine = create_engine('mysql+pymysql://root:@localhost:9030/zhou')
#engine = create_engine('mysql+pymysql://root:123456@localhost:3306/zhou')
Base = declarative_base()

class User(Base):
    __tablename__ = 'beijing'
    uid = Column(Integer, primary_key=True)
    name = Column(String(20))
    age = Column(Integer)
    __table_args__ = {'mysql_engine': 'OLAP'}

Base.metadata.create_all(engine)
---------------------------------------------------------------------------------

The error is :

(guoxiang) root@ubuntu2004:~/guoxiang/starrocks# python create1.py 
/root/guoxiang/starrocks/create1.py:8: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()
Traceback (most recent call last):
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "Getting analyzing error. Detail message: Unknown table 'beijing'.")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/guoxiang/starrocks/create1.py", line 17, in <module>
    Base.metadata.create_all(engine)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 5832, in create_all
    bind._run_ddl_visitor(
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3244, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2448, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 671, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 898, in visit_metadata
    [t for t in tables if self._can_create_table(t)]
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 898, in <listcomp>
    [t for t in tables if self._can_create_table(t)]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 863, in _can_create_table
    return not self.checkfirst or not self.dialect.has_table(
                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in has_table
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 88, in cache
    return fn(self, con, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/base.py", line 2748, in has_table
    with connection.exec_driver_sql(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1778, in exec_driver_sql
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "Getting analyzing error. Detail message: Unknown table 'beijing'.")
[SQL: DESCRIBE `zhou`.`beijing`]
(Background on this error at: https://sqlalche.me/e/20/f405)

-----------------------------

use the same code,  I connect the MySQL， create table 'beijing' is ok.

Waiting for your HELP,  thank you!

**Comment by singrockzhou** [comment]
Also, if I select a non-exist table from Mysql and Starrocks，the result is diffence

In MySQL:

mysql> select * from aaa;
ERROR 1146 (42S02): Table 'zhou.aaa' doesn't exist
mysql> 


In Starrocks:

StarRocks > select * from aaa;
ERROR 1064 (HY000): Getting analyzing error. Detail message: Unknown table 'zhou.aaa'.
StarRocks >

**Comment by singrockzhou** [comment]
Starrocks  start by  [starrocks/allin1-ubuntu:latest], Version: 3.2.2-269e832,  follow is version log:


root@ubuntu2004:~/dev/src# docker logs -f starrocks 
****************************************************************************************************
*   ________  _________  ________  ________  ________  ________  ________  ___  __    ________      
*  |\   ____\|\___   ___\\   __  \|\   __  \|\   __  \|\   __  \|\   ____\|\  \|\  \ |\   ____\     
*  \ \  \___|\|___ \  \_\ \  \|\  \ \  \|\  \ \  \|\  \ \  \|\  \ \  \___|\ \  \/  /|\ \  \___|_    
*   \ \_____  \   \ \  \ \ \   __  \ \   _  _\ \   _  _\ \  \\\  \ \  \    \ \   ___  \ \_____  \   
*    \|____|\  \   \ \  \ \ \  \ \  \ \  \\  \\ \  \\  \\ \  \\\  \ \  \____\ \  \\ \  \|____|\  \  
*      ____\_\  \   \ \__\ \ \__\ \__\ \__\\ _\\ \__\\ _\\ \_______\ \_______\ \__\\ \__\____\_\  \ 
*     |\_________\   \|__|  \|__|\|__|\|__|\|__|\|__|\|__|\|_______|\|_______|\|__| \|__|\_________\
*     \|_________|                                                                      \|_________|
*
*                      ________  ___       ___       ___  ________     _____
*                     |\   __  \|\  \     |\  \     |\  \|\   ___  \  / __  \
*                     \ \  \|\  \ \  \    \ \  \    \ \  \ \  \\ \  \|\/_|\  \
*                      \ \   __  \ \  \    \ \  \    \ \  \ \  \\ \  \|/ \ \  \
*                       \ \  \ \  \ \  \____\ \  \____\ \  \ \  \\ \  \   \ \  \
*                        \ \__\ \__\ \_______\ \_______\ \__\ \__\\ \__\   \ \__\
*                         \|__|\|__|\|_______|\|_______|\|__|\|__| \|__|    \|__|
*
****************************************************************************************************

StarRocks [(Blazing Fast)]> _


2024-01-09 09:20:57,029 INFO Set uid to user 0 succeeded
2024-01-09 09:20:57,031 INFO RPC interface 'supervisor' initialized
2024-01-09 09:20:57,031 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-01-09 09:20:57,031 INFO supervisord started with pid 6
2024-01-09 09:20:58,037 INFO spawned: 'beservice' with pid 524
2024-01-09 09:20:58,039 INFO spawned: 'broker' with pid 525
2024-01-09 09:20:58,041 INFO spawned: 'director' with pid 526
2024-01-09 09:20:58,042 INFO spawned: 'feproxy' with pid 527
2024-01-09 09:20:58,043 INFO spawned: 'feservice' with pid 528
2024-01-09 09:20:58+00:00 INFO checking if need to perform auto registring Backend and Broker ...
2024-01-09 09:20:58+00:00 INFO checking if FE service query port:9030 alive or not ...
2024-01-09 09:20:58+00:00 WARN FE service query port:9030 is NOT alive yet!
2024-01-09 09:21:00+00:00 WARN FE service query port:9030 is NOT alive yet!
2024-01-09 09:21:02+00:00 WARN FE service query port:9030 is NOT alive yet!
2024-01-09 09:21:03,203 INFO success: beservice entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2024-01-09 09:21:03,203 INFO success: broker entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2024-01-09 09:21:03,203 INFO success: director entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2024-01-09 09:21:03,204 INFO success: feproxy entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2024-01-09 09:21:03,204 INFO success: feservice entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2024-01-09 09:21:04+00:00 WARN FE service query port:9030 is NOT alive yet!
2024-01-09 09:21:06+00:00 WARN FE service query port:9030 is NOT alive yet!
2024-01-09 09:21:08+00:00 INFO FE service query port:9030 is alive!
2024-01-09 09:21:08+00:00 INFO generate my.cnf file ...
2024-01-09 09:21:08+00:00 INFO check if need to add BE into FE service ...
2024-01-09 09:21:09+00:00 INFO Add BE(127.0.0.1:9050) into FE service ...

2024-01-09 09:21:09+00:00 INFO BE service already added into FE service ... 
2024-01-09 09:21:09+00:00 INFO check if need to add BROKER into FE service ...
2024-01-09 09:21:09+00:00 INFO Add BROKER(127.0.0.1:8000) into FE service ...

2024-01-09 09:21:09+00:00 INFO broker service already added into FE service ... 
2024-01-09 09:21:09+00:00 INFO cluster initialization DONE!
2024-01-09 09:21:09+00:00 INFO wait a few seconds for BE and Broker's heartbeat ...
2024-01-09 09:21:19+00:00 INFO StarRocks Cluster information details:
*************************** 1. row ***************************
             Name: 127.0.0.1_9010_1704792059629
               IP: 127.0.0.1
      EditLogPort: 9010
         HttpPort: 8030
        QueryPort: 9030
          RpcPort: 9020
             Role: LEADER
        ClusterId: 1798960351
             Join: true
            Alive: true
ReplayedJournalId: 16
    LastHeartbeat: 2024-01-09 09:21:20
         IsHelper: true
           ErrMsg: 
        StartTime: 2024-01-09 09:21:06
          Version: 3.2.2-269e832
*************************** 1. row ***************************
            BackendId: 10004
                   IP: 127.0.0.1
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-01-09 09:21:10
        LastHeartbeat: 2024-01-09 09:21:20
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
            TabletNum: 0
     DataUsedCapacity: 0.000 B
        AvailCapacity: 1.428 TB
        TotalCapacity: 1.572 TB
              UsedPct: 9.14 %
       MaxDiskUsedPct: 9.14 %
               ErrMsg: 
              Version: 3.2.2-269e832
               Status: {"lastSuccessReportTabletsTime":"2024-01-09 09:21:10"}
    DataTotalCapacity: 1.428 TB
          DataUsedPct: 0.00 %
             CpuCores: 16
    NumRunningQueries: 0
           MemUsedPct: 0.19 %
           CpuUsedPct: 0.0 %
*************************** 1. row ***************************
          Name: allin1broker
            IP: 127.0.0.1
          Port: 8000
         Alive: true
 LastStartTime: 2024-01-09 09:21:10
LastUpdateTime: 2024-01-09 09:21:20
        ErrMsg: 
2024-01-09 09:21:21+00:00 INFO 
2024-01-09 09:21:21+00:00 INFO 
2024-01-09 09:21:21+00:00 INFO  * IMPORTANT NOTICE!

If FE/BE state needs to be persisted, please be sure the following directories are mounted:
* FE service meta: /data/deploy/starrocks/fe/meta
* BE service storage: /data/deploy/starrocks/be/storage

2024-01-09 09:21:21+00:00 INFO 
2024-01-09 09:21:21+00:00 INFO FE mysql query port: 9030
2024-01-09 09:21:21+00:00 INFO FE http service port: 8080
2024-01-09 09:21:21+00:00 INFO 
2024-01-09 09:21:21+00:00 INFO Enjoy the journal to StarRocks blazing-fast lake-house engine!

**Comment by rad-pat** [comment]
If you use the starrocks dialect itself, then an exception is not raised for `has_table` when tables do not exist as it has a specific implementation override to the mysql dialect
https://github.com/StarRocks/starrocks/blob/df32193f7e84dd6938041558ae868cc17986b28d/contrib/starrocks-python-client/starrocks/sqlalchemy/dialect.py#L39

Your exception is raised when using the mysql implementation of `has_table` as shown in the Traceback
```
File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/base.py", line 2748, in has_table
with connection.exec_driver_sql(
```
Try `pip install starrocks` and then use connection string: `starrocks://root:@localhost:9030/zhou` and see if problem persists.

**Comment by singrockzhou** [comment]
I use starrocks，but got the follow error:
--------------------------------------------------
at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()
Traceback (most recent call last):
  File "/root/guoxiang/starrocks/create2.py", line 45, in <module>
    create_all()
  File "/root/guoxiang/starrocks/create2.py", line 22, in create_all
    engine = create_engine(
             ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 150, in dbapi
    return __import__("MySQLdb")
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/MySQLdb/__init__.py", line 17, in <module>
    from . import _mysql
ImportError: /root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/MySQLdb/_mysql.cpython-311-x86_64-linux-gnu.so: undefined symbol: mysql_real_escape_string_quote

--------------------------------------

the code is:

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column
from sqlalchemy import Integer,String,Text,Date,DateTime
from sqlalchemy import create_engine


Base = declarative_base()

class Users(Base):
    __tablename__ = 'classmate112'

    #id = Column(Integer, primary_key=True)
    id = Column(Integer, primary_key=True)
    name = Column(String(32), index=True, nullable=False)

    #__table_args__ = (
    #   PrimaryKeyConstraint('id'),
    #)


def create_all():
    engine = create_engine(
        #"mysql+pymysql://root:123456@127.0.0.1:3306/zhou?charset=utf8",
        #"mysql+pymysql://root:@127.0.0.1:9030/zhou?charset=utf8",
        "starrocks://root:@127.0.0.1:9030/zhou?charset=utf8",
        max_overflow=0,  
        pool_size=5, 
        pool_timeout=30,  
        pool_recycle=-1
    )

    Base.metadata.create_all(engine)

def drop_all():
    engine = create_engine(
        "mysql+pymysql://root:123456@127.0.0.1:3306/zhou?charset=utf8",
        max_overflow=0,  
        pool_size=5,  
        pool_timeout=30, 
        pool_recycle=-1 
    )
    Base.metadata.drop_all(engine)

if __name__ == '__main__':
    create_all()

---------------
environment is:

(guoxiang) root@ubuntu2004:~/guoxiang/starrocks# pip show starrocks
Name: starrocks
Version: 1.0.5
Summary: Python interface to StarRocks
Home-page: https://github.com/StarRocks/starrocks
Author: StarRocks Team
Author-email:
License: Apache 2.0
Location: /root/miniconda3/envs/guoxiang/lib/python3.11/site-packages
Requires: mysqlclient, sqlalchemy, sqlalchemy-utils
Required-by:
(guoxiang) root@ubuntu2004:~/guoxiang/starrocks# pip show mysqlclient
Name: mysqlclient
Version: 2.2.1
Summary: Python interface to MySQL
Home-page:
Author:
Author-email: Inada Naoki <songofacandy@gmail.com>
License: GNU General Public License v2 (GPLv2)
Location: /root/miniconda3/envs/guoxiang/lib/python3.11/site-packages
Requires:
Required-by: starrocks
(guoxiang) root@ubuntu2004:~/guoxiang/starrocks# pip show sqlalchemy
Name: SQLAlchemy
Version: 1.4.51
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: /root/miniconda3/envs/guoxiang/lib/python3.11/site-packages
Requires: greenlet
Required-by: Flask-SQLAlchemy, langchain, langchain-community, SQLAlchemy-Utils, starrocks
(guoxiang) root@ubuntu2004:~/guoxiang/starrocks#

python -V
Python 3.11.5

**Comment by singrockzhou** [comment]
So, use the sqlalchemy can't create table in starrocks, can only SELECT、UPDATE、DELETE in a exist table ??

**Comment by rad-pat** [comment]
@singrockzhou, after trying to use the dialect within our application, I find that it is also not fit for purpose. There are many things missing from it, most notably any sqlalchemy testing. I now have the need to create and reflect tables and am currently writing something that will get this done. I will try to put this as a PR for Starrocks and let you know where it resides so you may also use it.

**Comment by singrockzhou** [comment]
@rad-pat  thank you.

**Comment by singrockzhou** [comment]
use another way to create table, still got error.

the follow is code:
----------------------------
import sqlalchemy
from sqlalchemy import *
from sqlalchemy_utils import database_exists, create_database


def init_sqlalchemy(dburl,echo=True):
    engine = create_engine(dburl,echo=echo)

    if not database_exists(engine.url):###确保目标数据库是存在的。
        create_database(engine.url)

    metadata = MetaData(bind = engine)
    return engine,metadata

engine,db = init_sqlalchemy('mysql+pymysql://root:@127.0.0.1:9030/zhou?charset=utf8')

try:
    users = Table('users',db,autoload=True)
except sqlalchemy.exc.NoSuchTableError:
    users = Table('users', db,
    Column('id', Integer, primary_key=True),
    Column('name', String(40)),
    Column('age', Integer),
    Column('password', String),
)

users.create(checkfirst=True)
----------------------------

Error is here:

----------------------------
Traceback (most recent call last):
  File "/root/guoxiang/starrocks/create4.py", line 18, in <module>
    users = Table('users',db,autoload=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in __new__
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 618, in __new__
    with util.safe_reraise():
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 757, in reflect_table
    tbl_opts = self.get_table_options(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 398, in get_table_options
    return self.dialect.get_table_options(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get_table_options
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/base.py", line 2828, in get_table_options
    parsed_state = self._parsed_state_or_create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/base.py", line 3085, in _parsed_state_or_create
    return self._setup_parser(
           ^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _setup_parser
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/base.py", line 3112, in _setup_parser
    sql = self._show_create_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/base.py", line 3220, in _show_create_table
    ).exec_driver_sql(st)
      ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1770, in exec_driver_sql
    return self._exec_driver_sql(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1674, in _exec_driver_sql
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "Unknown table 'users'")
[SQL: SHOW CREATE TABLE `users`]
(Background on this error at: https://sqlalche.me/e/14/f405)

----------------------------

**Comment by rad-pat** [comment]
@singrockzhou, try this version of the dialect. This is where I have been working on improvements before sharing back to main repo. It is not complete at all (quite a number of test failures), but it may do what you need. https://github.com/rad-pat/sqlalchemy-starrocks

Any help also appreciated 😃

**Comment by singrockzhou** [comment]
> @singrockzhou, try this version of the dialect. This is where I have been working on improvements before sharing back to main repo. It is not complete at all (quite a number of test failures), but it may do what you need. https://github.com/rad-pat/sqlalchemy-starrocks
> 
> Any help also appreciated 😃

Thanks so much.
I use your sqlalchemy-starroks to replace the env folder: /root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/starrocks



(guoxiang) root@ubuntu2004:~/guoxiang/starrocks# ls /root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/starrocks -l
total 76
-rw-r--r-- 1 root root  4140 Jan 31 01:58 datatype.py
-rw-r--r-- 1 root root 17164 Jan 31 01:58 dialect.py
-rw-r--r-- 1 root root   783 Jan 31 01:58 __init__.py
-rw-r--r-- 1 root root  2749 Jan 31 01:58 provision.py
drwxr-xr-x 2 root root  4096 Jan 31 01:58 __pycache__
-rw-r--r-- 1 root root 28670 Jan 31 01:58 reflection.py
-rw-r--r-- 1 root root  4998 Jan 31 01:58 requirements.py
(guoxiang) root@ubuntu2004:~/guoxiang/starrocks#




there ars still many errors:

(guoxiang) root@ubuntu2004:~/guoxiang/starrocks# python create2.py
/root/guoxiang/starrocks/create2.py:8: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()
Traceback (most recent call last):
  File "/root/guoxiang/starrocks/create2.py", line 46, in <module>
    create_all()
  File "/root/guoxiang/starrocks/create2.py", line 23, in create_all
    engine = create_engine(
             ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    entrypoint = u._get_entrypoint()
                 ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/engine/url.py", line 662, in _get_entrypoint
    cls = registry.load(name)
          ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 341, in load
    return impl.load()
           ^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/guoxiang/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'starrocks.sqlalchemy'
(guoxiang) root@ubuntu2004:~/guoxiang/starrocks#

**Comment by rad-pat** [comment]
Yes, as it currently stands, it is not a direct replacement for package `starrocks` because it now adheres to sqlalchemy dialect specification. It is called `sqlalchemy-starrocks` so I would `pip uninstall starrocks` and `pip install git+https://github.com/rad-pat/sqlalchemy-starrocks.git@main` to prevent any overlap
