### ISSUE TITLE
Fe startup failure: java.lang.IllegalStateException: null

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#3952]
### Steps to reproduce the behavior (Required)
Do schema change concurrently.

### Expected behavior (Required)
start success.
### Real behavior (Required)
```java
2022-04-01 04:45:13,819 ERROR (stateListener|70) [EditLog.loadJournal():821] Operation Type 42
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.catalog.TabletInvertedIndex.addReplica(TabletInvertedIndex.java:454) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Tablet.addReplica(Tablet.java:152) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Tablet.addReplica(Tablet.java:158) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.unprotectAddReplica(Catalog.java:4821) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayAddReplica(Catalog.java:4841) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:385) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2481) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.transferToMaster(Catalog.java:1220) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.access$800(Catalog.java:287) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$4.runOneCycle(Catalog.java:2398) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 40d791d

**Comment by gengjun-git** [comment]
Schema change has two main step:
1. pending: add shadow index's tablet to the TabletInvertedIndex.
2. finish: add shadow index to table.

But if checkpoint happened between pending and finish. The tablet will have no chance to be added to the TabletInvertedIndex.
