### ISSUE TITLE
create table  ... select...  从视图创建表

### ISSUE THREAD

**Issue by Theunfounded** [StarRocks/starrocks#3990]
creat table [ ] as select 语句目前是不支持从视图创建表的，希望后续能够支持从视图直接创建表。

**Comment by Astralidea** [comment]
CTAS syntax now supports View, can you provide some cases if there are any bugs when they are created?

**Comment by Theunfounded** [comment]
> CTAS syntax now supports View, can you provide some cases if there are any bugs when they are created?

CREATE view test_view (`col1`, `col2`, `col3`)
as SELECT * from  first_rygx_2192;

CREATE table test_table as select * from test_view;

test_view是一个视图，像通过这个视图创建一张test_table表，但是执行得时候报错了

`org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [1064] [42000]: Unknown error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3468)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4796)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLSyntaxErrorException: Unknown error
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 12 more`

**Comment by Astralidea** [comment]
which version is your dbeaver? I use 7.1 version in my environment is OK.
or you can you see some log in fe.warn.log ?

**Comment by Theunfounded** [comment]
> 

你这个7.1是什么啊，我现在用的是2.1版本

**Comment by Astralidea** [comment]
7.1 is the version of dbeaver, you are connecting SR with dbeaver. right?

**Comment by Theunfounded** [comment]
> 7.1 is the version of dbeaver, you are connecting SR with dbeaver. right?

是用的dbever, 我的dbever版本是这个 版本21.2.5.202111141807

**Comment by Astralidea** [comment]
> > 7.1 is the version of dbeaver, you are connecting SR with dbeaver. right?
> 
> 是用的dbever, 我的dbever版本是这个 版本21.2.5.202111141807

I go here 
https://github.com/dbeaver/dbeaver/releases
and download dbeaver-ce-21.2.5-macos-x86_64.dmg in my computer and test simple case is ok.
may be you can give me more others information about this issue.
my case is
```
CREATE TABLE `student` (
  `name` varchar(100) NOT NULL COMMENT "",
  `weight` int(11) NOT NULL COMMENT "",
  `height` decimal64(9, 3) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`name`)
COMMENT "student"
DISTRIBUTED BY HASH(`name`) BUCKETS 1 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
use test;
CREATE view test_view (name, weight, height)
as SELECT * from student;
select * from test_view;
insert into student values('a', 1, 1.0);
create table t4 as select * from stu_view;
select * from stu_view
```
You can try it out and see if it works in your environment
