### ISSUE TITLE
Failed to Create MATERIALIZED VIEW on tables for hybrid external catalog (iceberg + jdbc)

### ISSUE THREAD

**Issue by neokjchen** [StarRocks/starrocks#40095]
### Steps to reproduce the behavior (Required)
1. create iceberg table and PostgreSQL table.
2. create external catalog on iceberg and PostgreSQL in StarRocks.
```
mysql> create external catalog drugcentral_iceberg properties (
    ->   "type"="iceberg",
    ->   "iceberg.catalog.type"="rest",
    ->   "iceberg.catalog.uri"="https://api.tabular.io/ws",
    ->   "iceberg.catalog.credential"="",
    ->   "iceberg.catalog.warehouse"="share"
    -> );
Query OK, 0 rows affected (0.11 sec)

mysql> CREATE EXTERNAL CATALOG drugcentral
    -> PROPERTIES
    -> (
    ->     "type"="jdbc",
    ->     "user"="postgres",
    ->     "password"="postgres123",
    ->     "jdbc_uri"="jdbc:postgresql://postgres:5432/postgres",
    ->     "driver_url"="file:///data/deploy/starrocks/fe/lib/postgresql-42.4.3.jar",
    ->     "driver_class"="org.postgresql.Driver"
    -> );
Query OK, 0 rows affected (0.02 sec)
mysql> show catalogs;
+-----------------------------------+----------+------------------------------------------------------------------+
| Catalog                           | Type     | Comment                                                          |
+-----------------------------------+----------+------------------------------------------------------------------+
| drugcentral                    | Jdbc     | NULL                                                             |
| drugcentral_iceberg     | Iceberg  | NULL                                                             |
| default_catalog                   | Internal | An internal catalog contains this cluster's self-managed tables. |
+-----------------------------------+----------+------------------------------------------------------------------+
3 rows in set (0.00 sec)

```
3. create PUBLIC database in starrocks default_catalog.
4. create MATERIALIZED VIEW on iceberg catalog table.
```
mysql> desc `drugcentral_iceberg`.`drugdb`.`action_type`;
+-------------+------------------+------+-------+---------+-------+
| Field       | Type             | Null | Key   | Default | Extra |
+-------------+------------------+------+-------+---------+-------+
| id          | INT              | Yes  | false | NULL    |       |
| action_type | VARCHAR(1048576) | Yes  | false | NULL    |       |
| description | VARCHAR(1048576) | Yes  | false | NULL    |       |
| parent_type | VARCHAR(1048576) | Yes  | false | NULL    |       |
+-------------+------------------+------+-------+---------+-------+
4 rows in set (0.00 sec)

mysql> CREATE MATERIALIZED VIEW `MV_V_ActionType` (`ID`)
    -> DISTRIBUTED BY HASH(`ID`) BUCKETS 12
    -> REFRESH MANUAL
    -> PROPERTIES (
    -> "replicated_storage" = "true",
    -> "force_external_table_query_rewrite" = "CHECKED",
    -> "replication_num" = "1",
    -> "storage_medium" = "HDD",
    -> "colocate_with" = "actiontype"
    -> )
    -> AS SELECT `action_type`.`action_type` AS `ID`
    -> FROM `drugcentral_iceberg`.`drugdb`.`action_type`;
Query OK, 0 rows affected (0.06 sec)
```
6. create MATERIALIZED VIEW on PostgreSQL catalog table

```
mysql> desc `drugcentral`.`public`.`action_type`;
+-------------+--------------+------+-------+---------+-------+
| Field       | Type         | Null | Key   | Default | Extra |
+-------------+--------------+------+-------+---------+-------+
| id          | INT          | No   | false | NULL    |       |
| action_type | VARCHAR(50)  | No   | false | NULL    |       |
| description | VARCHAR(200) | No   | false | NULL    |       |
| parent_type | VARCHAR(50)  | Yes  | false | NULL    |       |
+-------------+--------------+------+-------+---------+-------+
4 rows in set (0.11 sec)
mysql> CREATE MATERIALIZED VIEW `PUBLIC`.`MV_E_OUT_HAS_PARENT_TYPE`
    -> DISTRIBUTED BY HASH(`ID`) BUCKETS 12
    -> REFRESH MANUAL
    -> PROPERTIES (
    -> "force_external_table_query_rewrite" = "true",
    -> "colocate_with" = "actiontype",
    -> "replication_num" = "1"
    -> )
    -> AS SELECT `action_type` AS `PUBLIC.ActionType__O`,
    -> `parent_type` AS `PUBLIC.ActionType__I`,
    -> `id` AS `ID`
    -> FROM `drugcentral`.`public`.`action_type`;
ERROR 1064 (HY000): Unexpected exception: Colocate tables distribution columns must have the same data type with group 10005.10428, current col: ID, should be: VARCHAR(1048576), current info type: HASH; distribution columns: [ID,]; bucket num: 12;
```

### Expected behavior (Required)
1. successful create MATERIALIZED VIEW on PostgreSQL

### Real behavior (Required)
1. Throw exception:
`ERROR 1064 (HY000): Unexpected exception: Colocate tables distribution columns must have the same data type with group 10005.10428, current col: ID, should be: VARCHAR(1048576), current info type: HASH; distribution columns: [ID,]; bucket num: 12;`

Error log in fe.warn.log

```
2024-01-26 07:03:14,354 WARN (starrocks-mysql-nio-pool-0|125) [StmtExecutor.handleDdlStmt():1583] DDL statement (CREATE MATERIALIZED VIEW `PUBLIC`.`MV_E_OUT_HAS_PARENT_TYPE`
DISTRIBUTED BY HASH(`ID`) BUCKETS 12
REFRESH MANUAL
PROPERTIES (
"force_external_table_query_rewrite" = "true",
"colocate_with" = "actiontype",
"replication_num" = "1"
)
AS SELECT `action_type` AS `PUBLIC.ActionType__O`,
`parent_type` AS `PUBLIC.ActionType__I`,
`id` AS `ID`
FROM `drugcentral`.`public`.`action_type`) process failed.
com.starrocks.common.DdlException: Colocate tables distribution columns must have the same data type with group 10005.10428, current col: ID, should be: VARCHAR(1048576), current info type: HASH; distribution columns: [ID,]; bucket num: 12;
	at com.starrocks.common.ErrorReport.reportDdlException(ErrorReport.java:99) ~[starrocks-fe.jar:?]
	at com.starrocks.common.ErrorReport.reportDdlException(ErrorReport.java:94) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.ColocateGroupSchema.checkDistribution(ColocateGroupSchema.java:113) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.ColocateGroupSchema.checkColocateSchema(ColocateGroupSchema.java:92) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.ColocateTableIndex.addTableToGroup(ColocateTableIndex.java:200) ~[starrocks-fe.jar:?]
	at com.starrocks.server.LocalMetastore.analyzeMVDataProperties(LocalMetastore.java:3397) ~[starrocks-fe.jar:?]
	at com.starrocks.server.LocalMetastore.createMaterializedView(LocalMetastore.java:3190) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.createMaterializedView(GlobalStateMgr.java:3470) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.lambda$visitCreateMaterializedViewStatement$8(DDLStmtExecutor.java:281) ~[starrocks-fe.jar:?]
	at com.starrocks.common.ErrorReport.wrapWithRuntimeException(ErrorReport.java:112) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitCreateMaterializedViewStatement(DDLStmtExecutor.java:280) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitCreateMaterializedViewStatement(DDLStmtExecutor.java:157) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.CreateMaterializedViewStatement.accept(CreateMaterializedViewStatement.java:269) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.DDLStmtExecutor.execute(DDLStmtExecutor.java:143) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1557) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:661) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:379) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:570) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:848) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 3.2.2-269e832     |
+-------------------+
1 row in set (0.01 sec)
```
also test in 3.1.7 and get the same result

**Comment by LiShuMing** [comment]
1. You can check  colocate group type of  `actiontype `:
```
show proc '/colocation_group';
```


```
com.starrocks.common.DdlException: Colocate tables distribution columns must have the same data type with group 10005.10428, current col: ID, should be: VARCHAR(1048576), current info type: HASH; distribution columns: [ID,]; bucket num: 12;
```

2. you can remove ` "colocate_with" = "actiontype",` property in the mv defination

**Comment by neokjchen** [comment]
remove `"colocate_with" = "actiontype",` did work.
But fe.warn.log show another exceptions after Create MV.

```
2024-01-26 09:37:54,895 WARN (starrocks-taskrun-pool-0|160) [PartitionBasedMvRefreshProcessor.doMvRefresh():258] Refresh mv MV_E_OUT_HAS_PARENT_TYPE failed: java.lang.IllegalStateException: corrupted partition meta
2024-01-26 09:37:54,895 WARN (starrocks-taskrun-pool-0|160) [TaskRunExecutor.lambda$executeTaskRun$0():57] failed to execute TaskRun.
java.lang.IllegalStateException: corrupted partition meta
	at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getPartitionNameWithPartitionInfo(ConnectorPartitionTraits.java:202) ~[starrocks-fe.jar:?]
	at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getUpdatedPartitionNames(ConnectorPartitionTraits.java:224) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfExternalTable(MaterializedView.java:702) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:729) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:545) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.needToRefreshTable(PartitionBasedMvRefreshProcessor.java:794) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.isNonPartitionedMVNeedToRefresh(PartitionBasedMvRefreshProcessor.java:816) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:888) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:850) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doMvRefresh(PartitionBasedMvRefreshProcessor.java:233) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.processTaskRun(PartitionBasedMvRefreshProcessor.java:184) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:189) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:50) ~[starrocks-fe.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by LiShuMing** [comment]
JDBC external table with `postgres` dialect is not support yet. 
Only mysql dialect is supported for now.

**Comment by neokjchen** [comment]
> JDBC external table with `postgres` dialect is not support yet. Only mysql dialect is supported for now.

Is there any timeline or plan to support MV on `postgres` ?
