### ISSUE TITLE
Issue connecting to a Kerberized hive metastore

### ISSUE THREAD

**Issue by metalshanked** [StarRocks/starrocks#40153]
Hi, I am having trouble connecting to a kerberized Hive Metastore
Starrocks 3.2.2  running in Shared Data mode on minio S3 (Only FE and CN Pods)
1. I have setup the kerberos  in all the FE and CN pods and the ticket is valid by doing klist command for checks.
2. Added hive-site.xml to fe/conf and cn/conf dirs
3. Created a jaas.conf and set the -Djava settings for krb5.conf and jaas.conf for JDK 11 (which the pods are using). Confirmed using `jps -lvm`
 4. Created an iceberg external catalog with kerberized HMS and Minio S3
 5. The only properties set for hive metastore in CREATE external catalog statement is "hive.metastore.uris" = "<hive_metastore_uri>"
 6. Running any query like Eg:- SHOW DATABASES FROM iceberg;  gives hive metastore error below
 7. The metastore is working fine and is accessible from the hosts (Eg:- trino is able to access the kerberized HMS without problem)
```
#hive-site.xml
<configuration>
    <property>
        <name>hive.metastore.kerberos.principal</name>
        <value>hive/metastoreserver@DOMAIN.DOM</value>
    </property>
    <property>
        <name>hive.metastore.sasl.enabled</name>
        <value>true</value>
    </property>
</configuration>
```

```
2024-01-26 15:01:41,223 WARN (starrocks-mysql-nio-pool-0|134) [HiveMetaStoreClient.openInternal():549] Failed to connect to the MetaStore Server...
2024-01-26 15:01:41,223 INFO (starrocks-mysql-nio-pool-0|134) [HiveMetaStoreClient.openInternal():583] Waiting 1 seconds before next connection attempt.
2024-01-26 15:01:41,251 INFO (nioEventLoopGroup-6-8|130) [RestBaseAction.handleRequest():73] receive http request. url=/api/bootstrap?cluster_id=974320758&token=82eed83d-e59d-440a-9362-5b4dd597228f
2024-01-26 15:01:41,259 INFO (replayer|91) [GlobalStateMgr.replayJournalInner():2385] replayed journal from 12701 - 12702
2024-01-26 15:01:42,223 INFO (starrocks-mysql-nio-pool-0|134) [HiveMetaStoreClient.openInternal():459] Trying to connect to metastore with URI thrift://metastoreserver:9083
2024-01-26 15:01:42,223 INFO (starrocks-mysql-nio-pool-0|134) [HiveMetaStoreClient.openInternal():511] HMSC::open(): Could not find delegation token. Creating KERBEROS-based thrift connection.
2024-01-26 15:01:42,225 DEBUG (starrocks-mysql-nio-pool-0|134) [TSaslTransport.open():255] opening transport 
Caused by: org.ietf.jgss.GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:162) ~[java.security.jgss:?]
        at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:126) ~[java.security.jgss:?]
        at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:193) ~[java.security.jgss:?]

```

Any help is appreciated!

**Comment by metalshanked** [comment]
Update: Solved this 

After a day of trial, error and research...I have it working now
The docs needed to be updated I guess for some of the items.
Kereberos config only required for FE. Not required for CN pods
In addition to doc items,  also needs JAAS config jaas.conf in any location (location needs to be mentioned in JAVA_OPTS_XXX as given below)
Needs to have the hive-site.xml to the fe/conf dir
Add other kerberos related JAVA_OPTS_JDK_11 (or appropriate JAVA opts for your JDK)
Final JAVA_OPTS in fe.conf looks like below
`JAVA_OPTS_FOR_JDK_11="-Djavax.security.auth.useSubjectCredsOnly=false -Dsun.security.krb5.debug=true -Djava.security.krb5.conf=/etc/krb5.conf -Djava.security.auth.login.config=/opt/starrocks/jaas.conf"`

and here is the jaas.conf
```
HiveMetastoreJaas {
com.sun.security.auth.module.Krb5LoginModule required
useKeyTab=true
useTicketCache=true
storeKey=false
renewTicket=true
debug=true;
};
```
and here is the hive-site.xml
```
<configuration>
    <property>
        <name>hive.metastore.kerberos.principal</name>
        <value>hive/metastoreserver@DOMAIN.DOM</value>
    </property>
    <property>
        <name>hive.metastore.sasl.enabled</name>
        <value>true</value>
    </property>
</configuration>
```

**Comment by metalshanked** [comment]
Done

**Comment by vineethvictor25** [comment]
@metalshanked i have similar issue but in my log it is looking for some ldap password file

Could not read password file: /etc/security/ldaptruststorepwd.txt

but I am trying to connect to hive metastore which is kerberised. I am able generate the valid ticket for the Kerberos . Could you please help me with this ??

**Comment by vineethvictor25** [comment]
Here is the log 

2024-04-10 11:53:08,883 ERROR (starrocks-mysql-nio-pool-0|150) [HiveMetadata.getTable():115] Failed to get hive table [resource_mapping_inside_catalog_hive_hive_zk.opcode.tedc_ctry]
com.starrocks.connector.exception.StarRocksConnectorException: Failed to get table [opcode.tedc_ctry], msg: Could not read password file: /etc/security/cert/ldaptruststorepwd.txt
