### ISSUE TITLE
Issue with LDAPS on port 636 for Authentication

### ISSUE THREAD

**Issue by metalshanked** [StarRocks/starrocks#40167]
Hi, I get the below error when connecting to LDAP on port 636 (TLS/SSL LDAP)
The required certs are present in the JVM truststore and the LDAPS configs work in other applications.

```
2024-01-28 00:55:32,901 WARN (starrocks-mysql-nio-pool-1|151) [LdapSecurity.checkPasswordByRoot():115] call ldap exception 
javax.naming.NamingException: LDAP connection has been closed
        at com.sun.jndi.ldap.LdapRequest.getReplyBer(LdapRequest.java:133) ~[?:?]
        at com.sun.jndi.ldap.Connection.readReply(Connection.java:443) ~[?:?]
        at com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:365) ~[?:?]
        at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:214) ~[?:?]
        at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2895) ~[?:?]
        at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348) ~[?:?]
        at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:266) ~[?:?]
        at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:226) ~[?:?]
        at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:284) ~[?:?]
        at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:185) ~[?:?]
        at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:115) ~[?:?]
        at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:730) ~[?:?]
        at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
        at javax.naming.InitialContext.init(InitialContext.java:236) ~[?:?]
        ```

### StarRocks version (Required)
 - 3.2.2 on K8s Operator

**Comment by alberttwong** [comment]
Security is an enterprise feature unless you can write it and donate it to the community.
