### ISSUE TITLE
Core on split function

### ISSUE THREAD

**Issue by Seaven** [StarRocks/starrocks#4092]
### Steps to reproduce the behavior (Required)
Any varchar column and value is `null`

```
select (split(id_varchar, id_varchar) is null) <=> (split(id_varchar, NULL) is null) from test_all_null
execute sql error and messages: (1064, 'Backend not found. Check if any backend is down or not'), and time is: 2022-03-14 17:14:35
```

stack:
```
(gdb) bt
#0  0x00007f0848415387 in raise () from /usr/lib64/libc.so.6
#1  0x00007f0848416a78 in abort () from /usr/lib64/libc.so.6
#2  0x00000000062ccb2a in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00000000062cb1d6 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00000000062cb241 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00000000062cb395 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x9f694c0, tinfo=0x645e860 <typeinfo for std::length_error>, dest=0x62d9e40 <std::length_error::~length_error()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x000000000631adf0 in std::__throw_length_error (__s=__s@entry=0x1fc0c5a "vector::reserve") at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:78
#7  0x0000000002421959 in std::vector<starrocks::Slice, std::allocator<starrocks::Slice> >::reserve (__n=<optimized out>, this=0x29600900) at /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/vector.tcc:70
#8  starrocks::vectorized::BinaryColumn::_build_slices (this=this@entry=0x296008c0) at /home/disk2/hekai/workspace/DorisDB/be/src/column/binary_column.cpp:193
#9  0x0000000003385fc8 in starrocks::vectorized::BinaryColumn::get_data (this=0x296008c0) at /home/disk2/hekai/workspace/DorisDB/be/src/column/binary_column.h:208
#10 starrocks::vectorized::ColumnHelper::get_const_value<(starrocks::PrimitiveType)10> (col=std::shared_ptr<starrocks::vectorized::Column> (use count 3, weak count 0) = {...}) at /home/disk2/hekai/workspace/DorisDB/be/src/column/column_helper.h:221
#11 starrocks::vectorized::StringFunctions::split_prepare (context=<optimized out>, scope=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/split.cpp:48
#12 0x000000000329fea8 in starrocks::vectorized::VectorizedFunctionCallExpr::open (this=0x385d5400, state=<optimized out>, context=0x142c8700, scope=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/function_call_expr.cpp:71
```
### StarRocks version (Required)
main

**Comment by Seaven** [comment]
```
CREATE TABLE test_all_null (
    id_int int null,
    id_boolean boolean null,
    id_tinyint tinyint null,
    id_smallint smallint null,
    id_bigint bigint null,
    id_largeint largeint null,
    id_float float null,
    id_double double null,
    id_decimal32 decimal32(8, 5) null,
    id_decimal64 decimal64(8, 5) null,
    id_decimal128 decimal128(8, 5) null,
    id_date date null,
    id_datetime datetime null,
    id_varchar varchar(2000) null,
    id_json json,
    id_any_element array<int> null,
    id_any_array int null,
    id_array_boolean array<boolean> null,
    id_array_tinyint array<tinyint> null,
    id_array_smallint array<smallint> null,
    id_array_int array<int> null,
    id_array_bigint array<bigint> null,
    id_array_largeint array<largeint> null,
    id_array_float array<float> null,
    id_array_double array<double> null,
    id_array_varchar array<varchar(2000)> null,
    id_array_date array<date> null,
    id_array_datetime array<datetime> null
) ENGINE=OLAP
DUPLICATE KEY(`id_int`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id_int`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

insert into test_all_null select t.* from (select 1 as d) x left join test_all_null t on x.d = t.id_int;
```
