### ISSUE TITLE
Core on json_query function

### ISSUE THREAD

**Issue by Seaven** [StarRocks/starrocks#4094]
### Steps to reproduce the behavior (Required)
id_json's type is `json` and value is `null`
id_varchar's type is `varchar(2000)` and value is `null`

```
 select (json_query(id_json, id_varchar)) <=> (json_query(NULL, NULL)) from test_all_null
execute sql error and messages: (1064, 'Backend not found. Check if any backend is down or not'), and time is: 2022-03-14 17:25:22
```

```
btProgram terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000033112fd in starrocks::vectorized::JsonFunctions::native_json_path_prepare (context=0x19937020, scope=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/json_functions.cpp:415
415	    if (scope != FunctionContext::FRAGMENT_LOCAL || context->get_constant_column(1)->only_null() ||
[Current thread is 1 (Thread 0x7fe27c297700 (LWP 74111))]
(gdb) bt
#0  0x00000000033112fd in starrocks::vectorized::JsonFunctions::native_json_path_prepare (context=0x19937020, scope=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/json_functions.cpp:415
#1  0x000000000329fea8 in starrocks::vectorized::VectorizedFunctionCallExpr::open (this=0x22e2bc00, state=<optimized out>, context=0xd1bd040, scope=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/function_call_expr.cpp:71
#2  0x0000000002d1e960 in starrocks::Expr::open (this=<optimized out>, state=0x2427ec10, context=0xd1bd040, scope=starrocks_udf::FunctionContext::FRAGMENT_LOCAL) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/expr.cpp:433
#3  0x0000000002d1d44e in starrocks::ExprContext::open (this=<optimized out>, state=state@entry=0x2427ec10) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/expr_context.cpp:69
#4  0x0000000002d1eff1 in starrocks::Expr::open (ctxs=std::vector of length 1, capacity 1 = {...}, state=state@entry=0x2427ec10) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/expr.cpp:425
#5  0x0000000002870960 in starrocks::vectorized::ProjectNode::open (this=0x25d98e00, state=0x2427ec10) at /home/disk2/hekai/workspace/DorisDB/be/src/exec/vectorized/project_node.cpp:96
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by Seaven** [comment]
```
CREATE TABLE test_all_null (
    id_int int null,
    id_boolean boolean null,
    id_tinyint tinyint null,
    id_smallint smallint null,
    id_bigint bigint null,
    id_largeint largeint null,
    id_float float null,
    id_double double null,
    id_decimal32 decimal32(8, 5) null,
    id_decimal64 decimal64(8, 5) null,
    id_decimal128 decimal128(8, 5) null,
    id_date date null,
    id_datetime datetime null,
    id_varchar varchar(2000) null,
    id_json json,
    id_any_element array<int> null,
    id_any_array int null,
    id_array_boolean array<boolean> null,
    id_array_tinyint array<tinyint> null,
    id_array_smallint array<smallint> null,
    id_array_int array<int> null,
    id_array_bigint array<bigint> null,
    id_array_largeint array<largeint> null,
    id_array_float array<float> null,
    id_array_double array<double> null,
    id_array_varchar array<varchar(2000)> null,
    id_array_date array<date> null,
    id_array_datetime array<datetime> null
) ENGINE=OLAP
DUPLICATE KEY(`id_int`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id_int`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

insert into test_all_null select t.* from (select 1 as d) x left join test_all_null t on x.d = t.id_int;

```

**Comment by Seaven** [comment]
core also
```
 select (json_exists(id_json, id_varchar)) <=> (json_exists(NULL, NULL)) from test_all_null
```

**Comment by Seaven** [comment]
result should be same
```
mysql> select (json_array(id_json)),  (json_array(NULL)) from test_all_null;
+---------------------+------------------+
| json_array(id_json) | json_array(NULL) |
+---------------------+------------------+
| [null]              | NULL             |
+---------------------+------------------+
1 row in set (0.01 sec)
```
