### ISSUE TITLE
FQDN issues on load jobs

### ISSUE THREAD

**Issue by ilhanadiyaman** [StarRocks/starrocks#41013]
### Steps to reproduce the behavior (Required)
We are testing FQDN with Starrocks. We setup 1 FE 1 BE in the new cluster. Updated the /etc/hosts files in both servers as shown below:

```
127.0.0.1	localhost

10.2.1.136	starrocks-front-de-0.acme.internal
10.2.1.69	        starrocks-back-de-0.acme.internal
```
Launched cluster without problem. We can confirm that FE connects to BE. However, when we tried to load a parquet file from Azure, we are getting an error below.

```
2024-02-09 12:03:48,281 WARN (heartbeat-mgr-pool-3|153) [HeartbeatMgr$BackendHeartbeatHandler.call():315] backend heartbeat got exception, addr: starrocks-back-de-0.acme.internal:9050
org.apache.thrift.transport.TTransportException: Socket is closed by peer.
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:130) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[libthrift-0.13.0.jar:0.13.0]
	at com.starrocks.thrift.HeartbeatService$Client.recv_heartbeat(HeartbeatService.java:61) ~[starrocks-fe.jar:?]
	at com.starrocks.thrift.HeartbeatService$Client.heartbeat(HeartbeatService.java:48) ~[starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:273) ~[starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:251) ~[starrocks-fe.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2024-02-09 12:03:48,281 WARN (heartbeat mgr|14) [HeartbeatMgr.runAfterCatalogReady():164] get bad heartbeat response: type: BACKEND, status: BAD, msg: Socket is closed by peer.
2024-02-09 12:03:52,700 WARN (loading_load_task_scheduler_priority_pool-1|9715) [QueryRuntimeProfile.waitForProfileFinished():236] failed to get profile within 5 seconds
2024-02-09 12:03:53,290 WARN (Thread-96|140) [CoordinatorMonitor$DeadBackendAndComputeNodeChecker.run():91] Cancel query [499fa339-4ddf-4e83-b313-d1244e4e037f], because some related backend is not alive
2024-02-09 12:03:53,290 WARN (Thread-96|140) [DefaultCoordinator.cancel():779] cancel execState of query, this is outside invoke
2024-02-09 12:03:53,291 WARN (loading_load_task_scheduler_priority_pool-1|9715) [LoadTask.exec():79] LOAD_JOB=11068, error_msg={Failed to execute load task}
com.starrocks.common.LoadException: Backend node not found. Check if any backend node is down.
```

Backend node is definitely alive, when we submit this job. And from the FE machine I can telnet to the BE on port 9050.

```
root@starrocks-front-de-0:~$ telnet starrocks-back-de-0.acme.internal 9050
Trying 10.2.1.69...
Connected to starrocks-back-de-0.acme.internal.
Escape character is '^]'.
```

### StarRocks version (Required)
 - 3.2.2

**Comment by alberttwong** [comment]
This would be better as an issue discussed on foru.starrocks.io.   Github issues are for code problems, not configure issues.
