### ISSUE TITLE
[BUG] Iceberg MV tasks break after Iceberg's "expire_snapshots" procedure is called

### ISSUE THREAD

**Issue by carlosescura** [StarRocks/starrocks#41335]
### Steps to reproduce the behavior (Required)
1. Create an Iceberg table using Glue as meta catalog store, and S3 as warehouse storage. Table is partitioned by day using `dt` field (TIMESTAMP)
2. Create a StarRocks MV pointing to a partitioned (daily) Iceberg base table.

```sql
CREATE MATERIALIZED VIEW downloads
DISTRIBUTED BY HASH(user_id)
REFRESH ASYNC START('2024-01-01 08:00:00') EVERY (interval 1 day)
PROPERTIES(
  "auto_refresh_partitions_limit" = "15"
)
PARTITION BY dt AS
SELECT
    date_trunc('day', dt) AS dt,
    user_id,
    sum(bytes) / 1048576 AS total_mb
FROM iceberg_catalog_glue.db.cf_media_downloads
GROUP BY dt, user_id;
```

4. Initial and subsequent Async MV refresh work as expected
5. Initiate an `expire_snapshots` Iceberg procedure
6. MV won't refresh any longer

### Expected behavior (Required)
Async MV should keep updating as normal

### Real behavior (Required)
Async MV break with the following errors:

FE error log is the following:

```
2024-02-15 18:19:11,955 INFO (starrocks-taskrun-pool-12|1967) [CatalogUtil.loadFileIO():302] Loading custom FileIO implementation: com.starrocks.connector.iceberg.io.IcebergCachingFileIO
2024-02-15 18:19:12,090 INFO (starrocks-taskrun-pool-12|1967) [BaseMetastoreTableOperations.refreshFromMetadataLocation():199] Refreshing table metadata from new version: s3://xxxxxxxxx/yyyyyyyyy.db/cf_media_downloads/metadata/02042-b613ea2f-7027-4fbc-b9ef-cdb208221331.metadata.json
2024-02-15 18:19:12,090 INFO (starrocks-taskrun-pool-12|1967) [CatalogUtil.loadFileIO():302] Loading custom FileIO implementation: org.apache.iceberg.aws.s3.S3FileIO
2024-02-15 18:19:12,096 INFO (starrocks-taskrun-pool-12|1967) [BaseMetastoreCatalog.loadTable():67] Table loaded by catalog: iceberg_catalog_glue.yyyyyyyyy.cf_media_downloads
2024-02-15 18:19:12,096 INFO (starrocks-taskrun-pool-12|1967) [SnapshotScan.planFiles():124] Scanning table iceberg_catalog_glue.yyyyyyyyy.cf_media_downloads snapshot 6691577339994639536 created at 2024-02-15T18:17:26.578+00:00 with filter true
2024-02-15 18:19:12,397 INFO (starrocks-taskrun-pool-12|1967) [PartitionBasedMvRefreshProcessor.syncPartitionsForExpr():842] The process of synchronizing materialized view [bandwidth] delete partitions range [{}]
2024-02-15 18:19:12,397 INFO (starrocks-taskrun-pool-12|1967) [PartitionBasedMvRefreshProcessor.syncPartitionsForExpr():854] The process of synchronizing materialized view [bandwidth] add partitions range [{}]
2024-02-15 18:19:12,401 INFO (starrocks-taskrun-pool-12|1967) [SnapshotScan.planFiles():124] Scanning table iceberg_catalog_glue.yyyyyyyyy.cf_media_downloads snapshot 6691577339994639536 created at 2024-02-15T18:17:26.578+00:00 with filter true
2024-02-15 18:19:12,452 INFO (tablet scheduler|34) [TabletScheduler.updateClusterLoadStatistic():484] update cluster load statistic:

2024-02-15 18:19:12,488 INFO (starrocks-taskrun-pool-12|1967) [LoggingMetricsReporter.report():38] Received metrics report: ScanReport{tableName=iceberg_catalog_glue.yyyyyyyyy.cf_media_downloads, snapshotId=6691577339994639536, filter=true, schemaId=0, projectedFieldIds=[1, 2, 3, 4, 5, 6, 7, 1000, 8, 9, 10, 11], projectedFieldNames=[partition, record_count, file_count, spec_id, position_delete_record_count, position_delete_file_count, equality_delete_record_count, partition.dt_day, equality_delete_file_count, last_updated_at, last_updated_snapshot_id, total_data_file_size_in_bytes], scanMetrics=ScanMetricsResult{totalPlanningDuration=TimerResult{timeUnit=NANOSECONDS, totalDuration=PT0.087485291S, count=1}, resultDataFiles=CounterResult{unit=COUNT, value=0}, resultDeleteFiles=CounterResult{unit=COUNT, value=0}, totalDataManifests=CounterResult{unit=COUNT, value=0}, totalDeleteManifests=CounterResult{unit=COUNT, value=0}, scannedDataManifests=CounterResult{unit=COUNT, value=0}, skippedDataManifests=CounterResult{unit=COUNT, value=0}, totalFileSizeInBytes=CounterResult{unit=BYTES, value=0}, totalDeleteFileSizeInBytes=CounterResult{unit=BYTES, value=0}, skippedDataFiles=CounterResult{unit=COUNT, value=0}, skippedDeleteFiles=CounterResult{unit=COUNT, value=0}, scannedDeleteManifests=CounterResult{unit=COUNT, value=0}, skippedDeleteManifests=CounterResult{unit=COUNT, value=0}, indexedDeleteFiles=CounterResult{unit=COUNT, value=0}, equalityDeleteFiles=CounterResult{unit=COUNT, value=0}, positionalDeleteFiles=CounterResult{unit=COUNT, value=0}}, metadata={iceberg-version=Apache Iceberg 1.4.2 (commit f6bb9173b13424d77e7ad8439b5ef9627e530cb2)}}
2024-02-15 18:19:12,489 ERROR (starrocks-taskrun-pool-12|1967) [MetadataMgr.getPartitions():453] Failed to get partitions on catalog [iceberg_catalog_glue], table [Table [id=100000110, name=cf_media_downloads, type=ICEBERG]]
java.lang.NullPointerException: null
        at com.starrocks.connector.iceberg.IcebergMetadata.getPartitions(IcebergMetadata.java:345) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.CatalogConnectorMetadata.getPartitions(CatalogConnectorMetadata.java:133) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.getPartitions(MetadataMgr.java:451) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorPartitionTraits$IcebergPartitionTraits.getPartitions(ConnectorPartitionTraits.java:470) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getPartitionNameWithPartitionInfo(ConnectorPartitionTraits.java:237) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getUpdatedPartitionNames(ConnectorPartitionTraits.java:260) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfExternalTable(MaterializedView.java:721) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:748) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:564) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getMVPartitionNamesToRefreshByRangePartitionNamesAndForce(PartitionBasedMvRefreshProcessor.java:1099) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:1046) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:973) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doMvRefresh(PartitionBasedMvRefreshProcessor.java:242) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.processTaskRun(PartitionBasedMvRefreshProcessor.java:194) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:214) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:53) ~[starrocks-fe.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2024-02-15 18:19:12,489 WARN (starrocks-taskrun-pool-12|1967) [PartitionBasedMvRefreshProcessor.doMvRefresh():267] Refresh mv bandwidth failed: java.lang.NullPointerException
2024-02-15 18:19:12,489 WARN (starrocks-taskrun-pool-12|1967) [TaskRunExecutor.lambda$executeTaskRun$0():60] failed to execute TaskRun.
java.lang.NullPointerException: null
        at com.starrocks.connector.iceberg.IcebergMetadata.getPartitions(IcebergMetadata.java:345) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.CatalogConnectorMetadata.getPartitions(CatalogConnectorMetadata.java:133) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.getPartitions(MetadataMgr.java:451) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorPartitionTraits$IcebergPartitionTraits.getPartitions(ConnectorPartitionTraits.java:470) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getPartitionNameWithPartitionInfo(ConnectorPartitionTraits.java:237) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.ConnectorPartitionTraits$DefaultTraits.getUpdatedPartitionNames(ConnectorPartitionTraits.java:260) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfExternalTable(MaterializedView.java:721) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:748) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.getUpdatedPartitionNamesOfTable(MaterializedView.java:564) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getMVPartitionNamesToRefreshByRangePartitionNamesAndForce(PartitionBasedMvRefreshProcessor.java:1099) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:1046) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.getPartitionsToRefreshForMaterializedView(PartitionBasedMvRefreshProcessor.java:973) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doMvRefresh(PartitionBasedMvRefreshProcessor.java:242) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.processTaskRun(PartitionBasedMvRefreshProcessor.java:194) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:214) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:53) ~[starrocks-fe.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2024-02-15 18:19:12,587 INFO (pool-22-thread-1|198) [TaskRunManager.checkRunningTaskRun():195] Task run is done from state RUNNING to FAILED, TaskRun{taskId=53621, type=MANUAL, uuid=b780fe3b-cc2e-11ee-afb3-eed833ae671e, task_state=FAILED, properties={spill_mode=force, datacache.enable=true, PARTITION_START=null, FORCE=false, query_timeout=3600, mvId=53619, enable_async_write_back=false, replication_num=1, enable_spill=true, PARTITION_END=null, in_memory=false}, extra_message ={"forceRefresh":false,"mvPartitionsToRefresh":[],"refBasePartitionsToRefreshMap":{},"basePartitionsToRefreshMap":{}}}
```

### StarRocks version (Required)
 - 3.2.3

### Discussion thread
https://starrocks.slack.com/archives/C02FACZSNJV/p1707921942031899

**Comment by carlosescura** [comment]
Not a Java expert, but reading this [related issue](https://github.com/StarRocks/starrocks/issues/41022) I also think the metadata table is using array index and not `Field ID` which in that case would be `9`. Shouldn't it be `10` if 0 indexed array is returned [here](https://github.com/StarRocks/starrocks/blob/743cc831356c20fe13ea1aaa6aac405826ce6886/fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergMetadata.java#L392)?

@mofeiatwork 

The only thing that scapes to my understanding is why it is working prior to running the `expire_snapshots` call  🔍 🤯
