### ISSUE TITLE
NPE when query sync MV on top of list partitioned table

### ISSUE THREAD

**Issue by murphyatwork** [StarRocks/starrocks#41349]
### Steps to reproduce the behavior (Required)

```sql
CREATE TABLE `t3` (
  `c1` int,
  `c2` int,
  `dt` date NOT NULL
) 
PARTITION BY (`dt`);

create materialized view rollup1 as select c1, c2 from t3;
create materialized view rollup2 as select c1, sum(c2) from t3 group by c1;

-- Exception 
select * from rollup1 [_SYNC_MV_];
```

### Real behavior (Required)

```java
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
        at com.starrocks.sql.optimizer.rewrite.OptOlapPartitionPruner.listPartitionPrune(OptOlapPartitionPruner.java:303) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.OptOlapPartitionPruner.prunePartitions(OptOlapPartitionPruner.java:72) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.PartitionPruneRule.transform(PartitionPruneRule.java:67) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:97) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.execute(RewriteTreeTask.java:59) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:65) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.ruleRewriteOnlyOnce(Optimizer.java:862) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:444) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.rewriteAndValidatePlan(Optimizer.java:598) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:201) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:148) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlanWithReTry(StatementPlanner.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:134) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:91) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:524) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:403) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:598) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:893) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### StarRocks version (Required)
- main branch 2024-02-21

**Comment by murphyatwork** [comment]
resolved
