### ISSUE TITLE
Core on array_overlap

### ISSUE THREAD

**Issue by Seaven** [StarRocks/starrocks#4138]
### Steps to reproduce the behavior (Required)
```
select (array_overlap(id_array_date, id_array_date)) <=> (array_overlap(id_array_date, NULL)) from test_all_null
```
```
#0  std::vector<unsigned char, std::allocator<unsigned char> >::data (this=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/function_helper.cpp:64
#1  starrocks::vectorized::FunctionHelper::union_null_column (v1=std::shared_ptr<starrocks::vectorized::FixedLengthColumn<unsigned char>> (use count 1, weak count 0) = {...}, v2=<error reading variable: Cannot access memory at address 0x3564300212>)
    at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/function_helper.cpp:64
#2  0x0000000003fa8386 in starrocks::vectorized::ArrayOverlap<(starrocks::PrimitiveType)11>::_array_overlap<phmap::flat_hash_set<starrocks::vectorized::DateValue, starrocks::vectorized::StdHash<starrocks::vectorized::DateValue>, phmap::EqualTo<starrocks::vectorized::DateValue>, std::allocator<starrocks::vectorized::DateValue> > > (columns=std::vector of length 2, capacity 2 = {...}) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/array_functions.tpp:468
#3  0x0000000003fa8b55 in starrocks::vectorized::ArrayOverlap<(starrocks::PrimitiveType)11>::process (columns=..., ctx=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/array_functions.tpp:441
#4  starrocks::vectorized::ArrayFunctions::array_overlap_date (context=<optimized out>, columns=...) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/array_functions.h:79
#5  0x000000000329efa6 in starrocks::vectorized::VectorizedFunctionCallExpr::evaluate (this=0x169c2000, context=<optimized out>, ptr=0x17c5e780) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/function_call_expr.cpp:141
#6  0x0000000002e00af3 in starrocks::vectorized::VectorizedNullSafeEqPredicate<(starrocks::PrimitiveType)2, starrocks::vectorized::BinaryPredFunc<std::equal_to<unsigned char> > >::evaluate (this=0x16ca1800, context=0x94af980, ptr=0x17c5e780)
    at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/binary_predicate.cpp:77
#7  0x0000000002d1d954 in starrocks::ExprContext::evaluate (chunk=0x17c5e780, e=<optimized out>, this=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/expr_context.cpp:199
#8  starrocks::ExprContext::evaluate (this=<optimized out>, chunk=0x17c5e780) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/expr_context.cpp:189
#9  0x000000000286f025 in starrocks::vectorized::ProjectNode::get_next (this=0x16ecf500, state=<optimized out>, chunk=0x16e62898, eos=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exec/vectorized/project_node.cpp:144
#10 0x00000000039a06ba in starrocks::PlanFragmentExecutor::_get_next_internal_vectorized (this=this@entry=0x16e62800, chunk=chunk@entry=0x7f5f8aa8ee50) at /home/disk2/hekai/workspace/DorisDB/be/src/runtime/plan_fragment_executor.cpp:329
#11 0x00000000039a1ff5 in starrocks::PlanFragmentExecutor::_open_internal_vectorized (this=this@entry=0x16e62800) at /home/disk2/hekai/workspace/DorisDB/be/src/runtime/plan_fragment_executor.cpp:217
#12 0x00000000039a2bc7 in starrocks::PlanFragmentExecutor::open (this=this@entry=0x16e62800) at /home/disk2/hekai/workspace/DorisDB/be/src/runtime/plan_fragment_executor.cpp:186
#13 0x00000000039be902 in starrocks::FragmentExecState::execute (this=0x16e62780) at /home/disk2/hekai/workspace/DorisDB/be/src/runtime/fragment_mgr.cpp:193
#14 0x00000000039c316c in starrocks::FragmentMgr::exec_actual(std::shared_ptr<starrocks::FragmentExecState>, std::function<void (starrocks::PlanFragmentExecutor*)> const&) (this=<optimized out>,
    exec_state=std::shared_ptr<starrocks::FragmentExecState> (use count 3, weak count 0) = {...}, cb=...) at /home/disk2/hekai/workspace/DorisDB/be/src/runtime/fragment_mgr.cpp:379
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by jaogoy** [comment]
@Pslydhh  Make sure to link #4150 to this issue.

**Comment by Pslydhh** [comment]
> @Pslydhh Make sure to link #4150 to this issue.

Fixed by https://github.com/StarRocks/starrocks/pull/4150
