### ISSUE TITLE
[BUG] read paimon table error

### ISSUE THREAD

**Issue by zhourui999** [StarRocks/starrocks#41892]
### Steps to reproduce the behavior (Required)
CREATE EXTERNAL CATALOG paimon_catalog_fs3
PROPERTIES
(
    "type" = "paimon",
    "paimon.catalog.type" = "hive",
    "paimon.catalog.warehouse" = "hdfs://nameHAservice/user/hive/warehouse",
    "hive.metastore.uris" = "*"
);

select * from paimon_catalog_fs3.zr_dev.paimon_rs;

24/02/29 08:55:50 INFO [main] close(HiveMetaStoreClient.java:562): Closed a connection to metastore, current connections: 0
24/02/29 08:55:50 INFO [main] open(HiveMetaStoreClient.java:405): Trying to connect to metastore with URI thrift://hz-hadoop-test-199-151-39:9083
24/02/29 08:55:50 INFO [main] open(HiveMetaStoreClient.java:479): Opened a connection to metastore, current connections: 1
24/02/29 08:55:50 WARN [main] open(HiveMetaStoreClient.java:504): set_ugi() not successful, Likely cause: new client talking to old server. Continuing without it.
org.apache.thrift.transport.TTransportException: null
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:379) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:236) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_set_ugi(ThriftHiveMetastore.java:4247) ~[hive-metastore-2.3.9.jar:2.3.9]
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.set_ugi(ThriftHiveMetastore.java:4233) ~[hive-metastore-2.3.9.jar:2.3.9]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:496) ~[hive-metastore-2.3.9.jar:2.3.9]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.reconnect(HiveMetaStoreClient.java:338) ~[hive-metastore-2.3.9.jar:2.3.9]
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:163) ~[hive-metastore-2.3.9.jar:2.3.9]
        at com.sun.proxy.$Proxy43.getTable(Unknown Source) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2327) ~[hive-metastore-2.3.9.jar:2.3.9]
        at com.sun.proxy.$Proxy43.getTable(Unknown Source) ~[?:?]
        at org.apache.paimon.hive.HiveCatalog.paimonTableExists(HiveCatalog.java:574) ~[paimon-bundle-0.5.0-incubating.jar:0.5.0-incubating]
        at org.apache.paimon.hive.HiveCatalog.getDataTableSchema(HiveCatalog.java:255) ~[paimon-bundle-0.5.0-incubating.jar:0.5.0-incubating]
        at org.apache.paimon.catalog.AbstractCatalog.getDataTable(AbstractCatalog.java:119) ~[paimon-bundle-0.5.0-incubating.jar:0.5.0-incubating]
        at org.apache.paimon.catalog.AbstractCatalog.getTable(AbstractCatalog.java:114) ~[paimon-bundle-0.5.0-incubating.jar:0.5.0-incubating]
        at com.starrocks.paimon.reader.PaimonSplitScanner.initTable(PaimonSplitScanner.java:113) ~[starrocks-paimon-reader.jar:?]
        at com.starrocks.paimon.reader.PaimonSplitScanner.open(PaimonSplitScanner.java:155) ~[starrocks-paimon-reader.jar:?]
24/02/29 08:55:50 INFO [main] open(HiveMetaStoreClient.java:532): Connected to metastore.
24/02/29 08:55:50 ERROR [main] open(PaimonSplitScanner.java:162): Failed to open the paimon reader.
java.lang.RuntimeException: Cannot determine if table zr_dev.paimon_rs is a paimon table.
        at org.apache.paimon.hive.HiveCatalog.paimonTableExists(HiveCatalog.java:579) ~[paimon-bundle-0.5.0-incubating.jar:0.5.0-incubating]
        at org.apache.paimon.hive.HiveCatalog.getDataTableSchema(HiveCatalog.java:255) ~[paimon-bundle-0.5.0-incubating.jar:0.5.0-incubating]
        at org.apache.paimon.catalog.AbstractCatalog.getDataTable(AbstractCatalog.java:119) ~[paimon-bundle-0.5.0-incubating.jar:0.5.0-incubating]
        at org.apache.paimon.catalog.AbstractCatalog.getTable(AbstractCatalog.java:114) ~[paimon-bundle-0.5.0-incubating.jar:0.5.0-incubating]
        at com.starrocks.paimon.reader.PaimonSplitScanner.initTable(PaimonSplitScanner.java:113) ~[starrocks-paimon-reader.jar:?]
        at com.starrocks.paimon.reader.PaimonSplitScanner.open(PaimonSplitScanner.java:155) ~[starrocks-paimon-reader.jar:?]
Caused by: org.apache.thrift.transport.TTransportException
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:425) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:321) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:225) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[libthrift-0.12.0.jar:0.12.0]
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table(ThriftHiveMetastore.java:1514) ~[hive-metastore-2.3.9.jar:2.3.9]
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table(ThriftHiveMetastore.java:1500) ~[hive-metastore-2.3.9.jar:2.3.9]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1346) ~[hive-metastore-2.3.9.jar:2.3.9]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:173) ~[hive-metastore-2.3.9.jar:2.3.9]
        at com.sun.proxy.$Proxy43.getTable(Unknown Source) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2327) ~[hive-metastore-2.3.9.jar:2.3.9]
        at com.sun.proxy.$Proxy43.getTable(Unknown Source) ~[?:?]
        at org.apache.paimon.hive.HiveCatalog.paimonTableExists(HiveCatalog.java:574) ~[paimon-bundle-0.5.0-incubating.jar:0.5.0-incubating]
        ... 5 more
(END)
### StarRocks version (Required)
3.1.8

**Comment by zhourui999** [comment]
1
