### ISSUE TITLE
crash on split

### ISSUE THREAD

**Issue by Seaven** [StarRocks/starrocks#4215]
### Steps to reproduce the behavior (Required)
```
 select (split(id_varchar, id_varchar) is null) <=> (split(id_varchar, NULL) is null) from test_all_null
```
```
#0  0x00007f246a774387 in raise () from /usr/lib64/libc.so.6
#1  0x00007f246a775a78 in abort () from /usr/lib64/libc.so.6
#2  0x00000000062ccb2a in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00000000062cb1d6 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00000000062cb241 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00000000062cb395 in __cxxabiv1::__cxa_throw (obj=obj@entry=0xb1c08f0, tinfo=0x645e860 <typeinfo for std::length_error>, dest=0x62d9e40 <std::length_error::~length_error()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x000000000631adf0 in std::__throw_length_error (__s=__s@entry=0x1fc0c5a "vector::reserve") at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:78
#7  0x0000000002421959 in std::vector<starrocks::Slice, std::allocator<starrocks::Slice> >::reserve (__n=<optimized out>, this=0x85e8740) at /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/vector.tcc:70
#8  starrocks::vectorized::BinaryColumn::_build_slices (this=this@entry=0x85e8700) at /home/disk2/hekai/workspace/DorisDB/be/src/column/binary_column.cpp:193
#9  0x0000000003385fc8 in starrocks::vectorized::BinaryColumn::get_data (this=0x85e8700) at /home/disk2/hekai/workspace/DorisDB/be/src/column/binary_column.h:208
#10 starrocks::vectorized::ColumnHelper::get_const_value<(starrocks::PrimitiveType)10> (col=std::shared_ptr<starrocks::vectorized::Column> (use count 3, weak count 0) = {...}) at /home/disk2/hekai/workspace/DorisDB/be/src/column/column_helper.h:221
#11 starrocks::vectorized::StringFunctions::split_prepare (context=<optimized out>, scope=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/split.cpp:48
#12 0x000000000329fea8 in starrocks::vectorized::VectorizedFunctionCallExpr::open (this=0xb0cb400, state=<optimized out>, context=0xb0b8180, scope=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/function_call_expr.cpp:71
#13 0x0000000002d1e960 in starrocks::Expr::open (this=<optimized out>, state=0xc3da010, context=0xb0b8180, scope=starrocks_udf::FunctionContext::FRAGMENT_LOCAL) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/expr.cpp:433
```
### StarRocks version (Required)
main

**Comment by stdpain** [comment]
it was caused by other SQL
