### ISSUE TITLE
crash on json_query

### ISSUE THREAD

**Issue by Seaven** [StarRocks/starrocks#4216]
### Steps to reproduce the behavior (Required)
```
 select (json_query(id_json, id_varchar)) <=> (json_query(NULL, NULL)) from test_all_null
```

```
#0  0x00007f246a774387 in raise () from /usr/lib64/libc.so.6
#1  0x00007f246a775a78 in abort () from /usr/lib64/libc.so.6
#2  0x00000000062ccb2a in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00000000062cb1d6 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00000000062cb241 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00000000062cb395 in __cxxabiv1::__cxa_throw (obj=obj@entry=0xb1c08f0, tinfo=0x645e860 <typeinfo for std::length_error>, dest=0x62d9e40 <std::length_error::~length_error()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x000000000631adf0 in std::__throw_length_error (__s=__s@entry=0x1fc0c5a "vector::reserve") at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:78
#7  0x0000000002421959 in std::vector<starrocks::Slice, std::allocator<starrocks::Slice> >::reserve (__n=<optimized out>, this=0x85e8740) at /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/vector.tcc:70
#8  starrocks::vectorized::BinaryColumn::_build_slices (this=this@entry=0x85e8700) at /home/disk2/hekai/workspace/DorisDB/be/src/column/binary_column.cpp:193
#9  0x0000000003385fc8 in starrocks::vectorized::BinaryColumn::get_data (this=0x85e8700) at /home/disk2/hekai/workspace/DorisDB/be/src/column/binary_column.h:208
```

### StarRocks version (Required)
main

**Comment by Seaven** [comment]
```
(gdb) bt
#0  0x00000000033112fd in starrocks::vectorized::JsonFunctions::native_json_path_prepare (context=0x14f7adb0, scope=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/json_functions.cpp:415
#1  0x000000000329fea8 in starrocks::vectorized::VectorizedFunctionCallExpr::open (this=0x14435c00, state=<optimized out>, context=0x9988940, scope=<optimized out>) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/vectorized/function_call_expr.cpp:71
#2  0x0000000002d1e960 in starrocks::Expr::open (this=<optimized out>, state=0x1378e410, context=0x9988940, scope=starrocks_udf::FunctionContext::FRAGMENT_LOCAL) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/expr.cpp:433
#3  0x0000000002d1d44e in starrocks::ExprContext::open (this=<optimized out>, state=state@entry=0x1378e410) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/expr_context.cpp:69
#4  0x0000000002d1eff1 in starrocks::Expr::open (ctxs=std::vector of length 1, capacity 1 = {...}, state=state@entry=0x1378e410) at /home/disk2/hekai/workspace/DorisDB/be/src/exprs/expr.cpp:425
#5  0x0000000002870960 in starrocks::vectorized::ProjectNode::open (this=0x14980000, state=0x1378e410) at /home/disk2/hekai/workspace/DorisDB/be/src/exec/vectorized/project_node.cpp:96
#6  0x00000000039a1edb in starrocks::PlanFragmentExecutor::_open_internal_vectorized (this=this@entry=0x13286bc0) at /home/disk2/hekai/workspace/DorisDB/be/src/runtime/plan_fragment_executor.cpp:203
#7  0x00000000039a2bc7 in starrocks::PlanFragmentExecutor::open (this=this@entry=0x13286bc0) at /home/disk2/hekai/workspace/DorisDB/be/src/runtime/plan_fragment_executor.cpp:186
#8  0x00000000039be902 in starrocks::FragmentExecState::execute (this=0x13286b40) at /home/disk2/hekai/workspace/DorisDB/be/src/runtime/fragment_mgr.cpp:193
#9  0x00000000039c316c in starrocks::FragmentMgr::exec_actual(std::shared_ptr<starrocks::FragmentExecState>, std::function<void (starrocks::PlanFragmentExecutor*)> const&) (this=<optimized out>,
```

**Comment by stdpain** [comment]
it was caused by other SQL
