### ISSUE TITLE
The BDB will be stalled in lock

### ISSUE THREAD

**Issue by chaoyli** [StarRocks/starrocks#4327]
### Steps to reproduce the behavior (Required)
The BDB will be stalled in lock
```
"Thread-38" #87 daemon prio=5 os_prio=0 tid=0x00007f72112d2800 nid=0x7528 runnable [0x00007f70e27ea000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.FileDispatcherImpl.force0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.force(FileDispatcherImpl.java:80)
        at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:388)
        at com.sleepycat.je.log.FileManager$LogEndFileDescriptor.force(FileManager.java:3094)
        at com.sleepycat.je.log.FileManager$LogEndFileDescriptor.access$500(FileManager.java:2760)
        at com.sleepycat.je.log.FileManager.syncLogEnd(FileManager.java:2046)
        at com.sleepycat.je.log.FSyncManager.executeFSync(FSyncManager.java:399)
        at com.sleepycat.je.log.FSyncManager.flushAndSync(FSyncManager.java:349)
        at com.sleepycat.je.log.LogManager.log(LogManager.java:343)
        at com.sleepycat.je.txn.Txn.logCommitEntry(Txn.java:1008)
        at com.sleepycat.je.txn.Txn.commit(Txn.java:767)
        - locked <0x00000005da2c2608> (a com.sleepycat.je.rep.txn.MasterTxn)
        at com.sleepycat.je.txn.Txn.commit(Txn.java:625)
        at com.sleepycat.je.txn.Txn.operationEnd(Txn.java:1803)
        at com.sleepycat.je.Database.put(Database.java:1506)
        at com.sleepycat.je.Database.put(Database.java:1556)
        at com.starrocks.journal.bdbje.CloseSafeDatabase.put(CloseSafeDatabase.java:28)
        at com.starrocks.journal.bdbje.BDBJEJournal.write(BDBJEJournal.java:157)
        - locked <0x0000000637b759c0> (a com.starrocks.journal.bdbje.BDBJEJournal)
        at com.starrocks.persist.EditLog.logEdit(EditLog.java:859)
        - locked <0x0000000637b55a20> (a com.starrocks.persist.EditLog)
        at com.starrocks.persist.EditLog.logUpdateReplica(EditLog.java:1057)
        at com.starrocks.master.ReportHandler.sync(ReportHandler.java:511)
        at com.starrocks.master.ReportHandler.tabletReport(ReportHandler.java:293)
        at com.starrocks.master.ReportHandler.access$300(ReportHandler.java:101)
        at com.starrocks.master.ReportHandler$ReportTask.exec(ReportHandler.java:244)
        at com.starrocks.master.ReportHandler.runOneCycle(ReportHandler.java:1119)
        at com.starrocks.common.util.Daemon.run(Daemon.java:119)

   Locked ownable synchronizers:
        - <0x0000000637be7c38> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        - <0x0000000637dda328> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
```

### StarRocks version (Required)
 - branch-2.2 f0805b8e084ba625348c5c4d739a8ad4111e13aa

**Comment by padmejin** [comment]
The main reason is that each thread that writes one journal needs to call `EditLog.logEdit()`, a synchronized method that holds a global lock. As a result, this function becomes the bottleneck of the journal writing pipeline. 
We can use an independent thread called `JournalWriter` to write journals by batch asynchronously. Each thread that needs to write a log can put the log in a blocking queue, while JournalWriter constantly gets as many logs as possible from the queue and write them all to BDB in one transaction. After committing, JournalWriter will notify the caller thread for consistency.
