### ISSUE TITLE
The AcceptListener in StarRocks failed

### ISSUE THREAD

**Issue by chaoyli** [StarRocks/starrocks#4329]
### Steps to reproduce the behavior (Required)
```
2022-03-22 15:58:19,963 WARN (starrocks-mysql-nio-pool-23|829154) [AcceptListener.lambda$handleEvent$1():91] connect processor exception because
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_322]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_322]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_322]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_322]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.8.0_322]
        at org.xnio.nio.NioSocketConduit.read(NioSocketConduit.java:289) ~[xnio-nio-3.7.9.Final.jar:3.7.9.Final]
        at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127) ~[xnio-api-3.7.9.Final.jar:3.7.9.Final]
        at org.xnio.channels.Channels.readBlocking(Channels.java:294) ~[xnio-api-3.7.9.Final.jar:3.7.9.Final]
        at com.starrocks.mysql.nio.NMysqlChannel.readAll(NMysqlChannel.java:67) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.MysqlChannel.fetchOnePacket(MysqlChannel.java:149) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.MysqlProto.negotiate(MysqlProto.java:146) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.AcceptListener.lambda$handleEvent$1(AcceptListener.java:68) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
```

### StarRocks version (Required)
 - branch-2.2 f0805b8e084ba625348c5c4d739a8ad4111e13aa

**Comment by guanxianchun** [comment]
I also encountered a similar problem

java.io.IOException: Error happened when receiving packet.
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:675) ~[fe-core-2.3.0.jar:2.3.0]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[fe-core-2.3.0.jar:2.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
