### ISSUE TITLE
查询报错DAY not  supported in date_trunc format string

### ISSUE THREAD

**Issue by lixiaoyong12** [StarRocks/starrocks#43333]
执行流程
1. 建表语法
  CREATE TABLE `dte__DEFAULT_entity_229_starrocks_time_dataset` (
  `id` int(11) NULL COMMENT "",
  `name` varchar(65533) NULL COMMENT "",
  `createTime` datetime NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`id`)
PARTITION BY date_trunc('DAY', createTime)
DISTRIBUTED BY RANDOM
PROPERTIES (
"replication_num" = "2",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"partition_live_number" = "3",
"compression" = "LZ4"
);
3. INSERT INTO dte__DEFAULT_entity_229_starrocks_time_dataset
	VALUES
		( 1, 'aa', '2024-03-15 13:00:00' ),
		( 2, 'bb', '2024-03-16 14:00:00' ),
		( 3, 'cc', '2024-03-17 15:00:00' ),
		( 4, 'dd', '2024-03-18 16:00:00' ),
		( 5, 'ee', '2024-03-19 17:00:00' );
4. SELECT * FROM dte__DEFAULT_entity_229_starrocks_time_dataset
### Expected behavior (Required)
( 1, 'aa', '2024-03-15 13:00:00' ),
( 2, 'bb', '2024-03-16 14:00:00' ),
( 3, 'cc', '2024-03-17 15:00:00' ),
( 4, 'dd', '2024-03-18 16:00:00' ),
( 5, 'ee', '2024-03-19 17:00:00' );
### Real behavior (Required)
java.lang.IllegalArgumentException: DAY not
 supported in date_trunc format string
### StarRocks version (Required)
3.1
![image](https://github.com/StarRocks/starrocks/assets/34184204/3802cb48-ff64-4e74-b45b-8bdda1bd5ce3)

日志报错
[2024-03-28 17:11:59.446+0800][WARN ][0][starrocks-mysql-nio-pool-14][ROOT][com.starrocks.qe.StmtExecutor][684] execute Exception, sql SELECT * FROM dte__DEFAULT_entity_229_starrocks_time_dataset java.lang.IllegalArgumentException: **DAY not
 supported in date_trunc format string**
        at com.starrocks.sql.optimizer.rewrite.ScalarOperatorFunctions.dateTrunc(ScalarOperatorFunctions.java:266)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.equivalent.DateTruncReplaceChecker.isEquivalent(DateTruncReplaceChecker.java:61)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.PredicateExtractor.rewriteByEquivalent(PredicateExtractor.java:136)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.PredicateExtractor.rewriteBinaryPredicate(PredicateExtractor.java:109)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.PredicateExtractor.visitBinaryPredicate(PredicateExtractor.java:68)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.PredicateExtractor.visitBinaryPredicate(PredicateExtractor.java:35)
        at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:75)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.PredicateExtractor.visitCompoundPredicate(PredicateExtractor.java:169)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.PredicateExtractor.visitCompoundPredicate(PredicateExtractor.java:35)
        at com.starrocks.sql.optimizer.operator.scalar.CompoundPredicateOperator.accept(CompoundPredicateOperator.java:51)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.PredicateSplit.splitPredicate(PredicateSplit.java:77)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.rule.BaseMaterializedViewRewriteRule.getQuerySplitPredicate(BaseMaterializedViewRewriteRule.java:172)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.rule.BaseMaterializedViewRewriteRule.transform(BaseMaterializedViewRewriteRule.java:108)
        at com.starrocks.sql.optimizer.rule.transformation.materialization.rule.SingleTableRewriteBaseRule.transform(SingleTableRewriteBaseRule.java:37)
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:76)
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.execute(RewriteTreeTask.java:59)
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:65)
        at com.starrocks.sql.optimizer.Optimizer.ruleRewriteIterative(Optimizer.java:697)
        at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:429)
        at com.starrocks.sql.optimizer.Optimizer.rewriteAndValidatePlan(Optimizer.java:479)
        at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:183)
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:137)
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:148)
        at com.starrocks.sql.StatementPlanner.planQuery(StatementPlanner.java:123)
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:98)
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:63)
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:453)
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:376)
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:570)
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:848)
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

**Comment by LiShuMing** [comment]
1. What's version 5.1? The newest version should not throw exception in mv rewrite phase.
2. this may be caused materialized view associated with this table, can you provide the associated mvs' schema?

**Comment by lixiaoyong12** [comment]
这个不涉及物化视图，就是普通的一个表，建表语句中没有物化视图，就是个更新表

**Comment by LiShuMing** [comment]
This's a bit werid. 

From the stack, there must be an existed mv associated with the table `dte__DEFAULT_entity_229_starrocks_time_dataset `.

1. You can try to find out the associated mvs:
```
trace rewrite SELECT * FROM dte__DEFAULT_entity_229_starrocks_time_dataset
```

2. You can `set enable_materialized_view_rewrite=false` to disable mv rewrite.
