### ISSUE TITLE
Using MySql.Data NugGet package above 8.0.16 returns error The input string 'True' was not in a correct format

### ISSUE THREAD

**Issue by jcotterill** [StarRocks/starrocks#44024]
https://starrocks.slack.com/archives/C02FACZSNJV/p1708575974580789

### Steps to reproduce the behavior (Required)
Create a .Net Core application with the MySql.Data NugGet package above version 8.0.16.
Use the context builder or try read data from StarRocks.

### Expected behavior (Required)
Return requested data from StarRocks.

### Real behavior (Required)
System.FormatException: The input string 'True' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Convert.ToInt32(String value)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSetsAsync(MySqlConnection connection, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.Driver.ConfigureAsync(MySqlConnection connection, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at MySql.EntityFrameworkCore.Scaffolding.Internal.MySQLDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at MySql.EntityFrameworkCore.Scaffolding.Internal.MySQLDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The input string 'True' was not in a correct format.

### StarRocks version (Required)
3.2.4-613f0b5

**Comment by kangkaisen** [comment]
We will check and fix it

**Comment by jcotterill** [comment]
> We will check and fix it

Hi, was there any update on this? Thank you :)

**Comment by jcotterill** [comment]
Hi @kangkaisen hope you are well? 

Please can you confirm if this was reviewed?

Thanks

**Comment by jcotterill** [comment]
Hi @before-Sunrise - please can you confirm if there was any update on this? Thanks 👍

**Comment by jcotterill** [comment]
Thank you again for your call today.

Please see the example project created and demonstrated in the call to replicate this problem 
https://github.com/jcotterill/StarRocks-MySql-Connector-Issue

**Comment by before-Sunrise** [comment]
> Thank you again for your call today.
> 
> Please see the example project created and demonstrated in the call to replicate this problem https://github.com/jcotterill/StarRocks-MySql-Connector-Issue

got it, I will handle it today

**Comment by before-Sunrise** [comment]
{
  "ConnectionStrings": {
    "DefaultConnection": "server=127.0.0.1;port=19030;uid=root;pwd=;database=test;TreatTinyAsBoolean=false"
  }
}
right now you can skip this problem by set TreatTinyAsBoolean= false, I am checking mysql's behavior to decide whether modify our code

**Comment by before-Sunrise** [comment]
find out mysql's behavior is litte bit different, which make .net work well, I will fix this problem in tomorrow
