### ISSUE TITLE
Alter table throwed java.lang.IllegalStateException in share data mode

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#44070]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t0(c0 INT, c1 BIGINT, c2 DATE) primary key(c0) distributed by hash(c0) buckets 1 order by(c1)
2. ALTER TABLE t0 ORDER BY (c2, c1);
3. Wait until the alter table job finished
4. ALATER TABLE t0 ADD COLUMN c3 DATETIME;

### Expected behavior (Required)
Alter table finished without any error.

### Real behavior (Required)
The last alter table command failed with following error message in `fe.log`:
```
2024-04-15 14:36:38.129+08:00 ERROR (schema change|32) [Daemon.run():109] daemon thread got exception. name: schema change
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:496) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.alter.LakeTableAsyncFastSchemaChangeJob.updateCatalogUnprotected(LakeTableAsyncFastSchemaChangeJob.java:120) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.LakeTableAsyncFastSchemaChangeJob.updateCatalog(LakeTableAsyncFastSchemaChangeJob.java:103) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.LakeTableAlterMetaJobBase.runFinishedRewritingJob(LakeTableAlterMetaJobBase.java:199) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.AlterJobV2.run(AlterJobV2.java:239) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.SchemaChangeHandler.runAlterJobV2(SchemaChangeHandler.java:1422) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.SchemaChangeHandler.runAfterCatalogReady(SchemaChangeHandler.java:1414) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.FrontendDaemon.runOneCycle(FrontendDaemon.java:72) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:107) ~[starrocks-fe.jar:?]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by sduzh** [comment]
The exception is thrown on the following line:
https://github.com/StarRocks/starrocks/blob/7e3fcfb7c3dbfa1684d23f744b5f8f62112de4c7/fe/fe-core/src/main/java/com/starrocks/alter/LakeTableAsyncFastSchemaChangeJob.java#L120
