### ISSUE TITLE
Using Debezium and Hibernate. When connecting using URI with database, it tries to connect to a different catalog.database.  

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#44849]
when the insert happens, it tries to insert into different databases I have. You can see in my database URI I'm connecting to demo database, so it should insert into demo database customer table. I have other databases on the same instance (_statistics_ and information_schema). The jdbc sink code tries to NOT insert into demo.customer but into _statistics_ database and I think table _statistics_.customer. when I create the customer table in _statistics database, then the code tries to insert in information_schema database customer table. It is very odd. It should just insert in the target table and use the database i set in the URI (demo).

```
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||  Starting JdbcSinkConnectorConfig with configuration:   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     connector.class = io.debezium.connector.jdbc.JdbcSinkConnector   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     table.name.format = customer   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     connection.password = ********   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     database.time_zone = UTC   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     tasks.max = 1   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     topics = postgres.public.customer   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     connection.username = root   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     delete.enabled = true   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     hibernate.connection.init_sql = use default_catalog.demo   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     schema.evolution = none   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     task.class = io.debezium.connector.jdbc.JdbcSinkConnectorTask   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     name = jdbc-connector   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     connection.url = jdbc:mysql://starrocks-fe:9030   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,094 INFO   ||     insert.mode = insert   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,098 INFO   ||  HHH000130: Instantiating explicit connection provider: org.hibernate.c3p0.internal.C3P0ConnectionProvider   [org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator]
2024-04-26 10:04:27 2024-04-26 17:04:27,099 INFO   ||  HHH010002: C3P0 using driver: null at URL: jdbc:mysql://starrocks-fe:9030   [org.hibernate.orm.connections.pooling.c3p0]
2024-04-26 10:04:27 2024-04-26 17:04:27,099 INFO   ||  HHH10001001: Connection properties: {password=****, init_sql=use default_catalog.demo, user=root}   [org.hibernate.orm.connections.pooling.c3p0]
2024-04-26 10:04:27 2024-04-26 17:04:27,099 INFO   ||  HHH10001003: Autocommit mode: false   [org.hibernate.orm.connections.pooling.c3p0]
2024-04-26 10:04:27 2024-04-26 17:04:27,099 WARN   ||  HHH10001006: No JDBC Driver class was specified by property `jakarta.persistence.jdbc.driver`, `hibernate.driver` or `javax.persistence.jdbc.driver`   [org.hibernate.orm.connections.pooling.c3p0]
2024-04-26 10:04:27 2024-04-26 17:04:27,111 INFO   ||  HHH10001007: JDBC isolation level: <unknown>   [org.hibernate.orm.connections.pooling.c3p0]
2024-04-26 10:04:27 2024-04-26 17:04:27,112 INFO   ||  Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@c84a1460 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@7c77213f [ acquireIncrement -> 32, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, identityToken -> 1hgeznyb37kogk418zy0i2|1fb0cadd, idleConnectionTestPeriod -> 0, initialPoolSize -> 5, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 32, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 5, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@788fbc44 [ description -> null, driverClass -> null, factoryClassLocation -> null, forceUseNamedDriverClass -> false, identityToken -> 1hgeznyb37kogk418zy0i2|1fd9b521, jdbcUrl -> jdbc:mysql://starrocks-fe:9030, properties -> {password=******, init_sql=use default_catalog.demo, user=******} ], preferredTestQuery -> null, privilegeSpawnedThreads -> false, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, extensions -> {}, factoryClassLocation -> null, identityToken -> 1hgeznyb37kogk418zy0i2|1f4b77fc, numHelperThreads -> 3 ]   [com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource]
2024-04-26 10:04:27 2024-04-26 17:04:27,136 WARN   ||  HHH000511: The 5.1.0 version for [org.hibernate.dialect.MySQLDialect] is no longer supported, hence certain features may not work properly. The minimum supported version is 5.7.0. Check the community dialects project for available legacy versions.   [org.hibernate.dialect.Dialect]
2024-04-26 10:04:27 2024-04-26 17:04:27,145 INFO   ||  HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)   [org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator]
2024-04-26 10:04:27 2024-04-26 17:04:27,145 INFO   ||  Using dialect io.debezium.connector.jdbc.dialect.mysql.MySqlDatabaseDialect   [io.debezium.connector.jdbc.dialect.DatabaseDialectResolver]
2024-04-26 10:04:27 2024-04-26 17:04:27,151 INFO   ||  Database TimeZone: Etc/UTC (global), Etc/UTC (system)   [io.debezium.connector.jdbc.dialect.GeneralDatabaseDialect]
2024-04-26 10:04:27 2024-04-26 17:04:27,153 INFO   ||  Database version 5.1.0   [io.debezium.connector.jdbc.JdbcChangeEventSink]
2024-04-26 10:04:27 2024-04-26 17:04:27,153 INFO   ||  WorkerSinkTask{id=jdbc-connector-0} Sink task finished initialization and start   [org.apache.kafka.connect.runtime.WorkerSinkTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,153 INFO   ||  WorkerSinkTask{id=jdbc-connector-0} Executing sink task   [org.apache.kafka.connect.runtime.WorkerSinkTask]
2024-04-26 10:04:27 2024-04-26 17:04:27,155 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] Cluster ID: j2ymKfRRSuyr_B7cVExOFQ   [org.apache.kafka.clients.Metadata]
2024-04-26 10:04:27 2024-04-26 17:04:27,155 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] Discovered group coordinator kafka:29092 (id: 2147483646 rack: null)   [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2024-04-26 10:04:27 2024-04-26 17:04:27,155 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] (Re-)joining group   [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2024-04-26 10:04:27 2024-04-26 17:04:27,157 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] Request joining group due to: need to re-join with the given member-id: connector-consumer-jdbc-connector-0-9e836584-170d-4981-b76e-a0f7d3287875   [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2024-04-26 10:04:27 2024-04-26 17:04:27,157 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] (Re-)joining group   [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2024-04-26 10:04:27 2024-04-26 17:04:27,158 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] Successfully joined group with generation Generation{generationId=3, memberId='connector-consumer-jdbc-connector-0-9e836584-170d-4981-b76e-a0f7d3287875', protocol='range'}   [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2024-04-26 10:04:27 2024-04-26 17:04:27,158 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] Finished assignment for group at generation 3: {connector-consumer-jdbc-connector-0-9e836584-170d-4981-b76e-a0f7d3287875=Assignment(partitions=[postgres.public.customer-0])}   [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2024-04-26 10:04:27 2024-04-26 17:04:27,160 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] Successfully synced group in generation Generation{generationId=3, memberId='connector-consumer-jdbc-connector-0-9e836584-170d-4981-b76e-a0f7d3287875', protocol='range'}   [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2024-04-26 10:04:27 2024-04-26 17:04:27,160 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] Notifying assignor about the new Assignment(partitions=[postgres.public.customer-0])   [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2024-04-26 10:04:27 2024-04-26 17:04:27,160 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] Adding newly assigned partitions: postgres.public.customer-0   [org.apache.kafka.clients.consumer.internals.ConsumerRebalanceListenerInvoker]
2024-04-26 10:04:27 2024-04-26 17:04:27,160 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] Found no committed offset for partition postgres.public.customer-0   [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2024-04-26 10:04:27 2024-04-26 17:04:27,161 INFO   ||  [Consumer clientId=connector-consumer-jdbc-connector-0, groupId=connect-jdbc-connector] Resetting offset for partition postgres.public.customer-0 to position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[kafka:29092 (id: 1 rack: null)], epoch=0}}.   [org.apache.kafka.clients.consumer.internals.SubscriptionState]
2024-04-26 10:04:27 2024-04-26 17:04:27,170 WARN   ||  SQL Error: 1064, SQLState: 42000   [org.hibernate.engine.jdbc.spi.SqlExceptionHelper]
2024-04-26 10:04:27 2024-04-26 17:04:27,170 ERROR  ||  Unknown table '_statistics_._statistics_.customer'   [org.hibernate.engine.jdbc.spi.SqlExceptionHelper]
2024-04-26 10:04:27 2024-04-26 17:04:27,170 ERROR  ||  Failed to process record: Failed to process a sink record   [io.debezium.connector.jdbc.JdbcSinkConnectorTask]
2024-04-26 10:04:27 org.apache.kafka.connect.errors.ConnectException: Failed to process a sink record
2024-04-26 10:04:27     at io.debezium.connector.jdbc.JdbcChangeEventSink.flushBuffer(JdbcChangeEventSink.java:210)
2024-04-26 10:04:27     at io.debezium.connector.jdbc.JdbcChangeEventSink.lambda$flushBuffers$2(JdbcChangeEventSink.java:188)
2024-04-26 10:04:27     at java.base/java.util.HashMap.forEach(HashMap.java:1337)
2024-04-26 10:04:27     at io.debezium.connector.jdbc.JdbcChangeEventSink.flushBuffers(JdbcChangeEventSink.java:188)
2024-04-26 10:04:27     at io.debezium.connector.jdbc.JdbcChangeEventSink.execute(JdbcChangeEventSink.java:149)
2024-04-26 10:04:27     at io.debezium.connector.jdbc.JdbcSinkConnectorTask.put(JdbcSinkConnectorTask.java:103)
2024-04-26 10:04:27     at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:601)
2024-04-26 10:04:27     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:350)
2024-04-26 10:04:27     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:250)
2024-04-26 10:04:27     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:219)
2024-04-26 10:04:27     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
2024-04-26 10:04:27     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
2024-04-26 10:04:27     at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
2024-04-26 10:04:27     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2024-04-26 10:04:27     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-04-26 10:04:27     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2024-04-26 10:04:27     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2024-04-26 10:04:27     at java.base/java.lang.Thread.run(Thread.java:829)
2024-04-26 10:04:27 Caused by: org.hibernate.exception.SQLGrammarException: error executing work [Unknown table '_statistics_._statistics_.customer'] [n/a]
2024-04-26 10:04:27     at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:64)
2024-04-26 10:04:27     at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
2024-04-26 10:04:27     at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
2024-04-26 10:04:27     at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
2024-04-26 10:04:27     at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:308)
2024-04-26 10:04:27     at org.hibernate.internal.AbstractSharedSessionContract.doWork(AbstractSharedSessionContract.java:977)
2024-04-26 10:04:27     at org.hibernate.internal.AbstractSharedSessionContract.doReturningWork(AbstractSharedSessionContract.java:973)
2024-04-26 10:04:27     at io.debezium.connector.jdbc.JdbcChangeEventSink.readTable(JdbcChangeEventSink.java:272)
2024-04-26 10:04:27     at io.debezium.connector.jdbc.JdbcChangeEventSink.alterTableIfNeeded(JdbcChangeEventSink.java:307)
2024-04-26 10:04:27     at io.debezium.connector.jdbc.JdbcChangeEventSink.checkAndApplyTableChangesIfNeeded(JdbcChangeEventSink.java:258)
2024-04-26 10:04:27     at io.debezium.connector.jdbc.JdbcChangeEventSink.flushBuffer(JdbcChangeEventSink.java:199)
2024-04-26 10:04:27     ... 17 more
2024-04-26 10:04:27 Caused by: java.sql.SQLSyntaxErrorException: Unknown table '_statistics_._statistics_.customer'
2024-04-26 10:04:27     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
2024-04-26 10:04:27     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
2024-04-26 10:04:27     at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1208)
2024-04-26 10:04:27     at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3002)
2024-04-26 10:04:27     at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:2989)
2024-04-26 10:04:27     at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:57)
2024-04-26 10:04:27     at com.mysql.cj.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3051)
2024-04-26 10:04:27     at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getPrimaryKeys(NewProxyDatabaseMetaData.java:3198)
2024-04-26 10:04:27     at io.debezium.connector.jdbc.dialect.GeneralDatabaseDialect.readTable(GeneralDatabaseDialect.java:178)
2024-04-26 10:04:27     at io.debezium.connector.jdbc.JdbcChangeEventSink.lambda$readTable$4(JdbcChangeEventSink.java:272)
2024-04-26 10:04:27     at org.hibernate.jdbc.WorkExecutor.executeReturningWork(WorkExecutor.java:56)
2024-04-26 10:04:27     at org.hibernate.internal.AbstractSharedSessionContract.lambda$doReturningWork$5(AbstractSharedSessionContract.java:973)
2024-04-26 10:04:27     at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:303)
2024-04-26 10:04:27     ... 23 more
```

**Comment by alberttwong** [comment]
I am also using an additional setting of hibernate.connection.init_sql="use default_catalog.demo".  It doesn't matter if I use this additional setting or not.

**Comment by alberttwong** [comment]
https://github.com/debezium/debezium-connector-jdbc/pull/71

**Comment by alberttwong** [comment]
chat with debezium - https://debezium.zulipchat.com/#narrow/stream/383534-community-jdbc/topic/Unknown.20table.20'_statistics_.2E_statistics_.2Ecustomer'

**Comment by alberttwong** [comment]
```
2024-04-26 20:58:09,202 INFO (starrocks-mysql-nio-pool-1|129) [StmtExecutor.execute():710] execute Exception, sql: select $$, error: Getting analyzing error. Detail message: Column '$$' cannot be resolved.
```

**Comment by alberttwong** [comment]
```
Hi @Albert Wong so after looking at this most of the morning, I don't believe StarRocks is feasible without changes that go beyond just setting the catalog name. For example, with the PR build, I actually get this error:

debezium     | Caused by: java.sql.SQLSyntaxErrorException: Access denied; you need (at least one of) the CREATE TABLE privilege(s) on DATABASE test for this operation. Please ask the admin to grant permission(s) or try activating existing roles using <set [default] role>. Current role(s): NONE. Inactivated role(s): NONE.
debezium     |  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
^ NOTE I granted all priviledges to my user, so no idea why this is the case :/

So this tells me the catalog feature works; however, if a table has a primary key or certain types of data like long text, this creates an issue because we hit datatype mismatches because the JDBC sink is using the MySQL dialect but StarRocks does not support all of MySQL's data types. So I truly think we need a StarRocks dialect implementation that handles these nuances before you can use the JDBC sink with this target system.
```
