### ISSUE TITLE
Failed to automatically add partition to dynamic_partition table

### ISSUE THREAD

**Issue by jinshuangxian** [StarRocks/starrocks#45550]
### Steps to reproduce the behavior (Required)
1. Dynamic partition table creation using 
 CREATE TABLE `table_name_xxx` (
  `dt` int(11) NULL COMMENT "日期",
  `distinct_id` varchar(65533) NULL COMMENT "用户去重ID",
  `md5key` varchar(65533) NULL COMMENT "主键id",
  ...
) ENGINE=OLAP 
UNIQUE KEY(`dt`, `distinct_id`, `md5key`, `uid`, `app_id`, `event_code`)
COMMENT "xxx"
PARTITION BY RANGE(`dt`)
(PARTITION p20231028 VALUES [("20231028"), ("20231029")),
...
PARTITION p20240512 VALUES [("20240512"), ("20240513")))
DISTRIBUTED BY HASH(`dt`, `distinct_id`) BUCKETS 5 
PROPERTIES (
"replication_num" = "2",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "UTC",
"dynamic_partition.start" = "-180",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "1",
"dynamic_partition.history_partition_num" = "0",
"datacache.enable" = "true",
"storage_volume" = "olap_storage_volume",
"enable_async_write_back" = "false",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);
2.Our company has 6 clusters(run_mode: shared_data) online, 1 cluster has all the dynamic partition tables, can not dynamically add partitions, the other 5 clusters are normal.
3.With ALTER TABLE xxx ADD PARTITION sql, it can be added successfully.

### Expected behavior (Required)
Automatically add Partition

### Real behavior (Required)
2024-05-13T10:38:51.420598849Z stderr F 2024-05-13 10:38:51.420Z ERROR (DynamicPartitionScheduler|44) [Daemon.run():109] daemon thread got exception. name: DynamicPartitionScheduler2024-05-13T10:38:51.420601613Z stderr F java.lang.IllegalStateException: null
2024-05-13T10:38:51.420603429Z stderr F         at com.google.common.base.Preconditions.checkState(Preconditions.java:496) ~[spark-dpp-1.0.0.jar:?]2024-05-13T10:38:51.420605825Z stderr F         at com.starrocks.catalog.SchemaInfo$Builder.build(SchemaInfo.java:262) ~[starrocks-fe.jar:?]
2024-05-13T10:38:51.420607712Z stderr F         at com.starrocks.server.LocalMetastore.buildCreateReplicaTasks(LocalMetastore.java:2057) ~[starrocks-fe.jar:?]2024-05-13T10:38:51.420609558Z stderr F         at com.starrocks.server.LocalMetastore.buildCreateReplicaTasks(LocalMetastore.java:2027) ~[starrocks-fe.jar:?]2024-05-13T10:38:51.420615847Z stderr F         at com.starrocks.server.LocalMetastore.buildCreateReplicaTasks(LocalMetastore.java:2018) ~[starrocks-fe.jar:?]
2024-05-13T10:38:51.420617738Z stderr F         at com.starrocks.server.LocalMetastore.buildPartitionsSequentially(LocalMetastore.java:1927) ~[starrocks-fe.jar:?] 
2024-05-13T10:38:51.420619334Z stderr F         at com.starrocks.server.LocalMetastore.buildPartitions(LocalMetastore.java:1905) ~[starrocks-fe.jar:?] 2024-05-13T10:38:51.420620962Z stderr F         at com.starrocks.server.LocalMetastore.addPartitions(LocalMetastore.java:1420) ~[starrocks-fe.jar:?]
2024-05-13T10:38:51.420623094Z stderr F         at com.starrocks.server.LocalMetastore.addPartitions(LocalMetastore.java:890) ~[starrocks-fe.jar:?] 2024-05-13T10:38:51.42062537Z stderr F  at com.starrocks.server.GlobalStateMgr.addPartitions(GlobalStateMgr.java:2554) ~[starrocks-fe.jar:?]
2024-05-13T10:38:51.420626529Z stderr F         at com.starrocks.clone.DynamicPartitionScheduler.executeDynamicPartitionForTable(DynamicPartitionScheduler.java:449) ~[starrocks-fe.jar:?]
2024-05-13T10:38:51.420627731Z stderr F         at com.starrocks.clone.DynamicPartitionScheduler.executeDynamicPartition(DynamicPartitionScheduler.java:356) ~[starrocks-fe.jar:?]
2024-05-13T10:38:51.420628788Z stderr F         at com.starrocks.clone.DynamicPartitionScheduler.runAfterCatalogReady(DynamicPartitionScheduler.java:699) ~[starrocks-fe.jar:?]
2024-05-13T10:38:51.42062995Z stderr F  at com.starrocks.common.util.FrontendDaemon.runOneCycle(FrontendDaemon.java:72) ~[starrocks-fe.jar:?]
2024-05-13T10:38:51.420631346Z stderr F         at com.starrocks.common.util.Daemon.run(Daemon.java:107) ~[starrocks-fe.jar:?]

### StarRocks version (Required)
3.2.6-2585333

**Comment by kevincai** [comment]
it's a known issue introduced in v3.2.5 and fixed in PR https://github.com/StarRocks/starrocks/pull/44372

you can either rollback to the version before upgrade or manually apply the fix to FE.
