### ISSUE TITLE
create MATERIALIZED view error

### ISSUE THREAD

**Issue by skypan** [StarRocks/starrocks#4728]
### Steps to reproduce the behavior (Required)
create MATERIALIZED view O_ST_XTGLB_case_process_info_sort_view as
    select OPERATETIMESTAMP,ROWGUID, OPERATEDATE from O_ST_XTGLB_case_process_info_sort order by operatetimestamp asc;

### Expected behavior (Required)
run ok
### Real behavior (Required)
run error, the error log is :

2022-04-02 09:16:04,948 WARN (starrocks-mysql-nio-pool-344|3832) [StmtExecutor.analyze():609] Analyze failed because 
java.lang.NullPointerException: null
	at com.starrocks.analysis.CreateMaterializedViewStmt.analyzeSelectClause(CreateMaterializedViewStmt.java:188) ~[starrocks-fe.jar:?]
	at com.starrocks.analysis.CreateMaterializedViewStmt.analyze(CreateMaterializedViewStmt.java:149) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.analyze(StmtExecutor.java:605) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:319) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$417(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

### StarRocks version (Required)
 2.1.3

**Comment by Astralidea** [comment]
hi @skypan could you provide O_ST_XTGLB_case_process_info_sort detail for me to reproduce this problem?
