### ISSUE TITLE
Enable FQDN access process not working

### ISSUE THREAD

**Issue by renaudk** [StarRocks/starrocks#47942]
Hello, 

The process explained on https://docs.starrocks.io/docs/3.2/administration/management/enable_fqdn/ is not working.

Here is the setup (shared data on S3) :

- FE Leader : 192.168.230.96 (FQDN to use : prd-starrocks-fe01)
- FE Follower 1 : 192.168.230.162 (FQDN to use : prd-starrocks-fe02)
- FE Follower 2 : 192.168.230.163 (FQDN to use : prd-starrocks-fe03)
- FE Follower 3 : 192.168.230.164 (FQDN to use : prd-starrocks-fe04)
- CN node 1 : 192.168.230.166 (FQDN to use : prd-starrocks-cn01)

/etc/hosts:
```
127.0.1.1       prd-starrocks-fe02
192.168.230.96 prd-starrocks-fe01
192.168.230.162 prd-starrocks-fe02
192.168.230.163 prd-starrocks-fe03
192.168.230.164 prd-starrocks-fe04
192.168.230.166 prd-starrocks-cn01
```

I tried to follow the process for the follower 1

When restarting the follower FE Node with --host_type FQDN, I get the following error :

```
2024-07-06 07:14:01.710Z INFO (main|1) [StarRocksFE.start():130] StarRocks FE starting, version: 3.2.8-759cc78
2024-07-06 07:14:01.725Z INFO (main|1) [FrontendOptions.init():85] use configured address. /192.168.230.162
2024-07-06 07:14:01.851Z DEBUG (main|1) [StreamLoadMgr.init():92] begin to init stream load manager
2024-07-06 07:14:01.864Z INFO (main|1) [ConsistencyChecker.initWorkTime():117] parsed startDate: 1970-01-01T23:00:00.000+0000, endDate: 1970-01-01T04:00:00.000+0000
2024-07-06 07:14:02.384Z DEBUG (main|1) [PrivTable.addEntry():93] add priv entry: global priv. host: %, user: root, priv: , set by resolver: false, domain user ident: null
2024-07-06 07:14:02.385Z DEBUG (main|1) [Auth.setPasswordInternal():1451] finished to set password for 'root'@'%'. is replay: true
2024-07-06 07:14:02.386Z DEBUG (main|1) [Auth.grantPrivs():1052] grant Node_priv Admin_priv  on *.* to 'root'@'%', err on non exist: false
2024-07-06 07:14:02.387Z DEBUG (main|1) [PrivTable.addEntry():109] merge priv entry: global priv. host: %, user: root, priv: Node_priv Admin_priv , set by resolver: false, domain user ident: null
2024-07-06 07:14:02.388Z DEBUG (main|1) [Auth.grantInternal():999] finished to grant privilege. is replay: true
2024-07-06 07:14:02.388Z DEBUG (main|1) [Auth.grantPrivs():1093] grant Node_priv Admin_priv  on resource * to 'root'@'%', err on non exist: false
2024-07-06 07:14:02.389Z DEBUG (main|1) [PrivTable.addEntry():109] merge priv entry: global priv. host: %, user: root, priv: Node_priv Admin_priv , set by resolver: false, domain user ident: null
2024-07-06 07:14:02.390Z DEBUG (main|1) [Auth.grantInternal():1043] finished to grant resource privilege. is replay: true
2024-07-06 07:14:02.390Z INFO (main|1) [Auth.grantRoleInternal():837] grant operator to 'root'@'%', isReplay = true
2024-07-06 07:14:02.392Z DEBUG (main|1) [Auth.createUserInternal():720] finished to create user: 'root'@'%', is replay: true
2024-07-06 07:14:02.437Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():284] create built-in role root[-1]
2024-07-06 07:14:02.447Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():284] create built-in role db_admin[-2]
2024-07-06 07:14:02.449Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():284] create built-in role cluster_admin[-3]
2024-07-06 07:14:02.450Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():284] create built-in role user_admin[-4]
2024-07-06 07:14:02.451Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():284] create built-in role public[-5]
2024-07-06 07:14:02.451Z INFO (main|1) [GlobalStateMgr.initAuth():1207] using new privilege framework..
2024-07-06 07:14:02.813Z DEBUG (main|1) [NodeMgr.getCheckedSelfHostPort():712] get self node: 192.168.230.162:9010
2024-07-06 07:14:02.814Z INFO (main|1) [NodeMgr.getHelperNodes():694] get helper nodes: [192.168.230.162:9010]
2024-07-06 07:14:02.830Z DEBUG (main|1) [NodeMgr.isMyself():566] self: 192.168.230.162:9010. helpers: [192.168.230.162:9010]
2024-07-06 07:14:02.831Z DEBUG (main|1) [NodeMgr.isMyself():566] self: 192.168.230.162:9010. helpers: [192.168.230.162:9010]
2024-07-06 07:14:02.831Z INFO (main|1) [NodeMgr.getClusterIdAndRoleOnStartup():495] Current run_mode is shared_data
2024-07-06 07:14:02.832Z INFO (main|1) [NodeMgr.getClusterIdAndRoleOnStartup():502] Got cluster id: 97738194, role: FOLLOWER, node name: 192.168.230.162_9010_1720249910746 and run_mode: shared_data
2024-07-06 07:14:02.834Z INFO (main|1) [BDBEnvironment.ensureHelperInLocal():336] skip check local environment because helper node and local node are identical.
2024-07-06 07:14:02.841Z DEBUG (AuditEventProcessor|62) [AuditEventProcessor$Worker.run():90] update audit plugins. num: 1
2024-07-06 07:14:02.862Z INFO (main|1) [BDBEnvironment.setupEnvironment():266] start to setup bdb environment for 1 times
2024-07-06 07:14:03.578Z WARN (UNKNOWN 192.168.230.162_9010_1720249910746(-1)|1) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: UNKNOWN
2024-07-06 07:14:03.827Z WARN (RepNode 192.168.230.162_9010_1720249910746(-1)|75) [BDBStateChangeListener.stateChange():79] this node is DETACHED
2024-07-06 07:14:03.830Z INFO (UNKNOWN 192.168.230.162_9010_1720249910746(-1)|1) [BDBEnvironment.setupEnvironment():277] replicated environment is all set, wait for state change...
2024-07-06 07:14:13.833Z INFO (UNKNOWN 192.168.230.162_9010_1720249910746(-1)|1) [BDBEnvironment.setupEnvironment():285] state change done, current role UNKNOWN
2024-07-06 07:14:13.835Z ERROR (UNKNOWN 192.168.230.162_9010_1720249910746(-1)|1) [BDBEnvironment.setupEnvironment():302] failed to setup environment after retried 1 times
com.sleepycat.je.EnvironmentFailureException: (JE 18.3.16) Environment must be closed, caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 18.3.16) 192.168.230.162_9010_1720249910746(11):/data/meta/bdb  Feeder: 192.168.230.96_9010_1717495650915(2). Conflicting hostnames for replica id: 192.168.230.162_9010_1720249910746(11) Feeder thinks it is: prd-starrocks-fe02 Replica is configured to use: 192.168.230.162 HANDSHAKE_ERROR: Error during the handshake between two nodes. Some validity or compatibility check failed, preventing further communication between the nodes. Environment is invalid and must be closed. Originally thrown by HA thread: RepNode 192.168.230.162_9010_1720249910746(-1) Originally thrown by HA thread: RepNode 192.168.230.162_9010_1720249910746(-1)
        at com.sleepycat.je.EnvironmentFailureException.wrapSelf(EnvironmentFailureException.java:230) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1835) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.EnvironmentImpl.checkOpen(EnvironmentImpl.java:1844) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.checkOpen(Environment.java:2697) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:659) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setupEnvironment(BDBEnvironment.java:288) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:172) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBEnvironment.initBDBEnvironment(BDBEnvironment.java:150) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalFactory.create(JournalFactory.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initJournal(GlobalStateMgr.java:1231) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1168) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]

```

### StarRocks version (Required)
 - 3.2.8

Any help would be much appreciated :)

**Comment by renaudk** [comment]
I resolved the issue by commenting the line
```
127.0.1.1       prd-starrocks-fe02
```
in /etc/hosts
