### ISSUE TITLE
When I upgrade follower node to 3.3, got unrecongized "clusterId" error

### ISSUE THREAD

**Issue by jhcnet2** [StarRocks/starrocks#48168]
### Steps to reproduce the behavior (Required)

 - upgrade follower node ( one of three frontend nodes)
 - 3.2.7 to 3.3.0
 
### Expected behavior (Required)
frontend start successful

### Real behavior (Required)
frontend start failed
```
2024-07-10 13:18:14.992Z INFO (main|1) [StarRocksFE.start():122] StarRocks FE starting, version: 3.3.0-19a3f66
2024-07-10 13:18:15.000Z INFO (main|1) [FrontendOptions.initAddrUseFqdn():165] Get FQDN from local host by default, FQDN: my-node001-dc1.tossdata.bz, ip: 111.111.111.111, v6: false
2024-07-10 13:18:15.001Z INFO (main|1) [FrontendOptions.initAddrUseFqdn():190] Try to match addr in fqdn mode, ip: 172.17.0.1, FQDN: 172.17.0.1
2024-07-10 13:18:15.002Z INFO (main|1) [FrontendOptions.initAddrUseFqdn():190] Try to match addr in fqdn mode, ip: 111.111.111.111, FQDN: my-node001-dc1.tossdata.bz
2024-07-10 13:18:15.003Z INFO (main|1) [FrontendOptions.initAddrUseFqdn():200] Using FQDN from local host by default, FQDN: my-node001-dc1.tossdata.bz, ip: 111.111.111.111, v6: false
2024-07-10 13:18:15.132Z INFO (main|1) [ConsistencyChecker.initWorkTime():119] parsed startDate: 1970-01-01T23:00:00.000+0000, endDate: 1970-01-01T04:00:00.000+0000
2024-07-10 13:18:15.448Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():301] create built-in role root[-1]
2024-07-10 13:18:15.455Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():301] create built-in role db_admin[-2]
2024-07-10 13:18:15.455Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():301] create built-in role cluster_admin[-3]
2024-07-10 13:18:15.456Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():301] create built-in role user_admin[-4]
2024-07-10 13:18:15.456Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():301] create built-in role public[-5]
2024-07-10 13:18:15.968Z INFO (main|1) [NodeMgr.getHelperNodes():619] get helper nodes: [my-node003-dc1.tossdata.bz:8784]
2024-07-10 13:18:16.019Z INFO (main|1) [NodeMgr.getFeNodeTypeAndNameFromHelpers():526] get fe node type FOLLOWER, name my-node001-dc1.tossdata.bz_8784_1711512966162 from my-node003-dc1.tossdata.bz:8781
2024-07-10 13:18:16.061Z INFO (main|1) [NodeMgr.getVersionFileFromHelper():673] Downloading version file from http://my-node003-dc1.tossdata.bz:8781/version
2024-07-10 13:18:16.390Z WARN (main|1) [NodeMgr.removeMetaFileIfExist():230] Deleted file /opt/starrocks/fe/meta/image/ROLE, maybe because the firstly startup failed.
2024-07-10 13:18:16.391Z WARN (main|1) [NodeMgr.removeMetaFileIfExist():230] Deleted file /opt/starrocks/fe/meta/image/VERSION, maybe because the firstly startup failed.
2024-07-10 13:18:16.391Z ERROR (main|1) [StarRocksFE.start():185] StarRocksFE start failed
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "clusterID" (class com.starrocks.persist.StorageInfo), not marked as ignorable (one known property: "imageJournalId"])
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 15] (through reference chain: com.starrocks.persist.StorageInfo["clusterID"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1138) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1709) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1687) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3809) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.starrocks.server.NodeMgr.getStorageInfo(NodeMgr.java:568) ~[starrocks-fe.jar:?]
        at com.starrocks.server.NodeMgr.getNewImageOnStartup(NodeMgr.java:699) ~[starrocks-fe.jar:?]
        at com.starrocks.server.NodeMgr.getClusterIdAndRoleOnStartup(NodeMgr.java:435) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1055) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:128) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:83) ~[starrocks-fe.jar:?]
```
### StarRocks version (Required)
 - 3.3.0

**Comment by jhcnet2** [comment]
first follower nodes start failed.

**Comment by kevincai** [comment]
@HangyuanLiu
