### ISSUE TITLE
zstd: upgrade from v1.5.0 to v1.5.7

### ISSUE THREAD

**Issue by derekperkins** [StarRocks/starrocks#48393]
## Enhancement
According to a comment in https://github.com/StarRocks/starrocks/pull/46966#issuecomment-2227154208, StarRocks is on v1.5.0. I'm not familiar with the codebase, but after lots of searching, I can't find where that is specified. Here are links to what I did find, including some version skew.

- ORC: v1.4.5 ([link](https://github.com/StarRocks/starrocks/blob/main/be/src/formats/orc/apache-orc/cmake_modules/ThirdpartyToolchain.cmake#L18))
- Paimon: v1.5.5-5 ([link](https://github.com/StarRocks/starrocks/blob/main/java-extensions/paimon-reader/pom.xml#L22))
- Kudu: v1.5.5-5 ([link](https://github.com/StarRocks/starrocks/blob/main/java-extensions/kudu-reader/pom.xml#L22))
- From this patch: v1.5.0 ([link](https://github.com/StarRocks/starrocks/blob/main/thirdparty/download-thirdparty.sh#L482))

v1.5.0 was released in May 2021, with at least 1 data corruption bug fixed since then, plus many performance and other enhancements. Presumably this is backwards compatible, since only the patch version changed, and hopefully would be a quick win.

**Comment by derekperkins** [comment]
Not stale

**Comment by murphyatwork** [comment]
+1

**Comment by kevincai** [comment]
looks like some incompatibility change between v1.5.0 ~ v1.5.7
```
[ RUN      ] OrcChunkReaderTest.Normal
/home/disk4/caixiaohua/git-src/starrocks/be/test/formats/orc/orc_chunk_reader_test.cpp:234: Failure
Expected equality of these values:
  records
    Which is: 9992
  total_record_num
    Which is: 10000
[  FAILED  ] OrcChunkReaderTest.Normal (2 ms)
[ RUN      ] OrcChunkReaderTest.NullSlotDescriptor
/home/disk4/caixiaohua/git-src/starrocks/be/test/formats/orc/orc_chunk_reader_test.cpp:245: Failure
Expected equality of these values:
  records
    Which is: 9992
  total_record_num
    Which is: 10000
[  FAILED  ] OrcChunkReaderTest.NullSlotDescriptor (1 ms)
[ RUN      ] OrcChunkReaderTest.SkipStripe
/home/disk4/caixiaohua/git-src/starrocks/be/test/formats/orc/orc_chunk_reader_test.cpp:272: Failure
Expected equality of these values:
  records
    Which is: 4872
  filter->expected_rows()
    Which is: 4880
[  FAILED  ] OrcChunkReaderTest.SkipStripe (0 ms)
```

**Comment by derekperkins** [comment]
Hard to say for sure, but it seems likely that may be broken behavior before that is now fixed?

**Comment by kevincai** [comment]
possibly something wrong with the test file

```
$ java -jar ~/bin/orc-tools-1.9.7-uber.jar data -n 8000 be/test/exec/test_data/orc_scanner/tpch_10k.orc.zstd > all-1w.data
[main] WARN org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Processing data file be/test/exec/test_data/orc_scanner/tpch_10k.orc.zstd [length: 76791]
Unable to dump data for file: be/test/exec/test_data/orc_scanner/tpch_10k.orc.zstd
io.airlift.compress.MalformedInputException: Bit stream is not fully consumed: offset=15945
	at io.airlift.compress.zstd.Util.verify(Util.java:45)
	at io.airlift.compress.zstd.Huffman.decodeTail(Huffman.java:316)
	at io.airlift.compress.zstd.Huffman.decode4Streams(Huffman.java:288)
	at io.airlift.compress.zstd.ZstdFrameDecompressor.decodeCompressedLiterals(ZstdFrameDecompressor.java:786)
	at io.airlift.compress.zstd.ZstdFrameDecompressor.decodeCompressedBlock(ZstdFrameDecompressor.java:297)
	at io.airlift.compress.zstd.ZstdFrameDecompressor.decompress(ZstdFrameDecompressor.java:184)
	at io.airlift.compress.zstd.ZstdDecompressor.decompress(ZstdDecompressor.java:44)
	at org.apache.orc.impl.AircompressorCodec.decompress(AircompressorCodec.java:94)
	at org.apache.orc.impl.InStream$CompressedStream.readHeader(InStream.java:521)
	at org.apache.orc.impl.InStream$CompressedStream.ensureUncompressed(InStream.java:548)
	at org.apache.orc.impl.InStream$CompressedStream.read(InStream.java:527)
	at org.apache.orc.impl.RunLengthIntegerReaderV2.readValues(RunLengthIntegerReaderV2.java:57)
	at org.apache.orc.impl.RunLengthIntegerReaderV2.next(RunLengthIntegerReaderV2.java:329)
	at org.apache.orc.impl.RunLengthIntegerReaderV2.nextVector(RunLengthIntegerReaderV2.java:379)
	at org.apache.orc.impl.TreeReaderFactory$IntTreeReader.nextVector(TreeReaderFactory.java:676)
	at org.apache.orc.impl.reader.tree.StructBatchReader.readBatchColumn(StructBatchReader.java:65)
	at org.apache.orc.impl.reader.tree.StructBatchReader.nextBatchForLevel(StructBatchReader.java:100)
	at org.apache.orc.impl.reader.tree.StructBatchReader.nextBatch(StructBatchReader.java:77)
	at org.apache.orc.impl.RecordReaderImpl.nextBatch(RecordReaderImpl.java:1443)
	at org.apache.orc.tools.PrintData.printJsonData(PrintData.java:208)
	at org.apache.orc.tools.PrintData.main(PrintData.java:288)
	at org.apache.orc.tools.Driver.main(Driver.java:115)
```

```
$ java -jar ~/bin/orc-tools-2.0.0-uber.jar data -n 8000 be/test/exec/test_data/orc_scanner/tpch_10k.orc.zstd > all-1w.data
[main] WARN org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Processing data file be/test/exec/test_data/orc_scanner/tpch_10k.orc.zstd [length: 76791]
Unable to dump data for file: be/test/exec/test_data/orc_scanner/tpch_10k.orc.zstd
com.github.luben.zstd.ZstdException: Restored data doesn't match checksum
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:205)
	at com.github.luben.zstd.Zstd.decompressByteArray(Zstd.java:439)
	at org.apache.orc.impl.ZstdCodec.decompress(ZstdCodec.java:228)
	at org.apache.orc.impl.InStream$CompressedStream.readHeader(InStream.java:521)
	at org.apache.orc.impl.InStream$CompressedStream.ensureUncompressed(InStream.java:548)
	at org.apache.orc.impl.InStream$CompressedStream.read(InStream.java:527)
	at org.apache.orc.impl.RunLengthIntegerReaderV2.readValues(RunLengthIntegerReaderV2.java:57)
	at org.apache.orc.impl.RunLengthIntegerReaderV2.next(RunLengthIntegerReaderV2.java:329)
	at org.apache.orc.impl.RunLengthIntegerReaderV2.nextVector(RunLengthIntegerReaderV2.java:379)
	at org.apache.orc.impl.TreeReaderFactory$IntTreeReader.nextVector(TreeReaderFactory.java:676)
	at org.apache.orc.impl.reader.tree.StructBatchReader.readBatchColumn(StructBatchReader.java:65)
	at org.apache.orc.impl.reader.tree.StructBatchReader.nextBatchForLevel(StructBatchReader.java:100)
	at org.apache.orc.impl.reader.tree.StructBatchReader.nextBatch(StructBatchReader.java:77)
	at org.apache.orc.impl.RecordReaderImpl.nextBatch(RecordReaderImpl.java:1434)
	at org.apache.orc.tools.PrintData.printJsonData(PrintData.java:208)
	at org.apache.orc.tools.PrintData.main(PrintData.java:288)
	at org.apache.orc.tools.Driver.main(Driver.java:115)
```

Different versions of java orc-tool reports error when dumping the test file.

**Comment by kevincai** [comment]
caused by #61453

will fix the corruption first and then upgrade the zstd.
