### ISSUE TITLE
How to solve FE FOLLOWER Alive: false issue

### ISSUE THREAD

**Issue by fiozhao** [StarRocks/starrocks#48523]
mysql> SHOW PROC '/frontends'\G
*************************** 1. row ***************************
             Name: 192.168.100.67_9010_1710931706732
               IP: 192.168.100.67
      EditLogPort: 9010
         HttpPort: 8030
        QueryPort: 0
          RpcPort: 0
             Role: FOLLOWER
        ClusterId: 1206449193
             Join: false
            Alive: false
ReplayedJournalId: 0
    LastHeartbeat: NULL
         IsHelper: true
           ErrMsg: invalid cluster id: 2098925161
        StartTime: NULL
          Version: NULL
*************************** 2. row ***************************
             Name: 192.168.100.66_9010_1710930697136
               IP: 192.168.100.66
      EditLogPort: 9010
         HttpPort: 8030
        QueryPort: 9030
          RpcPort: 9020
             Role: LEADER
        ClusterId: 1206449193
             Join: true
            Alive: true
ReplayedJournalId: 3286454
    LastHeartbeat: 2024-07-18 08:50:48
         IsHelper: true
           ErrMsg:
        StartTime: 2024-07-17 16:19:42
          Version: 3.1.7-7e897e2
2 rows in set (0.03 sec)

**Comment by kevincai** [comment]
> ErrMsg: invalid cluster id: 2098925161

stop the follower fe and clean content under the `fe/meta/` directory and start the fe.

**Comment by fiozhao** [comment]
The LEADER  FE failed.
1. stop the follower fe and clean content under the fe/meta/ directory (rm -rf bdb &&  rm -rf image/
)and start the fe.
2. mysql> alter system add follower "192.168.100.67:9010";
ERROR 2013 (HY000): Lost connection to MySQL server during query
3. mysql -h 192.168.100.66 -P 9030 -u root -pxxxx
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on '192.168.100.66' (111)
4. tail -30 fe/log/fe.warn.log
        at com.sleepycat.je.Environment.beginTransaction(Environment.java:1383) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.batchWriteBegin(BDBJEJournal.java:316) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalWriter.writeOneBatch(JournalWriter.java:107) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalWriter$1.runOneCycle(JournalWriter.java:87) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:107) ~[starrocks-fe.jar:?]
2024-07-18 09:49:20,084 WARN (JournalWriter|80) [JournalWriter.writeOneBatch():122] failed to write batch, will abort current journal com.starrocks.journal.JournalTask@22c8956d and commit
com.starrocks.journal.JournalException: failed to begin txn after retried 3 times! db = CloseSafeDatabase{db=3251520}
        at com.starrocks.journal.bdbje.BDBJEJournal.batchWriteBegin(BDBJEJournal.java:323) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalWriter.writeOneBatch(JournalWriter.java:107) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.JournalWriter$1.runOneCycle(JournalWriter.java:87) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:107) ~[starrocks-fe.jar:?]
Caused by: com.sleepycat.je.rep.InsufficientReplicasException: (JE 18.3.16) Commit policy: SIMPLE_MAJORITY required 1 replica. But none were active with this master.
        at com.sleepycat.je.rep.impl.node.DurabilityQuorum.ensureReplicasForCommit(DurabilityQuorum.java:116) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.rep.impl.RepImpl.txnBeginHook(RepImpl.java:1171) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.rep.txn.MasterTxn.txnBeginHook(MasterTxn.java:195) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.txn.Txn.initTxn(Txn.java:384) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.txn.Txn.<init>(Txn.java:288) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.txn.Txn.<init>(Txn.java:267) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.rep.txn.MasterTxn.<init>(MasterTxn.java:146) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.rep.txn.MasterTxn$1.create(MasterTxn.java:117) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.rep.txn.MasterTxn.create(MasterTxn.java:435) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.rep.impl.RepImpl.createRepUserTxn(RepImpl.java:1145) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.txn.Txn.createUserTxn(Txn.java:315) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.txn.TxnManager.txnBegin(TxnManager.java:199) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.dbi.EnvironmentImpl.txnBegin(EnvironmentImpl.java:2540) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.beginTransactionInternal(Environment.java:1498) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.sleepycat.je.Environment.beginTransaction(Environment.java:1383) ~[starrocks-bdb-je-18.3.16.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.batchWriteBegin(BDBJEJournal.java:316) ~[starrocks-fe.jar:?]
        ... 3 more
2024-07-18 09:49:20,085 ERROR (JournalWriter|80) [JournalWriter.abortJournalTask():176] failed to begin txn after retried 3 times! db = CloseSafeDatabase{db=3251520}
