### ISSUE TITLE
OOM error when executing udaf

### ISSUE THREAD

**Issue by sanikoyes** [StarRocks/starrocks#49438]
### Steps to reproduce the behavior (Required)
1. create udaf
2. execute 
3. oom in error message

```
W0806 17:14:30.675108 29943 fragment_context.cpp:176] [Driver] Canceled, query_id=474941d8-53d4-11ef-aa4f-0242652f24d0, instance_id=474941d8-53d4-11ef-aa4f-0242652f24d2, reason=InternalError
W0806 17:14:30.675132 29944 fragment_context.cpp:176] [Driver] Canceled, query_id=474941d8-53d4-11ef-aa4f-0242652f24d0, instance_id=474941d8-53d4-11ef-aa4f-0242652f24d6, reason=InternalError
W0806 17:14:30.676636 29964 java_udf.cpp:275] fail to create array java.nio.BufferUnderflowException
        at java.base/java.nio.DirectLongBufferU.get(DirectLongBufferU.java:294)
        at java.base/java.nio.LongBuffer.get(LongBuffer.java:770)
        at com.starrocks.udf.UDFHelper.createBoxedLongArray(UDFHelper.java:504)
        at com.starrocks.udf.UDFHelper.createBoxedArray(UDFHelper.java:385)
W0806 17:14:30.678236 29964 pipeline_driver.cpp:353] push_chunk returns not ok status Runtime error: OOM may happened in Java Heap
be/src/exec/aggregator.cpp:773 check_has_error()
be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.cpp:183 _aggregator->compute_batch_agg_states(chunk.get(), chunk_size)
be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.cpp:85 _push_chunk_by_auto(chunk, chunk->num_rows())
W0806 17:14:30.678260 29964 pipeline_driver_executor.cpp:170] [Driver] Process error, query_id=474941d8-53d4-11ef-aa4f-0242652f24d0, instance_id=474941d8-53d4-11ef-aa4f-0242652f24d6, status=Runtime error: OOM may happened in Java Heap
be/src/exec/aggregator.cpp:773 check_has_error()
be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.cpp:183 _aggregator->compute_batch_agg_states(chunk.get(), chunk_size)
be/src/exec/pipeline/aggregate/aggregate_streaming_sink_operator.cpp:85 _push_chunk_by_auto(chunk, chunk->num_rows())
W0806 17:14:30.679044 29968 java_udf.cpp:275] fail to create array java.nio.BufferUnderflowException
        at java.base/java.nio.DirectLongBufferU.get(DirectLongBufferU.java:294)
        at java.base/java.nio.LongBuffer.get(LongBuffer.java:770)
        at com.starrocks.udf.UDFHelper.createBoxedLongArray(UDFHelper.java:504)
        at com.starrocks.udf.UDFHelper.createBoxedArray(UDFHelper.java:385)
```

my udf function source is 
```java
public class TaDateCollect {
  public static class State {
    HashSet<Long> dateSets = new HashSet<>();
    List<Long> timestamps = new ArrayList<Long>();
    TypeReference<List<Long>> typ = new TypeReference<List<Long>>() {};

    public int serializeLength() {
      return 4 + JSONObject.toJSONString(timestamps).getBytes(StandardCharsets.UTF_8).length;
    }
  }

  public State create() {
    return new State();
  }

  public void destroy(State state) {
    state.dateSets.clear();
    state.timestamps.clear();
  }

  public final void update(State state, Long timestamp) {
    if (timestamp != null) {
      if (state.dateSets.contains(timestamp)) {
        return;
      }

      state.timestamps.add(timestamp);
      state.dateSets.add(timestamp);
    }
  }

  public void serialize(State state, java.nio.ByteBuffer buff) {
    byte[] bytes = JSONObject.toJSONString(state.timestamps).getBytes(StandardCharsets.UTF_8);
    buff.putInt(bytes.length);
    buff.put(bytes);
  }

  public void merge(State state, java.nio.ByteBuffer buffer) {
    int len = buffer.getInt();
    byte[] bytes = new byte[len];
    buffer.get(bytes);
    final String json = new String(bytes, StandardCharsets.UTF_8);

    List<Long> timestamps = JSONObject.parseObject(json, state.typ);
    for (Long ts : timestamps) {
      update(state, ts);
    }
  }

  public String finalize(State state) {
    return JSONObject.toJSONString(state.timestamps);
  }
}
```

sql is
```sql
SELECT
  virtual_user_id,
  ta_date_collect (`init_date`) `init_date_array`,
  ta_date_collect (`return_date`) `return_date_array`
FROM
  (
    SELECT
      virtual_user_id,
      CASE
        WHEN `@retention_type` = 0 THEN `@trunc_date`
        ELSE NULL
      END `init_date`,
      CASE
        WHEN `@retention_type` = 1 THEN `@trunc_date`
        ELSE NULL
      END `return_date`
    FROM
      (
        SELECT
          virtual_user_id,
          cast(coalesce(SUM(ta_ev.`price`), 0) AS double) stat_amount,
          `@trunc_date`,
          `@retention_type`
        FROM
          ...
        WHERE
          virtual_user_id IS NOT NULL
          AND (
            (`@retention_type` = 0)
            OR (`@retention_type` = 1)
            OR (`@retention_type` = 2)
          )
          AND (ta_ev.`#vp@paichu` IN ('正常'))
        GROUP BY
          virtual_user_id,
          `@trunc_date`,
          `@retention_type`
      ) t
  ) t
GROUP BY
  virtual_user_id
LIMIT
  10;
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

3.2.8-759cc78

**Comment by stdpain** [comment]
closed by https://github.com/StarRocks/starrocks/pull/48618
