### ISSUE TITLE
Machine power outage causes FE data damage

### ISSUE THREAD

**Issue by motto1314** [StarRocks/starrocks#49579]
### Steps to reproduce the behavior (Required)
1. Start FE
2. Machine power outage

### Expected behavior (Required)
FE is normal

### Real behavior (Required)
FE is bad: 

BEFORE Matchine power outage,  image.11833157 is save, log is:
```
2024-08-08T14:25:34,761 com.starrocks.server.GlobalStateMgr [leaderCheckpointer]-[line-1687] INFO  - finished save image /opt/data/meta/image/image.ckpt in 550 ms. checksum is -12510773
2024-08-08T14:25:34,764 com.starrocks.server.GlobalStateMgr [leaderCheckpointer]-[line-1624] INFO  - Move /opt/data/meta/image/image.ckpt to /opt/data/meta/image/image.11833157
2024-08-08T14:25:34,764 com.starrocks.leader.Checkpoint [leaderCheckpointer]-[line-210] INFO  - checkpoint finished save image.11833157
2024-08-08T14:25:34,765 com.starrocks.leader.Checkpoint [leaderCheckpointer]-[line-129] INFO  - push image.11833157 from subdir [] to other nodes. totally 0 nodes, push succeeded 0 nodes
2024-08-08T14:25:34,775 com.starrocks.leader.Checkpoint [leaderCheckpointer]-[line-180] INFO  - journals <= 11833157 with prefix [] are deleted. image version 11833157, other nodes min version 9223372036854775807
2024-08-08T14:25:34,778 com.starrocks.persist.MetaCleaner [leaderCheckpointer]-[line-65] INFO  - /opt/data/meta/image/image.11825934 deleted.
```

AFTER Matchine power outage, log is:
```
2024-08-08T14:59:07,784 com.starrocks.server.GlobalStateMgr [.....(-1)]-[line-1361] WARN  - load image eof.
java.io.EOFException: null
        at java.io.DataInputStream.readInt(DataInputStream.java:397) ~[?:?]
        at com.starrocks.server.GlobalStateMgr.loadHeader(GlobalStateMgr.java:1443) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1312) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:962) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:116) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:68) [starrocks-fe.jar:?]
2024-08-08T14:59:07,795 com.starrocks.StarRocksFE [......(-1)]-[line-170] ERROR - StarRocksFE start failed
java.lang.IllegalStateException: -1 vs. 0
        at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1366) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:962) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:116) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:68) [starrocks-fe.jar:?]
```
AFTER Matchine power outage,  image is:
```
[root@... fe]# ll /opt/data/meta/image/
total 8
-rw-r--r-- 1 root root  0 Aug  8 15:11 image.11833157
-rw-r--r-- 1 root root 91 Aug  8 15:11 ROLE
-rw-r--r-- 1 root root 93 Aug  8 15:11 VERSION
```
 image.11833157 size is 0...

### StarRocks version (Required)
 - 2.5.16

**Comment by kevincai** [comment]
do you have only one FE instance? @motto1314

**Comment by kevincai** [comment]
#46468

**Comment by motto1314** [comment]
> do you have only one FE instance? @motto1314

yes, and #46468 is copy from leader? one FE instance not HELPER operate?
