### ISSUE TITLE
[BUG] es catalog Unknown table 'default_db.test_indexx1'.

### ISSUE THREAD

**Issue by Jin-H** [StarRocks/starrocks#49681]
### Steps to reproduce the behavior (Required)
1. create es catalog
```sql
CREATE EXTERNAL CATALOG es7
COMMENT 'es7'
PROPERTIES
(
    "type" = "es",
    "hosts" = "http://ip:9200",
    "es.type" = "_doc"
);
```
2. show tables
```sql
show tables from es7.default_db;
```
![image](https://github.com/user-attachments/assets/4adc52ec-c14f-4f33-a342-322224a0e681)

3. query table
```sql
select * from es7.default_db.test_indexx1
```

![image](https://github.com/user-attachments/assets/b59c63e5-5c24-48ad-b720-be0d78a9b89b)

4. error log
```log
2024-08-10 15:45:57.815+08:00 INFO (starrocks-mysql-nio-pool-2|150) [MetadataMgr$QueryMetadatas.getConnectorMetadata():107] Succeed to register query level connector metadata [catalog:es7, queryId: 94a9051d-56ec-11ef-87c5-8e7f870c087f]
2024-08-10 15:45:57.826+08:00 ERROR (starrocks-mysql-nio-pool-2|150) [ElasticsearchMetadata.toEsTable():94] transform to EsTable Error
java.lang.ClassCastException: class org.json.JSONArray cannot be cast to class org.json.JSONObject (org.json.JSONArray and org.json.JSONObject are in unnamed module of loader 'app')
        at com.starrocks.connector.elasticsearch.EsUtil.parsePropertiesRoot(EsUtil.java:238) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.elasticsearch.EsUtil.parseProperties(EsUtil.java:203) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.elasticsearch.EsUtil.convertColumnSchema(EsUtil.java:122) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.elasticsearch.ElasticsearchMetadata.toEsTable(ElasticsearchMetadata.java:83) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.elasticsearch.ElasticsearchMetadata.getTable(ElasticsearchMetadata.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.CatalogConnectorMetadata.getTable(CatalogConnectorMetadata.java:134) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.lambda$getTable$5(MetadataMgr.java:485) ~[starrocks-fe.jar:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
```

### Expected behavior (Required)
query can be executed.

### StarRocks version (Required)
 - 3.3.0-19a3f66

**Comment by trapped** [comment]
Hey @Jin-H! I'm also running into this error. Is there a built Docker image I can use to test #49949's fix?

**Comment by Jin-H** [comment]
Sorry, I don't have a compiled image at the moment. If you need to use it, you may need to wait for the patch to be merged or compile it yourself.

**Comment by eoriented** [comment]
I’m encountering the same error.
It appears that the root cause is related to how the ES catalog retrieves transport_address information by calling the _search_shards API. 
The corresponding logic is implemented in this part of the [code](https://github.com/StarRocks/starrocks/blob/3fb06e0ff157d8a64a0dcd772bf4b8e9f595a000/fe/fe-core/src/main/java/com/starrocks/connector/elasticsearch/EsShardRouting.java#L45).
However, the current response from the _search_shards API no longer includes the transport_address field, which prevents the index from being queried properly.
Are there any known workarounds or alternative approaches to handle this issue?

**Comment by Jin-H** [comment]
What is your starrocks version? You can try version 3.3.12. See https://github.com/StarRocks/starrocks/pull/57049
