### ISSUE TITLE
CN crashed while ingesting data into pk table with 3.3.2 shard-data mode cluster

### ISSUE THREAD

**Issue by wxl24life** [StarRocks/starrocks#50034]
### Steps to reproduce the behavior (Required)
1. upgrading from 3.3.0 to 3.3.2, shared-data
2. ingest data into pk table

### Real behavior (Required)

```
** Aborted at 1724144592 (unix time) try "date -d @1724144592" if you are using GNU date ***
PC: @     0x7fc558a36387 __GI_raise
*** SIGABRT (@0x7) received by PID 7 (TID 0x7fc36aa7d700) from PID 7; stack trace: ***
    @     0x7fc559e0620b __pthread_once_slow
    @          0x79fb8f0 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x7fc559e0f630 (/usr/lib64/libpthread-2.17.so+0xf62f)
    @     0x7fc558a36387 __GI_raise
    @     0x7fc558a37a78 __GI_abort
    @          0x352e00e starrocks::failure_function()
    @          0x79f027a google::LogMessage::Fail()
    @          0x79f1645 google::LogMessageFatal::~LogMessageFatal()
    @          0x7bdfc62 brpc::BaiduStreamingLogHandler(google::protobuf::LogLevel, char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    @          0x7d8280a google::protobuf::internal::LogMessage::Finish()
    @          0x7dc0c70 google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Get(int) const
    @          0x61f0106 starrocks::lake::RowsetUpdateState::load_delete(unsigned int, starrocks::lake::RowsetUpdateStateParams const&)
    @          0x61dea8c starrocks::lake::UpdateManager::publish_primary_key_tablet(starrocks::TxnLogPB_OpWrite const&, long, std::shared_ptr<starrocks::TabletMetadataPB const> const&, starrocks::lake::Tablet*, starrocks::DynamicCache<unsigned long, starrocks::lake::LakePrimaryIndpt<AC>^R
    @          0x6223311 starrocks::lake::PrimaryKeyTxnLogApplier::apply_write_log(starrocks::TxnLogPB_OpWrite const&, long)
    @          0x6223610 std::_Function_handler<starrocks::Status (), starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&)
    @          0x6223655 starrocks::lake::PrimaryKeyTxnLogApplier::check_and_recover(std::function<starrocks::Status ()> const&)
    @          0x6228180 starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)
    @          0x61cd4d8 starrocks::lake::publish_version(starrocks::lake::TabletManager*, long, long, long, std::vector<starrocks::TxnInfoPB, std::allocator<starrocks::TxnInfoPB> > const&)
    @          0x3798f37 starrocks::LakeServiceImpl::publish_version(google::protobuf::RpcController*, starrocks::PublishVersionRequest const*, starrocks::PublishVersionResponse*, google::protobuf::Closure*)::{lambda()#1}::operator()() const
    @          0x379ab1a std::_Function_handler<void (), starrocks::ConcurrencyLimitedThreadPoolToken::submit_func(std::function<void ()>, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda()#1}>::_M_invokept<AC>^R
    @          0x383e96b starrocks::ThreadPool::dispatch_thread()
    @          0x3838606 starrocks::Thread::supervise_thread(void*)
    @     0x7fc559e07ea5 start_thread
    @     0x7fc558afe96d __clone
```

gcore result

```shell
0  0x00007f31c1a36387 in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f2e04fff700 (LWP 1816))]
(gdb) bt
#0  0x00007f31c1a36387 in raise () from /lib64/libc.so.6
#1  0x00007f31c1a37a78 in abort () from /lib64/libc.so.6
#2  0x000000000352e00e in starrocks::failure_function () at be/src/common/logconfig.cpp:131
#3  0x00000000079f027a in google::LogMessage::Fail () at ./glog-0.7.1/src/logging.cc:2076
#4  0x00000000079f1645 in google::LogMessageFatal::~LogMessageFatal (this=0x7f2e04fe61b0, __in_chrg=<optimized out>) at ./glog-0.7.1/src/logging.cc:2768
#5  0x0000000007bdfc62 in brpc::BaiduStreamingLogHandler (level=<optimized out>, filename=0xc8f6608 "./google/protobuf/repeated_field.h", line=1706, 
    message="CHECK failed: (index) < (current_size_): ") at src/brpc/global.cpp:318
#6  0x0000000007d8280a in google::protobuf::internal::LogMessage::Finish (this=0x7f2e04fe62a0) at google/protobuf/stubs/common.cc:254
#7  0x0000000007dc0c70 in google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler> (index=0, this=0x7f2d049bf788) at ./google/protobuf/repeated_field.h:1706
#8  google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Get (this=0x7f2d049bf788, index=index@entry=0)
    at ./google/protobuf/repeated_field.h:2173
#9  0x00000000061f0106 in starrocks::TxnLogPB_OpWrite::_internal_del_encryption_metas[abi:cxx11](int) const (index=0, this=<optimized out>)
    at be/src/gen_cpp/build/gen_cpp/lake_types.pb.h:6990
#10 starrocks::TxnLogPB_OpWrite::del_encryption_metas[abi:cxx11](int) const (index=0, this=<optimized out>) at be/src/gen_cpp/build/gen_cpp/lake_types.pb.h:6994
#11 starrocks::lake::RowsetUpdateState::load_delete (this=this@entry=0x7f2cb5489648, del_id=del_id@entry=0, params=...) at be/src/storage/lake/rowset_update_state.cpp:745
#12 0x00000000061dea8c in starrocks::lake::UpdateManager::publish_primary_key_tablet (this=0x7f31ae119180, op_write=..., txn_id=txn_id@entry=6673149, 
    metadata=std::shared_ptr<const starrocks::TabletMetadataPB> (use count 4, weak count 0) = {...}, tablet=0x7f3034ff3390, index_entry=0x7f303a95f380, builder=0x7f3034ff3428, 
    base_version=53610) at be/src/storage/lake/update_manager.cpp:264
#13 0x0000000006223311 in starrocks::lake::PrimaryKeyTxnLogApplier::apply_write_log (this=0x7f3034ff3380, op_write=..., txn_id=6673149)
    at be/src/storage/lake/txn_log_applier.cpp:224
#14 0x0000000006223610 in starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)::{lambda()#1}::operator()() const (__closure=<optimized out>)
    at be/src/storage/lake/txn_log_applier.cpp:119
#15 std::__invoke_impl<starrocks::Status, starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)::{lambda()#1}&>(std::__invoke_other, starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)::{lambda()#1}&) (__f=...) at /opt/rh/gcc-toolset-10/root/usr/include/c++/10.3.0/bits/invoke.h:60
#16 std::__invoke_r<starrocks::Status, starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)::{lambda()#1}&>(starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)::{lambda()#1}&) (__fn=...) at /opt/rh/gcc-toolset-10/root/usr/include/c++/10.3.0/bits/invoke.h:115
#17 std::_Function_handler<starrocks::Status (), starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (
    __functor=...) at /opt/rh/gcc-toolset-10/root/usr/include/c++/10.3.0/bits/std_function.h:292
#18 0x0000000006223655 in std::function<starrocks::Status ()>::operator()() const (this=this@entry=0x7f2e04fe6b80)
    at /opt/rh/gcc-toolset-10/root/usr/include/c++/10.3.0/bits/std_function.h:622
#19 starrocks::lake::PrimaryKeyTxnLogApplier::check_and_recover(std::function<starrocks::Status ()> const&) (this=this@entry=0x7f3034ff3380, publish_func=...)
    at be/src/storage/lake/txn_log_applier.cpp:171
#20 0x0000000006228180 in starrocks::lake::PrimaryKeyTxnLogApplier::apply (this=0x7f3034ff3380, log=...) at be/src/storage/lake/txn_log_applier.cpp:119
#21 0x00000000061cd4d8 in starrocks::lake::publish_version (tablet_mgr=0x7f31bf2a94c0, tablet_id=184529, base_version=base_version@entry=53610, new_version=new_version@entry=53611, 
    txns=std::vector of length 1, capacity 1 = {...}) at be/src/storage/lake/transactions.cpp:298
#22 0x0000000003798f37 in operator() (__closure=<optimized out>) at be/src/service/service_be/lake_service.cpp:209
#23 0x000000000379ab1a in std::function<void ()>::operator()() const (this=0x7f3035009660) at /opt/rh/gcc-toolset-10/root/usr/include/c++/10.3.0/bits/std_function.h:622
#24 starrocks::ConcurrencyLimitedThreadPoolToken::submit_func(std::function<void ()>, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda()#1}::operator()() const (__closure=0x7f3035009650) at be/src/util/threadpool.h:529
``` 

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by kevincai** [comment]
fixed in https://github.com/StarRocks/starrocks/pull/49550
