### ISSUE TITLE
[BUG] LakeCompaction IllegalArgumentException

### ISSUE THREAD

**Issue by kevincai** [StarRocks/starrocks#50284]
### Steps to reproduce the behavior (Required)

```
2024-08-21 10:22:42,115 ERROR (COMPACTION_DISPATCH|263) [Daemon.run():109] daemon thread got exception. name: COMPACTION_DISPATCH
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:899) ~[?:1.8.0_74]
        at java.util.TimSort.mergeAt(TimSort.java:516) ~[?:1.8.0_74]
        at java.util.TimSort.mergeForceCollapse(TimSort.java:457) ~[?:1.8.0_74]
        at java.util.TimSort.sort(TimSort.java:254) ~[?:1.8.0_74]
        at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_74]
        at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_74]
        at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:387) ~[?:1.8.0_74]
        at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_74]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_74]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_74]
        at com.starrocks.lake.compaction.ScoreSorter.sort(ScoreSorter.java:30) ~[starrocks-fe.jar:?]
        at com.starrocks.lake.compaction.CompactionMgr.choosePartitionsToCompact(CompactionMgr.java:125) ~[starrocks-fe.jar:?]
        at com.starrocks.lake.compaction.CompactionMgr.choosePartitionsToCompact(CompactionMgr.java:120) ~[starrocks-fe.jar:?]
        at com.starrocks.lake.compaction.CompactionScheduler.schedule(CompactionScheduler.java:187) ~[starrocks-fe.jar:?]
        at com.starrocks.lake.compaction.CompactionScheduler.runOneCycle(CompactionScheduler.java:105) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:107) ~[starrocks-fe.jar:?]
```

### StarRocks version (Required)

 - v3.2.4

**Comment by starrocks-xupeng** [comment]
https://stackoverflow.com/questions/8327514/comparison-method-violates-its-general-contract
