### ISSUE TITLE
[JsonLogging] FE OutOfMemory with json format log4j configuration for a -Xmx2g configuration

### ISSUE THREAD

**Issue by kevincai** [StarRocks/starrocks#50380]
### Steps to reproduce the behavior (Required)
1. add `sys_log_format = json` in `fe.conf`
2. set `JAVA_OPTS = -Xmx2g`
3. start fe with `./bin/start_fe.sh`

### Expected behavior (Required)

FE process can start with no issue

### Real behavior (Required)

FE java process OOM error

```
2024-08-28 22:28:03,715 main ERROR Could not create plugin of type class org.apache.logging.log4j.layout.template.json.JsonTemplateLayout for element JsonTemplateLayout: java.lang.OutOfMemoryError: Java heap space java.lang.OutOfMemoryError: Java heap space
        at java.base/java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:86)
        at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:116)
        at org.apache.logging.log4j.layout.template.json.util.JsonWriter.<init>(JsonWriter.java:104)
        at org.apache.logging.log4j.layout.template.json.util.JsonWriter.<init>(JsonWriter.java:56)
        at org.apache.logging.log4j.layout.template.json.util.JsonWriter$Builder.build(JsonWriter.java:907)
        at org.apache.logging.log4j.layout.template.json.JsonTemplateLayout.<init>(JsonTemplateLayout.java:106)
        at org.apache.logging.log4j.layout.template.json.JsonTemplateLayout.<init>(JsonTemplateLayout.java:61)
        at org.apache.logging.log4j.layout.template.json.JsonTemplateLayout$Builder.build(JsonTemplateLayout.java:549)
        at org.apache.logging.log4j.layout.template.json.JsonTemplateLayout$Builder.build(JsonTemplateLayout.java:345)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1138)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1063)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1055)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1055)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:664)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:258)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:304)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:285)
        at com.starrocks.common.Log4jConfig.reconfig(Log4jConfig.java:350)
        at com.starrocks.common.Log4jConfig.initLogging(Log4jConfig.java:414)
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:114)
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:83)
```

### StarRocks version (Required)
 - main/3.2.10/3.3.3

Related to #49609

**Comment by kevincai** [comment]
![image](https://github.com/user-attachments/assets/3fa0bbfe-3338-44a2-842b-d9e4e2b5f2be)

![image](https://github.com/user-attachments/assets/b0077512-f5dd-41d0-b274-f69bc691a17c)

![image](https://github.com/user-attachments/assets/89a6c495-0ebc-4790-b642-49b7f37ad5d6)

![image](https://github.com/user-attachments/assets/3458ab6c-fe87-4298-8140-6fc9a220a343)

**Comment by kevincai** [comment]
**ROOT CAUSE ANALYSIS**

* When enabled json format logging, the property `maxStringLength="104857600"` is added to `JsonTemplateLayout` in order to allow output the entire query profile into log file.
* `JsonTemplateLayout` constructs a JsonWriter in the following [code](https://github.com/apache/logging-log4j2/blob/main/log4j-layout-template-json/src/main/java/org/apache/logging/log4j/layout/template/json/JsonTemplateLayout.java#L87C1-L99C6)
```java
    private JsonTemplateLayout(final Builder builder) {
        this.charset = builder.charset;
        this.contentType = "application/json; charset=" + charset;
        final String eventDelimiterSuffix = builder.getNullEventDelimiterEnabled() ? "\0" : "";
        this.eventDelimiter = builder.eventDelimiter + eventDelimiterSuffix;
        final Configuration configuration = builder.configuration;
        final JsonWriter jsonWriter = JsonWriter.newBuilder()
                .setMaxStringLength(builder.maxStringLength)
                .setTruncatedStringSuffix(builder.truncatedStringSuffix)
                .build();
        this.eventResolver = createEventResolver(builder, configuration, charset, jsonWriter);
        this.contextRecycler = createContextRecycler(builder, jsonWriter);
    }
```
* JsonWriter constructs two StringBuilder with the maxStringLength, which is backed by a byte array with the maxStringLength. https://github.com/apache/logging-log4j2/blob/main/log4j-layout-template-json/src/main/java/org/apache/logging/log4j/layout/template/json/util/JsonWriter.java#L103
```java
    private JsonWriter(final Builder builder) {
        this.quoteBuffer = new char[] {'\\', '-', '0', '0', '-', '-'};
        this.stringBuilder = new StringBuilder(builder.maxStringLength);
        this.formattableBuffer = new StringBuilder(builder.maxStringLength);
        this.maxStringLength = builder.maxStringLength;
        this.truncatedStringSuffix = builder.truncatedStringSuffix;
        this.quotedTruncatedStringSuffix = quoteString(builder.truncatedStringSuffix);
    }
```

The above code logic causes the initialization of log4j holds several byte array objects with 100MB size underneath, and causes OOM if the -Xmx is too small.
