### ISSUE TITLE
Be crash

### ISSUE THREAD

**Issue by liuyehcf** [StarRocks/starrocks#5090]
### Steps to reproduce the behavior (Required)

TPCH-1g
Q1

```sql
SELECT l_returnflag, l_linestatus, SUM(l_quantity) AS sum_qty
    , SUM(l_extendedprice) AS sum_base_price
    , SUM(l_extendedprice * (1 - l_discount)) AS sum_disc_price
    , SUM(l_extendedprice * (1 - l_discount) * (1 + l_tax)) AS sum_charge
    , AVG(l_quantity) AS avg_qty, AVG(l_extendedprice) AS avg_price
    , AVG(l_discount) AS avg_disc, COUNT(*) AS count_order
FROM lineitem
WHERE l_shipdate <= DATE '1998-12-01'
GROUP BY l_returnflag, l_linestatus
ORDER BY l_returnflag, l_linestatus;
```

### Expected behavior (Required)

The right result

### Real behavior (Required)

```
#0  0x0000000005540e7b in tcmalloc::SLL_Next (t=0x0) at src/linked_list.h:45
#1  tcmalloc::SLL_PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=32, head=0x9ccf720) at src/linked_list.h:88
#2  tcmalloc::SLL_PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=32, head=0x9ccf720) at src/linked_list.h:79
#3  tcmalloc::ThreadCache::FreeList::PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=32, this=0x9ccf720) at src/thread_cache.h:238
#4  tcmalloc::ThreadCache::ReleaseToCentralCache (this=this@entry=0x9ccf6c0, src=src@entry=0x9ccf720, cl=<optimized out>, N=N@entry=32) at src/thread_cache.cc:206
#5  0x0000000005541205 in tcmalloc::ThreadCache::ListTooLong (this=0x9ccf6c0, list=0x9ccf720, cl=<optimized out>) at src/thread_cache.cc:164
#6  0x00000000040ec1e0 in google::protobuf::DescriptorBuilder::CheckEnumValueUniqueness(google::protobuf::EnumDescriptorProto const&, google::protobuf::EnumDescriptor const*) ()
#7  0x00000000040f4bf9 in google::protobuf::DescriptorBuilder::BuildEnum(google::protobuf::EnumDescriptorProto const&, google::protobuf::Descriptor const*, google::protobuf::EnumDescriptor*) ()
#8  0x00000000040f95de in google::protobuf::DescriptorBuilder::BuildFileImpl(google::protobuf::FileDescriptorProto const&) ()
#9  0x00000000040fa6e4 in google::protobuf::DescriptorBuilder::BuildFile(google::protobuf::FileDescriptorProto const&) ()
#10 0x00000000040fabc1 in google::protobuf::DescriptorPool::BuildFileFromDatabase(google::protobuf::FileDescriptorProto const&) const ()
#11 0x00000000040faca6 in google::protobuf::DescriptorPool::TryFindFileInFallbackDatabase(google::protobuf::StringPiece) const ()
#12 0x00000000040fae42 in google::protobuf::DescriptorPool::FindFileByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
#13 0x000000000415b112 in google::protobuf::(anonymous namespace)::AssignDescriptorsImpl(google::protobuf::internal::DescriptorTable const*, bool) ()
#14 0x00007f1c50fe720b in __pthread_once_slow () from /lib64/libpthread.so.0
#15 0x00000000041519ae in google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*, bool) ()
#16 0x000000000236b0d0 in starrocks::OrdinalIndexPB::GetMetadataStatic () at /home/disk3/hcf/starrocks/gensrc/build/gen_cpp/segment.pb.h:3294
#17 starrocks::OrdinalIndexPB::GetMetadata (this=<optimized out>) at /home/disk3/hcf/starrocks/gensrc/build/gen_cpp/segment.pb.cc:5805
#18 0x0000000004168ead in google::protobuf::Message::SpaceUsedLong() const ()
#19 0x0000000001bc8b61 in starrocks::ColumnReader::_init (this=0xe1abce0, meta=0x12c257a0) at /home/disk3/hcf/starrocks/be/src/storage/rowset/column_reader.cpp:140
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 
```
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 5e3ea2729 |
+-------------------+
```

**Comment by satanson** [comment]
this issue is resulted from QueryContext memtracker problem possibly, it test on tpch_100g and ASAN version; it has not recurred.
