### ISSUE TITLE
FE error: daemon thread got exception. name: config-refresh-daemon

### ISSUE THREAD

**Issue by awk333** [StarRocks/starrocks#51130]
### Expected behavior (Required)
需要确认下报错原因？以及修改方法？

### Real behavior (Required)
fe.log 每 10 秒出现一次报错，报错信息如下：需要确认下报错原因？

2024-09-19 09:09:46.842+08:00 ERROR (config-refresh-daemon|58) [Daemon.run():109] daemon thread got exception. name: config-refresh-daemon
java.lang.IllegalArgumentException: null
        at java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(ThreadPoolExecutor.java:1535) ~[?:?]
        at com.starrocks.common.ThriftServer.lambda$createThreadPoolServer$0(ThriftServer.java:75) ~[starrocks-fe.jar:?]
        at com.starrocks.common.ConfigRefreshDaemon.runAfterCatalogReady(ConfigRefreshDaemon.java:39) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.FrontendDaemon.runOneCycle(FrontendDaemon.java:72) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:107) ~[starrocks-fe.jar:?]

### StarRocks version (Required)
3.2.8-759cc78

**Comment by kevincai** [comment]
```
        GlobalStateMgr.getCurrentState().getConfigRefreshDaemon().registerListener(() -> {
            if (threadPoolExecutor.getMaximumPoolSize() != Config.thrift_server_max_worker_threads) {
                threadPoolExecutor.setCorePoolSize(Config.thrift_server_max_worker_threads);
                threadPoolExecutor.setMaximumPoolSize(Config.thrift_server_max_worker_threads);
            }
        });
```

Due to this code snippet, for now, the `thrift_server_max_worker_threads` can't be changed to a large number runtime. try to set the config in `fe.conf` and restart the frontend process.
