### ISSUE TITLE
FE cannot start normally.

### ISSUE THREAD

**Issue by yanyan84** [StarRocks/starrocks#51245]
### Bug Report

**Title:** StarRocksFE Start Failure Due to PID File Lock

**Version:** 3.1.15

**Environment:**
- **Java Version:** 11
- **Command Line Arguments:**
  ```bash
  -Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseG1GC -Xlog:gc*:/opt/module/starrocks-3.1/log/fe.gc.log.20240921-201416:time
  ```
- **Start Time:** Sat Sep 21 20:14:16 CST 2024
- **Server Uptime:** 20:14:16 up 18 min, 1 user, load average: 0.27, 0.21, 0.16

**Description:**
Upon attempting to start the StarRocksFE service, the process failed with an `IOException` indicating that the PID file is already locked. This issue prevents the service from starting, as it appears that a previous instance of StarRocksFE may still be running or the PID file was not properly cleaned up.

**Error Log:**
```plaintext
20:14:22.787 [main] ERROR com.starrocks.StarRocksFE - StarRocksFE start failed
java.io.IOException: pid file is already locked.
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:105) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]
```

**Steps to Reproduce:**
1. Start the StarRocksFE service using the provided command line arguments.
2. Observe the error in the logs indicating that the PID file is already locked.

**Expected Behavior:**
The StarRocksFE service should start successfully without encountering a PID file lock issue.

**Actual Behavior:**
The service fails to start with an `IOException` due to the PID file being locked.

**Additional Information:**
- The server uptime at the time of the failure was 18 minutes.
- The load average at the time of the failure was 0.27, 0.21, 0.16.

**Suggested Fix:**
- Ensure that the PID file is properly cleaned up when the service is stopped.
- Implement a check to verify if the previous instance of StarRocksFE is still running before attempting to start a new instance.

**Priority:** High

**Severity:** Critical

**Labels:** `bug`, `StarRocksFE`, `pid-lock`, `java11`

**Assignee:** [Assign to appropriate team member]

**Reporter:** [Your Name]

---

Please investigate and resolve this issue as soon as possible to ensure smooth operation of the StarRocksFE service.

**Comment by kevincai** [comment]
use `lsof` to check which process holds the lock of the fe.pid file, and possibly provide the `fe.out`, `fe.log` and relative fe service start/stop operational logs for us to troubleshoot.
