### ISSUE TITLE
存算分离架构下读Hive catalog(基于Juicefs构建)时FE异常退出

### ISSUE THREAD

**Issue by chinaSuperDada** [StarRocks/starrocks#52471]
### 背景描述
hive catalog  使用的是基于juicefs 构建的存储hive-metastore，使用 juceifs-hadoop-1.1.2.jar 访问数据
core中增加jfs 文件系统的实现类
fs.AbstractFileSystem.jfs.impl = io.juicefs.JuiceFS
fs.jfs.impl=io.juicefs.JuiceFileSystem

添加Hive catalog 后
然后执行 select * from hive.dw.table_name limit 10
或者执行
insert into  internal.table  select * from hive.dw.table_name where time='' 

### 异常描述 
FE 在select查询Hive catalog数据正常返回了，但是紧接着crash。在select时该情况非必现
但当进行数据写入时 fe 基本必挂。 

### 异常日志fe.out
`2024/10/11 10:40:27.584862 juicefs[10385] <WARNING>: maxmemory_policy is "volatile-lru",  we will try to reconfigure it to 'noeviction'. [redis.go:3583]
2024/10/11 10:40:27.585424 juicefs[10385] <WARNING>: reconfigured maxmemory-policy to 'noeviction', but it's still volatile-lru [redis.go:3589]
runtime: g 70: unexpected return pc for github.com/juicedata/juicefs/pkg/meta.(*baseMeta).flushDirStat called from 0x0
stack: frame={sp:0xc00086c7a8, fp:0xc00086c7c8} stack=[0xc00086c000,0xc00086c800)
0x000000c00086c6a8:  0x0000000000000000  0x0000000000000000
0x000000c00086c6b8:  0x0000000000000000  0x0000011000000007
0x000000c00086c6c8:  0x000000c000799ba0  0x000000c00086c6e8
0x000000c00086c6d8:  0x00007fcefd0bd606 <github.com/juicedata/juicefs/pkg/meta.(*baseMeta).getFormat.func1+0x0000000000000026>  0x0000000000000050
0x000000c00086c6e8:  0x000000c00086c730  0x00007fcefd0bd53c <github.com/juicedata/juicefs/pkg/meta.(*baseMeta).getFormat+0x000000000000003c>
0x000000c00086c6f8:  0x000000c00017fd20  0x00007fcf5401a668
0x000000c00086c708:  0x0000000000000000  0x0000000000000050
0x000000c00086c718:  0x00007fcefd0bd5e0 <github.com/juicedata/juicefs/pkg/meta.(*baseMeta).getFormat.func1+0x0000000000000000>  0x000000c000079900
0x000000c00086c728:  0x0000000000000000  0x000000c00086c798
0x000000c00086c738:  0x00007fcefd0acf85 <github.com/juicedata/juicefs/pkg/meta.(*baseMeta).doFlushDirStat+0x0000000000000025>  0x00007fcefc107cf6 <runtime.gopark+0x00000000000000d6>
0x000000c00086c748:  0x0000000000000000  0x0000000000000000
0x000000c00086c758:  0x000000c00086c798  0x00007fcefc139577 <time.Sleep+0x0000000000000137>
0x000000c00086c768:  0x00004d7c338ee91e  0x000000c00017fd20
0x000000c00086c778:  0x000000c00007b9ac  0x0000000000000002
0x000000c00086c788:  0x000000c0000ce8c0  0x000000c000799ba0
0x000000c00086c798:  0x000000c00086c7b8  0x00007fcefd0acf45 <github.com/juicedata/juicefs/pkg/meta.(*baseMeta).flushDirStat+0x0000000000000045>
0x000000c00086c7a8: <0x0000000000000000  0x000000003b9aca00
0x000000c00086c7b8:  0x000000c00086c7d0 !0x0000000000000000
0x000000c00086c7c8: >0x0000000000000000  0x0000000000000000
0x000000c00086c7d8:  0x0000000000000000  0x0000000000000000
0x000000c00086c7e8:  0x0000000000000000  0x0000000000000000
0x000000c00086c7f8:  0x0000000000000000
fatal error: unknown caller pc

runtime stack:
runtime.throw({0x7fcefe4beadb?, 0x7fcf00bfb980?})
        /go/src/runtime/panic.go:1047 +0x5f fp=0x7fced25f2ac0 sp=0x7fced25f2a90 pc=0x7fcefc104f7f
runtime.gentraceback(0xc000799ba0?, 0x7fceff5e2f00?, 0x7fcefef6ed80?, 0xc000799ba0, 0x0, 0x0, 0x7fffffff, 0x7fced25f2e68, 0x400000002?, 0x0)
        /go/src/runtime/traceback.go:270 +0x1bb0 fp=0x7fced25f2e18 sp=0x7fced25f2ac0 pc=0x7fcefc12d430
runtime.addOneOpenDeferFrame.func1()
        /go/src/runtime/panic.go:645 +0x6b fp=0x7fced25f2e90 sp=0x7fced25f2e18 pc=0x7fcefc10410b
runtime.systemstack()
        /go/src/runtime/asm_amd64.s:496 +0x46 fp=0x7fced25f2e98 sp=0x7fced25f2e90 pc=0x7fcefc13ac66

goroutine 70 [running]:
runtime.systemstack_switch()
        /go/src/runtime/asm_amd64.s:463 fp=0xc00086c598 sp=0xc00086c590 pc=0x7fcefc13ac00
runtime.addOneOpenDeferFrame(0xc0000ce6e0?, 0x0?, 0x0?)
        /go/src/runtime/panic.go:644 +0x69 fp=0xc00086c5d8 sp=0xc00086c598 pc=0x7fcefc104049
panic({0x7fceff1165c0, 0x7fcf00b99e00})
        /go/src/runtime/panic.go:886 +0x238 fp=0xc00086c698 sp=0xc00086c5d8 pc=0x7fcefc1049b8
runtime.panicmem(...)
        /go/src/runtime/panic.go:260
runtime.sigpanic()
        /go/src/runtime/signal_unix.go:841 +0x37d fp=0xc00086c6f8 sp=0xc00086c698 pc=0x7fcefc11c4dd
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).getFormat(0x7fcefc107cf6?)
        /go/src/github.com/juicedata/juicefs/pkg/meta/base.go:2161 +0x3c fp=0xc00086c740 sp=0xc00086c6f8 pc=0x7fcefd0bd53c
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).doFlushDirStat(0x0)
        /go/src/github.com/juicedata/juicefs/pkg/meta/base.go:384 +0x25 fp=0xc00086c7a8 sp=0xc00086c740 pc=0x7fcefd0acf85`

### StarRocks version (Required)
 - Starrocks 版本为3.3.4
 - hive版本为2.3.9
 - juceifs-hadoop-sdk版本为1.1  
 - hdfs-3.3.2

**Comment by tcodehuber** [comment]
We encounter the same situation, where it restarts approximately every ten minutes or so

**Comment by dontknow9179** [comment]
https://github.com/StarRocks/starrocks/issues/62485
