### ISSUE TITLE
garbled log information

### ISSUE THREAD

**Issue by bulolo** [StarRocks/starrocks#53388]
fe log garbled

```
 2024-11-30 14:25:33.643+08:00 WARN (starrocks-mysql-nio-pool-133|1944) [ConnectProcessor.handleQuery():383] Failed to parse SQL: CREATE TABLE
IF
	NOT EXISTS `product`.`ods_bpm_suppliers` (
		`_id` STRING NOT NULL COMMENT 'ID',
		`created` DATETIME COMMENT 'å  å»ºæ ¶é ´',
		`code` STRING COMMENT 'ä¾ åº å  ç¼ å ·',
		`accGroup` STRING COMMENT 'BPè´¦æ ·ç» ',
		`title` STRING COMMENT 'ç§°è° ',
		`name` STRING COMMENT 'ä¾ åº å  å  ç§°',
		`englishName` STRING COMMENT 'è ±æ  å  ç§°',
		`fullName` STRING COMMENT 'ä¾ åº å  å¨ç§°',
		`slug` STRING COMMENT 'ä¾ åº å  ç® ç§°',
		`supId` STRING COMMENT 'å  æ ¼ä¾ åº å  æ  è¯ ',
		`address` STRING COMMENT 'ä¾ åº å  å¬å ¸æ  å ¨è¡ é  å °å  ',
		`postcode` STRING COMMENT 'ä¾ åº å  é ®æ ¿ç¼ ç  ',
		`city` STRING COMMENT 'ä¾ åº å  å  å¸ ',
		`country` STRING COMMENT 'ä¾ åº å  å ½å®¶',
		`region` STRING COMMENT 'ä¾ åº å  å ºå  ',
		`language` STRING COMMENT 'ä¾ åº å  è¯­è¨ ',
		`email` STRING COMMENT 'ä¾ åº å  é ®ç®±',
		`phone` STRING COMMENT 'ä¾ åº å  æ  æ ºå ·',
		`fax` STRING COMMENT 'ä¼ ç  ',
		`currency` STRING COMMENT 'ç» ç® å¸ å «',
		`pmtTerms` STRING COMMENT 'ä» æ¬¾æ ¡ä»¶ä»£ç  ',
		`note` STRING COMMENT 'å¤ æ³¨',
		`invDup` BOOLEAN COMMENT 'æ ¯å ¦æ£ æ ¥é  å¤ å  ç¥¨',
		`pchGroup` STRING COMMENT 'é  è´­ç» ',
		`supSalesman` STRING COMMENT 'ä¾ åº å  é  å ®äººå  ',
		`pchBlock` BOOLEAN COMMENT 'é  è´­å »ç» ',
		`pmtBlock` BOOLEAN COMMENT 'ä» æ¬¾å »ç» ',
		`sortKey` STRING COMMENT 'æ  åº ç  ',
		`status` BOOLEAN COMMENT 'æ ¯å ¦å¼ ç ¨',
		`updated` DATETIME COMMENT 'æ ´æ °æ ¶é ´',
		`isOverseas` BOOLEAN COMMENT 'æ ¯å ¦æµ·å¤ ',
		`purchasePeriod` STRING COMMENT 'é  è´­å ¨æ  ï¼ æ ªå  æ ¶é ´ï¼ ',
		`authedCompanies` ARRAY < STRING > COMMENT 'æ  æ  ç» ç» ',
		`sapSyncAt` DATETIME COMMENT 'æ  å  ä¸ æ¬¡å  æ­¥å °sapç  æ ¶é ´ç ¹',
		`sapSyncStatus` STRING COMMENT 'SAPä»»å ¡ç ¶æ  ',
		`logs` JSON COMMENT 'æ ¥å¿ ' 
		) ENGINE = OLAP
		PRIMARY KEY ( _id, created ) 
		COMMENT "ods-bpmä¾ åº å  è¡¨"
		PARTITION BY date_trunc ( 'day', created ) 
		DISTRIBUTED BY HASH ( _id )
		ORDER BY( created ) 
		PROPERTIES ( ), because.
 com.starrocks.common.AnalysisException: Getting syntax error at line 46, column 15. Detail message: Unexpected input ')', the most similar input is {SINGLE_QUOTED_TEXT, DOUBLE_QUOTED_TEXT}.
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:320)
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:565)
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:903)
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by kevincai** [comment]
set your system locale to UTF-8 encoding.

**Comment by bulolo** [comment]
> set your system locale to UTF-8 encoding.

how to set？

On k8s env？

**Comment by kevincai** [comment]
for k8s env, inject env `LANG=en_US.UTF-8` into the pod, either through helm values or CRD

**Comment by bulolo** [comment]
> for k8s env, inject env `LANG=en_US.UTF-8` into the pod, either through helm values or CRD

thanks.it work

**Comment by bulolo** [comment]
> for k8s env, inject env `LANG=en_US.UTF-8` into the pod, either through helm values or CRD

```
root@starrockscluster-fe-2:/opt/starrocks# locale
LANG=en_US.utf8
LANGUAGE=
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

stil exist
```
COMMENT "dws-wmsæ ¶è´§å  æ  ç» å®½è¡¨"
```

**Comment by kevincai** [comment]
where is the `select` output ? fe.log?

**Comment by bulolo** [comment]
> where is the `select` output ? fe.log?

yes,this is fe log

**Comment by bulolo** [comment]
> where is the `select` output ? fe.log?

i show it on fe_ip:8030/log
is from /opt/starrocks/fe/log/fe.warn.log

**Comment by bulolo** [comment]
@kevincai is there any idea

**Comment by kevincai** [comment]
no idea, can you use `hexdump` to confirm that the chars are indeed UTF-8 encoded, it is just a display issue?

**Comment by kevincai** [comment]
also there is a little difference of the locale output

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

try to set both LC_ALL and LANG to your `en_US.utf8` , if that works?

**Comment by bulolo** [comment]
i open fe.warn.log ,the log is utf8 and show right chinese word,and on the web ,show the wrong way.
so is because of the web
