### ISSUE TITLE
SMT can't load database correctly from the database when using type = pgsql

### ISSUE THREAD

**Issue by zlly20** [StarRocks/starrocks#53440]
We are trying to use SMT tool to migrate some data from postgresql to starrocks using SMT tool. but after putting in the right configuration. SMT tool failed to run due to the following error:

```
[osssupport@gsbprdappl18: ~/postgres_to_starrocks/starrocks_mig_tools/smt]$ ./starrocks-migrate-tool -alsologtostderr
I1203 09:13:40.582884 1279077 config.go:172] loading configurations: [&{172.24.1.240 5432 db5uperuser dbP@55w0rd 2 0 false 3 3 [0xc0001c2420] ./result /home/loggedinuser/postgres_to_starrocks/starrocks_mig_tools/smt/conf/config_prod.conf}]

2024/12/03 09:13:40 source/pgsql.go:92
[error] failed to initialize database, got error failed to connect to `host=172.24.1.240 user=db5uperuser database=`: server error (FATAL: database "db5uperuser " does not exist (SQLSTATE 3D000))
panic: failed to connect to `host=172.24.1.240 user=db5uperuser database=`: server error (FATAL: database "db5uperuser " does not exist (SQLSTATE 3D000))

goroutine 1 [running]:
main.main()
        main.go:34 +0x92f
```
It looks like it takes the username as the default database and even though the database has been configured under the table-rule.1 section.

### Steps to reproduce the behaviour (Required)
the configuration file looks like the following, we have followed the document from https://docs.starrocks.io/docs/3.2/integrations/loading_tools/SMT/:

```
[db]
host = 172.24.1.240
port = 5432
user = db5uperuser 
password = dbP@55w0rd
type = pgsql

[other]
be_num = 3
use_decimal_v3 = false
output_dir = ./result

[table-rule.1]
database = ^mydb$
table = ^table$
schema = ^.*$

flink.starrocks.jdbc-url=jdbc:mysql://192.168.1.1:9030
flink.starrocks.load-url= 192.168.1.1:8030
flink.starrocks.username=root
flink.starrocks.password=
flink.starrocks.sink.max-retries=10
flink.starrocks.sink.buffer-flush.interval-ms=15000
flink.starrocks.sink.properties.format=json
flink.starrocks.sink.properties.strip_outer_array=true
```

### Expected behaviour (Required)
SMT tool at least can connect to the source database. 

### Real behaviour (Required)
SMT doesn't seem to load the correct database name configured in the configuration file and use username as default database name, then it error out that because that database doesn't exist. 

### StarRocks version (Required)
the SMT tool is downloaded via https://www.starrocks.io/download/community

Please advise how do we work around this issue, thanks.

**Comment by hffariel** [comment]
Are you able to remove the `@` from your password and give it another try?

**Comment by zlly20** [comment]
the password shown here is not the real password used, the real password has no @ in the password, it has a # and a dollar sign, but i have tried to change to another fake password, even though it can't connect, but in the logs, it still shows database=, it seems it didn't even pick up the db from the configuration file, however, just a guess.

**Comment by vislesh** [comment]
facing exactly same issue.
