### ISSUE TITLE
Error while reading Iceberg table having parquet files with dynamic column sequencing

### ISSUE THREAD

**Issue by amanjaiswalofficial** [StarRocks/starrocks#53494]
### Steps to reproduce the behavior (Required)
Create an iceberg table for a list of parquet files, where there might be a difference in the sequence of columns between 2 parquet files.
For example:
If I create 2 files (.parquet) having column information:
**File 1**:
col1 INT | col2 STRING | col3 INT
**File 2**:
col2 STRING | col1 INT | col3 INT
If I create an iceberg table with the schema of **File 2**, i.e.
CREATE TABLE ice_table (col2 STRING, col1 INT, col3 INT) USING ICEBERG LOCATION "s3://<>"
It fails for the following query, Ex -
select count(*) from ice_table
Failed to decode parquet page header, page header's size is out of range
Both the queries work on every other engine we've worked with, ex - Athena, DuckDB and even Spark. We're trying to get this done on starrocks as it will open a lot of doors for us in terms of efficiency and cost.
I can provide screenshots on top of this if needed for more insights
### Expected behavior (Required)
Starrocks, like other engine for querying data should be able to read the data together and sequence the data in the final result.
Tools like duckDB and others are able to query this data.

### Real behavior (Required)
While running the query on such a table, throws error:
Corruption: Failed to decode parquet page header, page header's size is out of range.  allowed_page_size=0, max_page_size=16777216, offset=115, finish_offset=115
Though if I read a single file at a time by passing the S3 path for it, it works without any issue.
In one of the cases that we've tried this with, shouldn't even consider the max_page_size as the files in question are hardly in KBs. In those cases, I have no issues when I read with a file which has the correct order of columns, whereas the second I query a different partition or a different file, I see the issue mentioned above.
Additionally, if I do a
SELECT * from FILES (path: "s3://<>/file1.pq") and
SELECT * from FILES (path: "s3://<>/file2.pq")
Both of these work
This is a crucial feature for us to have, as it breaks the maintainability of the tables that we have.
Humble request to either take a look at this and provide a fix or guide us with the necessary files or functions that might end up causing this and I'll try to work on the fix myself.

### StarRocks version (Required)
3.3.3

**Comment by zombee0** [comment]
Hi @amanjaiswalofficial, could you run `parquet meta file1` and `parquet meta file2` and i want to get the info of schema while like 
`Schema:
message table {
  required int32 k1 (INTEGER(32,true)) = 1;
  required binary k2 (STRING) = 2;
}`

**Comment by amanjaiswalofficial** [comment]
Sure,
Sharing for file1 and file2 here
## file1 (working)

```
File path:  1_working.parquet
Created by: parquet-mr version 1.13.1 (build ${buildNumber})
Properties:
                   org.apache.spark.version: 3.5.0
    org.apache.spark.sql.parquet.row.metadata: {"type":"struct","fields":[{"name":"_dw_level_0_id","type":"long","nullable":true,"metadata":{}},{"name":"_dw_source_key_id","type":"long","nullable":true,"metadata":{}},{"name":"question","type":"string","nullable":true,"metadata":{}},{"name":"value","type":"long","nullable":true,"metadata":{}},{"name":"_dw_extracted_at","type":"string","nullable":true,"metadata":{}},{"name":"_metadata_file_path","type":"string","nullable":true,"metadata":{}},{"name":"_metadata_file_modification_time","type":"timestamp","nullable":true,"metadata":{}}]}
Schema:
message spark_schema {
  optional int64 _dw_level_0_id;
  optional int64 _dw_source_key_id;
  optional binary question (STRING);
  optional int64 value;
  optional binary _dw_extracted_at (STRING);
  optional binary _metadata_file_path (STRING);
  optional int96 _metadata_file_modification_time;
}


Row group 0:  count: 4  107.25 B records  start: 4  total(compressed): 429 B total(uncompressed):345 B 
--------------------------------------------------------------------------------
                                  type      encodings count     avg size   nulls   min / max
_dw_level_0_id                    INT64     Z _ R     4         18.75 B    0       "0" / "0"
_dw_source_key_id                 INT64     Z   _     4         16.00 B    0       "89000160022" / "89000160034"
question                          BINARY    Z   _     4         9.50 B     4       
value                             INT64     Z _ R     4         21.25 B    0       "-103" / "103"
_dw_extracted_at                  BINARY    Z _ R     4         22.75 B    0       "2024-12-02 10:30:57" / "2024-12-02 10:30:57"
_metadata_file_path               BINARY    Z   _     4         9.50 B     4       
_metadata_file_modification_time  INT96     Z   _     4         9.50 B     4    
```   

## file2 (not working)

File path:  2_not_working_file.parquet
```
Created by: parquet-mr version 1.13.1 (build ${buildNumber})
Properties:
  writer.model.name: example
Schema:
message merged_schema {
  optional binary question (STRING);
  optional int64 _dw_level_0_id;
  optional int64 _dw_source_key_id;
  optional int64 value;
  optional binary _dw_extracted_at (STRING);
}


Row group 0:  count: 2  141.50 B records  start: 4  total(compressed): 283 B total(uncompressed):229 B 
--------------------------------------------------------------------------------
                   type      encodings count     avg size   nulls   min / max
question           BINARY    Z   D     2         21.00 B    2       
_dw_level_0_id     INT64     Z _ R     2         34.50 B    0       "0" / "0"
_dw_source_key_id  INT64     Z   D     2         23.50 B    0       "89000012498" / "89000012562"
value              INT64     Z   D     2         22.00 B    0       "-103" / "100"
_dw_extracted_at   BINARY    Z   D     2         40.50 B    0       "2023-05-24 20:00:20" / "2023-05-25 16:00:07"
```

**Comment by zombee0** [comment]
@amanjaiswalofficial from the schema information, i think this issue is not about schema.
And for this error message `page header's size is out of range`, could you send us the completed error message, and could you send us the file that we can reproduce the issue and fix it?

**Comment by amanjaiswalofficial** [comment]
Hey @zombee0 
The complete error message, along with steps to re-create it:
```
CREATE TABLE starrocks_bug_1 (survey_id BIGINT) USING ICEBERG LOCATION 's3a://.../adhoc/starrocks_bug_1';
CALL system.add_files('starrocks_bug_1', '`parquet`.`s3a://.../bug.zstd.parquet`');
SELECT * from starrocks_bug_1;

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1064] [42000]: FileReader::get_next failed. reason = Corruption: Failed to decode parquet page header, page header's size is out of range.  allowed_page_size=0, max_page_size=16777216, offset=557, finish_offset=557
be/src/formats/parquet/column_chunk_reader.cpp:104 _page_reader->next_header()
be/src/formats/parquet/column_chunk_reader.cpp:63 _parse_page_header()
be/src/formats/parquet/stored_column_reader.cpp:468 _reader->load_header()
be/src/formats/parquet/stored_column_reader.cpp:331 _next_page()
be/src/formats/parquet/group_reader.cpp:172 _column_readers[slot_id]->read_range(range, filter, (*chunk)->get_column_by_slot_id(slot_id).get())
be/src/formats/parquet/group_reader.cpp:129 _read_range(_active_column_indices, r, nullptr, &active_chunk), file = s3a://prod-data-processed/emr_lake/delta_lake/freshdesk__seller_care/satisfaction_ratings/sys_partition_year=2023/part-43977-276d9b12-ead1-4592-862a-e01d8330c113.c000.zstd.parquet
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:615)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:506)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:525)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:977)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4176)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5154)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLSyntaxErrorException: FileReader::get_next failed. reason = Corruption: Failed to decode parquet page header, page header's size is out of range.  allowed_page_size=0, max_page_size=16777216, offset=557, finish_offset=557
be/src/formats/parquet/column_chunk_reader.cpp:104 _page_reader->next_header()
be/src/formats/parquet/column_chunk_reader.cpp:63 _parse_page_header()
be/src/formats/parquet/stored_column_reader.cpp:468 _reader->load_header()
be/src/formats/parquet/stored_column_reader.cpp:331 _next_page()
be/src/formats/parquet/group_reader.cpp:172 _column_readers[slot_id]->read_range(range, filter, (*chunk)->get_column_by_slot_id(slot_id).get())
be/src/formats/parquet/group_reader.cpp:129 _read_range(_active_column_indices, r, nullptr, &active_chunk), file = s3a://prod-data-processed/emr_lake/delta_lake/freshdesk__seller_care/satisfaction_ratings/sys_partition_year=2023/part-43977-276d9b12-ead1-4592-862a-e01d8330c113.c000.zstd.parquet
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:767)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:652)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```

**Comment by zombee0** [comment]
Hi @amanjaiswalofficial, I reproduced the issue, and find that the root cause is that we haven't support DATA_PAGE_V2 in parquet. As i know common writer like parquet-mr and arrow both use DATA_PAGE_V1 as default, would you like to change your writer's configuration to generate DATA_PAGE_V1?

**Comment by zombee0** [comment]
@amanjaiswalofficial good, hope that works.
we have a schedule to support DATA_PAGE_V2, but it should be in next two months.

**Comment by asunyu1a** [comment]
@zombee0 
Is it supported in version 3.3.8 on 2025/01/03? If not, when will it be.

**Comment by zombee0** [comment]
@COLDMANYU 
Not yet, we'll finish developing in 2025/02, for which version to release need to be evaluated.

**Comment by cresny** [comment]
@zombee0 has there been any movement on support for DATA_PAGE_V2? This is an important issue for us because without that support we cannot read from Snowflake managed Iceberg via Polaris. Snowflake + Polaris -> Starrocks should be a huge market but lack of support for DATA_PAGE_V2 kills it. Snowflake does have a COMPATIBILITY mode but sadly this only forces PLAIN encoding and does not change page type. 

On another note, Snowflake and many others use Arrow library to write parquet. Has there been any thought to supporting Arrrow as an alternative parquet reader? That could be a configurable option, perhaps through table property, and could live along Starroks bespoke parquet implementation.

**Comment by dirtysalt** [comment]
@cresny @amanjaiswalofficial @COLDMANYU I'll looking into this feature in the next bi-month.  But I'm not sure when I can deliver this feature, I'll do my best.

And about arrow library.  We do use arrow to write data files, but we don't use arrow to read files just because of history.  We have done many co-deisgn(with our execution engine) optimizations on reading parquet files(like dict filter, runtime filter etc).  So in near future(or maybe long future), I don't see any chance that we will use arrow to read files, although I kind of wish to.

**Comment by cresny** [comment]
@dirtysalt Thanks for the update and insights. I do hope you will find time to get it done. 

About Arrow, I was thinking it could be treated as more of a compatibility option, where it might be made clear that performance gains would be sacrificed. For most users that would be a better option than nothing at all. Beyond page type, there's also apparently an issue with Delta encoding https://github.com/StarRocks/starrocks/issues/37169 . Snowflake uses that by default and I _think_ Databricks does. Basically all the C++ data stores are going to use Arrow with performance, not compatibility, in mind. This is going to leave a lot of users, especially at big companies, out in the cold with Starrocks.

**Comment by dirtysalt** [comment]
@cresny appreciate that.  I admit that we have to rapdily evolve with open source community.

**Comment by dirtysalt** [comment]
demo to create a data page v2 file

```py
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

schema = pa.schema([
    ('id', pa.int32()),
    ('name', pa.string())
])
writer = pa.parquet.ParquetWriter('output_v2.parquet', schema, data_page_version='2.0')
data = {
    "id": np.array([1, 2, 3, 4], dtype=np.int32),
    "name": ["a", "b", "c", "d"]
}
table = pa.Table.from_pydict(data)
writer.write_table(table)
writer.close()
```

**Comment by dirtysalt** [comment]
https://github.com/StarRocks/starrocks/pull/57621

**Comment by dirtysalt** [comment]
Related PRs:

- [[Enhancement] add more capabilities to bit stream util by dirtysalt · Pull Request #57757 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/57757)
- [[Enhancement] Support parquet DELTA BINARY PACKED encoding by dirtysalt · Pull Request #57828 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/57828)
- [[Enhancement] support parquet DELTA_LENGTH_BYTE_ARRAY encoding by dirtysalt · Pull Request #57954 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/57954)
- [[Enhancement] support parquet DELTA BINARY ARRAY encoding by dirtysalt · Pull Request #57958 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/57958)
- [[Enhancement] add xsmid thirdparty header files by dirtysalt · Pull Request #57964 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/57964)
- [[Enhancement] support parquet BYTE_STREAM_SPLIT encoding by dirtysalt · Pull Request #58034 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/58034)

**Comment by dirtysalt** [comment]
data page v2 features are all available on main branch right now. Since branch-3.5 is out there, so those features shoule be available on 3.6.

Those features are not battle tested yet, and I don't do benchmark. Will do those thing in the next few weeks.
