### ISSUE TITLE
SMT can't load database correctly from the database when using type = clickhouse

### ISSUE THREAD

**Issue by kynasln** [StarRocks/starrocks#53702]
### Steps to reproduce the behavior (Required)
1.download the smt.tar.gz file in doc version 3.3
2. vim the conf
3. run starrocks-migrate-tool command
![image](https://github.com/user-attachments/assets/1851c851-305c-4eed-9981-4d1ae6abc183)
![image](https://github.com/user-attachments/assets/43194b4a-dea3-4fe4-87d8-e3507a2d8ce7)

### Expected behavior (Required)
generate sql files in dir result

### Real behavior (Required)
error
2024/12/08 16:57:30 source/clickhouse.go:72
[error] failed to initialize database, got error driver: bad connection
panic: driver: bad connection

goroutine 1 [running]:
main.main()
        main.go:34 +0x965
![image](https://github.com/user-attachments/assets/ef2f1206-c616-4cf4-9c9d-7a030a8c6528)
![image](https://github.com/user-attachments/assets/88a50d1b-e692-4b4c-ba7e-02dab97d9308)

### StarRocks version (Required)
 - 3.3.7 The SMT tool should be unrelated to the StarRocks version.

**Comment by tuchuntong** [comment]
I encountered the same issue, and my ClickHouse version is ClickHouse client version 21.7.5.29 (official build).
![图片](https://github.com/user-attachments/assets/3e334f54-9211-4bb5-9bc3-24cac331b337)
