### ISSUE TITLE
存算分离模式下 执行 insert into 表1 (select * from 表2) 导致 CN 节点 down 掉

### ISSUE THREAD

**Issue by liyanwei89** [StarRocks/starrocks#53966]
### Steps to reproduce the behavior (Required)
1. insert into primary_key_test_t_2 (select * from primary_key_test_t_4);
data size：
primary_key_test_t_4        | 39.445 GB      | 13 

CN：
        LastStartTime: 2024-12-16 11:23:14
        LastHeartbeat: 2024-12-16 11:44:42
                Alive: false
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: java.net.ConnectException: Connection refused (Connection refused)
              Version: 3.3.5-6d81f75
             CpuCores: 8
             MemLimit: 25.312GB
    NumRunningQueries: 1
           MemUsedPct: 44.76 %
           CpuUsedPct: 52.7 %
     DataCacheMetrics: Status: Normal, DiskUsage: 0B/270GB, MemUsage: 0B/0B
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 1
        WarehouseName: default_warehouse
            TabletNum: 111

### Expected behavior (Required)
Successfully executed, data imported into primary_key_test_t_2 

### Real behavior (Required)
mysql client：
MySQL [jdcloud]> insert into primary_key_test_t_2 (select * from primary_key_test_t_4);
ERROR 5025 (HY000): [E1014]Got EOF of Socket{id=204 fd=623 addr=6.254.68.37:8060:33990} (0x0x14645578ca80) [R1][E112]Not connected to 6.254.68.37:8060 yet, server_id=204 [R2][E112]Not connected to 6.254.68.37:8060 yet, server_id=204 [R3][E112]Not connected to 6.254.68.37:8060 yet, server_id=204:  be:6.254.68.37: BE:10003

 cn.out :
hdfsOpenFile(/starrocks/bb38b0b2-fd18-49c2-a81d-a91776fd5a50/db10093/10650/11341/meta/0000000000002C4E_0000000000000005.meta): FileSystem#open((Lorg/apache/hadoop/fs/Path;I)Lorg/apache/hadoop/fs/FSDataInputStream;) error:
FileNotFoundException: /starrocks/bb38b0b2-fd18-49c2-a81d-a91776fd5a50/db10093/10650/11341/meta/0000000000002C4E_0000000000000005.meta: not foundjava.io.FileNotFoundException: /starrocks/bb38b0b2-fd18-49c2-a81d-a91776fd5a50/db10093/10650/11341/meta/0000000000002C4E_0000000000000005.meta: not found
        at jd.jdufs.JduHadoopFileSystem.failedException(JduHadoopFileSystem.java:78)
        at jd.jdufs.JduHadoopFileSystem.open(JduHadoopFileSystem.java:350)
        at org.apache.hadoop.fs.FilterFileSystem.open(FilterFileSystem.java:168)
3.3.5 RELEASE (build 6d81f75)
query_id:00000000-0000-0000-0000-000000000000, fragment_instance:00000000-0000-0000-0000-000000000000
tracker:process consumption: 12097584636
tracker:jemalloc_metadata consumption: 164375312
tracker:jemalloc_fragmentation consumption: 174893860
tracker:query_pool consumption: 140520
tracker:query_pool/connector_scan consumption: 0
tracker:load consumption: 0
tracker:metadata consumption: 36041808
tracker:tablet_metadata consumption: 8769
tracker:rowset_metadata consumption: 0
tracker:segment_metadata consumption: 493127
tracker:column_metadata consumption: 35539912
tracker:tablet_schema consumption: 8769
tracker:segment_zonemap consumption: 185611
tracker:short_key_index consumption: 1210
tracker:column_zonemap_index consumption: 208496
tracker:ordinal_index consumption: 32969096
tracker:bitmap_index consumption: 0
tracker:bloom_filter_index consumption: 0
tracker:compaction consumption: 5850242320
tracker:schema_change consumption: 0
tracker:column_pool consumption: 0
tracker:page_cache consumption: 5449159296
tracker:jit_cache consumption: 1720
tracker:update consumption: 0
tracker:chunk_allocator consumption: 0
tracker:clone consumption: 0
tracker:consistency consumption: 0
tracker:datacache consumption: 21620185
tracker:replication consumption: 0
*** Aborted at 1734320685 (unix time) try "date -d @1734320685" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 398898 (TID 0x1485b2624700) from PID 0; stack trace: ***
    @     0x1485ee831e67 __pthread_once_slow
    @          0x7aff560 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x1485ef65eaaa os::Linux::chained_handler(int, siginfo*, void*)
    @     0x1485ef6640ae JVM_handle_linux_signal
    @     0x1485ef657fb8 signalHandler(int, siginfo*, void*)
    @     0x1485ee834dd0 (/usr/lib64/libpthread-2.28.so+0x12dcf)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `
 3.3.5-6d81f75

**Comment by liyanwei89** [comment]
(gdb) bt
#0  0x000000000738e622 in newJavaStr ()
#1  0x000000000738fcc6 in constructNewObjectOfPath ()
#2  0x0000000007397461 in hdfsListDirectory ()
#3  0x00000000071d84f4 in staros::starlet::fslib::HdfsFileSystem::list_dir_internal(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, std::function<bool (staros::starlet::fslib::EntryStat)>) ()
#4  0x00000000071d9ab6 in staros::starlet::fslib::HdfsFileSystem::list_dir(std::basic_string_view<char, std::char_traits<char> >, bool, std::function<bool (staros::starlet::fslib::EntryStat)>) ()
#5  0x00000000071bb57f in staros::starlet::fslib::CacheFileSystemImpl::list_dir(std::basic_string_view<char, std::char_traits<char> >, bool, std::function<bool (staros::starlet::fslib::EntryStat)>) ()
#6  0x00000000071b9b65 in staros::starlet::fslib::CacheFileSystem::list_dir(std::basic_string_view<char, std::char_traits<char> >, bool, std::function<bool (staros::starlet::fslib::EntryStat)>) ()
#7  0x0000000005eaf41d in starrocks::StarletFileSystem::iterate_dir(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<bool (std::basic_string_view<char, std::char_traits<char> >)> const&) ()
#8  0x000000000627c70c in starrocks::lake::TabletManager::list_tablet_metadata(long) ()
#9  0x0000000006280298 in starrocks::lake::TabletManager::get_tablet_data_size(long, long*) ()
#10 0x0000000006281d96 in starrocks::lake::TabletManager::add_in_writing_data_size(long, long) ()
#11 0x0000000006236b8a in starrocks::lake::DeltaWriterImpl::check_immutable() ()
#12 0x0000000006236e05 in starrocks::lake::DeltaWriter::check_immutable() ()
#13 0x0000000006225e28 in starrocks::lake::AsyncDeltaWriter::check_immutable() ()
#14 0x00000000037885ce in starrocks::LakeTabletsChannel::open(starrocks::PTabletWriterOpenRequest const&, starrocks::PTabletWriterOpenResult*, std::shared_ptr<starrocks::OlapTableSchemaParam>, bool) ()
#15 0x0000000003721a77 in starrocks::LoadChannel::open(brpc::Controller*, starrocks::PTabletWriterOpenRequest const&, starrocks::PTabletWriterOpenResult*, google::protobuf::Closure*) ()
#16 0x000000000371b6a8 in starrocks::LoadChannelMgr::open(brpc::Controller*, starrocks::PTabletWriterOpenRequest const&, starrocks::PTabletWriterOpenResult*, google::protobuf::Closure*) ()
#17 0x0000000007d8bf24 in brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) ()
#18 0x0000000007cb82c7 in brpc::ProcessInputMessage(void*) ()
#19 0x0000000007cb9645 in brpc::InputMessenger::OnNewMessages(brpc::Socket*) ()
#20 0x0000000007ca793e in brpc::Socket::ProcessEvent(void*) ()
#21 0x0000000007c789c2 in bthread::TaskGroup::task_runner(long) ()
#22 0x0000000007dcde51 in bthread_make_fcontext ()
#23 0x0000000000000000 in ?? ()
(gdb) list
1       /export/code2/ljd/testrepo/src/jd.com/kun-lun-project/kunlun-ufs/sdk/libjd_ufs/bitmap.cpp: No such file or directory.
(gdb)

**Comment by tracymacding** [comment]
It seems to be related with kunlun-ufs, you'd better check it

**Comment by tracymacding** [comment]
It seems duplicate with https://github.com/StarRocks/starrocks/issues/54493
