### ISSUE TITLE
after drop db _statistics_ ,some tables cannot be automatically rebuilt

### ISSUE THREAD

**Issue by tan90zz** [StarRocks/starrocks#54384]
### Steps to reproduce the behavior (Required)
1. drop database `_statistics_` force;
2. check fe log...
Error content：
```
 ERROR (Load history syncer|55) [RepoExecutor.executeDML():76] RepoExecutor execute SQL INSERT INTO _statistics_.loads_history SELECT * FROM information_schema.loads WHERE load_finish_time IS NOT NULL AND load_finish_time < NOW() - INTERVAL 1 MINUTE AND load_finish_time > ( SELECT COALESCE(MAX(load_finish_time), '0001-01-01 00:00:00') FROM _statistics_.loads_history); failed: Getting analyzing error. Detail message: Table loads_history is not found.
com.starrocks.sql.analyzer.SemanticException: Getting analyzing error. Detail message: Table loads_history is not found.
        at com.starrocks.sql.common.MetaUtils.getSessionAwareTable(MetaUtils.java:177) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.beginTransaction(StatementPlanner.java:442) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:101) ~[starrocks-fe.jar:?]
        at com.starrocks.load.pipe.filelist.RepoExecutor.executeDML(RepoExecutor.java:68) ~[starrocks-fe.jar:?]
        at com.starrocks.load.loadv2.LoadsHistorySyncer.syncData(LoadsHistorySyncer.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.load.loadv2.LoadsHistorySyncer.runAfterCatalogReady(LoadsHistorySyncer.java:113) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.FrontendDaemon.runOneCycle(FrontendDaemon.java:72) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:107) ~[starrocks-fe.jar:?]

```

### Expected behavior (Required)
statistics.loads_history can be automatically rebuilt

### Real behavior (Required)
statistics.loads_history cannot be automatically rebuilt

### StarRocks version (Required)
 - 3.3.6-8f01cfa

**Comment by tracymacding** [comment]
Other tables under statistic are rebuilt automatically?

**Comment by meegoo** [comment]
https://github.com/StarRocks/starrocks/pull/54036

**Comment by tan90zz** [comment]
> Other tables under statistic are rebuilt automatically?

yes
