### ISSUE TITLE
FE Restart Failed with exception: com.sleepycat.je.rep.InsufficientLogException

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#5642]
### Steps to reproduce the behavior (Required)
Not easy to reproduce this bug.

### Expected behavior (Required)
restart successfully.

### Real behavior (Required)
restart failed.
```java
2022-04-28 16:38:15,491 ERROR (UNKNOWN 172.26.92.139_29917_1650957989140(-1)|1) [StarRocksFE.start():130] StarRocksFE start failed
com.sleepycat.je.rep.InsufficientLogException: (JE 7.3.8) Environment must be closed, caused by: com.sleepycat.je.rep.InsufficientLogException: Environment invalid because of previous exception: (JE 7.3.8) 172.26.92.139_29917_1650957989140(2407):/home/disk4/gengjun/fe/doris-meta/bdb INSUFFICIENT_LOG: Log files at this node are obsolete. Environment is invalid and must be closed.refreshVLSN=null logProviders=null repImpl=null props=null
        at com.sleepycat.je.rep.InsufficientLogException.wrapSelf(InsufficientLogException.java:315) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1766) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.log.LogManager.getLogEntry(LogManager.java:830) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.log.LogManager.getLogEntry(LogManager.java:784) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.log.LogManager.getLogEntryHandleFileNotFound(LogManager.java:935) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.DiskOrderedScanner.fetchEntry(DiskOrderedScanner.java:2062) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.DiskOrderedScanner.fetchAndProcessBINs(DiskOrderedScanner.java:1634) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.DiskOrderedScanner.scanSerial(DiskOrderedScanner.java:783) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.DiskOrderedScanner.scan(DiskOrderedScanner.java:703) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.DatabaseImpl.count(DatabaseImpl.java:2266) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.Database.count(Database.java:1910) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.getMaxJournalId(BDBJEJournal.java:223) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:299) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.open(EditLog.java:829) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.initialize(Catalog.java:884) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:107) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:62) [starrocks-fe.jar:?]
Caused by: com.sleepycat.je.rep.InsufficientLogException: Environment invalid because of previous exception: (JE 7.3.8) 172.26.92.139_29917_1650957989140(2407):/home/disk4/gengjun/fe/doris-meta/bdb INSUFFICIENT_LOG: Log files at this node are obsolete. Environment is invalid and must be closed. Originally thrown by HA thread: REPLICA 172.26.92.139_29917_1650957989140(2407)
        at com.sleepycat.je.rep.stream.ReplicaFeederSyncup.setupLogRefresh(ReplicaFeederSyncup.java:664) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.rep.stream.ReplicaFeederSyncup.getFeederRecord(ReplicaFeederSyncup.java:732) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.rep.stream.ReplicaFeederSyncup.findMatchpoint(ReplicaFeederSyncup.java:416) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.rep.stream.ReplicaFeederSyncup.execute(ReplicaFeederSyncup.java:151) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.rep.impl.node.Replica.initReplicaLoop(Replica.java:711) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.rep.impl.node.Replica.runReplicaLoopInternal(Replica.java:474) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.rep.impl.node.Replica.runReplicaLoop(Replica.java:409) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.rep.impl.node.RepNode.run(RepNode.java:1873) ~[starrocks-bdb-je-7.3.8.jar:?]
```

### StarRocks version (Required)
- all

**Comment by gengjun-git** [comment]
should reinit the bdb environment.

**Comment by gengjun-git** [comment]
sometimes it will throw npe:
```java
2022-05-05 16:21:36,733 ERROR (UNKNOWN 172.26.92.139_29917_1650957989140(-1)|1) [StarRocksFE.start():130] StarRocksFE start failed
java.lang.NullPointerException: null
        at com.sleepycat.je.rep.InsufficientLogException.initRepImpl(InsufficientLogException.java:244) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.rep.InsufficientLogException.getRepImpl(InsufficientLogException.java:348) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.rep.InsufficientLogException.<init>(InsufficientLogException.java:303) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.rep.InsufficientLogException.wrapSelf(InsufficientLogException.java:315) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1766) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.log.LogManager.getLogEntry(LogManager.java:830) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.log.LogManager.getLogEntry(LogManager.java:784) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.log.LogManager.getLogEntryHandleFileNotFound(LogManager.java:935) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.DiskOrderedScanner.fetchEntry(DiskOrderedScanner.java:2062) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.DiskOrderedScanner.fetchAndProcessBINs(DiskOrderedScanner.java:1634) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.DiskOrderedScanner.scanSerial(DiskOrderedScanner.java:783) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.DiskOrderedScanner.scan(DiskOrderedScanner.java:703) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.dbi.DatabaseImpl.count(DatabaseImpl.java:2266) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.sleepycat.je.Database.count(Database.java:1910) ~[starrocks-bdb-je-7.3.8.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.getMaxJournalId(BDBJEJournal.java:223) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:299) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.open(EditLog.java:836) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:942) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:107) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:62) [starrocks-fe.jar:?]

```
