### ISSUE TITLE
Two nodes are scale-in. Fe breaks down

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5787]
### Steps to reproduce the behavior (Required)
After the deployment is complete, you need to create a new file for scale-in or scale-out
1.
The premise
vim test123.yaml
```
global:
    user: "test222"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks222/fe
    meta_dir: /data/starrocks222/fe/meta
    log_dir: /data/starrocks222/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "1d"
  - host: 192.168.88.84
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks222/fe
    meta_dir: /data/starrocks222/fe/meta
    log_dir: /data/starrocks222/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "2d"
- host: 192.168.88.85
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks222/fe
    meta_dir: /data/starrocks222/fe/meta
    log_dir: /data/starrocks222/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "3d"
be_servers:
  - host: 192.168.88.83
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks222/be
    storage_dir: /data/starrocks222/be/storage
    log_dir: /data/starrocks222/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
./main-0505-2 cluster deploy test123 v2.0.1 test123.yaml
The cluster has been deploy
2.
nd5
```
mkdir /opt/starrocks222 && chown test222:test222 /opt/starrocks222
mkdir -p /data/starrocks222 && chown test222:test222 /data/starrocks222
```
3.
vim test_be_nd4_nd5.yaml
```
be_servers:
  - host: 192.168.88.84
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks222/be
    storage_dir: /data/starrocks222/be/storage
    log_dir: /data/starrocks222/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
be_servers:
  - host: 192.168.88.85
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks222/be
    storage_dir: /data/starrocks222/be/storage
    log_dir: /data/starrocks222/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
./main-0505-2 cluster scale-out test123 test_be_nd4_nd5.yaml
### Expected behavior (Required)
deploy success 
### Real behavior (Required)
Fe breaks down
```
2022-05-06 15:38:43,624 WARN (replayer|63) [BDBJournalCursor.next():148] Catch an exception when get next JournalEntity. key:26711
com.sleepycat.je.LockTimeoutException: (JE 7.3.7) Lock expired. Locker 410120672 -1_replayer_ReplicaThreadLocker: waited for lock on database=54 LockAddr:1392652642 LSN=0x0/0x8a1f4e type=READ grant=WAIT_NEW timeoutMillis=1000 startTime=1651822722624 endTime=1651822723624
Owners: [<LockInfo locker="<ReplayTxn id="-40906">30529951 -40906_ReplayThread_ReplayTxn" type="WRITE"/>]
Waiters: [<LockInfo locker="410120672 -1_replayer_ReplicaThreadLocker" type="READ"/>]

        at com.sleepycat.je.txn.LockManager.makeTimeoutException(LockManager.java:1117) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.LockManager.waitForLock(LockManager.java:606) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.LockManager.lock(LockManager.java:345) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.BasicLocker.lockInternal(BasicLocker.java:124) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.ReplicaThreadLocker.lockInternal(ReplicaThreadLocker.java:63) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Locker.lock(Locker.java:499) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3585) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3316) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.lockLNAndCheckDefunct(CursorImpl.java:2138) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.searchExact(CursorImpl.java:1950) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.searchExact(Cursor.java:4194) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.searchNoDups(Cursor.java:4055) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.search(Cursor.java:3857) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.getInternal(Cursor.java:1284) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Database.get(Database.java:1271) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Database.get(Database.java:1330) ~[je-7.3.7.jar:7.3.7]
        at com.starrocks.journal.bdbje.CloseSafeDatabase.get(CloseSafeDatabase.java:47) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJournalCursor.next(BDBJournalCursor.java:108) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2467) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$3.runOneCycle(Catalog.java:2256) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
2022-05-06 15:38:43,624 WARN (replayer|63) [Catalog.replayJournal():2485] replay journal cost too much time: 1000 replayedJournalId: 26710
```
![image](https://user-images.githubusercontent.com/57162397/167096467-e5542342-402a-441b-9591-1232958b3335.png)

**Comment by wangtianyi2004** [comment]
Sorry, I don't find this issue. Could you pls check it again?
