### ISSUE TITLE
BE and FE down

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5822]
### Steps to reproduce the behavior (Required)
1.The deployed cluster failed for unknown reasons
```
2022-05-07 14:43:55,449 INFO (starrocks-mysql-nio I/O-2|66) [AcceptListener.handleEvent():54] Connection established. remote=/192.168.88.81:47154
2022-05-07 14:43:55,452 INFO (starrocks-mysql-nio-pool-9|99) [StmtExecutor.analyze():578] begin to analyze stmt: 14, forwarded stmt id: 0
2022-05-07 14:43:55,452 WARN (starrocks-mysql-nio-pool-9|99) [StmtExecutor.execute():465] execute Exception, sql show backends
java.lang.Exception: Failed to get master client.
        at com.starrocks.qe.MasterOpExecutor.forward(MasterOpExecutor.java:121) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.execute(MasterOpExecutor.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.forwardToMaster(StmtExecutor.java:542) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:326) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:248) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:395) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:631) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_301]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_301]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: org.apache.thrift.transport.TTransportException: Cannot open null host.
        at org.apache.thrift.transport.TSocket.open(TSocket.java:210) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:116) ~[starrocks-fe.jar:?]
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.2.jar:2.2]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1012) ~[commons-pool2-2.2.jar:2.2]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.2.jar:2.2]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:277) ~[commons-pool2-2.2.jar:2.2]
        at com.starrocks.common.GenericPool.borrowObject(GenericPool.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.forward(MasterOpExecutor.java:118) ~[starrocks-fe.jar:?]
        ... 10 more
2022-05-07 14:43:59,182 WARN (replayer|62) [Catalog.setCanRead():2302] meta out of date. current time: 1651905839182, synchronized time: 1651893741259, has log: false, fe type: UNKNOWN
```

### Expected behavior (Required)
cluster success
### Real behavior (Required)
cluster failed

**Comment by wangtianyi2004** [comment]
could you pls provide the option you input?
