### ISSUE TITLE
Be crash of TPCDS-Q67

### ISSUE THREAD

**Issue by liuyehcf** [StarRocks/starrocks#6000]
### Steps to reproduce the behavior (Required)

* TPCDS-100g, 3be
* Q-67

```sql
select  *
from (select i_category
            ,i_class
            ,i_brand
            ,i_product_name
            ,d_year
            ,d_qoy
            ,d_moy
            ,s_store_id
            ,sumsales
            ,rank() over (partition by i_category order by sumsales desc) rk
      from (select i_category
                  ,i_class
                  ,i_brand
                  ,i_product_name
                  ,d_year
                  ,d_qoy
                  ,d_moy
                  ,s_store_id
                  ,sum(coalesce(ss_sales_price*ss_quantity,0)) sumsales
            from store_sales
                ,date_dim
                ,store
                ,item
       where  ss_sold_date_sk=d_date_sk
          and ss_item_sk=i_item_sk
          and ss_store_sk = s_store_sk
          and d_month_seq between 1200 and 1200+11
       group by  rollup(i_category, i_class, i_brand, i_product_name, d_year, d_qoy, d_moy,s_store_id))dw1) dw2
where rk <= 100
order by i_category
        ,i_class
        ,i_brand
        ,i_product_name
        ,d_year
        ,d_qoy
        ,d_moy
        ,s_store_id
        ,sumsales
        ,rk
limit 100;
```

### Real behavior (Required)

```
#0  0x0000000001c1738b in starrocks::BitShufflePageDecoder<(starrocks::FieldType)5>::next_batch (this=0x19f20300, range=..., dst=0x21f77000) at /home/disk3/hcf/starrocks/be/src/storage/rowset/bitshuffle_page.h:412
#1  0x0000000001c69363 in starrocks::ParsedPageV2::read (this=0x1ae3afd0, column=0x1c0526f0, range=...) at /home/disk3/hcf/starrocks/be/src/storage/rowset/parsed_page.cpp:268
#2  0x0000000001c415c8 in starrocks::ScalarColumnIterator::next_batch (this=0x198d6c60, range=..., dst=0x1c0526f0) at /home/disk3/hcf/starrocks/be/src/storage/rowset/scalar_column_iterator.cpp:235
#3  0x0000000001a9d450 in starrocks::vectorized::SegmentIterator::ScanContext::read_columns (range=..., chunk=0x1871fef0, this=0x14e28d18) at /home/disk3/hcf/starrocks/be/src/storage/rowset/segment_iterator.cpp:124
#4  starrocks::vectorized::SegmentIterator::_read (this=this@entry=0x14e28810, chunk=chunk@entry=0x1871fef0, rowids=rowids@entry=0x0, n=16384) at /home/disk3/hcf/starrocks/be/src/storage/rowset/segment_iterator.cpp:611
#5  0x0000000001a95935 in starrocks::vectorized::SegmentIterator::_do_get_next (this=0x14e28810, result=0x1871fd50, rowid=0x0) at /home/disk3/hcf/starrocks/be/src/storage/rowset/segment_iterator.cpp:690
#6  0x0000000001a990b1 in starrocks::vectorized::SegmentIterator::do_get_next (this=0x14e28810, chunk=0x1871fd50) at /home/disk3/hcf/starrocks/be/src/storage/rowset/segment_iterator.cpp:641
#7  0x0000000001af4912 in starrocks::vectorized::ChunkIterator::get_next (chunk=<optimized out>, this=<optimized out>) at /home/disk3/hcf/starrocks/be/src/storage/chunk_iterator.h:40
#8  starrocks::vectorized::ProjectionIterator::do_get_next (this=0x129d3810, chunk=0x265266c0) at /home/disk3/hcf/starrocks/be/src/storage/projection_iterator.cpp:69
#9  0x0000000001f19dca in starrocks::vectorized::ChunkIterator::get_next (chunk=<optimized out>, this=<optimized out>) at /home/disk3/hcf/starrocks/be/src/storage/chunk_iterator.h:40
#10 starrocks::SegmentIteratorWrapper::do_get_next (this=<optimized out>, chunk=<optimized out>) at /home/disk3/hcf/starrocks/be/src/storage/rowset/beta_rowset.cpp:209
#11 0x0000000001b2ac1b in starrocks::vectorized::ChunkIterator::get_next (chunk=0x265266c0, this=<optimized out>) at /home/disk3/hcf/starrocks/be/src/storage/chunk_iterator.h:40
#12 starrocks::vectorized::TimedChunkIterator::do_get_next (this=0x1776cb10, chunk=0x265266c0) at /home/disk3/hcf/starrocks/be/src/storage/chunk_iterator.h:159
#13 0x0000000001b2364e in starrocks::vectorized::ChunkIterator::get_next (chunk=<optimized out>, this=<optimized out>) at /home/disk3/hcf/starrocks/be/src/storage/chunk_iterator.h:40
#14 starrocks::vectorized::TabletReader::do_get_next (this=<optimized out>, chunk=<optimized out>) at /home/disk3/hcf/starrocks/be/src/storage/tablet_reader.cpp:85
#15 0x00000000028f1a7c in starrocks::vectorized::ChunkIterator::get_next (chunk=0x265266c0, this=<optimized out>) at /home/disk3/hcf/starrocks/be/src/storage/chunk_iterator.h:40
#16 starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage (this=0x13327a90, state=<optimized out>, chunk=0x265266c0) at /home/disk3/hcf/starrocks/be/src/exec/pipeline/scan/olap_chunk_source.cpp:386
#17 0x00000000028f2100 in starrocks::pipeline::OlapChunkSource::buffer_next_batch_chunks_blocking (this=0x13327a90, batch_size=32, state=0x13360000) at /home/disk3/hcf/starrocks/be/src/exec/pipeline/scan/olap_chunk_source.cpp:301
#18 0x00000000027f14e5 in operator() (__closure=0x18798690) at /home/disk3/hcf/starrocks/be/src/exec/pipeline/scan/scan_operator.cpp:228
#19 std::__invoke_impl<void, starrocks::pipeline::ScanOperator::_trigger_next_scan(starrocks::RuntimeState*, int)::<lambda()>&> (__f=...) at /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

+-------------------+
| current_version() |
+-------------------+
| UNKNOWN b1eda69e0 |
+-------------------+

**Comment by liuyehcf** [comment]
I have re-tested in 8ae3e6dc5 and the problem is solved. But I have no idea  which pr solved it
