### ISSUE TITLE
use trino exec insert sql to starrocks will error

### ISSUE THREAD

**Issue by Linzol** [StarRocks/starrocks#637]
### Steps to reproduce the behavior (Required)
1.when i exec this insert sql  in trino client : 
    [
    	insert into doris.dw.glog_m_deposit_rt (stat_date)
    	select  stat_date from oracle.rpt .GLOG_M_DEPOSIT_RT where STAT_DATE >=date_parse('2020-04-01','%Y-%m-%d') and STAT_DATE <=date_parse('2020-04-10','%Y-%m-%d')  
    ]
    
2.trino return an error : 
    [
			io.trino.spi.TrinoException: Syntax error in line 1:
			...d51b428e96657087f3edd750` AS SELECT * FROM `dw`.`glog_...
			                             ^
			Encountered: AS
			Expected

				at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:911)
				at io.trino.plugin.mysql.MySqlClient.copyTableSchema(MySqlClient.java:479)
				at io.trino.plugin.jdbc.BaseJdbcClient.beginInsertTable(BaseJdbcClient.java:628)
				at io.trino.plugin.jdbc.ForwardingJdbcClient.beginInsertTable(ForwardingJdbcClient.java:188)
				at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$beginInsertTable$23(StatisticsAwareJdbcClient.java:243)
				at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
				at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.beginInsertTable(StatisticsAwareJdbcClient.java:243)
				at io.trino.plugin.jdbc.CachingJdbcClient.beginInsertTable(CachingJdbcClient.java:293)
				at io.trino.plugin.jdbc.CachingJdbcClient.beginInsertTable(CachingJdbcClient.java:293)
				at io.trino.plugin.jdbc.DefaultJdbcMetadata.beginInsert(DefaultJdbcMetadata.java:665)
				at io.trino.metadata.MetadataManager.beginInsert(MetadataManager.java:930)
				at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:227)
				at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:174)
				at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:93)
				at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
				at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
				at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
				at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
				at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
				at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
				at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
				at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
				at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
				at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
				at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
				at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
				at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
				at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
				at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
				at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
				at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
				at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:78)
				at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:218)
				at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:203)
				at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:198)
				at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:488)
				at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:468)
				at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:411)
				at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
				at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
				at io.trino.$gen.Trino_362____20211013_111338_2.run(Unknown Source)
				at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
				at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
				at java.base/java.lang.Thread.run(Thread.java:834)
				Suppressed: java.lang.RuntimeException: Query: CREATE TABLE `dw`.`tmp_trino_7968fcc8d51b428e96657087f3edd750` AS SELECT * FROM `dw`.`glog_m_deposit_rt` WHERE 0 = 1
					at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:912)
					... 43 more
				Suppressed: java.lang.Exception: Current plan:
			                Output[rows]
			                │   Layout: [rows:bigint]
			                └─ TableCommit[doris:dw.glog_m_deposit_rt dw.glog_m_deposit_rt]
			                   │   Layout: [rows:bigint]
			                   └─ LocalExchange[SINGLE] ()
			                      │   Layout: [partialrows:bigint, fragment:varbinary]
			                      └─ RemoteExchange[GATHER]
			                         │   Layout: [partialrows:bigint, fragment:varbinary]
			                         └─ TableWriter
			                            │   Layout: [partialrows:bigint, fragment:varbinary]
			                            │   stat_date := stat_date_0
			                            └─ LocalExchange[SINGLE] ()
			                               │   Layout: [stat_date_0:date]
			                               └─ RemoteExchange[REPARTITION]
			                                  │   Layout: [stat_date_0:date]
			                                  └─ ScanProject[table = oracle:rpt.glog_m_deposit_rt RPT.GLOG_M_DEPOSIT_RT constraint on [STAT_DATE] columns=[STAT_DATE:timestamp(3):DATE]]
			                                         Layout: [stat_date_0:date]
			                                         stat_date_0 := CAST("stat_date" AS date)
			                                         stat_date := STAT_DATE:timestamp(3):DATE

					at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:84)
					... 12 more
			Caused by: java.sql.SQLSyntaxErrorException: Syntax error in line 1:
			...d51b428e96657087f3edd750` AS SELECT * FROM `dw`.`glog_... 
	]

3. i find the source code in trino :

	[
			@Override
	    protected void copyTableSchema(Connection connection, String catalogName, String schemaName, String tableName, String newTableName, List<String> columnNames)
	    {
	        String tableCopyFormat = "CREATE TABLE %s AS SELECT * FROM %s WHERE 0 = 1";
	        if (isGtidMode(connection)) {
	            tableCopyFormat = "CREATE TABLE %s LIKE %s";
	        }
	        String sql = format(
	                tableCopyFormat,
	                quoted(catalogName, schemaName, newTableName),
	                quoted(catalogName, schemaName, tableName));
	        execute(connection, sql);
	    }
	    
	    private static boolean isGtidMode(Connection connection)
	    {
	        try (java.sql.Statement statement = connection.createStatement();
	                ResultSet resultSet = statement.executeQuery("SHOW VARIABLES LIKE 'gtid_mode'")) {
	            if (resultSet.next()) {
	                return !resultSet.getString("Value").equalsIgnoreCase("OFF");
	            }

	            return false;
	        }
	        catch (SQLException e) {
	            throw new TrinoException(JDBC_ERROR, e);
	        }
	    }
	
	]
	
4. it because in mysql ，trino create temp table  use [  CREATE TABLE %s AS SELECT * FROM %s WHERE 0 = 1  ]  
		when [  SHOW VARIABLES LIKE 'gtid_mode'=OFF ]

5. in fact , starrocks has not system VARIABLES "gtid_mode" .

6. if starrocks add a system VARIABLES 'gtid_mode' may be can slove this bug  
   or starrocks support create table use "CREATE TABLE %s AS SELECT * FROM %s WHERE 0 = 1"  this syntax;

7. one more thing: 
	[ 
		trino can insert to starrocks and don`t create temp table ,just append "insert.non-transactional-insert.enabled=true" to starrocks.properties in trino config。
		with this config，i can exec insert sql when data all right 
		but ,when data has some error like " xxx cloumn is null ",
		trino will delete the table i create in starrocks, and starrrocks has no aim table,
		its really crazy,and high risk ! 
	]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by Linzol** [comment]
about starrocks support CATS ，do you have some plan in future ?     in fact ，in our company ，use trino insert data to starrocks will be an important point。

**Comment by imay** [comment]
> about starrocks support CATS ，do you have some plan in future ? in fact ，in our company ，use trino insert data to starrocks will be an important point。

Yes, we have plan to support CTAS.
