### ISSUE TITLE
CTAS with union all failed in 2.1.6

### ISSUE THREAD

**Issue by Astralidea** [StarRocks/starrocks#6564]
### Steps to reproduce the behavior (Required)
create table test_union_all as select * from 
(select * from (select 1 as k1) a
left join (select 1 as k2) b
on b.k2=a.k1
union all
select 2 as k1, 3 as k2
)aa

### Expected behavior (Required)
Success.
### Real behavior (Required)
java.lang.ClassCastException: com.starrocks.analysis.SetOperationStmt cannot be cast to com.starrocks.analysis.SelectStmt
    at com.starrocks.sql.analyzer.CTASAnalyzer.getReplicationNumAndGenTableRef(CTASAnalyzer.java:146) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.CTASAnalyzer.getReplicationNumAndGenTableRef(CTASAnalyzer.java:146) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.CTASAnalyzer.transformCTASStmt(CTASAnalyzer.java:63) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:60) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:34) ~[starrocks-fe.jar:?]
    at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:299) ~[starrocks-fe.jar:?]
    at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) ~[starrocks-fe.jar:?]
    at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) ~[starrocks-fe.jar:?]
    at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) ~[starrocks-fe.jar:?]
    at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_271]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_271]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.1.6

**Comment by jaogoy** [comment]
@Astralidea Does this bug accur in 2.2, 2.3?

**Comment by Astralidea** [comment]
> @Astralidea Does this bug accur in 2.2, 2.3?

This only affects 2.1.x and will not affect versions after 2.2
