### ISSUE TITLE
get hive table from meta store failed

### ISSUE THREAD

**Issue by minchowang** [StarRocks/starrocks#6687]
### Steps to reproduce the behavior (Required)
```
CREATE EXTERNAL RESOURCE "hive0"
PROPERTIES (
  "type" = "hive",
  "hive.metastore.uris" = "thrift://172.18.xx.xx:9083"
);

CREATE EXTERNAL TABLE `user` (
  `id` INT NULL,
  `name` varchar(200) NULL,
  `address` varchar(200) NULL
) ENGINE=HIVE
PROPERTIES (
  "resource" = "hive0",
  "database" = "test",
  "table" = "user"
);
 ERROR 1064 (HY000): get hive table from meta store failed: hive.test.user table not found

```

### Expected behavior (Required)
This hive external table for `test.user` existed, but starroocks cannot read it.

I'm using the following code to connect hms, `hiveClient.getAllDatabases() `got was empty.
```
HiveMetaClient client = new HiveMetaClient("thrift://172.18.xx.xx:9083");
```

### StarRocks version (Required)

sr 2.1.2
hive 3.1.2
hadoop 3.2.1

**Comment by DorianZheng** [comment]
@minchowang plz post your hms log

**Comment by minchowang** [comment]
> @minchowang plz post your hms log

```
2022-05-31T16:56:54,234 ERROR [pool-6-thread-1] server.TThreadPoolServer: Thrift error occurred during processing of message.
org.apache.thrift.TException: null
	at org.apache.hadoop.hive.metastore.TUGIBasedProcessor.process(TUGIBasedProcessor.java:97) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [hive-exec-3.1.2.jar:3.1.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
2022-05-31T16:56:54,237  INFO [pool-6-thread-1] metastore.HiveMetaStore: 2: Done cleaning up thread local RawStore
2022-05-31T16:56:54,261  INFO [pool-6-thread-1] HiveMetaStore.audit: ugi=root	ip=172.17.0.2	cmd=Done cleaning up thread local RawStore
2022-05-31T16:56:55,412 ERROR [pool-6-thread-2] server.TThreadPoolServer: Thrift error occurred during processing of message.
org.apache.thrift.TException: null
	at org.apache.hadoop.hive.metastore.TUGIBasedProcessor.process(TUGIBasedProcessor.java:97) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [hive-exec-3.1.2.jar:3.1.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
2022-05-31T16:56:55,413  INFO [pool-6-thread-2] metastore.HiveMetaStore: 3: Done cleaning up thread local RawStore
2022-05-31T16:56:55,413  INFO [pool-6-thread-2] HiveMetaStore.audit: ugi=root	ip=172.17.0.2	cmd=Done cleaning up thread local RawStore
```

**Comment by DorianZheng** [comment]
@minchowang Is user `root` are authorized to access HMS, would you mind to check what user is running HMS process, and set `HADOOP_USER_NAME` on fe/conf/hadoop_env.sh and be/conf/hadoop_env.sh to the same user name?
