### ISSUE TITLE
FE exists with npe when replaying add replica

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#6776]
### Steps to reproduce the behavior (Required)
1. set catalog_trash_expire_second to 60 in fe.conf
2. drop tables and restart be continually.

### Expected behavior (Required)
```
2022-05-31 19:15:54,512 INFO (stateListener|76) [CatalogRecycleBin.replayEraseTable():338] replay erase table[6057015] finished
2022-05-31 19:15:54,513 ERROR (stateListener|76) [EditLog.loadJournal():834] Operation Type 42
java.lang.NullPointerException: null
        at com.starrocks.server.LocalMetastore.getPartitionIncludeRecycleBin(LocalMetastore.java:2636) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.unprotectAddReplica(LocalMetastore.java:2507) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.replayAddReplica(LocalMetastore.java:2542) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayAddReplica(GlobalStateMgr.java:2236) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:387) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1696) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.transferToMaster(GlobalStateMgr.java:902) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.access$800(GlobalStateMgr.java:259) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$4.runOneCycle(GlobalStateMgr.java:1618) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - all

**Comment by gengjun-git** [comment]
The reason is that erase table dose not hold the db write lock.
