### ISSUE TITLE
【primary table accidental】stream load error

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#6785]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE Primary_200cols_3rep
(k0 DATE NOT NULL, k1 VARCHAR(146) NOT NULL, k2 DATE NOT NULL, k3 STRING NOT NULL, k4 DATETIME NOT NULL, k5 DATETIME NULL, k6 STRING NULL, k7 DECIMAL(7,1) NULL, k8 BIGINT NULL, k9 DATETIME NULL, k10 DECIMAL(8,4) NULL, k11 STRING NULL, k12 CHAR(126) NULL, k13 INT NULL, k14 DECIMAL(4,2) NULL, k15 DATETIME NULL, k16 DATETIME NULL, k17 STRING NULL, k18 CHAR(40) NULL, k19 VARCHAR(165) NULL, k20 STRING NULL, k21 CHAR(228) NULL, k22 DATE NULL, k23 INT NULL, k24 INT NULL, k25 VARCHAR(810) NULL, k26 DECIMAL(11,10) NULL, k27 STRING NULL, k28 VARCHAR(56) NULL, k29 DATETIME NULL, k30 VARCHAR(820) NULL, k31 VARCHAR(17) NULL, k32 VARCHAR(92) NULL, k33 DATETIME NULL, k34 CHAR(248) NULL, k35 VARCHAR(950) NULL, k36 STRING NULL, k37 STRING NULL, k38 DATE NULL, k39 DATETIME NULL, v0 DATE NULL, v1 LARGEINT NULL, v2 STRING NULL, v3 DATETIME NULL, v4 DATETIME NULL, v5 STRING NULL, v6 STRING NULL, v7 DECIMAL(2,0) NULL, v8 DATETIME NULL, v9 CHAR(109) NULL, v10 VARCHAR(49) NULL, v11 CHAR(135) NULL, v12 VARCHAR(986) NULL, v13 VARCHAR(65490) NULL, v14 STRING NULL, v15 DECIMAL(12,1) NULL, v16 DECIMAL(27,1) NULL, v17 STRING NULL, v18 VARCHAR(65519) NULL, v19 STRING NULL, v20 DECIMAL(32,17) NULL, v21 INT NULL, v22 STRING NULL, v23 TINYINT NULL, v24 STRING NULL, v25 STRING NULL, v26 BIGINT NULL, v27 STRING NULL, v28 VARCHAR(135) NULL, v29 CHAR(165) NULL, v30 CHAR(202) NULL, v31 LARGEINT NULL, v32 INT NULL, v33 STRING NULL, v34 LARGEINT NULL, v35 CHAR(234) NULL, v36 VARCHAR(12) NULL, v37 VARCHAR(886) NULL, v38 DATETIME NULL, v39 LARGEINT NULL, v40 CHAR(149) NULL, v41 STRING NULL, v42 SMALLINT NULL, v43 STRING NULL, v44 DATE NULL, v45 VARCHAR(74) NULL, v46 LARGEINT NULL, v47 DATETIME NULL, v48 INT NULL, v49 TINYINT NULL, v50 VARCHAR(65415) NULL, v51 VARCHAR(160) NULL, v52 CHAR(10) NULL, v53 VARCHAR(65458) NULL, v54 INT NULL, v55 INT NULL, v56 DECIMAL(31,14) NULL, v57 VARCHAR(95) NULL, v58 STRING NULL, v59 INT NULL, v60 DECIMAL(18,10) NULL, v61 TINYINT NULL, v62 DECIMAL(27,6) NULL, v63 DECIMAL(27,5) NULL, v64 VARCHAR(69) NULL, v65 LARGEINT NULL, v66 DATE NULL, v67 LARGEINT NULL, v68 BIGINT NULL, v69 STRING NULL, v70 SMALLINT NULL, v71 INT NULL, v72 TINYINT NULL, v73 DECIMAL(6,2) NULL, v74 DATETIME NULL, v75 DATE NULL, v76 DATE NULL, v77 DECIMAL(15,12) NULL, v78 LARGEINT NULL, v79 BIGINT NULL, v80 VARCHAR(818) NULL, v81 DECIMAL(29,28) NULL, v82 STRING NULL, v83 STRING NULL, v84 CHAR(20) NULL, v85 VARCHAR(65418) NULL, v86 LARGEINT NULL, v87 SMALLINT NULL, v88 INT NULL, v89 STRING NULL, v90 STRING NULL, v91 BIGINT NULL, v92 LARGEINT NULL, v93 VARCHAR(838) NULL, v94 DATETIME NULL, v95 VARCHAR(65447) NULL, v96 DATETIME NULL, v97 LARGEINT NULL, v98 DECIMAL(34,30) NULL, v99 VARCHAR(139) NULL, v100 CHAR(209) NULL, v101 BIGINT NULL, v102 DECIMAL(25,24) NULL, v103 BIGINT NULL, v104 CHAR(194) NULL, v105 STRING NULL, v106 BIGINT NULL, v107 STRING NULL, v108 DECIMAL(34,1) NULL, v109 BIGINT NULL, v110 VARCHAR(65506) NULL, v111 STRING NULL, v112 DECIMAL(36,8) NULL, v113 STRING NULL, v114 INT NULL, v115 LARGEINT NULL, v116 VARCHAR(65500) NULL, v117 VARCHAR(29) NULL, v118 VARCHAR(157) NULL, v119 INT NULL, v120 DATETIME NULL, v121 CHAR(221) NULL, v122 DECIMAL(23,6) NULL, v123 STRING NULL, v124 STRING NULL, v125 STRING NULL, v126 DECIMAL(8,5) NULL, v127 VARCHAR(65477) NULL, v128 STRING NULL, v129 DATE NULL, v130 VARCHAR(14) NULL, v131 LARGEINT NULL, v132 CHAR(50) NULL, v133 VARCHAR(65495) NULL, v134 LARGEINT NULL, v135 DATETIME NULL, v136 VARCHAR(197) NULL, v137 BIGINT NULL, v138 CHAR(238) NULL, v139 VARCHAR(42) NULL, v140 INT NULL, v141 LARGEINT NULL, v142 DECIMAL(8,2) NULL, v143 CHAR(255) NULL, v144 VARCHAR(807) NULL, v145 VARCHAR(65484) NULL, v146 STRING NULL, v147 STRING NULL, v148 VARCHAR(810) NULL, v149 STRING NULL, v150 INT NULL, v151 VARCHAR(87) NULL, v152 BIGINT NULL, v153 STRING NULL, v154 DECIMAL(25,9) NULL, v155 CHAR(38) NULL, v156 CHAR(79) NULL, v157 VARCHAR(109) NULL, v158 BIGINT NULL, v159 STRING NULL)
PRIMARY KEY(k0,k1,k2)
DISTRIBUTED BY HASH(k0,k1,k2) BUCKETS 100 PROPERTIES ("replication_num" = "3");
```
2.
stream load 1T data
```
    for i in range(1, 6):
        for j in range(200):
            cmd = """curl -v --location-trusted -u root: -T /home/disk1/sr/data_duplicate_200col_no_json_csv/data%s/fake_data%s.csv -H "format:csv" -H "strict_mode:false" http://IP:PORT/api/lcy/Primary_200cols_3rep/_stream_load""" % (i, (i - 1) * 200 + j)
            print(cmd)
            res = subprocess.run(
                cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, encoding="utf-8", timeout=1800
            )
```

### Expected behavior (Required)
stream load success
### Real behavior (Required)
fe.warn.log
```
2022-06-01 16:35:59,165 WARN (Thread-42|96) [Replica.updateReplicaInfo():352] current version 526 is larger than last failed version 521, maybe a fatal error or be report version, print a stack here
java.lang.Exception: null
        at com.starrocks.catalog.Replica.updateReplicaInfo(Replica.java:354) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Replica.updateRowCount(Replica.java:262) [starrocks-fe.jar:?]
        at com.starrocks.master.ReportHandler.sync(ReportHandler.java:572) [starrocks-fe.jar:?]
        at com.starrocks.master.ReportHandler.tabletReport(ReportHandler.java:349) [starrocks-fe.jar:?]
        at com.starrocks.master.ReportHandler.access$300(ReportHandler.java:102) [starrocks-fe.jar:?]
        at com.starrocks.master.ReportHandler$ReportTask.exec(ReportHandler.java:297) [starrocks-fe.jar:?]
        at com.starrocks.master.ReportHandler.runOneCycle(ReportHandler.java:1276) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
2022-06-01 16:36:01,293 WARN (heartbeat mgr|42) [HeartbeatMgr.runAfterCatalogReady():142] get bad heartbeat response: type: FRONTEND, status: BAD, msg: not ready, name: 172.26.195.70_9012_1653484930514, queryPort: 0, rpcPort: 0, replayedJournalId: 0, feStartTime: \N, feVersion: null
2022-06-01 16:36:02,324 WARN (thrift-server-pool-125|334) [MasterImpl.finishTask():186] cannot find task. type: PUBLISH_VERSION, backendId: 10006, signature: 177016
2022-06-01 16:36:02,484 WARN (thrift-server-pool-140|973) [MasterImpl.finishTask():186] cannot find task. type: PUBLISH_VERSION, backendId: 10006, signature: 177015
2022-06-01 16:36:06,437 WARN (heartbeat mgr|42) [HeartbeatMgr.runAfterCatalogReady():142] get bad heartbeat response: type: FRONTEND, status: BAD, msg: not ready, name: 172.26.195.70_9012_1653484930514, queryPort: 0, rpcPort: 0, replayedJournalId: 0, feStartTime: \N, feVersion: null
```
![wBJcM4LWXZ](https://user-images.githubusercontent.com/57162397/171186704-cd7f190d-deed-4ec6-a4b5-762b37e3f694.png)
![sCwna7UXYp](https://user-images.githubusercontent.com/57162397/171186740-0d040eb5-cf6d-4bd8-9071-4cc9be2141a0.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 ```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 7ccaf0b |
+----------------------+
```

**Comment by lvchenyang-maker** [comment]
accidental
