### ISSUE TITLE
read empty iceberg table will cause exception

### ISSUE THREAD

**Issue by hongli-my** [StarRocks/starrocks#6840]
### Steps to reproduce the behavior (Required)
1.
```
CREATE EXTERNAL TABLE `iceberg_t3` (
  `order_id` bigint(20) NULL COMMENT "",
  `order_time` datetime NULL COMMENT ""
) ENGINE=ICEBERG
COMMENT "ICEBERG"
PROPERTIES (
"database" = "iceberg_db",
"table" = "iceberg_t2",
"resource" = "iceberg0"
);
```
2.  `select * from iceberg_t3 where order_time > "2022-04-03 00:10:00"`

### Expected behavior (Required)
```
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.Statistics.getColumnStatistic(Statistics.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:60) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:39) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:32) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.getExpressionStatistic(PredicateStatisticsCalculator.java:324) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:215) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:32) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator.statisticsCalculate(PredicateStatisticsCalculator.java:29) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimateStatistics(StatisticsCalculator.java:1243) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitOperator(StatisticsCalculator.java:171) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeIcebergScanNode(StatisticsCalculator.java:259) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalIcebergScan(StatisticsCalculator.java:242) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalIcebergScan(StatisticsCalculator.java:135) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalIcebergScanOperator.accept(LogicalIcebergScanOperator.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:151) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:129) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:86) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:312) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:283) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:430) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
```
### Real behavior (Required)
select result

### StarRocks version (Required)
 -  branch-2.2

**Comment by hongli-my** [comment]
I think this reason is  iceberg cost : `generateIcebergFileStats` function get null,  here maybe return default statics, and count is zero from empty table.
