### ISSUE TITLE
Broker is not compatible with hadoop 3.2.1 when kerberos was enabled

### ISSUE THREAD

**Issue by caneGuy** [StarRocks/starrocks#6869]
### Steps to reproduce the behavior (Required)
1. Set up a cluster using 2.1.1 for SR, using aliyun emr 5.5.1
2. Set up a aliyun emr 5.5.1 which contains a hdfs cluster with 3.2.1 and enable kerberos
3. put a csv filve on hdfs
4. use broker load to load csv file into sr

### Expected behavior (Required)
- load success
### Real behavior (Required)
```
2022-06-02 20:47:37  [ TThreadPoolServer WorkerProcess-%d:94869 ] - [ WARN ]  Failed to connect to /10.0.1.222:9866 for block BP-384577958-10.0.1.221-1654079599483:blk_1073741832_1008, add to deadNodes an
d continue.
java.io.IOException: Invalid token in javax.security.sasl.qop: ^DD
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.DataTransferSaslUtil.readSaslMessage(DataTransferSaslUtil.java:220)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferClient.doSaslHandshake(SaslDataTransferClient.java:553)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferClient.getSaslStreams(SaslDataTransferClient.java:455)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferClient.send(SaslDataTransferClient.java:298)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferClient.checkTrustAndSend(SaslDataTransferClient.java:245)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferClient.checkTrustAndSend(SaslDataTransferClient.java:227)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferClient.peerSend(SaslDataTransferClient.java:170)
        at org.apache.hadoop.hdfs.DFSUtilClient.peerFromSocketAndKey(DFSUtilClient.java:657)
        at org.apache.hadoop.hdfs.DFSClient.newConnectedPeer(DFSClient.java:2904)
        at org.apache.hadoop.hdfs.client.impl.BlockReaderFactory.nextTcpPeer(BlockReaderFactory.java:825)
        at org.apache.hadoop.hdfs.client.impl.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:750)
        at org.apache.hadoop.hdfs.client.impl.BlockReaderFactory.build(BlockReaderFactory.java:387)
        at org.apache.hadoop.hdfs.DFSInputStream.getBlockReader(DFSInputStream.java:734)
        at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:681)
        at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:971)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:1029)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at com.starrocks.broker.hdfs.FileSystemManager.readByteArrayFully(FileSystemManager.java:947)
        at com.starrocks.broker.hdfs.FileSystemManager.pread(FileSystemManager.java:838)
        at com.starrocks.broker.hdfs.HDFSBrokerServiceImpl.pread(HDFSBrokerServiceImpl.java:163)
        at com.starrocks.thrift.TFileBrokerService$Processor$pread.getResult(TFileBrokerService.java:940)
        at com.starrocks.thrift.TFileBrokerService$Processor$pread.getResult(TFileBrokerService.java:920)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

and datanode of hdfs cluster will unavailable since the same exception  will thrown for each operation coming from every hdfs client
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by caneGuy** [comment]
I will fix this issue later, any suggestion welcome

**Comment by caneGuy** [comment]
this can be fixed by https://github.com/StarRocks/starrocks/pull/5534
