### ISSUE TITLE
Unkown error

### ISSUE THREAD

**Issue by Youngwb** [StarRocks/starrocks#6871]
### Steps to reproduce the behavior (Required)
1. use tpch
 ```
SELECT `$cor0`.`S_NATIONKEY`, `$cor0`.`S_NAME`, `$cor0`.`S_ADDRESS` FROM (SELECT `S_NAME`, `S_ADDRESS`, `S_NATIONKEY` FROM `tpch`.`supplier` GROUP BY `S_NAME`, `S_ADDRESS`, `S_NATIONKEY`) AS `$cor0`,  (SELECT * FROM (SELECT `S_SUPPKEY`, `S_NAME`, `S_ADDRESS`, `S_NATIONKEY`, `S_PHONE`, `S_ACCTBAL`, `S_COMMENT` FROM `tpch`.`supplier` ORDER BY `S_NATIONKEY` IS NULL, `S_NATIONKEY` LIMIT 15 OFFSET 6) AS `t0` ) AS `t1` LIMIT 61202;
```
ERROR 1064 (HY000): Unknown error

### Real behavior (Required)
```
2022-06-03 17:23:58,720 WARN (starrocks-mysql-nio-pool-1|195) [StmtExecutor.execute():471] execute Exception, sql SELECT `$cor0`.`S_NATIONKEY`, `$cor0`.`S_NAME`, `$cor0`.`S_ADDRESS` FROM (SELECT `S_NAME`, `S_ADDRESS`, `S_NATIONKEY` FROM `tpch`.`supplier` GROUP BY `S_NAME`, `S_ADDRESS`, `S_NATIONKEY`) AS `$cor0`,  (SELECT * FROM (SELECT `S_SUPPKEY`, `S_NAME`, `S_ADDRESS`, `S_NATIONKEY`, `S_PHONE`, `S_ACCTBAL`, `S_COMMENT` FROM `tpch`.`supplier` ORDER BY `S_NATIONKEY` IS NULL, `S_NATIONKEY` LIMIT 15 OFFSET 6) AS `t0` ) AS `t1` LIMIT 61202
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.MergeLimitWithLimitRule.transform(MergeLimitWithLimitRule.java:67) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.TopDownRewriteTask.doExecute(TopDownRewriteTask.java:49) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.TopDownRewriteIterativeTask.execute(TopDownRewriteIterativeTask.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.ruleRewriteIterative(Optimizer.java:327) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:224) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:88) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:122) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:87) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:321) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:288) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:436) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:672) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
UNKNOWN-f6aa7175b

**Comment by lvchenyang-maker** [comment]
![22bmex9bVV](https://user-images.githubusercontent.com/57162397/189017129-b2ae9ee4-20f2-4471-9b62-43ee76c7fde7.jpg)

**Comment by kangkaisen** [comment]
Please paste the exception stack
