### ISSUE TITLE
创建 UDF 成功, 但使用时提示 'ERROR 1064 (HY000): rpc failed, host: xx.xx.xx.xx'

### ISSUE THREAD

**Issue by aubdiy** [StarRocks/starrocks#7075]
### Steps to reproduce the behavior (Required)
1. 部署 2.2.1 版本集群,3 台主机,  每台主机都部署 1 个 fe, 1个 be,  
2. 开启 UDF 功能, 在 FE 配置文件（$FE_HOME/conf/fe.conf）中设置配置项 enable_udf = true, 并重启整个集群
3. 开发UDF

- POM.XML

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>self.aub</groupId>
    <artifactId>test_sr_udf</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.15</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.10</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

* java 类
```
package self.aub.starrocks.udf;
import org.apache.commons.codec.digest.MurmurHash2;

public class MurmurHash2T64 {
    public final Long evaluate(String value) {
        if (value == null) {
            return null;
        }
        try {
            return MurmurHash2.hash64(value);
        } catch (Exception e) {
            return null;
        }
    }
}

```

4. 执行 maven 打包出  `test_sr_udf-1.0-SNAPSHOT-jar-with-dependencies.jar`  并重命名为 `starrocks-udf.jar`
5. 上传到 nginx 文件服务器, 并提供无密码访问,  使用 url 可以正常下载文件
6. 登陆 starrock `mysql -h  172.16.30.30 -P 19030 -u root`
7. 创建 udf 数据库,  切换到udf数据库, 配置 udf
```
create database udf;
use udf;
CREATE FUNCTION murmur_hash2_64(STRING) 
RETURNS BIGINT
properties (
    "symbol" = "self.aub.starrocks.udf.MurmurHash2T64", 
    "type" = "StarrocksJar",
    "file" = "http://test:90/starrocks/starrocks-udf.jar"
);


# 看到正常返回提示: Query OK, 0 rows affected (0.02 sec)
```
9.  执行UDF 报错 : 
```
mysql> select murmur_hash2_64("abc");
ERROR 1064 (HY000): rpc failed, host:  172.16.30.30
```

10. fe 日志
```
2022-06-10 11:50:37,703 WARN (starrocks-mysql-nio-pool-30|509) [StmtExecutor.execute():476] execute Exception, sql select murmur_hash2_64("abc")
com.starrocks.rpc.RpcException: rpc failed, host: 172.16.30.30
	at com.starrocks.qe.Coordinator.exec(Coordinator.java:598) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:694) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:395) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:285) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:432) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:668) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2022-06-10 11:50:39,966 INFO (thrift-server-pool-9|160) [ReportHandler.handleReport():224] receive report from be 10003. type: WORKGROUP_REPORT, current queue size: 1
2022-06-10 11:50:40,305 WARN (heartbeat-mgr-pool-1|105) [HeartbeatMgr$BackendHeartbeatHandler.call():265] backend heartbeat got exception
org.apache.thrift.transport.TTransportException: Socket is closed by peer.
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:130) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[libthrift-0.13.0.jar:0.13.0]
	at com.starrocks.thrift.HeartbeatService$Client.recv_heartbeat(HeartbeatService.java:61) ~[starrocks-fe.jar:?]
	at com.starrocks.thrift.HeartbeatService$Client.heartbeat(HeartbeatService.java:48) ~[starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:234) [starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:213) [starrocks-fe.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2022-06-10 11:50:40,305 WARN (heartbeat-mgr-pool-2|108) [HeartbeatMgr$BackendHeartbeatHandler.call():265] backend heartbeat got exception
org.apache.thrift.transport.TTransportException: Socket is closed by peer.
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:130) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[libthrift-0.13.0.jar:0.13.0]
	at com.starrocks.thrift.HeartbeatService$Client.recv_heartbeat(HeartbeatService.java:61) ~[starrocks-fe.jar:?]
	at com.starrocks.thrift.HeartbeatService$Client.heartbeat(HeartbeatService.java:48) ~[starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:234) [starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:213) [starrocks-fe.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2022-06-10 11:50:40,306 WARN (heartbeat mgr|25) [HeartbeatMgr.runAfterCatalogReady():142] get bad heartbeat response: type: BACKEND, status: BAD, msg: Socket is closed by peer.
2022-06-10 11:50:40,306 WARN (heartbeat mgr|25) [HeartbeatMgr.runAfterCatalogReady():142] get bad heartbeat response: type: BACKEND, status: BAD, msg: Socket is closed by peer.
2022-06-10 11:50:41,032 INFO (tablet scheduler|32) [ClusterLoadStatistic.classifyBackendByLoad():155] classify backend by load. medium: HDD, avg load score: 1.1001376227236812, low/mid/high: 1/1/1
2022-06-10 11:50:41,032 INFO (tablet scheduler|32) [ClusterLoadStatistic.classifyBackendByLoad():155] classify backend by load. medium: SSD, avg load score: 0.0, low/mid/high: 0/3/0
2022-06-10 11:50:41,032 INFO (tablet scheduler|32) [TabletScheduler.updateClusterLoadStatistic():353] update cluster default_cluster load statistic:
    be id: 10002, is available: true, mediums: [{medium: HDD, replica: 12, used: 3951, total: 119154933615, score: 0.8034004384826887},{medium: SSD, replica: 0, used: 0, total: 119154929664, score: 0.0},], paths: [{path: /data/data/starrocks/be/storage2, path hash: -3319748020674712527, be: 10002, medium: SSD, used: 0, total: 119154929664},{path: /data/data/starrocks/be/storage1, path hash: -6521516111255847789, be: 10002, medium: HDD, used: 3951, total: 119154933615},]
    be id: 10003, is available: true, mediums: [{medium: HDD, replica: 12, used: 3951, total: 54197759855, score: 1.1670323497297002},{medium: SSD, replica: 0, used: 0, total: 54197755904, score: 0.0},], paths: [{path: /data/data/starrocks/be/storage2, path hash: -1669878110737463502, be: 10003, medium: SSD, used: 0, total: 54197755904},{path: /data/data/starrocks/be/storage1, path hash: -3071895401259714988, be: 10003, medium: HDD, used: 3951, total: 54197759855},]
    be id: 10004, is available: true, mediums: [{medium: HDD, replica: 12, used: 3951, total: 43557261167, score: 1.3299800799586547},{medium: SSD, replica: 0, used: 0, total: 43557257216, score: 0.0},], paths: [{path: /data/data/starrocks/be/storage2, path hash: 2257652941572081226, be: 10004, medium: SSD, used: 0, total: 43557257216},{path: /data/data/starrocks/be/storage1, path hash: 5244389570074383844, be: 10004, medium: HDD, used: 3951, total: 43557261167},]

2022-06-10 11:50:41,032 INFO (tablet scheduler|32) [TabletScheduler.adjustPriorities():382] adjust priority for all tablets. changed: 0, total: 0
2022-06-10 11:50:44,244 INFO (Routine load scheduler|38) [RoutineLoadScheduler.process():76] there are 0 job need schedule
2022-06-10 11:50:44,966 INFO (thrift-server-pool-25|344) [ReportHandler.handleReport():224] receive report from be 10003. type: WORKGROUP_REPORT, current queue size: 1
2022-06-10 11:50:45,326 WARN (heartbeat-mgr-pool-5|114) [HeartbeatMgr$BackendHeartbeatHandler.call():265] backend heartbeat got exception
org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:226) ~[libthrift-0.13.0.jar:0.13.0]
	at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:131) ~[starrocks-fe.jar:?]
	at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:116) ~[starrocks-fe.jar:?]
	at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.3.jar:2.3]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1036) ~[commons-pool2-2.3.jar:2.3]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.3.jar:2.3]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:278) ~[commons-pool2-2.3.jar:2.3]
	at com.starrocks.common.GenericPool.borrowObject(GenericPool.java:88) ~[starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:227) [starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:213) [starrocks-fe.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
	at java.net.Socket.connect(Socket.java:591) ~[?:?]
	at org.apache.thrift.transport.TSocket.open(TSocket.java:221) ~[libthrift-0.13.0.jar:0.13.0]
	... 13 more
2022-06-10 11:50:45,326 WARN (heartbeat-mgr-pool-0|101) [HeartbeatMgr$BackendHeartbeatHandler.call():265] backend heartbeat got exception
org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:226) ~[libthrift-0.13.0.jar:0.13.0]
	at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:131) ~[starrocks-fe.jar:?]
	at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:116) ~[starrocks-fe.jar:?]
	at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.3.jar:2.3]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1036) ~[commons-pool2-2.3.jar:2.3]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.3.jar:2.3]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:278) ~[commons-pool2-2.3.jar:2.3]
	at com.starrocks.common.GenericPool.borrowObject(GenericPool.java:88) ~[starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:227) [starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:213) [starrocks-fe.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
	at java.net.Socket.connect(Socket.java:591) ~[?:?]
	at org.apache.thrift.transport.TSocket.open(TSocket.java:221) ~[libthrift-0.13.0.jar:0.13.0]
	... 13 more
2022-06-10 11:50:45,327 WARN (heartbeat mgr|25) [HeartbeatMgr.runAfterCatalogReady():142] get bad heartbeat response: type: BACKEND, status: BAD, msg: java.net.ConnectException: Connection refused (Connection refused)
2022-06-10 11:50:45,327 WARN (heartbeat mgr|25) [HeartbeatMgr.runAfterCatalogReady():142] get bad heartbeat response: type: BACKEND, status: BAD, msg: java.net.ConnectException: Connection refused (Connection refused)
```

### Expected behavior (Required)
期望正常执行

### Real behavior (Required)
实际报网络错误

### StarRocks version (Required)
`2.2.1 147f178`

**Comment by imay** [comment]
Could you paste be.out information in your backend be/log

**Comment by stdpain** [comment]
please check your JAVA_HOME in BE

**Comment by aubdiy** [comment]
> Could you paste be.out information in your backend be/log

当时使用 自定义 UDF 时,   be.out 打印如下
```
log4j:WARN No appenders could be found for logger (org.apache.hadoop.fs.FileSystem).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
*** Aborted at 1654842080 (unix time) try "date -d @1654842080" if you are using GNU date ***
PC: @     0x7fb65caa5a88 (unknown)
*** SIGSEGV (@0x797c66ac0) received by PID 1056366 (TID 0x7fb6f2f93700) from PID 18446744071960947392; stack trace: ***
    @          0x3ca57d2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fb72bbcee2b os::Linux::chained_handler()
    @     0x7fb72bbd399e JVM_handle_linux_signal
    @     0x7fb72bbc7c08 signalHandler()
    @     0x7fb72ad8c630 (unknown)
    @     0x7fb65caa5a88 (unknown)
start time: Fri Jun 10 14:21:30 CST 2022
```

**Comment by aubdiy** [comment]
> please check your JAVA_HOME in BE

我是在 cent os7 上 使用 system service 启动的 FE / BE, 并指定了  openJDK11 的    JAVA_HOME   路径 

```
[Unit]
Description=starrocks fe service
After=network.target

[Service]
Type=forking
LimitNOFILE=65536
User=starrocks
Environment="JAVA_HOME=/data/baize-dp/jdk-11"
ExecStart=/data/baize-dp/starrocks-fe/bin/start_fe.sh  --daemon
ExecStop=/data/baize-dp/starrocks-fe/bin/stop_fe.sh
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target
```

**Comment by stdpain** [comment]
UDF/Hive external table only support JDK-1.8

**Comment by aubdiy** [comment]
> 

OK,   3Q

**Comment by jaogoy** [comment]
> UDF/Hive external table only support JDK-1.8

Is this note included in the documentation ?
