### ISSUE TITLE
Can't skip authorization and reset root password

### ISSUE THREAD

**Issue by padmejin** [StarRocks/starrocks#7359]
### Steps to reproduce the behavior (Required)
If a user forgets his root password and can not log in, one way to resolve this is by skip auth check.
1. Change `fe.conf`, set `enable_auth_check` 
2. Restart all FE.
3. Use mysql client to login with no password
4. `ALTER USER 'root'@'%' IDENTIFIED BY 'newpass'`
5. Change `fe.conf` back, restart all FE, and login with the new password.

### Expected behavior (Required)
Password should be reset.

### Real behavior (Required)
Step 3 will fail
```
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0
```
The following logs are found.
```
2022-06-15 19:22:37,680 WARN (starrocks-mysql-nio-pool-1|103) [AcceptListener.lambda$handleEvent$1():92] connect processor exception because
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_322]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_322]
        at com.starrocks.mysql.MysqlProto.authenticate(MysqlProto.java:95) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.MysqlProto.negotiate(MysqlProto.java:204) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.AcceptListener.lambda$handleEvent$1(AcceptListener.java:68) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

**Comment by lvchenyang-maker** [comment]
![Rx2D5XLqL2](https://user-images.githubusercontent.com/57162397/190637651-a571d6c6-c97d-474d-a361-02b77480d5a0.jpg)
![0tRrVpilwo](https://user-images.githubusercontent.com/57162397/190637697-2336279a-5789-4bf8-8c47-8eac4e01a68a.jpg)
