### ISSUE TITLE
Hive external execute failed？

### ISSUE THREAD

**Issue by winfys** [StarRocks/starrocks#770]
starrocks version:1.18.1

![image](https://user-images.githubusercontent.com/13195083/138024995-fa265282-f49c-41e7-95ab-913a4d50e690.png)

log:
2021-10-20 11:34:15 ERROR TThreadPoolServer:321 - Thrift Error occurred during processing of message.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:125)
        ... 9 more

How can I solve it？

**Comment by gengjun-git** [comment]
Are hdfs and starrocks cluster networks connected?

**Comment by gengjun-git** [comment]
Seems that it's not the permission problem. Can you show the plan for the sql? Execute the below command for the failed SQL
```sql
EXPLAIN SQL
```

**Comment by winfys** [comment]
I in another starkrocks cluster, check the same data to perform successfully, but there is another problem, 300 g of parquet file, hive is a partition table, do not specify a partition queries, be to hang out, how can I optimize
be : 3 node   24core * 88g

**Comment by gengjun-git** [comment]
ping @kangkaisen @dirtysalt

**Comment by winfys** [comment]
starrocks version:1.18.4

**Comment by winfys** [comment]
No valuable information is found in log
