### ISSUE TITLE
[BUG] Add new fe node failed: Can not find the key:1, fail to get journal cursor. will exit

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#7754]
### Steps to reproduce the behavior (Required)
1. Set a low jvm heap size to master node.
2. Add a new fe node, and start the node with `--helper master_node`

### Expected behavior (Required)
Add new fe node successfully.

### Real behavior (Required)
Add fe node failed.
```text
2022-06-24 14:46:42,744 WARN (main|1) [Storage.reload():118] image.4307152.part is not a validate meta file, ignore it
2022-06-24 14:46:42,744 INFO (main|1) [GlobalStateMgr.loadImage():1104] image does not exist: /home/disk1/sr/stability_master_01/fe/meta/image/image.0
2022-06-24 14:47:47,247 WARN (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.setup():212] insufficient exception, refresh and setup again
com.sleepycat.je.rep.InsufficientLogException: (JE 7.3.7) 172.26.195.72_9012_1654089311673(-1):/home/disk1/sr/stability_master_01/fe/meta/bdb INSUFFICIENT_LOG: Log files at this node are obsolete. Environment is invalid and must be closed.
        at com.sleepycat.je.rep.impl.node.RepNode.findRestoreSuppliers(RepNode.java:1629) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.queryGroupForMembership(RepNode.java:1468) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.findMaster(RepNode.java:1306) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.startup(RepNode.java:897) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.joinGroup(RepNode.java:2157) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.RepImpl.joinGroup(RepImpl.java:610) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.joinGroup(ReplicatedEnvironment.java:560) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:621) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:466) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:540) ~[je-7.3.7.jar:7.3.7]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:179) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:271) [starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.open(EditLog.java:890) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:845) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:109) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:64) [starrocks-fe.jar:?]
2022-06-24 14:54:54,665 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():427] start to close log databases
2022-06-24 14:54:54,665 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():436] close log databases end
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():439] start to close epoch database
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():448] close epoch database end
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():450] start to close replicated environment
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():460] close replicated environment end
2022-06-24 14:54:55,068 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.setup():188] add helper[172.26.195.71:9012] as ReplicationGroupAdmin
2022-06-24 14:54:55,068 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.setup():195] add self[172.26.195.72:9012] as ReplicationGroupAdmin
2022-06-24 14:54:55,082 WARN (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [GlobalStateMgr.notifyNewFETypeTransfer():1590] notify new FE type transfer: UNKNOWN
2022-06-24 14:54:55,113 WARN (RepNode 172.26.195.72_9012_1654089311673(-1)|77) [GlobalStateMgr.notifyNewFETypeTransfer():1590] notify new FE type transfer: FOLLOWER
2022-06-24 14:54:55,144 INFO (stateListener|90) [GlobalStateMgr$5.runOneCycle():1613] begin to transfer FE type from INIT to UNKNOWN
2022-06-24 14:54:55,144 INFO (stateListener|90) [GlobalStateMgr$5.runOneCycle():1694] finished to transfer FE type to UNKNOWN
2022-06-24 14:54:55,144 INFO (stateListener|90) [GlobalStateMgr$5.runOneCycle():1613] begin to transfer FE type from UNKNOWN to FOLLOWER
2022-06-24 14:54:55,148 INFO (replayer|91) [GlobalStateMgr.replayJournal():1711] replayed journal id is 0, replay to journal id is 4403970
2022-06-24 14:54:55,150 ERROR (replayer|91) [BDBJournalCursor.<init>():84] Can not find the key:1, fail to get journal cursor. will exit.

```

### StarRocks version (Required)
 - all

**Comment by gengjun-git** [comment]
2022-06-24 14:46:42,744 WARN (main|1) [Storage.reload():118] image.4307152.part is not a validate meta file, ignore it
2022-06-24 14:46:42,744 INFO (main|1) [GlobalStateMgr.loadImage():1104] image does not exist: /home/disk1/sr/stability_master_01/fe/meta/image/image.0
2022-06-24 14:47:47,247 WARN (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.setup():212] insufficient exception, refresh and setup again
com.sleepycat.je.rep.InsufficientLogException: (JE 7.3.7) 172.26.195.72_9012_1654089311673(-1):/home/disk1/sr/stability_master_01/fe/meta/bdb INSUFFICIENT_LOG: Log files at this node are obsolete. Environment is invalid and must be closed.
        at com.sleepycat.je.rep.impl.node.RepNode.findRestoreSuppliers(RepNode.java:1629) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.queryGroupForMembership(RepNode.java:1468) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.findMaster(RepNode.java:1306) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.startup(RepNode.java:897) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.joinGroup(RepNode.java:2157) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.RepImpl.joinGroup(RepImpl.java:610) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.joinGroup(ReplicatedEnvironment.java:560) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:621) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:466) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:540) ~[je-7.3.7.jar:7.3.7]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:179) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:271) [starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.open(EditLog.java:890) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:845) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:109) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:64) [starrocks-fe.jar:?]
2022-06-24 14:54:54,665 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():427] start to close log databases
2022-06-24 14:54:54,665 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():436] close log databases end
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():439] start to close epoch database
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():448] close epoch database end
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():450] start to close replicated environment
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():460] close replicated environment end
2022-06-24 14:54:55,068 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.setup():188] add helper[172.26.195.71:9012] as ReplicationGroupAdmin
2022-06-24 14:54:55,068 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.setup():195] add self[172.26.195.72:9012] as ReplicationGroupAdmin
2022-06-24 14:54:55,082 WARN (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [GlobalStateMgr.notifyNewFETypeTransfer():1590] notify new FE type transfer: UNKNOWN
2022-06-24 14:54:55,113 WARN (RepNode 172.26.195.72_9012_1654089311673(-1)|77) [GlobalStateMgr.notifyNewFETypeTransfer():1590] notify new FE type transfer: FOLLOWER
2022-06-24 14:54:55,144 INFO (stateListener|90) [GlobalStateMgr$5.runOneCycle():1613] begin to transfer FE type from INIT to UNKNOWN
2022-06-24 14:54:55,144 INFO (stateListener|90) [GlobalStateMgr$5.runOneCycle():1694] finished to transfer FE type to UNKNOWN
2022-06-24 14:54:55,144 INFO (stateListener|90) [GlobalStateMgr$5.runOneCycle():1613] begin to transfer FE type from UNKNOWN to FOLLOWER
2022-06-24 14:54:55,148 INFO (replayer|91) [GlobalStateMgr.replayJournal():1711] replayed journal id is 0, replay to journal id is 4403970
2022-06-24 14:54:55,150 ERROR (replayer|91) [BDBJournalCursor.<init>():84] Can not find the key:1, fail to get journal cursor. will exit.

**Comment by gengjun-git** [comment]
The reason is that, when get image file from master node, the process may fail, but do not throw any exception. image.4307152.part is a tmp file to download.
