### ISSUE TITLE
[BUG] fe start failed: The specified partition 0 is not in the consumed partitions

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#7775]
### Steps to reproduce the behavior (Required)
1. create routine load with kafka topic that has no new data.
2. after the routine load state changed to RUNNING, pause the routine load.
3. alter the routine load progress.

### Expected behavior (Required)
cluster is normal

### Real behavior (Required)
fe is down
```text
com.starrocks.common.DdlException: The specified partition 0 is not in the consumed partitions
        at com.starrocks.load.routineload.KafkaProgress.modifyOffset(KafkaProgress.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.load.routineload.KafkaRoutineLoadJob.modifyDataSourceProperties(KafkaRoutineLoadJob.java:530) ~[starrocks-fe.jar:?]
        at com.starrocks.load.routineload.RoutineLoadJob.modifyJob(RoutineLoadJob.java:1510) ~[starrocks-fe.jar:?]
        at com.starrocks.load.routineload.RoutineLoadManager.replayAlterRoutineLoadJob(RoutineLoadManager.java:571) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:798) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2499) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$3.runOneCycle(Catalog.java:2286) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - all

**Comment by gengjun-git** [comment]
If there is no loaded data, there will be no partition->offset info in the follower node. So the alter can be done in master node, but will fail in the follower node.
