### ISSUE TITLE
[sqlancer_branch_asan]:Unknown error,fe: StatisticsCalculator.computeCTEConsume

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#7839]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
DROP DATABASE IF EXISTS d0;
CREATE DATABASE d0;
USE d0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATETIME NULL ,c_0_1 PERCENTILE PERCENTILE_UNION NULL ,c_0_2 TINYINT REPLACE_IF_NOT_NULL NULL ,c_0_3 CHAR(21) MIN NOT NULL ,c_0_4 BOOLEAN REPLACE NULL ,c_0_5 DATETIME MAX NULL ,c_0_6 PERCENTILE PERCENTILE_UNION NOT NULL ,c_0_7 DECIMAL(16, 6)  REPLACE_IF_NOT_NULL NOT NULL ,c_0_8 LARGEINT MAX NOT NULL ,c_0_9 DATE REPLACE NOT NULL ,c_0_10 FLOAT REPLACE NOT NULL ,c_0_11 HLL HLL_UNION NOT NULL ) AGGREGATE KEY (c_0_0) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 112 day)) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATETIME NOT NULL ,c_1_1 BOOLEAN NOT NULL ,c_1_2 CHAR(1) NOT NULL ,c_1_3 LARGEINT NOT NULL ,c_1_4 VARCHAR(31) NULL ,c_1_5 SMALLINT NULL , INDEX index1_c_1_4(`c_1_4`) USING BITMAP) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 112 day)) DISTRIBUTED BY HASH (c_1_2,c_1_1,c_1_3,c_1_0) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_1_2") ;
CREATE TABLE t2 (c_2_0 DECIMAL(1, 0)  NULL ,c_2_1 DATETIME NULL ,c_2_2 DECIMAL(6, 3)  NULL ,c_2_3 VARCHAR(11) NOT NULL ) UNIQUE KEY (c_2_0,c_2_1,c_2_2) PARTITION BY RANGE(c_2_1) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 109 day)) DISTRIBUTED BY HASH (c_2_0,c_2_2) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 DATE NOT NULL,c_3_1 LARGEINT NOT NULL,c_3_2 DATETIME NOT NULL,c_3_3 VARCHAR(11) NOT NULL,c_3_4 VARCHAR(41) NOT NULL,c_3_5 BOOLEAN NOT NULL,c_3_6 TINYINT NOT NULL,c_3_7 VARCHAR(11) NOT NULL,c_3_8 VARCHAR(1) NOT NULL,c_3_9 VARCHAR(21) NOT NULL,c_3_10 VARCHAR(1) NOT NULL,c_3_11 VARCHAR(21) NOT NULL,c_3_12 VARCHAR(1) NOT NULL,c_3_13 INT NOT NULL,c_3_14 INT NOT NULL,c_3_15 BIGINT NOT NULL,c_3_16 BOOLEAN NOT NULL, INDEX index1_c_3_0(`c_3_0`) USING BITMAP, INDEX index1_c_3_4(`c_3_4`) USING BITMAP, INDEX index1_c_3_11(`c_3_11`) USING BITMAP) PRIMARY KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4,c_3_5,c_3_6,c_3_7,c_3_8,c_3_9,c_3_10,c_3_11,c_3_12,c_3_13,c_3_14,c_3_15) PARTITION BY RANGE(c_3_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 106 day)) DISTRIBUTED BY HASH (c_3_13,c_3_14,c_3_5,c_3_6,c_3_8,c_3_7,c_3_10,c_3_12,c_3_4,c_3_9,c_3_3) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_3_1") ;
CREATE MATERIALIZED VIEW v0 AS SELECT t2_14.c_2_0, t2_14.c_2_1, t2_14.c_2_2, t2_14.c_2_3 FROM t2 AS t2_14;
CREATE MATERIALIZED VIEW v0 AS SELECT t2_18.c_2_1, MAX(t2_18.c_2_0) , MAX(t2_18.c_2_2) , MAX(t2_18.c_2_3)  FROM t2 AS t2_18 GROUP BY t2_18.c_2_1 ORDER BY t2_18.c_2_1 ASC;
INSERT INTO t1 VALUES ('2010-01-16 08:00:14', false, '', -1920861343, NULL, 7);
INSERT INTO t1 VALUES ('2010-01-20 08:00:14', true, '', 1605335080, 'hi', 10);
INSERT INTO t2 VALUES (3, '2010-01-24 08:00:14', 0.397, 'Ue');
TRUNCATE TABLE t3;
```
2. SELECT
```
SELECT DISTINCT * FROM (WITH with_t_0 as (SELECT t2_26.c_2_0, t2_26.c_2_1, t2_26.c_2_2, t2_26.c_2_3 FROM t2 AS t2_26) , with_t_1 as (SELECT t0_24.c_0_0, t0_24.c_0_2, t0_24.c_0_3, t0_24.c_0_4, t0_24.c_0_5, t0_24.c_0_7, t0_24.c_0_8, t0_24.c_0_9, t0_24.c_0_10 FROM t0 AS t0_24 WHERE NULL) SELECT DISTINCT t2_26.c_2_0 FROM t2 AS t2_26, t0 AS t0_24, t3 AS t3_27, with_t_0 AS with_t_0, with_t_1 AS with_t_1 WHERE true UNION ALL SELECT DISTINCT t2_26.c_2_0 FROM t2 AS t2_26, t0 AS t0_24, t3 AS t3_27, with_t_0 AS with_t_0, with_t_1 AS with_t_1 WHERE (NOT (true)) UNION ALL SELECT DISTINCT t2_26.c_2_0 FROM t2 AS t2_26, t0 AS t0_24, t3 AS t3_27, with_t_0 AS with_t_0, with_t_1 AS with_t_1 WHERE ((true) IS NULL)) t;
```
### Fe stack
```
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:880) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeCTEConsume(StatisticsCalculator.java:1314) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalCTEConsume(StatisticsCalculator.java:1298) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalCTEConsume(StatisticsCalculator.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalCTEConsumeOperator.accept(LogicalCTEConsumeOperator.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:152) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:162) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:103) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:124) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:322) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:288) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:436) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:672) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------------+
| current_version()       |
+-------------------------+
| BRANCH-2.3-ASAN 9887c23 |
+-------------------------+
1 row in set (0.01 sec)

**Comment by Seaven** [comment]
Fixed
