### ISSUE TITLE
BE crash when dml & dql on primary table execute concurrently

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#8075]
### Steps to reproduce the behavior (Required)
1. create primary table with enable_persistent_index = true;
2. stream load with upsert mode;
3. stream load with delete mode;
4. update table set where;
5. delete from table where;
6. insert into table select from table;
7. select table
8. truncate table
BE crash when step 2-8 execute concurrently:

core:
```
Core was generated by `/home/disk2/sr/stability_master_01/be-7063d832-9520-477b-ba14-d391fc64b9b2/lib/'.
Program terminated with signal SIGSEGV, Segmentation fault.
Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#0  0x00000000024f9a73 in starrocks::stream_load::OlapTableSink::close (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0x1d1487800, state=<optimized out>, close_status=...)
    at /root/starrocks/be/src/exec/tablet_sink.cpp:937
937	/root/starrocks/be/src/exec/tablet_sink.cpp: No such file or directory.
[Current thread is 1 (Thread 0x7fd65c3f9700 (LWP 14771))]
(gdb) bt
Python Exception <type 'exceptions.ImportError'> No module named gdb.frames:
#0  0x00000000024f9a73 in starrocks::stream_load::OlapTableSink::close (this=0x1d1487800, state=<optimized out>, close_status=...)
    at /root/starrocks/be/src/exec/tablet_sink.cpp:937
#1  0x00000000020449f5 in starrocks::PlanFragmentExecutor::close (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0x7e174700) at /usr/include/c++/10.3.0/ext/atomicity.h:84
#2  0x0000000002044ac5 in starrocks::PlanFragmentExecutor::~PlanFragmentExecutor (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0x7e174700, __in_chrg=<optimized out>)
    at /root/starrocks/be/src/runtime/plan_fragment_executor.cpp:62
#3  0x0000000001fd52da in starrocks::FragmentExecState::~FragmentExecState (this=0x7e174680, __in_chrg=<optimized out>) at /root/starrocks/be/src/common/status.h:28
#4  std::_Sp_counted_ptr<starrocks::FragmentExecState*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=<optimized out>) at /usr/include/c++/10.3.0/bits/shared_ptr_base.h:380
#5  0x000000000197c49a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x1ef3804c0) at /usr/include/c++/10.3.0/ext/atomicity.h:70
#6  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0x1ef3804c0) at /usr/include/c++/10.3.0/bits/shared_ptr_base.h:151
#7  0x0000000001fcfaab in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<synthetic pointer>, __in_chrg=<optimized out>)
    at /usr/include/c++/10.3.0/x86_64-pc-linux-gnu/bits/gthr-default.h:779
#8  std::__shared_ptr<starrocks::FragmentExecState, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>)
    at /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
#9  std::shared_ptr<starrocks::FragmentExecState>::~shared_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>) at /usr/include/c++/10.3.0/bits/shared_ptr.h:121
#10 starrocks::FragmentMgr::exec_plan_fragment(starrocks::TExecPlanFragmentParams const&, std::function<void (starrocks::PlanFragmentExecutor*)> const&, std::function<void (starrocks::PlanFragmentExecutor*)> const&) (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0x9acb050, params=..., start_cb=..., cb=...) at /root/starrocks/be/src/runtime/fragment_mgr.cpp:399
#11 0x0000000001fd056e in starrocks::FragmentMgr::exec_plan_fragment(starrocks::TExecPlanFragmentParams const&, std::function<void (starrocks::PlanFragmentExecutor*)> const&) (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:

    cb=..., params=..., this=<optimized out>) at /usr/include/c++/10.3.0/new:175
#12 starrocks::FragmentMgr::exec_plan_fragment (this=<optimized out>, params=...) at /root/starrocks/be/src/runtime/fragment_mgr.cpp:386
#13 0x000000000333f1e8 in starrocks::PInternalServiceImplBase<doris::PBackendService>::_exec_plan_fragment (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
this=0x53e26920, cntl=<optimized out>)
    at /root/starrocks/be/src/runtime/exec_env.h:138
#14 0x0000000003340853 in starrocks::PInternalServiceImplBase<doris::PBackendService>::exec_plan_fragment (this=<optimized out>, cntl_base=<optimized out>,
    request=<optimized out>, response=0x1ef381460, done=<optimized out>) at /root/starrocks/be/src/service/internal_service.cpp:140
#15 0x00000000040b982e in brpc::policy::ProcessRpcRequest (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
msg_base=<optimized out>) at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/policy/baidu_rpc_protocol.cpp:496
#16 0x00000000040b0297 in brpc::ProcessInputMessage (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
void_arg=void_arg@entry=0x1153d6a80) at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/input_messenger.cpp:135
#17 0x00000000040b1143 in brpc::RunLastMessage::operator() (last_msg=0x1153d6a80, this=<synthetic pointer>)
    at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/input_messenger.cpp:141
#18 std::unique_ptr<brpc::InputMessageBase, brpc::RunLastMessage>::~unique_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>)
    at /usr/include/c++/10.3.0/bits/unique_ptr.h:361
#19 brpc::InputMessenger::OnNewMessages (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
m=0x765a6000) at /usr/include/c++/10.3.0/bits/unique_ptr.h:355
#20 0x0000000004157e0e in brpc::Socket::ProcessEvent (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
arg=0x765a6000) at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/socket.cpp:1017
#21 0x0000000004065d9f in bthread::TaskGroup::task_runner (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
skip_remained=<optimized out>) at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/task_group.cpp:296
#22 0x00000000041ee581 in bthread_make_fcontext ()
Backtrace stopped: Cannot access memory at address 0x7fd62d16d000
(gdb)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+--------------------+
| current_version()  |
+--------------------+
| 2.3.0-0629 e9bc0d7 |
+--------------------+
1 row in set (0.57 sec)
```

**Comment by sevev** [comment]
https://github.com/StarRocks/starrocks/pull/8078
