### ISSUE TITLE
[Bug] FE crashed 

### ISSUE THREAD

**Issue by aaawuanjun** [StarRocks/starrocks#8236]
# version
2.2.0

# log detail

## fe.out

- fe crash
[2022-07-04 17:03:13] this node is DETACHED

```plain text
[2022-07-04 17:03:13] this node is DETACHED
Jul 04, 2022 5:03:13 PM com.sleepycat.je.utilint.DaemonThread run
SEVERE: <DaemonThread name="Checkpointer"/> caught exception, com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) Environment must be closed, caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 7.3.8) 10.89.48.6_9010_1637547601661(4):/data/starrocks/doris-meta/bdb com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) want to read 242,587,394 but reader at 242,587,395 UNEXPECTED_STATE: Unexpected internal state, may have side effects. MasterFeederSource fetching vlsn=242,587,394 waitTime=1000 Uncaught exception in feeder thread:Thread[Feeder Output for 10.89.48.20_9010_1636627084286,5,main] Originally thrown by HA thread: MASTER 10.89.48.6_9010_1637547601661(4) UNCAUGHT_EXCEPTION: Uncaught Exception in internal thread, unable to continue. Environment is invalid and must be closed. Exiting
com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) Environment must be closed, caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 7.3.8) 10.89.48.6_9010_1637547601661(4):/data/starrocks/doris-meta/bdb com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) want to read 242,587,394 but reader at 242,587,395 UNEXPECTED_STATE: Unexpected internal state, may have side effects. MasterFeederSource fetching vlsn=242,587,394 waitTime=1000 Uncaught exception in feeder thread:Thread[Feeder Output for 10.89.48.20_9010_1636627084286,5,main] Originally thrown by HA thread: MASTER 10.89.48.6_9010_1637547601661(4) UNCAUGHT_EXCEPTION: Uncaught Exception in internal thread, unable to continue. Environment is invalid and must be closed.
    at com.sleepycat.je.EnvironmentFailureException.wrapSelf(EnvironmentFailureException.java:228)
    at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1766)
    at com.sleepycat.je.dbi.CursorImpl.checkEnv(CursorImpl.java:3813)
    at com.sleepycat.je.Cursor.checkEnv(Cursor.java:5391)
    at com.sleepycat.je.Cursor.close(Cursor.java:542)
    at com.sleepycat.je.rep.vlsn.VLSNIndex.getLTEBucketFromDatabase(VLSNIndex.java:950)
    at com.sleepycat.je.rep.vlsn.VLSNIndex.getLTEBucket(VLSNIndex.java:907)
    at com.sleepycat.je.rep.vlsn.VLSNIndex.getLTEFileNumber(VLSNIndex.java:843)
    at com.sleepycat.je.rep.impl.node.RepNode.computeReplayCostMinVLSN(RepNode.java:2837)
    at com.sleepycat.je.rep.impl.node.RepNode.getUnprotectedFileSet(RepNode.java:2648)
    at com.sleepycat.je.rep.impl.RepImpl.getUnprotectedFileSet(RepImpl.java:1861)
    at com.sleepycat.je.cleaner.Cleaner.deleteSafeToDeleteFiles(Cleaner.java:681)
    at com.sleepycat.je.cleaner.Cleaner.updateFilesAtCheckpointEnd(Cleaner.java:1011)
    at com.sleepycat.je.recovery.Checkpointer.doCheckpoint(Checkpointer.java:910)
    at com.sleepycat.je.recovery.Checkpointer.onWakeup(Checkpointer.java:559)
    at com.sleepycat.je.utilint.DaemonThread.run(DaemonThread.java:154)
    at java.lang.Thread.run(Thread.java:748)
Caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 7.3.8) 10.89.48.6_9010_1637547601661(4):/data/starrocks/doris-meta/bdb com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) want to read 242,587,394 but reader at 242,587,395 UNEXPECTED_STATE: Unexpected internal state, may have side effects. MasterFeederSource fetching vlsn=242,587,394 waitTime=1000 Uncaught exception in feeder thread:Thread[Feeder Output for 10.89.48.20_9010_1636627084286,5,main] Originally thrown by HA thread: MASTER 10.89.48.6_9010_1637547601661(4) UNCAUGHT_EXCEPTION: Uncaught Exception in internal thread, unable to continue. Environment is invalid and must be closed.
    at com.sleepycat.je.utilint.StoppableThread.handleUncaughtException(StoppableThread.java:205)
    at com.sleepycat.je.utilint.StoppableThread$UncaughtHandler.uncaughtException(StoppableThread.java:236)
    at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
Caused by: com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) want to read 242,587,394 but reader at 242,587,395 UNEXPECTED_STATE: Unexpected internal state, may have side effects. MasterFeederSource fetching vlsn=242,587,394 waitTime=1000 Uncaught exception in feeder thread:Thread[Feeder Output for 10.89.48.20_9010_1636627084286,5,main] Originally thrown by HA thread: MASTER 10.89.48.6_9010_1637547601661(4)
    at com.sleepycat.je.EnvironmentFailureException.unexpectedState(EnvironmentFailureException.java:428)
    at com.sleepycat.je.rep.stream.FeederReader.checkForPassingTarget(FeederReader.java:297)
    at com.sleepycat.je.rep.stream.FeederReader.isTargetEntry(FeederReader.java:317)
    at com.sleepycat.je.log.FileReader.readNextEntryAllowExceptions(FileReader.java:332)
    at com.sleepycat.je.log.FileReader.readNextEntry(FileReader.java:245)
    at com.sleepycat.je.rep.stream.FeederReader.scanForwards(FeederReader.java:280)
    at com.sleepycat.je.rep.stream.MasterFeederSource.getWireRecord(MasterFeederSource.java:70)
    at com.sleepycat.je.rep.impl.node.Feeder$OutputThread.writeAvailableEntries(Feeder.java:1266)
    at com.sleepycat.je.rep.impl.node.Feeder$OutputThread.run(Feeder.java:1144)
```

- 手动拉起的时间
Mon Jul 4 17:14:31 CST 2022

- you can download fe.out whole from here:
[fe.out.txt](https://github.com/StarRocks/starrocks/files/9038540/fe.out.txt)

## fe.warn.log

```plain text
2022-07-04 17:02:50,709 WARN (star rocks repository|41) [TableMetaSyncer.syncTable():31] get frontend client from pool failed
org.apache.thrift.transport.TTransportException: java.net.SocketException: Network is unreachable (connect failed)
    at org.apache.thrift.transport.TSocket.open(TSocket.java:226) ~[libthrift-0.13.0.jar:0.13.0]
    at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:131) ~[starrocks-fe.jar:?]
    at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:116) ~[starrocks-fe.jar:?]
    at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.3.jar:2.3]
    at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1036) ~[commons-pool2-2.3.jar:2.3]
    at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.3.jar:2.3]
    at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:278) ~[commons-pool2-2.3.jar:2.3]
    at com.starrocks.common.GenericPool.borrowObject(GenericPool.java:92) ~[starrocks-fe.jar:?]
    at com.starrocks.external.starrocks.TableMetaSyncer.syncTable(TableMetaSyncer.java:29) [starrocks-fe.jar:?]
    at com.starrocks.external.starrocks.StarRocksRepository.runAfterCatalogReady(StarRocksRepository.java:77) [starrocks-fe.jar:?]
    at com.starrocks.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:61) [starrocks-fe.jar:?]
    at com.starrocks.external.starrocks.StarRocksRepository.runOneCycle(StarRocksRepository.java:55) [starrocks-fe.jar:?]
    at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
Caused by: java.net.SocketException: Network is unreachable (connect failed)
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_202]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_202]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_202]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_202]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_202]
    at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_202]
    at org.apache.thrift.transport.TSocket.open(TSocket.java:221) ~[libthrift-0.13.0.jar:0.13.0]
2022-07-04 17:03:02,788 WARN (starrocks-mysql-nio-pool-3440|46241) [AcceptListener.lambda$handleEvent$1():91] connect processor exception because
java.io.IOException: Connection reset by peer
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_202]
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_202]
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_202]
    at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_202]
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_202]
    at org.xnio.nio.NioSocketConduit.read(NioSocketConduit.java:289) ~[xnio-nio-3.7.9.Final.jar:3.7.9.Final]
    at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127) ~[xnio-api-3.7.9.Final.jar:3.7.9.Final]
    at org.xnio.channels.Channels.readBlocking(Channels.java:294) ~[xnio-api-3.7.9.Final.jar:3.7.9.Final]
    at com.starrocks.mysql.nio.NMysqlChannel.readAll(NMysqlChannel.java:67) ~[starrocks-fe.jar:?]
    at com.starrocks.mysql.MysqlChannel.fetchOnePacket(MysqlChannel.java:149) ~[starrocks-fe.jar:?]
    at com.starrocks.mysql.MysqlProto.negotiate(MysqlProto.java:146) ~[starrocks-fe.jar:?]
    at com.starrocks.mysql.nio.AcceptListener.lambda$handleEvent$1(AcceptListener.java:68) ~[starrocks-fe.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
2022-07-04 17:03:18,563 ERROR (heartbeat mgr|36) [BDBEnvironment.getDatabaseNames():389] bdb environment failure exception.
com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) Environment must be closed, caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 7.3.8) 10.89.48.6_9010_1637547601661(4):/data/starrocks/doris-meta/bdb com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) want to read 242,587,394 but reader at 242,587,395 UNEXPECTED_STATE: Unexpected internal state, may have side effects. MasterFeederSource fetching vlsn=242,587,394 waitTime=1000 Uncaught exception in feeder thread:Thread[Feeder Output for 10.89.48.20_9010_1636627084286,5,main] Originally thrown by HA thread: MASTER 10.89.48.6_9010_1637547601661(4) UNCAUGHT_EXCEPTION: Uncaught Exception in internal thread, unable to continue. Environment is invalid and must be closed.
    at com.sleepycat.je.EnvironmentFailureException.wrapSelf(EnvironmentFailureException.java:228) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1766) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.dbi.EnvironmentImpl.checkOpen(EnvironmentImpl.java:1775) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.Environment.checkOpen(Environment.java:2473) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.Environment.getDatabaseNames(Environment.java:2245) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.starrocks.journal.bdbje.BDBEnvironment.getDatabaseNames(BDBEnvironment.java:375) [starrocks-fe.jar:?]
    at com.starrocks.journal.bdbje.BDBJEJournal.getMaxJournalId(BDBJEJournal.java:213) [starrocks-fe.jar:?]
    at com.starrocks.persist.EditLog.getMaxJournalId(EditLog.java:99) [starrocks-fe.jar:?]
    at com.starrocks.system.HeartbeatMgr.runAfterCatalogReady(HeartbeatMgr.java:158) [starrocks-fe.jar:?]
    at com.starrocks.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:61) [starrocks-fe.jar:?]
    at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
Caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 7.3.8) 10.89.48.6_9010_1637547601661(4):/data/starrocks/doris-meta/bdb com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) want to read 242,587,394 but reader at 242,587,395 UNEXPECTED_STATE: Unexpected internal state, may have side effects. MasterFeederSource fetching vlsn=242,587,394 waitTime=1000 Uncaught exception in feeder thread:Thread[Feeder Output for 10.89.48.20_9010_1636627084286,5,main] Originally thrown by HA thread: MASTER 10.89.48.6_9010_1637547601661(4) UNCAUGHT_EXCEPTION: Uncaught Exception in internal thread, unable to continue. Environment is invalid and must be closed.
    at com.sleepycat.je.utilint.StoppableThread.handleUncaughtException(StoppableThread.java:205) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.utilint.StoppableThread$UncaughtHandler.uncaughtException(StoppableThread.java:236) ~[starrocks-bdb-je-7.3.8.jar:?]
    at java.lang.Thread.dispatchUncaughtException(Thread.java:1959) ~[?:1.8.0_202]
Caused by: com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) want to read 242,587,394 but reader at 242,587,395 UNEXPECTED_STATE: Unexpected internal state, may have side effects. MasterFeederSource fetching vlsn=242,587,394 waitTime=1000 Uncaught exception in feeder thread:Thread[Feeder Output for 10.89.48.20_9010_1636627084286,5,main] Originally thrown by HA thread: MASTER 10.89.48.6_9010_1637547601661(4)
    at com.sleepycat.je.EnvironmentFailureException.unexpectedState(EnvironmentFailureException.java:428) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.rep.stream.FeederReader.checkForPassingTarget(FeederReader.java:297) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.rep.stream.FeederReader.isTargetEntry(FeederReader.java:317) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.log.FileReader.readNextEntryAllowExceptions(FileReader.java:332) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.log.FileReader.readNextEntry(FileReader.java:245) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.rep.stream.FeederReader.scanForwards(FeederReader.java:280) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.rep.stream.MasterFeederSource.getWireRecord(MasterFeederSource.java:70) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.rep.impl.node.Feeder$OutputThread.writeAvailableEntries(Feeder.java:1266) ~[starrocks-bdb-je-7.3.8.jar:?]
    at com.sleepycat.je.rep.impl.node.Feeder$OutputThread.run(Feeder.java:1144) ~[starrocks-bdb-je-7.3.8.jar:?]
2022-07-04 17:14:39,271 WARN (UNKNOWN 10.89.48.6_9010_1637547601661(-1)|1) [Catalog.notifyNewFETypeTransfer():2400] notify new FE type transfer: UNKNOWN
2022-07-04 17:14:39,294 WARN (RepNode 10.89.48.6_9010_1637547601661(-1)|63) [Catalog.notifyNewFETypeTransfer():2400] notify new FE type transfer: FOLLOWER
```

# fe.log

fe.log is end on 17:03, start log after 17:14

```plain text
2022-07-04 17:03:18,563 ERROR (heartbeat mgr|36) [BDBEnvironment.getDatabaseNames():389] bdb environment failure exception.
com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) Environment must be closed, caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 7.3.8) 10.89.48.6_9010_1637547601661(4):/data/starrocks/doris-meta/bdb com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) want to read 242,587,394 but reader at 242,587,395 UNEXPECTED_STATE: Unexpected internal state, may have side effects. MasterFeederSource fetching vlsn=242,587,394 waitTime=1000 Uncaught exception in feeder thread:Thread[Feeder Output for 10.89.48.20_9010_1636627084286,5,main] Originally thrown by HA thread: MASTER 10.89.48.6_9010_1637547601661(4) UNCAUGHT_EXCEPTION: Uncaught Exception in internal thread, unable to continue. Environment is invalid and must be closed.
	at com.sleepycat.je.EnvironmentFailureException.wrapSelf(EnvironmentFailureException.java:228) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1766) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.dbi.EnvironmentImpl.checkOpen(EnvironmentImpl.java:1775) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.Environment.checkOpen(Environment.java:2473) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.Environment.getDatabaseNames(Environment.java:2245) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.starrocks.journal.bdbje.BDBEnvironment.getDatabaseNames(BDBEnvironment.java:375) [starrocks-fe.jar:?]
	at com.starrocks.journal.bdbje.BDBJEJournal.getMaxJournalId(BDBJEJournal.java:213) [starrocks-fe.jar:?]
	at com.starrocks.persist.EditLog.getMaxJournalId(EditLog.java:99) [starrocks-fe.jar:?]
	at com.starrocks.system.HeartbeatMgr.runAfterCatalogReady(HeartbeatMgr.java:158) [starrocks-fe.jar:?]
	at com.starrocks.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:61) [starrocks-fe.jar:?]
	at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
Caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 7.3.8) 10.89.48.6_9010_1637547601661(4):/data/starrocks/doris-meta/bdb com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) want to read 242,587,394 but reader at 242,587,395 UNEXPECTED_STATE: Unexpected internal state, may have side effects. MasterFeederSource fetching vlsn=242,587,394 waitTime=1000 Uncaught exception in feeder thread:Thread[Feeder Output for 10.89.48.20_9010_1636627084286,5,main] Originally thrown by HA thread: MASTER 10.89.48.6_9010_1637547601661(4) UNCAUGHT_EXCEPTION: Uncaught Exception in internal thread, unable to continue. Environment is invalid and must be closed.
	at com.sleepycat.je.utilint.StoppableThread.handleUncaughtException(StoppableThread.java:205) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.utilint.StoppableThread$UncaughtHandler.uncaughtException(StoppableThread.java:236) ~[starrocks-bdb-je-7.3.8.jar:?]
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1959) ~[?:1.8.0_202]
Caused by: com.sleepycat.je.EnvironmentFailureException: (JE 7.3.8) want to read 242,587,394 but reader at 242,587,395 UNEXPECTED_STATE: Unexpected internal state, may have side effects. MasterFeederSource fetching vlsn=242,587,394 waitTime=1000 Uncaught exception in feeder thread:Thread[Feeder Output for 10.89.48.20_9010_1636627084286,5,main] Originally thrown by HA thread: MASTER 10.89.48.6_9010_1637547601661(4)
	at com.sleepycat.je.EnvironmentFailureException.unexpectedState(EnvironmentFailureException.java:428) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.rep.stream.FeederReader.checkForPassingTarget(FeederReader.java:297) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.rep.stream.FeederReader.isTargetEntry(FeederReader.java:317) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.log.FileReader.readNextEntryAllowExceptions(FileReader.java:332) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.log.FileReader.readNextEntry(FileReader.java:245) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.rep.stream.FeederReader.scanForwards(FeederReader.java:280) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.rep.stream.MasterFeederSource.getWireRecord(MasterFeederSource.java:70) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.rep.impl.node.Feeder$OutputThread.writeAvailableEntries(Feeder.java:1266) ~[starrocks-bdb-je-7.3.8.jar:?]
	at com.sleepycat.je.rep.impl.node.Feeder$OutputThread.run(Feeder.java:1144) ~[starrocks-bdb-je-7.3.8.jar:?]
2022-07-04 17:03:18,587 INFO (thrift-server-pool-5218|45535) [FrontendServiceImpl.loadTxnBegin():613] receive txn begin request, db: act_change, tbl: sl_slplacestrack_original, label: act_change-sl_slplacestrack_original_3669b4f4-d9fc-474b-b770-89b78b48f04f--1, backend: 10.89.48.29
2022-07-04 17:03:18,589 INFO (nioEventLoopGroup-3-40|139) [RestBaseAction.handleRequest():55] receive http request. url=/api/act_change/sl_weboutseeanls_original/_stream_load
2022-07-04 17:03:18,591 INFO (thrift-server-pool-5796|46219) [FrontendServiceImpl.loadTxnBegin():613] receive txn begin request, db: act_change, tbl: sl_webpagetraceless_original, label: act_change-sl_webpagetraceless_original_40d78efc-85bc-4257-9245-487267225c66--1, backend: 10.89.48.209
2022-07-04 17:03:18,592 INFO (nioEventLoopGroup-3-40|139) [LoadAction.executeWithoutPassword():99] redirect load action to destination=TNetworkAddress(hostname:10.89.48.29, port:8040), db: act_change, tbl: sl_weboutseeanls_original, label: act_change-sl_weboutseeanls_original_3376cd9b-1771-42b3-8cc0-e93b71f11100--1
2022-07-04 17:03:18,593 INFO (thrift-server-pool-4827|45108) [FrontendServiceImpl.loadTxnBegin():613] receive txn begin request, db: act_change, tbl: sl_weboutseeanls_original, label: act_change-sl_weboutseeanls_original_3376cd9b-1771-42b3-8cc0-e93b71f11100--1, backend: 10.89.48.29
2022-07-04 17:03:18,593 INFO (nioEventLoopGroup-3-41|140) [RestBaseAction.handleRequest():55] receive http request. url=/api/act_change_debug/sl_websldatareport_original/_stream_load
2022-07-04 17:03:18,594 INFO (nioEventLoopGroup-3-41|140) [LoadAction.executeWithoutPassword():99] redirect load action to destination=TNetworkAddress(hostname:10.89.48.26, port:8040), db: act_change_debug, tbl: sl_websldatareport_original, label: act_change_debug-sl_websldatareport_original_9a7ef776-3cb3-4c6a-96f1-3ead1307ce12--1
2022-07-04 17:03:18,595 INFO (thrift-server-pool-5785|46177) [FrontendServiceImpl.loadTxnBegin():613] receive txn begin request, db: act_change_debug, tbl: sl_websldatareport_original, label: act_change_debug-sl_websldatareport_original_9a7ef776-3cb3-4c6a-96f1-3ead1307ce12--1, backend: 10.89.48.26
2022-07-04 17:03:18,595 INFO (thrift-server-pool-5785|46177) [DatabaseTransactionMgr.beginTransaction():300] begin transaction: txn id 50023689 with label act_change_debug-sl_websldatareport_original_9a7ef776-3cb3-4c6a-96f1-3ead1307ce12--1 from coordinator BE: 10.89.48.26, listner id: -1
2022-07-04 17:03:18,595 INFO (thrift-server-pool-5471|45809) [FrontendServiceImpl.streamLoadPut():843] receive stream load put request. db:act_change_debug, tbl: sl_websldatareport_original, txn id: 50023689, load id: 8743b793-b4fd-f473-5313-533c0871e5a8, backend: 10.89.48.26
2022-07-04 17:03:18,596 INFO (thrift-server-pool-5471|45809) [StreamLoadPlanner.plan():159] use vectorized load: true, load job id: TUniqueId(hi:-8699908210125048717, lo:5986219847010346408)
2022-07-04 17:03:18,599 INFO (thrift-server-pool-5260|45577) [FrontendServiceImpl.loadTxnBegin():613] receive txn begin request, db: act_change, tbl: sl_websdkprotocol_original, label: act_change-sl_websdkprotocol_original_c2ad12ec-8178-47f0-a97b-155817bb0c56--1, backend: 10.89.48.26
2022-07-04 17:14:33,388 INFO (main|1) [StarRocksFE.start():101] StarRocks FE starting...
```

**Comment by aaawuanjun** [comment]
it is becaused of je version, closed
docs: https://forum.starrocks.com/t/topic/2583/28
