### ISSUE TITLE
[Bug] NullPointerException about ResourceGroupMetricMgr

### ISSUE THREAD

**Issue by aaawuanjun** [StarRocks/starrocks#8238]
# Version
main- #6953 

# log

in fe.out

```
2022-07-04 17:14:58,561 WARN (starrocks-mysql-nio-pool-1|93) [ReadListener.lambda$handleEvent$0():63] Exception happened in one session(com.starrocks.mysql.nio.NConnectContext@3feccfce).
java.lang.NullPointerException: null
	at com.starrocks.metric.ResourceGroupMetricMgr.updateQueryLatency(ResourceGroupMetricMgr.java:63) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.auditAfterExec(ConnectProcessor.java:165) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:329) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:437) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:673) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
2022-07-04 17:14:58,613 WARN (starrocks-mysql-nio-pool-0|92) [ReadListener.lambda$handleEvent$0():63] Exception happened in one session(com.starrocks.mysql.nio.NConnectContext@72495e71).
java.lang.NullPointerException: null
	at com.starrocks.metric.ResourceGroupMetricMgr.updateQueryLatency(ResourceGroupMetricMgr.java:63) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.auditAfterExec(ConnectProcessor.java:165) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:329) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:437) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:673) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
2022-07-04 17:14:58,651 WARN (starrocks-mysql-nio-pool-0|92) [ReadListener.lambda$handleEvent$0():63] Exception happened in one session(com.starrocks.mysql.nio.NConnectContext@36adcfb).
java.lang.NullPointerException: null
	at com.starrocks.metric.ResourceGroupMetricMgr.updateQueryLatency(ResourceGroupMetricMgr.java:63) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.auditAfterExec(ConnectProcessor.java:165) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:329) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:437) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:673) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by aaawuanjun** [comment]
in PR: #6953 
initHistogram method solved this exception, so close this issue.
main branch code will not appear this exception.
