### ISSUE TITLE
SQL error for collecting statistics

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#8278]
### Steps to reproduce the behavior (Required)
```
mysql> CREATE ANALYZE FULL ALL;
ERROR 1064 (HY000): Unknown error
mysql> CREATE ANALYZE FULL ALL  PROPERTIES(     "update_interval_sec" = "43200",     "collect_interval_sec" = "3600" );
ERROR 1064 (HY000): Property 'collect_interval_sec' is not valid
```

### Expected behavior (Required)
analyze success

### Real behavior (Required)
```
2022-07-05 14:13:17,951 WARN (starrocks-mysql-nio-pool-8|4938) [StmtExecutor.execute():485] execute Exception, sql CREATE ANALYZE FULL ALL
java.lang.NullPointerException: null
	at com.starrocks.sql.analyzer.PrivilegeChecker.checkTblPriv(PrivilegeChecker.java:68) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.PrivilegeChecker$PrivilegeCheckerVisitor.visitCreateAnalyzeJobStatement(PrivilegeChecker.java:422) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.PrivilegeChecker$PrivilegeCheckerVisitor.visitCreateAnalyzeJobStatement(PrivilegeChecker.java:90) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.CreateAnalyzeJobStmt.accept(CreateAnalyzeJobStmt.java:86) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:90) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.PrivilegeChecker$PrivilegeCheckerVisitor.check(PrivilegeChecker.java:92) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.PrivilegeChecker.check(PrivilegeChecker.java:62) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:44) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:335) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:277) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:395) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:631) [starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) [starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener$$Lambda$83/1533777363.run(Unknown Source) [starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_41]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_41]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_41]
2022-07-05 14:13:23,958 WARN (nioEventLoopGroup-5-10|439) [BaseAction.handleRequest():92] fail to process url: /variable
```
```
2022-07-05 14:13:23,958 WARN (nioEventLoopGroup-5-10|439) [BaseAction.handleRequest():92] fail to process url: /variable
java.lang.NullPointerException: null
	at com.starrocks.qe.VariableMgr.dump(VariableMgr.java:498) ~[starrocks-fe.jar:?]
	at com.starrocks.http.action.VariableAction.appendVariableInfo(VariableAction.java:71) ~[starrocks-fe.jar:?]
	at com.starrocks.http.action.VariableAction.executeGet(VariableAction.java:47) ~[starrocks-fe.jar:?]
	at com.starrocks.http.action.WebBaseAction.execute(WebBaseAction.java:133) ~[starrocks-fe.jar:?]
	at com.starrocks.http.BaseAction.handleRequest(BaseAction.java:90) [starrocks-fe.jar:?]
	at com.starrocks.http.HttpServerHandler.channelRead(HttpServerHandler.java:69) [starrocks-fe.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.61.Final.jar:4.1.61.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_41]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
MAIN-RELEASE-1793478

**Comment by wangruin** [comment]
fix by https://github.com/StarRocks/starrocks/commit/728439975aab64cc454303f4587e478545182a7d

**Comment by wangruin** [comment]
```
CREATE ANALYZE FULL ALL  PROPERTIES(     "update_interval_sec" = "43200",     "collect_interval_sec" = "3600" );
```
will be deleted and keep this cmd
```
CREATE ANALYZE FULL ALL;
```
