### ISSUE TITLE
Reading data by spark connector has an exception in 2.1.10

### ISSUE THREAD

**Issue by zhaominzy** [StarRocks/starrocks#8324]
### Steps to reproduce the behavior (Required)
1. create table.
```
CREATE TABLE `test` (
id bigint, str_col string, date_col date
) ENGINE=OLAP 
UNIQUE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 32 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```

2. read data by spark 
```
@Test
  def test2110test(): Unit = {
    val spark = SparkSession.builder().master("local[*]").getOrCreate()
    val data = spark.read.format("starrocks")
      .option("starrocks.fenodes", "xxx")
      .option("user", "xxx")
      .option("password", "xxx")
      .option("starrocks.table.identifier", "data_transform.test")
      .load()

    // query1
    data.select("id", "str_col", "date_col")
      .show()

    // query2
    data.select("str_col", "id", "date_col")
      .show()
  }
```

### Expected behavior (Required)
```
+---+-------+----------+
| id|str_col|  date_col|
+---+-------+----------+
|  1|      a|2022-07-06|
+---+-------+----------+
```

### Real behavior (Required)
The query1 work well, the query2 has an exception.
```
22/07/06 09:48:59 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1)
scala.MatchError: 1 (of class java.lang.Long)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$StringConverter$.toCatalystImpl(CatalystTypeConverters.scala:276)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$StringConverter$.toCatalystImpl(CatalystTypeConverters.scala:275)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:103)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$$anonfun$createToCatalystConverter$2.apply(CatalystTypeConverters.scala:379)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$3.apply(ExistingRDD.scala:60)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$3.apply(ExistingRDD.scala:57)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:253)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.1.10 9c477ef

**Comment by zhaominzy** [comment]
When reading data using spark-connector, the server always return data that columns order is table define. So, when query columns order is different from table define, the exception will encounter.

**Comment by zhaominzy** [comment]
By testing, the 2.2.2 also. 1.19 work well.

**Comment by wyb** [comment]
https://github.com/StarRocks/starrocks/pull/8578
https://github.com/StarRocks/starrocks/pull/9437

fixed, you can try the latest version.

**Comment by jxzdoing** [comment]
does the latest version 2.3.1 fixed it?
