### ISSUE TITLE
be crash when compaction

### ISSUE THREAD

**Issue by aaawuanjun** [StarRocks/starrocks#8723]
### env

version: 2.2.0
3fe+5be

### log

- be.out

```plain text
*** Aborted at 1657852729 (unix time) try "date -d @1657852729" if you are using GNU date ***
PC: @          0x1964db8 std::_Hashtable<>::find()
*** SIGSEGV (@0x0) received by PID 50090 (TID 0x7f25ccab9700) from PID 0; stack trace: ***
    @          0x3caa7b2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f26725b8e9b os::Linux::chained_handler()
    @     0x7f26725bda5d JVM_handle_linux_signal
    @     0x7f26725b0858 signalHandler()
    @     0x7f2671a985d0 (unknown)
    @          0x1964db8 std::_Hashtable<>::find()
    @          0x195b638 starrocks::Tablet::rowset_with_max_version()
    @          0x195b6c5 starrocks::Tablet::can_do_compaction()
    @          0x196b02f starrocks::TabletManager::find_best_tablet_to_compaction()
    @          0x194780b starrocks::StorageEngine::_perform_cumulative_compaction()
    @          0x1933f0e starrocks::StorageEngine::_cumulative_compaction_thread_callback()
    @          0x56e3590 execute_native_thread_routine
    @     0x7f2671a90dd5 start_thread
    @     0x7f26710abead __clone
    @                0x0 (unknown)
start time: Fri Jul 15 10:40:03 CST 2022
[wuanjun@centos logs]$ date -d @1657852729
2022年 07月 15日 星期五 10:38:49 CST
```

core dump time: 2022年 07月 15日 星期五 10:38:49 CST
restart time: Fri Jul 15 10:40:03 CST 2022

- gdb info

``` plain text
(gdb) bt
Python Exception <type 'exceptions.ImportError'> No module named gdb.frames:
#0  0x0000000001964db8 in std::_Hashtable<starrocks::Version, std::pair<starrocks::Version const, std::shared_ptr<starrocks::Rowset> >, std::allocator<std::pair<starrocks::Version const, std::shared_ptr<starrocks::Rowset> > >, std::__detail::_Select1st, std::equal_to<starrocks::Version>, starrocks::HashOfVersion, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node (__code=7457326326837984235, __k=..., __bkt=2, this=0x2295a518) at /usr/include/c++/10.3.0/bits/hashtable_policy.h:433
#1  std::_Hashtable<starrocks::Version, std::pair<starrocks::Version const, std::shared_ptr<starrocks::Rowset> >, std::allocator<std::pair<starrocks::Version const, std::shared_ptr<starrocks::Rowset> > >, std::__detail::_Select1st, std::equal_to<starrocks::Version>, starrocks::HashOfVersion, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_node (__c=7457326326837984235, __key=..., __bkt=2, this=0x2295a518) at /usr/include/c++/10.3.0/bits/hashtable.h:693
#2  std::_Hashtable<starrocks::Version, std::pair<starrocks::Version const, std::shared_ptr<starrocks::Rowset> >, std::allocator<std::pair<starrocks::Version const, std::shared_ptr<starrocks::Rowset> > >, std::__detail::_Select1st, std::equal_to<starrocks::Version>, starrocks::HashOfVersion, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find (this=0x2295a518, __k=...) at /usr/include/c++/10.3.0/bits/hashtable.h:1470
#3  0x000000000195b638 in std::unordered_map<starrocks::Version, std::shared_ptr<starrocks::Rowset>, starrocks::HashOfVersion, std::equal_to<starrocks::Version>, std::allocator<std::pair<starrocks::Version const, std::shared_ptr<starrocks::Rowset> > > >::find (__x=..., this=0x2295a518) at /data1/compile/starrocks-2.1/xxxxxx/starrocks-inner-version/be/src/storage/tablet.cpp:306
#4  starrocks::Tablet::rowset_with_max_version (this=0x2295a300) at /data1/compile/starrocks-2.1/xxxxxx/starrocks-inner-version/be/src/storage/tablet.cpp:306
#5  0x000000000195b6c5 in starrocks::Tablet::can_do_compaction (this=this@entry=0x2295a300) at /data1/compile/starrocks-2.1/xxxxxx/starrocks-inner-version/be/src/storage/tablet.cpp:606
#6  0x000000000196b02f in starrocks::TabletManager::find_best_tablet_to_compaction (this=<optimized out>, compaction_type=compaction_type@entry=starrocks::CUMULATIVE_COMPACTION,
    data_dir=data_dir@entry=0x91bc700) at /data1/compile/starrocks-2.1/xxxxxx/starrocks-inner-version/be/src/common/status.h:118
#7  0x000000000194780b in starrocks::StorageEngine::_perform_cumulative_compaction (this=this@entry=0x8accdc0, data_dir=data_dir@entry=0x91bc700)
    at /data1/compile/starrocks-2.1/xxxxxx/starrocks-inner-version/be/src/storage/storage_engine.cpp:577
#8  0x0000000001933f0e in starrocks::StorageEngine::_cumulative_compaction_thread_callback (this=0x8accdc0, arg=<optimized out>, data_dir=0x91bc700)
    at /data1/compile/starrocks-2.1/xxxxxx/starrocks-inner-version/be/src/storage/olap_server.cpp:310
#9  0x00000000056e3590 in std::execute_native_thread_routine (__p=0xa2b5380) at ../../../.././libstdc++-v3/src/c++11/thread.cc:80
#10 0x00007f2671a90dd5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f26710abead in clone () from /lib64/libc.so.6
```

**Comment by Toms1999** [comment]
let me see see
