### ISSUE TITLE
be crash when memcpy_inlined

### ISSUE THREAD

**Issue by aaawuanjun** [StarRocks/starrocks#8888]
### basic info
3fe+5be
version:2.2.0

### log

- gdb

```shell
#0  0x00007fcd8b9e76e6 in __memcpy_ssse3_back () from /lib64/libc.so.6
#1  0x0000000001922bb0 in strings::memcpy_inlined (size=<optimized out>, src=<optimized out>, dst=<optimized out>) at /data1/compile/starrocks-2.1/xxxxxxx/starrocks-inner-version/be/src/gutil/strings/fastmem.h:156
#2  starrocks::vectorized::BinaryColumn::append_selective (this=<optimized out>, src=..., indexes=<optimized out>, from=<optimized out>, size=<optimized out>) at /data1/compile/starrocks-2.1/xxxxxxx/starrocks-inner-version/be/src/column/binary_column.cpp:69
#3  0x00000000022da2d8 in starrocks::vectorized::NullableColumn::append_selective (this=0x10f660830, src=..., indexes=0x97fb51000, from=0, size=5000) at /data1/compile/starrocks-2.1/xxxxxxx/starrocks-inner-version/be/src/column/nullable_column.cpp:81
#4  0x0000000001d9ceff in starrocks::vectorized::MemTable::insert (this=0x610fe780, chunk=..., indexes=indexes@entry=0x97fb51000, from=from@entry=0, size=size@entry=5000) at /data1/compile/starrocks-2.1/xxxxxxx/starrocks-inner-version/be/src/storage/vectorized/memtable.cpp:96
#5  0x0000000003175c16 in starrocks::vectorized::DeltaWriter::write (this=this@entry=0x2dae48c00, chunk=..., indexes=<optimized out>, from=from@entry=0, size=5000) at /data1/compile/starrocks-2.1/xxxxxxx/starrocks-inner-version/be/src/storage/vectorized/delta_writer.cpp:200
#6  0x000000000316772b in starrocks::vectorized::AsyncDeltaWriter::_execute (meta=0x2dae48c00, iter=...) at /var/local/thirdparty/installed/include/bthread/execution_queue.h:61
#7  0x0000000003d7afcc in bthread::ExecutionQueueBase::_execute (this=0x13a6a3700, head=<optimized out>, high_priority=<optimized out>, niterated=0x0) at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/execution_queue.cpp:272
#8  0x0000000003d7bd98 in bthread::ExecutionQueueBase::_execute_tasks (arg=<optimized out>) at /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/execution_queue.cpp:151
#9  0x0000000001f5b959 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/10.3.0/bits/std_function.h:248
#10 starrocks::FunctionRunnable::run (this=<optimized out>) at /data1/compile/starrocks-2.1/xxxxxxx/starrocks-inner-version/be/src/util/threadpool.cpp:45
#11 starrocks::ThreadPool::dispatch_thread (this=0xa6f5180) at /data1/compile/starrocks-2.1/xxxxxxx/starrocks-inner-version/be/src/util/threadpool.cpp:514
#12 0x0000000001f5750a in std::function<void ()>::operator()() const (this=0x269376d8) at /usr/include/c++/10.3.0/bits/std_function.h:248
#13 starrocks::Thread::supervise_thread (arg=0x269376c0) at /data1/compile/starrocks-2.1/xxxxxxx/starrocks-inner-version/be/src/util/thread.cpp:327
#14 0x00007fcd8c374dd5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007fcd8b98fead in clone () from /lib64/libc.so.6
```

- be.out

```shell
tcmalloc: large alloc 4294975488 bytes == 0x15155ea000 @  0x5487c5f 0x57194dc 0x1eba748 0x5669755 0x1922eb8 0x22da2d8 0x1d9ceff 0x3175c16 0x316772b 0x3d7afcc 0x3d7bd98 0x1f5b959 0x1f5750a 0x7fcd8c374dd5
*** Aborted at 1658153802 (unix time) try "date -d @1658153802" if you are using GNU date ***
PC: @     0x7fcd8b9e76e6 __memcpy_ssse3_back
*** SIGSEGV (@0x3038f0) received by PID 22791 (TID 0x7fcd7d5e5700) from PID 3160304; stack trace: ***
@          0x3caa7b2 google::(anonymous namespace)::FailureSignalHandler()
@     0x7fcd8ce9ce9b os::Linux::chained_handler()
@     0x7fcd8cea1a5d JVM_handle_linux_signal
@     0x7fcd8ce94858 signalHandler()
@     0x7fcd8c37c5d0 (unknown)
@     0x7fcd8b9e76e6 __memcpy_ssse3_back
@          0x1922bb0 starrocks::vectorized::BinaryColumn::append_selective()
@          0x22da2d8 starrocks::vectorized::NullableColumn::append_selective()
@          0x1d9ceff starrocks::vectorized::MemTable::insert()
@          0x3175c16 starrocks::vectorized::DeltaWriter::write()
@          0x316772b starrocks::vectorized::AsyncDeltaWriter::_execute()
@          0x3d7afcc bthread::ExecutionQueueBase::_execute()
@          0x3d7bd98 bthread::ExecutionQueueBase::_execute_tasks()
@          0x1f5b959 starrocks::ThreadPool::dispatch_thread()
@          0x1f5750a starrocks::Thread::supervise_thread()
@     0x7fcd8c374dd5 start_thread
@     0x7fcd8b98fead __clone
@                0x0 (unknown)
start time: Mon Jul 18 22:18:03 CST 2022
```

- core timestamp

```shell
[root@centos logs]$ date -d @1658153802
2022年 07月 18日 星期一 22:16:42 CST
```

- large alloc信息

```shell
[root@centos logs]# addr2line -e /data/soft/starrocks/app/be/lib/starrocks_be 0x15155ea000 @  0x5487c5f 0x57194dc 0x1eba748 0x5669755 0x1922eb8 0x22da2d8 0x1d9ceff 0x3175c16 0x316772b 0x3d7afcc 0x3d7bd98 0x1f5b959 0x1f5750a 0x7fcd8c374dd5
??:0
??:0
/var/local/thirdparty/src/gperftools-gperftools-2.7/src/tcmalloc.cc:1338
/var/local/thirdparty/src/gperftools-gperftools-2.7/src/tcmalloc.cc:1357
/data1/compile/starrocks-2.1/xxx/starrocks-inner-version/be/src/service/mem_hook.cpp:232
/var/local/gcc/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/../../.././libstdc++-v3/libsupc++/new_op.cc:50
/usr/include/c++/10.3.0/bits/stl_vector.h:1169
/data1/compile/starrocks-2.1/xxx/starrocks-inner-version/be/src/column/nullable_column.cpp:82
/data1/compile/starrocks-2.1/xxx/starrocks-inner-version/be/src/storage/vectorized/memtable.cpp:93
/data1/compile/starrocks-2.1/xxx/starrocks-inner-version/be/src/storage/vectorized/delta_writer.cpp:201
/data1/compile/starrocks-2.1/xxx/starrocks-inner-version/be/src/common/status.h:36
/var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/execution_queue.cpp:272
/var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/execution_queue.cpp:151
/usr/include/c++/10.3.0/bits/shared_ptr_base.h:732
/usr/include/pthread.h:555
??:0
```

**Comment by trueeyu** [comment]
update to the latest version of 2.2.2, may be already fixed. https://github.com/StarRocks/starrocks/pull/7316
