### ISSUE TITLE
Too much writing causes follower `FE`  to fall behind.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#9278]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Expected behavior (Required)
execute 'show backends;' correctly.
### Real behavior (Required)
```
2022-07-27 14:35:57,210 WARN (starrocks-mysql-nio-pool-196|811) [ReadListener.lambda$handleEvent$0():63] Exception happened in one session(co
m.starrocks.mysql.nio.NConnectContext@3f252729).
java.io.IOException: Error happened when receiving packet.
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:621) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2022-07-27 14:35:57,484 WARN (starrocks-mysql-nio-pool-196|811) [StmtExecutor.execute():498] execute Exception, sql show backends
org.apache.thrift.transport.TTransportException: Cannot open null host.
        at org.apache.thrift.transport.TSocket.open(TSocket.java:210) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:116) ~[starrocks-fe.jar:?]
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.4.2.jar:2
.4.2]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1041) ~[commons-pool2-2.4.2.jar:2.4.2]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:357) ~[commons-pool2-2.4.2.jar:2.4.2
]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:279) ~[commons-pool2-2.4.2.jar:2.4.2
]
        at com.starrocks.common.GenericPool.borrowObject(GenericPool.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.rpc.FrontendServiceProxy.call(FrontendServiceProxy.java:20) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.LeaderOpExecutor.forward(LeaderOpExecutor.java:142) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.LeaderOpExecutor.execute(LeaderOpExecutor.java:75) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.forwardToLeader(StmtExecutor.java:590) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:376) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:279) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:392) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:630) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
```
mysql> show backends;
ERROR 1064 (HY000): Cannot open null host.
mysql> show frontends;
ERROR 1064 (HY000): Cannot open null host.
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 0f21f36 |
+----------------------+
1 row in set (0.00 sec)
```

**Comment by yongbingwang** [comment]
The host has a problem because I/O is full, so it cannot be forwarded to the host.
