### ISSUE TITLE
[BUG] FE start failed when replay update replica log

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#9387]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
```
2022-07-29 16:00:24,946 INFO (stateListener|74) [CatalogRecycleBin.recycleDatabase():123] recycle db[13201425-default_cluster:n3]
2022-07-29 16:00:24,946 INFO (stateListener|74) [LocalMetastore.replayDropDb():558] finish replay drop db, name: default_cluster:n3, id: 13201425
2022-07-29 16:00:24,946 INFO (stateListener|74) [LocalMetastore.replayCreateDb():375] finish replay create db, name: default_cluster:n3, id: 13201586
2022-07-29 16:00:24,947 INFO (stateListener|74) [EditLog.loadJournal():188] Begin to unprotect create table. db = default_cluster:n3 table = 13201598
2022-07-29 16:00:24,948 INFO (stateListener|74) [EditLog.loadJournal():188] Begin to unprotect create table. db = default_cluster:n3 table = 13201749
2022-07-29 16:00:24,948 INFO (stateListener|74) [EditLog.loadJournal():188] Begin to unprotect create table. db = default_cluster:n3 table = 13201975
2022-07-29 16:00:24,949 INFO (stateListener|74) [DatabaseTransactionMgr.replayUpsertTransactionState():1537] remove expired transaction: TransactionState. txn_id: 527681, label: delete_1e11cb33-0abe-11ed-b3ed-00163e137b38, db id: 13201586, table id list: 13201749, callback id: -1, coordinator: FE: 172.26.92.200, transaction status: ABORTED, error replicas num: 0, replica ids: , prepare time: 1658604718291, commit time: -1, finish time: 1658604718299, publish cost: 1658604718300ms, reason: all partitions have no load data
2022-07-29 16:00:24,949 INFO (stateListener|74) [DatabaseTransactionMgr.replayUpsertTransactionState():1537] remove expired transaction: TransactionState. txn_id: 525202, label: insert_6bf072a4-0abd-11ed-b3ed-00163e137b38, db id: 13145953, table id list: 13145996, callback id: -1, coordinator: FE: 172.26.92.200, transaction status: ABORTED, error replicas num: 0, replica ids: , prepare time: 1658604419438, commit time: -1, finish time: 1658604719458, publish cost: 1658604719459ms, reason: timeout by txn manager
2022-07-29 16:00:24,950 INFO (stateListener|74) [DatabaseTransactionMgr.replayUpsertTransactionState():1537] remove expired transaction: TransactionState. txn_id: 525208, label: insert_6c15fb45-0abd-11ed-b3ed-00163e137b38, db id: 13145953, table id list: 13145996, callback id: -1, coordinator: FE: 172.26.92.200, transaction status: ABORTED, error replicas num: 0, replica ids: , prepare time: 1658604419684, commit time: -1, finish time: 1658604723408, publish cost: 1658604723409ms, reason: timeout by txn manager
2022-07-29 16:00:24,951 INFO (stateListener|74) [DatabaseTransactionMgr.replayUpsertTransactionState():1537] remove expired transaction: TransactionState. txn_id: 525204, label: insert_6c09790d-0abd-11ed-b3ed-00163e137b38, db id: 13145953, table id list: 13145996, callback id: -1, coordinator: FE: 172.26.92.200, transaction status: ABORTED, error replicas num: 0, replica ids: , prepare time: 1658604419602, commit time: -1, finish time: 1658604724278, publish cost: 1658604724279ms, reason: timeout by txn manager
2022-07-29 16:00:24,951 INFO (stateListener|74) [CatalogRecycleBin.recycleTable():149] recycle table[13201598-t0]
2022-07-29 16:00:24,951 INFO (stateListener|74) [LocalMetastore.unprotectDropTable():515] finished dropping table[t0] in db[default_cluster:n3], tableId: 13201598
2022-07-29 16:00:24,951 INFO (stateListener|74) [CatalogRecycleBin.recycleTable():149] recycle table[13201749-t1]
2022-07-29 16:00:24,951 INFO (stateListener|74) [LocalMetastore.unprotectDropTable():515] finished dropping table[t1] in db[default_cluster:n3], tableId: 13201749
2022-07-29 16:00:24,951 INFO (stateListener|74) [CatalogRecycleBin.recycleTable():149] recycle table[13201975-t2]
2022-07-29 16:00:24,951 INFO (stateListener|74) [LocalMetastore.unprotectDropTable():515] finished dropping table[t2] in db[default_cluster:n3], tableId: 13201975
2022-07-29 16:00:24,951 INFO (stateListener|74) [CatalogRecycleBin.eraseDatabaseWithSameName():305] erase database[13201425-default_cluster:n3], because db with the same name db is recycled
2022-07-29 16:00:24,951 INFO (stateListener|74) [CatalogRecycleBin.recycleDatabase():123] recycle db[13201586-default_cluster:n3]
2022-07-29 16:00:24,951 INFO (stateListener|74) [LocalMetastore.replayDropDb():558] finish replay drop db, name: default_cluster:n3, id: 13201586
2022-07-29 16:00:24,951 WARN (stateListener|74) [LocalMetastore.replayUpdateReplica():2571] db is null: 13201425
2022-07-29 16:00:24,951 ERROR (stateListener|74) [EditLog.loadJournal():877] Operation Type 45
java.lang.NullPointerException: null
        at com.starrocks.server.LocalMetastore.replayUpdateReplica(LocalMetastore.java:2572) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayUpdateReplica(GlobalStateMgr.java:2274) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:398) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1726) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.transferToMaster(GlobalStateMgr.java:916) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.access$900(GlobalStateMgr.java:259) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.runOneCycle(GlobalStateMgr.java:1648) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - all

**Comment by gengjun-git** [comment]
The sequence is below:
1. db(id: 13201425, name: n3) is dropped, and is put into the RecycleBin.
2. the tablet in db(id: 13201425, name: n3) is been repaired.
3. another db(id: 13201586, name: n3) with the same name is dropped and db (id: 13201425, name: n3) is erased from RecycleBin
4. the drop of db(id: 13201586, name: n3) is logged to bdb.
5. the repair of tablet in db(id: 13201425, name: n3) is logged to bdb.

because the log of drop db is ahead of the log of repair tablet, so it will throw npe when replaying the log of repair tablet.
