### ISSUE TITLE
[BUG] FE start throws NPE when replaying delete replica

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#9439]
### Steps to reproduce the behavior (Required)
1. CREATE a OLAP Table.
2. Truncate the table.
3. Decomission a be to trigger clone.

### Expected behavior (Required)
fe runs normally.

### Real behavior (Required)
```
2022-07-31 09:29:14,788 ERROR (stateChangeExecutor|71) [EditLog.loadJournal():937] Operation Type 43
java.lang.NullPointerException: null
        at com.starrocks.catalog.TabletInvertedIndex.deleteReplica(TabletInvertedIndex.java:457) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.LocalTablet.deleteReplicaByBackendId(LocalTablet.java:314) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.unprotectDeleteReplica(LocalMetastore.java:2785) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.replayDeleteReplica(LocalMetastore.java:2792) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayDeleteReplica(GlobalStateMgr.java:2339) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:416) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1704) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1662) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.transferToLeader(GlobalStateMgr.java:938) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.access$100(GlobalStateMgr.java:271) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$1.transferToLeader(GlobalStateMgr.java:596) [starrocks-fe.jar:?]
        at com.starrocks.ha.StateChangeExecutor.runOneCycle(StateChangeExecutor.java:86) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - main after commit 67fe9a72c5051886d6eadcd06b9d9008eee1adc9

**Comment by gengjun-git** [comment]
If the LocalTablet is deserialized from a json string, the immutableReplicas will be empty. The TruncateTableInfo is a json format log, and the follower replayed this log will cause all the tablets lost of replicas in TabletInvertedIndex. So if there is a migration on that tablet, the follower will throws NPE when replaying the deleteReplica log, because the replica that should be remove is lost in TabletInvertedIndex.
