### ISSUE TITLE
FE crash when load image and replay log

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#9648]
### Real behavior (Required)
```
fe.log.20220805-1:2022-08-05 00:36:10,227 INFO (leaderCheckpointer|265) [DatabaseTransactionMgr.replayUpsertTransactionState():1586] replay a visible transaction TransactionState. txn_id: 2350306, label: metrics_detail_1659626180277774165, db id: 4994048, table id list: 4994050, callback id: -1, coordinator: BE: 172.26.195.72, transaction status: VISIBLE, error replicas num: 1, replica ids: 50726729, prepare time: 1659626180282, commit time: 1659626230748, finish time: 1659627638775, write cost: 50466ms, publish cost: 1408027ms, total cost: 1458493ms, reason:  attachment: com.starrocks.load.loadv2.ManualLoadTxnCommitAttachment@12bf8eb5
fe.log.20220805-1-2022-08-05 00:36:10,228 ERROR (leaderCheckpointer|265) [EditLog.loadJournal():937] Operation Type 100
fe.log.20220805-1-java.lang.IllegalStateException: only can remove node with no dependency
fe.log.20220805-1-      at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[spark-dpp-1.0.0.jar:?]
fe.log.20220805-1-      at com.starrocks.transaction.TransactionGraph.remove(TransactionGraph.java:107) ~[starrocks-fe.jar:?]
fe.log.20220805-1-      at com.starrocks.transaction.DatabaseTransactionMgr.unprotectUpsertTransactionState(DatabaseTransactionMgr.java:1190) ~[starrocks-fe.jar:?]
fe.log.20220805-1-      at com.starrocks.transaction.DatabaseTransactionMgr.replayUpsertTransactionState(DatabaseTransactionMgr.java:1589) ~[starrocks-fe.jar:?]
fe.log.20220805-1-      at com.starrocks.transaction.GlobalTransactionMgr.replayUpsertTransactionState(GlobalTransactionMgr.java:553) ~[starrocks-fe.jar:?]
fe.log.20220805-1-      at com.starrocks.persist.EditLog.loadJournal(EditLog.java:597) [starrocks-fe.jar:?]
fe.log.20220805-1-      at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1691) [starrocks-fe.jar:?]
fe.log.20220805-1-      at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1658) [starrocks-fe.jar:?]
fe.log.20220805-1-      at com.starrocks.leader.Checkpoint.replayAndGenerateGlobalStateMgrImage(Checkpoint.java:202) [starrocks-fe.jar:?]
fe.log.20220805-1-      at com.starrocks.leader.Checkpoint.runAfterCatalogReady(Checkpoint.java:92) [starrocks-fe.jar:?]
fe.log.20220805-1-      at com.starrocks.common.util.LeaderDaemon.runOneCycle(LeaderDaemon.java:60) [starrocks-fe.jar:?]
fe.log.20220805-1-      at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]

```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by decster** [comment]
The reason for this bug is TXNs needs to be added to TxnGraph in commit order, but when load image, txns are created without time order, so we need to construct txngraph after all txns are built, and add them to txngraph by commit order.
