### ISSUE TITLE
unknow error when select data from different database

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#9793]
### Steps to reproduce the behavior (Required)
```
create database db1;
use db1;
create database db2;
CREATE TABLE t1 (
                                            `k1` int,
                                            `k2` int,
                                            `k3` int
                                        ) ENGINE=OLAP
                                        DUPLICATE KEY(`k1`)
                                        COMMENT "OLAP"
                                        DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE TABLE db2.t1 (
                                            `k1` int,
                                            `k2` int,
                                            `k3` int
                                        ) ENGINE=OLAP
                                        DUPLICATE KEY(`k1`)
                                        COMMENT "OLAP"
                                        DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
insert into t1 values (1,1,1);
insert into db2.t1 values (1,2,2);
SELECT t1.k1 as k1, t1.k2 as k2, t2.k1 as k3, t2.k2 as k4 FROM t1 join db2.t1 t2 on t1.k1=t2.k1;
```

### Expected behavior (Required)
```
+------+------+------+------+
| k1   | k2   | k3   | k4   |
+------+------+------+------+
|    1 |    1 |    1 |    2 |
+------+------+------+------+
```
### Real behavior (Required)
```
2022-08-09 20:49:18,601 WARN (starrocks-mysql-nio-pool-66|998) [StmtExecutor.execute():490] execute Exception, sql SELECT t1.k1 as k1, t1.k2 as k2, t2.k1 as k3, t2.k2 as k4 FROM t1 join db2.t1 t2 on t1.k1=t2.k1
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.common.util.RuntimeProfile.addCounter(RuntimeProfile.java:120) ~[starrocks-fe.jar:?]
	at com.starrocks.common.util.RuntimeProfile.mergeIsomorphicProfiles(RuntimeProfile.java:629) ~[starrocks-fe.jar:?]
	at com.starrocks.common.util.RuntimeProfile.mergeIsomorphicProfiles(RuntimeProfile.java:675) ~[starrocks-fe.jar:?]
	at com.starrocks.common.util.RuntimeProfile.mergeIsomorphicProfiles(RuntimeProfile.java:675) ~[starrocks-fe.jar:?]
	at com.starrocks.common.util.RuntimeProfile.mergeIsomorphicProfiles(RuntimeProfile.java:675) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.Coordinator.mergeIsomorphicProfiles(Coordinator.java:2272) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.initProfile(StmtExecutor.java:234) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.writeProfile(StmtExecutor.java:595) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:412) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:316) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:429) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:667) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2022-08-09 20:49:18,601 WARN (starrocks-mysql-nio-pool-66|998) [Coordinator.cancel():1332] cancel execution of query, this is outside invoke
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE d401dc8 |
+----------------------------+
```

**Comment by colorfulu** [comment]
fix by #9765
