### ISSUE TITLE
startRocks 1.19.0 can not read hive 2.2.1 external table

### ISSUE THREAD

**Issue by lucasaytt** [StarRocks/starrocks#991]
com.google.common.util.concurrent.ExecutionError: java.lang.AbstractMethodError: org.apache.thrift.transport.TTransport.checkReadBytesAvailable(J)V
 at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[spark-dpp-1.0.0.jar:?]
 at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[spark-dpp-1.0.0.jar:?]
 at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[spark-dpp-1.0.0.jar:?]
 at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[spark-dpp-1.0.0.jar:?]
 at com.starrocks.external.hive.HiveMetaCache.getPartitionKeys(HiveMetaCache.java:153) ~[starrocks-fe.jar:?]
 at com.starrocks.external.hive.HiveRepository.getPartitionKeys(HiveRepository.java:106) ~[starrocks-fe.jar:?]
 at com.starrocks.catalog.HiveTable.getPartitionKeys(HiveTable.java:150) ~[starrocks-fe.jar:?]
 at com.starrocks.sql.optimizer.rule.transformation.HiveScanPartitionPruneRule.initPartitionInfo(HiveScanPartitionPruneRule.java:91) ~[starrocks-fe.jar:?]
 at com.starrocks.sql.optimizer.rule.transformation.HiveScanPartitionPruneRule.transform(HiveScanPartitionPruneRule.java:61) ~[starrocks-fe.jar:?]
 at com.starrocks.sql.optimizer.task.TopDownRewriteTask.execute(TopDownRewriteTask.java:55) ~[starrocks-fe.jar:?]
 at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:36) ~[starrocks-fe.jar:?]
 at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:112) ~[starrocks-fe.jar:?]
 at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:73) ~[starrocks-fe.jar:?]
 at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:44) ~[starrocks-fe.jar:?]
 at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:301) ~[starrocks-fe.jar:?]
 at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:244) ~[starrocks-fe.jar:?]
 at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:393) ~[starrocks-fe.jar:?]
 at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:629) ~[starrocks-fe.jar:?]
 at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$479(ReadListener.java:54) ~[starrocks-fe.jar:?]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.AbstractMethodError: org.apache.thrift.transport.TTransport.checkReadBytesAvailable(J)V
 at org.apache.thrift.protocol.TBinaryProtocol.checkStringReadLength(TBinaryProtocol.java:443) ~[libthrift-0.14.0.jar:0.14.0]
 at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:414) ~[libthrift-0.14.0.jar:0.14.0]
 at org.apache.thrift.protocol.TBinaryProtocol.readString(TBinaryProtocol.java:410) ~[libthrift-0.14.0.jar:0.14.0]
 at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:250) ~[libthrift-0.14.0.jar:0.14.0]
 at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[libthrift-0.14.0.jar:0.14.0]
 at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table(ThriftHiveMetastore.java:1993) ~[hive-apache-3.0.0-5.jar:3.0.0-4-4-g7dde337]
 at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table(ThriftHiveMetastore.java:1979) ~[hive-apache-3.0.0-5.jar:3.0.0-4-4-g7dde337]
 at com.starrocks.external.hive.HiveMetaStoreThriftClient.getTable(HiveMetaStoreThriftClient.java:588) ~[starrocks-fe.jar:?]
 at com.starrocks.external.hive.HiveMetaStoreThriftClient.getTable(HiveMetaStoreThriftClient.java:583) ~[starrocks-fe.jar:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
 at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
 at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:208) ~[hive-apache-3.0.0-5.jar:3.0.0-4-4-g7dde337]
 at com.sun.proxy.$Proxy38.getTable(Unknown Source) ~[?:?]
 at com.starrocks.external.hive.HiveMetaClient.getPartitionKeys(HiveMetaClient.java:140) ~[starrocks-fe.jar:?]
 at com.starrocks.external.hive.HiveMetaCache.loadPartitionKeys(HiveMetaCache.java:106) ~[starrocks-fe.jar:?]
 at com.starrocks.external.hive.HiveMetaCache.access$000(HiveMetaCache.java:25) ~[starrocks-fe.jar:?]
 at com.starrocks.external.hive.HiveMetaCache$1.load(HiveMetaCache.java:58) ~[starrocks-fe.jar:?]
 at com.starrocks.external.hive.HiveMetaCache$1.load(HiveMetaCache.java:55) ~[starrocks-fe.jar:?]
 at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
 at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
 at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
 at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
 at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
 ... 21 more

**Comment by gengjun-git** [comment]
Hello @lucasaytt  (陆瑞-lucas), nice to meet you on github. I'm 小鼎 of last week!

**Comment by lucasaytt** [comment]
hi,please help inform this issue



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 1, 2021 19:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [StarRocks/starrocks] startRocks 1.19.0 can not read hive 2.2.1external table (Issue #991)




 
Hello @lucasaytt  (陆瑞-lucas), nice to meet you on github. I'm 小鼎 of last week!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gengjun-git** [comment]
Can you show your hive-site.xml

**Comment by lucasaytt** [comment]
1.18.4 can work



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 1, 2021 20:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [StarRocks/starrocks] startRocks 1.19.0 can not read hive 2.2.1 external table (Issue #991)




 
Can you show your hive-site.xml
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gengjun-git** [comment]
Fixed on 1.19.1
PR: https://github.com/StarRocks/starrocks/pull/995
