### ISSUE TITLE
[BUG] FE Checkpoint failed: Exception when generate new image file... com.starrocks.cluster.Cluster.write

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#9948]
### Real behavior (Required)
```java
2022-08-12 17:24:01,162 ERROR (leaderCheckpointer|78) [Checkpoint.replayAndGenerateGlobalStateMgrImage():214] Exception when generate new image file
java.lang.IllegalStateException: 371 vs 253, fatal error, Write cluster meta failed!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.cluster.Cluster.write(Cluster.java:185) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.saveCluster(LocalMetastore.java:4034) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.saveImage(GlobalStateMgr.java:1390) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.saveImage(GlobalStateMgr.java:1360) ~[starrocks-fe.jar:?]
        at com.starrocks.leader.Checkpoint.replayAndGenerateGlobalStateMgrImage(Checkpoint.java:204) [starrocks-fe.jar:?]
        at com.starrocks.leader.Checkpoint.runAfterCatalogReady(Checkpoint.java:93) [starrocks-fe.jar:?]
        at com.starrocks.common.util.LeaderDaemon.runOneCycle(LeaderDaemon.java:60) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - main

**Comment by gengjun-git** [comment]
This is introduced by #9403, it remove the default_cluster from the code, but the db name loaded from image/log still have the default_cluster prefix.

**Comment by gengjun-git** [comment]
@zombee0 PTAL
